[FIX] web: fix Many2OneReference domain prop Steps to Reproduce: 1. Go to Sales > Products and select a product 2. Upload an image for the product 3. Go to Settings > Technical > Attachments 4. Click on one of the image attachments 5. Observe the Client Error: "Uncaught Promise > Invalid props for component 'Many2One': 'domain' is not a function"
Issue:
In Odoo 19 to 19.2 (inclusive), the `Many2One` component implements a
strict prop validation that requires the domain prop to be a function.
When clicking on an image attachment in the technical menu, the
`Many2OneReferenceField` crashes with an `OwlError`. This happens
because the field passes the domain as a static array instead of a
callable function.

Solution:
We can just update the `m2oProps` getter in
`many2one_reference_field.js` to intercept the computed properties.
Specifically, we can wrap the domain array in an arrow function if it
is not already a function. This satisfies the OWL prop validation while
also making sure that the correct domain is returned when evaluated by
the component.

opw-6563954