Cherry pick of 7814025abd80f39cb97325eb0fdc9caa64f7a14d failed
stdout:

stderr:
error: could not apply 7814025abd8... [REF] event_sale: create registrations in batch in SO confirm or registration editor
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'