Cherry pick of 7a43e459b982804c5648b2fcd5497b7ea9804c9f failed
stdout:
Auto-merging addons/account/models/partner.py
CONFLICT (content): Merge conflict in addons/account/models/partner.py

stderr:
15:34:03.422160 git.c:463               trace: built-in: git cherry-pick 7a43e459b982804c5648b2fcd5497b7ea9804c9f
error: could not apply 7a43e459b982... [IMP] account: make inheritable region base domain used to get fiscal position
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: