[FIX] account: prevent traceback when adding barcode for product
When the user tries to add a barcode without Customer Taxes,
a traceback will appear.

"Error: AttributeError: 'product.template' object has no attribute 'super'"

https://github.com/odoo/odoo/blob/42fa237296f9b1fa556ae310b3273f863420e659/addons/account/models/product.py#L146
Here, self.super is used instead of super() .
so, it will lead to the above traceback.

sentry-5766033395

closes odoo/odoo#178177

Signed-off-by: Adrien Widart (awt) <awt@odoo.com>