[FIX] crm: prevent error when clicking AI icon without a record
Currently, an error occurs when clicking the AI icon to calculate the
probability of CRM leads.

Steps to Reproduce:

 - Install the crm module.
 - Go to Leads > List View > Click "New".
 - Click on the AI (automated probability) icon.

ValueError: Expected singleton: crm.lead()

This error occurs when the user clicks on the AI icon to calculate the
probability of CRM leads. Since the record does not exist [1], the system
raises an error.

This commit will fix the above issue by not preparing tooltip data when
`resId` in the record is not available.

[1] https://github.com/odoo/odoo/blob/d3b4d1e8d35eebbc015f5ead02f249e8ae5267d8/addons/crm/models/crm_lead.py#L2763

sentry-6657175088

closes odoo/odoo#213781

X-original-commit: 2dbe4bcc473e21794f325018f46207a47c29c517
Signed-off-by: Jérémy Hennecart (jeh) <jeh@odoo.com>