Cherry pick of 0a65f360aad459e8d92c0c8d2a0be9ec5a35e8dc failed
stdout:
Auto-merging addons/mail/static/tests/gif_picker/gif_picker_tests.js
CONFLICT (content): Merge conflict in addons/mail/static/tests/gif_picker/gif_picker_tests.js

stderr:
18:03:07.726757 git.c:463               trace: built-in: git cherry-pick 0a65f360aad459e8d92c0c8d2a0be9ec5a35e8dc
error: could not apply 0a65f360aad... [FIX] mail: tests: fix "Composer GIF button should open [...]"
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: