[FIX] point_of_sale: prevent traceback while uninstalling module
When users try to uninstall the "point_of_sale", a traceback will be generated.

Error:   TypeError: uninstall_hook() missing 1 required positional argument: 'registry'

This is because the https://github.com/odoo/odoo/pull/138189 added the
unistallhook from 16, but in the forword port of this PR, it did not change
the argument list according to the new unistall hook from saas-16.2.

This commit fixes the above issue by passing a valid argument
in the unistill hook.

code reference:
https://github.com/odoo/odoo/blob/saas-16.2/addons/point_of_sale/__init__.py#L11

sentry-4586084597