Cherry pick of cdd56a13e708d08f05efb02ebddb3b275370dc5b failed
stdout:
Auto-merging odoo/addons/base/tests/test_base.py
Auto-merging odoo/addons/base/tests/test_res_config.py
Auto-merging odoo/addons/test_main_flows/tests/test_flow.py
CONFLICT (content): Merge conflict in odoo/addons/test_main_flows/tests/test_flow.py
Auto-merging odoo/addons/test_new_api/tests/test_new_fields.py
Auto-merging odoo/addons/test_read_group/tests/test_m2m_grouping.py
Auto-merging odoo/tests/common.py

stderr:
17:25:00.764538 git.c:463               trace: built-in: git cherry-pick cdd56a13e708d08f05efb02ebddb3b275370dc5b
error: could not apply cdd56a13e708... [FIX] base: Make tests demo data independent
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: