Cherry pick of d15dbb0cc4c6c3442183f923894b325e0ef57347 failed
stdout:
Auto-merging addons/web/static/src/webclient/barcode/ZXingBarcodeDetector.js
CONFLICT (add/add): Merge conflict in addons/web/static/src/webclient/barcode/ZXingBarcodeDetector.js
Auto-merging addons/web/static/src/webclient/barcode/barcode_scanner.js
CONFLICT (content): Merge conflict in addons/web/static/src/webclient/barcode/barcode_scanner.js

stderr:
15:00:49.840749 git.c:455               trace: built-in: git cherry-pick d15dbb0cc4c6c3442183f923894b325e0ef57347
error: could not apply d15dbb0cc4c... [REF] web: extract ZXingBarcodeDetector into dedicated file
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: