[FIX] mail: cannot read 'getMailboxCounter' of undefined
Before this commit, sometimes when opening Discuss app during page
loading, it throws the following error:

```
TypeError: Cannot read property 'getMailboxCounter' of undefined
```

This happens due to each thread creation in mail manager being
notifying to Discuss widget, which triggers a re-render of Discuss
sidebar. Discuss sidebar template assumes mailboxes always exist,
but that's not necessarily the case, especially during page load.

closes odoo/odoo#56972

X-original-commit: 4e4eacfcdd5052c186128f350b8769f4e097b2bd
Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>