Cherry pick of b61843640574804518aea1dcac75868d06a4191f failed
stdout:
Auto-merging addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
CONFLICT (content): Merge conflict in addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
Auto-merging addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
Auto-merging addons/website/static/tests/tours/link_tools.js

stderr:
17:00:22.707319 git.c:463               trace: built-in: git cherry-pick b61843640574804518aea1dcac75868d06a4191f
error: could not apply b61843640574... [FIX] web_editor: do not remove textless links with children or class
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: