[FIX] test_website_slides_full: change outstanding account in new company
Steps to reproduce:-
- Install `account` module.
- Invoicing > Configuration > Payment Providers
- Install `Demo` payment provider, check state `Test Mode` and
  is `Published`.
- Run `test_course_certification_employee` test case.

Error:  “Draft Payment” belongs to company “company_1_data” and “Outstanding
Account” (outstanding_account_id: 'Outstanding Receipts') belongs to another
company.

Cause:-
- When `Demo` provider is activated, `account.payment.method.line` is
  created with `payment_account_id` of company `YourCompany`, but that account
  was not changed in the test.

Solution: In `test_course_certification_employee` test, set outstanding account
of company `company_1_data` for `account.payment.method.line` with code
`Demo`.

Runbot Build Error-229953

closes odoo/odoo#220731

Signed-off-by: Hugo Poncelet (hupo) <hupo@odoo.com>