[FIX] l10n_{in,fr}_hr_holidays: prevent error in time off by employee
Currently, an error occurs when user opens Time Off per Employee Analysis.

Steps to Reproduce:
 - Install l10n_fr_hr_holidays with demo data.
 - Switch to a French company.
 - Create a time off for any employee (if none exists).
 - Go to Time Off > Reporting > By Employee.

TypeError: HrLeave._get_durations() got an unexpected keyword argument 'additional_domain'

After [this commit], _get_durations accepts an additional_domain parameter.
However, this parameter is not defined in the _get_durations method in
the French and Indian localizations. When a user opens Time Off by
Employee in the French or Indian localization, the compute method is
executed to calculate leave durations, and additional_domain is passed as
an argument [1], which raises this error [2][3].

This commit adds the additional_domain parameter to the Indian
and French localizations. In the French localization, it also passes
check_leave_type, as its value is passed internally within the method [4].

[this commit]: https://github.com/odoo/odoo/commit/1c3f5633ef87f6d9c5a6169eefd51cd42ef442d5#diff-38469def2f870bb866f971f57797dd7c21b6a95d52a8eae72f832f0eea2434f9R575

[1]: https://github.com/odoo/odoo/blob/8db5a8cf07fa9c2b677b061b5897f757cb1f7260/addons/hr_holidays/report/hr_leave_employee_report.py#L94

[2]: https://github.com/odoo/odoo/blob/80e29d864b3e54ea68d2731da4c0f2f917f5d56a/addons/l10n_in_hr_holidays/models/hr_leave.py#L218

[3]: https://github.com/odoo/odoo/blob/80e29d864b3e54ea68d2731da4c0f2f917f5d56a/addons/l10n_fr_hr_holidays/models/hr_leave.py#L112

[4]: https://github.com/odoo/odoo/blob/9d4103c061c5fbe9913fa721ea3e6d417bc89e93/addons/hr_holidays/models/hr_leave.py#L531

sentry-7213025295

closes odoo/odoo#245899

Signed-off-by: Abdelrahman Mahmoud (amah) <amah@odoo.com>