[FIX] purchase: select sellers failing on empty date
Following  #133759 - The code will fail if the purchase_order has NO
date.

This is because

max(
  po.date_order.date_order and po.date_order.date(),
  fields.Date.today()
)

will try to compare False with a date, resulting in:

closes odoo/odoo#139672

Typeerror: '>' not supported between instances of 'datetime.date' and 'bool'
Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>