[FIX] l10n_es_edi_verifactu: prevent error when opening the journal dashboard
Currently, an error occurs when the user opens the journal dashboard.

Steps to Reproduce:
 - Install l10n_es_edi_verifactu with demo data.
 - If another company does not exist, create one.
 - Switch to multi-company mode with the ES company and another company selected.
 - Open the Invoicing dashbaoad.

ValueError: Expected singleton: res.company(1, 3)

After the [recent commit] that fills the sale and purchase dashboard data,
when the user switches to multi-company mode with a Spanish company and
another company selected and opens the Invoicing journal dashboard, the
journal data is prepared and the sale and purchase dashboard data is
filled [1].
When there are journals from different companies, the journals' companies
can contain multiple records. In this case, the journals are related to two
companies, and directly accessing l10n_es_edi_verifactu_required raises
the error [2].

This commit ensures that journals can belong to multiple companies and
filters the sale journals based on the l10n_es_edi_verifactu_required field
of the corresponding company using the existing filter.

[recent commit]: https://github.com/odoo/odoo/commit/d7824bd3ca8de132b0de0abb02e3b217c6de8663

[1]: https://github.com/odoo/odoo/blob/853a1f86126b9f841e3bba5b3153dbc37ac1bffc/addons/account/models/account_journal_dashboard.py#L607

[2]: https://github.com/odoo/odoo/blob/853a1f86126b9f841e3bba5b3153dbc37ac1bffc/addons/l10n_es_edi_verifactu/models/account_journal_dashboard.py#L9

sentry-7759536436