[FIX] google_calendar: (in)appropriate detection of recurrence events
Currently, Google Calendar supports recurrent events that have no RRULE instruction. For example, those that only use RDATE, as shown in https://github.com/odoo/odoo/issues/126652#issuecomment-1757325834. However, Odoo doesn't understand that kind of recurrence rules. It only parses RRULE instructions.

This is not nice, and probably the best fix would be that Odoo understands the whole range of [RFC5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.5). However, that would require a deeper discussion. Is that a bugfix or a new feature?

So, to be practical, we can consider that, from Odoo's PoV, if an event is a recurrence but none of its recurrence instructions is an RRULE, it is not a recurrence.

See the error log of what this is fixing:

```
2023-10-11 11:28:15,938 202 ERROR odoo odoo.addons.google_calendar.models.res_users: [res.users(2,)] Calendar Synchro - Exception : Tienes que elegir al menos un d��a de la semana. !
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/google_calendar/models/res_users.py", line 91, in _sync_all_google_calendar
    user.with_user(user).sudo()._sync_google_calendar(google)
  File "/opt/odoo/auto/addons/google_calendar/models/res_users.py", line 69, in _sync_google_calendar
    synced_recurrences = self.env['calendar.recurrence']._sync_google2odoo(recurrences)
  File "/opt/odoo/auto/addons/google_calendar/models/google_sync.py", line 157, in _sync_google2odoo
    new_odoo = self.with_context(dont_notify=True)._create_from_google(new, odoo_values)
  File "/opt/odoo/auto/addons/google_calendar/models/calendar_recurrence_rule.py", line 178, in _create_from_google
    recurrence.with_context(dont_notify=True)._apply_recurrence(generic_values_creation=generic_values_creation)
  File "/opt/odoo/auto/addons/google_calendar/models/calendar_recurrence_rule.py", line 18, in _apply_recurrence
    detached_events = super()._apply_recurrence(specific_values_creation, no_send_edit,
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 225, in _apply_recurrence
    ranges = recurrence._range_calculation(event, duration)
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 421, in _range_calculation
    ranges = set(self._get_ranges(event.start, duration))
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 435, in _get_ranges
    starts = self._get_occurrences(start)
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 457, in _get_occurrences
    occurences = self._get_rrule(dtstart=dtstart.replace(tzinfo=None))
  File "/opt/odoo/auto/addons/calendar/models/calendar_recurrence.py", line 519, in _get_rrule
    raise UserError(_("You have to choose at least one day in the week"))
odoo.exceptions.UserError: Tienes que elegir al menos un día de la semana.
```

Odoo was trying to create a `calendar.recurrence` where its rrule was empty, because it was detecting some recurrence, but really none of the instructions was a RRULE.

@moduon MT-3925