[FIX] http: Unable to invalidate a session
Steps to reproduce
==================

- Login to an odoo 15 database @ localhost:8069
- Exit odoo 15
- Launch odoo 16 @ localhost:8069

```
Traceback:
  ...
  File "/home/hubert/src/16.0/odoo/odoo/http.py", line 1154, in _get_session_and_dbname
    session.logout(keep_db=False)
  File "/home/hubert/src/16.0/odoo/odoo/http.py", line 961, in logout
    self.clear()
  File "/home/hubert/.asdf/installs/python/3.10.7/lib/python3.10/_collections_abc.py", line 982, in clear
    self.popitem()
  File "/home/hubert/.asdf/installs/python/3.10.7/lib/python3.10/_collections_abc.py", line 974, in popitem
    value = self[key]
  File "/home/hubert/src/16.0/odoo/odoo/http.py", line 866, in __getitem__
    return request.geoip if request else {}
  File "/home/hubert/src/16.0/odoo/odoo/http.py", line 1225, in geoip
    if '_geoip' not in self.session:
AttributeError: 'Request' object has no attribute 'session' - - -

```

Cause of the issue
==================

Since https://github.com/odoo/odoo/pull/104573 ,
the session is bound after the session invalidation occurs.

Solution
========

Check if the session is bound before using it