[FIX] web: remove leftover token param in export
In commit adf34b9001eb34e, we remove unused token param.
These token's parameters are still a leftover of the previous cleaning.

This commit fixes the export in Xls in view form that crash with:
TypeError: index() missing 1 required positional argument: 'token'