[FIX] mail: raise UserError for missing external id on reset email template
This issue arises when a user deletes the external ID associated with an email
template, and attempts to reset the email template, resulting in an error.

Steps to produce :
- Install `mail` module.
- Now go to `External identifiers` and delete an external ID linked to an
  email template.
- Go to Settings > Technical > Email > Email Templates.
- Open an email template for which the external ID was previously deleted
- Click on `Reset template` button > Error will generated.

Error: ValueError: not enough values to unpack (expected 2, got 1)

This error occurs because it will not get external id here
https://github.com/odoo/odoo/blob/1e3e6d30a8f8ce3d490899113cab31fa465f3a8b/addons/mail/models/template_reset_mixin.py#L95
After this commit, it will raise user error if it does not find the external id.

Sentry-4510563659