[FIX] stock: prevent tuple index out of range error
Currently, an error occurs when the user clicks the "Replenish"
button after following the below steps:

- Install Inventory (stock)
- Go to Inventory > Products > Products
- Open any product > click on  "Replenish" >>> Error occur

Error: "IndexError:  tuple index out of range"

This is because at [1], code tries to access first rout ids via
index `[0]` but there are no rout ids.

This commit fixes the above issue by accessing the first route, if it exists.

[1]-https://github.com/odoo/odoo/blob/5284cb3b7661f575262d358dce884cef61a34902/addons/stock/wizard/product_replenish.py#L88

sentry-4715905728