[FIX] base: prevent singletonerror when unarchiving views
When the user tries to unarchive the multiple views,
a traceback will appear.

Steps to reproduce the error:
- Install 'website'
- Go to Settings > Technical > Views
- Open archived views > unarchive multiple views

Error: A traceback appears:
'ValueError: Expected singleton: ir.ui.view(534, 535, 537)'

https://github.com/odoo/odoo/blob/9be0c5348bfeb338bcba95b2a9c01e0d7dd14306/odoo/addons/base/models/ir_ui_view.py#L379
Here, self is used in place of view.
So it will lead to the above traceback.

sentry-5604174783

X-original-commit: 464069c3b159655dd5188843f9e536d0ac217f0a