[FIX] account_edi_ubl_cii: handle empty EndpointID
Description:
Importing a UBL file (vendor bill) fails if it contains an empty "EndpointID" node.
It assumes the node always contains text content to sanitize,but if it is empty,
it crashes with: AttributeError: 'NoneType' object has no attribute 'strip'.

Steps to reproduce:
1. Import a UBL as a bill, with an empty EndpointID node of the other party.
2. The import fails with the AttributeError.

opw-6246515

closes odoo/odoo#269028

Signed-off-by: Claire Bretton (clbr) <clbr@odoo.com>