[FIX] account: prevent value error when company is archived
Currently below error occurs when user archive the company
and run the cron job, 'Account:Post draft entries with auto_post
enabled and accounting date up to today'.

Error: `ValueError('max() iterable argument is empty')
 while evaluating 'model._autopost_draft_entries()'`

Steps to reproduce :-
- Install 'Accounting' App.
- Create a new company, add its address and switch to that company.
- Now create an invoice, add a product, change 'Auto-post' to 'At Date',
fill the dates and hit 'Save'.
- Archive the company that user created and run the cron job,
Account:Post draft entries with auto_post enabled and accounting date upto today
- The error appears in the log.

This commit solves the above issue by  adding `.with_context(active_test=False)`
to consider the archived company.
sentry-6187450960