Cherry pick of 5a5bbd8e3980f9ce6e3f5cc35eea8130cebe317c failed
stdout:
Auto-merging addons/pos_loyalty/static/src/js/Loyalty.js
CONFLICT (content): Merge conflict in addons/pos_loyalty/static/src/js/Loyalty.js

stderr:
15:07:16.766473 git.c:463               trace: built-in: git cherry-pick 5a5bbd8e3980f9ce6e3f5cc35eea8130cebe317c --strategy ort
error: could not apply 5a5bbd8e3980... [FIX] pos_loyalty: bugfix
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: