[FIX] l10n_tr: remove deprecated chart template method ref
As rewrite the whole chart template mechanism,
From here: https://github.com/odoo/odoo/commit/512574861691f425ec6a17f20fe4b586bb88a299
we need to remove chart template reference from
localization module. some of them are remaining.
so removed from Turkey, Turkey localization in migration
script otherwise we got this error:

```
File "/home/odoo/src/odoo/saas-16.3/addons/l10n_tr/migrations/1.1/end-migrate_update_taxes.py", line 2, in <module>
from odoo.addons.account.models.chart_template import update_taxes_from_templates
ImportError: cannot import name 'update_taxes_from_templates' from 'odoo.addons.account.models.chart_template'
 (/home/odoo/src/odoo/saas-16.3/addons/account/models/chart_template.py)
```

closes odoo/odoo#133411

Signed-off-by: William André (wan) <wan@odoo.com>