[FIX] google_gmail, *:  log a warning instead of error in the IAP request error
*=mircosoft_outlook

Currently the logger records an error in the logs whenever an IAP
request encounters an error.

Error: `Can not contact IAP: <!doctype html>`

Since this is a request-related error, the user receives an appropriate
message when this type of error occurs, so Therefore, it is better to log
this as a warning rather than an error.

sentry-6992264566