Cherry pick of 17b1cde060b7060018074e05c9335e4c0c943286 failed
stdout:
Auto-merging odoo/addons/base/tests/common.py
Auto-merging odoo/addons/base/tests/test_ir_actions.py
Auto-merging odoo/addons/base/tests/test_res_config.py
Auto-merging odoo/addons/base/tests/test_views.py
CONFLICT (content): Merge conflict in odoo/addons/base/tests/test_views.py
Auto-merging odoo/addons/test_http/tests/test_common.py
Auto-merging odoo/tests/common.py

stderr:
16:54:36.146646 git.c:463               trace: built-in: git cherry-pick 17b1cde060b7060018074e05c9335e4c0c943286
error: could not apply 17b1cde060b7... [FIX] base: Make tests demo data independent
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: