[FIX] pos_restaurant: refunded_orderline_id array type instead of int
To reproduce (16.1 and >):

 1. install pos_restaurant
 2. open the bar PoS (NOT a shop)
 3. choose a table
 4. sell a product & make the payment & new order
 5. choose a table (can be the same as before, it does not matter)
 6. refund
 7. select the previous order > refund
 (already a bug, it is not proposed it is empty. But we can force
 its selection by going again in the refund tab. Will create a
 dedicated task for this issue)
 8. go back to the main floor (to force sync the order)
 9. go back to the table with the hanging refund order
 10. try to pay it

=> server error:
```
bad query: INSERT INTO "pos_order_line" (..., "refunded_orderline_id", ...) VALUES (..., ARRAY[1,'Coca-Cola'], ...) RETURNING "id"
ERROR: invalid input syntax for type integer: "Coca-Cola"
LINE 1: ..., ARRAY[1,'Coca-Cola'],...
```

This happens due to this recent fix:
https://github.com/odoo/odoo/pull/116271
Adding this field in the `search_read` yield the product ID and the name
 (ORM default behavior on Many2one fields). As the PoS needs only the ID
  we take it from the tuple.
Note: the fix does target originally version 15, but the forward port
code was changed only on version 16.1 and > creating this issue.

After this commit:
Able to refund order without an errors

opw-3292121

closes odoo/odoo#120589

Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>