[FIX] mail: special mentions only on channels
Steps to reproduce:
- Go to a chatter
- Type `@everyone` in the composer
- Send the message
There is an RPC_ERROR: object has no attribute 'channel_member_ids'

Since `@everyone` is specific to the channels, this commit makes sure the
`special_mentions` param is only available in message_post params in channels.

closes odoo/odoo#173868

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>