[FIX] hr: update the value of bank_account_id to false when removing partner_id
This error occurs because when user removes a partner from the `address_home_id`
field and try to save record at that time the value of bank account number field
is not updating.

An error occurs by the following steps:
- Install hr_contract, contacts and account modules.
- Go to the contacts > Configuration > Bank Accounts.
- Create a new bank account add account number and select the account holder,
-  Save the record.
- Go to Employees > Create new employee > Provide any name.
- Go to private information page of the employee.
- In the `address_home_id` field select partner who is our account holder.
- Now bank account number field is visible > select the bank account number.
- Save the record.
- Return to `address_home_id` field and remove the previously selected partner.
- Attempt to save the record, which results in an error.

Error: ValueError: Expected singleton: res.partner()

sentry - 4284660846