[FIX] website_forum: prevent error when adding multiple new tags
Currently, an error occurs when a user tries to add multiple comma-
separated new tags to a forum post.

Steps to reproduce:

- Install the `website_forum` module.
- Go to: `Website > Configuration > Forums`, create a new forum, then
  click Go to Website.
- Click on `Start by creating a post`, enter content, and set the `Tags`
  to `_test, retour affectif rapide`.
- Click on `Post Your Question`.

Error:
ValueError: invalid literal for int() with base 10: 'retour affectif
rapide'

Root Cause:

After PR #169472, at [1], the code prepends an underscore (_) only to
the entire input string instead of each tag. When multiple tags are
entered, the backend receives a mixed list of values (e.g., ['__test',
'retour affectif rapide']), leading to an error during int() conversion
at [2].

Fix:
This commit updates the `onCreateOption` logic to prepend an underscore
to each tag in the comma-separated input,  similar to [3].

Also updated the test case at [4], to click `Create option` to save the tags.

[1]:
https://github.com/odoo/odoo/blob/afa26af132566a68ad6bf67565062bd73ddd7429/addons/website_forum/static/src/js/website_forum.js#L54-L61

[2]:
https://github.com/odoo/odoo/blob/afa26af132566a68ad6bf67565062bd73ddd7429/addons/website_forum/models/forum_forum.py#L304

[3]:
https://github.com/odoo/odoo/blob/ac93a25b216e6194895a64fe12c0d01f6833f743/addons/website_forum/static/src/js/website_forum.js#L69-L80

[4]:
https://github.com/odoo/odoo/blob/d155edfd729ab9b53f38939fe24b6d1e7b578083/addons/website_forum/static/tests/tours/website_forum_question.js#L34-L37

sentry-6761920887

closes odoo/odoo#220058

Signed-off-by: Stéphane Debauche (std) <std@odoo.com>