[FIX] pos_viva_wallet: handle error when system get bad response
When the system tries to get the verification key to configure the webhook
at [1], a JSONDecodeError occurs as the response status got '404 Not Found'.

Line 1: https://github.com/odoo/odoo/blob/a3b88c88d6d137f9b231fd7b2a71c624e905f2d2/addons/pos_viva_wallet/models/pos_payment_method.py#L85

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

To resolve this, the code has been updated to handle bad responses by using a
try-except block, which raises a logger warning if an HTTP error is encountered.

Sentry-6019053900