[FIX] hr_recruitment: set view priority
The view `hr_job_search_view` needs an xpath anchor set on the view
`view_job_filter_recruitment`. Since both views have default priority
the order they are applied depends on their ID. In a normal install
process the views are created in the right order, but there are cases
where the IDs are not on the right order.

Steps to reproduce:
1. Install hr_recruitment in 15.0
2. Remove the view pointed by view_job_filter_recruitment
3. Update to 16.0

We get an error:
```
ValueError: Element '<xpath expr="//filter[@name=&#39;my_favorite_jobs&#39;]">' cannot be located in parent view
```

closes odoo/odoo#111073

Signed-off-by: Christophe Simonis <chs@odoo.com>