Cherry pick of f4cb6c132c37d552928fdc179c6f45503aff1fb1 failed
stdout:
Auto-merging addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
CONFLICT (content): Merge conflict in addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
Auto-merging addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
CONFLICT (content): Merge conflict in addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js

stderr:
15:43:11.376648 git.c:463               trace: built-in: git cherry-pick f4cb6c132c37d552928fdc179c6f45503aff1fb1 --strategy ort
error: could not apply f4cb6c132c37... [FIX] web_editor: update link_in_selection when no selectionchange event
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: