[FIX] mrp_account:  take int values of analyticdistribution when creating work center
This traceback arises when the user tries to click on Analytic Distribution

To reproduce this issue:

1. Install 'mrp_account'
2. Open 'settings>Users&company>Groups
3. Search 'Analytic Distribution' and Give permissions to the current user
4. Open 'manufacturing>configuration>work centers'
5. Create a new record and give values to 'Analytic Distribution'
6. Try to save the record

Error:
ValueError: invalid literal for int() with base 10: '14,4'

When the user tries to create a record on workcenter with a`nalytic distribution
values.
A value error is occuring, because of getting a string value instead of integer
during int conversion.

Which leads to the traceback from here

https://github.com/odoo/odoo/blob/2eb769efff0b7b6ddd78376af9cb674a9168572b/addons/mrp_account/models/mrp_workcenter.py#L13-L16

After applying this commit will resolve the issue getting an int value instead
of string during int conversion.

sentry-4667862674