[FIX] im_livechat: no crash on closing livechat when no session
Steps to reproduce:

1. Navigate to Live chat and select a channel
2. Add a line in the Channel Rules tab
3. Select Show, Show with notification, or Open automatically
4. Add "Lead Generation Bot" (No error for Welcome Bot or Helpdesk Bot)
5. Save & Close
6. Navigate to Website and select the Live Chat button
7. Press the "x"
8. Crash

`TypeError: LivechatController.visitor_leave_session() missing 1 required positional argument: 'uuid'`

This happens because `visitor_leave_session` requires an active
livechat session, i.e. it needs an `uuid`. However, if no interaction
happens in the livechat conversation (e.g. posting a 1st message),
there's no livechat session, therefore there's no `uuid`.

This commit fixes the issue by not calling this route if there is
no active livechat session when closing the livechat.

opw-3347443

closes odoo/odoo#124378

X-original-commit: 248e4692adf495b86d298c4968bf70221109daa3
Signed-off-by: Stockbauer Matthieu (tsm) <tsm@odoo.com>
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>