[FIX] sale_stock,procurement_jit: not assign backorders
When the reservation is manual, the quantities in backorders are still
assigned automatically

To reproduce the issue:
1. In Settings, set "Reservation" to "Manually or based on automatic
scheduler"
2. Create a storable product P with an on-hand quantity equal to 3
3. Create and confirm a SO with 3 x P
4. On the associated delivery order, set the done quantity to 1 and
validate it (with backorder)
    - Note: When opening the delivery order, the reserved quantity is 0,
which is correct
5. Open the backorder

Error: the reserved quantity is 2, it should be 0

By default, when confirming a picking, if a backorder is created, the
latter is assigned by default. In case of a picking associated to a SO,
the default behavior (i.e., without the module `procurement_jit`) should
be the opposite

OPW-2703234

closes odoo/odoo#84102

Signed-off-by: Arnold Moyaux <arm@odoo.com>