[FIX] mail: prevent error while creating a thread from a file message
This error occurs when a user sends a file without a message, and
`Create Thread`.

Step to Reproduce :

- Install and open module `Discuss`.
- Open Channel and send any file from `Attach files` without a message.
- Hover over the sent file, click on `Expand`, and then click `Create Thread`

AttributeError: 'str' object has no attribute 'striptags'

This issue occurs when data is `str` instead of an HTML object.

This commit fixes the error by ensuring .striptags() is only used when the data
is in the correct format.

sentry - 6304779383

closes odoo/odoo#199796

X-original-commit: 42f1ddbd2582d150468d5e327cddd3d89aedc378
Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>