[FIX] hw_drivers: prevent error while update certificate status
Currently an error occurs when the `iot/box/update_certificate_status`
controller tries to write `ssl_certificate_end_date` as
`cert.not_valid_after_utc`.

Error: `ValueError: unconverted data remains: +00:00`

This is because when we convert `cert.not_valid_after_utc` to a string, it will
convert the UTC date as ` "2026-03-08 13:06:39+00:00"` and while the system
converts this string date with +00:00, it will throw an error.

This commit fixes the issue by using a `timezone-naive` value derived from
`cert.not_valid_after_utc`. Applying `replace(tzinfo=None)` removes the `+00:00`
timezone information and converts the datetime to a `timezone-naive` object.

sentry-7016111455

closes odoo/odoo#241592

Signed-off-by: Louis Travaux (lotr) <lotr@odoo.com>