[FIX] hr_attendance: Handle access error on overtime ruleset
Steps to reproduce:

1. Install the **Attendance** app in saas-19.2 with demo data.
2. Log in as a user who has **Administrator** rights in the Attendance app but
no access rights in the Employees app.
3. Go to **Attendance → Configuration → Overtime Rulesets**.
4. Open any overtime ruleset.

An `AccessError` is raised:

```
File "/home/odoo/src/odoo/saas-19.2/odoo/orm/models.py", line 3373,
in check_access
    raise result[1]()
 odoo.exceptions.AccessError: You are not allowed to access
'Employee Record' (hr.version) records.

This operation is allowed for the following groups:
	- Employees/Administrator
	- Employees/Officer: Manage all employees

Contact your administrator to request access if necessary.
```
Issue:

A new feature introduced an employee count stat button on
`hr.attendance.overtime.ruleset` in v19.2.
[PR]: https://github.com/odoo/odoo/pull/236555/changes

Users who have administer right in Attendance app but do not have access to
Employee records trigger an access error when opening the ruleset.

Solution:

The fix restricts the visibility of the stat button to users with the required
Employee groups, preventing the access error while keeping the feature
available for authorized users.

[Stat button]: https://github.com/odoo/odoo/blob/7c6f31d730304bca3f6c996800e76d1e40ce4adf/addons/hr_attendance/views/hr_attendance_overtime_rule_views.xml#L114

opw- 6358550
upg- 4449776

X-original-commit: de56eb6cccb8087f82da97050f7b62ca7c52369f