[ADD] partner: constraint check on email encoding
Problem:
* create a new partner: write wrongly formatted email address into the email field, for example: "Balázs <balazs@adam.hu>"
* save the partner form (it works)
* but there is a hidden error, because Odoo cannot compute the "email_formatted" field of the partner

To reproduce the error just put the email_formatted field into the form view of the res.partner:
<field name="email" position="after">
  <field name="email_formatted"/>
</field>

This will produce this error:
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 3: ordinal not in range(128)

And everytime if Odoo wants to compute this field it will throw this error.

Solution:
I created a constraint that will check if the email address is well formatted, so the user cannot create or save a partner with wrong email address.