[FIX] base/data/res_users_data.xml: For avoid unique constraint
Current behavior before PR:
This traceback raised because data is already present
in with user_id 2 because if we will install ``mail``
freshly this entry will generate due to this function
[``_find_or_create_for_user``](https://github.com/odoo/odoo/blob/3adeb31b9028bd70f0a692d9c13f96b29dc1cf87/addons/mail/models/res_users_settings.py#L27C9-L27C33)
call from [here](https://github.com/odoo/odoo/blob/fa9e4cb93f26ada5d68de4696033da4f1db2e1ab/addons/mail/models/res_users.py#L188)
with no ir_model_data entry and while updating newly
record introduce [here](https://github.com/odoo/odoo/blob/f839688c1cefc5113bbefe1aecfaef97067f6e59/odoo/addons/base/data/res_users_data.xml#L26)
in saas-17.1 it creating new entry in res_users_setting
and its voilating the unique constraint of the
[user_id](https://github.com/odoo/odoo/blob/f839688c1cefc5113bbefe1aecfaef97067f6e59/odoo/addons/base/models/res_users_settings.py#L14)

Desired behavior after PR is merged:
for prevent voilation of unique constraint  used forcecreate="0"

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.1/odoo/service/server.py", line 1286, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/registry.py", line 119, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/loading.py", line 422, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/saas-17.1/odoo/addons/base/data/res_users_data.xml:26, somewhere inside
<record id="user_admin_settings" model="res.users.settings">
            <field name="user_id" ref="base.user_admin"/>
        </record>
```
TBG-1066
upg-1311090,1311854

X-original-commit: f0101fd3bcc084d203edda4d01e9cebb2bd82454