[FIX] base: prevent key error when accessing leaf_id from self.__leaves
An error occurs when the code attempts to access `leaf_id` in `self.__leaves`,
but `leaf_id` does not exist in the dictionary .

Error: `KeyError: 35`

This might happen during installation when the `leaf_id` is not available in
`self.__leaves`.

This commit fixes the issue by accessing `leaf_id` from `self.__leaves`
only when it is present.

sentry-6925358461