Cherry pick of 75edcb3fd5ca012992f8c6828fdbaec3e2c331f7 failed
stdout:
Auto-merging addons/mrp/models/mrp_workorder.py
CONFLICT (content): Merge conflict in addons/mrp/models/mrp_workorder.py

stderr:
11:54:29.827756 git.c:455               trace: built-in: git cherry-pick 75edcb3fd5ca012992f8c6828fdbaec3e2c331f7
error: could not apply 75edcb3fd5c... [IMP] mrp: added mass start stop on workorders
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: