[FIX] account: fix corrupt PO wrapping
Currently an log error is generated when the user tries to install the
`Japanese` language after installing the `Invoicing (account)` module.

Error: `OSError: Syntax error in po file (line 1273): unescaped double quote found`

This issue is caused by a bug in Weblate that incorrectly escapes quotation
marks `(\")`. As a result, the PO file becomes corrupt because the quotation
mark that should terminate the string is improperly escaped.

This commit resolves the issue described above by manually correcting
the affected PO file.

sentry-6976676644