[FIX] account_payment: fix traceback if no acess_token when doing invoice transaction
Currently, a traceback may occur if there is no `access_token`, when
an RPC call is done for `invoice_transaction()`.

Error:-

"TypeError: PaymentPortal.invoice_transaction() missing 1 required positional argument: 'access_token'"

some context:
An empty access_token parameter is well handled,
so we can address this issue by giving it a None fallback value

sentry-5741581459