[FIX] hr_recruitment_skill: prevent ZeroDivisionError in job_total
Traceback :
```
File "/home/odoo/src/odoo/19.0/addons/hr_recruitment_skills/models/
hr_applicant.py", line 72, in _compute_matching_skill_ids
  matching_score = round(applicant_total / job_total * 100)
ZeroDivisionError: float division by zero
```

Steps to Reproduce:
- Install recruitment app.
- For any job position, select all expected skill level such that level_progress
  is 0 and no expected degree .

While calculating matching score for applicants here
https://github.com/odoo/odoo/blob/19.0/addons/hr_recruitment_skills/models/hr_applicant.py#L72
a ZeroDivisionError occurs if 'job_total' is zero.

This situation occured because in 19 version new feature to calculate applicants
matching score was introduced in
https://github.com/odoo/odoo/commit/164b55c324e63c45339088823e3d55dfe2147b61
and job_degree,applicant_degree, level_progress in skills for job and applicants
were not present in older versions making job_total as 0 causing above traceback

This commit adds a safety check to ensure the division only occurs
if 'job_total' is non-zero . and if job_total is 0 , there is no expectation
required for this position which makes matching score 100 .

closes odoo/odoo#230323

Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>