[FIX] hr_recruitment, hr_recruitment_sms: bridge module
Backport of #194647
Basically, starting from `saas~16.4` we have action window in
`hr_recruitment` which is pointing at `sms` module.

If client does this steps:
1. Install `hr_recruitment` in version 17.0
2. Uninstall the module `sms`
3. Try to upgrade db to `18.0`

We will have the issue similar to this:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1318, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 548, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/18.0/addons/hr_recruitment/views/hr_candidate_views.xml:220
Invalid model name “sms.composer” in action definition.

View error context:
'-no context-'

```

Th bridge module was intrdocued in #194647 targeting to version `saas~18.2`,
but we need it for `17.0, 18.0, saas~18.1` as you see in the example above.
This PR will only target to `17.0` and `saas~17.4`. Then we will make another patch for `18.0`
and `saas~18.1` as they have some additional change.

X-original-commit: c0f3bff835cc8dbe63d5369de43c76e83ca0018e