[FIX] sale_stock_margin: restrict to compute purchase price without product
This traceback raises when user remove the' product' while creating 'Sale Order'

To produce this issue:

1) Install 'sale_stock_margin'
2) Create a new "Sale Order" in sales
3) Give values to "customer" and click "confirm" button
4) Now in "Order Lines" click "Catalog" button
5) Add any "product" and remove it.
6) Now click back to Sale Order which created above through breadcrumb
7) Now remove the 'Product'
Note:- Make sure 'product_id' is visible in "Order lines".

Error: A traceback appears: "Expected singleton: product.product()"

On "_compute_purchase_price" method, product is referenced to
"compute average price".

See:-

https://github.com/odoo/odoo/blob/ee680a9365bba0ed4c0e5e741b3e8dce94fab9bd/addons/sale_stock_margin/models/sale_order_line.py#L10-L19

Because of user removed the 'product', it return none in self which leads to
above traceback.

sentry-4320939660

closes odoo/odoo#129067

X-original-commit: a5b04bebc80c3c483bfe2eaf6c22f47613a0f0a0
Signed-off-by: William Henrotin (whe) <whe@odoo.com>