[FIX] l10n_sa_edi: prevent error when printing the invoice
Printing an invoice for a Saudi partner raises an error.

Steps to reproduce the error:
- Install "l10n_sa_edi" module with demo data
- Switch to My Saudi Arabia Company
- Create a new Partner A > Country: Saudi Arabia > VAT Number: 311111111111113 >
  Click on + Button > Click Tax Identification Number > Save
- Create a new invoice > Customer: Partner A > Add a product > Confirm >
  Print the invoice

Traceback:
"AttributeError:
'account.edi.xml.ubl_21.zatca' object has no attribute '_l10n_sa_get_tin_from_vat'"

https://github.com/odoo/odoo/blob/2e2054d4203f6453fb35ec6037cda0e2e9033cc3/addons/l10n_sa_edi/models/zatca_ubl_mixin.py#L154-L156
In [Commit], "_l10n_sa_get_tin_from_vat()" method is called on self to retrieve
"identification_number".
however, self is an "account.edi.xml.ubl_21.zatca" record,
while "_l10n_sa_get_tin_from_vat()" is a method of "res.partner".
So, It will lead to the above traceback when printing the invoice.

Solution:
Call the "_l10n_sa_get_tin_from_vat()" method on the partner record instead of
self.

[Commit]: https://github.com/odoo/odoo/commit/227f61e2cb8582d0c3269bb0ae7256250563847a

sentry-7717905761

closes odoo/odoo#287173

Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>