[FIX] account: set amount zero while create new transaction
If user create new transaction keeping amount zero and try to add new line for
validate, traceback will appear

To reproduce the issue:
- Install 'Accounting'
- Go to 'Settings'
- From Users > Enable 'Multi Currencies'
- Go to 'Currencies' and activate 'EUR' > Save
- Now go to Accounting > Configuration > Journals
- In 'Miscellaneous Operations' select 'EUR' as the currency
- In Accounting > Journal Entries and create a journal entry
- Add two lines and change the currency to 'USD' in line then enter value in
  credit and debit
- One line entry must be '121000 Account Receivable' > Post that entry
- Go to Accounting Dashboard > Bank
- Create a new transaction with amount = 0.0 and Foreign Currency = 'EUR'
- Click 'Save and Close'
- Select the transaction and click on the journal entry you have just created
Error: A traceback appear: "ZeroDivisionError: float division by zero"

Adding the journal entries to validate in bank reconciliation which have
multi currencies in it and the amount is set zero of the transaction,
it will lead to the above traceback.

sentry-4223219496