[FIX] hw_drivers: get IoT log file instead of Internal Server Error
Before this commit:
 Using the "Download logs" button from the IoT box form view will
fail every time due to an Internal Server Error on the IoT side.
```py
File "/home/pi/odoo/odoo/tools/misc.py", line 189, in file_path
FileNotFoundError: File not found: /var/log/odoo/odoo-server.log
```
This happened due to changes introduced in:
https://github.com/odoo/odoo/pull/99658

The changes enforced to double check that the file path was in an
odoo addons (for security reasons).
However, it is generally not the case, thus the error

After this commit:
The log file is downloaded as intended

opw-3827121

closes odoo/odoo#160610

X-original-commit: a7aa4c6e58d6448556c85c393f2910490a0519f5
Signed-off-by: Loan Sens (lse) <lse@odoo.com>