[FIX] stock: action_show_details not working for virtual lines on mobile
Steps to reproduce:
1. Enable Responsive Design Mode and reload the page to enable the Mobile view
2. Create a new transfer
3. Click Add a product
4. Select a random product and click 'Save & Close'
5. Click on the line you've added
6. ValueError: not enough values to unpack (expected 1, got 0)

Before this commit:
On mobile, clicking on the `action_show_details` button on a stock move
not yet saved gives a traceback, as the button is called on an empty
recordset.

On desktop, clicking on the same button works, as the button behavior
was changed to save and open the details. However, this change only
applies to the tree view of the stock moves; on mobile, the moves are
shown in a kanban view, which does not implement this behavior.

After this commit:
The kanban view implements the same behavior as the tree view.

opw-3593371

X-original-commit: 222cbfb90162d73199171f3e7bcfbec62ca59b82