[FIX] web: fix property assignment in pivot view
Sales > Reporting > Sales
Select the measure "Customer (count)"

TypeError: Cannot add property group_operator, object is not extensible

As the object is immutable we need to workaround the assignment.
The previous fix 35967fabd54f596fa75fb2db7fbb1cfc5d7c8da9
will be moved in the `documents_spreadsheet` code

opw-2606424

X-original-commit: 865d0f5c4e9e14cbd5ed494f8c9dc75b6a82a78f