[FIX] stock_dropshipping: archive data after uninstallation
When user uninstall the module 'stock_dropshipping'. The value 'dropship' for
selection field 'Type of Operation' does not get deleted and cause error.
From version 14.0  when user uninstall the module 'stock_dropshipping', record
does not get deleted.

To reproduce the issue in sass-16.2:

- Install 'stock_dropshipping' module
- Go to 'inventory' module
- Go to 'Dropship' and click on 'NEW'
- Make sure 'Type of Operation' is 'Dropship' and save
- Uninstall 'stock_dropshipping' module.
- Go to 'Inventory' and click on 'Receipts' and remove all the filters
- Another way--> Create a new 'stock.picking' with 'Operation Type' as 'Dropship'

Error: A traceback appears: 'Wrong value for stock.picking.picking_type_code:
'dropship'

Fixed this issue by updating the code of the picking type and archiving it after
uninstallation of module using 'ondelete' function.

sentry-4167898386

Part-of: odoo/odoo#121732