[FIX] l10n_es_edi_facturae: enhance placeholder mail attachment logic for invoice EDI format Problem: Calling _get_placeholder_mail_attachments_data with extra_edis=None (default) causes error.
Fixes:
    placeholders = super()._get_placeholder_mail_attachments_data(move, invoice_edi_format=invoice_edi_format, extra_edis=extra_edis, pdf_report=pdf_report)
  File "/opt/odoo/addons/l10n_es_edi_facturae/models/account_move_send.py", line 57, in _get_placeholder_mail_attachments_data
    ('es_facturae' in extra_edis or invoice_edi_format == 'es_facturae')
TypeError: argument of type 'NoneType' is not iterable