[FIX] hr_timesheet: prevent keyerror when company is unarchived
Currently a `Keyerror` appears when the user unarchives the company.

Error: `Keyerror: 2`

Steps to reproduce above error :-
- Install `hr_timesheet` module.
- Settings > Users & Companies > Companies. create a company.
- Archive the company, now Unarchive the company.
- The error appears in the log.

The error occurs because on urachiving the company, the new company was
not found.

This commit fixes the error, if company does not exist, it still returns
 an empty dictionary.

sentry-6251348500