[FIX] sale_management: test reload template translations w/out demo data
Versions
--------
- 16.0+

Steps
-----
1. Run `test_reload_template_translations` without demo data.

Issue
-----
> AssertionError: sale_order_template_id was not found in the view

Cause
-----
The `sale_order_template_id` field requires the user to have the
`sale_management.group_sale_order_template` group, which they don't have
by default without demo data.

Solution
--------
Add the group to the current user before running the test.

opw-4260006

closes odoo/odoo#190264

X-original-commit: 086da10e946d02091242fa8cc11b836e84ae5212
Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>