[FIX] core: fix `_get_default_calendar_view`
Due to odoo/odoo#51075 it's an error to assign the `_date_name` field on
an empty recordset.

```
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1582, in _fields_view_get
    arch_etree = getattr(self, '_get_default_%s_view' % view_type)()
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1495, in _get_default_calendar_view
    self._date_name = dt
 AttributeError: 'project.phase' object attribute '_date_name' is read-only
```

Issue observed on upgrade requests 2615 and 3121.

closes odoo/odoo#73380

Signed-off-by: Christophe Simonis <chs@odoo.com>
Co-authored-by: Christophe Simonis <chs@odoo.com>