[IMP] analytic_plan: don't allow user to choose a parent's plan which
create a recursion

Problem
---------

When you have an analytics plans which is the parent of another one, you
should not be able to choose the child plan as parent of this one.

A user has the possibility to do it; when he saves, we he gets the
error: Recursion Detected.

Objective
---------

Don't show the child plans of an analytics plan to avoid the user to
choose something that raises the error.

Solution
---------

Update the domain of the field `parent_id` to exclude the analytic plans
that are the children of the current plan.

task-3414188

closes odoo/odoo#128302

Signed-off-by: Quentin De Paoli <qdp@odoo.com>