[FIX] mrp: fix inconsistency of product's on hand quantity
After this commit 784f1511 , The `float_round()` functionality is changed.
Before this commit, If the `qty_available` is 0.57:
```
In [2]: float_round(0.57,2)
Out[2]: 0.5700000000000001

After this commit:
In [2]: float_round(0.57,2)
Out[2]: 0.57
```

Now, while executing this line of code
https://github.com/odoo/odoo/blob/baea953d248471e8aef60e02c1216f77941f1951/addons/mrp/models/product.py#L244.
```
Before:
In [3]: 0.5700000000000001*100//1
Out[3]: 57.0

After:
In [3]: 0.57*100//1
Out[3]: 56.0
```

These differences leads to blocking the upgrade process.
```
Traceback (most recent call last):
File "/tmp/tmpft9eq3rf/migrations/testing.py", line 212, in test_check
self.check(value)
File "/tmp/tmpft9eq3rf/migrations/stock/tests/test_on_hand_quantity.py", line 90, in check
self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[12,[7979 chars]6, '57'], [20249, '17.06'], [20250, '1705'], [[12354 chars]'1']] != [[12,[7979 chars]6, '56'], [20249, '17.06'], [20250, '1705'], [[12354 chars]'1']]

First differing element 529:
[20246, '57']
[20246, '56']
```

upg-2096343
opw-4224012

closes odoo/odoo#185883

X-original-commit: a603ec169c10afc083ecf93f47738d8237d8dc69
Signed-off-by: William Henrotin (whe) <whe@odoo.com>