[FIX] l10n_in: fix demo data loading for non-recordset companies
Currently, an exception is raised while loading demo data because
`companies` is received as an integer id instead of a company recordset.

Error: `AttributeError: 'int' object has no attribute 'filtered'`

This commit fix the above issue by checking whether `companies`
is a  `models.BaseModel` instance and, if not, converting it to a
recordset using browse().

No Task