[ADD] l10n_gt{,_city}: move city data into separate module
Steps to reproduce:
- Create a new database.
- Install the l10n_gt module.

Error:
KeyError: 'res.city'

Root Cause:
In PR [1], the file `res.city.csv` was added in the `l10n_gt` module,
which relies on the `base_address_extended` module, but this
dependency is not declared in the manifest file.

Fix:
This commit adds a new bridge module between `l10n_gt` and
`base_address_extended`, and moves `res.city.csv` into this new
module (l10n_gt_city). This approach is chosen because modifying
dependencies in a stable version is not recommended.

[1]:
https://github.com/odoo/odoo/pull/247719