[FIX] base: prevent error when adding submenu without specifying menu item name
This error occurs when attempting to create a submenu item under a menu item.

Steps to reproduce:

 - Go to menu items.
 - Click New > In Submenus click Add a line

TypeError: unsupported operand type(s) for +: 'bool' and 'str'

This error occurs when attempting to create a submenu item under a menu item
that does not have a name. Since the menu item record has not been saved yet,
the system assigns a new ID to the menu item and sets its name to False.
When computing the complete name for the submenu item, the
menu(parent menu) item's name is False, which causes the error.

https://github.com/odoo/odoo/blob/d2ea23f252f0f8f329e2b0ff96de6ee2a14b922f/odoo/addons/base/models/ir_ui_menu.py#L56

This commit ensures that if the parent menu item record has not been saved
and its name is False, an empty string is used in its place.

sentry-6368548342

closes odoo/odoo#213560

X-original-commit: 4317cc7b40d8506a2a7cb26ba8ba82491c187b31
Signed-off-by: Raphael Collet <rco@odoo.com>