[FIX] web: context group propagated from quotations to deliveries
Steps to reproduce the bug:
- Have sale_stock installed
- In Sales > Quotations, create a new default favorite which groups by a value not present in stock picking (e.g. Incoterm)
- Reload the page
- Click a sale order with at least two deliveries
- Go back to the quotations via the breadcrumbs
- Click again the same sale order line
- Click the Delivery smart button

Bug:
Traceback:
ValueError: Invalid field 'incoterm' on model 'stock.picking'

Explanation:
The `group_by` context key is set when the list is reloaded after going to another view (in this case, the SO form). This is due to the fact that the favorites are well loaded initially, but are stored with the wrong context in RAM. After coming back to the list, the wrong context is loaded and is then propagated to another list (in this case, the SO deliveries).

opw:2346912

closes odoo/odoo#60757

Signed-off-by: backspac <backspac@users.noreply.github.com>