[FIX] web: don't do replace on boolean object
Before this commit if you have an image field on a model and you have a name_get override which returns (record.id, False) the webpage would crash.

Since there is no filename found in this case Odoo will try to do a .replace() statement on a boolean which fails and crashes the whole page:
Error to render compiling AST
AttributeError: 'bool' object has no attribute 'replace'

After this commit we will first check if there is a filename and if not we set it to ''.
This makes sure the image is loaded and the page is not crashed.
Technically you should have a <string> return for a name_get but since there is no real validation we should prevent it from crashing webpages.