[FIX] account: 'parent' use in payment method line field domain
Users in debug mode can click on a 'View' button in the list renderer
and open the specific record form view. However this may crash if the
model was not intended to be opened in a stand alone form view

Steps to reproduce:
- Go to debug mode
- Go to Accounting Dashboard
- Open Bank Journal settings
- Switch to Outgoing Payments tab
- in List menu options activate 'View Button'
- Click 'View' button
- Try to modify the 'Payment Account' field

Issue: Tracbeack will raise
```
    Error: Name 'parent' is not defined
    EvalError: Can not evaluate python expression: ((company_id and [('company_ids', 'parent_of', [company_id])] or [('company_ids', 'parent_of', '')]) + ([('deprecated', '=', False), '|', ('account_type', 'in', ('asset_current', 'liability_current')), ('id', '=', parent.default_account_id)]))
    Error: Name 'parent' is not defined
```

opw-4233216

closes odoo/odoo#189550

X-original-commit: 2642f4337dfafb2118a5acb2acc43b5d43bb4445
Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>