[FIX] website: fix traceback when opening website homepage
Currently, a traceback is occurring when the user redirects to the homepage
having no URL.

To reproduce this issue:

1) Install Website and remove the URL for homepage from configuration
2) Create a user having no access rights of designing and editing
3) Login with the user and open website

Error:- "AttributeError: 'bool' object has no attribute 'startswith'"

As we can see URL is not required for the homepage.
When the admin removes the URL, it leads to a traceback to the
user,  who doesn't have the access rights for editing and designing.

As `website_page` is only available for the user having those rights.

This leads to a traceback when startswith is accessing from the menu URL

https://github.com/odoo/odoo/blob/92284e7df1c40aee25ae7fc5041e1aa9e132a61d/addons/website/controllers/main.py#L113

sentry-5655297758