[FIX] l10n_tr_nilvera_einvoice: prevent error on generating invoice xml
For the `Türkiye` localization, sending an invoice by email with a recipient
bank causes an error.

Steps to reproduce:
1) Install `accountant` and `l10n_tr_nilvera_einvoice` modules with demo data.
2) Switch to TR Company.
3) Create a customer with country set to `Türkiye`.
4) Open the TR company contact and on the Accounting page edit an existing bank
   account, add a new bank (e.g., 'Test-Bank'), and set `Send Money` to
   `Trusted`.
5) Create an invoice for the customer, confirm it, and send it by email.

ref video: https://drive.google.com/file/d/1OoUzJ-Dr2uuy4yk9P-CKUS0L6OSgeyJ3/view?usp=sharing

Error:
KeyError: 'country_id'

Root Cause:
When sending the invoice, the system generates the invoice XML. In the method
`_get_address_node` (see [1]), there is a special case to determine the correct
country for `res.bank`. However, when `vals['partner']` is a `res.bank` record,
no `model` is provided in `vals`, so it defaults to `res.partner`. The code then
attempts to access `partner['country_id']`, which does not exist on `res.bank`,
raising the error.

FIX:
Ensure the `model` is set to `res.bank` when `vals['partner']` is a
`res.bank` record, ensuring the correct country value is used.

[1]: https://github.com/odoo/odoo/blob/0190bb7faca1dd5ce38dfdacbb8fa446f06d59a3/addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py#L165-L181

opw-5103598

closes odoo/odoo#240926

X-original-commit: 9159d9e89fc816bfa1eeda4179cab09b7a5013e4
Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>
Signed-off-by: Het Patel (path) <path@odoo.com>