[FIX] purchase_stock: confirm receipt date if needed
Before this commit, There would be Traceback (AttributeError: 'bool' object has no attribute 'date')
on Confirm Receipt Date If order has no Receipt Date.

Now, Button Confirm Receipt Date will be hidden if there is not Receipt Date to confirm.

Original behavior was fixed on #60659 but attribute was replaced
here which misses this condition.

X-original-commit: 1d680f488f68be4e6157ffd5d8d9dcbb86915ab8