[FIX] google_calendar: change the AttributeError to ValidationError
This error occurs when a user resets their Google Calendar account. As a result,
the authentication token disappears, and if they attempt to reset the account
again, an error is triggered.

Steps to reproduce:
- Install 'google_calendar' module
- Set Google Calendar Credentials in settings.
- Go to Calendar and Sync with Google
- Users > Mitchell Admin > Calendar
- 'Reset Account' > 'Confirm' (keep the selections as default)
- Again 'Reset Account' > 'User's Existing Events: Delete from Both'

Stack Trace:
AttributeError: An authentication token is required

Due to an AttributeError, users are seeing an error message in the stack trace
instead of a user-friendly notification.

sentry-6311340556