[FIX] mail: no crash _fieldsValue.get with chatter activities
Before this commit, when opening a chatter with some activities with
2 or more tabs, the following crash occurs:

```
TypeError: recordFullProxy._fieldsValue.get is not a function
```

This happens because activities are shared between tabs, and the
translation from structured records to data was leaking internal code
`_fieldsValue`, which is used to map values of records that model
Chatter data such as actvities.

Because `_fieldsValue` is a map and communication between tabs is
made through `BroadcastChannel`, data are JSON.stringified and it
is expected that reinsert of activity data works.

Maps like `_fieldsValue` were leaked, which turned the Map into an
object, and since restore activity record in other tabs had an object
for `_fieldsValue` instead of expected `Map`, it crashed.

This commit fixes the issue by not exposing `_fieldsValues` in the
`toData()`, which is used by `BroadcastChannel` use of crosstab sync
of activities. Also `toData()` had typos with relational fields which
could also result in errors. These are also fixed in this commit.