[FIX] mrp: prevent error when user remove date in productivity losses
If the `End Date` is already defined and the user removes that date in
the form view of productivity losses, an error is generated.

Steps to reproduce:
- Install the mrp module
- Manufacturing > Configuration > Work Centers > open any of the Work Centers
- In the form view of Work Center, click on the 'Lost' stat button
- Open a new Productivity Loss form, set a future date in `End Date`, click
  elsewhere, then clear the `End Date`

Traceback:
TypeError: unsupported operand type(s) for -: 'bool' and 'datetime.timedelta'

If the end date is missing, we will return from the method

sentry-6641245276

closes odoo/odoo#213397

X-original-commit: 7bb84621b773cdd7e9984222d61d70d622f8ac43
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>