[FIX] core: HttpDispatcher has no attribute 'env'
1. Apply the below diff.
2. Login using the same account in two independent tabs (e.g. one
   regular tab, and a private one).
3. In the first tab, change the account password.
4. In the second tab, go to `/web/binary/upload_attachment` (any
   `type='http', auth='user'` controller would do) => 500 error.

> AttributeError: 'HttpDispatcher' object has no attribute 'env'

```
diff --git a/odoo/http.py b/odoo/http.py
index b0fd6197aea8..1ea817ec85cd 100644
--- a/odoo/http.py
+++ b/odoo/http.py
@@ -2309,7 +2309,7 @@ class HttpDispatcher(Dispatcher):
         """
         if isinstance(exc, SessionExpiredException):
             session = self.request.session
-            was_connected = session.uid is not None
+            was_connected = True
             session.logout(keep_db=True)
             response = self.request.redirect_query('/web/login', {'redirect': self.request.httprequest.full_path})
             if was_connected:
```

It is necessary to apply the diff because most places that raise
`SessionExpiredException` also pro-actively `logout()`, i.e. they reset
`session.uid` and when the exception reaches handle-error `was_connected`
is always `False`. For the bug to occur, we need a way to be in the
`was_connected == True` case but we found no way in standard Odoo (this
also explains how this bug is still present, 2 years later). The diff is
the easiest way we found to reproduce it.

closes odoo/odoo#266050

X-original-commit: 0f6e0d0c2034d9b1db20155f7566fac2846577b7
Signed-off-by: Krzysztof Magusiak (krma) <krma@odoo.com>
Signed-off-by: Julien Castiaux (juc) <juc@odoo.com>