[FIX] website: do not try to schedule if field not loaded
If `publish_on` field isn't loaded for the model we attempt to schedule
get an error.

Steps to reproduce:
1. Install `website_appointment`
2. Update `website` (via `-u`)

We get the error:
```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/orm/domains.py", line 936, in __get_field
    field = model._fields[field_name]
            ~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'publish_on'
...
ValueError: Invalid field appointment.type.publish_on in condition ('publish_on', '!=', False)
```

Reason:
The field `publish_on` is added to the model `appointment_type` by the
module `website_appointment` but when we are loading `website` the
latter is still not loaded.
https://github.com/odoo/enterprise/blob/42c817197fee14ec83d907d2be1893d1fd85cc85/website_appointment/models/appointment_type.py#L13