[FIX] web_editor: Fix setTag in commands
Steps to reproduce

- Create a new report with studio
- Chose "External Business header/footer"
- Try to add a /heading1 below the header
- Crash

```
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of null (reading 'parentNode')
TypeError: Cannot read properties of null (reading 'parentNode')
```

As `startContainerChild` and `endCOntainerChild` refers to a dom element
that can be changed in the for loop, we can declare both of them after.

opw-4368425

closes odoo/odoo#191502

X-original-commit: 5ab832f259f836bb92930795b24f58d6be6bc05a
Signed-off-by: David Monjoie (dmo) <dmo@odoo.com>
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>