[FIX] mail_group: fix error when browsing mailing lists
To reproduce (on runbot):

- Go to /groups url
- click on "Public Mailing List"

This fix `AttributeError: 'PortalMailGroup' object has no attribute 'env'`
(introduced by odoo/odoo@b60cf1f9777)

closes odoo/odoo#122729

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>