[FIX] uom: Cap the value of uom.sequence to prevent out of range
The default value of uom.sequence is calculated as uom.relative_factor * 100.
If the value of relative_factor is big enough, it can be bigger than what the
int column can handle and trigger
```
ERROR: integer out of range
```
So we just cap it at an arbitrary value.

To reproduce:
- Create an uom with relative factor bigger than 2147483647.

closes odoo/odoo#234721

X-original-commit: b36b4316d9d16ad26531ed21a67b3a5ce63ff720
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Agustín Castro Bugallo (agcb) <agcb@odoo.com>