[FIX] tests: fix traceback log retry
The auto-retry is supposed to catch error logs as well as tracebacks.
In some cases a traceback is logged as a message, and not as a logger
arg, bypassing the replace already in place.

This pr simply replaces the traceback string in the message as well.

Also catches OSError in websocket handling, as it can also happen
when the browser is closed causing

closes odoo/odoo#238263

Oserror: [Errno 9] Bad file descriptor
X-original-commit: 3bba52d02f7dcd3e49a38bf628190e92f035b9ce
Signed-off-by: Xavier Dollé (xdo) <xdo@odoo.com>