[FIX] account: ensure fixed taxes can be marshaled
Versions
--------
- 18.0+

Steps
-----
1. Create a fixed tax;
2. create a sale order using only the fixed tax;
3. read the sale order via XML-RPC.

Issue
-----
TypeError: cannot marshal None unless allow_none is enabled

Cause
-----
If only a fixed tax is used, the `_get_tax_totals_summary` method
returns a dict where the `display_base_amount_currency` and
`display_base_amount` values are `None`, leading to an error serializing
the result.

Solution
--------
As the result gets serialized by `OdooMarshaller(allow_none=False)`, we
should use `False` instead of `None`.

opw-5173477

X-original-commit: a8fe57ff8d1d283b076fd06efbfc2d36e446ace4