[FIX] spreadsheet_dashboard_sale: prevent error on opening dashboard
The system will crash when the user opens the dashboard module.

Steps to produce:
- Install the `Sales` module with demo data.
- Open the dashboard module.

Error:
KeyError: 'recurring_invoice'
ValueError: Invalid field product.template.recurring_invoice in condition ('recurring_invoice', '!=', True)

Cause:
- From this [PR], the field `recurring_invoice` is being used
  in the`spreadsheet_dashboard_sale` module. However, this field
  is actually defined in the `sale_subscription` module. Since
  `spreadsheet_dashboard_sale` does not currently listed
  `sale_subscription`in its `depends`.

Solution:
- In this PR, I have removed the reference from the domain from
  `spreadsheet_dashboard_sale` module.

[PR]: https://github.com/odoo/odoo/pull/225542

sentry-6912254481

closes odoo/odoo#229880

X-original-commit: 27be7123f4304a2ae50b1ba96cb5afef3d3a1326
Signed-off-by: Lucas Lefèvre (lul) <lul@odoo.com>