[FIX] mrp: correctly plan necessary workorders
https://github.com/odoo/odoo/pull/112800 added a fix to ignore planning done or cancelled workorders.
However it introduced an issue where any unfinished workorders before the ignored workorder will also be ignored and cause a traceback in certain workflows.

Steps to reproduce
-----
1. Create a manufacturing order, and add 2 workorders
2. Start and finish the 2nd workorder
3. Attempt to add a 3rd workorder
4. Traceback occurs
```
    'date_planned_start': min([workorder.leave_id.date_from for workorder in workorders]),
TypeError: '<' not supported between instances of 'datetime.datetime' and 'bool'
```

Cause
-----
This early continue added in https://github.com/odoo/odoo/pull/112800 is too eager:
https://github.com/odoo/odoo/blob/f19b61b640c6623aad3269d8f0e515b5480e6880/addons/mrp/models/mrp_workorder.py#L525-L526
Although the specified workorder should be ignored, it could potentially have children (`workorder.blocked_by_workorder_ids`) that need to be planned.

Solution
-----
Remove the early continue and keep running `_plan_workorder` on the done/cancelled workorder.
All of its children `workorder.blocked_by_workorder_ids` will be correctly planned in the recursive call,
and the done/cancelled workorder will still be correctly ignored afterwards in this existing early return:
https://github.com/odoo/odoo/blob/f19b61b640c6623aad3269d8f0e515b5480e6880/addons/mrp/models/mrp_workorder.py#L529-L531

opw-4497704

closes odoo/odoo#197380

X-original-commit: 12e9a427b15b842df5d2de3805f7da4b327987d6
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Junqi Wu (juwu) <juwu@odoo.com>