[FIX] website: escape bad characters compile in website name
Currently, using special characters like backslashes (\) in the
website name would cause a regex substitution error during
website configuration.

Steps to Reproduce:
- Install the `website` module.
- Go to Settings and change the website name (e.g; "test\").
- Navigate to the URL: "http://localhost:8069/website/configurator"
- Select a theme and a color palette for the website,
 then apply the changes.

Error: error - bad escape (end of pattern) at position 19

Cause:
At [1], a backslash in the `website.name` string leads to a malformed
replacement string in `re.sub()`, causing a regex syntax error due to
an invalid escape sequence.

[1]: https://github.com/odoo/odoo/blob/b8edcd131b3288d037bee9ee03726153932d82f1/addons/website/models/website.py#L678

Fix:
This commit escapes the `website.name` using `re.escape()` before
using it in regex substitution, prevents runtime errors during
website configuration.

sentry-6651288996

closes odoo/odoo#223086

X-original-commit: e58ca972a159ac80e76ff0bd39129eeb7de5abf9
Signed-off-by: Quentin Smetz (qsm) <qsm@odoo.com>
Signed-off-by: Aditi Patel (adip) <adip@odoo.com>