[FIX] sale_pdf_quote_builder: traceback on printing report
before this commit, on printing the report if there is an
exception happens on rendering the header and footer,
traceback is shown to user without skipping the exception

AttributeError: 'sale.order.template' object has no
attribute '_message_log'

the exception come from _get_form_fields_mapping function,
format_date function is called by passing tz but the function
doesnt have this argument.

after this commit, if exception happens on rendering the
header or footer, a message will be added in the log and
report will be printed without traceback