[FIX] pos_viva_wallet: prevent an error when system try to retrieve session_id
An error occurs when the system tries to retrieve 'session_id' at [1] from
'MerchantTrns' but it is not available. Because of failed transactions, Ref: https://developer.viva.com/webhooks-for-payments/transaction-failed/#response-example

link [1]: https://github.com/odoo/odoo/blob/319cf81da8f16df21900f26bd6d8b4fc686e72eb/addons/pos_viva_wallet/models/pos_payment_method.py#L113

AttributeError: 'NoneType' object has no attribute 'split'

To resolve this issue, add a condition to check if 'MerchantTrns' is not
available then raise an error as send notification.

Sentry - 5466498742