[FIX] im_livechat: invalid URL Regex in Channel Rules
If the user adds an invalid value for URL Regex and tries to open the website,
A traceback will appear.

Steps to produce the error:
- Install "website_livechat" > configure website
- Go to 'Live Chat' > Open existing channel > Channel Rules > Add a line >
  Add * in URL Regex > Save
- Now Open the 'Website' > click on 'GO TO WEBSITE'

Error: A traceback appears:
"error: nothing to repeat at position 0"

https://github.com/odoo/odoo/blob/52fe645be92bf3c30edbab39bc1dc5a1ac4f1bd0/addons/im_livechat/models/im_livechat_channel.py#L335
Here, when user provides '*' as URL Regex, rule.regex_url will be *,
So when rule.regex_url is searched in the url,
It will lead to the above traceback because there is nothing to search for.

sentry-4586706988