[FIX] account: prevent error when downloading pdf of an invoice
When the user downloads the pdf of a draft invoice,
a traceback will appear.

Steps to reproduce the error:
- Create a new invoice > Don't confirm it
- Go to list view of invoices
- Select that invoice > Download > PDF

Traceback:
"AttributeError: 'bool' object has no attribute 'replace'"

https://github.com/odoo/odoo/blob/36e4b6f93bf2123557947e910e1be651c5357319/addons/account/models/account_move.py#L5744
When the customer downloads the pdf a draft invoice, "self.name" will be False,
So it will lead to the above traceback.

sentry-6191644587