[FIX] pos_hr: initialize employeeBuffer before super call to avoid error
Steps to reproduce:
===================
- Enable Login with Employee in POS settings
- Open POS and log in with employee
- Turn off the internet connection
- Reload the POS page

Issue:
======
- POS crashes with the following error:
TypeError: Cannot read properties of undefined (reading push)
- At that point, employeeBuffer is still undefined

Cause:
======
- The method set_cashier() is triggered during the parent setup()
- employeeBuffer was only initialized after super.setup()
- In offline mode, this sequence still executes, leading to an exception
when trying to .push() into an undefined buffer

Fix:
====
- Moved the initialization of employeeBuffer to the beginning of the
setup() method

Task: 4850543
Runbot Error: 227777

closes odoo/odoo#219228

X-original-commit: a7b45460a1688b3889b1e0d33b551f306106d198
Signed-off-by: David Monnom (moda) <moda@odoo.com>
Signed-off-by: Abhishek Khant (abhk) <abhk@odoo.com>