[FIX] base: fix error on properties field with missing definition
`_postprocess_tag_field` unconditionally add `field.definition_record`
to required view fields for `properties` type fields.

During upgrade, a `properties` field whose defining module is absent
(custom module not loaded) keep `ttype = 'properties'` in
`ir_model_fields` but never get `definition=` set, so
`definition_record` stay `None`. `must_have_fields` then call
`None.startswith('parent.')`, raising:
```py
   File "/home/odoo/src/odoo/19.0/odoo/addons/base/models/ir_ui_view.py", line 1685, in _postprocess_tag_field
    name_manager.must_have_fields(node, [field.definition_record], node_info, ('fieldname', field.name))
   File "/home/odoo/src/odoo/19.0/odoo/addons/base/models/ir_ui_view.py", line 3382, in must_have_fields
    if not name.startswith('parent.'):
 AttributeError: 'NoneType' object has no attribute 'startswith'
```
```py
> /home/odoo/src/odoo/19.0/odoo/addons/base/models/ir_ui_view.py(1686)_postprocess_tag_field()
-> if field.type == 'properties':
(Pdb) field
'l10n_latam.credit.limit.properties'
(Pdb) n
> /home/odoo/src/odoo/19.0/odoo/addons/base/models/ir_ui_view.py(1687)_postprocess_tag_field()
-> name_manager.must_have_fields(node, [field.definition_record], node_info, ('fieldname', field.name))
(Pdb) field.definition_record

> /home/odoo/src/odoo/19.0/odoo/addons/base/models/ir_ui_view.py(3378)must_have_fields()
-> access_groups = node_info['model_groups'] & node_info['view_groups']
(Pdb) l.
3373
3374        def has_action(self, name):
3375            self.available_actions.add(name)
3376
3377        def must_have_fields(self, node, names, node_info, use):
3378 ->         access_groups = node_info['model_groups'] & node_info['view_groups']
3379            for name in names:
3380                if name == 'id':
3381                    continue
3382                if not name.startswith('parent.'):
3383                    self.used_fields[name][access_groups] = (use, node)
(Pdb) locals()
{'self': <odoo.addons.base.models.ir_ui_view.NameManager object at 0x7dc4cba23520>, 'node': <Element field at 0x7dc4caa78980>, 'names': [None], 'node_info': {'view_type': 'form', 'view_editable': True, 'mobile': None, 'model_groups': "'account.group_account_invoice' | 'l10n_latam_gh.group_credit_manager'", 'view_groups': '*', 'name_manager': <odoo.addons.base.models.ir_ui_view.NameManager object at 0x7dc4cba23520>, 'editable': True}, 'use': ('fieldname', 'properties')}
(Pdb) names
[None]
```

Only call `must_have_fields` when `definition_record` is set.