[FIX] website: Fix TypeError calling Rule.build
The first argument to `rule.build` should be a dictionary.  This causes some
trouble with recent versions of werkzeug:

    Traceback (most recent call last):
      File "odoo/odoo/http.py", line 718, in _handle_exception
        return super(JsonRequest, self)._handle_exception(exception)
      File "odoo/odoo/http.py", line 376, in _handle_exception
        raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
      File "odoo/odoo/tools/pycompat.py", line 87, in reraise
        raise value
      File "odoo/odoo/http.py", line 760, in dispatch
        result = self._call_function(**self.params)
      File "odoo/odoo/http.py", line 408, in _call_function
        return checked_call(self.db, *args, **kwargs)
      File "odoo/odoo/service/model.py", line 101, in wrapper
        return f(dbname, *args, **kwargs)
      File "odoo/odoo/http.py", line 401, in checked_call
        result = self.endpoint(*a, **kw)
      File "odoo/odoo/http.py", line 1014, in __call__
        return self.method(*args, **kw)
      File "odoo/odoo/http.py", line 581, in response_wrap
        response = f(*args, **kw)
      File "odoo/addons/web/controllers/main.py", line 996, in call_kw
        return self._call_kw(model, method, args, kwargs)
      File "odoo/addons/web/controllers/main.py", line 988, in _call_kw
        return call_kw(request.env[model], method, args, kwargs)
      File "odoo/odoo/api.py", line 759, in call_kw
        return _call_kw_multi(method, model, args, kwargs)
      File "odoo/odoo/api.py", line 746, in _call_kw_multi
        result = method(recs, *args, **kwargs)
      File "odoo/addons/website/models/website.py", line 781, in search_pages
        for page in self.enumerate_pages(query_string=name, force=True):
      File "odoo/addons/website/models/website.py", line 715, in enumerate_pages
        if query_string and not converters and (query_string not in rule.build([{}], append_unknown=False)[1]):
      File ".v/lib/python3.8/site-packages/werkzeug/routing.py", line 977, in build
        return self._build(**values)
    TypeError: <builder:'/website/info'>() argument after ** must be a mapping, not list