[FIX] l10n_in_{}: add missing dependency for module
* l10n_in_purchase_stock, l10n_in_sale_stock

before this commit, if sale_stock or purchase_stock
module was uninstalled from db manually, exception
will be shown for the users.

* create a db with selecting country as india

for l10n_in_sale_stock:

* install sale and stock module in the db

* sale_stock and l10_in_sale_stock will get installed
in the db

* now uninstall sale_stock module, user will receive
500 internal server error as the l10_in_sale_stock
didn't get uninstalled and depends on warehouse_id
field from sale_stock module

* in l10n_in_sale_stock module, _compute_l10n_in_journal_id function is depending on the field warehouse_id
which is added from the sale_stock module

Exception: ValueError: Wrong @Depends on _compute_l10n_in_journal_id (compute method of field sale.order.l10n_in_journal_id). Dependency field warehouse_id not found in model sale.order.

for l10n_in_purchase_stock:

* in fresh db, install purchase and stock module

* purchase_stock, l10n_in_purchase_stock will get installed
automatically

* now uninstall purchase_stock module and try to open
the purchase order form,user will get exception
* l10_in_purchase_stock module is still installed and
depending on a field picking_type_id from purchase_stock
module

* onchange function l10n_in_onchange_company_id isdepending and using field picking_type_id which is added from
purchase_stock module

Exception:AttributeError: purchase.order object has no attribute picking_type_id

after this commit, on uninstalling sale_stock or
purchase_stock module from the db will uninstall
l10_in_sale_stock, l10_in_purchase_stock
modules respectively.