[FIX] partner_autocomplete: prevent error on industry enrichment
Currently, an error occurs when industry_id is written to the partner
```
  File "/home/odoo/odoo18/community/odoo/addons/base/models/res_partner.py", line 761, in <genexpr>
    self.env['res.partner']._fields[fname].convert_to_write(child[fname], self) != sync_vals[fname]
                                                                                   ~~~~~~~~~^^^^^^^
KeyError: 'industry_id'
```

During automatic company enrichment, _enrich() processes the data returned
by the IAP autocomplete service. When industry_id is returned, it comes as
a dictionary containing its display name and ID [1], so the Many2one ID needs
to be extracted before writing it to the partner.

This dictionary is passed directly to write(). When the partner's
commercial fields are synchronized to its descendants, the sync values are
computed based on the commercial fields [2] and converted to write values [3].
The Many2one conversion creates a new record ID [4], which is then skipped
when adding the value to the converted values [5]. When the field is
subsequently accessed from sync_vals, the field is missing and raises a
KeyError [6].

This commit ensures that industry_id is converted to its ID before writing,
consistently with the existing country_id and state_id handling [7]. The
_enrich_extract_m2o_id [8] helper is responsible for extracting Many2one IDs
from the data returned by res.partner._format_data_company [9], including
the industry code replacement performed by _iap_replace_industry_code.

[1]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/addons/partner_autocomplete/models/res_partner.py#L60-L65

[2]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/odoo/addons/base/models/res_partner.py#L756

[3]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/odoo/addons/base/models/res_partner.py#L657

[4]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/odoo/orm/fields_relational.py#L390-L391

[5]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/odoo/orm/models.py#L6123-L6126

[6]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/odoo/addons/base/models/res_partner.py#L760-L764

[7]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/addons/partner_autocomplete/models/res_company.py#L67

[8]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/addons/partner_autocomplete/models/res_company.py#L72-L79

[9]: https://github.com/odoo/odoo/blob/4e7b84db9455086754164db5e404987c34d48eb7/addons/partner_autocomplete/models/res_partner.py#L78-L84

sentry-7628464117