[FIX] calendar: using many2many to event and recurrence
The current code to search recurring ids doesn't handle '!' operator.

If for example we use calendar.event as target of many2many field, we
use a domain ['!', ['id', 'in', {{current_ids}}]] which if there is
recurrent events causes an error.

With this changeset, we avoid `!` operator by distributing it.

Code added in test without the fix fails with:

  AssertionError: This domain is syntactically not correct: ['!']

when inside calendar.event().get_recurrent_ids we do (with arg=='!'):

  e = expression.expression([arg], self)

opw-2442353