[FIX] Avoid trying to translate AbstractModel's fields
If you declare in your module an `AbstractModel` such as:

```
class A(openerp.models.AbstractModel):
    name = openerp.fields.Char(translate=True)
```

And then you try to export a translation for that module from *Settings
> Technical > Translations > Import / Export > Export Translation*, you
will get an error similar to this one:

```
2016-01-29 12:05:04,482 17 ERROR demo openerp.http: Exception during
JSON request handling.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 537, in
_handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 574, in
dispatch
    result = self._call_function(**self.params)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 310, in
_call_function
    return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line
118, in wrapper
    return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 307, in
checked_call
    return self.endpoint(*a, **kw)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 803, in
__call__
    return self.method(*args, **kw)
File "/usr/lib/python2.7/site-packages/openerp/http.py", line 403, in
response_wrap
    response = f(*args, **kw)
File "/opt/odoo/extra-addons/core-addons/web/controllers/main.py",
line 948, in call_button
    action = self._call_kw(model, method, args, {})
File "/opt/odoo/extra-addons/core-addons/web/controllers/main.py",
line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr,
request.uid, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 256, in
wrapper
    return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-
packages/openerp/addons/base/module/wizard/base_export_language.py",
line 65, in act_getfile
    tools.trans_export(lang, mods, buf, this.format, cr)
File "/usr/lib/python2.7/site-packages/openerp/tools/translate.py",
line 524, in trans_export
    translations = trans_generate(lang, modules, cr)
File "/usr/lib/python2.7/site-packages/openerp/tools/translate.py",
line 757, in trans_generate
    ids = objmodel.search(cr, uid, [])
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 256, in
wrapper
    return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 1647,
in search
    return self._search(cr, user, args, offset=offset, limit=limit,
order=order, context=context, count=count)
File "/usr/lib/python2.7/site-packages/openerp/api.py", line 256, in
wrapper
    return old_api(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4692,
in _search
    cr.execute(query_str, where_clause_params)
File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 158,
in wrapper
    return f(self, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 234,
in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "l10n_es_tgss_number_name" does not exist
LINE 1: SELECT "l10n_es_tgss_number_name".id FROM "l10n_es_tgss_numb...
```

Which means that no database object is found. And that is expected
because `AbstractModel` subclasses do not create DB tables.

To avoid the failure, we simply skip translation of fields from models
that did not create a table.