[FIX] hr_expense: fix type error when posting expenses
The `company_paid_move_ids` context key is normally present when the
wizard is generated [1]. However, its fallback value in `action_post_entry`
is an empty tuple [2], while `moves_sudo.ids` is a list.
If the context key is missing, for example due to a customization,
concatenating both values raises a TypeError.

TypeError: can only concatenate list (not "tuple") to list

Use an empty list as the fallback value so that both operands have the same type.

[1]: https://github.com/odoo/odoo/blob/2e2acfd6d2725d1a4a95b1a6056334e1ac34163f/addons/hr_expense/models/hr_expense.py#L1196

[2]: https://github.com/odoo/odoo/blob/2e2acfd6d2725d1a4a95b1a6056334e1ac34163f/addons/hr_expense/wizard/hr_expense_post_wizard.py#L65

sentry-7720978672