[FIX] website_sale: traceback when product has computed tax
Have a tax with Tax Computation set to 'Custom Formula', depending on a
product.<product_field> (i.e. product.list_price)
Add that tax to a product shown in website shop
Access Ecommerce

Error
```
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
ValueError: Expected singleton: product.template(17, 18, 23, 8)
Template: website_sale.products_item
Path: /t/form/div[2]/div[2]/div[2]/span[1]
Node: <span class="h6 mb-0" t-if="template_price_vals[\'price_reduce\'] or not website.prevent_zero_price_sale" t-out="template_price_vals[\'price_reduce\']" t-options="{\'widget\': \'monetary\', \'display_currency\': website.currency_id}"/>
Compiled code:
code = None
template = 'website_sale.products_item'
```

This occurs because we call `compute_all` with multiple product templates

opw-4295796

closes odoo/odoo#186590

X-original-commit: 04314d0d56e3a812ca919fa5a69be4f26d8f6751
Signed-off-by: Valentin Chevalier <vcr@odoo.com>