[FIX] mail: convert into markup before adding to markup
Since
https://github.com/odoo/odoo/commit/5a573db2495f448137037d4c15cefd301fdaa279,
float, int, boolean field crash when they were tracked

```
File ~/src/odoo/saas-19.3/addons/mail/models/mail_thread.py:672, in MailThread._track_log(self, track_init_values, trackings, track_records)
--> 672     record._message_log(

File ~/src/odoo/saas-19.3/addons/mail/models/mail_thread.py:2946, in MailThread._message_log(self, body, subject, author_id, email_from, message_type, partner_ids, attachment_ids, tracking_values)
-> 2946 return self._message_log_batch(

File ~/src/odoo/saas-19.3/addons/mail/models/mail_thread.py:3009, in MailThread._message_log_batch(self, bodies, subject, author_id, email_from, message_type, partner_ids, attachment_ids, tracking_values)
-> 3009     values_list[0]['body'] = self._message_compute_body_with_trackings(values_list[0]['body'], tracking_values)

File ~/src/odoo/saas-19.3/addons/mail/models/mail_thread.py:3082, in MailThread._message_compute_body_with_trackings(self, body, tracking_values)
-> 3082     line += val['old_value']

ValueError: TypeError("unsupported operand type(s) for +=: 'Markup' and 'float'") while evaluating
```

they need to be converted into markup before they can be concatenate
with the line