[FIX] web_editor: prevent valueerror for Unsupported file
The error arises because 'file_open' is called with a file path that includes a
'.css' extension, which is not supported in this context where a '.svg' file is
expected.

Error: ValueError
Unsupported file: actuator;/static/shapes/env;.css

This commit adds a try-catch block to handle a ValueError when an unsupported
file is added.

sentry-5163461799