[FIX] web: prevent error on switching to superuser
Currently an error occurs when user tries to switch to superuser.

Steps to replicate:
- Make a DB and turn on debug mode.
- Click on the bug icon and click `Become Superuser`.

 Error:
`AttributeError: 'Request' object has no attribute 'sesssion'`

Cause:
- Session incorrectly spelled as `sesssion`.

Fix:
- Corrected `request.sesssion` to `request.session`.

No Id