[FIX] sale_mrp: prevent traceback when reconfirming canceled SO with kit
Bug introduced in:https://github.com/odoo/odoo/pull/207955/commits/dbd9ae1c9042163d77931fe8d93064c006c7d148

Steps to reproduce the bug:
- Create a kit product:
    - BoM:
         - Components:
             - 1 unit of C1
             - 1 unit of C1 (same product)

- Create a SO with one unit of kit
- Confirm the SO
- The delivery is created
- Cancel the SO → the delivery is canceled.
- Set the SO back to quotation and confirm again

Problem:
A traceback is triggered:
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: mrp.bom.line(24, 25)

When a kit's BoM contains the same product multiple times, multiple
bom_line_ids match a given move. Assigning them causes an error.
Additionally, cancelled moves were incorrectly considered.

Solution:
Filter out cancelled stock moves before accessing the bom_line_id to
ensure only active moves are considered.

And in the case where we have the same component multiple times, we
have no choice but to link all the moves to the first bom_line, because
the moves are processed separately, so we can't loop over them.

opw-4919875

closes odoo/odoo#218925

X-original-commit: 8841ee13c55fe1fa6919f62c23926665811f6778
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>