[FIX] hr_expense: prevent error when post hr expense sheets for journal entries
Currently, the error arises during the posting of HR expense sheets for the
journal entries when an 'Expense Date' is not available in the HR expense.

Steps to reproduce:

- Install a 'hr_expense' module (with demo data).
- Navigate to Expense / Expense Reports and open any record.
- Add a line in the Expense section without entering an 'Expense Date.'
- Click the 'Approve' button and then proceed to click on
'POST JOURNAL ENTRIES.'

Error:   TypeError: '>' not supported between instances of 'datetime.date' and
'bool'.

When posting the HR expenses sheet for journal entries
without adding an expense date in 'Expense', There's an issue at [1], Where the
max() function is used to return highest expense date from 'expense_line_ids.'
But one of the dates is marked as 'False,'

[1]:https://github.com/odoo/odoo/blob/b1b94a075672067325ddcc125cbc57ae214b0a9a/addons/hr_expense/models/hr_expense.py#L1288

This commit fixes the above issue by adding a condition to eliminate date values
that are marked as 'False.' This ensures that only valid dates are considered
when determining the highest expense date.

sentry-4907496401