[FIX] mail: no crash on making mention in full composer
Before this commit, making a mention in full composer resulted
in a crash.

Steps to reproduce:
- Open a form view in Contacts
- Click on "Send a message"
- Click on the expand button in composer (2 outer-pointing arrows)
- In full composer (the composer in dialog), type `@`
- Then in popover, type any character

=> Crashes with:

```
TypeError: Cannot read properties of undefined (reading 'model')
```

This happens because the search on partner suggestion wrongly assumed
that the context of thread is provided, which is actually not
necessarily true, the full composer with `@`-mention being one such
example. As a result, accessing `thread.model` crashes.

This commit fixes the issue by not adding optional chaining on
`thread` param, as this is an optional parameter.

closes odoo/odoo#165647

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>