[FIX] l10n_sa_edi: fix ZATCA posting with reversed downpayment
An error occurs when trying to send a reversed invoice to ZATCA
if it included a downpayment that was also reversed.

Steps to reproduce:
- Install "Sales" and "Saudi Arabia - E-invoicing" apps.
- Create a quotation and confirm it.
- Create a downpayment and post it to ZATCA.
- Create an invoice **A** including the downpayment and post it.
- Reverse the downpayment and post it to ZATCA.
- Reverse invoice **A** and try posting it to ZATCA.

An error will occur:
```python
File ".../l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py", line 356, in _l10n_sa_get_line_prepayment_vals
    'prepayment_id': prepayment_move_id.name,
                     ^^^^^^^^^^^^^^^^^^^^^^^
File ".../odoo/fields.py", line 1154, in __get__
    record.ensure_one()
File ".../odoo/models.py", line 5204, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.move(190098, 190096)
```

This fix ensures that only the actual downpayment move is used by
filtering on the move type.

opw-4567756