[FIX] html_builder: fix crash with mouse move on overlay
__Current behavior before commit:__
The `onMouseMoveOrDown` event listener is inside `throttleForAnimation`
therefore it might be called asynchronously.

In this case `ev.currentTarget` is `null` and the following traceback
appears when we move the mouse while pressing a key in the html builder:
```
TypeError: Cannot read properties of null (reading 'removeEventListener')
```

__Description of the fix:__
Replace `ev.currentTarget` by `this.editable` since the
`onMouseMoveOrDown` event listener is always added on the latter.

closes odoo/odoo#216720

X-original-commit: 5193660f5364b204ad10fcd96a9dec9bed1b649e
Signed-off-by: Soukéina Bojabza (sobo) <sobo@odoo.com>
Signed-off-by: Julien Launois (jula) <jula@odoo.com>