[FIX] sale_pdf_quote_builder: play nice with existing form fields
Versions
--------
- saas-17.4+

Steps
-----
1. Have PDF file with checkbox form fields;
2. upload it as footer for a Quotation Template;
3. set up a quotation using the template;
4. print the PDF Quote.

Issue
-----
> Odoo Server Error
> IndexError: string index out of range

Thrown from the PyPDF2 package.

Cause
-----
Commit e1b05e95e73c expanded the form fields available in the quote
builder. It introduced the `_get_form_fields_values_mapping` method.

It ignores fields not in the `param_field_map` by associating them with
an empty string. This causes issues with non-text form fields, e.g.
checkbox, which uses `/Off` to represent the emptiness.

Solution
--------
Instead of retrieving all fields with `getFields`, use
`getFormTextFields`. This way, an empty string should always be a valid
value.

opw-4290594

X-original-commit: be2f31a4ad034427497ebd075a1795047336e190