[FIX] l10n_it_edi: fix async multi-company send to SDI
Fix an issue when sending invoices asynchronously to SDI
from multiple companies.

Steps to reproduce:
- Setup two Italian companies, A and B
- Create and post one invoice in each company
- From the list view, batch send both invoices
- Run the “Send invoices automatically” scheduled action

An error occurs:
ValueError: Expected singleton: account_edi_proxy_client.user(4, 3)

This happens because both companies try to send their moves
simultaneously, but the proxy client is company-specific.

This fix groups the invoices by company before sending them.

opw-4725653

X-original-commit: bffce6da20d0928b9037250911fcc3ad732291eb