[FIX] base: handle the canceling statement due to lock timeout
 A cron `Base: Auto-vacuum internal data` is running, which is performing
`auto_vacuum`. When the time limit exceeds 10 secs, we face the above issue.

Error: LockNotAvailable: canceling statement due to lock timeout

This commit solves the above issue by rollback the statement if the
`auto_vacuum` time limit exceeds 10 secs.

sentry-3938940519

closes odoo/odoo#131193

X-original-commit: f3dc0e12ba22968697d75c011352c0df99d5b5ed
Signed-off-by: Fabien Pinckaers (fp) <fp@odoo.com>
Signed-off-by: Archana Vaghasiya (arva) <arva@odoo.com>