[FIX] web: DomainSelector doesn't filter operators
Steps to reproduce
==================

- Go to invoices
- Open studio > report > Invoices
- Add a text block
- On the sidebar, click on the pencil next to "Visible If"
- Add a filter
- Set the condition to "doc.partner.name contains 'a'"

```
Error when compiling xml template
SyntaxError: invalid syntax. Perhaps you forgot a comma? (<>, line 1)
```

Cause of the issue
==================

The edit is the following

```
<span t-if='o.partner_id.name ilike "a"' data-oe-id="742" data-oe-xpath="/t/t/div[2]/div/div[3]/div/span" />
```

The t-if isn't a valid python expression.

THe ilike operator shouldn't be available in this case.

cf: https://github.com/odoo/enterprise/commit/26ac3f2199cdb1ad34ba9afe3cd2b63241cc9638

opw-3560346