[FIX] website_sale: prevent errors when adding a combo product to the cart
Currently, an error occurs when a user adds a combo product to the cart.

Steps to Reproduce:

 - Install the website_sale module.
 - Create a product of type combo and add a combo choice.
 - Go to the combo choices and delete that combo choice.
 - Go to the website > Shop and add that product to the cart.

ValueError: min() arg is an empty sequence

This error occurs after this [commit](https://github.com/odoo/odoo/pull/198070/files),
When user creates a combo product, adds its related combo choice,
and then deletes that combo choice, adding the product to the cart
causes the system to check the quantities of the order line [1]. Since
there is no sale combo choice for that product, the combo line
becomes empty and raises an error[2].

[1]:  https://github.com/odoo/odoo/blob/df05ae6d9af6abdfd67c49ac7a4d01762472bfc3/addons/website_sale/controllers/cart.py#L189

[2]: https://github.com/odoo/odoo/blob/df05ae6d9af6abdfd67c49ac7a4d01762472bfc3/addons/website_sale/models/sale_order.py#L621

This commit ensures combo choice quantities are checked only if they exist.

sentry-6924112987

X-original-commit: 8f96bd842dc0615018b37fed28cabb298c41c0d4