[FIX] account_edi_ubl_cii: prevent error when creating invoice for pos order
Currently, an error occurs when a user creates the invoice for a POS order.

Steps to Reproduce:

 - Install the point_of_sale module.
 - Start a Point of Sale session.
 - Go to Products > create a product without Sales Taxes and Purchase Taxes,
   and in the Point of Sale tab, select your POS session category.
 - Go to Customers and create a customer and In the Invoicing tab of the
   customer, select BIS Billing 3.0 SG in the eInvoice format field.
 - Go to the Point of Sale session and validate an order with the newly
   created product.
 - Go back from the session, open the newly created order in Orders and
   select the newly created customer in the Customer field, and click the
   Invoice button.

AttributeError: 'NoneType' object has no attribute 'amount'

This error occurs after [this commit](https://github.com/odoo/odoo/commit/840bd1832edcc7815b8df70ec52dca10ef978fae),
When a user creates an invoice for a POS order, the system calculates
the tax_category_code [1], and if the product does not have any type of
tax, then an error occurs here [2].

This commit ensures that if the tax is not present, it treats the tax
amount as 0 as in [3] and returns the tax_category_code safely.

[1]: https://github.com/odoo/odoo/blob/2627168eea8562477f600c97c42d443a072ddccc/addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py#L432

[2]: https://github.com/odoo/odoo/blob/2627168eea8562477f600c97c42d443a072ddccc/addons/account_edi_ubl_cii/models/account_edi_xml_ubl_sg.py#L23

[3]: https://github.com/odoo/odoo/blob/saas-18.4/addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py#L434-L435

sentry-6814145551

X-original-commit: 7b16864855c128a0ff00f0e8d1c1104ef2a0097d