[FIX] web: one2many and onchange on shared x2many WIP
If we have an onchange that adds line on a one2many itself containing an
x2many shared between two subviews, we could get an error when opening
one of the views.

This is because we handle several cases (new record, existing record,
new record not coming from onchange) but if we have eg.:

```
<form>
  <field name="one2manyField">
    <tree><field name="x2manyField"/></tree>
    <form><field name="x2manyField"/></form>
  </field>
</form>
```

if an onchange add a line to one2manyField, we will have established
changes value for x2manyField and when we open the form view we keep
these values without getting a new Datapoint which would have the
correct fields/fieldsInfo corresponding to x2manyField inside the form
view and not x2manyField inside the tree view.

This change is a WIP (work in progress) ugly hack that seems to work for
this given case.

Without the fix, the added test fails with:

  TypeError: Cannot read property 'list' of undefined
    at Class._getOptionalColumnsStorageKeyParts
    (/web/static/src/js/views/list/list_renderer.js:259:48)

  should have opened a dialog

And if this error was solved (it dosn't happen in 12.0), it fails when
adding a line to the x2many with:

  Cannot convert undefined or null to object
    at Class._makeDefaultRecord
    (/web/static/src/js/views/basic/basic_model.js:3950:33)

opw-2422806
closes #64793