Cherry pick of f6c5db7a0a82a9265d16d3df67fcf71bfa2af79c failed
stdout:

stderr:
12:15:36.833336 git.c:344               trace: built-in: git cherry-pick f6c5db7a0a82a9265d16d3df67fcf71bfa2af79c
error: could not apply f6c5db7a0a8... [FIX] point_of_sale: expose diff fields for bank payment methods in the closing popup
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: