[FIX] purchase_stock: prevent error when removing location from replenishment
Currently, an error occurs when removing the location from a replenishment.

Steps to Reproduce:
 - Install the purchase_stock module.
 - Go to Settings and enable Multi-Step Routes.
 - Go to Inventory > Configuration > Warehouse Management > Routes.
 - Open the Buy route and enable Product under Applicable On.
 - Go to Inventory > Products > Products.
 - Create a product and enable the Buy route in the Inventory tab.
 - Go to Inventory > Operations > Procurement > Replenishment.
 - In list view, click New, remove the Location value from the line,
   and then set that product.

TypeError: combine() argument 1 must be datetime.date, not bool

After the [commit], which changes the default replenishment multiple to
use the supplier's pricelist UoM or the BoM UoM instead of the product's
 default UoM when no replenishment multiple is manually configured,
when the user creates a replenishment, removes the location from the
record in the list view, and then sets the product, lead_horizon_date is
set to False for that record because it has no location [1]. It then
computes replenishment uom_id placeholder [2], from where it gets
the planned date [3] through orderpoint_procurement_date, which
raises an error due to the falsy lead_horizon_date [4].

This commit ensures that, if lead_horizon_date is falsy, it gets the
replenishment multiple alternative from the parent method, which
returns False. As a result, replenishment uom_id placeholder is left
 empty. Since location_id is a required field, once the user sets it,
the correct replenishment uom_id placeholder is recomputed.

[commit]: https://github.com/odoo/odoo/commit/7c503a5299a34446bb9c622e0cddd9b26b5bbedc

[1]: https://github.com/odoo/odoo/blob/4cb3090ee829084c2a9260b6d38095cd818678f5/addons/stock/models/stock_orderpoint.py#L182-L188

[2]: https://github.com/odoo/odoo/blob/4cb3090ee829084c2a9260b6d38095cd818678f5/addons/stock/models/stock_orderpoint.py#L220-L224

[3]: https://github.com/odoo/odoo/blob/4cb3090ee829084c2a9260b6d38095cd818678f5/addons/purchase_stock/models/stock.py#L309

[4]: https://github.com/odoo/odoo/blob/4cb3090ee829084c2a9260b6d38095cd818678f5/addons/stock/models/stock_orderpoint.py#L793-L794

sentry-7647465544