[FIX] board: fix error when switching layouts Fixes the error "TypeError: edit_custom() missing 1 required positional argument: 'custom_id'" when switching layouts.