[FIX] base_import: prevent errors when importing bank statements
Currently, an error occurs when a user imports a file in the Bank Statement.

Steps to Reproduce:

 - Install the Accounting module.
 - Go to the Bank Journal.
 - Import [this file] and click on Test.

ValueError: could not convert string to float: '.'

This error occurs when the user enters a . in the balance column. The value
matches the float_regex and fails to convert to a float, raising a ValueError.
The error only occurs in the case of dot.

This commit ensures that if the data contains only a single dot, or multiple
dots with numbers, parsing the float from the data raises an import error [3].

[this file]: https://drive.google.com/file/d/1A6p3yV_BtJKipWEjVNTQwN5ChQNPWNKl/view?usp=drive_link

[1]: https://github.com/odoo/odoo/blob/ec5da99ca3f52420e7d973c3cf07167bd4104ffa/addons/base_import/models/base_import.py#L1205

[2]: https://github.com/odoo/enterprise/blob/d57c3ab04a5ef2d056b3c11719ab0ba9db7ccece/account_bank_statement_import_csv/wizard/account_bank_statement_import_csv.py#L96-L98

[3]: https://github.com/odoo/odoo/blob/ec5da99ca3f52420e7d973c3cf07167bd4104ffa/addons/base_import/models/base_import.py#L1247

sentry-7198329852