[FIX] snailmail: prevent error in Snailmail letter process when invoice deleted
Currently, an error occurs when the Snailmail: process letters queue scheduled
action is triggered.

Steps to reproduce:

 - Install the website and account modules.
 - Create a Invoice > Confirm > Send > check the By Post checkbox.
 - Reset to Draft newly created invoice and delete it.
 - Run the Snailmail: process letters queue scheduled action.

MissingError: Record does not exist or has been deleted.
(Record: account.move(27,), User: 1)

This error occurs when the user sends the invoice by post, which creates
a Snailmail letter record related to the invoice. If the invoice is
subsequently deleted, the Snailmail: Process Letters Queue scheduled
action run and attempt to fetch the attachment of related snailmail letter
and invoice[1] but the invoice is not exists [2] and raise a MissingError.

[1] https://github.com/odoo/odoo/blob/cc368d553cd94bee8b09d4981cb8f1dbc27a34b3/addons/snailmail/models/snailmail_letter.py#L149

[2] https://github.com/odoo/odoo/blob/420765c787b33f79ee8814f799de721508858319/addons/account/models/account_move.py#L3605

This commit ensures that the system evaluates the attachment only if the
invoice also exists.

sentry-6635629791