[FIX] website: prevent error on missing attributes in embedded element
Currently, an error occurs when saving a website page that contains an embedded
element missing the 'data-oe-type', 'data-oe-field', or both attributes.

Steps to produce:
- Install the website module.
- Open the Website app and click Edit.
- Drag an Embed Code block and add one of the following examples:
  `<span data-oe-field='name' data-oe-model='res.partner' />`
        or
  `<span data-oe-type='int' data-oe-model='res.partner' />`
- Try to Save it.

Error:
TypeError: can only concatenate str (not 'NoneType') to str
KeyError: None

Root Cause:
At [1], the code tries to concatenate 'ir.qweb.field.' + el.get('data-oe-type'),
but when `data-oe-type` is missing, `el.get('data-oe-type')` returns None,
causing an error.
At [2], when the `data-oe-field` attribute is missing,
the code tries to access `Model._fields[field]`, resulting in an error.

Fix:
This commit adds validation for missing attributes in the embedded element,
ensuring a clear error message is raised instead of a crash.

[1]:
https://github.com/odoo/odoo/blob/4fca401148ed798b9c1d04674b44c3287ded5679/addons/web_editor/models/ir_ui_view.py#L67

[2]:
https://github.com/odoo/odoo/blob/4fca401148ed798b9c1d04674b44c3287ded5679/addons/web_editor/models/ir_ui_view.py#L71

sentry–6675421840