[FIX] website_sale_stock: fix error on choosing pick-up point
Steps to reproduce:
1. create a delivery method with Sendcloud, choose a shipping
product that uses a pick-up point
2. go to front-end and add some storable products to your
cart
3. make a sale order for a different customer, add Sendcloud
shipping, then attempt to select a pick-up point

Error:
```
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
Caused by: TypeError: Cannot read properties of undefined (reading 'length')
```

The error happens because the `website_sale_get_pickup_locations`
method that handles the route for pick-up point selection uses
https://github.com/odoo/odoo/blob/6209fec6957c933cd3a8a4644250e649444e67ba/addons/website_sale_stock/controllers/location_selector.py#L18
to check if the request comes from the front end or the back end,
but when there is an active cart for the current user,
this doesn't work when validating other sale orders from the
back end.

This commit changes the check to make sure it is working as expected.

opw-6267741