[FIX] mrp: handle parse-error if reinstall mrp module
When users try to reinstall the mrp, a traceback will be generated.

Error: while parsing /home/odoo/src/odoo/saas-16.4/addons/mrp/data/mrp_data.xml:17,
somewhere inside
<record id=stock.warehouse0 model=stock.warehouse>
            <field name=manufacture_to_resupply eval=True/>
        </record>

When users try to reinstall the mrp, a traceback will be generated.
This is because duplicate sequence records exist and raise the ParseError.

This commit solves the above issue by clean-up sequences mrp module
uninstallation time.

Apart from this commit, we are also updating the code of
the picking type and archiving it after the uninstallation of the module using
the 'ondelete' function.

code reference:
https://github.com/odoo/odoo/blob/16.0/addons/stock/models/stock_picking.py#L280
https://github.com/odoo/odoo/blob/16.0/addons/mrp/data/mrp_data.xml#L17

sentry-4489149490