[FIX] mail: prevent the error when the field name is not found in the model
This error occurs when we modify the 'Level Weight' in 'Partner Assignment'
within Contacts, then uninstall the 'Website' module, and subsequently attempt
to access the modified contact again.

Steps to reproduce:
- Install the 'website_crm_partner_assign' module
- Change the 'Level Weight' in 'Partner Assignment' in Contacts
- Now uninstall the 'Website' module
- Now open the changed contact again
- Error in terminal

Traceback: AttributeError
'NoneType' object has no attribute 'is_accessible'

The error in [1] occurred because the field name from 'tracking.field_id.name'
was not found in 'tracking.field_id.model'.

[1]- https://github.com/odoo/odoo/blob/d9d0b1c66dd608e475bdb7d29c162b6251b0f329/addons/mail/models/mail_tracking_value.py#L48-L49

sentry-5664351482

closes odoo/odoo#180479

X-original-commit: 8af712e4b4442c38493a97a51dff7d7aa4fa847f
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>