[FIX] l10n_din5008: wrong translation invoice
To reproduce the issue:
1. new db
2. localization in CH (french)
3. install module l10n_din5008
4. select an invoice
5. change invoice's client's language to
   french (CH)
6. print invoice
7. "Facture d'achat" should be "Facture client"

Error: invoice translation not correct

Invoice translation of this module is not
maintained by transifex
So invoice translation is changed manually in
fr.po

OPW-3186496

closes odoo/odoo#113776

Signed-off-by: Grazioso Andrea (agr) <agr@odoo.com>