[FIX] l10n_dk: prevent error when unlinking bank and cash accounts
This error occurs when attempting to delete the "Bank and Cash" account type
record.

Steps to reproduce:
- Install 'l10n_dk' and 'Accounting' module > Switch to 'DK Company'
- Go to 'Chart of Accounts' and groupby by 'Account Types'
- Try to delete 'Bank and Cash' record

Traceback:
AttributeError: 'account.account' object has no attribute 'read_group'

This error occurs because 'read_group' is used in the code, but it was
deprecated in [commit] and replaced by '_read_group'.

[commit]: https://github.com/odoo/odoo/pull/163300/commits/191ac027dd1e5133b0bcc72ab44358431c508a1c

sentry-7207582551

closes odoo/odoo#248313

X-original-commit: a250032055c2bb7a3d53a6e836e1039cf8762e20
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>