[FIX] l10n_in_pos: don't force update records
To reproduce the issue:
1) Initialize a database with l10n_in_pos in saas~17.2 or lower.
2) Go to point of sale>configuration>coins/bills.
3) Delete Records of Coins/bills.
4) Upgrade to the database to saas~17.4 or higher.

The records of pos.bill can be deleted, in point of sale module, these
records are created at initialization but they can be deleted. They
are not created later on as forcecreate="0". But in l10n_in_pos, these
records are forcecreated/forceupdated. so setting the forcreate="0".
Ensures that the records are created.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 559, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 387, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
Exception: Cannot update missing record 'point_of_sale.0_05'
```