[FIX] website_slide: prevent error when creating the attendee record.
Currently an error occurs when creating the attendee records.

Steps to Reproduce:

 - Install the website_slide module.
 - Go to Reporting > Attendees.
 - Go to either the Graph or Pivot View and click on any count value.
 - Open any attendee record and click on New.

SyntaxError: syntax error at or near ")"
LINE 18: WHERE SCP.id IN ()
^

This error occurs when creating an Attendee record. The _compute_next_slide_id
method runs every time the record is accessed and the next_slide_id field is
present in the view. Since next_slide_id is included in the form view,
clicking 'New' to open the form triggers _compute_next_slide_id, which
causes the error [1].

[1] https://github.com/odoo/odoo/blob/9f18013bc05e6657f5d41c05931fcdafad827d54/addons/website_slides/models/slide_channel.py#L91

This commit ensures that when the compute method runs and the record
has not been created yet, the next_slide_id is set to False.

sentry-6465821899