Cherry pick of 5267bfa5d2724f81a937c269f84790a5e87a6c53 failed
stdout:

stderr:
08:48:28.294932 git.c:344               trace: built-in: git cherry-pick 5267bfa5d2724f81a937c269f84790a5e87a6c53
error: could not apply 5267bfa5d27... [IMP] tests: partially backport classCleanups from CPython 3.8
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: