[FIX] base: prevent error when ISO code is not available in language
Currently, an error occurs when trying to create a payment for an invoice,
and ISO code is not available in the currently active language.

Step to produce:

- Install the 'account' module.
- Go to Settings / Translations / Languages, Open the currently active language,
and remove the ISO code from it.
- Create a new invoice add a customer and invoice line, and confirm it.
- Click on 'Register Payment',  and try to create a payment for that invoice.

TypeError: argument of type 'bool' is not iterable

An error occurs when the system tries to get ISO code from language at [1],
but it is not available.

Link [1]: https://github.com/odoo/odoo/blob/347b2eb1aa2ec576e9d228d2dd2019c38160e636/odoo/addons/base/models/res_currency.py#L181

To resolve the issue, add a condition to check if the ISO code is missing in the
language or not available, then set a default ISO code as 'en'.

Sentry-6108349395