Cherry pick of 1ceac7ce66ad8bfc7c35a48fe239ce7393814e42 failed
stdout:

stderr:
error: could not apply 1ceac7ce66a... [IMP] account: make tax report lines' constraints api.multi
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'