[FIX] core: avoid recursion error of check_access_rights()
When an AccessError is thrown, the error message needs to be translated
using _().  Then _get_lang() is called to create the translation, no
lang is found locals and will fall back on calling context_get() with
the current user, which will call re.lang.get_installed().  That call
will fail because the current user doesn't have access to res.lang,
here's where the recursion starts.

The recursion traceback looks like:

    File "/home/odoo/Documents/dev/odoo/odoo/addons/base/models/res_lang.py", line 281, in get_installed
      langs = self.with_context(active_test=True).search([])
    File "/home/odoo/Documents/dev/odoo/odoo/models.py", line 1637, in search
      return self.search_fetch(domain, [], offset=offset, limit=limit, order=order)
    File "/home/odoo/Documents/dev/odoo/odoo/models.py", line 1661, in search_fetch
      query = self._search(domain, offset=offset, limit=limit, order=order or self._order)
    File "/home/odoo/Documents/dev/odoo/odoo/models.py", line 5473, in _search
      model.check_access_rights('read')
    File "/home/odoo/Documents/dev/odoo/odoo/models.py", line 4226, in check_access_rights
      return self.env['ir.model.access'].check(self._name, operation, raise_exception)
    File "/home/odoo/Documents/dev/odoo/odoo/addons/base/models/ir_model.py", line 2061, in check
      resolution_info = _("Contact your administrator to request access if necessary.")
    File "/home/odoo/Documents/dev/odoo/odoo/tools/translate.py", line 508, in __call__
      translation = self._get_translation(source)
    File "/home/odoo/Documents/dev/odoo/odoo/tools/translate.py", line 525, in _get_translation
      lang = self._get_lang(frame)
    File "/home/odoo/Documents/dev/odoo/odoo/tools/translate.py", line 504, in _get_lang
      lang = env['res.users'].context_get()['lang']
    File "<decorator-gen-109>", line 2, in context_get
    File "/home/odoo/Documents/dev/odoo/odoo/tools/cache.py", line 104, in lookup
      value = d[key] = self.method(*args, **kwargs)
    File "/home/odoo/Documents/dev/odoo/odoo/addons/base/models/res_users.py", line 756, in context_get
      langs = [code for code, _ in self.env['res.lang'].get_installed()]
    File "<decorator-gen-100>", line 2, in get_installed
    File "/home/odoo/Documents/dev/odoo/odoo/tools/cache.py", line 104, in lookup
      value = d[key] = self.method(*args, **kwargs)
    File "/home/odoo/Documents/dev/odoo/odoo/addons/base/models/res_lang.py", line 281, in get_installed

Also, for another reason (explained after), this error is hidden and
ends in an infinite computation instead of a RecursionError.  And it
quickly prints tons of weird messages (infinites?) about the WeakSet:

    Exception ignored in: <generator object WeakSet.__iter__ at 0x7f548e558a50>
    Traceback (most recent call last):
      File "/usr/lib/python3.10/_weakrefset.py", line 64, in __iter__
      File "/usr/lib/python3.10/_weakrefset.py", line 33, in __exit__
      File "/usr/lib/python3.10/_weakrefset.py", line 58, in _commit_removals
    RecursionError: maximum recursion depth exceeded while calling a Python object

This is the result of the "except Exception" clause in
_get_translation() and the fact that the RecursionError is the result of
get_context() and get_installed() (both ormcached).

Anyway, the main issue is that the result of get_installed() depends on
the current user (for AccessError) but it shoudn't.  So we add a sudo()
in get_installed() to avoid the AccessError exception, which seems
perfectly legit in this case, as the method's purpose does not depend on
the current user.

Part-of: odoo/odoo#154177