[FIX] l10n_sa: fix error when computing SA TIN without VAT
Steps to Reproduce:
- Install the `l10n_sa` and `contacts` modules.
- Create a new contact and set the country to Saudi Arabia.
- Click the "+" sign next to the TIN field.
- Select "Tax Identification Number".

Error:
TypeError: 'NoneType' object is not subscriptable

Cause:
The onchange method tries to extract the SA TIN from the VAT even when the VAT
is not set. This causes an error when slicing the None value.

Fix:
Skip populating the SA TIN when the VAT is not set.

sentry-7716910106

closes odoo/odoo#289658

X-original-commit: 11378fa74cabf06b674af7bd77a7d32044486139
Signed-off-by: Seif Gneedy (segn) <segn@odoo.com>
Signed-off-by: Aditi Patel (adip) <adip@odoo.com>