[FIX] point_of_sale: extract UID from POS reference
When using another language than English, the UID of a POS order may be
incorrect

To reproduce the error:
1. Open a POS's configuration and enable "Manage Orders"
2. In Settings > Languages, add ans switch to:
    - French (BE) / Français (BE)
3. Start a POS session
4. Process an order
5. Open the orders managers

Error: the processed order is named "Commande de 00001-001-0001", the
"de" in the middle shouldn't be present

This is the combination of "Commande" and the UID of the order. The
latter is extract from the POS reference, which looks like "Commande
00001-001-0001" by removing the first 6 characters. It's ok in English:
from "Order 00001-001-0001", we have "00001-001-0001". But this won't
work in all other languages (specially for RTL languages)

The unique identifier of an order is a sequence of 12 digits:
https://github.com/odoo/odoo/blob/3e8d921318e86631b73c8c92c2e462fd0d761582/addons/point_of_sale/static/src/js/models.js#L2865-L2868
Knowing this, we can easily extract the UID from a POS reference

OPW-2538645
closes #71181
closes #71182

closes odoo/odoo#73876

X-original-commit: f5b23781cdf8a9e50c9a1fcd38ec704d4a4513fb
Signed-off-by: pimodoo <pimodoo@users.noreply.github.com>