[FIX] purchase: Check for downpayment when calculating Unit Price Product UoM
According to the constraint `_accountable_required_fields`, the field
`product_uom_id` is not required when `display_type` is set or when the line is
a downpayment. The first case has been patched, but not the second, which can
lead to errors during upgrades.

```
ValueError: Expected singleton: uom.uom()
```