[FIX] base: return False when uid is None
when i login with error password in rpc, odoo will raise this error:
psycopg2.ProgrammingError: operator does not exist: integer = boolean
LINE 1: SELECT 1 FROM res_groups_users_rel WHERE uid=false AND gid I...