[FIX] account_edi_ubl_cii: add account_edi module in depends
When user creates new invoice and tries to Send & Print,
a traceback will appear.

Steps to reproduce the error:
- Install 'account_edi_ubl_cii'
- Go to Invoicing > create new invoice
- Fill required fields > confirm > Send & Print > Send & Print

Error: A traceback appears:
AttributeError: 'account.move' object has no attribute
'_prepare_edi_vals_to_export'

https://github.com/odoo/odoo/blob/abc44e8027e4d3518b3de284f4773d6fbea20374/addons/account_edi_ubl_cii/__manifest__.py#L25
Here, 'account_edi' module is not in the depends.
So it will lead to above traceback.

From commit: https://github.com/odoo/odoo/commit/2d2faafb744abdb09f199ab85f11d317ee1d065e
'auto_install': True is removed from 'account_edi',
so when we install 'account_edi_ubl_cii', it will install invoice,
but due to this commit 'account_edi' will not be installed.

sentry-4380547757