[FIX] l10n_it_edi: Bill predictions, fix dependencies
After #38518, there are cases in which people uninstall l10n_it_edi so the following traceback is given when importing a PDF invoice (OCR):

```
File "/home/odoo/src/enterprise/saas-16.4/l10n_it_reports/models/account_move.py", line 9, in <lambda>
    lambda rec: self.env['account.edi.format']._check_filename_is_fattura_pa(rec.name)
AttributeError: 'account.edi.format' object has no attribute '_check_filename_is_fattura_pa'
```

We move everything back to l10n_it_edi, but the test will be excised.

Enterprise PR: odoo/enterprise#53452

closes odoo/odoo#148379

X-original-commit: 462c54c17498d4ca62d5d5dd62a85b02785569fb
Related: odoo/enterprise#53750
Signed-off-by: Josse Colpaert <jco@odoo.com>
Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>