[FIX] l10n_ar: prevent crash when sanitizing invalid VAT values
The system crashes when trying to sanitize invalid VAT inputs for Argentina
partners due to the assumption that the identification number can always be
safely cast to int().

Steps to reproduce:-
- Initialize a database with 'demo data'.
- Install the 'l10n_ar' module and switch to the 'AR Company'.
- Create a partner with:
             - Country: 'Argentina'
             - Identification Method: 'DNI'
             - Number: 'test'
- Observe the error.

Error:-
ValueError: invalid literal for int() with base 10: ''

Root cause:-
- The method '_run_check_identification' is introduced after this [commit](https://github.com/odoo/odoo/pull/179078)
- in this method, when [1] is executed, then 'get_id_number_sanitize' method
  is called.
- At [2], the error occurs because '_get_id_number_sanitize()' assumes the VAT
  is numeric after removing non-digit characters. If the VAT input is non-
  numeric (e.g., 'test'), it becomes an empty string '', and converting that to
  int('') raises an error.

Solution:-
- This ensures the function safely returns 0 when the ID number is falsy.

[1]: https://github.com/odoo/odoo/blob/2c019833bbc771866fb9a1c0021d87b8b07ed411/addons/l10n_ar/models/res_partner.py#L63

[2]: https://github.com/odoo/odoo/blob/2c019833bbc771866fb9a1c0021d87b8b07ed411/addons/l10n_ar/models/res_partner.py#L134-L135

sentry-6743438515

closes odoo/odoo#218810

Signed-off-by: Laurent Smet (las) <las@odoo.com>