[FIX] base: handle deletion of multiple records
This error occurs when we try to delete the multiple records of `ir.model` model

Steps to produce :
- Go to settings > Technical > Database structure > Models.
- Select the multiple records and try to delete the records.
- Error will be generated.

Error: Expected singleton: ir.model(621, 622, 623, 624, 426, 425, 416, 427, 638)

In this PR https://github.com/odoo/odoo/pull/133562 'if self.state == manual'
condition has been added but when we get multiple records in self a singleton
error occurs. To solve this issue the mapped has been used to only take
records having state manual at a time.

sentry-4502537032