[FIX] im_livechat: prevent error when giving feedback on livechat
Currently an error occurs when user tries to give feedback on livechat that has
a chatbot.

Steps to replicate:
- Install `im_livechat` with demo.
- Open Livechat > On Support Bot, Click `Configure Channel` from Kebab menu
  (3 dots menu).
- Go to Widget page > Copy the support link (bottom one) > and open it in an
  incognito tab.
- Open the chat > chat atleast once > Close the chat.
- Click on any of the smileys (i.e. give feedback) and click send.
- The error will occur on the terminal.

Error:
```
File '/home/odoo/src/odoo/saas-19.3/addons/mail/tools/discuss.py', line 228, in __init__
    assert bus_channel or not (notification_payload or notification_type), (
AssertionError: Notification parameters only make sense when a bus channel is passed.
```

Cause:
- As the livechat was managed by chatbot, it has no `livechat_agent_partner_ids`
  linked. This causes `rated_partner` [1] to be an empty recordset.
- So when initializing the Store [2] `rated_partner.sudo().user_ids` becomes an
  empty recordset. This causes the error to occur as the assertion fails [3] as
  the `bus_channel` is an empty recordset.

Solution:
- Updated the assertion to keep the behavior similar to `bus_send()` method.

[1]: https://github.com/odoo/odoo/blob/2b486f35235974584b3434c2ca93297db802ae81/addons/im_livechat/models/discuss_channel.py#L740
[2]: https://github.com/odoo/odoo/blob/2b486f35235974584b3434c2ca93297db802ae81/addons/im_livechat/models/discuss_channel.py#L760-L770
[3]: https://github.com/odoo/odoo/blob/2b486f35235974584b3434c2ca93297db802ae81/addons/mail/tools/discuss.py#L228-L230

sentry-7477572896

closes odoo/odoo#264561

Signed-off-by: Matthieu Stockbauer (tsm) <tsm@odoo.com>