Cherry pick of df09c62fb43179ad9ee7de43c0d03e3d9f717f55 failed
stdout:
Auto-merging odoo/addons/base/tests/test_ir_actions.py
CONFLICT (content): Merge conflict in odoo/addons/base/tests/test_ir_actions.py
Auto-merging odoo/addons/base/tests/test_ir_attachment.py
Auto-merging odoo/addons/base/tests/test_ir_model.py
Auto-merging odoo/addons/base/tests/test_res_config.py
Auto-merging odoo/addons/base/tests/test_views.py
Auto-merging odoo/addons/test_new_api/tests/test_new_fields.py
Auto-merging odoo/tests/common.py

stderr:
18:55:14.804548 git.c:463               trace: built-in: git cherry-pick df09c62fb43179ad9ee7de43c0d03e3d9f717f55
error: could not apply df09c62fb431... [FIX] base: Make tests demo data independent
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: