Cherry pick of 63153bce4addf82ba436cb6c1de48a0f1acaacf9 failed
stdout:

stderr:
error: could not apply 63153bce4ad... [FW][FIX] mail: correctly check all recipients when routing on aliases
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'