[FIX] website: prevent error when submitting the 'Send Email' form
Currently, an error occurs when submitting the 'Send Email' form.

Steps to Reproduce:

 - Install the website and web_studio modules.
 - Go to website > Click on Edit > Drag and drop form.
 - click the form and in actions select the more models, and select
   outgoing mails(mail.mail) model and save.
 - submit the form.

KeyError: 'website_form_signature'

This error occurs when submitting the "Send Email" form from the
website. If the form is saved without entering the recipient's email
(email_to). As a result, the email_to field is not present in the form.
The website_form_signature is added from [1], but due to the
condition at [2], the code at [1] is not executed. And when it is
accessed at [3], KeyError is raised.

[1]: https://github.com/odoo/odoo/blob/82639728f2bcb4e7786f120de2aeba3f5fbab209/addons/website/tools.py#L252

[2]: https://github.com/odoo/odoo/blob/82639728f2bcb4e7786f120de2aeba3f5fbab209/addons/website/tools.py#L236

[3]: https://github.com/odoo/odoo/blob/82639728f2bcb4e7786f120de2aeba3f5fbab209/addons/website/controllers/form.py#L88

This commit ensures that 'website_form_signature' is used if it is
available in kwargs.

sentry-6746753251