[FIX] l10n_sa_pos: prevent error when creating consolidated POS invoices
Currently, an error occurs when trying to create a consolidated invoice for
multiple POS orders associated with the same customer.

Steps to reproduce:

- Install the l10n_sa_pos module and switch to the SA company.
- Create two POS orders for the same customer without invoicing at checkout.
- Close the POS session and go to Point of Sale > Orders.
- Select both orders > click Create Invoice > confirm the action.
  (Make sure Consolidated Billing is enabled)

Error:
ValueError: Expected singleton: pos.order(8, 7)

Root cause:
At [1], the code accesses `self.date_order`, but when consolidated billing is
enabled, self contains multiple POS orders, causing an error.

Fix:
This commit prevents the error by ensuring that the current datetime is
assigned when creating a consolidated invoice, same as [2].

[1]:
https://github.com/odoo/odoo/blob/583bacdc8ad2b87b99b11d1e12dacf6e42edf22b/addons/l10n_sa_pos/models/pos_order.py#L13

[2]:
https://github.com/odoo/odoo/blob/583bacdc8ad2b87b99b11d1e12dacf6e42edf22b/addons/point_of_sale/models/pos_order.py#L828-L832

opw-5266908