[FIX] base: raise UserError if get Invalid value
When the 'Try to reconcile automatically your statement lines' scheduled action
is execute and if an invalid value is provided in the 'Parent Path' field,
the system tries to access that value, and an error will occur.

To reproduce the issue:

-Install the 'account_accountant' and 'web_studio' modules.
-Go to the Settings > Users & Companies > Companies.
-Open a current Company and add the 'Parent Path' field on the 'res.company'
form view using 'web_studio'.
-Provide only the '/' value to the 'Parent Path' field and save the record.

Error: ValueError: 'tuple index out of range' while evaluating
'model._cron_try_auto_reconcile_statement_lines(batch_size=100)'

To handle this situation, the code has been updated to ensure that if
the value is not appropriate then raise user error.

sentry-4398717767