[FIX] payment_adyen: log refusal reason for refused payments
Versions
--------
- 17.0+

Steps
-----
1. Enable Adyen as payment provider in test mode;
2. do an eCommerce checkout;
3. select Adyen as payment option;
4. use the following card details:
  - Number: 4111111111111111
  - expiry: 03/30
  - cvc: 737
  - name on card: CARD_EXPIRED
5. click Pay Now;
6. check order chatter on the backend.

Issue
-----
> Error: Adyen: Received data with invalid payment state: Refused

Refusal shouldn't be an invalid payment state.

Cause
-----
Commit 8162a850066a accidentally removed an `elif` branch that was added
by commit 97f8137bf99d9 specifically to handle refused payments.

Solution
--------
Re-add the `elif` branch.

opw-4481602

closes odoo/odoo#196700

X-original-commit: e0e34292d85d784560000126446f8cc33413f1ef
Signed-off-by: Morgane Demesmaeker <edm@odoo.com>