[FIX] hw_drivers: fix CUPS error when printer has too long name
CUPS has a limit on printer names of 127 characters, which means that if
a device has a very long device URI, it can exceed this limit and cause
an error when we try to add it to CUPS:

```
Failed to add printer 'dnssdPhotosmart%207520%20series%20%40%20Guillaume%E2%80%99s%20MacBook%20Air%20(2)_ipp_tcplocalcups?96d0de60-096c-3d08-5e2d-893393e10c2b'
Traceback (most recent call last):
  File "/home/pi/odoo/addons/iot_drivers/iot_handlers/interfaces/printer_interface_L.py", line 242, in set_up_printer_in_cups
    self.conn.addPrinter(name=device['identifier'], device=device['url'], **ppdname_argument)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cups.IPPError: (1024, 'client-error-bad-request')
```

We fix this error by truncating the identifier to 127 characters
maximum.

closes odoo/odoo#246298

X-original-commit: e2d28641ddca31c7a8c20302ed6fcca2e13df734
Signed-off-by: Louis Travaux (lotr) <lotr@odoo.com>
Signed-off-by: Max Whale (mawh) <mawh@odoo.com>