[FIX] mrp: prevent error on opening stock report
Currently an error occurs when user opens stock report after uninstalling mrp.

Steps to replicate:
- Install mrp.
- Uninstall mrp and open `Stock > Reporting > Stock`.

Error:
```
ValueError: Invalid field product.product.is_kits in condition ('is_kits', '=', False)
```

Cause:
- The `mrp` module overrides the `stock.action_product_stock_view` window action
  domain with `is_kits` field referenced inside [1].

- When mrp is uninstalled, the `is_kits` field is removed from `product.product`
  but the overridden action domain remains stored in the database. Opening the
  action then tries to evaluate a domain referencing a non-existent field,
  resulting in this error.

Solution:
- Restore the original `stock.action_product_stock_view` domain during mrp
  uninstallation to remove the `is_kits` condition.

[1]: https://github.com/odoo/odoo/blob/c8390638cae4b4dafb805bc0d3a4149fb5194934/addons/mrp/views/product_views.xml#L164-L166

sentry-7332688253

X-original-commit: 2a2a2c910958fae4414463374e2a2450d187ac37