[FIX] hw_scale: added field 'disable' to namedtuple 'ScaleProtocol'
Introduced at 5980caedac1
Getting error
TypeError: __new__() got an unexpected keyword argument 'disable'

closes odoo/odoo#28202