[FIX] l10n_ch: prevent error on QR invoice print
Steps to reproduce:
- Install the `l10n_ch` module and switch to a `CH Company`.
- Go to Invoicing Settings and enable `QR Codes`.
- Create a new invoice for the CH Company.
- In the `Other Info` tab, set `Payment QR-code` to `Swiss QR bill`.
- Confirm it and click `Print`.

Error:
TypeError: '_VirtualList' object is not callable

Root Cause:
At [1], the code incorrectly calls `pages` as a function using `round brackets`.
However, pages is a `_VirtualList` `object` that only supports index-based
access using `square brackets`.

Fix:
This commit prevents the traceback and ensures that invoices can be
printed successfully.

[1]:
https://github.com/odoo/odoo/blob/2b486f35235974584b3434c2ca93297db802ae81/addons/l10n_ch/models/ir_actions_report.py#L57-L58

opw-6215049

closes odoo/odoo#265338

X-original-commit: d2d8053037da9d04c5f85fa5f4d6f5999c7f5c38
Signed-off-by: Antoine Boonen (aboo) <aboo@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>