[FIX] web: Support reserved words as customer names
Steps:
- Have a customer named "constructor" (or any valid json prototype key value)
- Install `sale_management`
- Create a sale order with "constructor"
- Open Reporting -> Customers
- Traceback `Caused by: TypeError: groupedDataPoints[key].push is not a function`

This problem occurs because we use the client name directly in an object,
and “constructor” already exists in all objects but is not initialized
correctly, which raises a traceback.
One solution is to use `let object = Object.create(null)` instead of
`let object = {}`, which prevents inheritance of `Object.prototype`
properties.

https://github.com.com/odoo-dev/odoo/blob/5e74f04ff35ed3efa25be295567be41f42024692/addons/web/static/src/views/graph/graph_model.js#L451-L457

opw-5474691

X-original-commit: d645361a95037ac580d55e80bcb61d1eeb293efd