[FIX] base: add compatiblity with python 3.8
Partial backport of aeb1e592a6fbc91 to 11.0

Without this commit, trying to access a QWeb page (e.g. the login
page), was failing during the compilation as missing the argument
posonlyargs.

Traceback (most recent call last):
  File ".../odoo/addons/base/ir/ir_qweb/qweb.py", line 329, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
TypeError: required field "posonlyargs" missing from arguments

Error when compiling AST
TypeError: required field "posonlyargs" missing from arguments

ast.arguments does no validation but the compilation do

closes odoo/odoo#40406

Signed-off-by: Olivier Dony (odo) <odo@openerp.com>