[FIX] hr_recruitment: prevent error when change(update) all interviewers at once
Currently, An error occurs when trying to change(update) all interviewers at
once from the (hr)'Applications' list view.

Step to produce:

- Install the `hr_recruitment` module.
- Open Recruitment / Applications / All Applications and add the Interviewers
field in the list view, Select all records, and try to change or add
interviewers to any of them.

ValueError: Expected singleton: hr.applicant(800, 799, 798, 797, 819)

The error occurs because the system attempts to access a single value
from multiple records at [1].

Link [1]: https://github.com/odoo/odoo/blob/f1637a10db2f34ca3a272792079115e0192489f8/addons/hr_recruitment/models/hr_applicant.py#L384-L385

To resolve this issue, Use an iteration(for loop) to process each record
one by one.

Sentry-6229305438

closes odoo/odoo#199993

X-original-commit: 5b9a9b7a85b2fd74c0828c1cf498bb0450dfc3a9
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>