[FIX] l10n_no,l10n_de_skr03,l10n_de_skr04: remove chart template reference
As rewrite the whole chart template mechanism,
from here: https://github.com/odoo/odoo/commit/512574861691f425ec6a17f20fe4b586bb88a299
we need to remove chart template reference from
localization module. some of them are remaining.
so removed from norway, Germany localization in migration
script otherwise we got this error:

```
 from odoo.addons.account.models.chart_template import update_taxes_from_templates
ImportError: cannot import name 'update_taxes_from_templates' from 'odoo.addons.account.models.chart_template'
(/home/odoo/src/odoo/saas-16.2/addons/account/models/chart_template.py)
```