[FIX] l10n_mt: avoid TypeError when tax xmlid is missing
Issue:

During migration of Malta taxes, the script can fail when certain tax XML IDs
are missing for a company. If the XML ID does not exist,
env.ref(..., raise_if_not_found=False) returns None.
Trying to combine a recordset with None causes the migration to fail.
Due to recent [commit]

Traceback:
```py
    tax_7 |= env.ref(f'account.{company.id}_VAT_S_IN_MT_7_G', raise_if_not_found=False)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 6589, in __or__
    return self.union(other)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 6603, in union
    raise TypeError(f"unsupported operand types in: {self} | {arg!r}")
TypeError: unsupported operand types in: account.tax() | None
```

Solution:

Use a guard check with the walrus operator (:=) to assign and validate the
tax record before union.
This ensures that only existing tax records are added to the recordset,
preventing the crash.

OPW-6159300, 6149387

[commit]: https://github.com/odoo/odoo/commit/3b5b5d992214f8d37f96ed8c11536215bc65e5b5

closes odoo/odoo#264327

Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>