[FIX] account: allow payment journal to be changed
1. Create a bank payment P01
2. Create a second one P02
    - Journal: Bank
    - Amount: 123
3. Edit P02:
    - Journal: Cash
    - Amount: 456

Error: A UserError is raised "Cannot create unbalanced journal
entry[...]" This change should be possible.

When changing the journal, the account of the associated moves lines are
not updated. Since the amount is also changed, in
`_synchronize_to_moves`, `_seek_for_lines` is called and tries to find
the liquidity lines thanks to their `journal_id` and their `account_id`
(which, as said above, isn't updated). This lead to incorrect results
and thus, incorrect behavior.

OPW-2568002

closes odoo/odoo#75784

Signed-off-by: Laurent Smet <smetl@users.noreply.github.com>