[FIX] sale_mrp{,_margin}: fix dependency break on purchase_price This commit fixes premature usage of `purchase_price` field on sale.order.line model, before its definition in sale_margin module.
Since this test requires both sale_mrp and sale_stock_margin to pass,
this commit adds an auto-install bridge module that solely address this
issue.

Steps to reproduce:
- Install sale_mrp module
- Run tests (at least .test_kit_cost_calculation)

Problem:
Traceback:
AttributeError: 'sale.order.line' object has no attribute 'purchase_price'

See #100126

closes #104891

X-original-commit: https://github.com/odoo/odoo/commit/74b36c48f73710495e19c3ad258645f05e589a73

Co-authored-by: Thibault Libioulle <thibault.libioulle@aerospacelab.be>