[FIX] mrp: prevent traceback in MO allocation report
Issue:
----------------------------------------
When creating a manufacturing order and trying to allocate it to the desired
sale order or outgoing picking, a traceback is triggered:
`AttributeError: 'stock.move' object has no attribute 'group_id'.
Did you mean: 'grouped'?`

Steps to Reproduce:
----------------------------------------
- Install the `mrp` module and enable
  `Allocation Report for Manufacturing Orders`.
- Create a product with a BoM.
- Create a Sale Order or outgoing picking for the product.
- Create a Manufacturing Order and go to the allocation report.
- Try to assign it to the picking.
- Traceback is triggered.

Cause:
----------------------------------------
In PR odoo#212679, the `group_id` field was replaced by a many2many field
`reference_ids`.
However, the `_action_assign` method still tried to set the value of `group_id`
instead of `reference_ids`, causing the error.

After this Commit:
----------------------------------------
In this commit, we ensure that `reference_ids` is used and set properly instead
of `group_id`, allowing users to assign quantities to the desired picking
smoothly without errors.

Task ID: 5076863

closes odoo/odoo#227033

X-original-commit: 571b2a9d3bba4e68b6cbbeecae2a19e75913e734
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Sahil Koladiya (sako) <sako@odoo.com>