[FIX] mail: downgrade to 19.0 with chat hub data should not crash
Before this commit, when downgrading from 19.1 to 19.0 with chat hub
data from 19.1, i.e. chat windows or bubbles that are open, loading
web client would crash with following error:

```
KeyError: 'thread_model'
```

This happens because of mismatch of format of chat hub data in 19.0
and 19.1:

- 19.0 identifies channels with model "discuss.channel" and id
- 19.1 identifies channels with just id

When downgrading from 19.1 to 19.0, it attempts to getOrFetch a
thread to server by providing channel id but without passing a model.
The getOrFetch of 19.0 looks at thread level, so it cannot guess
providing just id means a channel, therefore it crashes due to
missing model to provide.

This commit fixes the issue by dropping the chathub local storage
data if the format of chathub data in local storage is invalid, i.e.
the identifying data of opened / closed should necessarily have id
and model. If no model is provided like with downgrade from 19.1 to
19.0, then it drops local storage and assumes no chat window or
bubbles is open.

Task-5223650

closes odoo/odoo#239504

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>