[FIX] l10n_id: invalid setup of QRIS API Key and Merchant ID
This error occurs because the bank's QRIS API Key and Merchant ID were set up
incorrectly.

Steps to reproduce:
- Install 'POS' and 'l10n_id' module
- Change company to 'ID Company'
- Create a new 'Warehouse' in Inventory
- Now create a new journal(eg: Test) in invoicing with 'Type' as 'Bank' > go to
  the internal link of 'Account Number' write any 'QRIS API Key' and
  'QRIS Merchant ID' and Save
- Now go to 'Payment Methods' and create a new one in POS(eg: Demo) with
  'Integration' as 'qr_code' and 'QR Code Format' as 'QRIS' > Select 'Journal'
  as 'Test' and Save
- Go to 'Clothes' > Open Session > Add product > Payment > select payment method
  as 'Demo' > Click 'retry'

Traceback: AttributeError
'str' object has no attribute 'get'

At [1], we are facing an error because 'data' contains the failed message in it,
and the status of the response is 'failed'.

[1]- https://github.com/odoo/odoo/blob/dd71d998796cf426527972a3feac6fdd040f3fe3/addons/l10n_id/models/res_bank.py#L101

sentry-6029900658

closes odoo/odoo#186528

X-original-commit: 89ee8bd9882fc9729b3aeabd9d28be629765ad12
Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>