[FIX] account_peppol: ensure partner peppol check returns an action
Steps to reproduce
------------------
* install `account_peppol`
* open a partner's list view
* select a contact
* on the top middle, click Actions > Verify Peppol

You should be met with a traceback:
`AttributeError: 'bool' object has no attribute 'setdefault'`

Cause
-----
`button_account_peppol_check_partner_endpoint` is expected to return an
action or a falsy value (no action to perform).

opw-3683612

X-original-commit: f1b473ad4312b29bd6a0a8c0b2cb848b3eec3b5e