[FIX] hr_recruitment_skills: pass `stage_id` correctly
Steps to reproduce:
1. Add a job position and configure it to require a skill
2. Add an application with the same skill
3. Go to the applications by the jobs and search for matching
applicants
4. Select the applicant and click on "Move to this Job Position"

Traceback:
```
psycopg2.ProgrammingError: can't adapt type 'hr.recruitment.stage'
```

The issue happens because in `action_add_to_job`, `stage_id` is
passed as the object itself, and not the id.

opw-4626114

closes odoo/odoo#205645

X-original-commit: 28d14168694bf3503fca7f37b3fae204e88094bc
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Ahmad Khanalizadeh (khah) <khah@odoo.com>