[FIX] event_product, sale, sale_timesheet: prevent error on installing module
Currently a 'ParseError' arises when the user installs the modules after
deleting the 'Service' Category in Invoicing.

Steps to reproduce:
- Install 'Invoicing' application (without demo data).
- Invoicing > Configuration > Categories > Delete 'Service'
- Now installs the modules (event_product, sale, sale_timesheet)

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError: while parsing /home/odoo/src/odoo/saas-18.1/addons/event_product/data/event_product_data.xml:4, somewhere inside
<record id="product_category_events" model="product.category">
            <field name="parent_id" ref="product.product_category_services"/>
            <field name="name">Events</field>
        </record>

The error occurs because the user deleted the category, and then installed the
modules, that reference the missing product category.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6235143606