[FIX] purchase: RFQ by mail needs login
To reproduce the issue:
1. Create an RFQ
2. Send it by email
3. Open link in email in incognito
4. URL in mail redirects to a login page

Error: Should be able to see the RFQ without being logged in

Backport of https://github.com/odoo/odoo/pull/87520/commits/c4bd3f450c571da1322acb464f837612d498647c
Which is a backport of https://github.com/odoo/odoo/commit/139e90027686b0471c3f2c9efa46d531c3abef5a
OPW-3175464