[FIX] account: fix validation error traceback
```
  File "/home/odoo/src/odoo/19.0/addons/account/models/account_tax.py", line 611, in _validate_repartition_lines
    raise ValidationError(_("Invoice and credit note distribution should have a total factor (+) equals to 100."))
odoo.exceptions.ValidationError: Invoice and credit note distribution should have a total factor (+) equals to 100.
```
- During the database migration, a traceback occurs because the total_pos_factor
https://github.com/odoo/odoo/blob/18.0/addons/account/models/account_tax.py#L558
is being calculated as 0. When this happens, the float_compare function
https://github.com/odoo/odoo/blob/18.0/addons/account/models/account_tax.py#L559
returns -1, which incorrectly satisfies the validation condition and
triggers a ValidationError.
- To resolve this, we need to add an additional condition to check whether
total_pos_factor is 0, similar to the condition already implemented here
https://github.com/odoo/odoo/blob/18.0/addons/account/models/account_tax.py#L562
in the code.

tbg-1970
opw-5228357

closes odoo/odoo#234816

X-original-commit: 2451f3fb85114d7bcfd59b2864298353d08ac670
Signed-off-by: de Wouters de Bouchout Jean-Benoît (jbw) <jbw@odoo.com>
Signed-off-by: Karna Modasiya (kmod) <kmod@odoo.com>