[FIX] phone_validation: confirm unblacklist phone number
This traceback raises when user gives phone number and clicks on
'unblacklist' and 'confirm' button.

To reproduce this issue:

- Install phone_validation
- Make developers mode on
- Open settings/Technical/Phone/Phone Blacklist
- Create a new record and give valid Phone Number
- Then click 'Unblacklist' button and 'Confirm' button

Error: A traceback :"ValueError: Invalid domain term ('number', 'in', '907856')"

On 'action_unblacklist_apply' method returns to call  '_remove' method in
'phone.blacklist' model.

https://github.com/odoo/odoo/blob/5a39b757b703fc2e3edb5b9d59631934cd40b819/addons/phone_validation/wizard/phone_blacklist_remove.py#L14-L22

Therefore in the above usecase '_remove' method uses 'numbers' argument for
searching in 'phone.blacklist' model, as 'self.phone' is a string and it leads to invalid
domain while searching for records.
See:
https://github.com/odoo/odoo/blob/5a39b757b703fc2e3edb5b9d59631934cd40b819/addons/phone_validation/models/phone_blacklist.py#L110-L115

Sentry-4275213194

closes odoo/odoo#127150

X-original-commit: 821136a3f2586852e2b7a299331c8cb79fe9a2d1
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>