[FIX] mail: use correct `poll_option_id` param in `store_poll_option_votes`
Since this https://github.com/odoo/odoo/pull/257062,
Previously, `store_poll_option_votes` expected
`pull_option_id` while the fetch payload from
`mail.poll.option` passed `poll_option_id`.

As a result, fetching poll option votes could raise:
    TypeError: WebclientController.store_poll_option_votes()
    got an unexpected keyword argument 'poll_option_id'

This commit updates the handler to use the correct `poll_option_id`
param name so it matches the payload and avoids the traceback.

It also adds the missing close button in the poll votes panel.

task-6237159