[FIX] base: handle the canceling statement due to lock timeout
 A cron `Base: Auto-vacuum internal data` is running, which is performing
`auto_vacuum`. When the time limit exceeds 10 secs, we face the above issue.

Error: LockNotAvailable: canceling statement due to lock timeout

This commit solves the above issue by rollback the statement if the
`auto_vacuum` time limit exceeds 10 secs.

sentry-3938940519