[FIX] onboarding: unlink progress when company_id is unlinked
Steps to reproduce issue:

1. Download Accounting (or Sales or just Invoices)
2. Open Accounting
3. Create Company 2 and switch to it
4. Open Accounting again
5. Remove Company 2
6. Open Accounting
7. You receive an error:

>     ValueError: Expected singleton: onboarding.progress(1, 2)

Explanation:

In `_compute_current_progress`, the filter to get `current_progress_id` accepts `onboarding.progress` with both the company in which the user is at the moment or no company at all.
https://github.com/odoo/odoo/blob/55f9a73c9daa45cb04f337995185364ff29691ab/addons/onboarding/models/onboarding_onboarding.py#L55-L69
This is due to the fact that some onboardings are not related to a company while others are.
After that, getting the `onboarding_state` will trigger an `ensure_one` check.

In the current case, an `onboarding.progress` with a `company_id` is not deleted once the company is deleted. Therefore the value becomes `False`. The `ensure_one` that comes after will throw an error because of it.

Suggested fix:

`ondelete='cascade'` will only remove `ondelete.progress` with an already set `company_id` once the company is removed. `onboarding.onboarding` with `is_per_company` set to False should not be concerned.

opw-3762382

closes odoo/odoo#157643

X-original-commit: f77727d280216bff044565c57bb968584f8aba64
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Signed-off-by: Stroobant Paul (stpa) <stpa@odoo.com>