[FIX] account_edi_ubl_cii: restrict XML export to posted invoices only
Currently, an error is raised when attempting to export the XML for a draft invoice.

**Steps to Reproduce:**
- Install the `account_edi_ubl_cii` module.
- Create an invoice with customer **OpenWood**.
- Without confirming the invoice, go to `Print > Export XML`.

**Error:**
`AttributeError - 'bool' object has no attribute 'replace'`

**Cause:**
In draft state, the invoice name is `False`, leading to an `AttributeError`
when calling `replace()` on bolean value. - [1]

[1] - https://github.com/odoo/odoo/blob/8bc24feca01a7d0e45606ac97e45ddf442670392/addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py#L32-L33

Restrict the XML export feature to only allow export for posted invoices,
where the name is always defined.

Sentry - 6695898207

closes odoo/odoo#215389

Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>