[FIX] html_builder, website: disable non-custom website form option list editing
Currently an error is generated when a user tries to submit their website
form, which is created as follows:

- Install `website_helpdesk`
- On the website, add a new form component with action as `Create a Ticket`
- Add an existing field `Priority` on the form and edit the first
  option `Low priority` as `Low` and save the component
- An error will be generated when the user submits the form with
  the edited option `Low`

Error: `ValueError: Wrong value for helpdesk.ticket.priority: 'High'`

This error occurs when a user edits an option and the modified value does
not exist in the field. In earlier versions, this issue did not arise because
users were not allowed to edit options of existing fields. However, after the
recent changes introduced in commit [1], the website builder was rewritten
using Owl and the new HTML editor. As a result, this scenario is no longer
handled correctly, which leads to the error.

This commit will fix the above issue by disabling the editing options when
the form field is an existing field.

[1]: https://github.com/odoo/odoo/commit/9fe45e2b7ddbbfd0445ffe25a859e67a316d02b2

Sentry-7175566174