[FIX] l10n_eg_edi_eta: remove wrong `tree` view type
The base view is a form view:
https://github.com/odoo/odoo/blob/e663d7bccf5f38589d162dba1c6cef6b74eec621/addons/product/views/product_views.xml#L359
https://github.com/odoo/odoo/blob/e663d7bccf5f38589d162dba1c6cef6b74eec621/addons/product/views/product_views.xml#L5

Without this change the upgrade to saas~16.1 fails:
```
Invalid custom view l10n_eg_edi_eta.product_normal_form_view_inherit_l10n_eg_eta_edi for model product.product
Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 701, in validate_view
    view._check_xml()
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 419, in _check_xml
    super(IrUiView, record)._check_xml()
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 478, in _check_xml
    raise err.with_traceback(e.__traceback__) from None
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 452, in _check_xml
    view._validate_view(combined_arch, view.model)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 1417, in _validate_view
    self._raise_view_error(_(
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 760, in _raise_view_error
    raise err from from_exception
odoo.exceptions.ValidationError: Error while validating view near:
<form string="Product Variant" __validate__="1" duplicate="false">
                <header>
                    <button string="Print Labels" type="object" name="action_open_label_layout" attrs="{'invisible': [('detailed_type', '==', 'service')]}"/>
The root node of a tree view should be a <tree>, not a <form>
```

closes odoo/odoo#110852

Signed-off-by: Christophe Simonis <chs@odoo.com>