[FIX] stock: multiple warehouses in replenishment
Company can have multiple warehouses,
when user open replenishment and company has multiple warehouses.
this will lead to below traceback.

Steps to reproduce the error:
- Go to 'Manufacturing' > Configuration > Settings > Enable Subcontracting
- Go to 'Contacts' > Create a Contact > Sales & Purchase >
  Open Subcontractor Location > Enable Replenish Location
- Go to 'Inventory' > Configuration > Warehouses > Create multiple warehouses
- Create a storable product > Create BoM > Set Subcontracting in BoM Type >
  Set already created contact in Subcontractors > Save
- Go to 'Purchase' > Set Subcontractor in Vendor > Add Product > Confirm Order
- Go to 'Inventory' > Operations > Replenishment

Error: A traceback appears:
'ValueError: Expected singleton: stock.warehouse(1, 2, 3, 4)'

https://github.com/odoo/odoo/blob/3864542914efcb9d4e3cabd3cfdeecb842e4f380/addons/stock/models/stock_orderpoint.py#L414
here, we can get multiple warehouses for a company.
So it will lead to above traceback.

sentry-4358838167

closes odoo/odoo#132977

X-original-commit: b90dfc98046e68803b112a03aa638de0842f12ea
Signed-off-by: William Henrotin (whe) <whe@odoo.com>