The Error is reproducible in the runbot here is an attached video with the steps: https://drive.google.com/file/d/1W1ZJG7aYueFa8Y24LSZlsil0caZB9mE5/view?usp=sharing
This happens because of :

1- cash rounding is enabled in the settings of accounting 2 - cash rounding by tax is chosen
3 - opening a vendor bill
4 - putting a decimal price and removing taxes
5- then choosing cash rounding by tax

The Error :
File "/home/odoo/odoo/odoo/addons/account/models/account_move.py", line 1570, in _compute_tax_totals
move.tax_totals = self.env['account.tax']._get_tax_totals_summary(
File "/home/odoo/odoo/odoo/addons/account/models/account_tax.py", line 2090, in _get_tax_totals_summary
max_subtotal, max_tax_group = max(
ValueError: max() arg is an empty sequence

opw-4558251 (related to ticket)