[FIX] core: allow Python identifiers as field names
Before 020ddc3a we allowed any Python identifier as column names. The
usual field definition `name = fields.FieldType(...)` restricts  `name`
to be a valid Python identifier. Forbidding it in 17.0 causes issues
during upgrades.

For example, with the model:
```py
class CustomModel(models.Model):
    _name = 'mymodule.custom.model'
    _description = "custom"

    année = fields.Char()
```

In 17.0 before this patch we get errors like:
```
  File "/home/odoo/src/odoo/17.0/odoo/tools/sql.py", line 150, in identifier
    assert IDENT_RE.match(name), f"{name!r} invalid for SQL.identifier()"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: 'année' invalid for SQL.identifier()
```

Co-authored-by: jepbarasgarov <jeas@odoo.com>