[FIX] mrp_subcontracting_dropshipping: use a sub-location
When using a sub-location of "Subcontracing Location" and a dropshipped
component, the purchase order doesn't have any dropship address.

To reproduce the issue:
(Enable debug mode)
1. In Settings, enable "Multi-Step Routes"
2. Create a new location L:
    - Parent: Physical Locations/Subcontracting Location
    - Type: Internal Location
3. In Rules, duplicate the rules of route "Dropship Subcontractor on
Order" and replace "Physical Locations/Subcontracting Location" with L
4. Create two products:
    - P_finished:
        - Type: Storable
        - Vendor: V_subcontractor
    - P_compo:
        - Type: Consumable
        - Vendor: V_compo
        - Routes: Dropship Subcontractor on Order
5. Edit V_subcontractor:
    - Subcontractor Location: L
6. Create a bill of materials:
    - Product: P_finished
    - Type: Subcontracting
    - Subcontractor: V_subcontractor
    - Components: 1 x P_compo
7. Create and confirm a purchase order:
    - Vendor: V_subcontractor
    - Products: 1 x P_finished
8. Open the purchase order linked with P_compo

Error: the Dropship Address is not defined

This address is defined thanks to the value of `partner_id`:
https://github.com/odoo/odoo/blob/aec7fcdb693729f432ae2341c00ef317b65fbcbc/addons/purchase_stock/models/stock_rule.py#L300
However, this key is missing

OPW-2721474

X-original-commit: ae940f8924b792e58a927de6eb1c928890c1687c