[FIX] sale_pdf_quote_builder: restrict user to upload corrupt pdf
When the header and footer pages of Quotation template contains corrupted pdf
then while previewing the quotation if the user clicks on view details or clicks
on action quote pdf then the user will face error.

Steps to produce:
- Sales > Configuration > Sale Orders > Quotation Templates.
- Create a new Quotation Template > Fill the necessary details.
- In PDF Quote Builder > Header Pages > Add a pdf which is corrupted, or does
  not have EOF.
- Create a new quotation, add the newly created quotation template.
- Save the details and preview the quotation.
- In the preview of quotaion click on `View Details` button.
- or after saving the details open the tree view of quotations
  select the quotation in which you kept newly created quotation
  template and then click on print then `PDF Quote`.

Error: `PdfReadError: EOF marker not found`

This commit does not allow user to upload corrupted pdf as header and footer
pages of Quotation templates.

sentry-4621647394