[FIX] l10n_id: fix ValueError
Error-1 :
```
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system:
account.1_l10n_id_domestic_fiscal_position
```

Error-2 :
```
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: account.1_tax_luxury_sales
```

Reason-1 :
- In this commit new account.fiscal.positions were added and linked to acc.tax
   using fiscal_position_ids
https://github.com/odoo/odoo/commit/e342a45aceb60b44052c5d52e9ecc35a9a7340da
- In this migration script, while creating taxes it didnt find fiscal positions,
  so need to create them first.

Reason-2 :
- original_tax_ids was also added in same commit, if client deleted those tax,
  It needs to be created first too.

- upg : 4341887
- opw : 6285978