[FIX] project: Allows users to view sub-tasks in kanban mobile view
Example of steps:
- Install `industry_fsm`
- Create a task with a subtask
- Enable mobile view with devtools
- Open a task
- Navigate to sub-tasks tab
- Traceback

```
TypeError: undefined is not an object (evaluating 'ctx['record'].parent_id.raw_value')
```

parent_id was missing from "view_task_kanban"

opw-5981990

closes odoo/odoo#253623

Signed-off-by: Hubert Van De Walle <huvw@odoo.com>