[FIX] stock: return empty recordset if no rule found
When _get_rule does not find any rule, it returns False. This
could create some tracebacks as we mostly expect a stock.rule.

It will give:
if False in <recordset>:
Hence a traceback:
TypeError: unsupported operand types in: False in stock.rule()

By applying these changes will resolve this issue.

Sentry-4206998573

X-original-commit: d6a0b9810ffc7fad68ebf7b13902747d43024455