[FIX] mrp: fix quantity edition in Produce wizard
- Create a Product and a BOM for it (i.e. Product X)
- Go to Manufactoring > Operations > Manufacturing Orders and create a MO for Product X
- Mark as Todo and click on Produce
- On Produce Wizard, add a Component line with any Product and edit Quantity to produce
An AttributeError is raised: "'mrp.product.produce.line' object has no attribute 'finished_workorder_line_id'"

"_workorder_line_ids" method can either return "mrp.workorder.line" records or "mrp.product.produce.line"
and "finished_workorder_line_id" does not exist in "mrp.product.produce.line" model.

The code generating the issue can be moved to an override method in "mrp.workorder" model
as it should only be executed for Work Orders.

opw-2439172