[FIX] auth_timeout: refresh when check identity dialog is displayed
If the check identity dialog is displayed and the window is refreshed
by the user (F5),
the dialog is supposed to be shown again when catching the
`CheckIdentityException` from the server following the rpc call,
through the error handler `checkIdentityErrorHandler`.

It wasn't because the service `check_identity` was not ready
during the loading, with `useService("check_identity")`,
it leaded to a javascript error:
```
@web/core/error_service: handler "checkIdentityErrorHandler" failed with "TypeError: Cannot read properties of null (reading 'component')" while trying to handle:
RPC_ERROR: Odoo Session Expired
    RPC_ERROR
        at makeErrorFromResponse (:8069/web/assets/debug/web.assets_web.js:32897:19) (/web/static/src/core/network/rpc.js:48)
        at XMLHttpRequest.<anonymous> (:8069/web/assets/debug/web.assets_web.js:32974:27) (/web/static/src/core/network/rpc.js:125)
```

closes odoo/odoo#222773

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>