[FIX] sale_stock_margin: prevent division by zero for `purchase_price`
Steps to reproduce:
- Install 'sale_stock_margin' module
- Create SO > Create product with category -> 'Costing Method' : 'FIFO'
- 'Confirm' SO > Change product 'Quantity' to zero

Traceback:
ZeroDivisionError: float division by zero

At [1], this error occurs because both 'product_uom_qty' and 'qty_delivered'
are '0', resulting in a denominator of zero, which is not allowed.

[1]: https://github.com/odoo/odoo/blob/a884794ebfc8145c61bb34908093f00246f224ff/addons/sale_stock_margin/models/sale_order_line.py#L23

Issue also occurs when 'product_uom_qty' = 0 and 'qty_delivery' < 0
since `qty_from_delivery + qty_from_std_price` = 0 in this case.

Expected result:
- If both `product_uom_qty` = `qty_delivered` = 0 => fallback on
  standard_price (default behavior when only `sale_margin` installed)
- If `qty_delivery <= 0` => fallback on `standard_price` to avoid
  inconsistent values for return moves, i.e. value would vary depending
  on whether or not the return is linked to a delivery (i.e.
  `price_unit_from_delivery`) whereas a return not linked to a delivery
  will default to `standard_price`

sentry-6978885438

closes odoo/odoo#233418

Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>