[FIX] mrp: prevent error when clicking on overview in mo
When the quantity of components is negative in mo and user clicks on
the overview button.
a traceback will appear.

Steps to reproduce the error:
- Install 'mrp' and 'purchase'
- Create product A > In Purchase, add vendor > In Inventory, Select Buy and
  Replenish on Order (MTO) in Routes > Save
- Create one MO > Select any product > In components, Select product A >
  In To consume, Set 10 for ex. > Confirm
- Click on Purchases smart button > Confirm Order > Receive Products > Validate
- Go back to MO > Set negative value in Quantity (ex. -1) > Save
- Click on Overview

Error: A traceback appears:
'AssertionError: precision_digits must be a non-negative integer, got 0.01'

https://github.com/odoo/odoo/blob/2c89fae7bc3e026425a4f02c4a70e4a87083560d/addons/mrp/report/mrp_report_mo_overview.py#L771
Here, In the above line 'precision_rounding' is missing.
So, it will lead to the above traceback.

This commit will prevent the negative quantity of component product.

Sentry-5729142241

closes odoo/odoo#178789

X-original-commit: 79bfce02c92f4fefba5189702976f4061cf1efac
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>