[FIX] stock: prevent keyerror when reloading page
When the customer opens the product from Physical Inventory and tries to reload
the page, a traceback will appear.

Steps to reproduce the error:
- Go to Inventory > Operations > Physical Inventory
- Open any product > reload the page

Error: A traceback appears:
'KeyError: views'

https://github.com/odoo/odoo/blob/a0af91d2a7fbf22b610240497a791fa6cb63cc25/addons/stock/models/stock_quant.py#L390-L398
Here, 'views' key is missing in the action.
When the user refreshes the page, 'load_breadcrumbs' method will be called here.
https://github.com/odoo/odoo/blob/afb35b9ea5392eb097e4fc7689cb98a64396aef9/addons/web/controllers/action.py#L90

In the action, 'views' key is not present.
so it will give the above traceback.

Earlier, if the 'views' key was not present in the action, It worked fine.
because 'view_id' was enough for the action.
since 'load_breadcrumbs' method, if 'views' key is not present in the action,
It will give the above traceback.

sentry-5132471164