[FIX] purchase_stock,mrp_subcontracting_purchase: decrease POL qty
When decreasing the qty of a subcontracted POL, it can create an
unexpected receipt

To reproduce the issue:
1. Create a BoM for a subcontracted product P
2. Create and confirm a PO with 5 x P
3. Process the receipt
4. Return one
5. Update the POL qty to 4

Error: a new receipt is created for 3 x P. When updating the POL,
nothing should happen with the receipts

Updating the POL qty leads to the create/update of the related picking:
https://github.com/odoo/odoo/blob/1495b54aa452498c79f4178c2e38426b1b423e66/addons/purchase_stock/models/purchase.py#L426
And this will lead to `_prepare_stock_moves`:
https://github.com/odoo/odoo/blob/1495b54aa452498c79f4178c2e38426b1b423e66/addons/purchase_stock/models/purchase.py#L447-L450
Where we will define the values of the new SM (for the new qty).
However, there are two similar issues: to get the current qty, we
sum the quantities of the incoming/outgoing stock moves. But, the
condition is incorrect and we therefore consider the subcontracting
return as an incoming qty. So, this current qty is incorrect. Then,
we get the dest moves to compute some quantities to push/attach.
Here is the second issue, the filter condition to exclude the return
SM is incorrect: again, we don't exclude the subcontracting return

OPW-3515275

closes odoo/odoo#139957

X-original-commit: 7767c9e14230902826da3f17c94797b9698e11fa
Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>