[FIX] base: check also inherited stored fields
Since odoo/odoo@5b1482a0 we cannot add any manual field to `res.users`.
We are always faced with the error:
```
... fields used for ordering must be present on the model and stored.
```
```
>>> u=self.env['ir.model'].search([('model','=','res.users')])
>>> u._check_order()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    u._check_order()
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_model.py", line 269, in _check_order
    raise ValidationError(_("Unable to order by %s: fields used for ordering must be present on the model and stored.", field))
odoo.exceptions.ValidationError: Unable to order by name: fields used for ordering must be present on the model and stored.
```

The reason is that `res.users.name` field is inherited from the parent
model `res.partner`. Similarly if we install `base_automation` we cannot
add any field to `base.automation` model, because they are ordered by
`sequence` coming from its parent model.

In this patch we propose to extend the check for field used in `_order`
to inherited stored fields.

closes odoo/odoo#187971

X-original-commit: fc1ccfa130d012426fcd6c94ff480b78d84af2b7
Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>