[FIX] point_of_sale: prevent error when creating invoice for pos order
When a user tries to create an invoice for a PoS order
a traceback occurs.

Steps to reproduce the error:
- Install "point_of_sale" and "sale_stock_product_expiry" with demo data
- Go to Settings > Enable Display Lots & Serial Numbers on Invoices
- Create a product > Tracking: By lots >
  Enable Expiration Date in Inventory tab > Save
- Create a lot number and add on hand quantity for the product
- Add the product into the Furniture Shops PoS Product Categories
- Open Register of Furniture Shop > Add the product > set customer
  > Payment > Uncheck invoice > Pay
- Go to Point of Sale > Orders > Orders > Open that Order > Click Invoice

Traceback:
"AttributeError: 'pos.pack.operation.lot' object has no attribute 'expiration_date'"

https://github.com/odoo/odoo/blob/039c5139119c9f59bcd999afebf61145be1f5b27/addons/point_of_sale/models/account_move.py#L58
When the Invoice button is clicked, "_extract_extra_invoiced_lot_values"
method is called.
But here, "lot" is a "pos.pack.operation.lot" record. which does not contain
"expiration_date" field.

https://github.com/odoo/odoo/blob/039c5139119c9f59bcd999afebf61145be1f5b27/addons/sale_stock_product_expiry/models/account_move.py#L9-L12

The method "_extract_extra_invoiced_lot_values" is designed to work with
"stock.lot" record.

Solution:
Ensure "_extract_extra_invoiced_lot_values" is called with the corresponding
"stock.lot" record instead of "pos.pack.operation.lot".

sentry-7375746210