[FIX] core: create record with computed inverse x2m field
The use of a computed inverse o2m field does not correctly work when
creating the record of the main model.

To reproduce:
(Need stock)
1. In Settings, enable "Storage Locations"
2. Create a new Storage Category
   - Make sure to have one Capacity by Product

Error: on save, the Capacity by Product disappears. Yet, if the user
reloads the page, the capacity will be back.

First, few details about the Storage Category model. We are dealing
with the field `product_capacity_ids`, a computed inverse o2m field:
https://github.com/odoo/odoo/blob/afd16e672e74bc48f8c9853ced79c41034e79423/addons/stock/models/stock_storage_category.py#L15
Its content is a subset of the `capacity_ids` field:
https://github.com/odoo/odoo/blob/afd16e672e74bc48f8c9853ced79c41034e79423/addons/stock/models/stock_storage_category.py#L14
So, its compute simply get a subset of `capacity_ids` and its inverse
will write some values on `capacity_ids`:
https://github.com/odoo/odoo/blob/afd16e672e74bc48f8c9853ced79c41034e79423/addons/stock/models/stock_storage_category.py#L39-L41

Now, back to the issue. When we `web_save` the category, at some
point in the create process, it leads here
https://github.com/odoo/odoo/blob/bdb24afbf85f4d58722db493f725dd95c5780ff7/odoo/orm/models.py#L4389-L4408
Where we want to resolve all the pending inverse. To do so, we first
update the cache (L4401) and we then call the inverse methods (L4408).
In the above case, it means that we first update the value of
`product_capacity_ids` in the cache. The value we are passing is a
`Command.CREATE` value. In that case, when converting the value for
the cache, we actually create a `NewId` record:
https://github.com/odoo/odoo/blob/ae55f5b494005a1e7566c819592f7dd64623c3fd/odoo/orm/fields_relational.py#L513-L516
When running the inverse, we write this record on `capacity_ids` (cf
the code quoted above). This will lead to the actual creation of the
capacity record.

But... Here is where the problems begin: we have updated the cache
with a `NewId` value and define `capacity_ids` with an existing
record. However, we don't update anything in the cache. As a result,
at the end of `web_save`, we do a `web_read`. It will lead here:
https://github.com/odoo/odoo/blob/bdb24afbf85f4d58722db493f725dd95c5780ff7/odoo/orm/models.py#L3427
Where we convert the value of `product_capacity_ids`. Since
available in the cache, we will use the `NewId` value and convert it,
i.e.: we will return the `.ids` of the recordset:
https://github.com/odoo/odoo/blob/ae55f5b494005a1e7566c819592f7dd64623c3fd/odoo/orm/fields_relational.py#L569-L570
Which means... The actual IDs, excluding the `NewId` one.

This explains why the line suddenly disappears on save. Then,
reloading the page will trigger the compute based on `capacity_ids`.
This field is correctly defined, so will do the compute -> the line
will appear.

Since we update the cache to compute the inverse, we should then
clear that cache to ensure proper consistency with what happened
during the inverse.

OPW-4915087

closes odoo/odoo#224995

X-original-commit: 008d2cd27204d7895033026bcbabab5b2ac6e0df
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>