Cherry pick of 0141285fcf3425c37ac4634196a2b7936d0adadc failed
stdout:
Auto-merging addons/website_slides_survey/i18n/website_slides_survey.pot
CONFLICT (content): Merge conflict in addons/website_slides_survey/i18n/website_slides_survey.pot

stderr:
13:15:52.978001 git.c:463               trace: built-in: git cherry-pick 0141285fcf3425c37ac4634196a2b7936d0adadc --strategy ort
error: could not apply 0141285fcf34... [FIX] website_slides_survey: restrict creation of certification on fly
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: