[FIX] l10n_it_edi: Errors in warnings_message -> actionable errors migration code
The compatibility was broken in a couple of points, clients
are required to update the `l10n_it_edi` or cannot send invoices
to the Italian EDI. Updating the module fixes the errors.

These two errors may appear:

```
[...]
  File "/home/odoo/work/odoo/odoo/fields.py", line 1216, in __get__
    raise ValueError(f"Compute method failed to assign {missing_recs}.{self.name}")
ValueError: Compute method failed to assign account.move.send(<NewId 0x7ff2da360eb0>,).l10n_it_edi_warning_message

[...]
  File "/home/odoo/work/odoo/addons/l10n_it_edi/wizard/account_move_send.py", line 57, in _compute_l10n_it_edi_warning_message
    action = error_data['action']
             ~~~~~~~~~~^^^^^^^^^^
KeyError: 'action'
```

Original broken PR: odoo/odoo#142596

closes odoo/odoo#152986

X-original-commit: 355878cfb7b431df8b78af8977cfad61a10bba12
Signed-off-by: Josse Colpaert <jco@odoo.com>