Cherry pick of a323af20de1940c14cd962f658d7265074b899ec failed
stdout:

stderr:
15:59:45.789734 git.c:344               trace: built-in: git cherry-pick a323af20de1940c14cd962f658d7265074b899ec
error: could not apply a323af20de1... [FIX] fleet: correct cost date on recurring costs creation
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: