[FIX] base_setup: nightly documentation links test
AssertionError: 404 != 200 : The following link is broken: 'https://www.odoo.com/documentation/19.1a1/applications/marketing/sms_marketing/pricing/pricing_and_faq.html'
The wrong version tag was used when checking documentation links validity,
making the nightly test fail every night.

closes odoo/odoo#232361

Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>