[FIX] l10n_sa_edi: fix wrong edi content returned
The `_l10n_sa_get_invoice_content_edi` function is used to download the
edi_content of an edi_document when this edi_document is in error. This
function should return the xml encoded as a bytes, as it is then encoded
in base64 in account_edi/models/account_edi_document.py otherwise a

closes odoo/odoo#131729

Typeerror: "a bytes-like object is required, not 'dict'" is raised.
Signed-off-by: Josse Colpaert <jco@odoo.com>