[FIX] sale_stock: resist if write_date is null
If account_move_line.write_date is False/None/Null there is an error like below.
TypeError: '>' not supported between instances of 'bool' and 'datetime.datetime'.
Now also support this case