[FIX] l10n_gcc_pos: separate RTL and LTR words
When printing a ticket, if some lines mix RTL and LTR words, the
rendering won't be correct

To reproduce the issue:
(Need l10n_sa. Use demo data)
1. Switch the company: SA Company
2. Create a point of sale POS
    - Setup a direct device to print the tickets
3. Start POS
4. Process an order and print the ticket

Error: On the printed ticket (not the displayed one, which is correct),
some Arabic words overlap (see for instance the "Served by").

When printed the ticket, the latter is converted into an image thanks to
`html2canvas`. However, we need to add a space to separate LTR and RTL
words, otherwise the rendering won't be done properly. A similar issue
can be observed if the user language is AR: some other rendering issues
can be noticed on the ticket.

OPW-2704550

closes odoo/odoo#81899

X-original-commit: 86a20f7ef1b93eb099110feec5bca05b3a8d9a39
Signed-off-by: Trinh Jacky (trj) <trj@odoo.com>