[FIX] mrp: fix traceback new operation
Go to the menu Manufacturin / Configuration / Operations (need to enable Work order option), click on new, got a traceback:

...
  File "/home/odoo/Documents/dev/odoo/addons/mail/models/mail_thread.py", line 464, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/Documents/dev/odoo/odoo/orm/models.py", line 4623, in _compute_field_value
    determine(field.compute, self)
  File "/home/odoo/Documents/dev/odoo/odoo/orm/fields.py", line 73, in determine
    return needle(*args)
  File "/home/odoo/Documents/dev/odoo/addons/mrp/models/mrp_routing.py", line 110, in _compute_time_cycle
    operation.cycle_number = float_round(quantity / capacity, precision_digits=0, rounding_method="UP")
ZeroDivisionError: float division by zero

Fix it by adding a fallback with 1 as capacity.
Bug found by adding a test on all form view in https://github.com/odoo/odoo/pull/209587 PR. But need to backport this part.