[FIX] point_of_sale: pass noupdate True for pos load demo data
when database uploaded without demo data and there is no
any valid pos product in point of sale, and customer used
load demo data from point of sale frontend screen, then
it will create demo record from this file which was actually defined in point_of_sale/data/point_of_sale_onboarding_main_config.xml
with noupdate= False.

but as this xmlids has been created from python file using load samples, it was noupdate=False.

so during upgrade as there was no demo file loaded, and this entry are with noupdate='f'
ORM try to remove those recod , pos session too.
in _process_end during upgrade from 17.0 to
saas-17.1, and which was create issues as
that pos session linked with account bank statement lines which was
linked to journal entry so it will try remove journal entries which
was partially reconciled.
so we need to set noupdate=True in file:
point_of_sale/data/point_of_sale_onboarding_main_config.xml
 and also in python function `_load_onboarding_data`

see:
https://github.com/odoo/odoo/blob/1648ee1abff1ae12b3933baa85a2e048fa2eb557/addons/point_of_sale/models/pos_session.py#L2247

```
 File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_model.py", line 2561, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_model.py", line 2490, in _process_end_unlink_record
    record.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/point_of_sale/models/pos_session.py", line 517, in unlink
    self.statement_line_ids.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_bank_statement_line.py", line 395, in unlink
    moves.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/sale/models/account_move.py", line 30, in unlink
    res = super(AccountMove, self).unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_move.py", line 2770, in unlink
    self.line_ids.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_move_line.py", line 1672, in unlink
    self._check_reconciliation()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_move_line.py", line 1322, in _check_reconciliation
    raise UserError(_("You cannot do this modification on a reconciled journal entry. "
odoo.exceptions.UserError: No puede hacer esta modificación en un asiento conciliado. Puede cambiar algunos campos no legales, o romper antes la conciliación.
Asiento (id): CSH1/2024/00002 (5)
```

closes odoo/odoo#168726

Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>