Cherry pick of 300bb53dff891f0d2bae8a2c8c2f1c4c4b404236 failed
stdout:

stderr:
21:28:18.136269 git.c:344               trace: built-in: git cherry-pick 300bb53dff891f0d2bae8a2c8c2f1c4c4b404236
error: could not apply 300bb53dff89... [FIX] account: matched move lines should be marked as reconciled
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: