[FIX] account: allow only positive number for prefix and suffix in sequence
This traceback arises when the user gives alphabets or special characters in
prefix or suffix for 'Lock Posted Entries with Hash' enabled journal sequences.

To reproduce this issue:

1) Install 'Invoicing' and make sure developer mode is On
2) Open 'settings/groups/Show Accounting Features - Readonly'
3) Add 'Mitchel Admin' to that group.
4) Open 'Invoicing/Configuration/Journals/Customer Invoices' record
5) Enable 'Lock Posted Entries with Hash' in 'Advance Settings
6) Open 'Sequences' from 'Settings/technical'
7) Open the 'Securisation of secure_sequence_id - Customer Invoices'
   sequence record
8) Give any alphabet to prefix or suffix like (INV-2023-) and save.
9) create a new invoice with the 'Customer Invoices' journal.

Error: 'ValueError: invalid literal for int() with base 10: 'INV-2023-002''

[1] On the '_get_new_hash' method in 'account.move', 'secure_seq_number' is
    is converted to an integer using the 'int()' function.

[2] Here 'secure_sequence_number' is getting value from
    'journal_id.secure_sequence_id.next_by_id()'.

[3] In that 'next_by_id()', prefix and suffix are used to get sequence number.

When the user enabled 'restrict_mode_hash_table' a new sequence is created.

In that sequence, the user gives any alphabet or special character to a prefix
or suffix. It leads to the above traceback, as the 'int()' function is used to
convert that sequence number.

See:-

[1]
https://github.com/odoo/odoo/blob/883c03a06c092c0f8a90ac590b1fe8e40e4f54cb/addons/account/models/account_move.py#L2935-L2943

[2]
https://github.com/odoo/odoo/blob/883c03a06c092c0f8a90ac590b1fe8e40e4f54cb/addons/account/models/account_move.py#L2122-L2125

[3]
https://github.com/odoo/odoo/blob/883c03a06c092c0f8a90ac590b1fe8e40e4f54cb/odoo/addons/base/models/ir_sequence.py#L237-L238

sentry-4477040897