[FIX] stock: prevent printing traceability report that has no lines
Currently when the user refreshes the traceability report and tries to print the
report, they face a traceback

Issue1:
Steps to produce:
- Install Inventory
- From settings Enable 'Lots & Serial Numbers'
- Go to Lots/Serial Numbers > Create a new Lots and Serial Number and assign a
  product to it.
- Traceability > Refresh the page > Print

Observed Behaviour:
A traceback is raised saying KeyError: 'false'

Root cause:
This error occurs because when the user refreshes the page the context gets
cleared so the 'model' key becomes false at:
https://github.com/odoo/odoo/blob/e5ab4821f9cbcb6871b8e2399828ae626a1878cb/addons/stock/static/src/client_actions/stock_traceability_report_backend.js#L53-L65

After pressing print active model onClickPrint() is called
https://github.com/odoo/odoo/blob/e5ab4821f9cbcb6871b8e2399828ae626a1878cb/addons/stock/static/src/client_actions/stock_traceability_report_backend.js#L120-L131

report route on python side is called which calls `get_pdf` at
https://github.com/odoo/odoo/blob/e5ab4821f9cbcb6871b8e2399828ae626a1878cb/addons/stock/controllers/main.py#L23-L28

since active_model is 'false' the system tries to do self.env['false']
causing the key error at:
https://github.com/odoo/odoo/blob/e5ab4821f9cbcb6871b8e2399828ae626a1878cb/addons/stock/report/stock_traceability.py#L213-L215

Issue2:
Steps to produce:
- Install Manufacturing without demo data.
- Enable Lots & Serial Numbers in Settings.
- Create two products: Car and Engine.
- Configure Engine to use Unique Serial Number tracking
  (Inventory →Traceability).
- Set the on-hand quantity of Engine to 1 with serial number 0001.
- Create a BoM for Car using Engine as a component.
- Create and confirm a manufacturing order for Car.
- Click Consumed for the component and click Produce All.
- Navigate to Lots & Serial Numbers → Engine → 0001 → Traceability.
- Click the arrow next to the manufacturing order reference, refresh then click
  Print.

Observed Behavior:
TypeError: can't access property "replace", this.controllerUrl is undefined

Root cause:
The issue also occurs because of context getting cleared, but now since this
client action is called via javascript side
https://github.com/odoo/odoo/blob/3851c66b896e3c5cd5034603356c88ebbb64b6b4/addons/stock/static/src/client_actions/stock_traceability_report_backend.js#L105-L118
the URL specified  in this action also gets cleared from the context causing
controller URL to become undefined and causing above traceback at
https://github.com/odoo/odoo/blob/3851c66b896e3c5cd5034603356c88ebbb64b6b4/addons/stock/static/src/client_actions/stock_traceability_report_backend.js#L120-L125

Solution:
Hide the Print button when there are no operation lines, since generating a
printout is not meaningful in that case. This also prevents the print flow from
being triggered when the required operation data is unavailable.

opw-6478098