[FIX] website: prevent editing on search icon
When the user tries to edit search icon of search bar in website > shop
using web_editor and then save the changes, the error occurs.

To reproduce the issue:
- Install eCommerce module.
- Go to Website > Shop > Open Editor.
- Click on search icon in the search bar and edit inline text.
- Then save the changes the error will occur at the backend.

Error: ValueError: not enough values to unpack (expected 1, got 0)

The issue is occurring because on search icon we are getting
section_xpath - '/data/xpath[3]/form/t[1]/div[1]/button[1]/i[1]'
and we are not getting any value in root from this section_xpath
over here -
https://github.com/odoo/odoo/blob/cdedc1752b845bed9acc0dd4bfeb4b343b675326/addons/web_editor/models/ir_ui_view.py#L121

To fix this issue 'o_not_editable' class has been used on that
particular search icon.

sentry-3933794130