[FIX] l10n_hu_edi: fix error when printing invoice with section lines
When a user tries to print an invoice with section lines for Hungarian company,
a traceback occurs.

Steps to reproduce the error:
- Install "l10n_hu_edi" module with demo data and switch to HU Company
- Create an invoice > Add a seaction >Add a line under that section > Save
- Confirm > Print

Traceback:
"QWebError: Error while rendering the template:
 TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'"

https://github.com/odoo/odoo/blob/8018cc47a0185faaccbeba6151411e575f228c2e/addons/l10n_hu_edi/views/report_invoice.xml#L84-L86
Here, "current_subtotal" is used instead of "section_subtotal".
So, It will lead to the above traceback.

"current_subtotal" was changed to "section_subtotal" in the commit [1],
but the t-out attribute in the same block was not changed accordingly.

[1]: https://github.com/odoo/odoo/commit/529b456e69599c2575f9db1d34b613dfc17f2d12

sentry-6933103730

closes odoo/odoo#230948

Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>