[FIX] website_sale: fix ecommerce product rating acl check
Steps to produce:
- Install the `Ecommerce` module.
- Create a product.
- In the Sales tab, set an alternative product and ensure both are published.
- Open the product page on the website and enable `reviews` from the editor.
- Open the same product page in incognito mode.

Issue:
```
AccessError: You do not have enough rights to access the field "rating_avg"
on Product Variant (product.product).
```

Root cause:
- Currently, product records in dynamic snippets to be fetched without
  superuser privileges. Since the `rating_avg` field is restricted to
  internal users, public visitors encounter an `AccessError` when
  viewing snippets with ratings enabled.
- Similar approach used [here].

[here]: https://github.com/odoo/odoo/commit/12bb994da4c3222e8c7fb2df95c202a6c45a28b0

opw-6065319