[FIX] repair: avoid traceback when updating uom in repair order
Steps to reproduce:
- Enable "Units of Measure" in Inventory settings
- Create a repair order
    - Select a product
    - Change its UoM

Problem:
A traceback is triggered:
```
Uncaught Promise > Can not evaluate python expression:
([('id', 'in', allowed_uom_ids)]) Error: Name 'allowed_uom_ids' is not defined
Occured on localhost:8076 on 2025-05-07 20:02:29 GMT
EvalError: Can not evaluate python expression: ([('id', 'in', allowed_uom_ids)])
    Error: Name 'allowed_uom_ids' is not defined

```

The problem is that the field is "readonly=False" in the view, but by
default it's "readonly=True" in Python side.
As a result, the ORM considers the field as read-only and does not
trigger the computation of "allowed_uom_id". When the domain is later
applied in Python, it causes a traceback due to the missing computed
value.

Solution:
Explicitly set readonly=False in the Python field definition.

opw-4773270

X-original-commit: 57cce2ec8a667b37143e411e047fd6c0d69d45cd