[FIX] mail sanitize: restore slideshow BUTTON if removed
Scenario:

- in 18.0, insert a slideshow in sanitize_form=True (the default) html
  field, for example an appointment description
- reload the page

Result: the navigation button are removed, and this traceback error
happens when showing the page (which prevent editing and remove it):

TypeError: Cannot read properties of undefined (reading 'style')
  at Class.start
  (/website/static/src/snippets/s_image_gallery/000.js:125)

Why:

Since 3deb8050831c69ca1e32039622b322ffa38cc497 18.0, the slideshow uses
BUTTON tags instead of LI as does bootstrap 5.0 for such case.

The "sanitize_form" field options enable the lxml cleaner "forms" option
which removes FORM tags, and kill BUTTON, INPUT, SELECT, TEXTAREA tags.

So the buttons used for navigation are removed which causes an issue
with the code not expecting it.

Solutions:

There would be multiple solutions (rerendering the template on opening,
changing our uses of BUTTON to A or LI tags, adding sanitize_form=False
on fields that could have carousel, ...) but that would be a bigger to
do and with some of these using code having buttons (such as bootstrap
carousel) could still not work.

So this PR propose to change the sanitize to not kill BUTTON tags if the
sanitize_form is set on the field.

This seems alright to do since:

- removing buttons with forms options dates from first commit adding
  lxml.html in 2017: lxml/lxml@b87bcb0859c05363489934d0a989d8d979b5b268
  and this code has not been changed till now, so there doesn't seem to
  be any security logic besides "don't all tags that appear in forms in
  emails"

- buttons are often used in html content (such as bootstrap is doing
  in version 5.0) and are in the allowed list of tags of lxml

- the mail editor doesn't had buttons (uses A link instead) but if we
  adds buttons by editing the code, they seem to appear correctly in
  mail client such as gmail / outlook.com so removing them doesn't seem
  needed

- some attribute like onclick could cause issue button they also works
  on other elements and are stripped by sanitize if the options is
  enabled

opw-4844700