[FIX] hr_recruitment : send interview to duplicated applicant
Steps :
Install Recruitment and Surveys.
Recruitment > Settings > Enable Send Interview Survey.
Recruitment > Any Position > Create an Application,
click on Send Interview and then on Send.
Duplicate it, click on Send Interview end then on Send.

Issue :
ValueError: Wrong value for survey.user_input.applicant_id.

Fix :
This is initially caused by the fact that the applicant's response
is also duplicated. As it shouldn't be, copy=False.

opw-2751975