[FIX] mail: no crash on ESC chat window
Before this commit, when 2 chat windows were
open, focusing the chat window on right then
pressing ESC would lead to the following crash:

```
TypeError: Cannot read properties of undefined (reading 'focus')
```

This happens because when closing a chat window, it attempts to
focus the next open chat window if any exist. It remembers last
index, and picks the next chat window at that index.

Problem was that checking last index was applied on new listing
after close, so it was not detecting the closed chat window
as last, thus calling Array.at() on a invalid index.
So in scenario above with 2 chat windows, the list of indexes was
`[0, 1], then `[0]` but index was `1`, so it attempted to access
`[0].at(1)` which is `undefined`.

This commit fixes the issue by reliably picking the item at index
of last close chat window.

closes odoo/odoo#176654

Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>