[FIX] point_of_sale: handle parse-error if reinstall point_of_sale module
When users try to reinstall the "point_of_sale", a traceback will
be generated.

Error:  while parsing /home/odoo/src/odoo/saas-16.4/addons/point_of_sale/
data/point_of_sale_data.xml:4, somewhere inside
<function model="stock.warehouse" name="_create_missing_pos_picking_types"/>

This is because duplicate sequence records exist and raise the ParseError.

code reference:
https://github.com/odoo/odoo/blob/saas-16.3/addons/stock/models/stock_picking.py#L284
https://github.com/odoo/odoo/blob/saas-16.3/addons/point_of_sale/data/point_of_sale_data.xml#L4C49-L4C82

sentry-4452246611