[FIX] core: can compute translated non-callable
Scenario:

- activate another lang on website
- go to a product page (eg. /shop/1)
- swith to secondary language and edit translations

Result: a 500 error page is shown with error:

  Error while render the template
  ValueError: Compute method failed to assign
              product.template.attribute.value(378,).name
  Template: website_sale.product

Cause:

From 18.0 40d79d6c869e2fdd0e85c372aa589373e6607975 used an underscore
prefixed lang in cache, when it should have only done so if the field
had a callable translate.

note: to have the issue, the field needs to also be readonly or we use
update_raw with the non underscore prefixed language.

opw-5039727
opw-5040036
opw-5043034
opw-5043718
opw-5045525
opw-5049079
opw-5049139
opw-5045575
opw-5049531
opw-5049811
opw-5052090
opw-5052930
opw-5053949
opw-5057485
opw-5058659
opw-5059343
opw-5059987
opw-5060138

closes #225192