[FIX] account_peppol,l10n_fr_pdp: prevent error when changing Peppol Reception Mode
Steps to reproduce:
- Install 'documents_account_peppol' and 'l10n_be' module
- Switch to BE Company > Activate Peppol
- Change 'Peppol Reception Mode' -> 'Receive as Documents'

Traceback:
AttributeError: 'res.company' object has no attribute '_peppol_allows_document_reception'

Problem:
Changing the 'Peppol Reception Mode' to 'Receive as Documents' causes an
'AttributeError' because '_compute_peppol_purchase_journal_required()' calls
'_peppol_allows_document_reception()' on 'config.company_id', but the method
is defined on 'res.config.settings'.

Cause:
The method is available on the 'res.config.settings', not on the 'res.company'.

Solution:
Add '_peppol_allows_document_reception()' method in 'res.company' and call
company's method from the 'res.config.settings' method.

opw-6470552

closes odoo/odoo#286799

X-original-commit: c8cfe5c5f0603515a10185b50de233ff8cadfebb
Signed-off-by: Sven Führ (svfu) <svfu@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>