[FIX] base: Do not apply ustr() to the exception obtained when sending a message
Example use case:
- Sending a message and adding an attached .eml file

File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 327, in set_data
     value = value.encode(self.charset)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 6547-6548: surrogates not allowed

The message must be processed, otherwise all subsequent messages will be blocked.

Already solved in 18.0 indirectly since https://github.com/odoo/odoo/commit/41464b5896c00679a8f8ac4faba6bd6f1b11876d

TT55423

X-original-commit: 7e880f5ca44857af19923e7081ab538aa8098e1a