Cherry pick of 825c04434c752429dfaf972730def7cec3296621 failed
stdout:
Auto-merging addons/stock/models/stock_location.py
CONFLICT (content): Merge conflict in addons/stock/models/stock_location.py
Auto-merging addons/stock/models/stock_move_line.py

stderr:
10:35:40.793234 git.c:455               trace: built-in: git cherry-pick 825c04434c752429dfaf972730def7cec3296621
error: could not apply 825c04434c75... [FIX] stock: Consider putaway with a package type and a product
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: