[FIX] hr_holidays_attendance: prevent error in installing hr_holidays_attendance
Currently, an error occurs when installing the hr_holidays_attendance module.

Steps to Reproduce:
 - Install the hr_attendance module without demo data.
 - Go to Attendance > Configuration > Overtime Rulesets and
    open the Default Ruleset record.
 - Delete its linked overtime rules.
 - Install the hr_holidays_attendance module.

Exception: Cannot update missing record 'hr_attendance.hr_attendance_overtime_employee_schedule_rule'

odoo.tools.convert.ParseError: while parsing /home/odoo/odoo18/community/addons/hr_holidays_attendance/data/hr_holidays_attendance_data.xml:7, somewhere inside
<record id="hr_attendance.hr_attendance_overtime_employee_schedule_rule" model="hr.attendance.overtime.rule">
            <field name="compensable_as_leave" eval="True"/>
        </record>

This error occurs when the user deletes all overtime rules and then
installs the hr_holidays_attendance module. During installation, the
module attempts to update the deleted overtime rule records,
which raises an error.

This commit uses forcecreate="0" to skip updating records if the
corresponding overtime rules do not exist.

sentry-7372074675

closes odoo/odoo#279349

X-original-commit: bb45eb2e3437c100e4a75c6b8e43c38e242d9721
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>