[FIX] account: prevent TypeError when calculating days left
When manually changing the discount_date field to null in an invoice related to
a customer with an Early price discount payment term, the customer will face a
type error on the website when accessing their invoices.

Steps to reproduce:

* Install the accountant module
* Create a new invoice for the current user as a customer (e.g., Mitchel Admin).
* Set `2/7 Net 30` in payment terms and add any product.
* Go to Journal Items and make Discount Date visible if not already visible.
* Under the account field `121000 Account Receivable` remove the discount date
  and confirm the invoice.
* Open portal View (/my) and click on Your Invoices >>> Error occurs.

TypeError: unsupported operand type(s) for -: 'bool' and 'datetime.date'

Solution:
We `set discount_date` as today if discount_date
is set none by the user.
If it is in past we will set days_left to zero
and continue the function as usual.

Sentry-6395559503

closes odoo/odoo#205306

Signed-off-by: Antoine Boonen (aboo) <aboo@odoo.com>