[FIX] base: wrong CH state name
To reproduce the issue:
1. Go to 'res.country.state.csv' in base
2. state_ch_sh is "Shaffhausen"

Error: should be "Schaffhausen"

State code is still SH because
ISO 3166 code for this state is CH-SH

OPW-3199628

closes odoo/odoo#114202

X-original-commit: 245804aabb5cd8b3a84b2a4836b188ec9fb144e1
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>