[FIX] account: handle non-positive days in payment terms
Steps to reproduce:
- Install 'Accounting' module
- Payment Terms > Create NEW
- Add a new Due Term line with "Days end of month on the" and a negative amount
  of days(eg: -1)

Traceback:
ValueError: day is out of range for month

When 'days_next_month' is set to a negative value, it is passed directly to
'relativedelta' as the 'day' value. Since a negative value is not a valid day
of the month, the due-date computation raises a 'ValueError'.

Use the end of the month for the calculation when 'days_next_month' is
non-positive. This prevents the traceback while computing the payment term and
allows the proper validation error to be raised when the record is saved.

opw-6453640

closes odoo/odoo#284252

X-original-commit: c2a518d3137d14f8c75f9daa6dda5029389c564d
Signed-off-by: John Laterre (jol) <jol@odoo.com>