Cherry pick of 33db89b9e48489b442ae361f17fefbe6b23d3573 failed
stdout:

stderr:
error: could not apply 33db89b9e48... [FIX] website: fix authentication of archived visitor
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'