[FIX] account: move test case to enterprise
Community build was failing with:
```test_bill_state_change_on_payment_state
    self.assertEqual(payment.invoice_ids.payment_state, 'not_paid')
AssertionError: 'paid' != 'not_paid'
- paid
+ not_paid```

In community there is no any `in_payment` state for account move records. As on
changing payment state to draft It stayed in the `paid` only. `in_payment` state
introduced in the enterprise module. So the test case is failing for the
community version.

To fix this I've moved the test case to the enterprise to retain the expected
behaviour.

runbot error: 234453

closes odoo/odoo#237933

X-original-commit: a54dd0e0e41d10bcd3548c4edc20fd02d1636f00
Related: odoo/enterprise#100865
Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>