[FIX] base: handle NewId in _get_number_next_actual computation
Currently an exception is generated when the user tries to change the
value of `Prefix` or `Suffix` in sequence as the following steps
- Create a sequence with `Use subsequences per date_range` and
  add any `From` and `To` dates
- Click on the view button of any line of `Use subsequences per date_range`
  (visible in developer option)
- Redirect the created sequence by clicking on the arrow key of `Main Sequence`
- Change the value of `Prefix` or `Suffix`

Error: `TypeError: %d format: a real number is required, not NewId`

This issue was introduced by the recently refactored changes in commit [1],
which added an `onchange` method for the `prefix` and `suffix` fields.
Now, when the user changes either field, the `onchange` is triggered
and recomputes all dependent fields, including `_get_number_next_actual`
on `ir.sequence.date_range`. At that point, the record can be a `NewId`,
which causes the issue.

This commit fixes the issue by defaulting `number_next_actual` to `0` when
`_get_number_next_actual` is invoked with a `NewId` for the related sequence
during recomputation.

[1]: https://github.com/odoo/odoo/commit/387b2289da68454599666bf96844b22c41c5cc55

Sentry-7609468821