Cherry pick of 9e128cd2f6e11e490cae38acc85e5093a25a9bb5 failed
stdout:

stderr:
12:04:17.776868 git.c:344               trace: built-in: git cherry-pick 9e128cd2f6e11e490cae38acc85e5093a25a9bb5
error: could not apply 9e128cd2f6e... [FIX] calendar: fix typo 'weeky'
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: