Cherry pick of 1be94a264466f2720505f888958d24bd20a0b6c2 failed
stdout:

stderr:
14:42:17.473075 git.c:344               trace: built-in: git cherry-pick 1be94a264466f2720505f888958d24bd20a0b6c2
error: could not apply 1be94a264466... [REV] web_editor: revert "fix mobile delete backward"
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: