[FIX] stock: avoid operation sequence change
Installing PoS will change some values on existing operations types.

To reproduce the issue
1. Install stock
2. Operations Types, Delivery, open its sequence:
   - Change the prefix
3. Install point_of_sale

Error: the prefix is reset

When installing PoS, it will execute a generic method that creates
and updates all operation types:
https://github.com/odoo/odoo/blob/0bc90e7d74bd0792b9af7464256ba8770d894a25/addons/point_of_sale/data/point_of_sale_data.xml#L4
https://github.com/odoo/odoo/blob/14e9a698e333c3d6d2f7830353c34311de9ecb2c/addons/point_of_sale/models/stock_warehouse.py#L45-L50
https://github.com/odoo/odoo/blob/03478253c166238442d2f81f095de9fbcdfb265f/addons/stock/models/stock_warehouse.py#L350-L356
Thanks to this, the PoS operation type will be created. However, as
said in its docstring, the method will also update the existing
operation types. And, because of [1], we also reset the values of
the sequence. However, the writing is too invasive: ensuring a correct
value for the company is enough.

[1] e52d8f6648556ca97e07769529779be048a96fb7

OPW-4668505

closes odoo/odoo#212615

X-original-commit: e1f6755e35141ad14cdad8cdeea94c89983b207b
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>