[FIX] website_sale: checkout step work with rewrite
Steps:

- create a 308 rewrite from /shop/cart to /test/cart
- go to /shop/cart

Result:

An error 500 is shown with this traceback in server log:

  odoo.addons.base.models.ir_qweb.QWebException: Error while render the
  template
  KeyError: 'current_step'
  Template: website.step_wizard
  Path: /t/div/div[1]/div/div/a/span
  Node: <span t-field="current_step.name"/>

Cause:

The code of website()._get_checkout_step_values doesn't take into
account possible URL rewrite, so we get an error when showing
website.step_wizard template that expect to have found a current_step.

Fix: use url_rewrite to match the current URL to the current step and
use the step_href of the step as current_website_checkout_step_href to
have it not rewritten.

Note: without the fix, the added test fail with the error shown above.

opw-5037289

closes odoo/odoo#225610

X-original-commit: a4593adf850a2fabb2035ab61966af89f0e805a3
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>