[FIX] hr_recruitment: prevent error when loading sample data
When the user clicks on Load sample data button after deleting the stages,
A traceback will appear.

Steps to reproduce the error:
- Install "hr_recruitment" module
- Go to Recruitment > Configuration > Stages > Delete all stages
- Go to Recruitment > Applications > By Job Positions > Load sample data

Traceback:
"ValueError: External ID not found in the system: hr_recruitment.stage_job3"

ParseError: while parsing /home/odoo/src/odoo/addons/hr_recruitment/data/scenarios/hr_recruitment_scenario.xml:94, somewhere inside
<record id="scenario_applicant_macm_enrique" model="hr.applicant">
    <field name="candidate_id" ref="scenario_candidate_enrique" />
    <field name="priority">2</field>
    <field name="linkedin_profile">www.example.linkedin.com/in/enrique.jones</field>
    <field name="job_id" ref="job_marketing" />
    <field name="user_id" ref="base.user_admin" />
    <field name="medium_id" ref="utm.utm_medium_direct" />
    <field name="department_id" ref="dep_marketing" />
    <field name="salary_expected">2900</field>
    <field name="stage_id" eval="ref('stage_job3ob3', raise_if_not_found=False)" />

    <field name="create_date" eval="DateTime.today() - relativedelta(months=2)" />
    <field name="date_last_stage_update"
       eval="DateTime.today() - relativedelta(days=1)" />
 </record>

This commit resolves the error by "raise_if_not_found=False" for the field
if the stage is missing.

sentry-6530485438