[FIX] mail: notify recipients with active records of model
This error occurs when users select Add Follower in Invoice and enable
`Notify Recipients`.

Steps to Reproduce:

- Install the `Account module`.
- Open Invoices > In Chatter `Add Follower`
- Activate `Notify Recipients. '
- Click on Add Followers

ValueError: Expected singleton: account.move()

This error occurred when the system failed to retrieve account move ID due to
current changes at [1], causing account.move to be empty.

This commit ensures the records are correctly retrieved from the wizard context
before sending notifications.

Link [1] : https://github.com/odoo/odoo/pull/167045

Sentry - 6489398559, 6451557597

closes odoo/odoo#203641

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>