[FIX] hr_work_entry: correct add item to list
The fix introduced in #110559 was partially wrong, the employee ID was
not properly added to the list and would crash.

> TypeError: 'int' object is not iterable

X-original-commit: a7914d43d7d1835a76486bb66de753b29a24dd70