Cherry pick of c0e226b67720b5a2f7224a4a75c112fd84ac83a7 failed
stdout:

stderr:
12:09:30.092655 git.c:344               trace: built-in: git cherry-pick c0e226b67720b5a2f7224a4a75c112fd84ac83a7
error: could not apply c0e226b6772... [FIX] account: Fix reconciliation rounding issue
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: