[FIX] html_editior: prevent key error when content-type is missing
This error occurs when 'content-type' is not found in the response when
attaching any file with the type 'URL'.

Traceback:
KeyError: 'content-type'

https://github.com/odoo/odoo/blob/2fe55ae592e5812c5ee5e39ed1e8332bde608cb2/addons/html_editor/controllers/main.py#L257

sentry-6015024235

closes odoo/odoo#196773

X-original-commit: 626182b055ed8468cf41d5a3d9c76ecce01390ff
Signed-off-by: David Monjoie (dmo) <dmo@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>