[FIX] payment_flutterwave: redirect user on token authorization
Versions
--------
- 16.0+

Steps
-----
1. Have a payment token saved via Flutterwave;
2. use token to pay for an order.

Issue
-----
Error: Provide a valid redirect url

Cause
-----
Flutterwave now mandates authorization for tokenized flows. They provide
an authorization url for this, and expect to receive a redirect url value
to return to afterwards.

Solution
--------
Solution partially based on the Ogone redirect flow added in 0ed92bcc9791

The authorization url is provided in the notification data. Store this
en the `provider_reference` field if the transaction is pending.

When processing the pending transaction, initiate a force redirect flow,
which redirects the user to the authorization url.

opw-4669110

closes odoo/odoo#204599

X-original-commit: e51cca6a877c772f26c86cce00d7b731fb3bc4d0
Signed-off-by: Levi Siuzdak <sile@odoo.com>