[FIX] web: update log while error in generating report
When there is an error in a report and user tries to
download that report a logger exception occurs.

Exception: Error while generating report
studio_customization.studio_report_docume_1c084f7d-9ac2-4dd4-9977
-03d87251392c

The error occurs from report_download controller -
https://github.com/odoo/odoo/blob/0d70e38ab4bab850ee4bddc7b21b4c6c10809294/addons/web/controllers/report.py#L136

The logger is updated to use the 'warning' level instead of the 'exception'
level when an error occurs while generating report.

sentry-4321014875

closes odoo/odoo#132515

X-original-commit: 1210e1c7bc97ea772df5d2230a3b8f42b13e9e10
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>
Signed-off-by: Saurabh Choraria (sauc) <sauc@odoo.com>