[FIX] pos_sale: prevent an error while choosing Furnitures scenario card
Currently, an error occurs when trying to load onboarding 'Furnitures' without
a product name 'Down Payment (POS).

Step to produce:

- Install the 'pos_sale' module.
- Delete a product name 'Down Payment (POS)'.
- Open a point of sale and archive all sessions, Click on the
'Furnitures' scenario card.

ValueError: No record found for unique ID pos_sale.default_downpayment_product.
It may have been deleted.

An error occurs when the system tries to retrieve an external ID of
product 'Down Payment (POS)' at [1], When opening a 'Furnitures' scenario card
in POS, but it is not available.

To handle this issue, add 'raise_if_not_found=False' so that if the external id
of a product 'Down Payment (POS)' is not found, then it will return a None value
instead of raising an error.

Sentry-5690826936

closes odoo/odoo#176272

Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>