[FIX] stock: update owner on lot change
In the detailed operations, changing the lot does not update the owner.

To reproduce the issue:
1. In Settings, enable "Consignment"
2. Create a storable and tracked-by-lot product P
3. Update its quantity:
    - 1 x P with lot L1 and an owner ON1
    - 1 x P with lot L2 and an owned ON2
4. Create a planned delivery order DO with 1 x P
5. Confirm DO and Check Availability
6. Open the detailed operations:
    - Set the lot to L2

Error: The owner is still ON1, it should be ON2

An onchange is missing.

OPW-2804973