[FIX] payment_stripe: update log when creation of payment intent fails
When the payment method was detached from the customer, trying to pay with the
linked payment token would end up with a crash because Stripe failed to send us
the payment intent, as it could not create it. In that case, a logger error
occurs on the server which creates noise in the sentry.

Error: The creation of the payment intent failed.
Stripe gave us the following info about the problem:
'Your card has insufficient funds.'

The logger is updated to use the 'warning' level instead of the 'error' level.
This change reflects a less severe logging level for cases where the creation
of payment intent fails.

sentry-4363481906

closes odoo/odoo#131100

X-original-commit: 737d3b410c6e5ce0a50242d7f29d25cc3cb3d456
Signed-off-by: Antoine Vandevenne (anv) <anv@odoo.com>