[FIX] web: prevent error while changing the language
When the user changes the language in My Profile and tries to save,
a traceback will appear.

Steps to reproduce the error:
- Install "account_accountant" and "hr" module
- Activate multi languages
- Go to accounting > Dashboard > New Invoice
- Click on the profile icon > My Profile > Change language > Save

Error: A traceback appears:
"ValueError: Expected singleton: account.move('n', 'e', 'w')"

https://github.com/odoo/odoo/blob/59985860264f7fbd2726a51ff15d7e5101ae8234/addons/web/controllers/action.py#L97
Here, when the user changes the language and tries to save the record.
we received record_id as ('n', 'e', 'w'),
when it tries to access display_name
So it will lead to the above traceback.

sentry-5135218331

closes odoo/odoo#179614

X-original-commit: 0335db090c19c8a97c15c22e6118531b81be69ec
Signed-off-by: Jorge Pinna Puissant (jpp) <jpp@odoo.com>