Cherry pick of 3effc92e8def509efbf50debdd125d8c3f884d19 failed
stdout:

stderr:
18:13:52.456184 git.c:344               trace: built-in: git cherry-pick 3effc92e8def509efbf50debdd125d8c3f884d19
error: could not apply 3effc92e8def... [IMP] snailmail: Generate a cover page if the "Cover Page" option is turned on
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: