[FIX] hr_recruitment: allow Recruitment Users to load recruitment data
Currently an error was generated when the user with access right
`Officer: Manage all applicants` tries to load recruitment data by clicking
`Load Sample data` from recruitment.

error: `ParseError: while parsing /home/odoo/src/odoo/18.0/addons/hr_rec...`

This is because when the user tries to load recruitment data, it tries to create
a `Mail Tracking Value` that requires admin rights. 

This commit allows non-admin users to load the recruitment scenerio and make
the `Load Sample data` button visible to the recruitment User.

sentry-6042340046

closes odoo/odoo#186678

X-original-commit: 7b3a277029b152871e64205bd21725b7a36c6f8f
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>