Cherry pick of dd5a04e7cac3fbdc9b9dad11c33a84f8bbbf1356 failed
stdout:

stderr:
error: could not apply dd5a04e7cac... [FIX] base: arch should be required
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'