[FIX] lunch: fix traceback on lunch order with vendor until date set
Steps to reproduce:
------------------------------
1. Install Lunch module
2. Lunch > configurations > Vendors
3. Open any vendor and set Until date to any near future date
4. Go to My Lunch > New Order
5. Click on Any product with above vendor > Add to Cart
6. Click on Order Now

Observation:
------------------------------
Traceback Occurs:
```
return not (self.recurrency_end_date and date.date() >= self.recurrency_end_date) and self[fieldname]
^^^^^^^^^
AttributeError: 'datetime.date' object has no attribute 'date'
```

Issue:
------------------------------
`_available_on_date` calls `date.date()` unconditionally, which fails when
passed a `datetime.date` object (from `lunch.order`) since date objects
lack the `date()` method.

Solution:
------------------------------
Check instance type before calling `date()` to handle both `datetime.datetime`
and `datetime.date` objects correctly.

opw-5948688