[FIX] mail: prevent timed-out error when quit pop and imap server
OSError: cannot read from timed out object while evaluating a
"model._fetch_mails()", it occurs because when we try to quit a POP server
of incoming mail using the "pop_server.quit()" method, sometimes it is not
able to reach the remote server to quit the pop server, so it throws an OSError.

We added the try block for POP and IMAP.
if it fails then we display the os error.

sentry-3932133536

X-original-commit: 0c30529cc9256c0b2483c2fcbbc599b87c1f8577