[FIX] pos_loyalty: avoid traceback giftcard offline
Currently when selling a physical giftcard, if you loose connection,
a traceback will appear.

Steps to reproduce:
-------------------
* Add a gift card to the order
* Turn off the Wifi
* Click "Sell physical gift card?" and type a code in the popup
> Observation: Traceback
> OwlError: An error occured in the owl lifecycle
> Caused by: TypeError: this.child.mount is not a function
> at VToggler.mount

Why the fix:
------------
When the gift card code check fails (because of the network error),
we throw a notification that looks like `notification.add({ type, body })`.
https://github.com/odoo/odoo/blob/943a9429d7b8d859a6426145ffaa1b19f38879c1/addons/pos_loyalty/static/src/app/components/popups/manage_giftcard_popup/manage_giftcard_popup.js#L106-L109

But the add function's signature looks like this `add(message, options)`
https://github.com/odoo/odoo/blob/943a9429d7b8d859a6426145ffaa1b19f38879c1/addons/web/static/src/core/notifications/notification_service.js#L43

So the `{type, body}` is actually passed as message but the object
cannot be rendered.

opw-6475760

closes odoo/odoo#293446

X-original-commit: c51f997277a042e185a30ec037ab279b242cbbd5
Signed-off-by: Sarah Bellefroid (sbel) <sbel@odoo.com>