[FIX] l10n_vn_edi_viettel: Add index on
sinvoice.symbol.invoice_template_id (inverse One2many field)

`TestIndex.test_enforce_index_on_one2many_inverse Traceback (most recent
call last):
AssertionError: The following fields should be indexed with a btree
index, as they are inverse of an One2many field: - if the field is
sparse -> 'btree_not_null' - if the field is Required or low fraction of
False/NULL values -> True or 'btree' - if not sure -> 'btree_not_null':
l10n_vn_edi_viettel.sinvoice.symbol.invoice_template_id (inverse of
l10n_vn_edi_viettel.sinvoice.template.invoice_symbols_ids)`

closes odoo/odoo#236518

X-original-commit: ff75325cb3230566a83c9e5f3b99a22f4a43bbb5
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>