[FIX] l10n_dk_nemhandel: fix traceback on timeout
In case of timeout when sending an invoice there is a traceback
due to the following error.
```
AttributeError: 'UserError' object has no attribute 'message'
```

It is fixed in this commit.

task-None