[FIX] l10n_ro_edi_stock: conditionally checked if the module is installed in the test
The test was failing when the module was not installed because it was
trying to access the auto_batch field but AttributeError: 'stock.picking.type' object has no attribute 'auto_batch'
, because we need to install the module to have the field available which is stock_picking_batch module.

task-115361 (related to task)

closes odoo/odoo#201378

X-original-commit: 8ec079035924772f563e29101507ccfe79953c0c
Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>