[FIX] pos_loyalty: prevent deletion of mail template if in use
Currently a 'ParseError' is arising when the user upgrades the 'pos_loyalty'
module after deleting the 'Gift Card: Gift Card Information' template in the
mail template.

Steps to reproduce:
- Install the 'pos_loyalty' module
- Delete 'Gift Card: Gift Card Information' from 'Email Templates'
- Now upgrade 'pos_loyalty' module

Traceback:
UserError: You must set 'Email template' before setting 'Print Report'.

ParseError: while parsing /home/odoo/src/odoo/saas-18.1/addons/pos_loyalty/data/gift_card_data.xml:12, somewhere inside
<record id="loyalty.gift_card_program" model="loyalty.program">
        <field name="pos_report_print_id" ref="loyalty.report_gift_card"/>
    </record>

This commit resolves the issue by preventing the deletion of mail template if
it is used by 'Gift Cards'

sentry-6267881886