[FIX] im_livechat,mail: prevent error when enabling can create in studio
Currently, an error occurs when enabling Can Create in Studio for a Website
Live Chat channels.

Steps to reproduce:

- Install the im_livechat and web_studio modules.
- Go to Live Chat, create a new channel, then return to the Live Chat channels
  view and open the newly created channel in kanban view.
- Open Studio and enable Can Create.

Error:
SyntaxError: syntax error at or near ')'
LINE 12: WHERE discuss_channel.id IN ()

Root Cause:
At [1], an SQL query is executed with self.ids, when self.ids is empty, this
leads to an error.

Fix:
This commit prevents the error by updating _get_last_messages to check for empty
self.ids and return an empty recordset early and also updates _compute_duration
to safely handle cases where record.create_date is False.

[1]:
https://github.com/odoo/odoo/blob/70a7babcc830f72bd069a5bb1504748363e4e848/addons/mail/models/discuss/discuss_channel.py#L1404-L1421

Sentry-6861438710

closes odoo/odoo#227845

X-original-commit: 661f6105ffecc971d440c977720e47afcd405a18
Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>