[FIX] html_editor: fix traceback when editing website appointment page
Steps to reproduce:
- Install website_appointment_sale with demo data
- Start booking an appointment and stop at the `Date & Time` selection page
- Open the website editor and click the `edit` option
- A traceback occurs

Issue:
- A traceback occurs when trying to edit the page,

Error:
`TypeError: blocker.hasAttribute is not a function
    at selection_blocker_predicates`

Cause:
- The `selection_blocker_predicates` function assumed every `blocker` was an
Element and called `blocker.hasAttribute(...)`. When a non-element
node (text, comment, or object) was encountered, the call raised a 'TypeError'.

Reference:
https://github.com/odoo/odoo/blob/133d7de629904b03c750023685e63c3c39e36c04/
addons/html_editor/static/src/main/selection_placeholder_plugin.js#L39-L45

Solution:
- Make the function defensive by checking that `blocker` is an instance of
`Element`
- before accessing DOM methods. Non-element nodes are now safely ignored by
 returning `false`.

opw : 5241222

closes odoo/odoo#235065

Signed-off-by: David Monjoie (dmo) <dmo@odoo.com>