Cherry pick of 011b7cc3e8ecf1d59154ceb3765525e07d732d29 failed
stdout:

stderr:
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 4051 and retry the command.
error: could not apply 011b7cc3e8e... [FIX] account: use correct variable on iteration
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/account/models/account_bank_statement.py'