[FIX] website: handle MissingRecord in slug_matching
In case of record doesn't exit, raise a 404 instead of crash in slug function with
odoo.exceptions.MissingError: Record does not exist or has been deleted.

slug_matching() -> build() -> to_url() -> slug()

How to reproduce:
   Add a 308 from /shop/<product>  to /mag/<product>
   Try to access /shop/<product>-unexisting_ID will crash with:
      odoo.exceptions.MissingError