[FIX] mail: ignore ancestors with missing message_id
Context:

A recent improvement (https://github.com/odoo/odoo/pull/203739) slightly
changed how the search domain for `ancestors` operates.
Before it ignored note subtypes, i.e. `'subtype_id', '!=', note_type.id`.

After the PR, it now matches all messages as long as they have a subtype.

In doing so, it didn't account for the fact that in some production
database, you might have `mail.message` records that have **no** message_id
set, i.e. `message_id == False`.

In such cases a traceback would be generated when sending a message from
a mail.thread having an ancestor without `message_id` set.

Example:
```
    references = ' '.join(m.message_id for m in (ancestors + message_sudo))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, bool found
```

While such records *should* not exist when using the ORM, they might be
the result of:
* certain upgrade scripts that use direct SQL (cf https://github.com/odoo/upgrade/blob/06b9e7f3cd98c383698695d6028bb7adefb6f805/migrations/base_vat/saas~16.3.1.0/pre-migrate.py#L104-L120)
* direct SQL inserts by users or/and customisations

Proposed solution:
Since there are no ad-hoc mecanismes to fix such records on productions,
the next best thing would be to simply adapt the search domain for `ancestors`
and ignore any records where `message_id == False`.
Indeed, if there is no `message_id` it makes no sense to try to add it in the
references header.

Reproduction steps:
1) Setup database and install contacts
2) Pick a contact and post a log note
3) For this new `mail.message` write `message_id == False` in the backend
4) Try to send a new message to the contact
-> Traceback

OPW-4728399

X-original-commit: b22cc333b783ef39f47cb42d55dfda192a8a1854