[FIX] tests: ignore errors when deleting screencast frames dir
As a followup of https://github.com/odoo/odoo/pull/151364, since frame
files can be written asynchronously to the frames folder, it happens
sometimes that you can get to a race condition where the folder is
deleted but other frames land in the folder at the same time. The logs
are similar to these:

```
ERROR: TestSaleSignature.test_01_portal_sale_signature_tour
Traceback (most recent call last):
  File "/opt/prod-env-16.0-python3-3.10.12-env/lib/python3.10/site-packages/odoo/addons/sale/tests/test_controllers.py", line 93, in test_01_portal_sale_signature_tour
    self.start_tour("/", 'sale_signature', login="portal")
  File "/opt/prod-env-16.0-python3-3.10.12-env/lib/python3.10/site-packages/odoo/tests/common.py", line 1792, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/prod-env-16.0-python3-3.10.12-env/lib/python3.10/site-packages/odoo/tests/common.py", line 1778, in browser_js
    self.browser.clear()
  File "/opt/prod-env-16.0-python3-3.10.12-env/lib/python3.10/site-packages/odoo/tests/common.py", line 1452, in clear
    shutil.rmtree(self.screencasts_frames_dir)
  File "/opt/python3-3.10.12/lib/python3.10/shutil.py", line 731, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/python3-3.10.12/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/builds/moduon/odoo/test-artifacts/odoo/screencasts/frames'
```

This commit ignores the error when deleting the folder, so that the
tests can continue. Garbage will be removed later, or it can be left
there without much harm.

@moduon MT-1075