[FIX] sale_pdf_quote_builder: prevent error when uploading invalid pdf file
Currently, an error occurs when uploading encrypted or incomplete
PDF files (missing EOF marker) while creating a quotation document
header or footer.

Steps to reproduce:
- Install the sale_pdf_quote_builder module.
- Navigate to: Sales > Configuration > Headers/Footers.
- Upload encrypted file [1], or incomplete file [2].

Error:
PyPDF2.errors.DependencyError: PyCryptodome is required for AES algorithm
PyPDF2.errors.PdfReadError: EOF marker not found

Root cause:
At [3], `_get_form_fields_from_pdf` and `_ensure_document_not_encrypted` directly
call `pdf.PdfFileReader`, when it fails to read or decrypt the file, Python raises
an error.

Fix:
Flush the recordset immediately so all computated fields and constraint
are computed inside the try/except. Use the opportunity to send valid
HTTP response (status-code and content-type wise).

[1]:
https://drive.google.com/file/d/1moSlwXHkqcV6_7zHBNhLMLi-9Ye_xDGJ/view?usp=sharing

[2]:
https://drive.google.com/file/d/16O4LLH8dL0RWmbOx4HrcooFUyesWaVi-/view?usp=sharing

[3]:
https://github.com/odoo/odoo/blob/694f1d0fb03b56dd41a59eb676e56622634cc91b/addons/sale_pdf_quote_builder/utils.py#L11

opw-5227601
sentry-6928220164

closes odoo/odoo#245109

Helped-by: Julien Castiaux <juc@odoo.com>
X-original-commit: 5db1f815a3b511c836ba1db61b9bf08eab5f25ec
Signed-off-by: Julien Castiaux (juc) <juc@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>