[FIX] account: Allow to validate from journal entries menu
**Steps to reproduce**

* Enable developer mode and "Show Full Accounting Features"
* Go to *Invoicing > Accounting > Miscellaneous > Journal Entries*.
* Create a new record and fill it.
* Go back to the list.
* Select the recently created record (or any not posted).
* Click on *Action > Post entries*.
* Click on "Post Journal Entries" button on the appearing popup.

**Current behavior**

Error: "There are no journal items in the draft state to post."

**Expected behavior**

Journal entry is posted.

The problem is a recent change in 3d40e05, that switches the way selected moves
are recognized, for accomodating other use case. With this code, both are valid.