[FIX] l10n_fr_hr_work_entry_holidays: fix traceback when creating a work entry
Currently, a traceback occurs when a user attempts to
create a work entry in the list view.

To reproduce this issue:

1) Install the l10n_fr_hr_work_entry_holidays module.
2) Switch to the French company and open the payroll.
3) Open the work entries in list view and try to create a new record.

Error:
"AttributeError: 'int' object has no attribute 'seconds'"

Cause:
By default, when creating a work entry through the list view,
no start or end date is provided.

This leads to the traceback originating from the following line
https://github.com/odoo/odoo/blob/84b15dc1f866e27d5c8a5fe3e457c2f982bcb133/addons/l10n_fr_hr_work_entry_holidays/models/hr_work_entry.py#L31

Solution:
Adding an extra check of the start and end date would resolve this issue.

opw-4943104

closes odoo/odoo#222043

X-original-commit: 8f35005e0b3fc1adbb282b8d50ffb78f838b7f1f
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>