[FIX] hr_calendar: prevent error when opening the calendar
Currently, an error occurs when a user opens the calendar.

Steps to Reproduce:
 - Install the hr_calendar module.
 - Go to Employees and create an employee.
 - Under the Settings tab, set the employee's user to Administrator.
 - Create a new company and switch to it.
 - Open the Calendar and set the scale to Month.

TypeError: reduce() of empty iterable with no initial value

When the user opens the calendar, it fetches the unusual days for the
selected attendees. By default, the current user's partner is set as an
attendee [1]. It then computes the schedule for the attendee [2], which
returns an empty dictionary [3] because the linked employee belongs
to a different company than the current company, as restricted by the
domain [4]. This empty dictionary is then passed to reduce() to intersect
the schedules, which raises an error because the iterable is empty.

This commit ensures that when no schedule is found for the attendees,
an empty set is returned.

[1]: https://github.com/odoo/odoo/blob/658018684d781fef8bf77a77f1e050d1eb16937c/addons/hr_calendar/models/calendar_event.py#L38-L40

[2]: https://github.com/odoo/odoo/blob/658018684d781fef8bf77a77f1e050d1eb16937c/addons/hr_calendar/models/res_partner.py#L123-L130

[3]: https://github.com/odoo/odoo/blob/658018684d781fef8bf77a77f1e050d1eb16937c/addons/hr_calendar/models/res_partner.py#L40-L42

[4]: https://github.com/odoo/odoo/blob/658018684d781fef8bf77a77f1e050d1eb16937c/addons/hr_calendar/models/res_partner.py#L19-L25

sentry-7672490836

closes odoo/odoo#282866

Signed-off-by: Einar Andersen (eian) <eian@odoo.com>