[FIX] point_of_sale: allow classic users to load demo products
While click on add demo data wizard button it will generate trackback.

Steps to Produce:-
- Create database without demo data.
- Login as Admin.
- Install 'point of sale' module.
- Delete all product
- Create New User and give user access to 'point of sale'.
- Login with new created user.
- Go to 'Point of Sale' module.
- Open new session
- Click Open session on opening cash control
- Click on Generate Demo Data >> Error occur

Error: A traceback appears: AccessError: You are not allowed to create
'Point of Sale Category' (pos.category) records.

This commit solves the above issue by allowing the creation of demo
data on POS for users, which has User rights.

sentry-4245391993

X-original-commit: 12c9a6c3eebda5e3d8feee7e3779130f3d1b5b64