[FIX] product: remove jQuery selector from pricelist report
Versions
--------
- 18.0
- master

Steps
-----
1. Go to product view;
2. using the actions button, go to Pricelist Report;
3. click on the "+" button of the Quantities selector.

Issue
-----
ReferenceError: Can't find variable: $

Cause
-----
jQuery's `$` selector has been disabled there at some point between 17.4
& 18.0.

This wasn't caught by the pricelist report's unit tests, as jQuery is
made available in that context.

Solution
--------
Replace the jQuery selector with `ev.target.previousSibling`, which
points to the same `input` element.

opw-4230836

closes odoo/odoo#184514

X-original-commit: 20d419e3320f4dbd3a2eaef50d5dce81bdb8b41c
Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>