[FIX] stock: prevent an errors when open a routes diagram
Currently, the error is generated when the user opens a routes diagram in
product view without 'Production Location'.

Steps to reproduce:

- Install the 'stock' and 'mrp' modules.
- Go to inventory > configuration > settings > enable Multi-Step Routes.
- Open product > inventory and enable 'Manufacture' in routes and set
'Production Location' as empty value.
- Now try to open a 'View Diagram'.

ValueError: False is not in list

The issue arises when the user tries to open a routes diagram without
'Production Location'  because the system tries to get an index of location
destination and location source at [1], Which is not available.

To resolve the issue, we add a condition of location destination and location
source at [1], To ensure that route lines can not append without
location destination or location source.

link [1]: https://github.com/odoo/odoo/blob/0ae818cca87bd8433a0783797309771125772d86/addons/stock/report/report_stock_rule.py#L60-L63

sentry-5049873238