[FIX] iap: handle connection errors while iap jsonrpc
This error occurs when the IAP service is unreachable when calling the JSON-RPC
in IAP.

ConnectionError: HTTPSConnectionPool(host='extract.api.odoo.com', port=443)

At [1] ValueError is now raised and handled connection errors separately
because this can also be raised from `requests.post`

This commit will raise a ValueError instead of the ConnectionError

Link [1] :
https://github.com/odoo/odoo/blob/62ca36f5a347a230eda3cec2d31797fef0c7a13d/addons/iap/tools/iap_tools.py#L140

Sentry - 6280660773