[FIX] dependency conflict between gevent and greenlet on ubuntu:jammy (22.04)
based on the following error:

ERROR: Cannot install gevent==22.10.2 and greenlet==1.1.2 because these package versions have conflicting dependencies.