[FIX] payment: allow payment for internal user even if not same company
Steps to reproduce:

  - Install `l10n_lu` and `account_payment` modules
  - Login with Admin User
  - Switch to LU company
  - Create and confirm a new invoice
  - Click on Preview

Issue:

  Error: `Please switch to company Odoo - Lu to make this payment`.

Cause:

  In payment module, we ensure that the partner company is matching the
  invoice company. However, in this case, this is an internal user and
  his partner is linked to a different company A but user has
  access to company A & B.

Solution:

  If partner is linked to an internal user, add to allowed companies
  the companies that user has access to.

opw-2922633