[FIX] l10n_pe_pos: various bugs preventing opening the POS session
1. Loading the POS with l10n_pe_pos installed will simply fail because
`_load_pos_data_fields` returns a list of fields, not a dict
("TypeError: list indices must be integers or slices, not str")

2. After fixing this first bug, we are met with another traceback in the
JS code: "TypeError: this.update is not a function". The update function
should be called on an order.

Bug 1 was introduced in 65e373c583b7ec4ac7718a5b8b5b431a1b610d4e

X-original-commit: 974a0ccef1d3fac14d7656d262dcd2cb539628af
Part-of: odoo/odoo#175222
Related: odoo/enterprise#67738
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Julien Van Roy (juvr) <juvr@odoo.com>