[FIX] website_sale: process stock notifications individually
Currently, an error occurs when the cron sends emails to users who opted to be
notified when a product is back in stock.

Steps to replicate:
- Install `website_sale` with demo.
- Create a product `test` and turn on `Track Inventory` and make quantity zero.
- In the eCommerce tab, uncheck `Sell when Out-of-Stock` and publish it.
- Open the `test` product on the website and click `Notify me`.
- Logout and login with another user (Example: Demo user).
- Open the same product and click Notify when in stock.
- Login as admin.
- Make the `test` product's available quantity as 1.
- Run the cron `Product: send email regarding products availability`.

Error:
```
ValueError: Expected singleton: res.partner(16, 17, 3)
ValueError: ValueError('Expected singleton: res.partner(16, 17, 3)') while evaluating
'model._send_availability_email()'
```

Cause:
- Error occurs after a recent [PR].
- Notifications are stored in the `notifications_to_send` list as its first
  element.
- When iterating over the list, the first element can be a multi-recordset
  containing multiple notifications.
- Accessing `notification.partner_id` can therefore return multiple partners.
- Trying to access `partner.name` [1] on multiple partners raises the error.

Solution:
- Store the `notifications_to_send` in a `product.stock.notification` recordset
  instead of a Python list.

[PR]: https://github.com/odoo/odoo/pull/253064

[1]: https://github.com/odoo/odoo/blob/12cad5c5fbdeb22d499cf5389c194d6902a9ef76/addons/website_sale/models/product_product.py#L533

sentry-7777549028