[FIX] account: prevent error when clicking on Send payment status to SInvoice
When User Clicks on Send payment status to SInvoice action,
a traceback will appear.

Steps to reproduce the error:
- Install 'l10n_vn_edi_viettel' module
- Switch to VN Company
- Go to Invoicing > Customers > Invoices > Select any invoice > Actions >
  Send payment status to SInvoice

Error: A traceback appears:
'SyntaxError: syntax error at or near ")"
LINE 1: SELECT * FROM account_move WHERE id IN () FOR UPDATE SKIP LO...'

https://github.com/odoo/odoo/blob/072da22e72e66e6332d073502b987682f1b6e88b/addons/account/models/company.py#L745
Here, when there are no records for sending their payment status to SInvoice,
records.ids will be empty,
It will lead to the above traceback.

This commit will fix the above issue by preventing the execution of the query
when 'records.ids' is empty.

sentry-5954926261