[FIX] website_crm_sms: prevent error when sending sms to visitors
Currently, an error occurs when a user tries to send an sms to a visitor.

Steps to Reproduce:
 - Install website_crm_sms without demo data.
 - Go to Website > Edit, drag and drop another Form block.
 - Configure the form action to "Create an Opportunity" and save.
 - Fill in the required fields, including phone number and Submit the form.
 - Go to Website > Reporting > Visitors and click the SMS button on
   the visitor record.

AttributeError: 'website.visitor' object has no attribute 'phone'

After [this commit], which removed the mobile field from res.partner
along with all related views, then it was updated to access the phone
number from the website visitor.
When a user creates an opportunity through the website and then tries
to send an sms from the corresponding visitor record, it raises an error [1]
because it attempts to access the phone field on website.visitor.
when an anonymous (non-logged-in) user creates an opportunity,
clicking the sms button on the corresponding visitor record triggers
error here [2].

This commit ensures that the correct mobile field is accessed from the
website visitor.

[this commit]: https://github.com/odoo/odoo/commit/6b820eb6fc6f782ba6a83d605d87b4a1dd2a87be

[1]: https://github.com/odoo/odoo/blob/6a0e6443951053f8361e97f42e5e45c32bb73656/addons/website_crm_sms/models/website_visitor.py#L13

[2]: https://github.com/odoo/odoo/blob/6a0e6443951053f8361e97f42e5e45c32bb73656/addons/website_crm_sms/models/website_visitor.py#L20

sentry-7550340909

closes odoo/odoo#270869

X-original-commit: 7baab8d5a939a99b3f228bc5349bbd916243464e
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>