[FIX] stock_account: include return pick lots in valuation
Steps to reproduce:
- Install stock, stock_account, sales
- Create a product with pricing policy not standard(AVCO, FIFO)
- Track this product by lot and keep lot valuation **unchecked**
- Add a quant of the product with this lot
- Create a quotation on the product and confirm the SO
- Confirm the delivery
- Activate the lot valuation on the product
- Make a return delivery based on the delivery we had
- Confirm the return

**Issue**:
Traceback is thrown
```py
new_std_price = ((amount_unit * qty_avail) + (move_cost[lot] * qty)) / (qty_avail + qty)
KeyError: stock.lot(55,)
```
Because `move_cost` is a dictionary returned by `_get_price_unit()`, which
gets the current lots’ valuations. Since the pick is a return one, then
`_get_price_unit()` uses the original pick stock valuation layers and hence
we were disabling the valuation on the original delivery then the layers
don’t have the lot of the product valuated. Then the `move_cost` dict is
not having the lot of the product while valuating it currently, hence the
KeyError is thrown. This issue happens with the AVCO, FIFO because both
valuation models depend on the already valuated lots values using the
`_get_price_unit()`.

opw-4662744
opw-4660094

X-original-commit: f0232282422d46012e37a8d01e1fb810f31ed862