[FIX] l10n_cl: prevent IndexError when creating customer
When the user creates a new customer and enters "." in Identification Number,
a traceback will appear.

Steps to reproduce the error:
- Install "l10n_cl" module
- Switch to Chile Company
- Go to Invoicing > Customers > Create New Customer > Enter Name >
  Select 'Chile' in Country > Enter "." in Identification Number > Save

Error: A traceback appears:
"IndexError: string index out of range"

code reference:
https://github.com/odoo/odoo/blob/276972f96d2eb1a65686e7319f601ed435b57b88/addons/l10n_cl/models/res_partner.py#L40
Here, when user enters "." in Identification Number
then values['vat'] will be ".",
So when it will try to .format(),
It will lead to above traceback.

sentry-4593791704

closes odoo/odoo#140862

Signed-off-by: Josse Colpaert <jco@odoo.com>