[FIX] tools: use get_object instead of deprecated getObject
Currently an error occurs when user tries to send a pdf of a invoice to a
customer.

Steps to replicate: (Make sure to have `python 3.14.4` and `pypdf=5.4.0`)
- Install `l10n_sa_edi` with demo and switch to `My Saudi Arabia Company`.
- Open invoices and create an invoice with customer and an invoice line.
- Click Send > Again click Send.

Error:
```
AttributeError: 'PageObject' object has no attribute 'getObject'
AttributeError: No attribute getObject found in IndirectObject or pointed object
```

- A recent [PR] introduced the old `getObject()` API in the PDF/A conversion code,
  even though it has been renamed to `get_object()` in the modern pypdf API.
- As PyPDF2 1.x compatibility has already been removed, getObject() is no longer
  available and causes the error to log on the terminal.
- Please refer to [1] and [2].

[PR]: https://github.com/odoo/odoo/pull/281275

[1]: https://github.com/odoo/odoo/pull/248197/files#diff-f3528e61bb9aa2d24d9b57cddafb7429d21216ba29f9dc7e08c92bb617949911L218

[2]: https://pypdf.readthedocs.io/en/stable/meta/changelog-v1.html#details

sentry-7663263079