[FIX] account: prevent deletion of default account reports
Steps to Reproduce:
- Install the Accounting module.
- Activate debug mode.
- Accounting > Configuration > Accounting Reports.
- Delete the "Balance Sheet" report.
- Install `l10n_be` module.

Error:
ValueError: External ID not found in the system: account_reports.balance_sheet
ParseError: while parsing /home/odoo/odoo18/enterprise/l10n_be_reports/data/balance_sheet_comp_acon.xml:4, somewhere inside

Cause:
If the user deletes the default accounting reports, and they are referenced by
localization modules, during module installation or upgrade, it tries to fetch
these references, but the records no longer exist, causing an error.

Fix:
This commit prevents the deletion of default account reports.

sentry-7441124574