[FIX] website_sale_digital: handle non-integer type attachment_id
This issue arises when a user cannot add value to the `attachment_id` when
entering the manual URL.In this case traceback will be generated.

steps to produce :
- Install the website_sale_digital module.
- Go to website > Enter the wrong URL without the value of `attachment_id`.
- For e.g. `my/download?attachment_id` > Press the enter error will generated.

Error: invalid literal for int() with base 10: ''

After this commit, the problem of a non-integer type for `attachment_id` will be
resolved by redirecting the user to the Sales Orders page.

We added attachment_id=False because users get an error when attempting to
visit `my/download` URL, which was caused by the missing argument attachment_id.

sentry-4286948781