[FIX] mrp{,_repair}: use scrapped and tracked compo in a MO
It is currently not possible to use a scrapped tracked-by-SN
component in a new MO

To reproduce the issue:
1. In Settings, enable "Multi Locations"
2. Create two products P_finished, P_comp:
    - Storable
    - P_comp tracked by SN
3. Update the quantity of P_comp:
    - WH/Stock: 1 x SN01
4. Process a manufacturing order:
    - Product: P_finished
    - Components:
      - 1 x P_comp
5. Process a repair order:
    - Product: P_finished
    - Remove:
           - Product: P_comp
           - Lot: SN01
           - Destination Location: Virtual Location/scrap
6. Unscrap SN01 (via an internal transfer from scrap to stock)
7. Repeat 4

Error: a UserError is displayed because the SN of the component has
already been consumed. It should be possible to use it

When checking the uniqueness, we are working on the SMLs (see the
lines removed by this commit).
`duplicates` contains the SML from step 4. `duplicates_returned` is
zero since we did not return the component back to the stock.
`removed` is zero too, because we look at the scrapped SML from an
internal location. However, step 5 generates an SML that starts from
the production location. As a result, nothing compensate the value
of `duplicates`, hence the raised error.

Removing the condition of the source location of `removed` would
lead to another bug, so we can't do that. So, this commit suggests a
new implementation based on the following rationale:
- The uniqueness checking simply ensures that one and only one
  existing finished product consumed a specific SN
- What happened outside this context does not matter here

That way, we should only look at the SML from/to production
locations, for tracked-by-sn products used as components only. All
other SML (scrap, unscrap, SML for SN production, and so on) should
not be considered here.

OPW-3834835

X-original-commit: 77355e20f174a09510c3dff24e5ef8eab301fd47
Part-of: odoo/odoo#164302