[FIX] hr: prevent error when clicking the New Contract button
Currently, an error occurs when the user clicks the New Contract button.

Steps to Reproduce:

 - Install the hr module.
 - Go to Employees > click New > do not fill in the employee name.
 - In the Payroll section, set the contract start and end dates.
 - Click New Contract and select a date outside that date range.

IndexError: tuple index out of range

This error occurs because the user clicks the New Contract button before
the employee record is created. Since the employee is not created, the
employee ID is False. It then attempts to create a contract with this False
ID [1]. When the system tries to find the employee’s version using this
False ID, no version is found, raise the error [2].

This commit ensures that the Add Contract button is visible only after the
employee record is created.

[1]: https://github.com/odoo/odoo/blob/dca62b1662f0e3e0ccc66ca9897adb3945b0d715/addons/hr/static/src/components/button_new_contract/button_new_contract.js#L45-L48

[2]: https://github.com/odoo/odoo/blob/dca62b1662f0e3e0ccc66ca9897adb3945b0d715/addons/hr/models/hr_employee.py#L554

sentry-7033637685

closes odoo/odoo#236198

Signed-off-by: Einar Andersen (eian) <eian@odoo.com>