[FIX] mail: don't crash when tracking monetary without currency
before this commit when a monetary field without currency was traked
it raise this traceback

```
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/tests/common.py", line 1327, in flush_tracking
    self.cr.flush()
  File "/home/odoo/src/odoo/saas-19.3/odoo/sql_db.py", line 281, in flush
    self.precommit.run()
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/misc.py", line 1115, in run
    func()
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_track_mixin.py", line 155, in _track_finalize
    records_su._track_execute(initial_values, trackings)
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_thread.py", line 555, in _track_execute
    self._track_log(track_init_values, trackings, track_records=track_records)
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_thread.py", line 672, in _track_log
    record._message_log(
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_thread.py", line 2946, in _message_log
    return self._message_log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_thread.py", line 3009, in _message_log_batch
    values_list[0]['body'] = self._message_compute_body_with_trackings(values_list[0]['body'], tracking_values)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_thread.py", line 3082, in _message_compute_body_with_trackings
    line += val['old_value']
TypeError: unsupported operand type(s) for +=: 'Markup' and 'float'
```

because _create_mail_tracking_values was not converting the old_value
into a string if the currency is False

this commit convert the monetary field without currency into a string as it was a float.
This seems a good enough degraded behavior.

Update addons/test_mail/tests/test_message_track.py

closes odoo/odoo#285910

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Co-authored-by: Thibault Delavallée <tde-banana-odoo@users.noreply.github.com>