[FIX] l10n_in_{edi,ewaybill}: Point view to right parent
The views inherit from the root view `account.res_config_settings_view_form`
but modifies a node like `name='module_l10n_in_edi'` introduced by a sibling
view `l10n_in.res_config_settings_view_form_inherit_l10n_in`.

This leads to errors during upgrades:
```
odoo.exceptions.ValidationError: Error while parsing or validating view:

Element '<xpath expr="//field[@name=&#39;module_l10n_in_ewaybill&#39;]">' cannot be located in parent view
```