[FIX] web: prevent error when rendering a non-existent view
This error occurs in 18.2 when a user creates a course record for any attendee.

Steps to Reproduce:
 - Install the website_slide module.
 - Go to Reporting > Attendees.
 - Go to either the Graph or Pivot View and click on any count value.
 - Open any attendee record and click on New.

SyntaxError: syntax error at or near ")"
LINE 18:             WHERE SCP.id IN ()
                                      ^

This error occurs because when the user clicks on New to create the attendee's
course record, the system triggers the compute method before saving the record.
Since the record has not been saved yet, the self.id is empty, which causes
the error.

In the list and kanban views, clicking on any attendee record does not open any
form view. However, in the graph and pivot views, clicking on an attendee
record opens a form view that does not exist, resulting in an error.

This commit ensures that if the form view is present, it will be included in
the graph and pivot views. The list view is always included to display the
records. The form view may contain computed methods, which can lead to
errors if the view is not properly defined.

Sentry-6465821899