[FIX] l10n_in: make name mandatory on PAN entity
Cause:
When saving a PAN Entity without a PAN, `record.name` is False.
The create() method calls `record.name.upper()`, which crashes with
"AttributeError: 'bool' object has no attribute 'upper'".

Before this commit:
It was possible to save a PAN Entity without a name, leading to a traceback
during record creation.

After this commit:
The PAN field is marked as required.

Ref - https://pastebin.com/Gu15zLwA