[FIX] hr_timesheets : Fix timesheet stat compute method
The issue is raised in this pr(v19.2) :
https://github.com/odoo/odoo/pull/236971

The compute method used a `return`
https://github.com/odoo/odoo/pull/236971/changes#diff-4e1a18a369f7dd4de264139227676dd818c06612681c88019f43d238bd8a1490R91
statement when a `if condition` was met.
While this works correctly for a single record, it causes issues when multiple
records are present.
For example, if `self` contains records like `project.project(3, 2, 4)`,
and the condition is satisfied for the first `record (3)`, the method exits
early.
As a result, the remaining `records (2 and 4)` are not processed.

When the compute method is triggered,
https://github.com/odoo/odoo/blob/8c3043b436f8aae295f247341e3ac427fab05474/odoo/orm/fields.py#L1746
this incomplete computation leads to
missing values for some records and can result in errors.

To resolve this issue, `return` has been replaced with `continue`.
This ensures that:
Only the current record is skipped when the condition is satisfied.
The loop continues processing the remaining records.

Traceback:
```
Traceback (most recent call last):
  File "/tmp/tmp2cuqrnuy/migrations/testing.py", line 483, in test_check
    self.check(value)
  File "/tmp/tmp2cuqrnuy/migrations/base/tests/test_mock_crawl.py", line 228,
 in check
    self.assertFalse(diff, msg)
AssertionError: [('project.menu_projects', 391, 'Project > Projects', 593)] is
not
false : At least one menu or view working before upgrade is not working after
upgrade.

('project.menu_projects', 391, 'Project > Projects', 593):
 Traceback (most recent call last):
   File "/tmp/tmp2cuqrnuy/migrations/base/tests/test_mock_crawl.py", line
335, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp2cuqrnuy/migrations/base/tests/test_mock_crawl.py", line
348, in mock_action
    return self.mock_act_window(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/tmp2cuqrnuy/migrations/base/tests/test_mock_crawl.py", line
508, in mock_act_window
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp2cuqrnuy/migrations/base/tests/test_mock_crawl.py",
line 541, in mock_view_form
    [data] = record.read(fields_list)
             ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/odoo/src/odoo/saas-19.2/odoo/orm/models.py", line 2735, in read
    return self._read_format(fnames=fields, load=load)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/odoo/src/odoo/saas-19.2/odoo/orm/models.py", line 2991, in
_read_format
    vals[name] = convert(record[name], record, use_display_name)
                         ~~~~~~^^^^^^
   File "/home/odoo/src/odoo/saas-19.2/odoo/orm/models.py", line 6007, in
__getitem__
    return self._fields[key].__get__(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/odoo/src/odoo/saas-19.2/odoo/orm/fields.py", line 1805, in
__get__
raise ValueError(f"Compute method failed to assign {missing_recs}.{self.name}")
ValueError: Compute method failed to assign
project.project(2, 4).stat_timesheet_value
```
opw-6046808