[FIX] maintenance: handle type error without effective_date
When the user creates the new equipment record and sets the
"Preventive Maintenance Frequency" as 1, the "Effective Date" is set to empty,
and a traceback will be generated.

Steps to reproduce:
- Install the "maintenance" module.
- Maintenance > Equipments
- Try to create a new record, set the "Preventive Maintenance Frequency" to 1,
 and set the "Effective Date" to empty.
- After that, a traceback will be generated.
Error: TypeError: unsupported operand type(s) for +: 'bool' and 'datetime.timedelta'

When the user creates the new equipment record and sets the
"Preventive Maintenance Frequency" as 1, the "Effective Date" is set to empty,
and a traceback will be generated. So, check the "Effective Date"
value in the '_compute_next_maintenance()' function of the
maintenance.equipment object; if it is true, pass it; otherwise, it is false.
code reference:
https://github.com/odoo/odoo/blob/a6777c22c84976bc9cb77f9c95566881cf46d5c6/addons/maintenance/models/maintenance.py#L179

sentry-4508012402