[FIX] pos_loyalty: force `all_discount_product_ids` domain evaluation on python
To reproduce:
 1. Install PoS
 2. In the PoS config, enable "Promotions, Coupons, Gift Card & Loyalty Program"
 3. Go to Products > Discount & Loyalty
 4. Open the form view of "15% on next order"
 5. Change the reward to:
  - Discount: Specific Product
  - Discount Product Domain (! only appear in debug mode) > edit domain:
  `[("name", "ilike", "chair")]`
  Then save (the whole loyalty program)
 6. Open the PoS session
 -> JS traceback `TypeError: fieldValue.toLowerCase is not a function as matchCondition`

Before this commit:
This happened as the PoS JS load only certain fields of the products.
When the domain try to use a field which was not loaded, it will fail to compute the domain.
I propose to fix this issue by evaluating the domain from the Python side instead.
Currently, this is automatic IF you set the `loyalty.compute_all_discount_product_ids` system parameter as `enabled`.
But in this case, every PoS session will load with this process which can lead to performance issues.

After this commit:
This PR propose to use the same Python domain evaluation only if the domain is detected to have at least one field
which is not loaded from the PoS JS side (which will likely cause a JS error).

Note: there is an existing try catch which catch for "InvalidDomain" exception with a friendly error message.
Unfortunately, it does not help here as another exception happen (which is not caught).
The fact that the PoS continue to load even if the reward is incorrect is intended to not be blocking.

opw-3495793