[FIX] website_sale: decouple `sale_timesheet` dependency from test
Versions
--------
- saas-18.2+

Steps
-----
1. Have a database without `sale_timesheet` installed;
1. run `TestWebsiteSequence` test suite.

Issue
-----
ValueError: No record found...

Cause
-----
Commit 1ad051a08f594 updated the test to account for a `sale_timesheet`
product that cannot be deleted or archived, but didn't check whether the
module was actually installed.

Solution
--------
Revert changes to the test that were added in the commit, and instead
archive the product via `cr.execute` to bypass the `write` method where
the restriction exists.

runbot-111883

closes odoo/odoo#200172

X-original-commit: 858494ca6e165ebdd9d83af8b65d3894314aa28e
Signed-off-by: Levi Siuzdak <sile@odoo.com>