[FIX] point_of_sale: create new pos product category in Preparation Printers
When user creates new Pos Product Category in Preparation Printers,
a traceback will appear.

Steps to reproduce the error:
- Go to Point of Sale
- Configuration > Settings > Connected Devices > Enable Preparation Printers
- Go to Orders > Preparation Printers > Open any Preparation Printer
- In PoS Product Category > Add a line > New

Error: A traceback appears:
'TypeError: sequence item 0: expected str instance, bool found'

https://github.com/odoo/odoo/blob/dca6ef8051aac367b94c1b5287f988456ae1d905/addons/point_of_sale/models/pos_category.py#L33
When user creates new pos product category,
Here, 'self.name' will be False in '_get_hierarchy' method.
'_get_hierarchy' method is called in '_compute_display_name' method.
So it will lead to above traceback.

sentry-4379442099