[FIX] payment_paypal: ignore exception in sentry for missing notification data.
ValidationError: PayPal: Missing value for txn_id (78X739757D473425R) or
txn_type (None).

This issue occurs when there is some missing value in the received
notification_data while evaluating the '_process_notification_data' function.
It raises an Exception which will be caught by the sentry.

sentry-3954375754

closes odoo/odoo#123184

X-original-commit: 8c539133f374ad709b5ed7770b15a3233e2463b2
Signed-off-by: Antoine Vandevenne (anv) <anv@odoo.com>