[FIX] models: groupby date for pivot view
When user tries to apply any 'Group By' as date or datetime in the pivot view
and the column value of pivot view is also a date or dateime, the traceback will
be generated.

To reproduce the issue:

- Install 'Point of Sale'
- Go to 'Reporting' and clicks on 'Orders'
- Select pivot view
- Go to 'Group By' and select 'Order Date' same as column value
- Issue can be produce in the same way in other modules, such as -
'sale', 'sale_subscription', 'crm', 'planning', 'hr_expense' etc.

Error: A traceback appears: 'can only concatenate str (not relativedelta) to
str'

When user selects value of 'Group By' as date or datetime and when the column is
also a date or datetime in pivot view, the 'read_group' method is called. And
the 'read_group' method returns the 'value' as a string like 'June 2023'. When
it concatenates the 'value' with 'interval' which is relativedelta, the
error will be generated.

Fixed this issue by applying the condition when the 'value' is not passed as datetime.

sentry-4262719543