[FIX] web: ensure IR Profile is enabled before proceeding further
This error occurs when users create an IR profile and open the Speedscope URL
without ensuring that profiles are enabled.

Steps to Reproduce:
 - Install the base module.
 - Open the profile page in Settings.
 - Create an IR Profile.
 - Click on the Speedscope URL and click Open.

TypeError: the JSON object must be str, bytes or bytearray, not bool

This error occurs when the system fails to retrieve init_stack_trace because
the IR Profile is not enabled.

This commit ensures that the system proceeds to check init_stack_trace only
if the IR Profile is enabled.

Sentry-6466200993