Cherry pick of f5fb638c43fdc26e495d05eca25fe3e23d0fee85 failed
stdout:

stderr:
17:35:05.609603 git.c:344               trace: built-in: git cherry-pick f5fb638c43fdc26e495d05eca25fe3e23d0fee85
error: could not apply f5fb638c43f... [FIX] various: update query counters to last runbot state
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: