[FIX] website_sale: prevent error on loading translation
Currently an error occurs when user tries to load translations to website.

Steps to replicate:
* Install website_sale
* website > Edit > Theme > Add a Language > Add any language
* Go to shop > you should get an error in the terminal.

Error:
`Qweb Error:
 Error while rendering the template:
    SyntaxError: invalid syntax (<>, line 1)
    Template: website_sale.products
    Reference: website_sale.products`

Root cause:
* When the placeholder variable is not set, the string 'placeholder' is passed
  to the template [1].

* This 'placeholder' value is translated, and a <span> tag is added as its value
  [2].
  This result is then passed to [3], which in turn is passed as an expression to
  [4], causing the error.

Solution:
* Define the placeholder inside the <t> tag instead of passing it as a parameter
  to avoid mistranslation.

[1]:
https://github.com/odoo/odoo/blob/97294a2798f5fd20748ad1e0f4a9bd2403fd7d1a/addons/website_sale/views/templates.xml#L727
[2]:
https://drive.google.com/file/d/1gpDa8Ua9Zq8XMHKmL3FbVAtetech_twP/view?usp=sharing
[3]:
https://github.com/odoo/odoo/blob/97294a2798f5fd20748ad1e0f4a9bd2403fd7d1a/odoo/addons/base/models/ir_qweb.py#L2558
[4]:
https://github.com/odoo/odoo/blob/97294a2798f5fd20748ad1e0f4a9bd2403fd7d1a/odoo/addons/base/models/ir_qweb.py#L1550

sentry-6917649923