[FIX] l10n_sa_edi: missing reason when reversing entries
With a SA company setup
Open a jounrnal entry
Hit 'Reverse Entry' > Reverse
Error: "For Credit/Debit notes issued in Saudi Arabia, you need to
specify a Reason"

This occurs because with SA localization we need to provide a reason for
move reversal but by default the reason field is invisible for journal entries

opw-3789732