[FIX] hr_attendance: prevent error when removing check-in value
The system crashes with an error when the user removes the Check In value while
creating a new attendance record and then tries to modify other fields.

Steps to produce:
- Install the Attendances module.
- Go to the Attendance app and click on New.
- In the wizard, remove the Check In value and click anywhere.

Error:
AttributeError: 'bool' object has no attribute 'tzinfo'

Cause:
- At [1], when the `check_in` value is changed, the `_compute_date` method is
  triggered. If `attendance.check_in` is `False`, the computation attempts to
  access `tzinfo` on a boolean value.

Solution:
- If the `check_in` value is not present, set the `attendance.date` to today’s
  date.

[1]: https://github.com/odoo/odoo/blob/6bcb1a58beb763e5454a26eb8d0953394de7a8fc/addons/hr_attendance/models/hr_attendance.py#L83-L90

sentry-6924425687

closes odoo/odoo#230068

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>