[FIX] web: pass new context key in /json request
An internal server error happened when trying to acces json from the url in the employees app

Steps to reproduce:
-------------------
* Open employees app
* Change /odoo/ for /json/ in the url
> Observation:
 ValueError: NameError("name allowed_company_ids is not defined") while evaluating
"[(company_id, in, allowed_company_ids)]"

Why the fix:
------------
With the odoo web route allowed_company_ids is added to the context here https://github.com/odoo/odoo/blob/648956b75bdd09396bae3b7162f236236fccae23/addons/web/static/src/webclient/actions/action_service.js#L346    from user.context.
With the json route we need to add it manually as it's not in the env

opw-4601689

closes odoo/odoo#204135

X-original-commit: 5e6b2f84bb7e2b47a8bfe5deabb1817bda2587f9
Signed-off-by: Julien Castiaux (juc) <juc@odoo.com>
Signed-off-by: Guillaume Vardakis (gvar) <gvar@odoo.com>