[FIX] event_product: ensure tickets have correct service tracking
Steps
-----
1. Have `sale_renting` but not `sale_stock_renting` installed;
2. create an event with a ticket;
3. make the ticket's product rentable;
4. change ticket's product type to Goods;
5. publish the event to website;
6. register for the event via website;
7. go to payment.

Issue
-----
AttributeError: 'bool' object has no attribute 'tzinfo'

Cause
-----
By making it a rental product, it creates a rental order, but as
registering for an event via website doesn't have any way to add rental
dates, rental lines cannot be processed & rendered as expected.

Solution
--------
Prevent users from changing the `service_tracking` away from `'event'`
by adding an `api.constrains` to `product.product` on `service_tracking`
and `event_ticket_ids`.

opw-5207045

closes odoo/odoo#235249

X-original-commit: afcbd98594c9f7007f03a343ea40ea122b955459
Signed-off-by: Jérémy Hennecart (jeh) <jeh@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>