[FIX] base: prevent error when user timezone is unset
This error occurs when clicking the “Code History” button in Server Action.

Steps to reproduce:
- Search 'Server Action' > Open any server action
- Change 'Code' and Save > Click 'Code History' button

Traceback:
AttributeError: 'bool' object has no attribute 'upper'

This error occurs when the “Code History” button is clicked and, at that point,
the user’s timezone is 'False' because it is not set in the user’s calendar.

[1]- https://github.com/odoo/odoo/blob/54681272e9f00a171fe49f690979e2a8353ff5fb/odoo/addons/base/models/ir_actions.py#L515

sentry-7167683304

closes odoo/odoo#245204

X-original-commit: 4e2916e2d36c09641407a3224faecc298f9e304b
Signed-off-by: Krzysztof Magusiak (krma) <krma@odoo.com>
Signed-off-by: Aayush Modi (aamo) <aamo@odoo.com>