[FIX] l10n_br_sales: correctly override a t-call
Currently, you can't print quotations with a Brazilian company.

Steps to reproduce
------------------
* install `l10n_br_sales`
* switch to a Brazilian company
* attempt to print a quotation

You should be met with the following traceback:
```
TypeError: 'NoneType' object is not subscriptable
Template: l10n_br_sales.document_tax_totals_brazil
Path: /t/tr[1]
Node: <tr t-if="\'cash_rounding_base_amount_currency\' in tax_totals"/>
```

opw-4239563

closes odoo/odoo#183390

X-original-commit: d061b71849e2de399d35867d3d468cfd7be317b5
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>
Signed-off-by: Séna Serge Nshimiyimana (sesn) <sesn@odoo.com>