[FIX] sale_stock: force invoice_policy on product in test
## Issue
The test `test_multi_steps_partially_delivered` from
the `sale_stock` module is failing when the Kenyan localization is installed.

This issue is similar to the one fixed by https://github.com/odoo/odoo/commit/b9e5807cd70d.

## Steps to reproduce
1. Install `sale_stock` and `l10n_ke_edi_oscu_stock`
2. Run the test `test_multi_steps_partially_delivered`
3. **The test fails with the following error:**

```
Traceback (most recent call last):
  File "/home/odoo/Documents/src/odoo/191/addons/sale_stock/tests/test_anglo_saxon_valuation.py",
  line 1824, in test_multi_steps_partially_delivered
    invoice = sale_order._create_invoices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/Documents/src/odoo/191/addons/sale/models/sale_order.py",
  line 1732, in _create_invoices
    raise UserError(self._nothing_to_invoice_error_message())
odoo.exceptions.UserError: Cannot create an invoice. No items are available
to invoice.

To resolve this issue, please ensure that:
   • The products have been delivered before attempting to invoice them.
   • The invoicing policy of the product is configured correctly.

If you want to invoice based on ordered quantities instead:
   • For consumable or storable products, open the product, go to the
   'General Information' tab and change the 'Invoicing Policy' from
   'Delivered Quantities' to 'Ordered Quantities'.
   • For services (and other products), change the 'Invoicing Policy' to
   'Prepaid/Fixed Price'.
```

## Cause
When `l10n_ke_edi_oscu_stock` is installed, the `invoice_policy` of kenyan
products (or products without a company set) is set to `"delivery"` by
the `_compute_invoice_policy` method from that module:

https://github.com/odoo/enterprise/blob/f4cd9a38c699e8d8f17990a283793985bfc89948/l10n_ke_edi_oscu_stock/models/product.py#L16-L21

This impacts the `SaleOrder.qty_to_invoice` field, as we now use the
`qty_delivered` (which is 0 here) instead of the `product_uom_qty`:

https://github.com/odoo/odoo/blob/d0ee4af1ddb969dfc9023c628f8b128f2b22e89d/addons/sale/models/sale_order_line.py#L1001-L1006

With a `qty_to_invoice` set to 0, the `SaleOrder._get_invoiceable_lines`
doesn't add the product as an invoiceable line:

https://github.com/odoo/odoo/blob/d0ee4af1ddb969dfc9023c628f8b128f2b22e89d/addons/sale/models/sale_order.py#L1492-L1498

And finally, as there's nothing to invoice, the error is raised:

https://github.com/odoo/odoo/blob/1231a671ad76537f559e21aae39153416dfd8ae0/addons/sale/models/sale_order.py#L1731-L1732

## Fix
We manually set the `invoice_policy` of the test product to 'order' to
keep the test configuration consistent regardless of the other modules
installed.

runbot-242508