[FIX] mail_group: traceback on mail group filter
Steps to reprodude:
-------------------------
1. Install `mail_group` module.
2. Go to groups from the portal side
3. Click on any group
4. From Archives section, click on any month in By Date groupby

Observation:
-------------------------
Taceback occurs:
```
TypeError: unsupported operand type(s) for &: 'DomainCondition' and 'tuple'
```

Issue:
-------------------------
In the following code:
https://github.com/odoo/odoo/blob/0c19399518029b85650b6204279e1e20d8d2e85c/addons/mail_group/controllers/portal.py#L112-L113
Only one tuple is converted to Domain object and it was trying to combine a
Domain object with a plain tuple using the `&` operator, which generates the
`TypeError`

Solution:
-------------------------
Converted other domain tuple to the Domain object.