[FIX] l10n_my_edi_pos: fix year-range sequence error in MyInvois
Currently an error is produced when sending invoices to MyInvois if the invoice
number uses a year-range sequence (e.g., INV/2025-2026/00001).

Steps to Reproduce(v-19.0):
1. Install the `accountant` and `l10n_my_edi` modules (with demo data).
2. Switch to "MY Company"(Malaysian company).
3. Enable "Quick Encoding" for Customer Invoices in Settings.
4. Create a customer invoice with customer "MY Company", set a Malaysian
   classification code and taxes on the invoice line, and confirm the invoice.
5. Set the invoice back to Draft and modify the invoice number with a
   year-range sequence (e.g., INV/2025-2026/00001), then confirm it again.
6. Open the invoice list view and click "Send to MyInvois".

Error:
ValueError: not enough values to unpack (expected 4, got 2)

The `_get_sequence_date_range()` method on 'myinvois.document' overrides the
method from `sequence.mixin` and returns only two values from
`date_utils.get_fiscal_year()`. However, it expects the method to return four
values at [1].

[1]: https://github.com/odoo/odoo/blob/cff9a2cc468fe8de60224cac3a3623926ddd9b4e/addons/account/models/sequence_mixin.py#L146
Ref: https://github.com/odoo/odoo/blob/796f7a5ea93a1f88226dafd4a05734a07a12338b/addons/account/models/account_move.py#L4263

sentry-7320998540

closes odoo/odoo#266221

X-original-commit: 3018a45f73dafea9f6def3d992654f53a9d5cf1e
Signed-off-by: William André (wan) <wan@odoo.com>
Signed-off-by: Aditi Patel (adip) <adip@odoo.com>