[FIX] website_sale_loyalty: prevent error while remove product from cart
Currently, an error is generated when removing a reward product that has
been added multiple times  in the cart.

Step to produce:

- Install a 'website_sale_loyalty' module.
- Navigate to the website / eCommerce / Loyalty / Discount & Loyalty to create
a record.
- Set the Loyalty Program name and Program Type as 'Loyalty Cards'.(Ensure it's
available on sale and on the website.)
-  And add 'Rewards' and set a Reward Type as 'Discount' which is applied on
Cheapest Product.
 - Go to the website shop add any product on a card, Open a cart increase the
quantity of the product, and claim the discount reward multiple times.
- Now try to remove a reward product that has been added multiple times in cart.

ValueError: Expected singleton: sale.order.line(33, 34)

The issue occurs when 'Remove' a reward product that is added
multiple times in a cart. As a results the system receives multiple lines at[1],
and from it gets an id [2].

link [1]: https://github.com/odoo/odoo/blob/499056a82db26f7d9caa86314e666e2bd49cc79c/addons/website_sale_loyalty/models/sale_order.py#L162

link [2]: https://github.com/odoo/odoo/blob/499056a82db26f7d9caa86314e666e2bd49cc79c/addons/website_sale_loyalty/models/sale_order.py#L166

To resolve the issue, Add indexing so system will now target and remove only one
an product of the duplicate product from cart.

sentry-5091141573