[FIX] payment_paypal: ignore exception in sentry for missing notification data.
ValidationError: PayPal: Missing value for txn_id (78X739757D473425R) or
txn_type (None).

This issue occurs when there is some missing value in the received
notification_data while evaluating the '_process_notification_data' function.
It raises an Exception which will be caught by the sentry.

sentry-3954375754