[FIX] sale: ensure method receives a recordset, not a dictionary
At [1], '_create_invoices()' expects a recordset, not a dictionary. The test
case currently passes because the 'advance_payment_method' is set to 'percentage'.
However, if someone overrides '_create_invoices()' and uses a different
'advance_payment_method' (e.g., 'delivered'), it will fail.

Traceback:
AttributeError: 'dict' object has no attribute '_create_invoices'

[1]- https://github.com/odoo/odoo/blob/4cd24dc73d46b714cd5a764ed3f003e9507b0777/addons/sale/tests/test_accrued_sale_orders.py#L150-L152

X-original-commit: 0bfc2c26c4381bd98974353fb36aad26a34f9640