[FIX] core: fix like domain with trailing escape
before this commit:
for python domain
    [('name', 'ilike', 'a\\')]
the sql would be
    "name" ILIKE '%a\%'
where the wildcard character '%' is escaped by the '\'

for python domain
    [('name', '=ilike', 'a\\')]
the sql would be
    "name" ILIKE 'a\'
which will trigger error
ERROR: LIKE pattern must not end with escape character

Reproduce the problem
Go to Settings > Companies > New a Company
In address fill 'state' field with value 'k\'
ERROR: LIKE pattern must not end with escape character

after this commit:
Since the search bar may auto search before user confirms, some incomplete
domain may be sent to the server. Instead of raising error, we
choose to drop the trailing escape character for 'like' relevant operators