[FIX] base_import: raise ImportValidationError if user select invalid seperator
When a user tries to import the CSV file with a different separator at that
time, the values in mapper and rows_to_import are not correctly mapped. So the
traceback will be generated.

Steps to reproduce:
1. Install the accounting module.
2. Click on import in the bank statement.
3. Select any CSV file for the bank statement line or can download and import
this file `https://drive.google.com/file/d/1lnScw4RN6T01pOkyNON8vvb3FQOPiy1O/view?usp=drive_link`
4. Select `semicolon` in the separator.
5. Click on the test or Import button.

Error: A traceback appears  `IndexError: list index out of range.`

This commit fixes the above issue by throwing 'ImportValidationError' if the
user selects an invalid separator at the time of importing data from CSV.

sentry-4021250095