[FIX] iot: pip install geoip2
Before this commit:
The odoo service on the IoT box will crash on start if it's synchronised
with an Odoo server version 16.1 (or higher).

Trying to manually start Odoo, we have the following traceback:
```
Traceback (most recent call last):
  File "/home/pi/odoo/odoo-bin", line 5, in <module>
    import odoo
  ...
    from odoo.http import request
  File "/home/pi/odoo/odoo/http.py", line 140, in <module>
    import geoip2.database
ModuleNotFoundError: No module named 'geoip2'
```

Since: https://github.com/odoo/odoo/pull/91337
`geoip2` python library is an Odoo requirement, which is not installed
on the IoT box.

After this commit:
Odoo service start without crashing

opw-3278925