[FIX] stock: skip putaway rule if dest loc set by user
To reproduce the issue:
1. In Settings, enable:
   - Storage Locations
   - Storage Categories
2. Create and confirm a receipt with one product
3. Open the detailed operation
4. Add a line
   - To: WH/Stock/Shelf 1
   - Done: 1

Error: Once the user sets the done quantity to 1, the destination
location will be automatically set to WH/Stock

Since the Storage Locations option is enabled, when updating the
done quantity of the SML, it triggers an onchange in charge of
applying the putaway rules. Since the Storage Categories option is
enabled, the putaway process starts from the SM's location (i.e.
WH/Stock). Then, since there isn't any putaway rule, the process
will simply return the initial location (WH/Stock) and we will use
it as new destination location of the SML.

Since the destination location has already been set by the user, we
should avoid overriding it, otherwise he will have to set the
location again.

OPW-3511560
OPW-3549579

closes odoo/odoo#139787

X-original-commit: e8d711694d9c345afa5bea700c9642d7123d9409
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>