[FIX] website_sale: prevent traceback while saving the shipping address
When user tries to save a new shipping address without filling out any fields,
a traceback will appear.

Steps to produce the error:
- Install 'website_sale' module
- Go to Website > Shop > Add any product to cart
- Checkout > Edit Billing & Shipping address
- Add new Shipping address > Save address

Error: A traceback appears:
'ValueError: Use 0/1/yes/no/true/false/on/off'

https://github.com/odoo/odoo/blob/a0741f6427514be5246a5476b5c2f1ca1c23e6e5/addons/website_sale/controllers/main.py#L1346
Here, when the user saves a shipping address without filling out any fields,
kw.get('use_same') will be an empty string, but 'str2bool' will not accept
the empty string because 'str2bool' only accepts 0/1/yes/no/true/false/on/off.
So it will lead to the above traceback.

sentry-4798968320