[FIX] website_sale: Fixed error for bool object attribute
When there is no default confirmation template,
An error is raised:
AttributeError: 'bool' object has no attribute 'exists'.
This happens because default_template is False,
So calling default_template.exists() results in the error.
The issue occurs during the upgrade process.

```
File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3142, in _init_column
    value = field.default(self)
  File "/home/odoo/src/odoo/19.0/addons/website_sale/models/website.py", line 52, in _default_confirmation_email_template
    if default_template.exists():
AttributeError: 'bool' object has no attribute 'exists'
```