[FIX] mrp_account: fix traceback when trying to post WIP entry
Steps to reproduce:
* install MRP and Accounting
* open an MO
* go to actions -> "Post WIP Accounting Entry"

Odoo shows an error message, ending with:

```
KeyError: 'property_stock_account_input_categ_id'
```

This looks like a missing part of the "New Inventory valuation"
(commit ee8a0efec8db747e2fd135bcb1ee5f5121b3797d).

From that commit's message:

There is no more account for input and output. Instead in the closing
report, we show the po/so that are delivered but not invoiced. This way
the user can create the accrual for it. If you have good receipt not
billed. The inventory value will be greater than stock value. It result
by an entry that debit stock account and credit the variation account.
Then an accrual entry is posted to debit the variation account and
credit a bill to receive account.

closes odoo/odoo#226083

Signed-off-by: Tiffany Chang (tic) <tic@odoo.com>