[FIX] stock_account: rounding_adjustment missing pop in stock replenish call
In some cases, when changing cost method for a product category, a
ValueError: Invalid field 'rounding_adjustment' on model 'stock.valuation.layer'
is raised.

This is because in commit https://github.com/odoo/odoo/commit/862d3bdfb581437210fbbf57d833d5b03cbe0e58
a bug was introduced: a _prepare_out_svl_vals() call was added, without
rouding_adjustment svl_vals dict pop when SVL final description is defined.