Cherry pick of 361eac12074e480d26c23d6f2eba704a18515f2d failed
stdout:

stderr:
error: could not apply 361eac12074... [IMP] website, web_tour: have steps to select shape or color
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'