[FIX] website_sale: Fixed error for bool object attribute
When there is no default confirmation template,
An error is raised:
AttributeError: 'bool' object has no attribute 'exists'.
This happens because default_template is False,
So calling default_template.exists() results in the error.
The issue occurs during the upgrade process.

```
File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3142, in _init_column
    value = field.default(self)
  File "/home/odoo/src/odoo/19.0/addons/website_sale/models/website.py", line 52, in _default_confirmation_email_template
    if default_template.exists():
AttributeError: 'bool' object has no attribute 'exists'
```

closes odoo/odoo#249658

X-original-commit: 78a37ab34bf5e188dc3f60445f2d76b7f3353940
Signed-off-by: Valentin Chevalier <vcr@odoo.com>