[FIX] l10n_eu_oss: prevent error when clicking on Refresh tax mapping
When the user selects multiple companies and clicks on Refresh tax mapping,
a traceback will appear.

Steps to reproduce the error:
- Install "l10n_eu_oss" module
- Select multiple companies
- Go to Invoicing > Configuration > Settings > Taxes >
  EU Intra-community Distance Selling > Click on Refresh tax mapping

Error: A traceback appears:
"ValueError: Expected singleton: res.company(1, 2)"

https://github.com/odoo/odoo/blob/bbcef64e3296efa2b985e8d08dfe0573dc62dbb4/addons/l10n_eu_oss/models/res_company.py#L32
Here, "self" is used instead of "company", When self has multiple companies,
It will lead to the above traceback.

sentry-6002997139