Cherry pick of f3a6b0ee4391e2fe702f037b942bc0e3654a39c2 failed
stdout:

stderr:
10:54:10.068323 git.c:344               trace: built-in: git cherry-pick f3a6b0ee4391e2fe702f037b942bc0e3654a39c2
error: could not apply f3a6b0ee439... [FIX] base: compatible with python 3.9
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: