[FIX] google_spreadsheet: fix parameters in spreadsheet pivot insertion
Observed Behaviour

When opening a pivot view (in any of Odoo module) and trying to import
it in a Google Spreadsheet, we get the following error:
UncaughtPromiseError > TypeError
Uncaught Promise > Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
at AddToGoogleSpreadsheet.addToGoogleSpreadsheet (...)
at HTMLSpanElement.eval (eval at _compile (...)

Expected Behaviour

When trying to import the pivot in a spreadsheet, everything should
work fine, openning a new tab with a Google spreadsheet.

Reproducibility

This issue can be reproduced following these steps:
1. Install the 'Google Spreadsheet" module
2. Go to 'Settings' > 'Google Drive' and set your credentials
3. Go to the Sales App
4. Select the pivot view
5. Click on 'Favorites' > 'Add To Google Spreadsheet'

Fix Description

The original issue was coming from the fact we try to access the ID
of a null view, giving us the reported error. Moreover, after fixing
this issue, we got another error coming from the fact the config
method was called with a domain passed as a list, while it need a
string. Both errors were corrected in the way it was already done in
https://github.com/odoo/odoo/blob/2e5acb4b15422c1ee38c5630e4fdb929d7a24d3c/addons/google_spreadsheet/static/src/legacy/js/add_to_google_spreadsheet_menu.js#L25

Related Issues/PR

opw-2794744
opw-2761065
opw-2752840

X-original-commit: cd6a2c83a9c9dbc7efcecb69b542a237a30cc8a8