[FIX] sale: prevent error when replacing combo product on sale order line
Currently, an error occurs when a user replaces a combo product with another
product in a sale order line before the order is saved.

Steps to produce:

- Install the sale_management module with demo data.
- Open sale order, click Add a product, and add a combo product (Office Combo).
   (Make sure the form is not saved)
- Click on the combo name (Office combo x 1) and replace it with another product.

Error:
IndexError: tuple index out of range

Root cause:
After PR [1], at [2], when a combo product is replaced before the order is
saved, the code attempts to update the combo item lines even though the
template type (`product_template_id.type`) is not `combo`. This leads to an
update of `product_uom_qty`, which triggers the `_compute_price_unit` method
and results in the error at [3].

Fix:
This commit prevents errors when a user replaces a combo product with
another product.

[1]:
https://github.com/odoo/odoo/pull/194496

[2]:
https://github.com/odoo/odoo/blob/47e561bd1f6bc14724d60ebf09a66e458dfd4799/addons/sale/models/sale_order.py#L966-L970

[3]:
https://github.com/odoo/odoo/blob/c758b93a57cd98ab76c26c03bd0097f2eef50961/addons/sale/models/sale_order_line.py#L766

sentry-7009976704

closes odoo/odoo#237882

X-original-commit: bc84c0c100aa88a44288cd7391f57459c49a3238
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>
Signed-off-by: Louis Tinel (loti) <loti@odoo.com>