[FIX] l10n_es_edi_facturae: fix test_import_multiple_invoices
__Current behavior before commit:__
If `crm` is installed `test_import_multiple_invoices` will fail because
the crm demo data are changing the email of the partner
`base.res_partner_12` (i.e. Azure Interior)(see [crm_lead_demo.xml][1]).
`partner` will therefore be `False`.

__Description of the fix:__
Creating a new company partner in `setUpClass` and using the same
contact details in the XML files that were using Azure Interior.
This way we make sure those tests do not depend on modifications from
other modules.

__Steps to reproduce the issue:__
Run:
```sh
./odoo/odoo-bin -d test-17 -i crm,l10n_es --test-tags .test_import_multiple_invoices --addons-path=./enterprise,./odoo/addons
```
You will get:
```log
odoo.addons.l10n_es_edi_facturae.tests.test_edi_xml: FAIL: TestEdiFacturaeXmls.test_import_multiple_invoices
Traceback (most recent call last):
  File "/home/odoo/src/odoo/addons/l10n_es_edi_facturae/tests/test_edi_xml.py", line 283, in test_import_multiple_invoices
    self.assertRecordValues(moves, [
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 659, in assertRecordValues
    self.fail('\n'.join(errors))
AssertionError: The records and expected_values do not match.

==== Differences at index 0 ====
---

+++

@@ -1 +1 @@

-partner_id:14
+partner_id:False

==== Differences at index 1 ====
---

+++

@@ -1 +1 @@

-partner_id:14
+partner_id:False
```

opw-4009379

[1]: https://github.com/odoo/odoo/blob/1c8e2555366fe6e6b0d74d6db71a29d09bd5f06a/addons/crm/data/crm_lead_demo.xml#L606