[FIX] analytic: Support updating analytic.project_plan sys param
The dynamic fields created for each analytic plan, besides the project plan do not update when the project plan system parameter changes.

1. Set the analytic.project_plan system parameter to a value other than 1
2. Enable Analytic Accounting setting under Accounting > Analytic
3. Create a sales order with a service product that creates a project.
4. Confirm sales order and receive a traceback:
    ValueError: Invalid field account.analytic.line.x_plan1_id in leaf ('x_plan1_id', 'in', [23])

A field on account.analytic.line is created for every plan using the id of the plan to make the names unique, like x_plan{id}_id.
The plan that has the ID of the analytic.project_plan parameter does not get a dynamic field, it uses account_id.
If you change the system parameter for analytic.project_plan, the plan with the corresponding value will now use account_id, and the plan
that corresponds to the previous default value will have no corresponding field on account.analytic.line.

Extend the write method on ir.config_parameter so that when the value of the analytic.project_plan is changed the dynamic fields on
account.analytic.line are properly added and removed. This solution always creates a field for the previous value and
deletes a field for the new value so that no plan ever has two fields referencing it.
opw-ticket 5069381