[FIX] web: correct formating date
FYI: numbers in arabic localization are not arabic (also known as "western
arabic"), but "eastern arabic":
* western arabic: 0	1	2	3	4	5	6	7	8	9	10
* eastern arabic: ٠	١	٢	٣	٤	٥	٦	٧	٨	٩	١٠

STEPS:
* install and switch to arabic language
* install and open hr_holidays app

BEFORE:
ValueError: time data '٢٠٢٠-١١-٢٧' does not match format '%Y-%m-%d'

AFTER: no error, dates are formated in western arabic

---

opw-2422915