Cherry pick of 3ef8eb4de0f48369f1c6bb3e2a5f34e89115cc1b failed
stdout:

stderr:
Performing inexact rename detection:  49% (1342460/2720600)   Performing inexact rename detection:  50% (1360300/2720600)   Performing inexact rename detection:  51% (1389290/2720600)   Performing inexact rename detection:  52% (1416050/2720600)   Performing inexact rename detection:  53% (1442810/2720600)   Performing inexact rename detection:  54% (1469570/2720600)   Performing inexact rename detection:  55% (1496330/2720600)   Performing inexact rename detection:  56% (1525320/2720600)   Performing inexact rename detection:  57% (1552080/2720600)   Performing inexact rename detection:  58% (1581070/2720600)   Performing inexact rename detection:  59% (1605600/2720600)   Performing inexact rename detection:  60% (1632360/2720600)   Performing inexact rename detection:  61% (1663580/2720600)   Performing inexact rename detection:  62% (1688110/2720600)   Performing inexact rename detection:  63% (1714870/2720600)   Performing inexact rename detection:  64% (1741630/2720600)   Performing inexact rename detection:  65% (1768390/2720600)   Performing inexact rename detection:  66% (1797380/2720600)   Performing inexact rename detection:  67% (1824140/2720600)   Performing inexact rename detection:  68% (1850900/2720600)   Performing inexact rename detection:  69% (1877660/2720600)   Performing inexact rename detection:  70% (1904420/2720600)   Performing inexact rename detection:  71% (1933410/2720600)   Performing inexact rename detection:  72% (1960170/2720600)   Performing inexact rename detection:  73% (1986930/2720600)   Performing inexact rename detection:  74% (2013690/2720600)   Performing inexact rename detection:  75% (2040450/2720600)   Performing inexact rename detection:  76% (2069440/2720600)   Performing inexact rename detection:  77% (2096200/2720600)   Performing inexact rename detection:  78% (2122960/2720600)   Performing inexact rename detection:  79% (2149720/2720600)   Performing inexact rename detection:  80% (2176480/2720600)   Performing inexact rename detection:  81% (2205470/2720600)   Performing inexact rename detection:  82% (2232230/2720600)   Performing inexact rename detection:  83% (2258990/2720600)   Performing inexact rename detection:  84% (2285750/2720600)   Performing inexact rename detection:  85% (2312510/2720600)   Performing inexact rename detection:  86% (2341500/2720600)   Performing inexact rename detection:  87% (2368260/2720600)   Performing inexact rename detection:  88% (2395020/2720600)   Performing inexact rename detection:  89% (2421780/2720600)   Performing inexact rename detection:  90% (2453000/2720600)   Performing inexact rename detection:  91% (2477530/2720600)   Performing inexact rename detection:  92% (2504290/2720600)   Performing inexact rename detection:  93% (2531050/2720600)   Performing inexact rename detection:  94% (2560040/2720600)   Performing inexact rename detection:  95% (2595720/2720600)   Performing inexact rename detection:  96% (2613560/2720600)   Performing inexact rename detection:  97% (2640320/2720600)   Performing inexact rename detection:  98% (2669310/2720600)   Performing inexact rename detection:  99% (2693840/2720600)   Performing inexact rename detection: 100% (2720600/2720600)   Performing inexact rename detection: 100% (2720600/2720600), done.
error: could not apply 3ef8eb4de0f... [FIX] account_voucher: no restrictions on payment account type
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/account_voucher/models/account_voucher.py'