[FIX] base.module.uninstall model gets errors when trying to call onchange from the server. This happen duing the unistallation of a few installed modules, you can produce the error by install discuss(for example) and uninstall it again in freshly initialized database. The error happen to be caused by odoo.models._get_external_ids method, when reading external_ids of records with ids of NewId type.
Traceback (most recent call last):
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/api.py", line 890, in get
    return field_cache[record._ids[0]]
KeyError: <NewId origin=2103>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/fields.py", line 1126, in __get__
    value = env.cache.get(record, self)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/api.py", line 893, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'ir.model.fields(<NewId origin=2103>,).modules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/http.py", line 1381, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/service/model.py", line 136, in retrying
    result = func()
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/http.py", line 1410, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/http.py", line 1607, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/addons/base/models/ir_http.py", line 137, in _dispatch
    result = endpoint(**request.params)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/http.py", line 541, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/mohamed/odoo_arena/odoo/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/mohamed/odoo_arena/odoo/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6636, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6418, in __init__
    self.fetch(name)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6426, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6426, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6418, in __init__
    self.fetch(name)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6426, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6426, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6418, in __init__
    self.fetch(name)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6428, in fetch
    self[name] = record[name]
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 6040, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/fields.py", line 1175, in __get__
    self.compute_value(recs)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/fields.py", line 1334, in compute_value
    records._compute_field_value(self)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 4409, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/addons/base/models/ir_model.py", line 548, in _in_modules
    xml_ids = models.Model._get_external_ids(self)
  File "/home/mohamed/odoo_arena/odoo/odoo/odoo/models.py", line 5123, in _get_external_ids
    result[data['res_id']].append('%(module)s.%(name)s' % data)
KeyError: 2072