[FIX] l10n_sa_edi: missing reason when reversing entries
With a SA company setup
Open a jounrnal entry
Hit 'Reverse Entry' > Reverse
Error: "For Credit/Debit notes issued in Saudi Arabia, you need to
specify a Reason"

This occurs because with SA localization we need to provide a reason for
move reversal but by default the reason field is invisible for journal entries

opw-3789732

closes odoo/odoo#158782

X-original-commit: d660fd5204dcb42c45b466a1fbc0ca7f8bf7cbe6
Signed-off-by: Claire Bretton (clbr) <clbr@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>