[FIX] stock: fix label_transfer_template report
Steps to reproduce:
- Create a PDF report for the stock.picking model
- Add the template stock.label_transfer_template_view_pdf.
- When printing the report for the transfer record, an metioned error occurred.

```py
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'stock.picking' object has no attribute 'move_lines'
Template: stock.label_transfer_template_view_pdf
Path: /t/t/div/t[2]/t[2]
Node: <t t-foreach="picking.move_ids" t-as="move"/>
```
- [Ref](https://github.com/odoo/odoo/pull/78732) were move_lines has been renamed to move_ids.
- [Ref](https://github.com/odoo/odoo/pull/80434) were product_uom_qty has been renamed to reserved_uom_qty.