[FIX] l10n_pe: fix parent view of address_form_fields
Issue:
------
`l10n_pe.address_form_fields` inherits from `portal.address_form_fields`
but targets a `<div>` element that has been moved to
`portal_address_extended.address_extended_form_fields` in [saas~19.2].

Traceback:
----------
```py
Error while rendering the template:
    ValueError: Element '<div id="div_city_id">' cannot be located in parent view (view: l10n_pe.address_form_fields)
    Template: website_sale.address
    Reference: 1973
    Path: /t/t/div/div/form/div/t
    Element: <t t-call="website_sale.address_form_fields"/>
```

Steps to reproduce:
-------------------
1. Install `l10n_pe` and `website` in v19
2. Upgrade to v19.2
3. Go to the website and add a product to the cart
4. Go to checkout → Traceback

Root cause:
-----------
The view is adapting an element owned by a sibling view, making the
inheritance hierarchy conceptually wrong and fragile.

Solution:
---------
Update the `inherit_id` of `l10n_pe.address_form_fields` to
`portal_address_extended.address_extended_form_fields` so it correctly
inherits from the view that owns the targeted element.

opw: [6302145]

[saas~19.2]: https://github.com/odoo/odoo/commit/026c6f9f2a388ee509a135c53e38f5bb3d08ff73#diff-83bb066f4477532b76aadd957ae736d0c0b67bc66b48d6f47c035e8cfb4773deR7-R21
[6302145]: https://www.odoo.com/odoo/70/tasks/6302145?debug=1

X-original-commit: 6d57ed27830b09bd76be5e3222136a4b1b6eb0b4