[FIX] website: check menu.url datatype is sting or not
When a user changes homepage url and adds a menu with no url and
then tries to go to homepage then the traceback is generated.

Steps to reproduce:
- Install Website module.
- Go to Configuration > Menus > Create a new menu without URL,
website as My Website and parent menu as Top Menu for Website 1 [My Website]
- Go to Site > Properties > Page URL.
- Change its route by adding 'test' to url and activate redirect old url button.
- Repeat above two steps.
- Now go to Site > Homepages, the traceback will occur.

Error: AttributeError: 'bool' object has no attribute 'startswith'

The issue is occurring because value of menu.url is False over here -
https://github.com/odoo/odoo/blob/7e2e2e0b257d44ce051a3ee8f60e9e03f5d14739/addons/website/controllers/main.py#L113

To solve this issue the datatype of menu.url is checked whether
it is string or not.

sentry-4527212121