[FIX] stock,mrp: skip deleted moves on `_action_done`
To reproduce the issue:
1. In Settings, enable:
   - Multi-Routes
2. Update the warehouse:
   - Manufacture: 2-steps
3. Create three storable product P1, P2
4. Create and confirm a MO:
   - Product: P1
   - Components:
     - 1 x P2
     - 1 x P2
5. Set the produced/consumed quantities:
   - On the first line of P2, set 1.5
6. Mark the MO as done

Error: an error message is displayed: "Record does not exist or has
been deleted"

Step 6, we iterate on the raw SM:
https://github.com/odoo/odoo/blob/e029abe649573350e633999e42ab040c57b8fe4e/addons/stock/models/stock_move.py#L1706-L1710
First iteration, because of the extra qty, we create an extra move.
But, because of the 2 steps delivery, the initial move is an MTO one
and the extra move is an MTS one. As a result, we will confirm the
extra move without providing any `merge_into`:
https://github.com/odoo/odoo/blob/e029abe649573350e633999e42ab040c57b8fe4e/addons/stock/models/stock_move.py#L1684-L1690
Therefore, in the merge process, we will create some group of
candidates and one of them will be the raw SM of the MO for product P2:
https://github.com/odoo/odoo/blob/ba8f99c0a64560dae5ed31f38fcaa6c60a34a7d8/addons/mrp/models/stock_move.py#L508-L511
Then, when processing this group, both raw SM will be merged (same
product, and so on), so the second raw SM of P2 will be deleted.
Back to the iteration, we now iterate on that second raw SM, but it
does not exist anymore, hence the error.

OPW-3432293

X-original-commit: 5dd9bfa52e63efa1b3a8330f46321459009d6716