[FIX] mrp: Fix rounding issue to get correct value
as this pr is [merged]
(https://github.com/odoo/odoo/pull/152709)
so due to this float_round behaviour is bit changed due to that
here is test case is failing in upgrade that checks the qty_available
with product their is difference come here

[here]
(https://github.com/odoo/odoo/blob/251ef3edcc7e0894683acb7c69bfa437a024110f/addons/stock/models/product.py#L207)
before record ``qty_avaliable`` (it non stored field and compute)
to come like this ``'qty_available': 0.7000000000000001 ``
after float_round and now after this pr in 17.4 value is
 ``'qty_available': 0.7`` coming like this and after dividing
[here]
(https://github.com/odoo/odoo/blob/913c081a8687d0f2aa6c40faeee9013fa10865db/addons/mrp/models/product.py#L280)
with 0.1 becomes like
```py
before

0.7000000000000001/0.1
7.0

after
0.7/0.1
6.999999999999999
```
while taking quotent [here]
(https://github.com/odoo/odoo/blob/b3d61b372a8cd315f9063b6add634ad194f3341b/addons/mrp/models/product.py#L264)
it taking 6 instead of 7 so this difference come and test case failed

```
AssertionError: Lists differ: [[142[456 chars]63, '7'], [14264, '0.7'], [14265, '-30'], [142[12426 chars]-2']] != [[142[456 chars]63, '6'], [14264, '0.7'], [14265, '-30'], [142[12426 chars]-2']]

First differing element 27:
[14263, '7']
[14263, '6']

Diff is 15569 characters long. Set self.maxDiff to None to see it. : Invariant check fail
```
for correcting this as discussed here
https://github.com/odoo/odoo/pull/152709#issuecomment-2383006955
fix is proposed.

closes odoo/odoo#183995

X-original-commit: 36392ff50fa1d7163b2e46eb4bef354ac7f365d7
Signed-off-by: William Henrotin (whe) <whe@odoo.com>