Cherry pick of 37681e9d2e24663691b4be022f34c29c7126d9f6 failed
stdout:

stderr:
13:41:16.253112 git.c:344               trace: built-in: git cherry-pick 37681e9d2e24663691b4be022f34c29c7126d9f6
error: could not apply 37681e9d2e2... [IMP] mrp: cancel workorder in backorder when qty_remaining is 0
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: