[FIX] stock: getting value from context in inventory
Attribute Error: 'frozendict' object has no attribute 'default_product_id'
trace back that occurs in stock/stock_quant: action_inventory_at_date
was caught by sentry.

steps to produce:-
Install inventory module
Select any product from menuitem/reporting/stock
Click replinish button & from that replinish wizard, select the product again
Then click forecasted stat button and in forecast click On Hand button
Then click Inventory At Date.
At this moment you find a trace back.
Because default_product_id is not getting from context in inventory.

sentry:-3952193922

closes odoo/odoo#115638

Signed-off-by: William Henrotin (whe) <whe@odoo.com>