[FIX] payment_mercado_pago: prevent payment without account country
Steps to Reproduce:
- Install `website_sale` with demo data.
- Activate the "Mercado Pago" payment provider.
- Website > Shop > Add a product > Go to cart and proceed to Checkout.
- Select the "Card" payment method and proceed.

Error:
AttributeError: 'bool' object has no attribute 'lower'

Cause:
Before commit https://github.com/odoo/odoo/commit/1ef1b73ee2ec3c1adfdffe32c34bb441b97dfbec,
the availability of a payment provider was controlled by the `state` field
('disabled', 'enabled', 'test'). To use Mercado Pago in test mode, users first
had to configure an account country (mercado_pago_account_country_id).

But after this commit, the `state` field has been replaced by `is_live`.
By default, providers are available in test mode when `is_live` is disabled,
allowing users to make a test payment. - [1]
During payment processing, the missing account country leads to an error.

Fix:
Before processing a payment, ensure that an account country is configured and
raise a validation error if it is missing.
Ref - https://github.com/odoo/odoo/blob/ada769dac1deda7dbd89596153f97c6f5887f57a/addons/payment_mercado_pago/models/payment_provider.py#L154-L157

[1]: https://github.com/odoo/odoo/blob/ada769dac1deda7dbd89596153f97c6f5887f57a/addons/payment/models/payment_provider.py#L38-L43

sentry-7638271109