[FIX] im_livechat: no crash on restart chatbot
Before this commit, when opening a chatbot and then immediately
clicking on restart button, there was this crash:

```
TypeError: LivechatChatbotScriptController.chatbot_restart() missing 1 required positional argument: 'channel_uuid'
```

This happens because livechat allocates a UUID only when the visitor
consumes at least one step of the chatbot. Indeed, there's no point
in storing a livechat session if the user doesn't actively use the
livechat, and a UUID only makes sense when there's an active
livechat session.

This commit fixes the issue by not calling route to restart chatbot
when the livechat has no UUID. Also does not show restart button
when at 1st step.

opw-3429892

closes odoo/odoo#128844

Signed-off-by: Matthieu Stockbauer (tsm) <tsm@odoo.com>