[FIX] l10n_fr_pdp: prevent error when uncheck French E-Invoicing
Steps to reproduce:
- Install 'l10n_fr_pdp' and 'Accounting' > Switch to FR Company
- Activate 'French electronic invoicing'
- Create New Invoice with 'FR Company' as Customer
- Send > unchecked French E-Invoicing (Demo)

Traceback:
AttributeError: 'res.partner' object has no attribute '_get_pdp_receiver_identification_info'

In this REF [PR], we removed the '_get_pdp_receiver_identification_info' method
and replaced it with the 'l10n_fr_is_pdp' field, but we missed updating it here.

Solution:
Replaced the removed '_get_pdp_receiver_identification_info' method with
'l10n_fr_is_pdp'.

[PR]: https://github.com/odoo/odoo/commit/5c3dde7f36609a74ffed8357c11a648d85942bdd#diff-a9b0aba990a93514e74372976dd8c77cda07db893324a0a2fad8a9027ec0b1da

opw-6443303