[FIX] mail_group: fix error when browsing mailing lists
To reproduce (on runbot):

- Go to /groups url
- click on "Public Mailing List"

This fix `AttributeError: 'PortalMailGroup' object has no attribute 'env'`
(introduced by odoo/odoo@2683be7d950)

closes odoo/odoo#123032

X-original-commit: 2bd4a907a0db07ee8bb7f4ffa3017f20c25f79d4
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Signed-off-by: Xavier Alt (xal) <xal@odoo.com>