[FIX] payment: sync access token generation parameters
Versions
--------
- 17.0

Doesn't occur in later versions due to improved rounding utils.

Steps
-----
1. Set up a sales order with a total of $286.90;
2. generate a payment link;
3. open payment link in private window.

Issue
-----
Error: The provided parameters are invalid.

Cause
-----
Commit c59a47da7400 added a `float_repr` to round the amount used in the
url parameters. Issue occurs because this number can be different from
the value used to generate the token, making their hashes different.

Solution
--------
Use `float_repr` when generating a token, and in both instances, convert
the string back into a float so they don't have mismatching zeroes at
the end.

opw-4669839