[FIX] website: restrict access to optimize SEO
When user creates a new 'livechat channel' in website,
and click on 'Optimize SEO' traceback will appear.

To reproduce the issue:

- Install 'website' and 'im_livechat' module
- Go to 'website' module
- Click on 'NEW' and then create a new 'Livechat Widget'
- Go to 'Site' and click on 'Optimize SEO'

Error: A traceback appears: Invalid field 'website_meta_title' on model
'im_livechat.channel'

When user create a new livechat channel in website module, the 'get_seo_data'
method is called and the value of 'res_model' is passed as 'im_livechat.channel'.
Fixed this issue by raising UserError when user tries to access
'Optimize SEO'.

sentry-4241511888