[FIX] config.py Traceback when saving new added section
Before: When creating new section in odoo.conf (eg: [IOT]), first
save is ok since it doesn't exists. But subsequent save fails ->
configparser.DuplicateSectionError: Section 'IOT' already exists

Now: Subsequent saves work

mool