[IMP] account_edi_ubl_cii: add base_vate module in dependency
AttributeError: "res.partner" object has no attribute '_run_vat_test' log error
is generated, and nothing is imported when users upload invoice file that have a
VAT field. This is because the "_run_vat_test" attribute is defined in the
"base_vat" module and is not installed due to countries not having VAT.

This commit add the 'base_vat' in depends to prevent above error.

sentry-4074943505