[FIX] l10n_hu_edi: fix error when printing invoice with section lines
When a user tries to print an invoice with section lines for Hungarian company,
a traceback occurs.

Steps to reproduce the error:
- Install "l10n_hu_edi" module with demo data and switch to HU Company
- Create an invoice > Add a seaction >Add a line under that section > Save
- Confirm > Print

Traceback:
"QWebError: Error while rendering the template:
 TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'"

https://github.com/odoo/odoo/blob/dc6dd927faea1f4501d6c50c586d5ea46bd1fc95/addons/l10n_hu_edi/views/report_invoice.xml#L84-L86
Here, "current_subtotal" is used instead of "section_subtotal".
So, It will lead to the above traceback.

"current_subtotal" was changed to "section_subtotal" in the commit [1],
but the t-out attribute in the same block was not changed accordingly.

[1]: https://github.com/odoo/odoo/commit/af9bf2ac1939aa8d64c4ba5caa202b229debba3f

sentry-6933103730

closes odoo/odoo#231111

X-original-commit: 1e0586aea9081b88098ae7edb59a88a4a9e22bcd
Signed-off-by: Habib Ayob (ayh) <ayh@odoo.com>