[FIX] website_project: prevent error when submitting the “Create a Task” form
Currently, an error occurs when a user submits the “Create a Task” form.

Steps to Reproduce:

 - Install the website_project module.
 - Go to website > Click on Edit > Drag and drop form.
 - Click on the form and, set the action to Create a Task, then save.
 - Fill in the required data in the form.
 - In the Email Address field, enter an email that does not correspond
   to any existing partner.
 - Submit the form, and the error appears in the logs.

ValueError: Invalid field 'email_cc' in 'project.task'

With this [recent commit], the email_cc field has been removed from
project.task, along with the mail.thread.cc inheritance, because threads
are now able to find CC recipients. so, when user submits the form with
an email address that does not correspond to any existing partner, the
system adds email_cc to the record, and when it attempts to create the
record [2], it raises an error.

This commit ensures that email_cc is no longer added to the record.

[recent commit]: https://github.com/odoo/odoo/commit/3c26c0553754a75d9440097ad473be3cc8bcb320#diff-93ba226020add6481cfeab916e69980a59163e2925a5c2c9a3bc0aaceb484cdf

[1]: https://github.com/odoo/odoo/blob/21aa7e7eca0bf78978e0667cee43129985833166/addons/website_project/controllers/main.py#L61

[2]: https://github.com/odoo/odoo/blob/21aa7e7eca0bf78978e0667cee43129985833166/addons/project/models/project_task.py#L1167

sentry-7374084515

X-original-commit: 7bc83630a9290c28db293785331fb43f71f5c8b7