[FIX] resource: prevent attributeerror when opening hours is not selected
When User opens an appointment with resource that does not have Opening Hours,
a traceback will appear.

Steps to reproduce the error:
- Go to 'Appointments' > Configuration > Resources >
  Create a new Resource without opening hours (ex. court) > Save
- Create new Appointment > Availability on: resources > Resource: court > Save
- Click on Go to website or Preview

Error: A traceback appears:
"AttributeError: 'bool' object has no attribute 'upper'"

https://github.com/odoo/odoo/blob/6cb52b4a02a7b3236c20863b177bfaadf474651d/addons/resource/models/resource_resource.py#L147
Here, when the user does not select Opening Hours in resource,
"calendar.tz" will be False.
So, it will lead to the above traceback.

sentry-5475389977

closes odoo/odoo#175763

X-original-commit: fe2cf639202de3d0c823b8dfc5dae1dee470c3b1
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>