[FIX] html_editor: prevent removal of unremovable link element with link popover
Currently, an error occurs when the user edits the 'Contact Us' button and
removes both the label and the link.

Steps to replicate:
* Install website
* website > edit > Click on contact us > Edit Link
* replace all the fields by adding one space ' ' and apply > Save.

Error:
ValueError: Element '<xpath expr='//a[hasclass('oe_unremovable')]'>'
cannot be located in parent view.

Root cause:
* When the user edits the 'Contact Us' button and clears all the fields, then
  clicks 'Apply' line [1] removes the button.
  But the button is meant to be unremovable, so this breaks the website.

Solution:
* Add a check before removal to verify whether the link element is removable
  and only remove it if it is removable.

[1]:https://github.com/odoo/odoo/blob/674280cd86088a6cc3bd5c10dd56ece65bf5e517/addons/html_editor/static/src/main/link/link_plugin.js#L701

sentry-6639000902