[FIX] {website_sale_,}loyalty: prevent error when applying a code
Currently, an error occurs when a user applies a discount code to the cart.

Steps to reproduce:

 - Install the website_sale_loyalty module.
 - Go to Discount & Loyalty and create a new program with
   Program Type = Discount Code.
 - Under the Rules & Rewards tab, add a rule with a code (e.g., demo).
 - Archive the program record.
 - Repeat steps 2 and 3.
 - Unarchive the first record.
 - Go to Website > Shop, add a product to the cart, and go to the cart page.
-  Apply the code demo.

ValueError: Expected singleton: loyalty.program(2, 3)

This error occurs when a user creates a sale loyalty program and
adds a loyalty rule with a code, then archives that record. If the
user creates the same record again and later unarchive the first
record, there will be two rules with the same code, resulting in
two loyalty programs [1], which raises the error [2].
The same issue also occurs in loyalty when creating a new record
with the same code after archiving the first one.

This commit ensures that the system also checks archived records
when unarchiving and verifies that there are no two or more
programs with the same code being unarchived, so that no conflicting
rules are activated.

[1]: https://github.com/odoo/odoo/blob/76a8d6bc28eb5998bd976b3c41bf9772d325c8bf/addons/sale_loyalty/models/sale_order.py#L1351

[2]: https://github.com/odoo/odoo/blob/76a8d6bc28eb5998bd976b3c41bf9772d325c8bf/addons/sale_loyalty/models/sale_order.py#L1371

sentry-6871330244

X-original-commit: 2c779d05428860a12f6fe859eee63bed777d4eb3