[FIX] pos_sale: make default product and down payment product required
Step to reproduce:
- install `pos_sale`
- create a pos and go to settings
- remove product from `Default Sale Product`
- start pos and select a product

Observation:
- we will get a blank screen and error in browser console
```
TypeError: Cannot read properties of undefined (reading 'id')
    at get orderDisplayProductName (point_of_sale.assets_prod.min.js:20914:497)
    at get orderDisplayProductName (point_of_sale.assets_prod.min.js:27593:14)
```
- similar issue when we remove down payment product from config
and try to load a order with downpayment in pos

Cause:
- `default_product_id` was introduce in commit[1] which is necessary for
description first order line
- if we remove this field, for pos config, `this.config.default_product_id`
is undefined, and accessing its id raises error
[1] https://github.com/odoo/odoo/commit/0ce605f8db9aa9901bf6b14c4888e5bcc0734401

Fix:
- as in stable, we cannot make a field "required", we use python constraint
and hook `_check_before_creating_new_session` to ensure every session/config
has these products available with only exception to those session which are
already running
- checks for `down_payment_product_id` in js side are redundant now as we do not
allow opening a session with this product
- for master, we plan to make the field required and remove redundant methods
from js all together

opw-6458117