[ADD] stock_dummy_test and dummy_delivery_depends: To do a PoC of inheritance with the delivery dependency.
stock_dummy_test
Is a module that only depends from stock. So, delivery dependency isn't
needed.
However has an inheritance from stock.quant and that model has a relation
with stock.move in tests. Then stock.move is related to stock.picking
and finally the delivery module inherits stock.picking and adds the
required field weight_uom_id.
In the PoC this module has to fail showing the error:
IntegrityError: null value in column "weight_uom_id" violates not-null
constraint

dummy_delivery_depends:
This module inherits the module above and the delivery dependency. In
tests. The stock_dummy_test module has to fail with the mentioned error
but the dummy_delivery_depends module should not fail its own tests.