[IMP] ormcache: move fallback outside of exception handler
Because `self.method` is currently inside the exception handlers for
cache miss and lookup failure, currently any time a cached function
raises an exception the top of the chained stack is one to multiple
chained traces internal to caching.

These are useless to detrimental, so they should be suppressed and not
show up in the final. However AFAIK there is no easy way to suppress
the context for *indirect* raises (triggered by a function
call).

While technically we could catch the secondary exception and try to
walk the chain of causes to try to find the cache error, this is
probably unnecessarily complicated compared to just moving the call
outside the exception handlers (even if the latter requires a
conditional).

Ideally we would be able to just mark code objects as system /
irrelevant and python would perform the suppression internally, but as
far as I know that's not an option, so handroll the fix.

Before:
```
2025-08-14 07:55:38,137 1730884 WARNING 86823013-master-all odoo.http: <log message>

Traceback (most recent call last):
  File "odoo/odoo/tools/cache.py", line 138, in lookup
    r = d[key]
        ~^^^^^
  File "odoo/odoo/tools/lru.py", line 57, in __getitem__
    val = self._values[key]
          ~~~~~~~~~~~~^^^^^
KeyError: ('ir.qweb', <function IrQweb._get_cached_values at 0x7d414d4df1a0>, ('5060', "'en_US'", 'False', 'None', 'False', 'None', 'None', 'None', '1', 'True', 'None'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "odoo/odoo/tools/cache.py", line 138, in lookup
    r = d[key]
        ~^^^^^
  File "odoo/odoo/tools/lru.py", line 57, in __getitem__
    val = self._values[key]
          ~~~~~~~~~~~~^^^^^
KeyError: ('ir.qweb', <function IrQweb._generate_code_cached at 0x7d414d4dce00>, 'sale.report_saleorder_document', ('en_US', False, False, False, False, False, False, 1, True, False))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<start of the actual traceback>
```

After:
```
2025-08-14 08:13:48,957 1739755 WARNING 86823013-master-all odoo.http: <log message>
Traceback (most recent call last):
<useful traceback>
```