[FIX] account: prevent crash when vendor has multiple uoms across companies
Step to reproduce:

1. Install purchase and account module.
2. Enable the uom option (Purchase > Configuration > Settings).
3. Create a vendor (partner).
4. Create a product that is shared across two companies.
5. Create a product that is shared across two companies.
6. Go to Vendors > Product : in the product’s Purchase tab:
         Add the same vendor twice - one line for each company.
        Assign different UoMs (e.g., “Unit(s)” for US company and
        “Kilogram(s)” for AT company).
7. Switch to one company.
8. Create a vendor bill in one of the companies using that product and vendor.

Issue:

A ValueError is raised when creating the vendor bill:
ValueError: Wrong value for account.move.line.product_uom_id: uom.uom(1, 2)

Cause:

During the computation of product_uom_id  where retrieves all seller records
matching the partner_id  but fails to limit the result.

Solution:

To fix this, retrieve sellers by both partner_id and company_id and first
matching seller is used. This ensures the UoM is correctly set according
to the company also.

opw-4877577