[FIX] l10n_in: handle company ids when loading demo data
When demo data is loaded from Settings after installing l10n_in
without demo data, the _install_demo method receives company ids
instead of a recordset. This causes a crash when calling filtered()
on an integer:

AttributeError: 'int' object has no attribute 'filtered'

Convert the received ids into a res.company recordset before
processing them to ensure demo data can be loaded successfully
from the settings menu.

Steps to reproduce:

Install l10n_in without demo data
Go to Settings and load demo data

closes odoo/odoo#270523

Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>