[FIX] payment_{asiapay,ogone,payulatam}: remove useless AccountTestInvoicingCommon subclassing
Some tests are failing when account isn't installed because they extend
AccountTestInvoicingCommon but they have no dependencies on account:

ValueError: External ID not found in the system: account.group_account_manager

Each addon contains a test
`test_reference_is_computed_based_on_document_name` that is already
skipped if account_payment is not installed.

Similar to https://github.com/odoo/odoo/commit/d844fef414fbd6f59089ce3f0dca34895badfa33

runbot-163120
runbot-163121
runbot-163122
runbot-163161
runbot-163162