[FIX] mrp: display Post Inventory button with tracked products
When less then the planned quantity is produced, if components are
tracked, it won't be possible to post the inventory.

To reproduce the error:
(Enable debug mode. Use demo data)
1. Create two products P_compo and P_finished
    - Type: Storable
    - Tracking: By Lots
2. Update P_compo's quantity: 5 on hand, lot L
3. In Settings, enable "Work Orders"
4. Create a Bill of Materials BM
    - Product: P_finished
    - Quantity: 1
    - Type: Manufacture
    - Routing: Primary Assembly
    - Components:
        - 1 P_compo, consumed in Manual Assembly
5. Create a MO:
    - Product: P_finished
    - Quantity: 5
6. Check Availability, Plan
7. Process the Work Order
    - Validate + Record production with 3 P_finished
8. Go back to MO

Error: Button 'Post Inventory' is not present

To fix this issue, this commit needs to be reverted:
https://github.com/odoo/odoo/commit/75460e697a20505aa22b3a273d3056e0bdc75633
This commit was a fix for another flow: Suppose the same procedure than
above. Without the problematic line, the button 'Post Inventory' is
present. However, if the user clicks on it, he will get an error: "You
need to supply a Lot/Serial number for product Component." Here is the
problem origin:
On step 7, when recording the current production, the sock move line
associated to P_compo is updated: its done quantity is defined (3 in our
case) as well as the lot used (L). Then, a second SML is created for the
last 2 P_compo that would be used for the last 2 P_finished. However,
the done quantity of this SML is already set to 2. Therefore, when
clicking on 'Post Inventory':
https://github.com/odoo/odoo/blob/e5ab8cf9623bc436f43706926bc6ee596c549244/addons/stock/models/stock_move_line.py#L413-L414
This error is raised if (1) the done quantity is > 0 and (2) if the
SML's product is tracked and the SML's lot is not defined, which is the
case for the second SML that has been created.
This is the reason why this commit also suggests to cancel the done
quantity of the second SML, so the condition (1) will not be respected
and the error won't be raised.

Note: This fix only concerns 12.0 and saas-12.3. Here is the fix for
13.0:
https://github.com/odoo/odoo/commit/d7f63ce413525609e09bcbbe16b9d58eae81008b

OPW-2476598

closes odoo/odoo#71731

X-original-commit: 2a1244533e3a0f821d6f2a8869dd070c0e806239
Signed-off-by: William Henrotin <Whenrow@users.noreply.github.com>
Signed-off-by: Adrien Widart <adwid@users.noreply.github.com>