[FIX] website_sale: prevent attributeerror when paying by Demo
If the user's contact have delivery address without contact name and
the user pays for an order by the Demo payment provider,
a traceback will appear.

Steps to reproduce the error:
- Install "website_sale" and "contacts" module
- Activate Demo payment provider
- Go to Contacts > Open Mitchell Admin > Contacts & Addresses
  > Add Delivery Address without Contact Name > Save
- Go to Website >  Shop > Add a product to cart > Proceed to Checkout
  > Pay with Demo > Pay

Error: A traceback appears:
"AttributeError: 'bool' object has no attribute 'endswith'"

https://github.com/odoo/odoo/blob/97d13089ba320ab20e564a45fcd2a6f8b33d8e9b/addons/website_sale/controllers/main.py#L1429
When the delivery address does not have a contact name,
Here, order_sudo.partner_shipping_id.name will be False,
So it will lead to the above traceback.

sentry-4664052401