[IMP] hr: runbot error on TestDeparture.test_departure_notice_contract_date
Currently, there's runbot error where on test_departure_notice_contract_date.
ValueError: Invalid field 'l10n_be_dimona_category' in 'hr.employee'

Error happens because this field was localized for belgium payroll,
but it was used for non-belgium payroll unit-testing.

task-947291