[FIX] pos_hr: initialize employeeBuffer before super call to avoid error
Steps to reproduce:
===================
- Enable Login with Employee in POS settings
- Open POS and log in with employee
- Turn off the internet connection
- Reload the POS page

Issue:
======
- POS crashes with the following error:
TypeError: Cannot read properties of undefined (reading push)
- At that point, employeeBuffer is still undefined

Cause:
======
- The method set_cashier() is triggered during the parent setup()
- employeeBuffer was only initialized after super.setup()
- In offline mode, this sequence still executes, leading to an exception
when trying to .push() into an undefined buffer

Fix:
====
- Moved the initialization of employeeBuffer to the beginning of the
setup() method

Task: 4850543
Runbot Error: 227777

X-original-commit: b333b2703ff97c19d6acb9b4093f0c17b06b1a90