[FIX] account_payment: right context for payment creation
Steps to reproduce:
- Install eCommerce and `l10n_be` (to get a second company)
- Enable online payment in the settings
- Go to the payment provider and duplicate it for belgium company
- Publish the payment provider
- Make an invoice for a customer
- Send or generate the link
- Open the link in incognito
- Pay the invoice

Issues:

A traceback arises:

File "odoo/addons/payment/controllers/post_processing.py", line 54, in poll_status
  monitored_tx._finalize_post_processing()
File "odoo/addons/account_payment/models/payment_transaction.py", line 217, in _finalize_post_processing
  super()._finalize_post_processing()
File "odoo/addons/payment/models/payment_transaction.py", line 1001, in _finalize_post_processing
  self.filtered(lambda tx: tx.operation != 'validation')._reconcile_after_done()
File "odoo/addons/account_payment/models/payment_transaction.py", line 128, in _reconcile_after_done
  tx._create_payment()
File "odoo/addons/account_payment/models/payment_transaction.py", line 181, in _create_payment
  ).reconcile()
File "odoo/addons/account/models/account_move_line.py", line 2959, in reconcile
  return self._reconcile_plan([self])
File "odoo/addons/account/models/account_move_line.py", line 2369, in _reconcile_plan
  self._reconcile_plan_with_sync(plan_list, all_amls)
File "odoo/addons/account/models/account_move_line.py", line 2516, in _reconcile_plan_with_sync
  exchange_diff_values = exchange_lines_to_fix._prepare_exchange_difference_move_vals(
File "odoo/addons/account/models/account_move_line.py", line 2627, in _prepare_exchange_difference_move_vals
  accounting_exchange_date = journal.with_context(move_date=exchange_date).accounting_date if journal else date.min
(...)
File "odoo/addons/account/models/account_journal.py", line 417, in _compute_accounting_date
  journal.accounting_date = temp_move._get_accounting_date(move_date, has_tax)
File "odoo/addons/account/models/account_move.py", line 4360, in _get_accounting_date
  lock_dates = self._get_violated_lock_dates(invoice_date, has_tax)
File "odoo/addons/account/models/account_move.py", line 4391, in _get_violated_lock_dates
  return self.company_id._get_violated_lock_dates(invoice_date, has_tax)
File "odoo/addons/account/models/company.py", line 370, in _get_violated_lock_dates
  self.ensure_one()
File "odoo/odoo/models.py", line 5852, in ensure_one
  raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.company()

During the payment reconciliation, a temporary move is created to compute some data,
but it's created only with the given journal of the payment, not its company.
Therefore, it'll try to fall back on the journal company (see account.move _compute_company_id),
which might not be accessible if not in the default companies of the environment
(aka the user one by default), ending up with a temporary move without any company,
which will fail as the company is required to compute some data.

To avoid this issue, we make sure that the company of the environment is correctly set to
the transaction company, ensuring the company will be considered accessible (cf _accessible_branches)
and the payment reconciliation won't fail.

opw-3859791

closes odoo/odoo#169121

X-original-commit: 2595116bd8c63da16abeda04a16f30aa74cb0c37
Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>
Signed-off-by: Mattis Megevand (mmeg) <mmeg@odoo.com>