[FIX] base: properly handle bad value in attrs view attribute
View specification may have `attrs` attributes, where we specify domain when
extra properties must be applied. Example:

```
<button ... attrs="{'invisible': [('has_accounting_entries','=', False)]}"/>
```

Since Odoo provides admin tools to modify view by user, the view is validated
before saving. If there is an error, user will see error message explaining what
is wrong with the changes.

Such an error message wasn't clear if user passes random string to `attrs`
value. One of the examples caught by sentry [1]:

```
<button ... attrs="'{mobiel}'"/>
```

Before this commit, the user get traceback

```
AttributeError
'ValueError' object has no attribute 'context'
```
with traceback pointing to another error processing [2]

After this commit the error message points exactly to the badly formatted
dictionary.

[1]: https://online.sentry.io/issues/3942045631/
[2]: https://github.com/odoo/odoo/blob/57a89dd6011442fc261cce4891a7d14b2e9ffabd/odoo/addons/base/models/ir_ui_view.py#L480