[FIX] stock: prevent error when report not found
This error occurs when the user deletes the ‘Lot/Serial Number (PDF)’ report
and then attempts to print report.

Steps to reproduce:
- Install 'stock' module(without demo)
- Search 'Lot/Serial Number (PDF)' in ..Actions/Reports > Delete it
- Enable 'Lots & Serial Numbers' in settings.
- Create a Picking and 'Mark as TODO'
- Set a 'Serial Numbers' in order line
- In cog menu Print Labels > Lot/SN labels > Confirm > Confirm

Traceback:
ValueError: External ID not found in the system: stock.action_report_lot_label

At [1], when we try to access any report XML ID, we encounter an error because
the corresponding report has been deleted.

[1]- https://github.com/odoo/odoo/blob/b6b37a794f9e3e724a32a3529ce2ef7361b8046e/addons/stock/wizard/stock_lot_label_layout.py#L40

sentry-7064566500