[FIX] point_of_sale: fix crash in order details using currency getter
Steps to reproduce:
===================
- Open Retail POS
- Add at least one product to the order
- Go to the Payment Screen
- Select any payment method
- Navigate to the Ticket Screen
- Click the (i) button to open Order Details

Issue:
======
- Application crashes with an OWL lifecycle error:
  TypeError: Cannot read properties of undefined (reading 'id')
- At that point, this.props.order.currency_id is undefined

Cause:
======
- The currency_id relation field may not be fully loaded when orders
  are accessed during certain navigation flows (Payment Screen → Ticket Screen)
- The method formatCurrency() tried to access currency.id on an undefined object

Fix:
====
- Changed formatCurrency() in OrderDetailsDialog to use the currency
  getter instead of the direct currency_id field

Task:6178180

closes odoo/odoo#262437

Signed-off-by: David Monnom (moda) <moda@odoo.com>