[FIX] *: kit product invoiced then delivered
* mrp_account, purchase_{stock, mrp}, sale_{stock, mrp}

Steps to reporduced:

- In the settings enable: Automatic Accounting
- Create 3 storable product:
	- COMP1, cost 1 $
	- COMP2, cost 2 $
	- KIT with a kit bom using COMP1 and COMP2, cost 3 $
- Modify the product category of all three products to:
    - Costing Method: AVCO
    - Inventory Valuation: Automated
- Create and confirm a sale order with 2 lines:
    - 1 x KIT
    - 1 x COMP2
- Create and confirm the associated incoive
- Try to validate the delivery
> UserError: You are trying to reconcile some entries that are already
> reconciled.

Cause of the issue:

Validating the delivery will create stock valuation layers related to
the associated stock moves — one for COMP1 and two for COMP2 — and then
attempt to validate the corresponding accounting entries:
https://github.com/odoo/odoo/blob/596937dfef4d203b0cbf5431e71a97f60154d7cb/addons/stock_account/models/stock_move.py#L283-L291

However, during this call, the SVLs are grouped by product_id:
https://github.com/odoo/odoo/blob/596937dfef4d203b0cbf5431e71a97f60154d7cb/addons/stock_account/models/stock_valuation_layer.py#L88-L93

As a result, the first time we enter the loop, the accounting entries
related to COMP01 will not be reconciled by the
`_stock_account_anglo_saxon_reconcile_valuation` call. This is because
we restrict this call using the product COMP01. Therefore, we will not
find the invoice needed to reconcile the outgoing moves here:
https://github.com/odoo/odoo/blob/596937dfef4d203b0cbf5431e71a97f60154d7cb/addons/stock_account/models/account_move.py#L217-L219
(This happens because the related line of the invoice actually refers to
the kit product, as the AMLs were not exploded like the stock moves.)

Now, the issue is that, since the AMLs were not reconciled, they will be
added to the pool of lines to be reconciled later:
https://github.com/odoo/odoo/blob/596937dfef4d203b0cbf5431e71a97f60154d7cb/addons/stock_account/models/stock_valuation_layer.py#L92-L100

However, the second time we enter the loop — for COMP02 — since COMP02
was sold by itself, there will be an account move line referring to this
product on the invoice. The `_stock_account_anglo_saxon_reconcile_valuation`
call, now restricted to COMP02, will therefore reconcile the AMLs for
both COMP02 and COMP01 related to the kits (as it successfully finds the
invoice to reconcile all outgoing moves). This is problematic because
the AML related to COMP01 has now been reconciled, despite already
having been added to the set of moves to be reconciled. This will raise
an error during the second reconciliation attempt:
https://github.com/odoo/odoo/blob/596937dfef4d203b0cbf5431e71a97f60154d7cb/addons/account/models/account_move_line.py#L2379-L2380

Fix:

In the case of kit products, the account move lines of the invoice refer
to a different product than the stock valuation layers (because the
stock move was exploded but not the AMLs). Therefore, it is important to
refer to the kit product during the reconciliation process.

We achieve this by grouping the SVLs using the product of their
associated SOL or POL. Unfortunately, we cannot rely on the product
from the BoM related to the stock move of the SVL, as kits can be nested
within one another. In such cases, the invoice related to the SO or the
bill related to the PO would not refer to the intermediate kit we would
found that way.

opw-4864925

closes odoo/odoo#225706

X-original-commit: 94fe3abaf561fe2c7e44f1d79e5dbb8d1000b890
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Lancelot Semal (lase) <lase@odoo.com>