[FIX] website_{cf_turnstile,mass_mailing}: turnstile ok with newsletter
Forward-port of: 10550b3c7ad607576dc48eeba4d601184a2f90d4

Scenario:

- configure turnstile in setting
- install website_mass_mailing
- drop the newsletter widget in any page

Result:

In saas-18.3 and over, we get this traceback error and the turnstile
code is not working:

 TypeError: Cannot destructure property 'turnStile' of
 'odoo.loader.modules.get(...)' as it is undefined.

Cause:

- On January 2025, in saas-18.2 and over,
  f512afe736deda14e1de88bf45dd72d21bbcef5c and
  6b0c8f7d3cf40275cf9d0baf8c59091b997e20a8 rewrote turnstile
- On April 2025, in 17.0 up to master,
  c48e74f57569a1670fee65d65625488846513d79 uses addTurnstile and
  addSpinner method and the old file
- On April 2025, in saas-18.2 and only saas-18.2,
  10550b3c7ad607576dc48eeba4d601184a2f90d4 fixes turnstile for the
  interaction rewrite

So turnstile still cause an error  with the newsletter widget in
saas-18.3 up to master.

Fix: forward-port the saas-18.2 10550b3c7ad607576dc48eeba4d601184a2f90d4
fix in following versions.

opw-4925771
opw-4933957

closes odoo/odoo#220497

X-original-commit: b365ffba2f85849de3013b1610af64826807f625
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>
Co-authored-by: bram1000 <brvg@odoo.com>