[FIX] iot_box_image: pip install error with new image
When checking out 19.0 from the new IoT box image running Python 3.13,
there is an error when running `pip install`:

```
error: subprocess-exited-with-error

× Building wheel for cffi (pyproject.toml) did not run successfully.
```

This is due to it trying to install `aiortc` and all its dependencies
via `pip` even though it is already installed via `apt`.

To fix this, we add a Python version check to the requirement, so that
it will only be installed when using an old IoT box image.

closes odoo/odoo#234897

Signed-off-by: Louis Travaux (lotr) <lotr@odoo.com>