[FIX] project, test_orm: prevent error when editing multiple project names
Currently, an error will occur when user multi edits name of projects.

Steps to replicate:
- Install `project` and open projects.
- From the list view select multiple projects and edit their name.

Error:
```
File '/home/odoo/src/odoo/saas-19.3/addons/project/models/project_project.py', line 754, in write
    analytic_account_to_update.write({'name': self.name})
File '/home/odoo/src/odoo/saas-19.3/odoo/orm/fields.py', line 1728, in __get__
    record.ensure_one()
File '/home/odoo/src/odoo/saas-19.3/odoo/orm/models.py', line 5341, in ensure_one
    raise ValueError('Expected singleton: %s' % self)
ValueError: Expected singleton: project.project(8, 9, 10)
```

Cause:
- As multiple records were changed at the moment `self` had multiple recordsets
  and trying to access `self.name` [1] causes this error.

Solution:
- Avoided accessing self.name on a multi-recordset during multi-edit.
- Updated analytic account names using the name received in vals.
- Added these fields to the translated field write whitelist to explicitly
  mark this usage as supported as both the fields are translated.
- Copied field_names so that removing values during the test does not mutate
  the original whitelist.

[1]: https://github.com/odoo/odoo/blob/a69ec43f490735f639292d116b0207182c5b2581/addons/project/models/project_project.py#L608

sentry-7452096418

X-original-commit: 37949c055108b529287fe6840eaacf9909d8ecc0