[FIX] pos_self_order: raise not found error when pos_config_id is None
This error occurs when user has removed `pos_config_id` form the URL.

Steps to produce:
- install pos_self_order module.
- Go to Point of Sale > Navigate to bar point of sale > Click on the three dots.
- Click on Mobile menu. > Click on the view menu
- From that  resulting URL : `/menu/2/products`
- Remove the pos_config_id which is 2 from the above URL.
- Press the Enter > Error will be generated.

Error: 'int() argument must be a string, a bytes-like object or a real number ,
        not NoneType'

Afterward, if the user removes the pos_config_id, they will see the
 `404 Not Found` error.

Sentry-4351886827