Cherry pick of 08d9b45c37127aa5764843550b39647f6ef2a682 failed
stdout:

stderr:
Performing inexact rename detection:   9% (1383552/15211866)   Performing inexact rename detection:  10% (1524069/15211866)   Performing inexact rename detection:  11% (1675395/15211866)   Performing inexact rename detection:  12% (1826721/15211866)   Performing inexact rename detection:  13% (1978047/15211866)   Performing inexact rename detection:  14% (2132976/15211866)   Performing inexact rename detection:  15% (2284302/15211866)   Performing inexact rename detection:  16% (2439231/15211866)   Performing inexact rename detection:  17% (2586954/15211866)   Performing inexact rename detection:  18% (2738280/15211866)   Performing inexact rename detection:  19% (2893209/15211866)   Performing inexact rename detection:  20% (3044535/15211866)   Performing inexact rename detection:  20% (3051741/15211866)   Performing inexact rename detection:  21% (3195861/15211866)   Performing inexact rename detection:  22% (3347187/15211866)   Performing inexact rename detection:  23% (3502116/15211866)   Performing inexact rename detection:  24% (3653442/15211866)   Performing inexact rename detection:  25% (3804768/15211866)   Performing inexact rename detection:  26% (3956094/15211866)   Performing inexact rename detection:  27% (4107420/15211866)   Performing inexact rename detection:  28% (4262349/15211866)   Performing inexact rename detection:  29% (4413675/15211866)   Performing inexact rename detection:  30% (4565001/15211866)   Performing inexact rename detection:  31% (4716327/15211866)   Performing inexact rename detection:  32% (4871256/15211866)   Performing inexact rename detection:  33% (5022582/15211866)   Performing inexact rename detection:  34% (5173908/15211866)   Performing inexact rename detection:  35% (5325234/15211866)   Performing inexact rename detection:  36% (5476560/15211866)   Performing inexact rename detection:  37% (5631489/15211866)   Performing inexact rename detection:  38% (5782815/15211866)   Performing inexact rename detection:  38% (5808036/15211866)   Performing inexact rename detection:  39% (5934141/15211866)   Performing inexact rename detection:  40% (6085467/15211866)   Performing inexact rename detection:  41% (6240396/15211866)   Performing inexact rename detection:  42% (6391722/15211866)   Performing inexact rename detection:  43% (6543048/15211866)   Performing inexact rename detection:  44% (6694374/15211866)   Performing inexact rename detection:  45% (6845700/15211866)   Performing inexact rename detection:  46% (7000629/15211866)   Performing inexact rename detection:  47% (7151955/15211866)   Performing inexact rename detection:  48% (7303281/15211866)   Performing inexact rename detection:  49% (7454607/15211866)   Performing inexact rename detection:  50% (7605933/15211866)   Performing inexact rename detection:  51% (7760862/15211866)   Performing inexact rename detection:  52% (7912188/15211866)   Performing inexact rename detection:  53% (8063514/15211866)   Performing inexact rename detection:  53% (8135574/15211866)   Performing inexact rename detection:  54% (8214840/15211866)   Performing inexact rename detection:  55% (8369769/15211866)   Performing inexact rename detection:  56% (8521095/15211866)   Performing inexact rename detection:  57% (8672421/15211866)   Performing inexact rename detection:  58% (8823747/15211866)   Performing inexact rename detection:  59% (8975073/15211866)   Performing inexact rename detection:  60% (9130002/15211866)   Performing inexact rename detection:  61% (9281328/15211866)   Performing inexact rename detection:  62% (9432654/15211866)   Performing inexact rename detection:  63% (9583980/15211866)   Performing inexact rename detection:  64% (9738909/15211866)   Performing inexact rename detection:  65% (9890235/15211866)   Performing inexact rename detection:  66% (10041561/15211866)   Performing inexact rename detection:  67% (10192887/15211866)   Performing inexact rename detection:  68% (10344213/15211866)   Performing inexact rename detection:  68% (10477524/15211866)   Performing inexact rename detection:  69% (10499142/15211866)   Performing inexact rename detection:  70% (10650468/15211866)   Performing inexact rename detection:  71% (10801794/15211866)   Performing inexact rename detection:  72% (10963929/15211866)   Performing inexact rename detection:  73% (11108049/15211866)   Performing inexact rename detection:  74% (11259375/15211866)   Performing inexact rename detection:  75% (11410701/15211866)   Performing inexact rename detection:  76% (11562027/15211866)   Performing inexact rename detection:  77% (11713353/15211866)   Performing inexact rename detection:  78% (11868282/15211866)   Performing inexact rename detection:  79% (12019608/15211866)   Performing inexact rename detection:  80% (12170934/15211866)   Performing inexact rename detection:  81% (12322260/15211866)   Performing inexact rename detection:  82% (12477189/15211866)   Performing inexact rename detection:  83% (12628515/15211866)   Performing inexact rename detection:  84% (12779841/15211866)   Performing inexact rename detection:  85% (12931167/15211866)   Performing inexact rename detection:  86% (13082493/15211866)   Performing inexact rename detection:  86% (13176171/15211866)   Performing inexact rename detection:  87% (13237422/15211866)   Performing inexact rename detection:  88% (13388748/15211866)   Performing inexact rename detection:  89% (13540074/15211866)   Performing inexact rename detection:  90% (13691400/15211866)   Performing inexact rename detection:  91% (13846329/15211866)   Performing inexact rename detection:  92% (13997655/15211866)   Performing inexact rename detection:  93% (14148981/15211866)   Performing inexact rename detection:  94% (14300307/15211866)   Performing inexact rename detection:  95% (14451633/15211866)   Performing inexact rename detection:  96% (14606562/15211866)   Performing inexact rename detection:  97% (14757888/15211866)   Performing inexact rename detection:  98% (14909214/15211866)   Performing inexact rename detection:  99% (15060540/15211866)   Performing inexact rename detection: 100% (15211866/15211866)   Performing inexact rename detection: 100% (15211866/15211866), done.
error: could not apply 08d9b45c371... [IMP] payment: sca readyness
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/payment/controllers/portal.py'
Recorded preimage for 'addons/payment/models/payment_acquirer.py'