[FIX] payment: inconsistent JSONDecodeError classes
Issue:
Requests library prioritizes simplejson over the stdlib json for JSONDecodeError if installed.
Since we have simplejson installed on all of our hosted platforms, when we try to use the json JSONDecodeError after a requests call the inconsistencys between simplejsons JSONDecodeError and jsons JSONDecodeError cause incompatibility issues.

Error:
'test_parsing_non_json_response_falls_back_to_text_response
self.assertIsInstance(e, ValidationError)
AssertionError: JSONDecodeError('Expecting value: line 1 column 1 (char 0)') is not an instance of <class 'odoo.exceptions.ValidationError'>'

Fix:
Catch all Exceptions instead of just the JSONDecodeError.

request package priority check:
https://github.com/psf/requests/blob/main/src/requests/compat.py

simplejson:
https://github.com/simplejson/simplejson/blob/19b5f94f235d3ac11646b82c02f292845b2aa184/simplejson/errors.py#L28
stblib json
https://github.com/python/cpython/blob/main/Lib/json/decoder.py#L20

opw-6086192

closes odoo/odoo#260413

Signed-off-by: Joseph Maiarana (josm) <josm@odoo.com>