[FIX] sale_loyalty: handle adding order & specific discounts
Versions
--------
- 18.0+

Steps
-----
1. Create a promotion to apply a fixed discount to an order;
2. create a promotion to apply a fixed discount to a specific product;
3. create a order with a taxed product eligible for the 2nd discount;
4. apply the first promotion;
5. apply the second promotion.

Issue
-----
Traceback:
> KeyError: account.tax(1,)

Cause
-----
Commit b97e78c93772 changed the way taxes get handled for discounts on
the order total. They no longer automatically get a tax applied to them.

This causes a problem in the `_discountable_specific` method, which
builds a `dict` using taxes of existing discount lines as keys to
calculate discountable amounts.

Because the existing reward doesn't have a tax, this `dict` only has
an `account.tax()` key, leading to a `KeyError` when trying to get the
discountable amount associated with the product-specific reward's taxes.

Solution
--------
Change the `dict` to a `defaultdict` which returns `0` for non-existing
keys.

opw-4419764

closes odoo/odoo#193635

X-original-commit: 9cc42c6eaed90ecaaa63ada9735864694ea16607
Signed-off-by: Levi Siuzdak <sile@odoo.com>