[FIX] web_editor: upload unsupported image in web editor
This traceback appears when user tries to import 'svg' image by changing its
extension to some other supported subtype.

Steps to reproduce:
1) Install "note" module.
2) Download any "svg" image and change its extension to supported
   mimetypes ( e.g: '"JPEG")
3) Open "Notes" > click on "Create" button.
4) Tpe "/img" command to open editor for uploading image.
5) Click on "UPLOAD AN IMAGE" button > Select that image.

Error: AttributeError: 'bool' object has no attribute 'size'

When the extension of svg image is chaaged to 'supported_subtype' and so it
tries to access the value of 'size' attribute while the value of 'img.image'
attribute is 'False', That's why this error is coming that 'bool' object has no
attribute 'size'.

sentry-4336547180