[FIX] web: handle missing app_id in scoped_app route
Currently, calling "/scoped_app" without providing an app_id raises an error.

Error:
TypeError: WebManifest.scoped_app() missing 1 required positional argument: 'app_id'

Cause:
The scoped_app route defined app_id as a required positional argument.
However, in custom RPC calls, the parameter may be empty, which triggers
the error.

Fix:
This commit handles the case when the app id is not provided and redirects to
the main page instead of raising an error.

sentry-4952598215