[FIX] l10n_ch: adapt ISR report CSS to SCSS
In the CSS of the ISR report, we had things like:

 2 + 3/12in

This was valid in less, but in SCSS there would be no CSS with error:

  Error: 2.4/in isn't a valid CSS value.
          on line 3350 of stdin
  >>         width: 2 + 4/10in;

   ---------------^

These expressions were just used so it is more apparent that the number
is corresponding to the standard template.

We could keep them using:

  #{2 + 3/12}in

But this commit change it to directly use float number since with
margin/fonts/padding/... the expressions anyway didn't match that much
the standard template.