[FIX] website_livechat : fix current_livechat_agent_ids access error
Steps to Reproduce

1. Open a database in version 19.2 with demo data.
2. Install the `website` and `im_livechat` modules.
3. Login with another user who has access to the Website application but
does not have access to the Live Chat application.
4. Navigate to:
   **Website → Reporting → Visitors**
5. An `AccessError` is raised with the traceback below.

The traceback is caused by the following commit introduced in v19.2
[here]: https://github.com/odoo/odoo/pull/240778/changes#diff-580c2ced97a218f926605037b31c4fd2d01253eb1b4f290038f251f9ef31be3b

In this commit, a new computed field `current_livechat_agent_ids` was added on
`website.visitor`.

Compute method
[here]: https://github.com/odoo-dev/odoo/blob/381aede4fde0f871b51df41911c28be3153cd489/addons/website_livechat/models/website_visitor.py#L32

Inside this compute, data from `im_livechat.channel.member.history` is accessed
using `_read_group`.

However, `im_livechat.channel.member.history` is only accessible to users
belonging to the following group:

```python
im_livechat.im_livechat_group_user
```

At the same time, the Website Visitors menu is accessible to normal Website
users through the Website module ACLs:
[here]: https://github.com/odoo/odoo/blob/006a6a1cc6e50bd8b328d0cabb7abbcf610e34bb/addons/website/security/ir.model.access.csv#L30

The issue occurs because the same `website.visitor` views/actions
are reused from multiple menus (Website, Social Marketing, Live Chat),
but the compute method assumes that the current user has Live Chat access.

As a result, when a user without Live Chat permissions opens:
**Website → Reporting → Visitors**

the compute of `current_livechat_agent_ids` triggers an `AccessError`.

Solution:
To fix this issue, a group access check is added inside
`current_livechat_agent_ids` field.

Traceback:

```python
File "/home/odoo/src/odoo/saas-19.2/addons/
website_livechat/models/website_visitor.py", line 32, in
 _compute_current_livechat_agent_ids
self.env["im_livechat.channel.member.history"]._read_group(
File "/home/odoo/src/odoo/saas-19.2/odoo/orm/models.py", line 1933, in
_read_group
    self.browse().check_access('read')
File "/home/odoo/src/odoo/saas-19.2/odoo/orm/models.py", line 3373,
in check_access
    raise result[1]()
odoo.exceptions.AccessError: You are not allowed to access
'Keep the channel member history' (im_livechat.channel.member.history) records.

This operation is allowed for the following groups:
    - Live Chat/User

Contact your administrator to request access if necessary.
```
opw : 6169395
upg : 4286153, 4286493, 4283345
tbg : 2676