[FIX] server: Allow the shell to be used concurrently with the server.
When using a pre-forking (workers > 0) server, if you run the server and try
to run the shell you may get an exception:

    Traceback (most recent call last):
     ...
    socket.error: [Errno 98] Address already in use

This is because we start/stop the server before running the shell.  This is
needed to load the DB (if any is given).

When using the threaded server it does not bind the socket if it's going to be
stopped immediately, so the error is not produced.  We copy that.

Occasionally, we use a shell [*] to perform 'surgical' interventions in live
systems; so we need to be able to do it while running a pre-forking server.

[*] We developed a shell for OpenERP 7 and Odoo 8 in
    https://github.com/merchise/xoeuf.  Now we're backporting this shell, so
    that we have a similar interface.  While we currently don't have any Odoo
    9 or 10 server in production, we're working to migrate our clients to Odoo
    10.