[FIX] base: avoid error if embedded action refers to uninstalled module
The system failed to evaluate the embedded action, which refers to the
Uninstalled module.

Steps to produce:-
- Install Project and Timesheets.
- Go to Project and open any project.
- Click on the embedded action icon and select Timesheets.
- Save the view from the embedded action's icon.
- Now, Uninstall Timesheets.
- Now, go to that Project and try to open it.

Error:-
KeyError: 'allow_timesheets'
ValueError: Invalid field in filter of project.project:
 [('allow_timesheets', '=', True)]

Solution:-
- Added a safe check using hasattr to verify if the python_method defined on the
  embedded action actually exists on the specified model.
- Ensured that if the method is missing or invalid, the embedded action is
  marked as not visible instead of causing a crash.

sentry-6738596751

X-original-commit: 037282219fafd63a8b5e6dcd153fca0b5b80ecc2