[FIX] account: prevent singleton error during journal entry reversal
Currently, an error was occurring when a user tried to reverse a journal entry
by following these steps:
- Enabled payroll entries in Payroll > Configuration > Settings.
- Created a new employee and its corresponding contract in payroll.
- Computed the payslip, generated draft journal entries, and created a payment.
- In accounting check in payments by payslip, currency id will not get fetched.
- Make a reverse entry.

Traceback:
ValueError: Expected singleton: res.currency().

This is because at [1] does not have currency_id in self so it does not link any
currency with account payment register

This commit will fix the above issue by providing default company currency when
currency is not found in self

[1] - https://github.com/odoo/odoo/blob/0583db332efdc884975da1a074c91981d2865c9d/addons/account/wizard/account_payment_register.py#L972

sentry-6207053954