[FIX] account: Fix stock_account post init hook
Repro steps:
1. Install a localization module with defined account_stock_expense_id or account_stock_variation_id
2. Add a branch to that localization company
3. Attempt to install stock_account

Problem:
A traceback shows preventing the user from installing stock_account
ERROR: null value in column "account_type" of relation "account_account" violates not-null constraint

Root cause:
In stock_account post init hook, stock related fields data are attempted to be added from localizations.
The problem is that branches don't have accounts by default, they own their parent company accounts.

Solution:
This commit fixes this issue by using AccountChartTemplate.ref in _load_data.
This ref would find the record (i.e., account.account record) instead of attempting to create a new one
for child companies.

opw-5391764

X-original-commit: 27c6436862ebdb7d0c43fc4c95b97c9d4bcfd08f