[FIX] pos_loyalty: prevent error when user pays for their order through website
Currently, an error occurs when a user pays for their order through the website.

Steps to Reproduce:

 - Install the website_sale and pos_loyalty modules.
 - Go to Products and create a product.
 - Go to Gift Cards & eWallets and create a program with the type
   set to Gift Card.
 - Generate at least one gift card.
 - In Gift Card Products, add the recently created product.
 - Ensure the SMTP server is configured.
 - Make sure that in the "Gift Card: Gift Card Information" email template,
   the Email From field is set.
 - Now, go to the shop, add the product to the cart, and proceed to
   Checkout > Pay.
 -  And the error appears in the logs.

odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: mail.mail(11,), User: 1)

After this [recent commit], when user pays for their order, the Payment:
Post-process transactions step confirms the order and attempts to send
reward coupon email [1] if any coupon is applied to the product.
The system sends the email with force_send=True [2] and retrieves the sent
mail_ids [3].  because force_send=True, the email is sent
immediately [4] instead of being queued.
Once the email is successfully sent [5], _postprocess_sent_message [6] is
triggered. Since there is no failure in sending the email, the corresponding
mail record is deleted [7], because the email template has auto_delete=True.
Later, when the system tries to access the deleted mail.mail record using
the previously returned mail_ids, it raises error [8].

This commit ensures that only existing mail records are used when processing
mail_ids, preventing access to deleted records.

[recent commit]: https://github.com/odoo/odoo/commit/80d80a007131827ddd231bed320708068d0086b6

[1]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/sale_loyalty/models/sale_order.py#L188

[2]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/sale_loyalty/models/sale_order.py#L245

[3]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/pos_loyalty/models/loyalty_card.py#L73

[4]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/mail/models/mail_template.py#L815-L816

[5]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/mail/models/mail_mail.py#L871-L872

[6]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/mail/models/mail_mail.py#L919

[7]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/mail/models/mail_mail.py#L288-L289

[8]: https://github.com/odoo/odoo/blob/0f395269e9815977263f27fa85855096166e15a2/addons/pos_loyalty/models/loyalty_card.py#L73-L76

sentry-7367887795

closes odoo/odoo#257298

Signed-off-by: Stéphane Vanmeerhaeghe (stva) <stva@odoo.com>