change psycopg2 version
version of psycopg2==2.8.6 with python 3.10.2 is causing an ImportError. New one psycopg2==2.9.5 working just fine

Traceback (most recent call last):
  File "C:\Users\wda61\odoo\odoo-bin", line 5, in <module>
    import odoo
  File "C:\Users\wda61\odoo\odoo\__init__.py", line 113, in <module>
    from . import modules
  File "C:\Users\wda61\odoo\odoo\modules\__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry, neutralize
  File "C:\Users\wda61\odoo\odoo\modules\db.py", line 4, in <module>
    from psycopg2.extras import Json
  File "c:\Users\wda61\odoo\venv\lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

Update requirements.txt

Any changes would be nice to have. It is always bad to faff around with installation problems

Co-Authored-By: xdo <35262360+Xavier-Do@users.noreply.github.com>