[FIX] mass_mailing:  handle sms testing with empty record
When testing empty records in sms marketing it generates traceback.

Step to Reproduce:
   1. Install the SMS Marketing module.
   2. Install Studio
   3. Go to SMS Marketing. Create new
   4. Change the property of the fields, Title, Mailing Lists, and SMS Body
       to make it unrequited.
   5. Again create a new record.
   6. Click on the Test button
   7. Then click on the DISCARD CHANGES Button.

Error: Expected singleton: mailing.mailing()

Therefore, to prevent an empty record set add a condition.

sentry-4309438646