[FIX] l10n_it_edi: fix storing errors sent from Italian e-invoicing
Before this commit:
Steps
1) When clients try to send their invoice to Italian e-invoicing
2) If it's got rejected, they replied with an error message

=> A Traceback Error is raised with the message:
`errors = '\n- '.join(error.get('errors', ''))
^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'`,

This occurs because the `_call_web_service_after_invoice_pdf_render()` method in l10n_it_edi is setting `moves_data[move]['error']` to a string while `_generate_and_send_invoices()` that calls `_hook_if_errors()` expects it to be a dict.

After this commit:
If the Italian e-invoicing rejects the request with `error_message` in the response, Odoo stores and displays it to the client correctly.

opw-5271525

closes odoo/odoo#237689

Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>