[FIX] account,purchase: prevent error when creating accrual entries
Steps to reproduce:
- Install the accountant and purchase modules.
- Create and confirm a Purchase Order (with 1 quantity).
- Create a vendor bill using auto-complete from the PO,
  set the quantity to 1, and confirm it.
- Navigate to Accounting > Review > Billed Not Received.
- Change the date from the top left.
- Select a record and click `Create Accrual Entries`.

Error:
TypeError: '<=' not supported between instances of 'datetime.date' and 'str'

Root cause:
At [1], the `accrual_entry_date` is set in the context as a string.
Later, at [2], this value is retrieved from the context and used
directly in a comparison with `ivl.date`, which is a `datetime.date`.

Fix:
This commit converts `accrual_entry_date` to a `datetime.date` object at [2],
allowing users to create accrual entries without errors.

[1]:
https://github.com/odoo/enterprise/blob/3ab460a935c6caf013202ec6be1c3708178c8d7d/account_reports/static/src/views/accrual_list_controller.js#L61-L76

[2]:
https://github.com/odoo/odoo/blob/f810243b7df73d3e5334dad07a1115226781b5fe/addons/account/wizard/accrued_orders.py#L166-L188

opw-6110907

closes odoo/odoo#259047

Signed-off-by: Yolann Sabaux (yosa) <yosa@odoo.com>