[FIX] tests: fix traceback log retry
The auto-retry is supposed to catch error logs as well as tracebacks.
In some cases a traceback is logged as a message, and not as a logger
arg, bypassing the replace already in place.

This pr simply replaces the traceback string in the message as well.

Also catches OSError in websocket handling, as it can also happen
when the browser is closed causing

closes odoo/odoo#238133

Oserror: [Errno 9] Bad file descriptor
Signed-off-by: Xavier Dollé (xdo) <xdo@odoo.com>