[FIX] point_of_sale: test tries to install pos_restaurant
`TestPosOrderReceipt.test_split_per_product_preserves_combo_children`:

This test sets `module_pos_restaurant` to `True`, which causes the
`pos_restaurant` module to start installing, leading to this error:

```
RuntimeError: Module operations inside tests are not transactional and
thus forbidden.

If you really need to perform module operations to test a specific
behavior, it is best to write it as a standalone script, and ask the
runbot/metastorm team for help.
```

The test does not in fact rely on any `pos_restaurant` behaviour, so the
line can simply be removed.

runbot-946164

closes odoo/odoo#285926

Signed-off-by: Louis Travaux (lotr) <lotr@odoo.com>