[FIX] uom: Cap the value of uom.sequence to prevent out of range
The default value of uom.sequence is calculated as uom.relative_factor * 100.
If the value of relative_factor is big enough, it can be bigger than what the
int column can handle and trigger
```
ERROR: integer out of range
```
So we just cap it at an arbitrary value.

To reproduce:
- Create an uom with relative factor bigger than 2147483647.