[FIX] l10n_it_edi_website_sale: fix crash when submitting address
Fix wrong condition introduced by odoo/odoo@453cfab75850 to avoid
crashing on /shop/address/submit:

```
Traceback (most recent call last):
  ...
  File "/data/build/odoo/addons/website_sale/controllers/main.py", line 1189, in shop_address_submit
    invalid_fields, missing_fields, error_messages = self._validate_address_values(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/build/odoo/addons/l10n_it_edi_website_sale/controllers/main.py", line 28, in _validate_address_values
    if pa_index and len(pa_index) < 6 or len(pa_index) > 7:
                                         ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

closes odoo/odoo#175883

Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>