[FIX] html_editor, website_sale: load remote images
Versions
--------
- saas-19.3+

Steps
-----
1. Go to the product page in editor mode.
2. Press the "Add More" button next to "Extra Media"
3. Add an image by URL.
4. Select the new image and press "Add".

Issue
-----
Traceback
```python
Traceback (most recent call last):
  File "/data/build/odoo/odoo/http/router.py", line 432, in serve_db
    return retrying(serve_func, env=request.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ...
  File "/data/build/odoo/addons/website_sale/controllers/main.py", line 757, in add_product_media
    product_product.write({"product_variant_image_ids": media_create_data})
  ...
  File "/data/build/odoo/odoo/orm/fields_binary.py", line 84, in convert_to_cache
    raise TypeError(f'{self}: use BinaryValue instead of {value.__class__.__name__}')
TypeError: product.image.image_1920: use BinaryValue instead of bytes
```

Cause
-----
When saving the image, the remote URL is fetched and the raw `bytes` are
stored in the `product.image.image_1920` field. However, since commit
41fe2ebdb9cc37341362d7af829c087a5f72f9f1, raw `bytes` cannot be directly
assigned to `Binary` fields.

Solution
--------
Use the new `BinaryBytes` wrapper.

closes odoo/odoo#262870

Signed-off-by: Lionel Piraux (lipi) <lipi@odoo.com>