[FIX] tools/mail: force non-strict getaddresses()
A patch was backported in python 3.12.3-1ubuntu0.2 on ubuntu noble
breaking the address parsing. Odoo relies on the non strict behavior
but the strict was introduced as the default one.

This commit conditionally checks if the patch is present and reverts it
to the previous behavior.

test_email_split unittest was used for testing in both version (
3.12.3-1ubuntu0.1 and 3.12.3-1ubuntu0.2)3.10.3-ubuntu0.1

references:
https://launchpad.net/ubuntu/+source/python3.12/3.12.3-1ubuntu0.2
Backported patch:
python/cpython/4a153a1d3b18803a684cd1bcc2cdf3ede3dbae19

closes odoo/odoo#180987

X-original-commit: b73c994fd70719418f9fb6e47cdaf402ad32a7c5
Signed-off-by: Olivier Dony (odo) <odo@odoo.com>
Signed-off-by: Xavier Dollé (xdo) <xdo@odoo.com>

[FIX] sale: display expiration date in portal only for quotations

Problem: The expiration date were showing on confirmed sale orders in
the customer portal.

Purpose: The expiration date should only show if the order is still a
quotation in the customer portal.

Steps to Reproduce on Runbot:
1. Install Sale
2. Create a quotation with an expiration date and confirm
3. View the sale order in the customer portal view and
observe that the expiration date is still displayed

opw-3926689

closes odoo/odoo#181098

X-original-commit: c3db0085e4c9a76254e94d712dc991fcdc063528
Signed-off-by: Mylyna Hy (myhy) <myhy@odoo.com>

[FIX] l10n_sa_edi: fix tax retention with down payment

Steps:

- Create a negative retention tax T
- Create, confirm and reveive a SO
- Create and confirm a downpayment
- Create a regular draft invoice for the rest, and
  add tax T to the product line, confirm and process edi
-> Traceback: list index out of range

This is because we override `_get_tax_category_list` to filter
the retention taxes, therefore we try to acces an empty list

opw-4139894

closes odoo/odoo#178769

Signed-off-by: Laurent Smet (las) <las@odoo.com>

[FIX] website_{customer,crm_partner_assign}: partner image elongated

Current behaviour:
When going to /customers or /partners and selecting
a partner, in the References section, if the text
is too long, the image will be taking the text height

Expected behaviour:
The image fits the width but not the height

Steps to reproduce:
1. Go to Website
2. Go to /customers
3. Select a partner that has references
4. Open the editor (top left)
5. Add long text to one of the reference
6. The image will match the text height

Cause of the issue:
Caused by: https://github.com/odoo/odoo/commit/1efdb96227dab8f1b3bcb8e8854dbad5dd874e69

Fix:
Removed h-100 and added w-100

opw-3970462

closes odoo/odoo#173363

Signed-off-by: Antoine Demany (ande) <ande@odoo.com>

[FIX] account_payment_term: prevent error when days on next month is empty

This error occurs in 'Payment Terms' when the 'Days end of month' field is
selected in the payment terms line, but the 'days' field is left empty.

Steps to reproduce:
- Install 'account' module
- Go to 'Payment Terms'
- Create a new one and select 'Days end of month on the' payment terms line and
  empty the days

Traceback: AttributeError
'bool' object has no attribute 'isnumeric'

At [1] 'days_next_month' in the record is getting as 'false'

This commit will fix the above error by checking that 'days_next_month' is
present in the record otherwise it will raise an error.

[1]- https://github.com/odoo/odoo/blob/a800b5dc2a7444c1f4944dd99509d36096bc797f/addons/account_payment_term/models/account_payment_term.py#L26

Sentry-5583615279

closes odoo/odoo#172260

Signed-off-by: de Wouters de Bouchout Jean-Benoît (jbw) <jbw@odoo.com>

[FIX] website_forum: fix flagged post validation

Purpose
=======
Fix the validation button of a flagged post that wasn't doing
anything when clicking on it.

Specification
=============
Adding a missing css class named 'o_wforum_flag_alert' that was forgotten
during the front-end redesign odoo/odoo@21531bd9b9ac24bec57665432d9c18c807c31b44.
The alert banner is now correctly hidden at validation.

Task-4163955

closes odoo/odoo#179263

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>

[I18N] Update translation terms from Transifex

[IMP] website: support Google Consent Mode V2

Commit [958b41c4] added an event triggered when clicking on "Accept all"
on a cookie banner (in 17.4) and [cee8a5e6] added support for Google
Consent Mode V2 in master (18.0).
This commit backports the relevant parts of both so that stable versions
are compliant with Google's policy and that the analytics are properly
working. The event will also make it easier for customers to add custom
code working with Odoo's standard cookie banner.

Note that due to [958b41c4], the behavior of Google Consent Mode is
slightly different in stable versions than in 17.4 and above:
- In stable, Google is called on page load with consents set on denied.
This grants that only cookieless pings, non-identifying information is
sent to Google (see [Google's documentation]). It is updated once the
cookies are accepted.
- In 17.4 and above, Google is not called until the cookies are accepted
and only then receives the default + updated consents.

[958b41c4]: https://github.com/odoo/odoo/commit/958b41c4acec7e1700ca4d6e0b25ee0ad2aac9f1
[cee8a5e6]: https://github.com/odoo/odoo/commit/cee8a5e6aafd9c05e5b2c027e52aee6b174a4ad5
[Google's documentation]: https://support.google.com/google-ads/answer/10000067

Related to task-3880544

closes odoo/odoo#180960

X-original-commit: 876a97a1fe649492b6bef071773c00aee53facc2
Signed-off-by: Quentin Smetz (qsm) <qsm@odoo.com>

[FIX] account: clear attachment ids to proccess on import error

Versions
--------
- 16.0+

Steps
-----
1. Try to import a malformed OFX file into a bank journal;
2. close traceback;
3. try to import a valid OFX or CSV file.

Issue
-----
Same traceback as first upload.

Cause
-----
There's no error handling on the RPC call. If the file is successfully
imported, the `attachmentIdsToProcess` gets clear, but if there's an
error, the bad file remains in the queue until leaving the view.

Solution
--------
Put the RPC call in a `try` block, and clear the
`attachmentIdsToProcess` in a `finally` block to ensure this happens
regardless of outcome.

opw-4113740

closes odoo/odoo#180938

X-original-commit: 81d8257e016684c303baa00444c658e336c9f075
Signed-off-by: Ruben Gomes (rugo) <rugo@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>

[FIX] base: fix traceback when user removes all devices in preferences

Currently, a traceback occurs when the user tries to `log out from all devices`.

To reproduce this issue:

1) Open the `Preferences` from the profile
2) Click `Log out from all devices` from the Account Security page
3) Give the current password and click `Log out from all devices`

Error:- "AttributeError: 'bool' object has no attribute 'strip'"

When the user clicks on the `Log out from all devices`, the `revoke_all_devices`
method triggers in which the `_check_identity` method is triggered.

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L2000-L2002

But here in the `_check_identity()` current password is set to False.
This leads to a traceback from the `_change_password` method.

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L1982-L1988

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L977-L978

Note:-
I don't know the scope of setting the password as False,
So instead of removing that line, I passed the current password as a variable.

sentry-5867375557

closes odoo/odoo#180612

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>

[FIX] pos_loyalty: loyalty reward product quantity and loyalty points

Before this commit:

- An issue existed with the quantity of reward products where there were more
  reward products applied than configured in the backend.
- Rewards were being applied even when loyalty points were insufficient for the
  redemption of loyalty rewards.
- In a loyalty program configuration with a reward point mode per order, loyalty
  points were consistently decreasing.
- We were not showing a balance of loyalty points for the customers.

After this commit:

- The quantity of the applied reward product will now match the configuration
  set in the backend.
- Reward products will not be applied if the customer's loyalty points are
  insufficient for the specific reward product.
- Loyalty points will be computed correctly in the case of the reward point mode
  per order.
- We will show a balance of loyalty points for the customers.

task-4126886

closes odoo/odoo#180850

X-original-commit: 606f6ee435ae2d79b3cb522f46ce52e9eb41e12a
Signed-off-by: David Monnom (moda) <moda@odoo.com>
Signed-off-by: Anantkumar Parmar (paan) <paan@odoo.com>

[FIX] tools: fix zeep imports for version 4.2.0

Updated imports for `zeep.wsse` components to explicitly import modules.

This change is required because zeep 4.2.0 introduced an `__all__`
declaration in `zeep.wsse`:
````
__all__ = [
    "Compose",
    "BinarySignature",
    "MemorySignature",
    "Signature",
    "UsernameToken",
]
```
The __all__ prevents using wildcard imports for all wsse submodules as
we did before.

Steps to Reproduce:
- Install the l10n_nl_reports_sbr module.
- Navigate to Accounting > Report > Tax Report.
- Select XBRL from the dropdown menu on the PDF button in the top left corner.
- Attempt to send the document.
- An error will occur:
```
Copy code
  File "/home/odoo/src/enterprise/saas-17.4/l10n_nl_reports_sbr/wizard/l10n_nl_reports_sbr_tax_report_wizard.py", line 168, in __init__
    wsse.signature.MemorySignature.__init__(
    ^^^^^^^^^^^^^^
AttributeError: module 'odoo.tools.zeep.wsse' has no attribute 'signature'
````

Fix: perform every import fully explicitely.

opw-4181876

closes odoo/odoo#180926

X-original-commit: 283fc1b8bf275fe64cbe8e190b8458b09133ec58
Signed-off-by: Xavier Morel (xmo) <xmo@odoo.com>
Signed-off-by: Louis Gobert (loug) <loug@odoo.com>

[FIX] hr_holidays: prevent in-use leave type allocation requirement edit

Steps to reproduce:
- Time off > Configuration > Time off types > New
- Set 'Requires Allocation' to 'No Limit'
- Takes leaves of this type
- Set 'Requires Allocation' to 'Yes'
- Approvals > Allocations > New > Select your time off type
- Edit validity period to start after the leaves you took
- Confirm > Click on the newly created allocation
- Displays -X remaining out of Y

The allocations try to cover leaves taken before the requirement was
changed, when we'd expect leaves taken under No Limit mode not to
require any. This is problematic because it can happen with past leaves
as well, which we cannot get rid of on production databases.

Since Odoo does not track which allocation requirement mode leave are
taken under nor the date and content of edits to that parameter, we
cannot tell apart leaves of the same type when distributing allocated
days. Tracking either would certainly require edits to the model which
rules out stable versions, so instead the edits to allocation
requirement should be restricted in favor of creating new time off types
when we want to switch that parameter.

opw-3919886

closes odoo/odoo#180773

X-original-commit: 33da34b842f2fe700efaf55915d4cb9828e139d7
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Yoann Baron (bary) <bary@odoo.com>

[FIX] calendar: Avoid sending more emails than necessary at events.

We want to make sure that in all mails sent from the calendar event, the recipients are only the ones
we want and avoid sending them to 'indirect' followers.

Examples use case:
- Subtype Notes with Default checked.
- Several Attendees set (including several users).
- Each invitation email must be sent only to the corresponding attendee, no one else.
- Each event reminder email must reach only the corresponding attendee, no one else.

TT50302

closes odoo/odoo#174494

closes odoo/odoo#180164

Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>

[FIX] l10n_vn_edi_viettel: Correct sinvoice xml page on move

* PROPBLEM: In form view we try to use m2o.field_name which is
'l10n_vn_edi_replacement_origin_id.l10n_vn_edi_invoice_number', odoo
doesn't
support that so it will not work at least in form view
* SOLUTION: this commit make the invisible condition more simpler and
create a non-store field to fix the issue

closes odoo/odoo#180818

Signed-off-by: Nicolas Viseur (vin) <vin@odoo.com>

[FIX] l10n_in_withholding: load taxes for company only in post_init_hook

Steps to Produce:
- Install `l10n_in`
- create a branch for the Indian company
- install `l10n_in_withholding` it will raise an error.

Before this commit:
- If there is an Indian company with a branch, then while installing
`l10n_in_withholding` raises an RPC error because the branch is also a record of
 res.company and it cannot find the TDS group for the branch since the branch
uses the COA of the parent company.

After this commit:
- Load taxes for company only.

Task-4143223

closes odoo/odoo#178305

Signed-off-by: John Laterre (jol) <jol@odoo.com>

[FIX] web: prevent out of bound error in ListRenderer

Steps

- install `stock`
- create a delivery for 2 products > *Mark as Todo* > *Validate*
- make a return, a `ListRenderer` for the return moves opens
- click the last field (quantity) of the last record in the list
- press `tab`
   * => Traceback: `Uncaught Promise > futureRecord is undefined`

Cause
---
This specific view is `editable='top' create='0'`, but the return moves
have been generated on the fly, so their `isNew` property is true.

But, we check `isNew` to decide if a record has just been created in the list,
and what element is the last.

This leads to a false negative where we don't detect that we're on the last
record.

Note
---
`.isNew` is still needed because we can run into problems with the
pager or if we start with a grouped list view.

opw-4108845

closes odoo/odoo#180725

X-original-commit: 88650bad0ee2e6627e92bf03a2de4b6304419776
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>

[FIX] analytic: prevents override timesheet

Steps to reproduce:
- install only `timesheet_grid`
- run `test_analytic_account_branches`

Issue:
An access error is raised

Cause:
There are no default access rule defined in `analytic`. So if there is only `hr_timesheet` installed the following rule will be the only one
https://github.com/odoo/odoo/blob/8029b467dacaf9e34b21db52b148a2963efb29e4/addons/hr_timesheet/security/hr_timesheet_security.xml#L33-L44

runbot-97783

closes odoo/odoo#180001

Signed-off-by: William André (wan) <wan@odoo.com>

[FIX] web: x2many came back to initial state when discard

- Have a x2many on your view;
- Edit another field that through a onChange modify the x2many;
- Discard the changes.

Before this commit, the x2many didn't come back to its initial state.

Now, the x2many will came back to its initial state.

Note that this commit is a fix up of [1] which already address part of
this issue.

[1] https://github.com/odoo/odoo/commit/e450d03a5f4fc80198837cccf10fa349ecc205a9

closes odoo/odoo#180829

Signed-off-by: Aaron Bohy (aab) <aab@odoo.com>

[FIX] delivery: fix failing test

In `test_base_on_rule_currency_is_converted` we create a rate for a
testing currency and check that is applied, but we don't specify
its name/date, so under certain conditions it will considered as
applying only tomorrow and the test will fail.

runbot-97969

closes odoo/odoo#180878

X-original-commit: b43d1c26db0b8c7acbe749b234b9718d75e12dd3
Signed-off-by: Antoine Vandevenne (anv) <anv@odoo.com>
Signed-off-by: Nathaniel Jacques (naja) <naja@odoo.com>

[FIX] account: normalize tax_tag_invert on early payment discount

Steps to reproduce the issue:

1. Create a Customer Invoice with two product lines
2. Give a negative price to one of those lines, the total must remain positive
3. Add distinct analytic accounts to each line's analytic_distribution
4. Add a payment term with applicable early discount
5. Confirm and Register Payment
6. Go to the Journal Entry related to the Invoice
7. Check the Invert Tags (developer mode), one of them is set to True, which should not be the case

Explanation:

In the current situation, `_compute_is_refund` and `_compute_tax_tag_invert` will assign a value to `tax_tag_invert` depending on the `account.move.line.balance`. Because of the distinct analytic accounts, the negative line is separated from the others and because of the logic behind the computes, `tax_tag_invert` is set to the opposite value.

Fix reasoning:

While `account.payment` are restricted to `account.move` with the same direction, `account.bank.statement.line` are not. In the current case, the affected lines all have `tax_ids` values. Thanks to this, we can use `account.tax.type_tax_use` independently of the line's balance to differentiate in and out transactions and assign `tax_tag_invert` consistently.
We must also consider the case where `account.bank.statement.line` is reconciled with newly created `account.move.line`. To target the Early Payment Discount lines, we will separate them from the other values using `display_type`.

opw-3989174

closes odoo/odoo#180797

X-original-commit: 3293fcbc0b4ca59fba3f0ed220d4637cda72ccb6
Related: odoo/enterprise#70328
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Stroobant Paul (stpa) <stpa@odoo.com>

[FIX] delivery: don't return error when rate can't be fetched

Before this commit
==================
Some contracts in SendCloud do not have rates. This caused an annoying popup
when adding it to the Sales Order.

After this commit
=================
This commit ensures red banner is displayed with the same message instead of
the annoying popup when adding it to the Sales Order.

closes odoo/odoo#173791

Taskid: 4012182
Related: odoo/enterprise#66976
Signed-off-by: William Henrotin (whe) <whe@odoo.com>