[FIX] product,stock: show the quantity field in onchange
The `Quantity On Hand` field doesn't always show up directly

To reproduce the issue:
1. Create a product template without any tracking
2. Switch the tracking to 'Quantity'

Error: if we don't save the form, the `Quantity On Hand` field doesn't show
up. That's terrible and reminds us the so old click-to-edit Odoo 14.

The field `qty_available` is wrapped into a `div` container that is
invisible in some conditions, and one of them is based on `is_storable`:
https://github.com/odoo/odoo/blob/913efdfe9af3d1dd75a0687a72a7ec5ecb7297fe/addons/stock/views/product_views.xml#L194-L195

The field is a computed one and will be set to `False` under some
conditions in its compute method. The compute will never mark it as `True`,
which is a first issue. Second, in the above use case, it only changes to
`True` when saving thanks to the inverse method of the `tracking field`:
https://github.com/odoo/odoo/blob/1fdc147b75b1746f85d810f1288bd1d632166083/addons/stock/models/product.py#L1003-L1005
This therefore explains why the `Quantity On Hand` doesn't show up during
step 2: it's an onchange mechanism, the inverse methods are not triggered.

A similar issue will also happen on a variant form, but because of another
reason. This time we need to look at the field `qty_available` itself, which
depends on `show_qty_update_button`:
https://github.com/odoo/odoo/blob/913efdfe9af3d1dd75a0687a72a7ec5ecb7297fe/addons/stock/views/product_views.xml#L200
The field is a computed one and the method is missing one dependency.

No ticket
Discovered during PR review of opw-6316788

co-authored by: William Henrotin (whe) <whe@odoo.com>
co-authored by: Adrien Widart (awt) <awt@odoo.com>