[FIX] l10n_it_edi: prevent crash when importing XML without invoice body
Currently, an error occurs when a user uploads an Italian EDI XML file
without an invoice body.

Steps to Reproduce:
- Install l10n_it_edi with demo data.
- Switch to an Italian company.
- Go to Invoices and upload [this XML file].
- An error is logged in the terminal.

AttributeError: 'NoneType' object has no attribute 'xpath'

After [this commit], the system retrieves the first invoice from the XML [1].
However, if the XML file does not contain a FatturaElettronicaBody
(e.g., it only contains metadata), the resulting tree for the invoice is None.
When it attempts to extract the VAT [2] using an XPath [3] expression on
this None tree, an error is raised.

This commit ensures that if the tree is None (i.e., there is no invoice body),
it returns early and posts a message in the body.

[this commit]: https://github.com/odoo/odoo/commit/e7c93e5a6ff1754a9c798ab6f775ea411cf98a8e

[1]: https://github.com/odoo/odoo/blob/42b8852df9b323984364c41a13cf27d19fbe04a7/addons/l10n_it_edi/models/account_move.py#L1259

[2]: https://github.com/odoo/odoo/blob/42b8852df9b323984364c41a13cf27d19fbe04a7/addons/l10n_it_edi/models/account_move.py#L1282

[3]: https://github.com/odoo/odoo/blob/42b8852df9b323984364c41a13cf27d19fbe04a7/addons/l10n_it_edi/models/account_move.py#L34

[this XML file]: https://drive.google.com/file/d/18OoBKDvrKtCCiUg4sOb3MfHP1miApItn/view?usp=drive_link

sentry-7429395262