[FIX] base: fix incorrect call of method of dictionary
This PR fixes an issue introduced in commit https://github.com/odoo/odoo/commit/c08777da27a39b463762895f291ce7056ef32ffe

When this line is executed, the following error is shown:

closes odoo/odoo#109652

Attributeerror: 'dict' object has no attribute 'vals'
X-original-commit: f3b6225e268711e3d9e6f6fda24f398e2f506259
Signed-off-by: Xavier Morel (xmo) <xmo@odoo.com>