[FIX] mrp_repair: fix error when using kit in repair order
When user tries to set the kit as product parts in repair order,
A traceback will appear.

Steps to reproduce the error:
- Install "mrp_repair" module with demo data
- Create a new repair order > In Parts, Add a line > Product: Table Kit > Save

Traceback:
"AttributeError: 'stock.move' object has no attribute 'name'"

https://github.com/odoo/odoo/blob/83a8508b958ed88bbdbf80612039ec33817bc02c/addons/mrp_repair/models/repair.py#L84
The "name" field of "stock.move" was removed in the commit [1],
but it is still being referenced here.
So, It will lead to the above traceback.

1: https://github.com/odoo/odoo/pull/211488/commits/f3fc7a5cfd6e77cbbcfff891383abeac930d41ac

sentry-6870866512