[FIX] l10n_br: support Pix codes with a None amount
QR code support was added to the POS [1]. A fallback QR code with a
None amount is downloaded when the POS loads. This is used when the
POS is offline.

This commit ensures we don't float_repr() None which results in:

TypeError: must be real number, not NoneType

[1] https://github.com/odoo/odoo/pull/148803