[FIX] website_event_track: prevent error if event track duration exceeds 2 days.
Currently, the error occurs if the event track duration is more than  two days
or 48:00 hour

Steps to reproduce

- Install a 'website_event_track' module.
- Open 'Events' and create new events.
- Add an event name and make a boolean true of 'Showcase Tracks',
'Website Submenu', 'Allow Track Proposals', 'Extra Register Button'.
- Click on the 'Tracks' button, Create an Event Tracks, Add a Title, Track Date,
 and location, and Give a value to a duration field of more than 48:00
- Make this Event Tracks state to 'Announced'.
- Click on the 'Go to Website' Button, go into 'Agenda'

Error:  AttributeError: 'datetime.date' object has no attribute 'datetime'

When the event track duration is more than 48:00 hours, The error occuring
because system trying to access the datetime on a datetime.date object
,which is not possible[1].

Line 1:https://github.com/odoo/odoo/blob/422625615b2f6708667fa44d2a9e83ad3e66e5af/addons/website_event_track/controllers/event_track.py#L294

This commit solves the issue by preventing the conversion of 'next_day' into a
date format, as 'next_day' is already in datetime format.

sentry-4516712041