[FIX] base,tools: prevent error on attribute nodes with no name
Currently, an error occurs when user tries to save a view with an attribute node
without name.

Steps to replicate:
- Initialize a DB and open Views.
- Create a new view and fill in random values for name and give a View Type.
- In the Architecture give value as `<attribute></attribute>`.
- Save and you will get the error.
(Same error can also be produced with Web Studio report editor.)

Error:
`AttributeError: 'NoneType' object has no attribute 'endswith'`

Cause:
- The error occurred because we received key as `None` at [1], as it was called
  from an attribute node with no name [2].
- In `saas-18.2`, we only checked if `node.get('name') not in TRANSLATED_ATTRS`.
  Since `node.get('name')` was `None` and `None` was not included in the
 `TRANSLATED_ATTRS` list, no error occurred.

Solution:
- Added a conditional check, so that attributes with no names return from
  function call.

[1]: https://github.com/odoo/odoo/blob/f254da2253e7ce9426e51112b513fa9e6a474ce4/odoo/tools/translate.py#L83

[2]: https://github.com/odoo/odoo/blob/f254da2253e7ce9426e51112b513fa9e6a474ce4/odoo/tools/translate.py#L190

[3]: https://github.com/odoo/odoo/blob/0b700ec3c08ecd9c6f1597f9d10f6c1eee06bcee/odoo/tools/translate.py#L255

sentry-6877030439

closes odoo/odoo#229321

X-original-commit: 5fced331c71a0da27c0c4c4fc51b53631ff4849a
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Bhavya Ashesh Nanavati (bhna) <bhna@odoo.com>