[FIX] hr_attendance: prevent access error on flexible employee attendance
Steps to reproduce:
-------------------------
1. Install hr_attendance
2. Create a user with Attendance Administrator access
3. Create an employee for this user and remove their resource calendar
4. Log in as the newly created user and try to create an attendance
for this employee

Issue:
--------
An AccessError is raised when trying to create/edit an attendance record:
```python
odoo.exceptions.AccessError: You do not have enough rights to access the field "is_fully_flexible" on Employee (hr.employee). Please contact your system administrator.

Operation: read
User: 88
Groups: allowed for groups 'Employees / Officer: Manage all employees
```
Cause:
----------
After the working schedule refactoring, flexible calendars were removed,
and the `is_fully_flexible` field is now used to determine whether an
employee is fully flexible.

https://github.com/odoo/odoo/blob/42bd769c00ce12793bdf595e0e8ed6851fcfd8d2/addons/hr/models/hr_version.py#L166
However, this field is restricted to `hr.group_hr_user`. As a result,
an Attendance Administrator cannot access this field, even though they
have the required access rights to create/edit attendance records.
https://github.com/odoo/odoo/blob/fb1754e0b2d86089cef7ff3bb6d4f4a1b6f14eea/addons/hr_attendance/models/hr_employee.py#L326-L330

Solution:
------------
Use `sudo()` when checking `is_fully_flexible` to allow Attendance
Administrators to create/edit attendance records of fully flexible employees.

opw-6537671

X-original-commit: bde371dec3ab5c73c57f46ba060fbbb7454ba77f