Cherry pick of 79504dcdc393f955781c220f5300a193da2c6ba9 failed
stdout:

stderr:
error: could not apply 79504dcdc39... [FIX] account: Fix bug if internal payment has 0 amount.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'