[FIX] product: prevent mutually recursive pricelist rules
Steps
-----
1. Create a selectable pricelist A;
2. create a selectable pricelist B;
3. add a rule to pricelist B which uses pricelist A;
4. add a rule to pricelist A which uses pricelist B;
5. go to /shop & select one of the pricelists.

Issue
-----
> 500: Internal Server Error
> Error while render the template
> RecursionError: maximum recursion depth exceeded in comparison

Cause
-----
The `_check_pricelist_recursion` constraint only checks if a pricelist
item's `base_pricelist_id` is the same as the item's `pricelist_id`. It
can therefore not detect if two or more pricelists have a mutually
recursive dependence relationship.

Solution
--------
Use a depth-first search to ensure any dependent pricelist doesn't
depend on a parent pricelist.

opw-5070604

closes odoo/odoo#226692

X-original-commit: e7b41abf2bc034ae8cb10ab22f73007e88670f13
Signed-off-by: Levi Siuzdak <sile@odoo.com>