[FIX] safe_eval: accept Python 3.8 opcodes
Python 3.8 introduced four new opcodes ROT_FOUR, BEGIN_FINALLY, CALL_FINALLY and POP_FINALLY.
https://docs.python.org/3/whatsnew/3.8.html#cpython-bytecode-changes
https://bugs.python.org/issue17611

Safe eval will fail on code with try except.
ValueError: forbidden opcode(s) in 'try:...except:...': BEGIN_FINALLY

Minimal backport of #41085

X-original-commit: 4289d266320396c49c2f735d2c987627db615e75