[FIX] pos_self_order: check if pos_config_id is available or not
If a user gets 'pos_config_id' None, then traceback will appear.

Error: int() argument must be a string, a bytes-like object or a real number,
       not 'NoneType'

In the 'pos_self_order_start' function if  'pos_config_id' is none
then traceback will raise:
https://github.com/odoo/odoo/blob/saas-16.3/addons/pos_self_order/controllers/controllers.py#L46

Therefore, in the above use case, applying the condition will check if
'pos_config_id' is available or not

sentry-4235926588