[FIX] mrp_subcontracting_account: validate a picking
When validating a picking that comes from a subcontractor, if there is a
backorder, it will lead to an odoo error

To reproduce the issue:
(Need purchase)
1. Create a product category PC:
    - Costing Method: FIFO
2. Create two products P_compo, P_finished
    - Both storable
    - P_compo:
        - Tracked by lot
    - P_finished:
        - With a vendor V
3. Create a BoM:
    - Product: P_finished
    - Type: Subcontracting
    - Subcontractors: V
    - Components:
        - 1 x P_compo
4. Create and confirm a PO:
    - Vendor: V
    - Products:
        - 10 x P_finished
5. On the receipt, record the production of 7 x P_finished
6. Validate the receipt (with backorder)

Error: An Odoo Error is displayed "ValueError: Expected singleton"

When recording the production, because the producing quantity is not the
expected one, a second manufacturing order MO02 is created. Therefore,
the stock move SM01 that brings the P_finished in the stock has now two
origin moves: the finished moves of MO01 and MO02.

Then, when validating the picking, SM01 is split into two SM:
https://github.com/odoo/odoo/blob/30cc4b5050f538ac4b9152dd78686682d42e7036/addons/stock/models/stock_move.py#L1542-L1547
And this new stock move SM02 has the same origin moves (i.e., the
finished moves of MO01 and MO02). Later on, still while validating the
receipt, it leads to:
https://github.com/odoo/odoo/blob/6c086d820b05602c149f4387d3d19c8e4eed0c8c/addons/mrp_subcontracting_account/models/mrp_production.py#L10-L14
where `self` is MO01. So, here is the issue: as explained above, the
finished moves of M01 contains two moves: SM01 and SM02. Therefore,
reading `is_subcontract` on the recordset or calling `_get_price_unit`
(which is an `ensure_one` method) on this recordset will raise the
error.

OPW-2814448
OPW-2817512

closes odoo/odoo#88214

Signed-off-by: Arnold Moyaux <arm@odoo.com>