[FIX] portal: prevent error while country is not selected
Currently, the error arises when saving details in the portal view without
selecting a country

Steps to reproduce:

- Install the 'account' module.
- Turn on developer mode.
- Navigate to Settings > Users & Companies > Users and open the current user.
- Open the related partner.
- Click on 'Invoice' and create a new invoice.
- Add a product and confirm it.
- Go to portal view and click on 'Edit information'.
- Click on the 'Save' button.

TypeError:  invalid literal for int() with base 10: 'False'

The issue occurs when attempting to save details in the portal view without
selecting a country. At this point [1], a string "False" is passed as the
'country_id', and the system attempts to convert it into an integer using
typecasting (int()).

link[1] : https://github.com/odoo/odoo/blob/fc55cd0ecb9e79ee4491537cc77baa0d57f1f3c7/addons/portal/views/portal_templates.xml#L500

To resolve this issue, the condition is added to ensure that only integer
values are passed to the 'country_id'.

sentry-4959817278