[FIX] l10n_ar_withholding: module reinstall
Uninstall l10n_ar_withholding
Install again l10n_ar_withholding

Issue:
 Reinstall will fail with error
 odoo.exceptions.ValidationError: Invoice and credit note distribution should each contain exactly one line for the base.

This occurs because the system attempt to create a tax repartition line in
existing tax instead of updating the data

opw-3946193

X-original-commit: b09db37fe1e51f931d6769319a1dad7454102bc7