[FIX] account: ensure correct model is used for invoice report generation
Currently an error occurs during post-processing of a payment transaction.

Steps to Reproduce:

 - Install the website_sale module.
 - Open Reports > Quotation / Order and enable the Invoice report option.
 - Go to the Website, place an order using the Wire Transfer payment provider.
 - Open Scheduled Actions.
 - Find and manually run the Payment: Post-process transactions action.

MissingError: Record does not exist or has been deleted.
(Record: account.move(22,), User: 1)

This issue was generated because the user clicked on the invoice report
option on the report Quotation / Order as a result, when we try to print
qutation /order it tries to browse the sale.order with id 22 as an account.move

This commit ensures that the is_invoice_report field is only visible
when the model is account.move. Additionally, the _is_invoice_report method
has been modified to return True only when the model is account.move,
thereby preventing a MissingError during scheduled actions.

Sentry-6563415103

X-original-commit: 98e32aa1a7a15fb71229ae7df1f6d5d0c922697d