[FIX] website: add the necessary field in the kanban view
Before this commit,
The 'icon' field is referenced in the link below
https://github.com/odoo/odoo/blob/d8315df6fd733c1331911583f86803bad1718d2d/addons/website/views/website_views.xml#L444
But it has not been defined on the kanban view
(Actually it has been removed from the view by this commit: https://github.com/odoo/odoo/commit/69b24e4de17878ea5bc5f3509f0c9aa7c06be20a)
And because of this, below error is thrown:
TypeError: Cannot read properties of undefined (reading 'value')
while clicking the 'Pick a theme' button in Website settings.

After this commit,
This issue has been resolved.

closes odoo/odoo#81578