Cherry pick of c239da97b17fa9bc8983dc0a6aea20fde9bf773c failed
stdout:

stderr:
17:40:18.348205 git.c:344               trace: built-in: git cherry-pick c239da97b17fa9bc8983dc0a6aea20fde9bf773c
error: could not apply c239da97b17f... [FIX] point_of_sale: Do not allow refund and sales
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: