[FIX] Move payment icons to payment addon, to avoid installation problem if missing subaddon
If one wants to restrict the addons used by custom odoo deployment, and for instance you only want `payment_transfer`, you still needed to have available all the other ones, or you'd be getting this error at install:

    odoo.tools.convert.ParseError: "File not found: payment_buckaroo/static/src/img/buckaroo_icon.png" while parsing /opt/odoo/auto/addons/payment/data/payment_acquirer_data.xml:15

For some weird reason, the base addon is using files of the submodules, instead of making it the other way around: submodules should use files from base addon.

So, here the patch is quite simple: just move files to base addon, where they are being used, and reuse them from there in submodules.