Cherry pick of 5fbf579487355cbe42c1bed5db006afc993935e2 failed
stdout:

stderr:
error: could not apply 5fbf5794873... [ADD] website_event_*: add Online Event support base modules
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'