[FIX] sale: prevent error when immediately removing catalog product after add
Currently, an error occurs when the user immediately removes a catalog
product after adding it.

Steps to Reproduce:
 - Install the sale_management module.
 - Go to Sales Orders and create a new sale order.
 - In the order line, click on the Catalog button.
 - Add a product and then immediately remove it.

ValueError: Expected singleton: sale.order.line()

This error occurs after [this commit], when the user clicks the Remove
button immediately after clicking the Add button (within 500 ms). In this
case, the system proceeds with the last request due to the useDebounced
delay [1], which removes the product. However, since there is no order
line yet for that product [2] and the quantity is 0, the order line [3] is not
created. When it attempts to retrieve the discounted price, it
raises the error [4].

This commit ensures that if no order line exists, the product's
price is returned according to the sale order's pricelist.

[this commit]: https://github.com/odoo/odoo/pull/233098/commits/697c559791fdf00b5602b9459bbdf21f392757d8

[1]: https://github.com/odoo/odoo/blob/ec212f38e50520edf612522717952855c8c09a80/addons/product/static/src/product_catalog/kanban_record.js#L17-L19

[2]: https://github.com/odoo/odoo/blob/ec212f38e50520edf612522717952855c8c09a80/addons/sale/models/sale_order.py#L2202

[3]: https://github.com/odoo/odoo/blob/ec212f38e50520edf612522717952855c8c09a80/addons/sale/models/sale_order.py#L2218-L2219

[4]: https://github.com/odoo/odoo/blob/ec212f38e50520edf612522717952855c8c09a80/addons/sale/models/sale_order_line.py#L1602-L1603

sentry-7019831319

closes odoo/odoo#235470

Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>