Cherry pick of b877831cef7990bd3a302b6722d9ceea3e7eaf2f failed
stdout:

stderr:
10:32:47.240051 git.c:344               trace: built-in: git cherry-pick b877831cef7990bd3a302b6722d9ceea3e7eaf2f
error: could not apply b877831cef7... [FIX] l10n_fr_pos_cert: do not allow to delete last line
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'