[FIX] hr_work_entry: fix ValueError on creating payslips
Steps to reproduce:
1. Install Payroll and Time Off modules on v19.2.
2. Create a public holiday via the form view (Time Off -> Configuration ->
   Public Holidays). Do not enter a work entry type and save.
3. Open Payroll and try to create a payslip for any employee in the same
   month as the public holiday.

Issue:
The `work_entry_type_id` is required for payroll calculations. If it is null
the `_round_days` calculation evaluates an empty recordset, producing a
ValueError.
[here]: https://github.com/odoo/enterprise/blob/39095789c2b6a7e558d11f479a249871b3b800b6/hr_payroll/models/hr_payslip.py#L1021

While in this PR
[pr]: https://github.com/odoo/odoo/pull/254666/changes
made this field was made required in the
list view, it was missed in the form view. This allows users to save a
holiday without a work entry type, crashing payslip generation later.

Solution:
Make the `work_entry_type_id` field required in the form view as well to
prevent the creation of inconsistent public holiday records.

Also fixed the test case in hr_attendance module as in it useing the
`form.save()` will give error as now `work_entry_type_id` has become
requierd.

Traceback:
```.py

  File "/home/odoo/src/enterprise/saas-19.2/hr_payroll/models/hr_payslip.py",
line 1021, in _round_days
    day_rounded = float_round(days, precision_rounding=precision_rounding,
rounding_method=work_entry_type.round_days_type)
  File "/home/odoo/src/odoo/saas-19.2/odoo/tools/float_utils.py", line 152, in
float_round
    raise ValueError(msg)
ValueError: unknown rounding method: False
```

opw-6477587

closes odoo/odoo#285597

X-original-commit: 9721a34efff3a5f1210748b6c3f3c9d7f02ef96b
Signed-off-by: Romain Carlier (romc) <romc@odoo.com>