[FIX] mrp_subcontracting: make warehouse duplication test agnostic to purchase_stock
The test `test_duplicating_warehouses_recreates_their_routes_and_operation_types` was failing with:

    AttributeError: 'stock.warehouse' object has no attribute 'buy_to_resupply'

A recent change added to the test :

    wh_original.buy_to_resupply = False

However, `buy_to_resupply` is defined in `purchase_stock`. When this module is not installed,
the field is absent and the test crashes.

Fix:
    Only assign the field if it exists on stock.warehouse.

RB-232580

X-original-commit: 66ddf08e7bd3b29f9c67f0ad367b0395a4be9790