[FIX] l10n_latam_check: Fix when transfer third party check
Description of the issue/feature this PR addresses:

The same third-party check payment method (e.g., in_third_party_checks) can currently be assigned multiple times to the same journal,
either as inbound or outbound.
This misconfiguration leads to unexpected behavior and runtime errors when using the payment transfer wizard.

It is possible to assign a third-party check payment method more than once to a journal.

When transferring a third-party check via the wizard (l10n_latam_payment_mass_transfer), the system may raise:

pgsql
Copy
Edit
ValueError: Expected singleton
because more than one payment method line is returned.