Cherry pick of ef8f472bfa85a4aa9c4c26f5ae41651b1fab582f failed
stdout:

stderr:
12:09:25.066440 git.c:344               trace: built-in: git cherry-pick ef8f472bfa85a4aa9c4c26f5ae41651b1fab582f
error: could not apply ef8f472bfa8... [FIX] pos_sale: remove redundant payment information in invoice
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: