[FIX] mrp: missed update for workorder creation
Issue
----

When work orders are computed, the compute function deletes some of the previous work orders. However,
it doesn't take into account these deleted work orders when chosing what work orders to update. So it ends up
issuing an update command after a delete command for the same order. This causes work orders to disappear.

Steps
-----

 - Open Manufacturing -> Create a storable product and a BoM for this product.
 - Create a product as part of the BoM.
 - For the latter product, create another BoM that is a kit.
 - Set an operation in the BoM of the kit.
 - Create a manufacturing order for the storable product.
 - Set a quantity larger than 1, and manually save the MO (without confirming it).
 - Split the MO in any number of MOs, and after confirming the split the following traceback is triggered:

 `remaining_qty = initial_workorder_remaining_qty[index % workorders_len]
ZeroDivisionError: integer division or modulo by zero`

opw-3994583