[FIX] tools: prevent error on signed document with an invalid certifiacte
Currently, an error occurs when a user sign the document and tries to validate
and send the completed document.

Steps to reproduce:

- Install the sign module.
- Go to: Sign Settings > Cryptographic Signature > Create a 'Signing certificate'
  and upload any random PDF (Observe: A warning appears 'This certificate
  could not be loaded. Either the content or the password is erroneous.').
- In the Sign app, upload any document, drag and drop a Signature field, and
  sign the document.
- Click Validate & Send Completed Document.

Note:
- [1] Make sure your system has cryptography version 41.0.7 or above.
- Refer to [2] for steps to reproduce.

Error:
TypeError: expected bytes-like object, not bool

Root Cause:
At [3], when the certificate is not correctly created,
certificate.pem_certificate is False, which leads to an error.

This commit allows validating and sending a signed document, when the
certificate is invalid.

[1]:
https://github.com/odoo/odoo/blob/d730518fa6a1fba3b3edba6f3b65bcc88ed992fe/odoo/tools/pdf/signature.py#L16

[2]:
https://drive.google.com/file/d/19fd82TdGzVPRUVW3PDMGEhyaQLTwL41h/view?usp=sharing

[3]:
https://github.com/odoo/odoo/blob/a6fa3784b20f75490e405e3728d5a335f2104fa0/odoo/tools/pdf/signature.py#L85

sentry-6796501254

closes odoo/odoo#222417

Signed-off-by: Chong Wang (cwg) <cwg@odoo.com>