[FIX] point_of_sale: better error when missing nomenclature
Before this commit:
If the PoS config have no "Barcode Nomenclature" set, the PoS
session can't start and a cryptic JS traceback will be shown:
```js
TypeError: Cannot read properties of undefined (reading 'message')
at Chrome.start
```
This happen as the barcode rejected Promise request doesn't contains
an error message. More details in:
https://github.com/odoo/odoo/pull/108797

After this commit:
A more user friendly error is displayed

Note: the issue does not happen in previous Odoo's versions
as the field was required before.

opw-3110204

Signed-off-by: Loan (LSE) <lse@odoo.com>