[FIX] product_pricelist.py
QWebException: "read() takes at least 2 arguments (1 given)" while evaluating "get_categories(objects,data['form'])"

Do a browse instead of a read.