[FIX] purchase_stock: returning subcontracted product to vendor location
Steps to reproduce the bug:
- Create a subcontracted product “P1”:
    - the valuation: AVCO automated
    - BoM:
        - component: C1 ($15)
- Go back to the product form for “P1.”
- Click on "Compute from BoM" -> Result: P1 = $15.
- Create a Purchase order:
    - 1 unit of P1
- Confirm the PO and receive P1
- Return the received quantity:
    - Location: “Partner/lcoation”

Problem:
A traceback is triggered:
```
File "/home/odoo/src/odoo/addons/mrp_subcontracting_purchase/models/stock_valuation_layer.py", line 21, in _get_layer_price_unit
 return super()._get_layer_price_unit() + components_price
 File "/home/odoo/src/odoo/addons/purchase_stock/models/stock_valuation_layer.py", line 12, in _get_layer_price_unit
 return self.value / self.quantity
ZeroDivisionError: float division by zero

```

When validating the return, the `_account_entry_move` function is called
to verify if the returned value of the product is different from the
purchased one. In this case, we need to clear the `stock_in` account
with the difference. To do this, we retrieve the layer associated with
the origin move of the return. However, since this move is an internal
one (from the subcontracting location to WH/stock),
the `_should_be_valued` function returns `False`, and no layer is
created for this move:

https://github.com/odoo/odoo/blob/7afd9294338dd18c3351afd2017648931fdb9ee3/addons/stock_account/models/stock_location.py#L25-L30

Because we do not check if a layer exists for this move and directly
call the `_get_layer_price_unit` function, a traceback is triggered as
we have division by zero

Solution:
In case there is no layer associated with the original move, we can
consider the difference as 0.

For example, in our case, the layer of the returned move has a value of
30 (15 for P1 and 15 for C1). Therefore, even if we return P1 to the
subcontractor, we will not return the value of C1 because it has already
been delivered and used.

opw-4053362

X-original-commit: fc7a3307ed4fb36e65a0d0ac873f3dbcf71a9381