[FIX] account: Concatenate properly account name
The account name is summing strings which is a bad practice
and in some refactor in the orm it is generating a traceback
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

Even if this solution can be done with a fix that avoid compute
the name for an empty record, the proper way of concatenate strings
in python is ensuring the types in the concatenation itself.