[FIX] account: make balance zero when it is None
When the cron `_cron_try_auto_reconcile_statement_lines` is executed manually
or automatically in the scenario where currency is not same as `journal_currency`
and `transaction_currency` then the user will face error if the balance is None.

Error: `<class 'TypeError'>: 'unsupported operand type(s) for *: 'NoneType' and
'float' while evaluating
'model._cron_try_auto_reconcile_statement_lines(batch_size=100)'`

Balance is None in these scenarios:
- https://github.com/odoo/enterprise/blob/09f84651e5df4df2b18a6af14aab3a19a8f4298b/account_accountant/models/bank_rec_widget.py#L836

- https://github.com/odoo/enterprise/blob/09f84651e5df4df2b18a6af14aab3a19a8f4298b/account_accountant/models/bank_rec_widget.py#L932

Our commit tends to make the balance 0.0 whenever the balance is None or
not a float value while calculating `journ_amount_currency`.

sentry-4573049666