[P3] Remove unneeded and unported dependency
`python-openid` is required in some places, but no actual code uses it.

Pinned version (2.2.5) did not work in Python 3. See these compilation output:

```
*** Error compiling '/usr/local/lib/python3.5/dist-packages/gevent/_util_py2.py'...
  File "/usr/local/lib/python3.5/dist-packages/gevent/_util_py2.py", line 8#
    raise type, value, tb# modified:
addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
              ^# SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/consumer/consumer.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/consumer/consumer.py", line 345
    except fetchers.HTTPFetchingError, why:
                                     ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/consumer/discover.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/consumer/discover.py", line 307
    except ValueError, why:
                     ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/dh.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/dh.py", line 8
    xor = lambda (a, b): chr(ord(a) ^ ord(b))
                 ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/extensions/ax.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/extensions/ax.py", line 307
    except NotAXMessage, err:
                       ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/extensions/sreg.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/extensions/sreg.py", line 97
    except NamespaceAliasRegistrationError, e:
                                          ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/fetchers.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/fetchers.py", line 209
    except urllib2.HTTPError, why:
                            ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/message.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/message.py", line 104
    raise NamespaceAliasRegistrationError, \
                                         ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/oidutil.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/oidutil.py", line 167
    except binascii.Error, why:
                         ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/server/server.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/server/server.py", line 441
    except ValueError, why:
                     ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/server/trustroot.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/server/trustroot.py", line 445
    except RealmVerificationRedirected, err:
                                      ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/store/filestore.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/store/filestore.py", line 27
    fd = os.open(name, os.O_CREAT | os.O_EXCL | os.O_RDWR, 0600)
                                                              ^ SyntaxError: invalid token *** Error
compiling '/usr/local/lib/python3.5/dist-packages/openid/store/sqlstore.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/store/sqlstore.py", line 352
    except self.exceptions.OperationalError, why:
                                           ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/urinorm.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/urinorm.py", line 76
    map(lambda (m, n): u'%s-%s' % (unichr(m), unichr(n)),
               ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/yadis/etxrd.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/yadis/etxrd.py", line 70
    except XMLError, why:
                   ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/yadis/parsehtml.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/yadis/parsehtml.py", line 183
    except HTMLParseError, why:
                         ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/yadis/services.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/yadis/services.py", line 29
    except XRDSError, err:
                    ^ SyntaxError: invalid syntax *** Error compiling
'/usr/local/lib/python3.5/dist-packages/openid/yadis/xri.py'...
  File "/usr/local/lib/python3.5/dist-packages/openid/yadis/xri.py", line 53
    map(lambda (m, n): u'%s-%s' % (unichr(m), unichr(n)),
               ^
SyntaxError: invalid syntax
```

I just removed the useless dependency.