[FIX] l10n_sa_edi: missing reason when reversing entries
With a SA company setup
Open a journal entry
Hit 'Reverse Entry' > Reverse
Error: "For Credit/Debit notes issued in Saudi Arabia, you need to
specify a Reason"

This occurs because with SA localization we need to provide a reason for
move reversal but by default the reason field is invisible for journal entries

Backport of https://github.com/odoo/odoo/commit/d660fd5204dcb42c45b466a1fbc0ca7f8bf7cbe6

opw-3789732