[FIX] l10n_nl: fix syntax issue in `3.3` migration
fixup for PR : #171737

This PR introduced syntax error while using `IN` with
`sql.Literal` here[^1] and here[^2]. For fixing the issue I avoided
using `psycopg2` and used query parameters and cr.mogrify.

similar traceback:
```
2024-07-09 13:20:03,873 5170 ERROR db_1790119 odoo.sql_db: bad query:
                UPDATE account_account_tag_account_tax_repartition_line_rel
                SET account_account_tag_id = 157
                WHERE account_tax_repartition_line_id = ANY(ARRAY[59,60])
                AND account_account_tag_id IN ARRAY[52]

ERROR: syntax error at or near "ARRAY"
LINE 5:                 AND account_account_tag_id IN ARRAY[52]
                                                      ^

2024-07-09 13:20:03,880 5170 WARNING db_1790119 odoo.modules.loading: Transient module states were reset
2024-07-09 13:20:03,881 5170 ERROR db_1790119 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 236, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/16.0/addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py", line 94, in migrate
    cr.execute(
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near "ARRAY"
LINE 5:                 AND account_account_tag_id IN ARRAY[52]
```

[^1]: https://github.com/odoo/odoo/blob/16.0/addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py#L94-L104
[^2]: https://github.com/odoo/odoo/blob/16.0/addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py#L64-L74

X-original-commit: 1fbb47fbe8964b7c2fc1fd7e104fdefb93b3b264