Cherry pick of eb2cc069de51b6b17327f9ee8aac293d0faa0493 failed
stdout:

stderr:
09:52:12.876204 git.c:344               trace: built-in: git cherry-pick eb2cc069de51b6b17327f9ee8aac293d0faa0493
error: could not apply eb2cc069de5... [IMP] tests: partially backport classCleanups from CPython 3.8
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: