[FIX] sale_stock: prevent error when updating sale order in delivery picking
Currently, an error occurs when user updates the sale order in the
delivery picking.

Steps to Reproduce:
 - Install the sale_stock and sale_management modules.
 - Create a sale order and confirm it.
-  Click the Delivery button on top of the order.
 - In the Additional Info tab of the sale order, select any order
   in sale order field.

psycopg2.ProgrammingError: can't adapt type 'sale.order'
KeyError: <Command.LINK: 4>

This error occur after [this commit] where, after creating sale order,
navigating to its delivery picking, and selecting the same or a different
order, an invalid link caused the error[1].

This commit ensures that the sale order is linked correctly to the
delivery picking.

[this commit]: https://github.com/odoo/odoo/commit/2713876dbc70d3984e584a9037a2206dcda4e84a#diff-2b9de2e50ff5e1dc0362b825bac2b07623770fb3275b3257ef972f255f3ccb8bR172-R173

[1]: https://github.com/odoo/odoo/blob/d484516bcae1beb767d90d20e1ab294f1e9ae8a9/addons/sale_stock/models/stock.py#L173

sentry-6921046230