[FIX] account: Fix bug if internal payment has 0 amount.
Bug description:
Create a payment of type internal and with amount=0
Try to confirm payment and this error will be displayed:
```if not (all_accounts[0].reconcile or all_accounts[0].internal_type == 'liquidity'):
IndexError: list index out of range```

Bug Causes:
In the function `_check_reconcile_validity`:
If there no line to reconcile this error will be shown.

closes odoo/odoo#61915

X-original-commit: ee76b25b003f96073f78420960e216acf14bf821
Signed-off-by: Laurent Smet <smetl@users.noreply.github.com>