[FIX] l10n_sa_edi: download EDI document in invoice
When user create a new invoice and then process it, if server returns an
unexpected error and user download the EDI Document.
a traceback will appear.

Steps to reproduce the error:
- Install 'l10n_sa' and 'l10n_sa_edi'.
- Switch to SA Company.
- Create New Invoice > Select Customer who has parent company
  (ex. Azure Interior, Brandon Freeman) > Add Invoice Lines
- Confirm > Process now
- Go to EDI Documents > Download

Error: A traceback appears:
'TypeError: a bytes-like object is required, not dict'

https://github.com/odoo/odoo/blob/08f2ed7a132b8df4cc6c1863b9cc1e75ab4ddf32/addons/account_edi/models/account_edi_document.py#L62
Here, when user download EDI Document,
it will get move_applicability['edi_content'](move) as dictionary.
So it will lead to above traceback.

sentry-4312719182