[FIX] sale_stock,stock: fix traceback  if user click return picking for exchange
Currently, a traceback occurs when the user tries to click
return for exchange button.

To reproduce this issue:
1) Install `stock`
2) Create a new receipt picking with stock moves and quantity
3) Click on the `validate` button and then the `return` button
4) Update the return quantity and click `return for exchange`

Error:- "AttributeError: 'stock.move' object has no attribute 'sale_line_id'"

The sale_line_id is defined in sale_stock. If the sales module is not installed,
then the move does not contain any sale_line_id.
which leads to the traceback mentioned above.

sentry-5993887458

X-original-commit: 9af72011e0f9a5441dd7338576128d7bf99edce6