[FIX] point_of_sale: force cascade delete when switching CoA
Steps to reproduce:
- Install industry Hair Salon
- Settings > Invoicing > Fiscal Localization
- Switch to Jordan fiscal localization

Issue:
Action will fail with error
```
ERROR: update or delete on table "account_journal" violates foreign key constraint "pos_payment_method_journal_id_fkey" on table "pos_payment_method"
DETAIL:  Key (id)=(6) is still referenced from table "pos_payment_method".
```

Analysis:
It occurs because, when switching CoA, the system attempt to delete and
re-create journals. However, the hair salon industry initialize a PoS
configuration that will create a default payment method based on one of
those journal, thus the system will raise a constraint error on delete.
A solution is to manually enforce cascade delete when we are switching
CoA.

opw-5145235

X-original-commit: bb2bc30e0166a7f7c3d1e6f6d933db00c2b69a58