[FIX] l10n_es_edi_verifactu: removed unnecessary chatter
The system will crash with error when user clicks on expand button.

Error:
`AttributeError: 'l10n_es_edi_verifactu.document' object has no attribute '_get_thread_with_access'`

Cause:
- `l10n_es_edi_verifactu.document` does not inherits ['mail.thread',
  'mail.activity.mixin'] and used chatter in it's form view.

- In this PR, removed `<chatter/>` from view.

sentry-6792833694

closes odoo/odoo#232928

X-original-commit: 8d10a3720d94b59b7ed2e686f928e2acd8c6f508
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>
Signed-off-by: Krishna Arvindkumar Patel (krip) <krip@odoo.com>