[FIX] hr_recruitment: click on applicant_char widget
Scenario:

- install hr_recruitment but not documents (to have the right view)
- go to Employee > Configuration > Recruitment | Job Positions
- choose a job positions with documents and click on Documents
- click on Applicant column on one of the rows

=> traceback shown:

OwlError: Invalid props for component 'FormController': 'resId' is not a
number or boolean
  at Object.validateProps

Reason:

In saas-17.2 with 3713e5622f0d6b04bec0156fd66fa9f91ef93213 merged in
february 2024, many2one_reference was changed from a simple integer to
either 0 if unset, or a object containing resId and displayName keys.

Fix:

Get the id with .resId and this should not happen, but test if the
record is set with "if(res_id && ...)" in case res_id was 0.

Note: without the fix, the added test fails by opening the view if
res_id was 0, and if not the next click would fail with:

OwlError: Invalid props for component 'FormController': 'resId' is not a
number or boolean

opw-4384139

closes odoo/odoo#197042

X-original-commit: 04d5066c6b413c1522dade74f6e1820b62750434
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>