[FIX] web,sale_pdf_quote_builder: restrict uploading non-supported files
Currently an exception is generated when a user uploads an image or non-PDF
file in the `File Content (datas)` field of the quotation document.

Steps to produce an error:
- Install `sale_management` and go to `Sales`
- Click Configuration > Headers/Footers > Click on New
- Click `"Upload your file"` and upload a non-PDF (Select `All Files` instead
  of `.pdf` while uploading the file.)

Error:  `PdfReadError: EOF marker not found`

The `accepted_file_extensions` tag is avaliable that only shows `.pdf`
files when users try to upload files, but many users select `All Files`
instead of `.pdf` if they do not see the pdf file in the list and try to upload
non-pdf  files. Also, the error will occur if users have a file with a
`.pdf` extension, but different type.

This commit will fix the above issue by restricting uploading non-supported
files that were uploaded by users.

By introducing the `allowed_mime_type` option in binary fields, it prevents
users from uploading only supported file if we provide the field option.
`accepted_file_extensions` option is avaliable but it works on a browser level,
showing PDF files for uploading, but users may select another file by
selecting `All files` while uploading.

sentry-6112968654,6161120972

closes odoo/odoo#199762

Signed-off-by: Morgane Demesmaeker <edm@odoo.com>