[BUG] account_edi_ubl_cii: TestUblExportBis3BE tests fail due to partner ref database contamination
Module: account_edi_ubl_cii
Version: 18.0
Type: Bug in test setup

Problem
Two tests fail when running on a database where res.partner records already have a ref field set:
FAIL: TestUblExportBis3BE.test_invoice_BR_CO_10_line_extension_amount_sum_lines
FAIL: TestUblExportBis3BE.test_invoice_BR_S_08_tax_subtotal_taxable_amount
Error:
AssertionError: Number of children elements for node /Invoice is different.
Non-expected child:
<cbc:BuyerReference>SPX00007</cbc:BuyerReference>