Cherry pick of 1c5916a85f0f7314b48288d0393a1df01fc2a38d failed
stdout:

stderr:
18:03:31.909444 git.c:344               trace: built-in: git cherry-pick 1c5916a85f0f7314b48288d0393a1df01fc2a38d
error: could not apply 1c5916a85f0... [ADD] l10n_ar: refunds with liquido docs
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: