[FIX] mail: fix test_mail_template_dynamic_placeholder_tour
Issue:
"test_mail_template_dynamic_placeholder_tour" tour is failing
sometimes with the following error:

Tour mail_template_dynamic_field_tour ->
Step Click on contact (trigger: div[name="model_id"] .ui-autocomplete).
TypeError: Cannot read properties of undefined (reading 'click')

Cause:
It happens that the element is not loaded yet after the delay
and clicking on an undefined element triggers the error.

Solution:
Make sure to only click on the element when it's ready.

runbot-223306

X-original-commit: 9d332fd0c8b79f33151cb368bdcb8d1807829c48