[FIX] base: add properties definition field automatically in views
Steps to reproduce
==================

- Install repair,web_studio
- Go to repair
- Open any record
- Open studio
- Switch to the misceallaneous tab
- Click on the Operation Type field
- Add the "Technical / Receive notifications in Odoo" group in
  "Allow visibility to groups"

```
TypeError: Cannot read properties of undefined (reading '0')
  at PropertiesField._getSeparatorFoldKey
```

Cause of the issue
==================

Since the user doesn't have that group, the field `picking_type_id` will no be available.

```py
repair_properties = fields.Properties(
    'Properties',
    definition='picking_type_id.repair_properties_definition'
)
```

That field is needed as it's the definition field for the
repair_properties field.

Solution
========

When postprocessing views, we already add some fields that are needed by
others. We can do the same for properties fields.

opw-4594796

closes odoo/odoo#200918

X-original-commit: 4ce50ea6b22261200b1efc072ab8644f8bd88f3b
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>