[FIX] base_import_module: warning while import module with unmet dependencies
When user tries to import some third party module from 'Import Module' and has
unmet dependencies or module contains some error.

Steps to reproduce:
1) Install 'base_import_module' module.
2) Go to 'Apps' in 'Apps' > 'Third-Party Apps'.
3) Download any incompatible version third-party free app.
4) Now, Click on 'Import Module' in 'Apps'.
5) Now in import module wizard, Upload your zip file by clicking
  'UPLOAD YOUR FILE' button.
6) Click on 'IMPORT APP' button and the error will be generated in
  the backend.

Error: ParseError:while parsing /tmp/tmpdcod8m08...  traceback will be generated
       because of '_logger.exception' in the method 'import_zipfile'.

Sentry-4254922962