Cherry pick of 61355df81ab92c765014606efc168467c15f3aeb failed
stdout:

stderr:
16:21:20.232657 git.c:344               trace: built-in: git cherry-pick 61355df81ab92c765014606efc168467c15f3aeb
error: could not apply 61355df81ab... [FIX] event: keep default values when registering from frontend
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: