[FIX] account: prevent error when creating accrual entries for draft invoices
Steps to reproduce:
- Install the `accountant` and `sale_management` modules.
- Create and confirm a SO with a product whose `Invoicing Policy` is
  set to `Ordered quantities`.
- Click `Create Invoices` > select `Regular invoice` > `Create Draft`.
  (leave the invoice in the draft state).
- Navigate to Accounting > Review > Invoiced Not Delivered.
- Select the newly created invoice and click `Create Accrual Entries`.

Error:
ZeroDivisionError: division by zero

Root Cause:
At [1], `processed_qty` is initialized with 0. If all the selected invoices are
in the draft state, the code never enters the for loop, so `processed_qty`
remains 0. Later, it attempts to divide the `amount` by `processed_qty ',
causing an error.

Fix:
This commit prevents errors when creating accrual entries for draft invoices.

[1]:
https://github.com/odoo/odoo/blob/a7d285a833f5b1d47a11a1b8ec31e3730c1c854c/addons/account/wizard/accrued_orders.py#L258-L265

opw-6332652

closes odoo/odoo#277441

X-original-commit: fd8c0a7ed4e1d8a9d3839c6a51a4505a6b5983d6
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>