[FIX] l10n_ar_website_sale: prevent error while opening account detail in portal
Currently, an exception was generated when the user tries to open their
account details in the portal (url: my/account)

error: `KeyError: 'partner_sudo'`

This error was generated because when the user tries to open their account
detail in the portal, we do not have 'partner_sudo'.

Recentley refacto code with [1] replaced `partner` with `partner_sudo` for the
getting partner in the website sale address (`shop/address`) and we have the new
key because the template 'partner_info' called from template 'address' see [2]
and `partner_sudo` set from [3] for address. But when we call the 'partner_info'
from template 'portal_my_details_fields' at [4], we do not have `partner_sudo`

This commit will fix the above issue by passing `partner_sudo` in the template
at the time prepare value for opening account detail in portal.

[1] - https://github.com/odoo/odoo/commit/453cfab758505ae15135703fb7be8bdb54981444
[2] - https://github.com/odoo/odoo/blob/3ea0c936c01a7c55ee8fa6ee64fd8e89b2a04f5f/addons/l10n_ar_website_sale/views/templates.xml#L60
[3] - https://github.com/odoo/odoo/blob/3ea0c936c01a7c55ee8fa6ee64fd8e89b2a04f5f/addons/website_sale/controllers/main.py#L1119
[4] - https://github.com/odoo/odoo/blob/3ea0c936c01a7c55ee8fa6ee64fd8e89b2a04f5f/addons/l10n_ar_website_sale/views/templates.xml#L68

sentry-5725856236