[FIX] website_slides: fix datetimeObj.getTime is not a function
HOW TO REPRODUCE
================

- Don't need to login
- From Odoo front-end, go to Courses > Trees, Wood and Gardens >
    Main Trees Categories
- You get the following client error:
    Uncaught Promise > datetimeObj.getTime is not a function

HOW TO SOLVE:
============

Unlike standard JS equivalent, luxon datetime objects don't have a
getTime() function. Replace it by valueOf() function.
Also, remove calls to `DateTime.fromJSDate().formatting_fn()` by
luxon equivalent functions.

see bb09cf76e32b20864dc45eacf912d2c6f26768ef

task-3632077

X-original-commit: 657d5493f8a0f42cdbc6a4c598361d6366aef812