[FIX] event_crm: prevent error whenever modify questions in attendees form view
Currently, the error occurs when trying to update question answers in the
attendees form view

Steps to reproduce:

- Install a 'website_event_questions' and 'event_crm' modules.
- Create a record in the 'Lead Generation Rule' without any match conditions
and add values for 'Rules Name' and 'Event' in which registrations are open.
- After that go to that Event which is added in the 'Event' field and add a
question answer in the 'Questions' page.
- In Event click on 'Go to Website' and proceed an event registration.
- Return to the event, And click on the 'Attendees' button to open a registered
attendee.
- Try to add any 'Question' on the Questions page.

Error:   keyerror: 'registration_answer_ids'.

When modifying questions or answers in the attendees' form view, There's an
issue where the system attempts to retrieve the 'registration_answer_ids' key
from the 'old_vals' dictionary [1]. But, This key is not present. because the
value of 'registration_answer_ids' is only returned by the method
'_get_lead_description_fields' [2], and this method is not executed in the
entire flow. As we can see at this point [3] 'self._get_lead_contact_fields()'
always returns a static value so method  '_get_lead_description_fields' is never
executed.

[1]:https://github.com/odoo/odoo/blob/8a60ee5076adeec54169243f804ef1362eb3744c/addons/event_crm/models/event_registration.py#L135
[2]:https://github.com/odoo/odoo/blob/8a60ee5076adeec54169243f804ef1362eb3744c/addons/website_event_crm_questions/models/event_registration.py#L24-L27
[3]:https://github.com/odoo/odoo/blob/8a60ee5076adeec54169243f804ef1362eb3744c/addons/event_crm/models/event_registration.py#L295

This commit solves this issue by appending 'registration_answer_ids' values
based on new values in method name '_get_lead_tracked_values' to ensure that the
'registration_answer_ids' key is present in the 'old_vals' dictionary during the
process of modifying questions or answers in the attendees' form view.

sentry-4874260136