[FIX] hr_recruitment: prevent error when installing the Recruitment module
Currently, an error occurs when upgrading the `hr_recruitment` module, if
the `sms` module is not installed.

Steps to produce:
- Install `hr_recruitment`.
- Uninstall `sms`.
- Upgrade `hr_recruitment`.
- Observe the error.

```
ParseError:  while parsing /home/odoo/src/odoo/saas18.1/addons/hr_recruitment/
views/hr_candidate_views.xml:220
Invalid template name “sms.composer” in action definition.

View error context:
'-no context-'
```

An error occurs when attempting to access the `sms.composer` - [1],
without ensuring `sms` module is installed. If `sms` is not installed,
this causes a `ParseError` when installing `hr_recruitment`.

[1] - https://github.com/odoo/odoo/blob/eb1b38723363b4dc54dbfadaed2831d41f688c29/addons/hr_recruitment/views/hr_candidate_views.xml#L222

This commit resolves the issue by adding `sms` module as a dependency,
ensuring that `hr_recruitment` has the required model installed.

sentry - 6258561025