Cherry pick of b8fa82ecd2bcd4bac3402590fbf327eb599e07e5 failed
stdout:

stderr:
17:08:43.546848 git.c:344               trace: built-in: git cherry-pick b8fa82ecd2bcd4bac3402590fbf327eb599e07e5
error: could not apply b8fa82ecd2b... [FIX]account_edi_ubl : fix finding of partner using vat identification
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes odoo/odoo#69059

Signed-off-by: Laurent Smet <smetl@users.noreply.github.com>