[FIX] base: AttributeError in check_view_fields
If corresponding_field is None, we need to avoid the "AttributeError: 'NoneType' object has no attribute 'get'" error.