[FIX] stock_dropshipping: add CoA setup
The test `test_dropship_return_backorders_bill_on_order` failed when running
without demo data because no chart of accounts was installed, so no Purchase
journal existed. As a result, `purchase_order.action_create_invoice()` raised:

  UserError: No journal could be found in company ... for any of those types: purchase

This change inherits from AccountTestInvoicingCommon to have the necessary charts.
runbot-231285

closes odoo/odoo#224775

Signed-off-by: William Henrotin (whe) <whe@odoo.com>