[FIX] sale: prevent traceback when accessing collapse_prices
Steps to reproduce:
-------------------
1. Install sale_management with demo data
2. Create a new quotation/order and add a section and a subsection
3. Drag the subsection line above the section line
4. Confirm it and click on Preview

Issue:
------
```python
Traceback (most recent call last):
The error occurred while rendering the template sale_subscription.subscription_portal_content and evaluating the following expression: <t t-set="collapse_prices" t-value="current_section.collapse_prices or line.collapse_prices"/>

Error while rendering the template:
    AttributeError: 'NoneType' object has no attribute 'collapse_prices'
    Template: sale_subscription.subscription_portal_content
    Reference: 1713
    Path: /t/div[4]/section[1]/div[1]/table/tbody/t[4]/t[11]/t[3]
    Element: <t t-set="collapse_prices" t-value="current_section.collapse_prices or line.collapse_prices"/>
    From: (1712, '/t/t', '<t t-call="portal.portal_layout"/>')
          (1712, '/t/t/body/div[1]/div/div[2]/div[11]/div/t', '<t t-call="#{sale_order._get_name_portal_content_view()}"/>')
          (1713, '/t/div[4]/section[1]/div[1]/table/tbody/t[4]/t[11]/t[3]', '<t t-set="collapse_prices" t-value="current_section.collapse_prices or line.collapse_prices"/>')
```

Cause:
------
Since current_section is None in this case, it leads to the
above traceback when trying to fetch the collapse_prices value.

Solution:
---------
Convert subsection lines without a parent_id into section lines
to prevent the traceback.

opw-5367739

X-original-commit: b0fe8e9440422f622c9c86c490cd0644e958cd79