Cherry pick of b2af63f30f940a5d93746f190e67818e14ad9816 failed
stdout:
Auto-merging .tx/config
CONFLICT (content): Merge conflict in .tx/config

stderr:
14:15:48.328414 git.c:455               trace: built-in: git cherry-pick b2af63f30f940a5d93746f190e67818e14ad9816
error: could not apply b2af63f30f9... [I18N] base: add module to transifex
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: