[FIX] hr_attendance: prevent errors when employees manually do their attendance
Currently, an error occurs when employees manually do their attendance, and an
employee's avatar is not available.

Step to produce:

- Install the 'hr_attendance' module.
- Go to the Employees open any employee and remove an image from it.
- Go to Attendances / Kiosk Mode and click 'Identify Manually', Open the
employee who does not have an image.

TypeError: 'bool' object is not subscriptable

An error occurs when the system tries to retrieve a data URL from an employee
image but it is not available resulting False (bool) value passing instead of
binary.

link [1]:https://github.com/odoo/odoo/blob/0a69d91ff2ccb90fc5ca94013a4fc7371017c876/addons/hr_attendance/controllers/main.py#L38

To handle this issue, Add a condition that, Only converts data URI from an
employee's image if it is available.

Sentry-5681797884

closes odoo/odoo#175807

Signed-off-by: Jurgen Gjini (jugj) <jugj@odoo.com>