Cherry pick of 60cdc33483f3c31477ad6f5b7cee0a815e19817c failed
stdout:
Auto-merging addons/web_editor/static/src/js/editor/odoo-editor/src/utils/serialize.js
CONFLICT (content): Merge conflict in addons/web_editor/static/src/js/editor/odoo-editor/src/utils/serialize.js

stderr:
18:27:36.936785 git.c:463               trace: built-in: git cherry-pick 60cdc33483f3c31477ad6f5b7cee0a815e19817c
error: could not apply 60cdc33483f3... [FIX] web_editor: allow a node to not have oid in serialize
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: