[FIX] base: decorate api key create method
Reproduce
---
- tick "Customers can generate API Keys" in settings
- login as portal user
- Connection & Security -> New API key -> give name -> Confirm ->BUG

```
TypeError: APIKeyDescription.create() missing 1 required positional argument: 'vals_list'
```

opw-4385632

closes odoo/odoo#190769

X-original-commit: 3b3ee6bb5f2d3edc69f4166e0e63074f8b1e1c87
Signed-off-by: Olivier Dony (odo) <odo@odoo.com>