[FIX] base_import_module: avoid warning when browsing industry modules
An ormcache has been added to a method that takes lists as parameters but
lists are not hashable.

steps to reproduce:
- go to apps and click on on 'Industries'

before this commit:
- a warning is raised in the logs:

WARNING industry odoo.tools.cache: cache lookup error on ('ir.module.module', <function IrModule._get_modules_from_apps at 0x7f99e842fc70>, ['icon', 'icon_flag', 'to_buy', 'name', 'state', 'summary', 'website', 'application', 'module_type', 'shortdesc'], 'industries', False, ['&', '!', ['name', '=like', 'theme_%'], '&', ['application', '=', True], ['module_type', '=', 'industries']], 80, 0)
Traceback (most recent call last):
  File "/home/nda/dev/odoo/17.0/odoo/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/home/nda/dev/odoo/17.0/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/nda/dev/odoo/17.0/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
TypeError: unhashable type: 'list'

after this commit:
- ormcache is properly used

opw-3660052

X-original-commit: 50541486332fa8e56ba4a890746bc8ecb60d7996