Cherry pick of 9a684eb0639b8b99a49047e00e61c5c5b316c1d5 failed
stdout:

stderr:
error: could not apply 9a684eb0639... [FIX] mrp: installation on very large inventories
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'