[FIX] website_event_track: fix track proposal submit with speaker image
Followup of odoo/odoo@41fe2ebdb9cc.

Before this commit, when trying to submit a track proposal with a
speaker image, the request failed with:

```
TypeError: event.track.image: use BinaryValue instead of bytes
```

closes odoo/odoo#280753

X-original-commit: 32defafded0b79f2965742254decfc1b29bad9c1
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>
Signed-off-by: Xavier Alt (xal) <xal@odoo.com>