[FIX] mail: prevent error when uploading invalid pdf file
Currently, an error occurs when trying to preview the first page of a PDF
attachment in Discuss if the PDF is encrypted or contains invalid encoding.

Steps to produce:

- Install the mail module.
- Open Discuss and attach the encrypted file [1], or the invalid PDF file [2].

(Note: Ensure Python version 3.12+ is used.)

Error:
PyPDF2.errors.DependencyError: PyCryptodome is required for AES algorithm
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid
start byte

Root cause:
At [3], extract_page directly calls PdfFileReader, when it fails to read or
decrypt the file, Python raises an error.

Fix:
This commit prevents errors when a user attaches a PDF file that is unreadable
or encrypted.

[1]:
https://drive.google.com/file/d/1moSlwXHkqcV6_7zHBNhLMLi-9Ye_xDGJ/view?usp=sharing

[2]:
https://drive.google.com/file/d/16O4LLH8dL0RWmbOx4HrcooFUyesWaVi-/view?usp=sharing

[3]:
https://github.com/odoo/odoo/blob/6baf1ec4403701692ee9775152de6a74f4af4f7a/odoo/tools/pdf/__init__.py#L227

sentry-6912765819

closes odoo/odoo#230713

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>