[FIX] web: prevent error when clicking on the translate button
Currently, an error occurs when the user clicks on the translate button.

Steps to Reproduce:

 - Install the CRM module.
 - Go to settings and in Languages add 1 more language.
 - Go to CRM > Configuration > Pipeline > Tags.
 - Click New and, in the Name field click the translate button on the
   right.

Behavior in 18.0

When the tag name is not set, the translation dialog opens immediately.
If a tag name is entered, the translation dialog shows the translated value
on the second click.

Behavior in saas-19.1

AssertionError: Invalid falsy real id

Error:
After this [recent commit], when the user clicks on the translate button,
if the record has a root record, the root record is saved before opening
the translation dialog. However, in the case of an editable DynamicList
view, the record does not have a root record so saving the record returns
a promise instead of the resolved value [1].
Because of this promise, the condition fails [2], and the translation dialog
is opened with a falsy ID since the record is not yet saved [3].
In saas-19.1, this issue raises Invalid falsy real id error after
[this second commit].

This commit ensures that await is used so the resolved value is returned
after the record is saved before opening the translation dialog.

[recent commit]: https://github.com/odoo/odoo/commit/5245ec39a12e7d3a10fcc4c2c92b0f7dbf52d3be

[this second commit]: https://github.com/odoo/odoo/commit/4290724a4c8c57fba4f4d3d688d38f65dadcc38f

[1]: https://github.com/odoo/odoo/blob/9e3fc9568fcebcb1de6486d2ab7134e8a12087b7/addons/web/static/src/views/fields/translation_button.js#L23

[2]: https://github.com/odoo/odoo/blob/9e3fc9568fcebcb1de6486d2ab7134e8a12087b7/addons/web/static/src/views/fields/translation_button.js#L24-L26

[3]: https://github.com/odoo/odoo/blob/9e3fc9568fcebcb1de6486d2ab7134e8a12087b7/addons/web/static/src/views/fields/translation_button.js#L29-L41

sentry-7384270487

closes odoo/odoo#267914

Signed-off-by: Aaron Bohy (aab) <aab@odoo.com>