[FIX] website_sale_stock: products in multiple warehouses
- Create 2 warehouses A & B
- In the website settings, set the `inventory_availability` as `always`,
  but do not set a warehouse
- Create a Product P, make some stock in warehouse A
- Create a Product Q, make some stock in warehouse B
- Publish the products
- Go to `/shop` => both products have availability
- Add P in the cart => it works
- Add Q in the cart

Error: 'Some products became unavailable and your cart has been
updated...'.

This happens because the availability is checked on the warehouse of the
SO, not the warehouse of the website (not set in this case).

opw-2361768

closes odoo/odoo#60829

Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>