[FIX] website: raise validation on invalid domains
Currently, an error occurs when user tries to give a domain that has both arabic
and latin script letters.

Steps to replicate:
- Install `website` and open settings.
- Under the domain field give `https://pثا.com` and save.
- Open website (only if version below `saas-19.4`).

Error (saas-19.4):
```
  File '/home/odoo/odoo19/community/odoo/addons/base/models/ir_http.py', line 281, in _filter_domain
    url1 = parse_url(website.domain if '://' in str(website.domain) else f'//{website.domain}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File '/home/odoo/odoo19/myenv/lib/python3.12/site-packages/urllib3/util/url.py', line 451, in parse_url
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: https://pثا.com
```

Error (below saas-19.4):
```
UnicodeError: Violation of BIDI requirement 2
encoding with 'idna' codec failed
```

Cause:
- The website domain validation does not reject domains containing invalid
  internationalized hostname labels.
- As a result, an invalid domain (e.g.`https://pثا.com`) can be saved in
  the database.
- Later, when we try to parse the configured website domain to determine the
  matching website for an incoming request, the invalid hostname raises an
  error from the line [1] (in saas-19.4 ), causing the request to fail.

Solution:
- Use `urllib3.parse_url()` for website domain validation since it covers the
  existing validation while also validating internationalized hostnames. Invalid
  domains now raise a `LocationParseError`, which is converted into a
  `ValidationError` to prevent them from being saved.

- Please refer to [this] documentation for reference
  (especially the `Guideline Rules for writing Arabic Labels`, Rule-2).

[this]: https://help.nic.sa/en/guidelines-for-writing-arabic-idn/

[1]: https://github.com/odoo/odoo/blob/40538eb7e9890aafb88ec7626032bae1e06dbf6f/odoo/addons/base/models/ir_http.py#L281

sentry-7619224790