[FIX] l10n_fr_pdp: traceback on batch invoice sending
Sending several invoices at once from the list view of a French company
crashes instead of opening the batch sending wizard.

Steps to reproduce:

- Activate French Electronic Invoicing
- Create a French customer with a valid PDP endpoint
- Post two invoices for that customer, select them in the invoice list
  and click 'Send'

Issue:

The batch sending wizard raises
```
  AttributeError: 'account.move.send.batch.wizard' object has no
  attribute 'company_id'
```

opw-6558940

closes odoo/odoo#289547

Signed-off-by: Sven Führ (svfu) <svfu@odoo.com>