[FIX] hr_expense: update sheet's state when posting AM again
When posting again an account move related to an expense, the sheet's
state and the expense's state won't be updated

To reproduce the issue:
1. Create an expense
   - Paid By: Company
2. Create the related report
3. Submit to manager, Approve, Post Journal Entries
4. Open the related journal entry
5. Reset & Post

Error: States of both expense and sheet are incorrect (sheet:
"Posted" instead of "Done", expense: "Approved" instead of "Paid")

The state of the expense depends on the one of the sheet:
https://github.com/odoo/odoo/blob/1c517b6e67127971f343ffac0a4c29d684c8c13e/addons/hr_expense/models/hr_expense.py#L141-L153

The state of the sheet is manually written, each time the user does
an action. For instance, when posting the journal entries from the
sheet, we update the state of the sheet (which will change the state
of the expense, as shown in the above `compute`)
https://github.com/odoo/odoo/blob/1c517b6e67127971f343ffac0a4c29d684c8c13e/addons/hr_expense/models/hr_expense.py#L642-L643
https://github.com/odoo/odoo/blob/1c517b6e67127971f343ffac0a4c29d684c8c13e/addons/hr_expense/models/hr_expense.py#L1164-L1165

Same thing will happen when resetting the AM to draft:
https://github.com/odoo/odoo/blob/f6a13938f904f275b0360507b7ec987ef3bc2ddc/addons/hr_expense/models/account_move.py#L16-L20

But here is the issue: nothing updates the expense/sheet states when
posting again the AM

OPW-3322836

closes odoo/odoo#131060

Signed-off-by: Josse Colpaert <jco@odoo.com>