[FIX] account: prevent an error when print and send an invoice
Currently, an error occurs when attempting to print and send an invoice that is
in a draft state and the invoice's name is not available.

Step to produce:

- Install the 'account' module.
- Go to Invoicing / Customers / Invoices, Create one invoice without a customer
and invoice line, and come to the list view of Invoices.
- Select this invoice and click on 'Print & Send'.

AttributeError: 'bool' object has no attribute 'replace'

The issue occurs because the system attempts to replace the name at [1] to
generate a PDF file name. But the invoice's name is not available.

Link [1]: https://github.com/odoo/odoo/blob/41de88b930e569daea7624ee3655cef218f9136f/addons/account/models/account_move.py#L5739

To resolve this issue, Raise a user error if the user attempts to select the
'Print & Send' action on an invoice that is not in the confirmed state.

Sentry-6185757435

closes odoo/odoo#195330

X-original-commit: bcab59b0dff275eab1e739670dcd3f7497827aee
Signed-off-by: Ruben Gomes (rugo) <rugo@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>