[FIX] website_blog: prevent error when there is invalid url
Steps to reproduce:
- Install 'website_blog' module(with demo data)
- Change URL (eg: /blog/tag/hotels)

Traceback:
AssertionError: Invalid falsy real id

We are encountering this error because [active_tag_ids] contains '[None]', and
falsy IDs are no longer allowed in browse().

[active_tag_ids]: https://github.com/odoo/odoo/blob/4e4d1dba32ef45567eda004fc1a3584591508720/addons/website_blog/controllers/main.py#L83

sentry-7289765426

X-original-commit: fe8211f2033a6126772154f5292756ce02174384