[FIX] mail: guard against chat bubble no thread
There are some rare cases there's a chat bubble
but no thread, e.g. when the thread is deleted and/or
data hasn't be fetched (yet).

These cases should assume no thread for a short time
instead of following crash:

```
TypeError: Cannot read properties of undefined (reading 'importantCounter')
```

closes odoo/odoo#215112

X-original-commit: 12893d39d6bd3029504aacc07b148bfd5046f4f5
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>