[FIX] l10n_eg_edi_eta: Fix JSON decode error
Using the “Get ETA Invoice PDF” button located on the form view of invoices can result in a stacktrace error.

Since installing  with python 3.10, and using:

requests.exceptions.JSONDecodeError

Will raise the following error:

AttributeError: module 'requests.exceptions' has no attribute 'JSONDecodeError'

This change fixes the error by using  from the package.

Related: https://github.com/odoo/odoo/commit/8d1f2de373b66c9229eb9497efa854cf5c88d9a5

opw-6275476

closes odoo/odoo#268920

Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>