[FIX] sale: prevent error when changing the quantity of a combo product so line
Currently, an error occurs when a user changes the quantity of a combo product.

Steps to Reproduce:

 - Install the sale_management module.
 - Go to Combo Choices and create two combo choices, each with at least
   one product.
 - Go to Products and create a product with type Combo, then add both combo
   choices to it.
 - Go to Quotations and create a new quotation. Add the newly created combo
   product in the order line.
 - Now, go back to the combo product and remove one of the combo choices
   from it.
 - Return to the quotation and change the quantity of the combo product in the
   sale order line.

KeyError: product.combo(6,)

After [this commit], when a user adds a combo product in a sale order line, the
dialog for selecting single-choice options in the combo no longer opens.
Starting from version 19.0, if a user wants to increase the quantity, they can
do it directly from the order line.
However, if a user deletes one of the combo choices from the combo product
and then tries to increase the quantity of the combo product order line, the
compute method runs to update the sale order line price — including the
removed combo choice product. In the combo_prices[1], it contains a record
of the current combo choices, and when it tries to access the removed combo
choice from it, it raises an error [2].

This commit ensures that if a user removes a combo choice from a combo
product and then updates the quantity of the combo product line, the
quantity of the removed combo choice order line is set to zero.

[this commit]: https://github.com/odoo/odoo/pull/194496/commits/4a96d35655edd2ea94833dad0a335d26fa8e7c89

[1]: https://github.com/odoo/odoo/blob/257537584bedc1ab7db1bdc700f89145a3bb6095/addons/sale/models/sale_order_line.py#L736

[1]: https://github.com/odoo/odoo/blob/257537584bedc1ab7db1bdc700f89145a3bb6095/addons/sale/models/sale_order_line.py#L757

sentry-6952615636