[FIX] l10n_ro_edi_stock: conditionally checked if the module is installed in the test
The test was failing when the module was not installed because it was
trying to access the auto_batch field but AttributeError: 'stock.picking.type' object has no attribute 'auto_batch'
, because we need to install the module to have the field available which is stock_picking_batch module.

task-115361 (related to task)

closes odoo/odoo#200964

Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>