[FIX] pos_hr: prevent singleton error during batch write
Since odoo/odoo@ab3fddb58f4329f4d95d45e0fbccec8c690a18fb,
the write method uses `with_company(self.company_id)`.
If `write` is called on a recordset containing multiple POS config
belonging to diff companies, a ValueError (Expected singleton) is raised.

This scenario occurs when saving Settings (res.config.settings). The
`set_values` method[^1] in `point_of_sale` can trigger a batch write on
multiple `pos.config` records (e.g., when updating `cash_rounding`).

```py
  File "/home/odoo/src/odoo/19.0/addons/point_of_sale/models/res_config_settings.py", line 202, in set_values
    ]).cash_rounding = False
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1845, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/src/enterprise/19.0/pos_urban_piper/models/pos_config.py", line 114, in write
    res = super().write(vals)
  File "/home/odoo/src/odoo/19.0/addons/pos_self_order/models/pos_config.py", line 187, in write
    res = super().write(vals)
  File "/home/odoo/src/odoo/19.0/addons/pos_restaurant/models/pos_config.py", line 51, in write
    return super().write(vals)
  File "/home/odoo/src/odoo/19.0/addons/pos_hr/models/pos_config.py", line 25, in write
    group_users = self.sudo()._get_group_pos_manager().with_company(self.company_id).user_ids.filtered(
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 6005, in with_company
    company_id = int(company)
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 6655, in __int__
    return self.id or 0
  File "/home/odoo/src/odoo/19.0/odoo/orm/fields_misc.py", line 114, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: res.company(1, 3, 7, 4, 11, 8)
```

This patch ensures the company-dependent logic is executed per-record.

opw-6013433
upg-3949467

[^1]: https://github.com/odoo/odoo/blob/19.0/addons/point_of_sale/models/res_config_settings.py#L194-L202