[FIX] account: prevent error on opening Analytic Distribution
Currently, an error occurs when a new company is created without selecting a
'Fiscal Localization', and then both companies are selected while creating a
new 'Analytic Distribution'.

Steps to reproduce:
- Install 'Accounting' module
- Enable 'Analytic Accounting'
- Create a New company and switch to it
- Select both companies and Open 'Analytic Distribution' and click 'New'

Traceback:
TypeError: 'bool' object is not subscriptable

At [1], we are searching by 'account_type', but if 'Fiscal Localization' is not
set for the current company, there will be no records in 'account.account'.
However, due to the multi-company setup, it still return accounts from the
first company. In such cases, the 'code' field is empty, which causes the 'code'
to be treated as False.

[1]: https://github.com/odoo/odoo/blob/d155edfd729ab9b53f38939fe24b6d1e7b578083/addons/account/models/account_analytic_distribution_model.py#L55-L58

sentry-6754820454

X-original-commit: 8ad3ac312384f04ada5000f54188cfa810e1a403