[FIX] l10n_ee: wrong parameter passed in try_loading
- In version 18, the force_create parameter was introduced in the try_loading
  method.
https://github.com/odoo/odoo/pull/198030/commits/8153a957746d7ad11db5df743a948c471d828f15
  Therefore, the upgrade fails when try_loading with the force_create parameter
  is used in version 17.
https://github.com/odoo/odoo/pull/223405/files#diff-25bc11e6653e875717f3a1c96d0773f08c59c68d0290011f217c7e877fb06d0b
  In version 17, this parameter is not available for the try_loading method.
https://github.com/odoo/odoo/blob/17.0/addons/account/models/chart_template.py#L131

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 519, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 221, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 239, in exec_script
    migrate(cr, installed_version)
  File "/home/odoo/src/odoo/17.0/addons/l10n_ee/migrations/1.3/end-migrate_update_data.py", line 7, in migrate
    env['account.chart.template'].try_loading('ee', company, force_create=False)
TypeError: AccountChartTemplate.try_loading() got an unexpected keyword argument 'force_create'

```

upg-3164417
tbg-2185