[FIX] mrp,{purchase,sale}_stock,stock: handle assigning multiple stock reference
Currently an error occurs when there are multiple stock references of same name,
and user assigns references on Reception report.

Steps to replicate:
- Install `sale_stock`.
- Load Demo data from Settings.
- Go to settings and check `Reception Report`.
- Go to Operations > Reference > S00004 > Duplicate it (from the form view).
- Open Receipts > WH/IN/00002 > Allocation (Smart button) > Click 'Assign All'
  or the S00004 line.

Error:
```
File "/home/odoo/odoo18/community/addons/stock/report/report_stock_reception.py", line 271, in action_assign
    self._action_assign(in_move, out)
  File "/home/odoo/odoo18/community/addons/stock/report/report_stock_reception.py", line 343, in _action_assign
    in_move._get_source_document()._add_reference(out_ref)
  File "/home/odoo/odoo18/community/addons/stock/models/stock_picking.py", line 2102, in _add_reference
    self.move_ids.reference_ids = [Command.link(reference.id)]
  File "/home/odoo/odoo18/community/odoo/orm/fields_misc.py", line 112, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: stock.reference(3, 19)
```

Cause:
- As the user duplicated the record, there were two records received in the
  variable `reference` at [1] that caused the expected singleton error.

Solution:
- The methods `_add_reference()` and `_remove_reference()` can now handle
  multiple reference records.

[1]: https://github.com/odoo/odoo/blob/4b2154870eebcce449f53d8f593386ae6af04a83/addons/sale_stock/models/sale_order.py#L329

sentry-6982131891

closes odoo/odoo#237860

X-original-commit: 70308b37545a06afea6553c50b3211f767a613f9
Signed-off-by: William Henrotin (whe) <whe@odoo.com>