[FIX] l10n_in_ewaybill: fix traceback while unlinking attchments
Currently, a traceback is occurring when the user tries to unlink
an attachment.

To reproduce this issue:

1) Install `l10n_in_ewaybill`
2) Try to unlink any attachments from `settings/technical/attachments`

Error:-
"AttributeError: 'super' object has no attribute '_unlink_except_government_document'"

This error was occurring because of the latest changes from the below commit.

https://github.com/odoo/odoo/pull/195701/commits/f2a5024f6fb43110e1f0672db89df7c67f54412d

Here the method `_unlink_except_government_document` is actually defined
in the `account_edi` module.

But in the above commit a super call was used in `l10n_in_ewaybill`.
Which is not dependent on `account_edi` directly or indirectly.

This will lead to the above traceback.

sentry-6272499414

closes odoo/odoo#197813

X-original-commit: e983b466d4b0f24bc6410a9394d122c9371b6e66
Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>