[FIX] mail: hide unfollow button if mail delivery fail
When the user clicks the email's Unfollow button, an error traceback will show
up.

Step reproduce :
 1. Install the Discuss, Sales
 2. Open Sale Order> Click on the Send by Email Button > Send.
    (Send record Delivery Failed due to SMTP config, not set up)
 3.Open Settings > Techincal >Email > Emails.
 4. Open Email record. > See UnFollow Button in the Body Of Email Template.
    (Footer of Body or Right side of Powered by Odoo )
 5 . Click the Unfollow Button.

Error:
TypeError :-MailController.mail_action_unfollow() missing 4 required positional
            arguments: 'model', 'res_id', 'pid', and 'token'

While Clicking on unfollow Button, at that times argument data is not prepared
due to that data preparing in real-time so for that we should do the  SMTP
Config for getting the value of that function argument.

sentry-3965574308