[FIX] website_event_track: fix track proposal submit with speaker image
Followup of odoo/odoo@41fe2ebdb9cc.

Before this commit, when trying to submit a track proposal with a
speaker image, the request failed with:

```
TypeError: event.track.image: use BinaryValue instead of bytes
```

closes odoo/odoo#274366

Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>