Cherry pick of 1de496502fb0015eed1611fb74dd3a238c0d144d failed
stdout:
Auto-merging odoo/addons/base/tests/common.py
Auto-merging odoo/addons/base/tests/test_base.py
CONFLICT (content): Merge conflict in odoo/addons/base/tests/test_base.py
Auto-merging odoo/addons/base/tests/test_ir_actions.py
Auto-merging odoo/addons/base/tests/test_ir_model.py
Auto-merging odoo/addons/base/tests/test_osv.py
Auto-merging odoo/addons/base/tests/test_views.py
CONFLICT (content): Merge conflict in odoo/addons/base/tests/test_views.py
Auto-merging odoo/addons/test_main_flows/tests/test_flow.py
Auto-merging odoo/addons/test_new_api/tests/test_new_fields.py
Auto-merging odoo/addons/test_read_group/tests/test_m2m_grouping.py
Auto-merging odoo/tests/common.py

stderr:
19:18:02.020581 git.c:463               trace: built-in: git cherry-pick 1de496502fb0015eed1611fb74dd3a238c0d144d
error: could not apply 1de496502fb0... [FIX] base: Make tests demo data independent
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: