[FIX] web: prevent crash when using invalid args in name_search
The system crashes with an error when attempting to scan a barcode. because
`name_search` expects `domain` and it gives `args`.

Error:-
`TypeError: ProductProduct.name_search() got an unexpected keyword argument
'args'`

Sentry - 6388425767