[FIX] google_calendar: avoid cancelling missing events
For some reason, this module was trying to cancel unexisting events. That's solved now. See the traceback:

```
2023-10-11 11:29:44,750 242 ERROR odoo odoo.addons.google_calendar.models.res_users: [res.users(2,)] Calendar Synchro - Exception : El registro no existe o ha sido eliminado.
(Registro: calendar.event(11,), Usuario: 2) !
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 891, in get
    return field_cache[record._ids[0]]
KeyError: 11
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1082, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 894, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'calendar.event(11,).user_id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/google_calendar/models/res_users.py", line 91, in _sync_all_google_calendar
    user.with_user(user).sudo()._sync_google_calendar(google)
  File "/opt/odoo/auto/addons/google_calendar/models/res_users.py", line 70, in _sync_google_calendar
    synced_events = self.env['calendar.event']._sync_google2odoo(events - recurrences, default_reminders=default_reminders)
  File "/opt/odoo/auto/addons/google_calendar/models/google_sync.py", line 172, in _sync_google2odoo
    cancelled_odoo._cancel()
  File "/opt/odoo/auto/addons/google_calendar/models/calendar.py", line 279, in _cancel
    my_cancelled_records = self.filtered(lambda e: e.user_id == user)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5517, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5517, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/opt/odoo/auto/addons/google_calendar/models/calendar.py", line 279, in <lambda>
    my_cancelled_records = self.filtered(lambda e: e.user_id == user)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2615, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1112, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: El registro no existe o ha sido eliminado.
(Registro: calendar.event(11,), Usuario: 2)
```

@moduon MT-3925