[FIX] website_sale: prevent error when updating quantity in cart
This error occurs when attempting to update the quantity in the cart.

Steps to Reproduce:
- Install the 'website_sale' module
- Activate 'Demo' payment provider
- Go to Website > Shop > Add a product to Cart > View cart
- Pay with Demo > Pay
- Click the back button(chrome navbar)(Instantly)
- Change the quantity for the product

Traceback:
ValueError: Expected singleton: sale.order()

At [1], this error occurs because 'order_sudo' is empty. This happens when
there are no products in the cart — typically because, upon clicking "Pay",
a sale order is created for the product, and when the user navigates back, the
cart is empty.

[1]- https://github.com/odoo/odoo/blob/a8a7a26dbda046db6f679bc29940add510e34485/addons/website_sale/controllers/cart.py#L248

sentry-5682671428