[FIX] account_payment: prevent removing active payment journal
Versions
--------
- 17.0+

Steps
-----
1. Have an active payment provider;
2. create a branch company;
3. set payment provider's company to branch;
4. leave Payment Journal unchanged (parent company Bank);
5. go to Accounting / Configuration / Accounting / Journals;
6. open Bank journal;
7. open "Incoming Payments" tab;
8. enable the "Payment Provider" column;
9. unset the payment provider on the active provider's line & save;
10. attempt paying using the provider.

Issue
-----
> Error: psycopg2.errors.NotNullViolation:
> null value in column "journal_id" of relation "account_payment"
  violates not-null constraint

Cause
-----
We shouldn't be able to change the related journal of active providers.

Solution
--------
Make the field read-only if the payment method is active.

opw-5045000

X-original-commit: 811eea042d2651b4c9c52e83998c737191ce13f7