[FIX] purchase: allow printing multiple po foreign currency
The issue: Printing multiple purchase orders with a currency different from the company’s caused a traceback:
  File "/data/build/odoo/addons/purchase/models/purchase_order.py", line 235, in _compute_tax_totals
    order.tax_totals['amount_total_cc'] = f"({formatLang(self.env, self.amount_total_cc, currency_obj=self.company_currency_id)})"
  File "/data/build/odoo/odoo/fields.py", line 1204, in __get__
    record.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5979, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: purchase.order(23, 22)

How to reproduce the issue:
Go to the purchase module, select POs with different currencies, try to print them in bulk.

The issue:
The `amount_total_cc` was computed using the `self` recordset instead of individual records.

opw-4292675

X-original-commit: 6417087e8d5d370e03bf9a36c29cc4314d59ccaf