[FIX] web_tour: fix run tours when JS bundle is not loaded
There is an issue with the POS since 19.3, when a tour is running, the
tour service would get the tour name from the backend with 0 steps, and
because the JS bundle of the tours is not loaded by the POS frontend the
tour would continue with 0 steps.

Most of the time the currentActionIndex would be > 0, so the check on
line 87 of `tour_interactive.js` would pass
```
if (this.currentActionIndex === this.actions.length)
```
and later run into a
```
TypeError: Cannot read properties of undefined (reading 'step')
      at TourInteractive.play (http://localhost:8069/web/assets/debug/point_of_sale.assets_prod.js:121705:33) (/web_tour/static/src/js/tour_interactive/tour_interactive.js:95)
      at TourInteractive.start (http://localhost:8069/web/assets/debug/point_of_sale.assets_prod.js:121655:14) (/web_tour/static/src/js/tour_interactive/tour_interactive.js:45)
      at TourService.resumeTour (http://localhost:8069/web/assets/debug/point_of_sale.assets_prod.js:123226:39) (/web_tour/static/src/js/tour_service.js:260)
```

I'm not sure what's the correct fix,
- either what I did here
- change the condition on the `play()` to `this.currentActionIndex >=
this.actions.length` instead of `this.currentActionIndex ===
this.actions.length`
- bundle the tours inside the POS front end (although they are not used
  there so it seems unnecessary)