[FIX] stock, mrp_workorder: add quantity field dependency lot gen
Steps to Reproduce :

1. Install MRP.
2. Create a Bill of Materials (BOM) and add a component with lot tracking.
3. Create and confirm a Manufacturing Order (MO) with BOM.
4. Navigate to the shop floor and click on Generate Serials/Lots.
5. The error appears when trying to generate the lot .

Issue :

Error raised when try to Generate Serials/Lots during the manufacturing
process.

TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

Causes:

This error occurs because the quantity field is undefined when
Generate Serials/Lots is triggered, the quantity field is not being passed in
the context, and its value is undefined, which is leading to a division by none.

Solution:

To fix this, we added the stock move’s demand quantity as a fallback.
This ensures the quantity field value is present and its value
correctly passed during lot generation.

Second issue:

Steps to reproduce:

- In the settings enable workorders and serial numbers
- Inventory > Configuration > Warehouse Management > Operations Types
- Modify the manufacturing type to "Create New Lots/Serial Numbers"
- Create a bom for a product P:
    - 1 x COMP tracked by lots consumed in an operation
- Create and confirm an MO for 1 unit of P
- Go to the shopfloor, remove the filters click on the component line
- Generate lot/serial numbers > Generate
> No new line was created

Cause of the issue:

Clicking on the component line will trigger a call of the
"action_show_details_quality_check" which will in turn open the
`mrp_workorder.view_stock_move_operations_quality_check` view.
However, this view displays  the "move_line_ids_picked" rather than the
"move_line_ids" if the product is tracked and if its picking type does
not prefill lots:
https://github.com/odoo-dev/enterprise/blob/96b1537236a74afd7f2a02c638a64f49ade583a5/mrp_workorder/views/stock_move_views.xml#L13-L18
This is problematic since the the Generate dialog will only update
the `move_line_ids` of the move and not its `move_line_ids_picked`.
In turn, the view will not notice any new "lines" and the new records
can not be created via the save button of the detailed operations.

opw-4763600

closes odoo/odoo#220303

X-original-commit: b126feb200aba6d5530ab8d4cf32e3a9d0c10a1b
Related: odoo/enterprise#90879
Signed-off-by: Lancelot Semal (lase) <lase@odoo.com>