[FIX] mail: prevent traceback on clicking 'Unfollow' in email footer
**Issue:**
Currently, a `typeError` occurs when clicking the `Unfollow` link in an email footer.

**Steps to Produce:**
- Create a meeting and add attendees (e.g., Marc Demo for demo data) using
  a calendar.
- Navigate to `Settings > Technical > Email > Emails`.
- Open the invitation email and click `Unfollow`
- Trackback occurs.

**Error Log:**
TypeError:MailController.mail_action_unfollow() missing 4 required positional
          arguments: `'model', 'res_id', 'pid', and 'token'`

**Root Cause:**
The /mail/unfollow route is being triggered without `'model', 'res_id', 'pid',
and 'token'` parameters at [1], causing an error.
[1]- https://github.com/odoo/odoo/blob/f3d000be70b1eb7b32ce6552900ecf126e1b116c/addons/portal/controllers/mail.py#L53

**Fix:**
This commit ensure that user will be redirected to a `Not Found` page, preventing an error.

sentry - 4952598215