[FIX] account: prevent an error when open a preview of invoice
Currently, an error occurs when the user attempts to preview an invoice, and
invoice has no invoice lines.

Step to produce:

- Install the 'account' module.
- Create a new invoice, add a customer name, and 'Cancel' this invoice.
- Click on 'Preview' buttoon(ensure that no invoice lines have been added).

ValueError: Expected singleton: account.move()

An error occurs when the system tries to get installment data from the move line
at [1], and the move lines are not available in the invoice.

Link [1]:  https://github.com/odoo/odoo/blob/430656132044f8d675712d5b6cbfef807880d024/addons/account/models/account_move.py#L5411-L5412

To handle this issue, pass empty data for installments if the move line is
not available in the invoice.

Sentry-5978934688

closes odoo/odoo#185928

X-original-commit: 5087398657de448c24403ceaf69871956a2bf3bf
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>