Cherry pick of d87c0ba36a420c6f0b18f088c5c5769057b5ac72 failed
stdout:
Auto-merging addons/l10n_mx/i18n/l10n_mx.pot
CONFLICT (content): Merge conflict in addons/l10n_mx/i18n/l10n_mx.pot
Auto-merging addons/l10n_mx_hr/i18n/l10n_mx_hr.pot
CONFLICT (add/add): Merge conflict in addons/l10n_mx_hr/i18n/l10n_mx_hr.pot

stderr:
16:14:40.714148 git.c:463               trace: built-in: git cherry-pick d87c0ba36a420c6f0b18f088c5c5769057b5ac72
error: could not apply d87c0ba36a42... [I18N] l10n_mx*: update pot files
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: