[FIX] base: make update_path required for 'Update Record' server actions
Currently, an error occurs when a user changes the `Type` of a server action to
`Update Record` and save it without specifying an update field, and then
triggers that action.

**Steps to produce:**

- Install the `accountant` and `documents` modules and enable developer mode.
- Navigate to `Settings > Technical > Actions > Server Actions`.
- Open the action `Create vendor bill`, change its `Type` To `Update Record` and click Save.
- Navigate to `Documents > Company > Finance`.
- Open any PDF and click `Create vendor bill`.

**Error:**
`AttributeError: 'bool' object has no attribute 'split'`

**Root Cause:**
At [1], the `update_path` field is expected to be a string for `split()`, but
when no value is provided, it is False, resulting in an AttributeError.

[1]
https://github.com/odoo/odoo/blob/9dac8d0204011ca6b2b771f940a2331fd3625b88/odoo/addons/base/models/ir_actions.py#L701

This commit ensures that the `update_path` field is mandatory when the server
action type is set to Update Record, by marking the field as `required` in the
form view. This prevents the action from being saved unless the update path is
configured.

sentry-6565012793