[FIX] hr_holidays: prevent error when creating time off request for an employee
Currently, an error occurs when creating a time off request for an employee.

Steps to Reproduce:

 - Install the hr_holiday module.
 - Go to Management > Time Off.
 - Create a new time off and remove the start date.
 - Now change the employee.

AttributeError: 'bool' object has no attribute 'date'

This error occurs when creating a time off request for an employee. If the
start date is removed and then the employee is changed, the compute
method [1] runs to determine whether the time off can be approved and to
update the states [2]. During this process, the system checks whether the
time off date is in the past, and since the start date is missing, it results in
the error [3].

This commit ensures that the system only checks whether the time off is in
the past when a start date is provided.

[1]: https://github.com/odoo/odoo/blob/aa53689d3c593a8a41479c51edc2b01e3c284f96/addons/hr_holidays/models/hr_leave.py#L594-L597

[2]: https://github.com/odoo/odoo/blob/aa53689d3c593a8a41479c51edc2b01e3c284f96/addons/hr_holidays/models/hr_leave.py#L1279

[3]: https://github.com/odoo/odoo/blob/aa53689d3c593a8a41479c51edc2b01e3c284f96/addons/hr_holidays/models/hr_leave.py#L1237

No Task ID

closes odoo/odoo#238281

Signed-off-by: Abdelrahman Mahmoud (amah) <amah@odoo.com>