[FIX] account: prevent error on creating invoice
Steps to reproduce:
- Install 'account' module
- Taxes > open any existing tax > Set 'factor_percent(%)' of repartition lines
  to negative(eg: https://www.awesomescreenshot.com/image/58851592?key=ce0017bb467a583ad020f33d21d4d8ba)
- Create a Invoice and add tax in move line and save

Traceback:
IndexError: list index out of range

We are getting 'factors' as empty because 'target_factors' from
'_add_accounting_data_to_base_line_tax_details' is empty.

This happens because, in 'tax_reps', we are filtering repartition lines with a
'factor' greater than '0'. However, when the 'factor' is less than '0',
'tax_reps' becomes empty, which leads to the error.

We are reverting this commit: https://github.com/odoo/odoo/pull/234334
because it prevents the validation error from being raised when there is a
negative value in the repartition lines.

[factors]: https://github.com/odoo/odoo/blob/de056cc784a3bbe2575fd3c9e81ca62e73c362d4/addons/account/models/account_tax.py#L1641

[tax_reps]: https://github.com/odoo/odoo/blob/de056cc784a3bbe2575fd3c9e81ca62e73c362d4/addons/account/models/account_tax.py#L2429-L2431

sentry-7102210210

X-original-commit: bc70917935271b4379381ca04713a042ced07f83