[FIX] stock: apply putaway rules on packaging
To reproduce the issue:
1. In Settings, enable:
   - Storage Locations
   - Units of Measure & Packagings
   - Packages
2. In uom list, edit Pack of 6:
   - Package type: Pallet
3. Create a putaway rules:
   - From: WH/Stock
   - Package type: Pallet
   - To: WH/Stock/Shelf 1
4. Create and confirm a receipt with one Pack of 6 of any product

Error: in the detailed operations of the SM, the destination
location is still WH/Stock. It should be the shelf.

A small mistake happened during the big refactoring of UoM and
packaging: commit [1] simply removed the use of the SM's packaging
instead of using the new field

[1] dc24a1d1c93cf6eeb6456b1591a0ab8ccc4086ba

OPW-4750639

X-original-commit: 4231ffe3d8d0a7a6403fa0185437338d0af6a515