[FIX] website: error when saving page without URL
Before this commit, when trying to save a website page without an URL
set, the following error was raised:

    AttributeError: 'bool' object has no attribute 'startswith'

The above is because the URL is automatically formatted to add a
leading slash when it's missing, but it didn't handled properly empty
URLs.

This commit ensures such case is handled properly.