Cherry pick of 779a6875ea48299236573a6895c22f209f07ff31 failed
stdout:

stderr:
error: could not apply 779a6875ea4... [FW][FIX] mail: correctly check all recipients when routing on aliases
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'