[FIX] web: fix handling of dates field with group_operator in grouped list
Trying to group a list view with a date or datetime field having a
group_operator defined will raise the followup crash:

Error:
TypeError: value.format is not a function

Traceback:
formatDate@http://localhost:8069/web/static/src/js/fields/field_utils.js:118:18
_renderAggregateCells/<@http://localhost:8069/web/static/src/js/views/list/list_renderer.js:236:38

This is because the field format method expect a moment object, not a string
value; so we ensure to parse the server value when computing aggregates.

OPW-1969482