[FIX] auth_ldap: traceback during installation due to invalid view
This is an oversight in odoo/odoo#106425

`<div name="auth_ldap_right_pane">`
has been replaced by
`<setting ... id="oauth">`

But, in the `auth_ldap` module,
the view has not been adapted to replace the selector
`<div name='auth_ldap_right_pane' position="inside">`

Therefore leading to the below exception

```
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/master/addons/auth_ldap/views/res_config_settings_views.xml:3
Error while validating view:

Element '<div name="auth_ldap_right_pane">' cannot be located in parent view
```

This is most-likely because the runbot doesn't install `auth_ldap`
and therefore doesn't test it.

I take the opportunity of the commit to better name this setting
section, from `id="oauth"` to `id="module_auth_ldap"`,
first because "oauth" is not "ldap",
second to make the naming uniform compared to the other setting section
id names.