[FIX] account_edi_ubl_cii: prevent an error when confirm an invoice
Currently, An error is generated when confirming an invoice, and Country
Group  name  Europe is not available

Steps to reproduce:

- Install an 'account_reports' module.
- Navigate to Contacts / Configuration / Localization / Country Group, And
Delete the country group name 'Europe'.
- Create a new tax, add name,  amount, and set tax scope as goods.
- Create an invoice and confirm it.

ValueError: External ID not found in the system: base.europe

An error occurs when the system tries to retrieve an external id of the country
group name Europe at [1], but it is not available.

Link [1]: https://github.com/odoo/odoo/blob/64a4ca83cd9b2f208c555942346bb62e31825266/addons/account_edi_ubl_cii/models/account_edi_common.py#L155-L156

To handle this issue, add 'raise_if_not_found=False' in ref() so that when
country group name Europe is not available it will return a None value instead
of traceback.

Sentry-5851989243