[FIX] core: avoid "studio_customization" from module list
Step to reproduce:
- start a fresh db, install studio and pos
- using studio, edit any view (add or remove a field)
- run any tour

Observation:
- we are not able to run any tour
Traceback
```
File "/home/odoo/odoo/codebase/odoo/18.0/odoo/addons/base/models/ir_qweb.py", line 2703, in _get_lazy_bundles_from_js
    for fname in glob.iglob('**/static/src/**/*.js', root_dir=modroot, recursive=True):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/glob.py", line 46, in iglob
    root_dir = os.fspath(root_dir)
               ^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not bool
```

Cause:
- `_get_lazy_bundles_from_js` fetches module path for all installed module in
addons
- in case we have a view edited, we get the `studio_customization` as
installled module, which doesn't have any path in addons. i.e. False

Fix:
- filter out such pseudo-modules from the list

X-original-commit: 6adcbb13218cf114055c871340883a2f2c1f1105