[FIX] tools: traceback in sending E-invoice to SII (ES)
With ES Company setup
In Settings > Registro de Libros connection SII select a Tax Agency and
enable 'Test' flag
Create a new invoice
Process EDI

Traceback - AttributeError: 'Client' object has no attribute 'bind'
It occurs because in our wrapper of Zeep the bind method is missing

opw-3888556
opw-3885287
opw-3888257
opw-3888559
opw-3888155