[FIX] l10n_sa_edi: prevent error while updating demo data
Currently, error occurs when user tries to install Saudi Arabia EDI module.

Steps to replicate:
- Install `l10n_sa` with demo and switch to SA company.
- Open Invoices > `INV/2026/00001` > Reset to draft  > Delete.
- Open Invoices > `INV/2026/00002` > Reset to draft  > Delete.
- Install `l10n_sa_edi`.

Error:
```
File '/home/odoo/src/odoo/saas-19.2/addons/l10n_sa_edi/demo/account_demo.py', line 16, in _l10n_sa_edi_onboard_sa_sale_demo
    self.ref('demo_sa_invoice_1', raise_if_not_found=False)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

```

Cause:
- As the user deleted `INV/2026/00001` (linked to `demo_sa_invoice_1`) and
 `INV/2026/00002` (linked to `demo_sa_invoice_2`), [here] when we try to
  create a recordlist to update we get this error.

Solution:
- Avoided direct concatenation of `self.ref(...)`, which may return None.

- Iterated over the expected IDs, fetched records safely, and skipped
  missing ones before processing.

[here]: https://github.com/odoo/odoo/blob/b8bcaa6af2531f49654d804231942b6af2261933/addons/l10n_sa_edi/demo/account_demo.py#L15-L20

sentry-7458234787

X-original-commit: 7003088775dd53f36406a37d44a3e89ca42e1266