[FIX] account: Allow users to edit subview list with studio
Steps to reproduce:

* Install `web_studio` and `account`
* Open customers/invoices
* Edit view form with studio
* click on subview list
* click edit
* traceback

```
TypeError: Cannot read properties of undefined (reading 'state')
    get isProductClickable()
    /account/static/src/components/product_label_section_and_note_field/
        product_label_section_and_note_field.js:188
```

To get fields from the parent view, we need to use evalContext instead
of `model.root`.

opw-4148174

closes odoo/odoo#179408

X-original-commit: 4b8ef2ae36c57344a82827324a741174f14601ff
Signed-off-by: Florian Gilbert (flg) <flg@odoo.com>