[FIX] web: avoid traceback in kanban quick_create if RPC error
steps to reproduce:
- open the fleet app, default view is a kanban view of vehicles
- create a new vehicule using the kanban quick create
- click on edit

before this commit:
a combination of unfortunate events:
- fleet does not handle well quick create as it always lead to a (silent)
error because model_id is required and not set in the kanban quick create
- a dialog form is created and quickly destroyed, which leads to an error

error_service.js:72 Error: Component is destroyed
    at RequestBatcherORM.rpc (hooks.js:170:1) (/web/static/src/core/utils/hooks.js:170)
    at RequestBatcherORM.call (orm_service.js:109:1) (/web/static/src/core/orm_service.js:109)
    at Record._onChange (relational_model.js:1256:1) (/web/static/src/views/relational_model.js:1256)
    at Record.load (relational_model.js:835:1) (/web/static/src/views/relational_model.js:835)
    at http://localhost:8069/web/assets/debug/web.assets_backend.js:53252:77 (web/static/src/views/relational_model.js:1901)
    at always (concurrency.js:96:1) (/web/static/src/core/utils/concurrency.js:96)

after this commit:
the fleet quick create still silently breaks but there is no error since
we only try to open the record in the form view if it has been created in
database.

note: there is no error since refactoring in 067bcac (16.3)

opw-3451913