[FIX] hr_recruitment: prevent error when refusing duplicate application
When the user refuses the application with its duplicate application,
a traceback will appear.

Steps to reproduce the error:
- Go to Recruitment > All Applications >
  Create 2 applications with the same candidate
- Open that application > Refuse > Select refuse reason >
  Select other Duplicate application > Refuse

Error: A traceback appears:
"AttributeError: 'hr.applicant' object has no attribute
'_get_similar_applicants_domain'"

https://github.com/odoo/odoo/blob/e4a4806e5c58c599815204a73c78a228ee230613/addons/hr_recruitment/wizard/applicant_refuse_reason.py#L75
"_get_similar_applicants_domain" method is removed in
this commit 9359d08d331beac389fde0e6c82c895341f7dbc5 but still used here.
So, it will lead to the above traceback.

sentry-5986653915