[FIX] l10n_dk_nemhandel: fix traceback on timeout
In case of timeout when sending an invoice there is a traceback
due to the following error.
```
AttributeError: 'UserError' object has no attribute 'message'
```

It is fixed in this commit.

task-None

closes odoo/odoo#242906

X-original-commit: 292d52e39f8f31c867e3806dd93c533e85c237ea
Signed-off-by: Wala Gauthier (gawa) <gawa@odoo.com>
Signed-off-by: Sven Führ (svfu) <svfu@odoo.com>