[FIX] l10n_ar_website_sale: prevent error while opening account detail in portal
Currently, an exception was generated when the user tries to open their
account details in the portal (url: my/account)

error: `KeyError: 'partner_sudo'`

This error was generated because when the user tries to open their account
detail in the portal, we do not have 'partner_sudo'.

Recentley refacto code with [1] replaced `partner` with `partner_sudo` for the
getting partner in the website sale address (`shop/address`) and we have the new
key because the template 'partner_info' called from template 'address' see [2]
and `partner_sudo` set from [3] for address. But when we call the 'partner_info'
from template 'portal_my_details_fields' at [4], we do not have `partner_sudo`

This commit will fix the above issue by passing `partner_sudo` in the template
at the time prepare value for opening account detail in portal.

[1] - https://github.com/odoo/odoo/commit/c6e71c0b3df9fe6f01e932d0d1d23ee3f44012df
[2] - https://github.com/odoo/odoo/blob/3ea0c936c01a7c55ee8fa6ee64fd8e89b2a04f5f/addons/l10n_ar_website_sale/views/templates.xml#L60
[3] - https://github.com/odoo/odoo/blob/3ea0c936c01a7c55ee8fa6ee64fd8e89b2a04f5f/addons/website_sale/controllers/main.py#L1119
[4] - https://github.com/odoo/odoo/blob/3ea0c936c01a7c55ee8fa6ee64fd8e89b2a04f5f/addons/l10n_ar_website_sale/views/templates.xml#L68

sentry-5725856236

closes odoo/odoo#187594

X-original-commit: c514cb915697f19f42eaafd81d741e8ac2e17375
Signed-off-by: de Wouters de Bouchout Jean-Benoît (jbw) <jbw@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>