[FIX] stock: log cancel activity only if the move is linked to a picking
Steps to reproduce the bug:
- Unarchive the MTO route
- Create a storable product P1:
    - Route: MTO + Manufacture
    - BoM:
        - Component: 1 unit of X1

- Create a storable product X1:
    - Component: 1 unit of C1

- Create a manufacturing order for 1 unit of P1
- Confirm the MO
-> A child MO is created

- Try to cancel the MO for P1

Problem:
A traceback is triggered:
IndexError: tuple index out of range

'origin_picking': moves.picking_id[0],

Explanation:
When the parent MO is cancelled, all the moves linked to this MO are
cancelled (finished moves and raw moves). While cancelling them, an
activity of type "cancel" is logged on the pickings linked to these
moves (if any), in order to warn the user that actions may be required
on those pickings.

However, we do not check whether the moves actually have a picking
linked before logging the activity. The code directly tries to access
the first picking linked to the move, which triggers the traceback when
there is none:
https://github.com/odoo/odoo/blob/688528030215c20b33842ab03ebef3bbb51d5853/addons/mrp/models/stock_move.py#L442

When cancelling an MO, the method `_log_manufacture_exception` is already
called and logs an exception activity on the child MO.

Bug introduced by:
https://github.com/odoo/odoo/pull/254636/changes/7c68c3dbb29eaad4e09d59ef7c86bd525969caec

closes odoo/odoo#257011

Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>