[FIX] purchase_stock: Allow salesmen to confirm SOs that update PO lines
**Steps to reproduce:**

- Create a product with MTO route and a seller set.
- With a plain salesman user, create a sales order with that product
  and confirm it.
- Do a second sales order with the same product.
- Try to confirm it.

**Current behaviour:**

You get the following error:

```
odoo.exceptions.AccessError: You are not allowed to access 'Purchase Order Line' (purchase.order.line) records.

This operation is allowed for the following groups:
        - Accounting & Finance/Billing
        - Inventory/User
        - Purchases/Administrator
        - Purchases/User
        - Technical Settings/Show Accounting Features - Readonly
        - User types/Portal

Contact your administrator to request access if necessary.
```

**Expected behaviour:**

No error.

**Explanation:**

When a matching PO line is found, there's a request to a method for
getting the update vals using the PO line and other records (like
product.supplierinfo), that requires specific permissions that a
salesman doesn't have.

**Solution:**

Do whole operation with sudo. In fact, the write operation was done
already with sudo, but not the call to `_update_purchase_order_line`
method.

TT50492