[FIX] pos_restaurant,product: prevent parseerror when user deletes combo choices
Currently a Traceback occurs when the user deletes the combo choices.

Error: `ParseError: while parsing /home/odoo/src/odoo/saas-18.1/addons/
pos_restaurant/data/scenarios/restaurant_data.xml:607
A combo product must contain at least 1 combo choice.`

Steps to reproduce above error :-
- Install 'Point of Sale' application.
- Open POS and click 'Restaurant' button.
- POS > Products > Combo Choices, delete the combo choices.
- Now archive the 'Restaurant' in POS, again click 'Restaurant' and delete it.
- Open POS again and click 'Restaurant' button.
- The error appears in the log.

The error occurs because the user deleted combo choices, and when 'Restaurant'
is clicked again, it tries to access the deleted combo choices.

This commit fixes the error by checking if the master data is loaded again
thorugh the `context`.

sentry-6233666117