[FIX] payment_razorpay: prevent error on secret not existing
An error is expected to occur at line [1] if the secret is missing when a
transaction is processed through Razorpay and the page is redirected.

Error:
AttributeError:'bool' object has no attribute 'encode'

Solution:
* Added a check to log a warning and return None to abort
  signature calculation if the secret is missing similar to [2]

[1]: https://github.com/odoo/odoo/blob/bb37b3e320395c6e96b6a0c0c96367bd87d1c702/addons/payment_razorpay/models/payment_provider.py#L232
[2]: https://github.com/odoo/odoo/blob/bb37b3e320395c6e96b6a0c0c96367bd87d1c702/addons/payment_razorpay/models/payment_provider.py#L236-L238

Sentry-6767571136