Cherry pick of 673a66f5b81b36b2eef21153e2471f8d52bbf147 failed
stdout:

stderr:
17:35:39.225044 git.c:344               trace: built-in: git cherry-pick 673a66f5b81b36b2eef21153e2471f8d52bbf147
error: could not apply 673a66f5b81... [FIX] account: remove unused variables
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes odoo/odoo#79971

Related: odoo/enterprise#22324
Signed-off-by: Olivier Colson <oco@odoo.com>