[FIX] point_of_sale: Fix existing multiple refunded orders
In saas~17.1, the field `refunded_order_id` was changed from a Many2Many to a
Many2One, as refunding lines from different orders with the same order was no
longer possible.

The problem is that there were no changes applied to the existing data to
account for this, so databases with those kind of refunds will trigger an error
when the field is computed:
```
ValueError: Wrong value for pos.order.refunded_order_id
```

This behaviour can also break upgrades if the error happens during the mock
crawl test after the upgrade.

To reproduce:
	- In 17, create an order refunding products from different orders.
	- Upgrade to 18.
	- Try to view the refunding order.

closes odoo/odoo#236800

X-original-commit: a9e72a3e7f4ca82d6516126b49e44f8efd67aa71
Signed-off-by: Stéphane Vanmeerhaeghe (stva) <stva@odoo.com>
Signed-off-by: Agustín Castro Bugallo (agcb) <agcb@odoo.com>