[FIX] point_of_sale: change state of generate demo data button after first click
This error occurs when the user clicks multiple times on  the
`Generate demo data` button simultaneously.
Steps to produce:
- start the server without installing demo data.
- Install point_of_sale module.
- Go to point_of_sale > Delete all the products due to the visibility of
 `Generate demo data` button
- Go to dashboard > Click on new session > Open  a session
- Rapidly click on the `Generate demo data` button.
- Error will be generated.

Error: ParseError while parsing /home/odoo/src/odoo/saas 16.4/addons/
point_of_sale/data/point_of_sale_onboarding.xml:3, somewhere inside

To address this issue, we have changed the state of a button after the
first click. While users can still see the button after clicking it once, the
changed state of the button prevents the error from occurring.

sentry-4384327471

X-original-commit: 2463e8a64be035c7afb369afe305be887c60b750