[FIX] account_edi_ubl_cii: handle empty EndpointID
Description:
Importing a UBL file (vendor bill) fails if it contains an empty "EndpointID" node.
It assumes the node always contains text content to sanitize,but if it is empty,
it crashes with: AttributeError: 'NoneType' object has no attribute 'strip'.

Steps to reproduce:
1. Import a UBL as a bill, with an empty EndpointID node of the other party.
2. The import fails with the AttributeError.

opw-6246515

closes odoo/odoo#269755

X-original-commit: 72e3380b56576af1cf5402cc4b92524f670b60df
Signed-off-by: Claire Bretton (clbr) <clbr@odoo.com>
Signed-off-by: Mohamed Yousef Ahmed (myah) <myah@odoo.com>