[FIX] http: decode url in local_redirect and redirect_with_hash
From 2.0.0, werkzeug.utils.redirect uses html.escape  which expects 'str' instead of a bytes-like object.

Previous versions use its own escape which seems to handle either just fine.

Prevents exeption:

  File "/opt/odoo/odoo-14.0-dev/odoo/http.py", line 178, in redirect_with_hash
    return werkzeug.utils.redirect(url, code)
  File "/usr/lib/python3/dist-packages/werkzeug/utils.py", line 554, in redirect
    display_location = html.escape(location)
  File "/usr/lib/python3.10/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
TypeError: a bytes-like object is required, not 'str'