[FIX] sale_management: prevent error when updating SOL qty in portal
Currently, an error occurs when updating the quantity of an SOL in the portal.

Steps to Reproduce:
 - Install the sale_management module.
 - Go to Settings and enable Pricelists under Pricing.
 - Go to Sales > Orders > Orders and create a sale order.
 - Add an order line of type Section, click the three-dot menu on the line,
   and click Set Optional.
 - Add another line using Add a line and enter only the description in that line.
 - Save the order and click Preview.
 - Increase the quantity of the line using the + icon.

ValueError: Expected singleton: product.product()

After [recent commit], support for productless Sale Order Lines was added,
allowing users to create quotation/invoice lines directly from descriptions
without requiring a product. After [this commit], when updating the quantity
of a productless SOL in the portal, the price is updated based on the
pricelist [1]. While getting the pricelist price [2] for the SOL, the product is
ensured on the SOL, which raises the error [3] because the SOL does not
have a product.

This commit ensures that the unit price is updated based on the pricelist
only if the line contains a product.

[recent commit]: https://github.com/odoo/odoo/commit/d069ce59e28fda2bc25fb89fd01ee7b988a30fa0

[this commit]: https://github.com/odoo/odoo/commit/86d40fe5c5ad32af0ceca7cd384b96a8a2f4adc3

[1]: https://github.com/odoo/odoo/blob/e940a655aba06adc784008b72a3917170fdb3dd0/addons/sale_management/controllers/portal.py#L68-L69

[2]: https://github.com/odoo/odoo/blob/e940a655aba06adc784008b72a3917170fdb3dd0/addons/sale/models/sale_order_line.py#L783

[3]: https://github.com/odoo/odoo/blob/e940a655aba06adc784008b72a3917170fdb3dd0/addons/sale/models/sale_order_line.py#L801

sentry-7665145989