[FIX] l10n_eu_oss: prevent singleton error
While installing the l10n_eu_oss module it was raising a singleton error because
it was getting more than one account record with the same configurations.

Steps to produce:
1. Install the module on any `European Union` country  e.g. `l10n_be` and switch the company e.g. `BE Company CoA`
2. Go to  Tax Groups and change the `tax_payable_account_id`
3. Go to Apps and install `l10n_eu_oss`

Error: traceback appears: "Expected singleton: account.account(272, 492)"

https://github.com/odoo/odoo/blob/11f5d95a94f7fc068e0fd8ff085566f55d6eac4d/addons/l10n_eu_oss/models/res_company.py#L67

This line of code is attempting to find a single record of account.tax.group
with a specific condition. but search returns multiple records, which causes the
singleton error.

sentry-4338482840