[FIX] stock_account: update qty from negative to positive
If an AVCO product has a negative quantity and if a user updates the
quantity to a positive one, the valuation may fail in function on
the decimal accuracy configuration

To reproduce the issue:
(Enable debug mode)
1. Set the decimal accuracy of 'Product Price' to 4
2. Ensure the rounding of the company currency is 0.01
3. Create a product:
   - Cost: 0.001
   - Category: AVCO
4. Update the on hand quantity to -20000
5. Update the on hand quantity to 3000
6. Open the inventory valuation

Error: There are 3 SVL

|         | Qty    | Value |
|---------|--------|-------|
| SVL_03  | 0      | -20   |
| SVL_02  | 23000  | 23    |
| SVL_01  | -20000 | -20   |
| _Total_ | 3000   | -17   |

The total is incorrect, it comes from an unexpected layer: SVL_03

When updating the on hand quantity, we call `_run_fifo_vacuum`. This
is relevant for the second update (step 5) as we try to consume
SVL_01 with SVL_02. However, at the end of the process, we check if
there is still a remaining value we need to correctand here is the
issue: to get the value, we use the field `unit_cost` but this
field is a monetary one. Therefore, since the unit cost is
`-20000/-20 = 0.001` and the currency rounding is `0.01`, the unit
cost is rounded to zero. As a result, it makes the computations
wrong, and it will lead to the creation of SVL_03.

OPW-3121130