[FIX] l10n_es_edi_verifactu: removed unnecessary chatter
The system will crash with error when user clicks on expand button.

Error:
`AttributeError: 'l10n_es_edi_verifactu.document' object has no attribute '_get_thread_with_access'`

Cause:
- `l10n_es_edi_verifactu.document` does not inherits ['mail.thread',
  'mail.activity.mixin'] and used chatter in it's form view.

- In this PR, removed `<chatter/>` from view.

sentry-6792833694

closes odoo/odoo#231601

Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>