[FIX] pos_viva_wallet: prevent error when sending walled response bus notification
With commit [1], we removed the method '_get_bus_channel_name', but at
line [2], it's still referenced, which causes an error.

AttributeError:
'pos.session' object has no attribute '_get_bus_channel_name'

This commit will fix the issue by using '_notify' for calling the notification
bus.

[1]-https://github.com/odoo/odoo/commit/3836aad466c6c111f0f0d33c357a1c7a5150f3fd
[2]-https://github.com/odoo/odoo/blob/5633d590decc6e8989c0f454a355e965f072f967/addons/pos_viva_wallet/models/pos_payment_method.py#L133

sentry-5562979975

X-original-commit: 7c78dd49fb16b70f9df52510cee9a6e21b9678f5