[FIX] hr_holidays: prevent traceback on leave allocation
Steps to reproduce:
------------------------------------
1. Install the Time off module
2. Create a flexible working schedule:
     * Set Avg. hours per day to 0.0
3. Create an employee using this working schedule
4. Create a Time Off Type with Duration Type set to Hours
5. Try to create an allocation with the created employee and time off type

Observation:
------------------------------------
Traceback occurs:
```
  File '/home/odoo/odoo/community/addons/hr_holidays/models/hr_leave_allocation.py', line 280, in _compute_number_of_days
    allocation.number_of_days = allocation.number_of_hours_display / allocation.employee_id._get_hours_per_day(allocation.date_from)
ZeroDivisionError: float division by zero
```

Issue:
------------------------------------
When the allocation unit is set to Hours, the number of days is computed by
dividing the allocated hours by the employee's hours per day from the
Employee's working schedule
https://github.com/odoo/odoo/blob/f66614193cce18f5a3298d03ce7e5f29d54f07e9/addons/hr_holidays/models/hr_leave_allocation.py#L279-L280

If the employee's working schedule has an average of 0 hours per day,
`_get_hours_per_day()` returns 0, leading to a division by zero and causing
a traceback.

Solution:
------------------------------------
Handle this case gracefully by raising a `UserError` when the employee's
working schedule has 0 hours per day instead of allowing the division by zero
to occur.

opw-6298681