[FIX] account_edi_ubl_cii: prevent error when sending quotation
Currently an error is generated when the user tries to send a quotations
to the users.

Steps to produce an error:
- Create a new database with demo data and install `sale_management`
- Go to Invoicing > Configuration > Accounting >Taxes
- Create a new tax with a negative percentage, e.g., -10%
- Create a new `Quotation` and add a product line with the above-created
  negative tax.
- Error is generated when we try to `Send` this `Quotation`

Error: `KeyError: {'is_withholding': False, 'currency': res.currency(8,)}`

This issue occurs because the key `tax_total_grouping_key` is missing from
`ubl_values[target_key]`.  As we see at code line [1], there is already a
condition intended to continue and avoid accessing the key when
`tax_total_grouping_key` is empty. However, this condition is never triggered
because `tax_total_grouping_key` is never empty.

The reason is that `tax_total_grouping_key` is populated from
`ubl_default_tax_total_grouping_key` method. As shown in [2], this method
always returns a value since it uses a static dictionary. Therefore,
`tax_total_grouping_key` is guaranteed to have a value, making the empty
check ineffective and allowing the code to attempt access to a key that may not
exist in `ubl_values[target_key]`.

This commit fixes the issue by accessing `tax_total_grouping_key` from
`ubl_values[target_key]` only when it is available.

[1]: https://github.com/odoo/odoo/blob/c620283459d802d06d07900652752d9f5ad3abef/addons/account_edi_ubl_cii/models/account_edi_ubl.py#L537
[2]: https://github.com/odoo/odoo/blob/c620283459d802d06d07900652752d9f5ad3abef/addons/account_edi_ubl_cii/models/account_edi_ubl.py#L99-L110

sentry-7113127232