[FIX] website: prevent error while submit the contact form
Currently the error occurs when user submit their contact form.

Steps to reproduce:
- Install 'Website' module.
- Go to Website > Contact Us > click on Edit.
- Select contact us form > STYLE (sidebar)
- In the 'Form' section remove whatever is written
  on the 'Recipient Email' field.
- Then save it .
- Open contact us page, fill details and click on the 'Submit' button.
- The error is generated in the log.

Error: KeyError : 'website_form_signature'

This is because the 'website_form_signature' is added from [1], but due to
condition at [2] it is not executed in  [1] as result the key was not added in form.

This commit solves this issue by adding the condition which validate the
'website_form_signature' if it available in kwargs.

[1]-https://github.com/odoo/odoo/blob/550727ccabe5ad2b2cc6c2979147139b45587da7/addons/website/tools.py#L226
[2]-https://github.com/odoo/odoo/blob/550727ccabe5ad2b2cc6c2979147139b45587da7/addons/website/tools.py#L217

sentry-4633940473