Cherry pick of 2c497fdbe8c49328e6f07a1172afcb2c707deffc failed
stdout:
Auto-merging doc/cla/corporate/acsone.md
CONFLICT (content): Merge conflict in doc/cla/corporate/acsone.md

stderr:
11:27:05.341342 git.c:455               trace: built-in: git cherry-pick 2c497fdbe8c49328e6f07a1172afcb2c707deffc
error: could not apply 2c497fdbe8c... [CLA] add signature for jdoutreloux
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: