[FIX] website_sale_product_feed: fix _post_init_hook
```
  File /home/odoo/src/odoo/saas-18.4/addons/website_sale_product_feed/models/product_feed.py, line 105, in _check_product_limit
    raise ValidationError(feed.env._(
odoo.exceptions.ValidationError: A single feed cannot contain more than 5,000 products. Please separate products with Categories.
```
During migration I am getting the traceback mentioned above, which is occurring
because here we have populated feed records in _post_init_hook https://github.com/odoo/odoo/blob/saas-18.3/addons/website_sale_product_feed/__init__.py#L14 which will create feed records without any category ID
https://github.com/odoo/odoo/blob/saas-18.3/addons/website_sale_product_feed/models/website.py#L21
because of which, here we get all records without a category
https://github.com/odoo/odoo/blob/saas-18.3/addons/website_sale_product_feed/models/product_feed.py#L101
which is of course higher than our soft limit of 5000, and
a validation error occurs.

This commit skips websites for which the soft limit is already exceeded.

opw-5180407

closes odoo/odoo#233365

Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>