[FIX] portal,website_sale: redirection to HTML content
When submitting the new address, the `post` method from the `http`
service is called. This method expects a response in JSON. The problem
arises when a redirection occurs during that call, then the returned
content might be of another type which triggers an error. For example,
it is possible to be redirected to the `/shop/cart` page if the cart is
not valid.

Steps to reproduce:
- Add a product to your cart
- Then head over to the address form during checkout.
- Before confirming your address, in another tab, open the backend and
  remove every order line in your cart.
- Then back on the previoous tab, confirm your address.
- You can observe an error in the console:

```
SyntaxError: Unexpected token '<', ..."
        <!DOCTYPE "... is not valid JSON
```

This commit fixes this issue by sending the redirection URL in the
result of `shop_address_submit` and lets the client handle the
redirection.

This commit also renames the `successUrl` value to `redirectUrl` to make
it more clear that it is not necessarily a success URL any more, but the
next location URL for the user, ie. redirect.