[FIX] membership: wrong view arch
Wrong arch caused the following error when user language is not English

ValueError: Không tìm thấy phần tử '<tree string="Liên hệ">' trong giao
diện cha

View name: res.partner.tree.form.inherit
Error context:
 view: ir.ui.view(2867,)
 xmlid: membership.view_partner_tree
 view.model: res.partner
 view.parent: ir.ui.view(115,)

closes odoo/odoo#84508

Signed-off-by: Martin Trigaux (mat) <mat@odoo.com>