[FIX] mail: no crash 'undefined (reading '_raw')
Backport of https://github.com/odoo/odoo/pull/251769

Before this commit, Discuss code may crash with the following error:

```js
TypeError: Cannot read properties of undefined (reading '_raw')
```

This happens because delete operations in JS models could lead to
inconsistent state of record lists. Deletion of a record is done
internally as follow:

```js
const index = recordList.indexOf(record);
recordList.splice(index, 1);
```

This is done that way as to reuse custom methods of `RecordList`,
especially the `splice()` that is used by many methods that mutate
the record list. Internal code of the custom `splice` method does
`slice()`, which is used to retrieve some records without mutating
the record list.

In practice, these `.slice()` were accidentally mutating the list,
because they invoke the `Proxy.getter` of the `RecordList`, and when
the list is flagged for `computeOnNeed` / `sortOnNeed`, invoking this
`Proxy.getter` would mistakenly enable the `computeInNeed` /
`sortInNeed` flags and thus mutate the list, e.g. with a sort, which
may change the order of items and mess up the `index` computed in
`indexOf()` step.

This is what might happen with deletion of any item in record list.
For example, let's have `menuThreads` that have this value:

```js
menuThread = ["thread_1", "thread_2", "thread_3"];
```

With the removal of `thread_2`, the `.indexOf()` is `1`, but due to
`.slice()` triggering the sort, the list was changed to:

```js
menuThread = ["thread_2", "thread_1", "thread_3"];
```

... And it instead removed `thread_1` but kept `thread_2` in list.
This introduce 2 problems:
- `thread_1` is mistakenly removed from relation when it shouldn't
- `thread_2` is kept, but since this is a local id with no actual
record in store, `recordList[index]` would return `undefined` as
there's no existing record matching this local id.

This commit fixes the issue by improving internal code of record list
methods to avoid accidental triggering of lazy re-compute and
re-sort. The accidental re-compute and re-sort come from invoking
non-implemented array methods on the proxy of record, such as:

- `recordProxy.at()`
- `recordProxy.slice()`

These methods were just used meant to retrieve records from the
record list, and they did so by using accessing through
`recordProxy`. This approach has the benefit to look good as this is
exactly the same as the external API, but it has the unintended
side-effect of the re-compute / re-sort of lazy fields. Instead of
using these methods, records are retrieved with:

- raw access to get local ids in relation
- convert local ids to raw records through raw access in
  `store.recordByLocalId`

This approach, while uglier, has the benefit to not accidentally
trigger the re-compute / re-sort.

opw-5761279

closes odoo/odoo#251769

closes odoo/odoo#260109

Signed-off-by: Matthieu Stockbauer (tsm) <tsm@odoo.com>
Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>