[FIX] account: filter invalid default purchase taxes
Steps to Reproduce:
- Install the Invoicing module.
- Open the "15%" purchase tax and change its tax type to None.
- Create and save a new product.

Error:
ValueError: Cannot link inaccessible records in product.template.supplier_taxes_id ([('type_tax_use', '=', 'purchase')])

Cause:
The default value of supplier_taxes_id includes the company's default purchase
tax, even when its type is no longer Purchase.
Since this https://github.com/odoo/odoo/commit/447ea3bcfefd0dab6958b6d1f1e59668da70c5eb
commit, the x2many domain validation rejects this tax and raises an error.

Fix:
Filter out taxes whose type is not Purchase when setting the default supplier
taxes and forcing company default taxes on products.

sentry-7752148735,7761410453