Cherry pick of f1356a4ba03cd10d658e95086bbac254d5e4293c failed
stdout:
CONFLICT (modify/delete): addons/pos_restaurant/data/pos_restaurant_onboarding.xml deleted in HEAD and modified in f1356a4ba03c ([FIX] pos_restaurant: load pos data with noupdate).  Version f1356a4ba03c ([FIX] pos_restaurant: load pos data with noupdate) of addons/pos_restaurant/data/pos_restaurant_onboarding.xml left in tree.
CONFLICT (modify/delete): addons/pos_restaurant/data/pos_restaurant_onboarding_main_config.xml deleted in HEAD and modified in f1356a4ba03c ([FIX] pos_restaurant: load pos data with noupdate).  Version f1356a4ba03c ([FIX] pos_restaurant: load pos data with noupdate) of addons/pos_restaurant/data/pos_restaurant_onboarding_main_config.xml left in tree.
CONFLICT (modify/delete): addons/pos_restaurant/data/pos_restaurant_onboarding_open_session.xml deleted in HEAD and modified in f1356a4ba03c ([FIX] pos_restaurant: load pos data with noupdate).  Version f1356a4ba03c ([FIX] pos_restaurant: load pos data with noupdate) of addons/pos_restaurant/data/pos_restaurant_onboarding_open_session.xml left in tree.
Auto-merging addons/pos_restaurant/models/pos_session.py
CONFLICT (content): Merge conflict in addons/pos_restaurant/models/pos_session.py

stderr:
10:39:04.950102 git.c:463               trace: built-in: git cherry-pick f1356a4ba03cd10d658e95086bbac254d5e4293c --strategy ort
error: could not apply f1356a4ba03c... [FIX] pos_restaurant: load pos data with noupdate
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: