[REV] {purchase_,}mrp, {purchase_,}stock: handle mutlti routes
Commit [1] introduces a regression

Steps to replicate:
- Install `mrp_subcontracting_dropshipping` and turn on `Multi-step Routes`
- Create a product > From the Purchase tab add a Vendor to this product
- Click on cog menu, Click Replenish

Note: This error can also be replicated using duplicating the `Buy` route

Error:
ValueError: Expected singleton: stock.route(4, 13)

Reason:
Cf for instance in `/mrp:ProductReplenish._get_route_domain`
The search might find several rule of several routes
Therefore, doing `manufacture_route.id` will lead to the error

The case will be protected with a test in another PR

[1] 705e27a2d3d9e3c4d075a1e8fb599333a504a316

sentry-7287557500
opw-5961814
opw-5973658
opw-5969160
opw-5969487
opw-5972463
opw-5972805