[FIX] payment_mercado_pago: handle unauthorized payment attempt
The user attempts to make a payment using the 'Mercado Pago' Payment Provider
when they are not allowed to access or authorized to make a payment at that
time response does not convert into JSON. And JSONDecode error will be
generated, There is another chance to trackback occurs due to
Server-side issues.

Error: Expecting value: line 1 column 1 (char 0)
HTTPError:403 Client Error: Forbidden for URL: https://api.mercadopago.com/
checkout/preferences

To handle this situation, the code has been updated to ensure that if
the response is not appropriate then raise validation error.

sentry-4214916971