[FIX] base: add company field on child partner form
To reproduce the issue:
(Need more than one company)
1. Create a partner and link him to a specific company
2. In "Contacts & Addresses", add a new partner
3. Open this "child partner"

Error: the child partner does not belong to the company defined at
step 1

Commit [1] removed the field from the company, but this field is
needed so we can define its value thanks to the onchange
https://github.com/odoo/odoo/blob/988b47c0ca409a38c2f429a6db017eef17053c04/odoo/addons/base/models/res_partner.py#L529-L532

[1] d9e7c12a4bfc84b1be0664144ea56e4ccb5c8c17

OPW-4247914

closes odoo/odoo#190647

X-original-commit: 2844130646be817de80b8352f8b7198c9f3ba501
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>