[FIX] l10n_in_upi: move xpath from l10n_in_upi to l10n_in
When a user tries to print an invoice AttributeError occurs:

- Install `l10n_in`.
- Unistall `l10n_in_upi`
- Switch to IN Company
- Accounting > Configuration> Setting> RQ Codes (Enable).
- Accounting > Invoice >  Open any invoice and Print this Invoice.

Error: traceback appears: "Error while render the template
AttributeError: 'res.company' object has no attribute 'l10n_in_upi_id'
Template: account.report_invoice_document".

This is because the 'l10n_in_upi_id' field is used in 'l10n_in' module but
it belongs to 'l10n_in_upi'.

This commit fixes the above issue by moving
the 'l10n_in_upi_report_invoice_document_inherit'
from 'l10n_in' module to 'l10n_in_upi' to which it belongs.

sentry-4347295630