Fix error in QWeb when a record is empty
When using a many2one widget, in the following scenario:

<h2><span t-field="o.partner_id.parent_id.country_id"/></h2>

If 'parent_id' is an empty recordset, the following error will be
raised:

2016-11-25 21:46:44,730 6210 WARNING openerp_travis openerp.addons.base.ir.ir_qweb: Could not get field country_id for model res.partner
Traceback (most recent call last):
  File "/home/travis/build/camptocamp/parts/server/openerp/addons/base/ir/ir_qweb.py", line 624, in to_html
    content = self.record_to_html(cr, uid, field_name, record, options, context=context)
  File "/home/travis/build/camptocamp/parts/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/travis/build/camptocamp/parts/server/openerp/addons/base/ir/ir_qweb.py", line 795, in record_to_html
    [read] = record.read([field_name])
ValueError: need more than 0 values to unpack

This is because record.read([field_name]) returns an empty list which
cannot be unpacked.