[FIX] base: prevent TypeError when adding submenu without saving parent
Currently, a traceback occurs when the user tries to add a submenu
by following the following steps:
- Open menu items (ir.ui.menu) list view
- Click the Create button > Open Submenus tab
- Click on Add a line >>> traceback will appear.

Error: "TypeError: unsupported operand type(s) for +: 'bool' and 'str'"

This is because at [1] in the code 'self.parent_id._get_full_name(level - 1)'
we got False because currently parent is not saved.

This commit solves the above issue by adding a blank string instead
of the parent menu's full name if it is False.

[1]-https://github.com/odoo/odoo/blob/472ea5f6c0c33bb24d453432c4169f077c376581/odoo/addons/base/models/ir_ui_menu.py#L58

sentry-4769838838