Cherry pick of 5c28b9ac2c204292862a2fafa24447e30676d84e failed
stdout:

stderr:
Performing inexact rename detection:   0% (114760/32440840)   Performing inexact rename detection:   1% (326160/32440840)   Performing inexact rename detection:   2% (652320/32440840)   Performing inexact rename detection:   3% (978480/32440840)   Performing inexact rename detection:   4% (1298600/32440840)   Performing inexact rename detection:   5% (1624760/32440840)   Performing inexact rename detection:   6% (1950920/32440840)   Performing inexact rename detection:   7% (2271040/32440840)   Performing inexact rename detection:   8% (2597200/32440840)   Performing inexact rename detection:   9% (2923360/32440840)   Performing inexact rename detection:   9% (2947520/32440840)   Performing inexact rename detection:  10% (3249520/32440840)   Performing inexact rename detection:  11% (3575680/32440840)   Performing inexact rename detection:  12% (3895800/32440840)   Performing inexact rename detection:  13% (4221960/32440840)   Performing inexact rename detection:  14% (4542080/32440840)   Performing inexact rename detection:  15% (4868240/32440840)   Performing inexact rename detection:  15% (4928640/32440840)   Performing inexact rename detection:  16% (5194400/32440840)   Performing inexact rename detection:  17% (5520560/32440840)   Performing inexact rename detection:  18% (5840680/32440840)   Performing inexact rename detection:  19% (6166840/32440840)   Performing inexact rename detection:  20% (6493000/32440840)   Performing inexact rename detection:  21% (6813120/32440840)   Performing inexact rename detection:  22% (7139280/32440840)   Performing inexact rename detection:  23% (7465440/32440840)   Performing inexact rename detection:  24% (7791600/32440840)   Performing inexact rename detection:  24% (7864080/32440840)   Performing inexact rename detection:  25% (8111720/32440840)   Performing inexact rename detection:  26% (8437880/32440840)   Performing inexact rename detection:  27% (8764040/32440840)   Performing inexact rename detection:  28% (9084160/32440840)   Performing inexact rename detection:  29% (9410320/32440840)   Performing inexact rename detection:  30% (9736480/32440840)   Performing inexact rename detection:  31% (10062640/32440840)   Performing inexact rename detection:  32% (10382760/32440840)   Performing inexact rename detection:  32% (10400880/32440840)   Performing inexact rename detection:  33% (10708920/32440840)   Performing inexact rename detection:  34% (11035080/32440840)   Performing inexact rename detection:  35% (11355200/32440840)   Performing inexact rename detection:  36% (11681360/32440840)   Performing inexact rename detection:  37% (12007520/32440840)   Performing inexact rename detection:  38% (12327640/32440840)   Performing inexact rename detection:  39% (12653800/32440840)   Performing inexact rename detection:  39% (12841040/32440840)   Performing inexact rename detection:  40% (12979960/32440840)   Performing inexact rename detection:  41% (13306120/32440840)   Performing inexact rename detection:  42% (13626240/32440840)   Performing inexact rename detection:  43% (13952400/32440840)   Performing inexact rename detection:  44% (14278560/32440840)   Performing inexact rename detection:  45% (14598680/32440840)   Performing inexact rename detection:  46% (14924840/32440840)   Performing inexact rename detection:  47% (15251000/32440840)   Performing inexact rename detection:  47% (15474480/32440840)   Performing inexact rename detection:  48% (15577160/32440840)   Performing inexact rename detection:  49% (15897280/32440840)   Performing inexact rename detection:  50% (16223440/32440840)   Performing inexact rename detection:  51% (16549600/32440840)   Performing inexact rename detection:  52% (16869720/32440840)   Performing inexact rename detection:  52% (17123400/32440840)   Performing inexact rename detection:  53% (17195880/32440840)   Performing inexact rename detection:  54% (17522040/32440840)   Performing inexact rename detection:  55% (17848200/32440840)   Performing inexact rename detection:  56% (18168320/32440840)   Performing inexact rename detection:  57% (18494480/32440840)   Performing inexact rename detection:  58% (18820640/32440840)   Performing inexact rename detection:  58% (19019960/32440840)   Performing inexact rename detection:  59% (19140760/32440840)   Performing inexact rename detection:  60% (19466920/32440840)   Performing inexact rename detection:  61% (19793080/32440840)   Performing inexact rename detection:  62% (20119240/32440840)   Performing inexact rename detection:  63% (20439360/32440840)   Performing inexact rename detection:  64% (20765520/32440840)   Performing inexact rename detection:  65% (21091680/32440840)   Performing inexact rename detection:  66% (21411800/32440840)   Performing inexact rename detection:  66% (21544680/32440840)   Performing inexact rename detection:  67% (21737960/32440840)   Performing inexact rename detection:  68% (22064120/32440840)   Performing inexact rename detection:  69% (22384240/32440840)   Performing inexact rename detection:  70% (22710400/32440840)   Performing inexact rename detection:  71% (23036560/32440840)   Performing inexact rename detection:  72% (23362720/32440840)   Performing inexact rename detection:  73% (23682840/32440840)   Performing inexact rename detection:  74% (24009000/32440840)   Performing inexact rename detection:  74% (24087520/32440840)   Performing inexact rename detection:  75% (24335160/32440840)   Performing inexact rename detection:  76% (24655280/32440840)   Performing inexact rename detection:  77% (24981440/32440840)   Performing inexact rename detection:  78% (25307600/32440840)   Performing inexact rename detection:  79% (25633760/32440840)   Performing inexact rename detection:  80% (25953880/32440840)   Performing inexact rename detection:  81% (26280040/32440840)   Performing inexact rename detection:  81% (26557880/32440840)   Performing inexact rename detection:  82% (26606200/32440840)   Performing inexact rename detection:  83% (26926320/32440840)   Performing inexact rename detection:  84% (27252480/32440840)   Performing inexact rename detection:  85% (27578640/32440840)   Performing inexact rename detection:  86% (27904800/32440840)   Performing inexact rename detection:  87% (28224920/32440840)   Performing inexact rename detection:  88% (28551080/32440840)   Performing inexact rename detection:  89% (28877240/32440840)   Performing inexact rename detection:  90% (29197360/32440840)   Performing inexact rename detection:  91% (29523520/32440840)   Performing inexact rename detection:  91% (29541640/32440840)   Performing inexact rename detection:  92% (29849680/32440840)   Performing inexact rename detection:  93% (30175840/32440840)   Performing inexact rename detection:  94% (30495960/32440840)   Performing inexact rename detection:  95% (30822120/32440840)   Performing inexact rename detection:  96% (31148280/32440840)   Performing inexact rename detection:  97% (31468400/32440840)   Performing inexact rename detection:  98% (31794560/32440840)   Performing inexact rename detection:  98% (31867040/32440840)   Performing inexact rename detection:  99% (32120720/32440840)   Performing inexact rename detection: 100% (32440840/32440840)   Performing inexact rename detection: 100% (32440840/32440840), done.
error: could not apply 5c28b9ac2c2... [FIX]web_editor: remove useless datarecord from URL
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/web_editor/controllers/main.py'