[FIX] base: convert integer ids to strings in ModelsConverter.to_url
When building a URL using the models converter (e.g. via url_for or
MapAdapter.build on routes declared with <models('model'):ids>),
ModelsConverter.to_url called ','.join(value.ids).

Because value.ids contains integer IDs, str.join raised
TypeError: sequence item 0: expected str instance, int found.

Convert integer ids to strings using map(str, value.ids) before joining.

Fixes #292724

closes odoo/odoo#293836

X-original-commit: ca17864f5e6349788a7512239986a006c0ea3bc8
Signed-off-by: Ankit raj sharma <ankitrajsharma666@gmail.com>
Signed-off-by: Krzysztof Magusiak (krma) <krma@odoo.com>