[FIX] mrp: avoid traceback when computing Qty Packaging for Kit with UoM
When printing a delivery order with a kit product that has a BoM
with a product template (not a product_id) and a packaging quantity, we
encounter a traceback due to the conversion of the quantity from the
product's UoM to the order line's UoM. This happens because the
product's UoM is not defined.

Steps to reproduce the bug:
- Create a storage “P1”:
    - UoM: Kg

- Create a storable “Kit 1”:
    - UoM: unit
    - BoM:
       - set only the product template field (not the product_id)
        - 1 Kg of P1

- Create a delivery order for 1 unit of Kit 1
- Mark it as to do
- Set the quantity of P1 to 1kg
- try to print

Problem:
A traceback is triggered because we try to convert 1kg to an undefined
uom

```
Error while render the template
UserError: The unit of measure Units defined on the order line doesn't
belong to the same category as the unit of measure False defined on
the product. Please correct the unit of measure defined on the order
line or on the product. They should belong to the same category.

```

opw-4619140

closes odoo/odoo#205868

X-original-commit: 3ffde0f4a1f6ece6e86482e7d36e378e7a3f4f41
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>