[FIX] l10n_it[_edi_withholding]: split payment vat error
With an IT Company setup but without the withholding module:
- Set fiscal position to split payment
- Set tax on product to SP type tax
- Click send and print to generate XML

Error: XML generation is blocked with message
"Invoices must have exactly one VAT tax set per line"

This occurs because the system find 2 VAT taxes, but only the positive
one should count for the validation

opw-3945046

X-original-commit: fefd066ae740e7f3028b22fc82f4dc7210d79c6a