[FIX] stock{,_account}: open stock report with basic rights
An inventory user can't open the forecast report.

To reproduce the issue:
(Use demo data)
1. Edit the user Marc Demo:
    - Inventory: User
2. Log in with Marc Demo
3. Open the product 'Acoustic Bloc Screens'
4. Open its forecasted report

Error: There is an access error "You are not allowed to access 'Stock
Valuation Layer' (stock.valuation.layer) records"

We use `read` on the outgoing stock moves, but the current user does not
have the access rights to all relational fields of that records (for
instance, `stock_valuation_layer_ids`, which is a `2many` field to the
model `stock.valuation.layer`: an inventory user does not have any
access to this model).

OPW-3056287

X-original-commit: 32cdd04747f5a229e94305e7d36b02c7e0344161