[FIX] maintenance: fixed close_date null value
field `close_date` for maintenance is not required
and we used it on `compute_maintenance_request`
to calculate `mttr`, on this line
`sum(int((request.close_date - request.request_date).days`
so close_date is null , will get traceback
```
 File "/home/odoo/src/odoo/17.0/addons/maintenance/models/maintenance.py", line 109, in _compute_maintenance_request
    record.mttr = len(maintenance_requests) and (sum(int((request.close_date - request.request_date).days) for request in maintenance_requests) / len(maintenance_requests)) or 0
   File "/home/odoo/src/odoo/17.0/addons/maintenance/models/maintenance.py", line 109, in <genexpr>
    record.mttr = len(maintenance_requests) and (sum(int((request.close_date - request.request_date).days) for request in maintenance_requests) / len(maintenance_requests)) or 0
 TypeError: unsupported operand type(s) for -: 'bool' and 'datetime.date'
```