[FIX] mail: fix NotAllowedError from audio play in Firefox
Before this commit, when receiving a new message in a chat
while the device is in sleep mode on Firefox, the browser
could show the following traceback on waking up the device:

```
NotAllowedError: The play method is not allowed by the user agent
```

This happens because the page is reloaded, and autoplay is blocked
by Firefox autoplay policies (which are different from Chrome and
Webkit). When receiving a new message while device is sleeping,
the odoo tab is not focused, so it attempts to play an audio alert.
Since the autoplay is disabled, it shouldn't play the audio.

This commit fixes the issue by handling all `.play()` in the same
way, with `Promise.resolve(audio.play()).catch(() => {})`, which
is a pattern that should work for all problems in all conditions,
whether autoplay is allowed or not.