[FIX] im_livechat: no duplicate t-key in channel invite
Follow-up of https://github.com/odoo/odoo/pull/198093

PR above improved channel invitation UI to show livechat
operator languages and expertise, whereas it was only
showing the main language.

This PR introduced the following crash by mistake:

```
OwlError: Got duplicate key in t-foreach: undefined
```

This happens because the keys were defined as `index`,
which is `undefined` thus an operator with at least 3
languages or 2 expertise items made it crash.

The intend of `t-key` was to use the index of item in
the respective list, so the `t-value` variable with
`_index`, e.g. `language_index`, which this commit fixes.

X-original-commit: 4dd66bc47dff3d6321f5de871f3c0fb2e853c098