[FIX] translating %s to %س
In arabic we should not translate %s to %س because this cause 
              TypeError: not all arguments converted during string formatting