[IMP] account: expanding the range of integer for sequence_number
Before this commit
==================
If continue sequence is more than 10 digits then we had an error if below regex
is applied on sequence_override_regex for journal .
so converting column_type for sequence number from int4 to int8
inorder to support sequence_number of max 19 digits which was previously 10 digits only.

error: https://justpaste.it/aikhq
Regex: `^(?P<prefix1>.*?)(?P<seq>\d*)(?P<suffix>\D*?)$`