Cherry pick of becde6781dbfc47feceaa3a25dccffe5234772d0 failed
stdout:

stderr:
error: could not apply becde6781db... [IMP] calendar: faster recurring events search
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'