[FIX] l10n_jo_edi: Remove deprecated mobile fallback
Since https://github.com/odoo/enterprise/commit/555de9b336f0538439d6e2977984573bf2b4fc28
the `mobile` field has been removed.

This fix eliminates its usage as a fallback.

Steps to reproduce
1. Install `l10n_jo_edi`
2. Create a partner without a mobile number
3. Generate and validate an invoice
4. Attempt to send it to JoFatura

You'll get:
```
AttributeError: 'res.partner' object has no attribute 'mobile'
```

closes odoo/odoo#202016

X-original-commit: 5b47990597622009fd8b80c8626ca89a9d855391
Signed-off-by: de Wouters de Bouchout Jean-Benoît (jbw) <jbw@odoo.com>
Signed-off-by: Louis Gobert (loug) <loug@odoo.com>