[FIX] base,irQweb: When in dev-mode xml some attributes disappear
The compilation consumed attributes, in dev mode the template can be
compiled twice with the same etree. This causes some t-calls to not be
made, and some attributes to disappear if the templates are used twice in
a request.

Issue:

Odoo Client Error
UncaughtPromiseError > TypeError

Uncaught Promise > snippetEl.children[0] is undefined

Occured on localhost:8069 on 2025-06-19 07:34:46 GMT

TypeError: snippetEl.children[0] is undefined
    computeSnippetTemplates@http://localhost:8069/web/assets/9ed6d90/html_builder.assets.min.js:1096:67
    load/this.loadProm<@http://localhost:8069/web/assets/9ed6d90/html_builder.assets.min.js:1093:186
    async*load@http://localhost:8069/web/assets/9ed6d90/html_builder.assets.min.js:1093:268
    setup/</<@http://localhost:8069/web/assets/3ec822d/web.assets_web.min.js:21059:109

closes odoo/odoo#214999

Signed-off-by: Christophe Matthieu (chm) <chm@odoo.com>