[FIX] mail: no crash on record.delete() on already deleted record
Before this commit, when opening AI chat from systray in home
menu and immediatley closing the chat window, it crashed with
following error:

```
TypeError: Cannot read properties of undefined (reading '_proxy')
```

This happens because closing chat window triggers deletion of the
thread, and there are the following side-effects in code:
- delete of thread implies delete of channel
- delete of thread implies deletion of the members
- thread correspondent field is computed based on members field
(Note: deletions are in JS, not necessarily made server-side)

When thread is being deleted, it triggers deletion of members and
channels, but both fields have side-effect `onDelete` to delete the
thread. This leads to invoking thread deletion twice, which is not
a problem usually but here this crashes.

This crashes in this case because field `correspondent` is computed.
Compute of fields are not triggered for soft-deleted records, but
internal code relies on `onChange` that necessarily triggers proxy
accessor, including on soft-deleted records like thread.

This commit fixes the issue by not passing a deleted record to the
`onDelete` hook of a field. (Note: record deletion deletion of record
in a field).

closes odoo/odoo#230609

Related: odoo/enterprise#96724
Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>