[FIX] project: prevent error on opening studio view
An error currently occurs when opening the studio view.

Steps to reproduce:
- Install 'Project' and 'web_studio'
- Project > Configuration> Projects > Create a New Project
- Click on the 'Dashboard' button > Open studio view
- Error in terminal

Traceback:
TypeError: object of type 'bool' has no len()

This error occurs because 'project.update' doesn’t have any records. When
opening the studio view, at [1] it tries to compute the record’s name,
which is 'False', and 'False' has no length.

[1]- https://github.com/odoo/odoo/blob/e0322e2cbc16d2405e66f3b16cbabeac2ad265e7/addons/project/models/project_update.py#L80

sentry-6830573412

X-original-commit: ac181b075957d6e5591d76140972fc097e8e56c1