[FIX] pos_stripe: use payment provider method for payment capture
Before this commit:
 If you make a PoS payment using a Stripe terminal, you will have
 the following JS Traceback:
 ```js
 TypeError: Cannot read properties of undefined (reading 'data')
    at Proxy.captureAfterPayment
 ```

 This happens on the line:
 `capturePayment.charges.data[0].payment_method_details.card_present.brand;`
 It occurs as Stripe API most recent version does not provide the
 `charges` value anymore.
 > The charges property on PaymentIntent has been removed
 source:
 https://stripe.com/docs/upgrades#2022-11-15

After this commit:
 We skip the data if not mentioned on the JS side.
 In addition of that, we use the `_stripe_make_request`
 method of the Stripe payment provider as it
 force in its header to use a certain Stripe API version
 compatible with the features that we are looking for.

opw-3097460

closes odoo/odoo#108735

Signed-off-by: Loan (LSE) <lse@odoo.com>
Signed-off-by: Quentin Lejeune (qle) <qle@odoo.com>