[FIX] product: prevent error while unarchive product with dynamic variant
Currently, an error is generated when unarchiving multiple products which have
dynamic attributes & variants.

Step to produce:

- Install a 'Sales' module.
- Navigate to the Sales / Products / Products, And create a product.
- Add a 'Product Name' and save a record, and then add dynamic
Attributes & Variants.
- Repeat the process described in the above step to create another product with
the same configuration as the first one.
-Go to list view of 'Product'. select both products that we made recently
and click on the Action button to archive both products.
- Click on 'Filters' to see the archive product, And select those products
to Unarchive.

ValueError: Expected singleton: product.template(39, 37, 40, 42, 38, 46, 34)

The issue occurs when unarchive multiple products that contain dynamic
attributes & variants. As a result, the system receives multiple product
templates at [1].

link[1]: https://github.com/odoo/odoo/blob/e5635c38810a745f00b106d7a075ae1553de50c7/addons/product/models/product_template.py#L745

To resolve the issue, replace a 'self' with 'tmpl_id' to get a single product
template record instead of multiple.

sentry-5222160918

closes odoo/odoo#165477

X-original-commit: 96b439472d214cbb0cb40c242582de41a69b7aa1
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>