Cherry pick of d72fc710b954f9521e4f628cc5fdf9501b05f1c4 failed
stdout:

stderr:
error: could not apply d72fc710b95... [FIX] account, l10n_in: refund invoice should have localization's field
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/l10n_in/models/account_invoice.py'