[FIX] hr_timesheet,sale_project: allow to upgrade module dependent on another module
When the user upgrades a module which depends on another module
then the user faces ParseError.

In our case the user was trying to upgrade `hr_timesheet` without
upgrading `project` module.

Error: `Failed to load registry`

sentry-4247161969