[FIX] microsoft_calendar: add missing argument 'service'
When the user tries to synchronize calendar with Outlook calendar,
a traceback will appear.

Error: A traceback appears:
TypeError: User._refresh_microsoft_calendar_token() missing 1 required
positional argument: 'service'

https://github.com/odoo/odoo/blob/88fa5a113debfbf65f9b0862b14c15ef4da45d12/addons/microsoft_calendar/models/res_users.py#L35
Here, "_refresh_microsoft_calendar_token" method is called without
"service" argument.

https://github.com/odoo/odoo/blob/88fa5a113debfbf65f9b0862b14c15ef4da45d12/addons/microsoft_calendar/models/res_users.py#L41
Here, the "service" argument is added but not used anywhere.

sentry-6026445994