[FIX] website: prevent error while searching in website without pages
Currently, an exception was generated when the user deleted all website
pages and tried to search for anything on the website.

error: `SyntaxError: syntax error at or near ")"`

This is because the user deleted all pages, and we got an empty list on
`most_specific_pages`.

This commit will fix the above issue by preventing the execution of the
query when most_specific_pages is empty.

sentry-5449704973