[FIX] analytic: populate analytic lines
The `sum` function needs to be given a compatible for the `start`
argument.
Instead of using that function for a simple sum of two elements (not
`int`), lets just sum them explicitly instead.

Traceback:
```
TypeError: unsupported operand type(s) for +: 'int' and 'account.analytic.plan'
```

X-original-commit: 133356da4c587e4e3d43870c2721286e36746425