[FIX] l10n_in_ewaybill: Fix traceback while loading demo data
Issue caused because of https://github.com/odoo/odoo/commit/619d8ce9f31349ed06b11ead4988a4a1d9ca6bdd
Steps to reproduce-
Create db with demo and install l10n_in
Create a new company for India (other than IN Company)
Go to Settings -> Accounting/Invoice Tab -> Enable Ewaybill

traceback
```py
Traceback (most recent call last):
  File "/home/odoo/odoo18/community/odoo/orm/models.py", line 5385, in ensure_one
    _id, = self._ids
    ^^^^
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo18/community/odoo/http/router.py", line 273, in __call__
    response = serve_db(request)
               ^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/odoo/http/router.py", line 380, in serve_db
    registry = Registry(request.db)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/odoo/orm/registry.py", line 105, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/odoo/tools/func.py", line 67, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/odoo/orm/registry.py", line 217, in new
    cr.rollback()
  File "/home/odoo/odoo18/community/odoo/sql_db.py", line 568, in rollback
    with rollbacking:
  File "/home/odoo/.pyenv/versions/3.12.0/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 1004, in rollbacking
    self.restore_state()
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 1067, in restore_state
    self.reset()
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 912, in reset
    self._reset_registry_change()
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 832, in _reset_registry_change
    registry._setup_models__(cr)
  File "/home/odoo/odoo18/community/odoo/tools/func.py", line 67, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/odoo/orm/registry.py", line 422, in _setup_models__
    env.invalidate_all()
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 395, in invalidate_all
    self.flush_all()
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 413, in flush_all
    self._recompute_all()
  File "/home/odoo/odoo18/community/odoo/orm/environments.py", line 406, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/odoo/odoo18/community/odoo/orm/models.py", line 6462, in _recompute_field
    field.recompute(records)
  File "/home/odoo/odoo18/community/odoo/orm/fields.py", line 2042, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/odoo18/community/odoo/orm/fields.py", line 2012, in apply_except_missing
    func(records)
  File "/home/odoo/odoo18/community/odoo/orm/fields.py", line 2066, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/odoo18/community/addons/mail/models/mail_thread.py", line 498, in _compute_field_value
    return super()._compute_field_value(field)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/odoo/orm/models.py", line 4387, in _compute_field_value
    determine(field.compute, self)
  File "/home/odoo/odoo18/community/odoo/orm/fields.py", line 82, in determine
    return needle(*args)
           ^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py", line 228, in _compute_document_partners_details
    seller_buyer_details = ewaybill._get_seller_buyer_details()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py", line 185, in _get_seller_buyer_details
    return move._get_l10n_in_seller_buyer_party()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/odoo18/community/addons/l10n_in/models/account_invoice.py", line 629, in _get_l10n_in_seller_buyer_party
    self.ensure_one()
  File "/home/odoo/odoo18/community/odoo/orm/models.py", line 5388, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.move()
```
In this commit, we resolve the above traceback

closes odoo/odoo#279274

X-original-commit: ccc3bcad8df771d0325f5e0e971d79435385c2a1
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>
Signed-off-by: Harsh Modi (hamo) <hamo@odoo.com>