[FIX] project: pass correct args while deleting the project
ValueError: Invalid field project.task.website_id in leaf ('website_id', 'in',
(False, 1)) is generated when the user tries to delete the project.

The value of 'args' is getting updated by reference from variable 'args' from
method '_search' present in the same model. This results in a traceback with the
above message

This commit fixes the above issue by passing proper args.

sentry-4272349450