Cherry pick of f1206bb2a6deb6ca021f487e076909ebe25de330 failed
stdout:

stderr:
error: could not apply f1206bb2a6d... [FIX] website_event_*: fix minor view/wording issues
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'