[FIX] html_editor: ignore unevaluated domains in many2one fields
Currently, editing the address or organizer on an event page in website editor
triggers an error due to an invalid, unevaluated domain being passed.

Steps to reproduce:
1. Install 'website_event' module with demo data.
2. Open any event page and activate the website editor.
3. Click on My Company under Organizers (also works with Location).
4. On the right sidebar click on "Contact" drop-down.

Error:
ValueError: Domain() invalid item in domain: ')'

Cause:
The fields `event.event.address_id` and `event.event.organizer_id` have
`check_company=True`, which generates in a domain expression like this at [1]:
(company_id and ['|', ('company_id', '=', False), ('company_id', 'parent_of', [company_id])] or ['|', ('company_id', '=', False), ('company_id', 'parent_of', '')]) + []

This domain is not evaluated on the back-end; instead serialized as JSON string.
When the website editor opens the many2one dropdown, the JS code (ref 2)
incorrectly splits this string into a list of individual characters, for example:
['(', 'c', 'o', 'm', 'p', 'a', 'n', 'y', '_', 'i', 'd', ' ', 'a', 'n', 'd', ' ', '[', "'", '|', "'", ',', ' ', '(', "'", 'c', 'o', 'm', 'p', 'a', 'n', 'y', '_', 'i', 'd', "'", ',', ' ', "'", '=', "'", ',', ' ',>

Such a malformed domain passed directly to `name_search()` method,
where Domain() fails to validate it, raising the error.

Fix:
This commit checks for unevaluated domains (returned as strings) and
ignores them when rendering many2one fields in the website editor.

[1]: https://github.com/odoo/odoo/blob/9bf7a6511711cbd4866bec03dce5cd08d7580065/addons/html_editor/models/ir_qweb_fields.py#L255
[2]: https://github.com/odoo/odoo/blob/9bf7a6511711cbd4866bec03dce5cd08d7580065/addons/html_builder/static/src/core/building_blocks/select_many2x.js#L102-L109

sentry-6916986959

X-original-commit: a0ceb0be04f1c1ac13574abef3721de71b4e1051