[FIX] purchase: convert qty in purchase report
Some fields of the purchase report are not correcly computed.

To reproduce the issue:
1. In Settings, enable "Units of Measure & Packagings"
2. Create a product and UoM:
   - UoM of the product: Pack of 2
   - Available UoM: Pack of 6
   - Volume: 10
3. Confirm a PO with one pack of 6
4. Purchase > Reporting > Purchase
5. Observe the volume of the confirmed PO

Error: The value is incorrect, it should be 30.

Since the big refactoring of the UoM [1], the factor is now the
ratio `reference unit / related unit`. Considering this, multiplying
the line qty with the factor of its UoM gives the qty based on the
reference unit. Then, dividing that new qty with the factor of the
product UoM gives the qty based on the product UoM. However, that's
not the case in the code, we are still doing the opposite.

For some mysterious reasons, commit [1] has updated a part of the
report only, and some fields still need to be fixed, among them: the
volume.

[1] a8246ec4c2fabcb1c5686ea06d746eb6c77512bd

OPW-4871100

closes odoo/odoo#220132

X-original-commit: a47024805755ea9b7e77ac47f68dd967b47beb3f
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Maeva de Keyser (mdek) <mdek@odoo.com>