[FIX] l10n_be: create account tags while loading of demo data
When user install 'l10n_be' and load demo data,
a traceback will appear.

Steps to reproduce the issue:
- Install 'l10n_be'.
- Settings > Developer Tools > Load demo data

Error: A traceback appears:
'ValueError: External ID not found in the system: account.demo_capital_account'

https://github.com/odoo/odoo/blob/5a535d3ac90092f682ea0cb5802c7629102f53aa/addons/l10n_be/demo/account_demo.py#L14
Here, account tags is still referenced.
When demo data will load, it will not find the external_id of account tags,
So it will lead to above traceback.

sentry-4057974589