[FIX] web: Fix grouping on view with expand
Since 26c37c9c070107f8bd753cb8a6d8343384fdd7bf, when performing nested Group
By on a view with expand = True, a traceback was raised when applying 2 or more groups.

  File "/home/odoo/Documents/odoo_projects/odoo/addons/web/models/models.py", line 447, in web_read_group
    self._add_groupby_values(groupby_read_specification, groupby, groups)
  File "/home/odoo/Documents/odoo_projects/odoo/addons/web/models/models.py", line 480, in _add_groupby_values
    id_label[0] for group in current_groups if (id_label := group[groupby_spec])
                                                            ~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

This was because we expected 'group' to be a dict, but it was a string.
This commit change the 'group' creation, by adding the right dict in it.

no-task

X-original-commit: f49ab245c732928ebce1d301e5e4ca948098eaef