[FIX] requirements: with Python >= 3.8 passlib >= 1.7.2 is required on Windows
From Python 3.8, the `time.clock()` function has been definitively removed,
leading to the following `passlib` issue on Windows:
`ImportError: cannot import name 'clock' from 'time' (unknown location)`.

This point has been fixed in `passlib` `1.7.2`.

Due to https://github.com/odoo/odoo/pull/51784, this passlib version update,
is only done from Odoo 13.0.