Cherry pick of 7015096eb937f20a6a66010f54b18aedec48a5b2 failed
stdout:
Auto-merging addons/mrp_subcontracting/models/stock_move.py
CONFLICT (content): Merge conflict in addons/mrp_subcontracting/models/stock_move.py
Auto-merging addons/mrp_subcontracting/tests/test_subcontracting.py
CONFLICT (content): Merge conflict in addons/mrp_subcontracting/tests/test_subcontracting.py
Auto-merging addons/mrp_subcontracting/wizard/change_production_qty.py
CONFLICT (content): Merge conflict in addons/mrp_subcontracting/wizard/change_production_qty.py
Auto-merging addons/stock/models/stock_move.py

stderr:
20:36:52.935104 git.c:463               trace: built-in: git cherry-pick 7015096eb937f20a6a66010f54b18aedec48a5b2
error: could not apply 7015096eb937... [FIX] mrp_subcontracting: set larger done quantity
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: