[FIX] account: prevent error when importing product records with tax values
This error occurs when user import the product record.

Steps to Reproduce:

 - Install the stock and account modules.
 - Go to Products > switch to List View, select a product, and click Export
   under the Actions.
 - In the Available Fields, search for Sales Taxes or Purchase Taxes,
   select either one, and then click Export.
 - In the Products, click Actions > Import Records, and upload the file
   that was recently exported.
 - Click import.

TypeError: Domain() invalid argument type for domain: None

This error occurs when a user imports a product template record and the
system calls name_search to resolve tax_id values. When no domain is passed,
it defaults to None, causing a TypeError.

This commit ensures that when the system calls name_search to resolve
tax_id values without a domain, an empty domain ([(1, '=', 1)]) is used
instead to prevent the error.

sentry-6616172972

closes odoo/odoo#211053

X-original-commit: d82a81d5b9beedc3ed684cde06c8eb85b3451f63
Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>