[FIX] spreadsheet: missing lang
If for some reason there is no lang set on the user, the spreadsheet
locale would not have been able to determine the `dateFormat` and
`timeFormat`

```
  File "/home/odoo/git/odoo/enterprise/spreadsheet_edition/models/spreadsheet_mixin.py", line 96, in join_spreadsheet_session
    "user_locale": self.env["res.lang"]._get_user_spreadsheet_locale()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/git/odoo/odoo/addons/spreadsheet/models/res_lang.py", line 27, in _get_user_spreadsheet_locale
    return lang._odoo_lang_to_spreadsheet_locale()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/git/odoo/odoo/addons/spreadsheet/models/res_lang.py", line 36, in _odoo_lang_to_spreadsheet_locale
    "dateFormat": strftime_format_to_spreadsheet_date_format(self.date_format),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/git/odoo/odoo/addons/spreadsheet/utils.py", line 49, in strftime_format_to_spreadsheet_date_format
    for part in re.finditer(r"(%.)", strf_format):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 223, in finditer
    return _compile(pattern, flags).finditer(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'bool'
```