[FIX] discuss: allow message id to be pinned messages
Somehow 'message_id' holds the floating values, so while we are going
to pin the message will generate the traceback.

Error: InvalidTextRepresentation: invalid input syntax for type integer: 16.01
LINE 1: ...s_partner_id = 3) WHERE ((((mail_message.id = '16.01')

Therefore, if we convert message_id into an integer it will prevent the traceback.
if message_id has float values.

sentry-4307398197