Cherry pick of b24a16f547e7e03f9d4a5de79048e3633676df9e failed
stdout:
Auto-merging addons/l10n_at/data/account_tax_template.xml
CONFLICT (content): Merge conflict in addons/l10n_at/data/account_tax_template.xml

stderr:
15:17:24.627428 git.c:463               trace: built-in: git cherry-pick b24a16f547e7e03f9d4a5de79048e3633676df9e
error: could not apply b24a16f547e7... [FIX] l10n_at: multiple commits about improving tax templates
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: