Cherry pick of 12df56ccf7a69c0533cab04c7be88b250133f92e failed
stdout:
Auto-merging addons/l10n_it_edi/i18n/it.po
Auto-merging addons/l10n_it_edi/i18n/l10n_it_edi.pot
Auto-merging addons/l10n_it_edi/models/account_move.py
CONFLICT (content): Merge conflict in addons/l10n_it_edi/models/account_move.py

stderr:
18:51:06.779864 git.c:463               trace: built-in: git cherry-pick 12df56ccf7a69c0533cab04c7be88b250133f92e --strategy ort
error: could not apply 12df56ccf7a6... [FIX] l10n_it_edi: add warning for public administration
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: