[FIX] account_accountant: writeoff date should be off type date
Steps to follow

  - Have unreconciled entries
  - Go to General Ledger
  - Filter -> Unreconciled
  - Select one, action -> Reconcile
  - Manual operations -> click on write-off date
  - Hit enter while there is calendar
  -> TypeError: value.isSame is not a function

Cause of the issue

  The Writeoff Date field is declared as type char
  FieldDate._onKeyDown calls _parseValue and returns a string

opw-2820370
https://www.odoo.com/web#view_type=form&model=project.task&id=2820370

closes odoo/odoo#91119

Signed-off-by: William André (wan) <wan@odoo.com>