[FIX] hr_holidays: prevent errors when creating group time off
Currently, an error occurs when a user tries to create a group time off.

Steps to Reproduce:
 - Install the hr_presence module without demo data.
 - Make sure there are at least two employee records.
 -  Go to Employees and switch to the list view.
 - Select both employees > click Presence Control > click Create a Time Off.

Error1:
TypeError: unsupported operand types in: hr.work.entry.type() | None

Erro2:
AttributeError: 'NoneType' object has no attribute 'ids'

When a user creates a group time off record and the wizard is opened, it
computes the valid work entry types. If no work entry type exists, accessing
the `True` key (`requires_allocation`) from the empty dictionary returns
None [1]. Later, when performing a union (|) between an empty work entry
type recordset and None, it raises the first error [2].
Additionally, accessing ids on None raises the second error [3].

This commit ensures that when no work entry type exists, accessing
key(requires_allocation) from an empty dictionary returns an empty
work entry type record instead of None.

[1]: https://github.com/odoo/odoo/blob/374f48cfba75ff98f53d8c3fcc51847711bd406a/addons/hr_holidays/wizard/hr_leave_generate_multi_wizard.py#L144-L145

[2]: https://github.com/odoo/odoo/blob/374f48cfba75ff98f53d8c3fcc51847711bd406a/addons/hr_holidays/wizard/hr_leave_generate_multi_wizard.py#L146

[3]: https://github.com/odoo/odoo/blob/374f48cfba75ff98f53d8c3fcc51847711bd406a/addons/hr_holidays/wizard/hr_leave_generate_multi_wizard.py#L148

sentry-7552717400

closes odoo/odoo#270302

Signed-off-by: Mathias Lebel (lebm) <lebm@odoo.com>