Cherry pick of f1d72e17276c7572f8bd7bd2e0e2e64cdb89ee4a failed
stdout:
Auto-merging addons/website/static/src/js/editor/snippets.options.js
Auto-merging addons/website/static/src/js/editor/wysiwyg.js
CONFLICT (content): Merge conflict in addons/website/static/src/js/editor/wysiwyg.js

stderr:
19:12:53.311935 git.c:463               trace: built-in: git cherry-pick f1d72e17276c7572f8bd7bd2e0e2e64cdb89ee4a --strategy ort
error: could not apply f1d72e17276c... [FIX] website: always set the first carousel slide as the active one
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: