[FIX] base: prevent quick create of new field using studio
This error occurs when a user tries to create `quick create` a field.
steps to produce:
- Enable developer mode > Install the web_studio module.
- Go to Settings > Technical > Fields Selection.
- Create a new record > Open Studio > Drag and drop new many2one field
- Select the `fields` in Relation > Click on confirm and close the studio.
- Attempt to quick create a field for the new many2one field
- Error will be generated.

Error: AssertionError: missing model name for {'field_description': 'Loan'}

I handle this issue by adding usererror instead of using an assert statement.

sentry-4280377855