[FIX] mrp: prevent error when marking multiple manufacturing orders as done
Currently, an error occurs when user marks multiple Manufacturing Orders as Done.

Steps to Reproduce:
 - Install the mrp module.
 - Go to Settings and enable Units of Measure & Packagings.
 - Go to Products and create two products with different units of measure.
 - Go to Manufacturing Orders, create a manufacturing order by adding
   one of the products, and then create work order in the Work Orders section
   and confirm it.
 - Create another manufacturing order with the same quantity for the second
   product and add a Work Order for it as well and confirm it.
 - Go to the list view, select both orders, and click Mark as Done from the
   Actions menu.

ValueError: ValueError('Expected singleton: uom.uom(4, 6)') while evaluating
"if records:\n                res = records.filtered(lambda mo: mo.state in {'confirmed', 'to_close', 'progress'}).button_mark_done()\n                if res is not True:\n                    action = res"
ValueError: Expected singleton: uom.uom(4, 6)

After [this commit], which improves the performance of button_finish,
when a user marks multiple orders as done with the same quantity but
different uom , it creates all_vals_dict based on the vals[1] data as the key
and the work order as the value[2]. Then it  stores two or more work
orders with different UoMs under the same vals key. When attempting to
write multiple work orders[3], the precision rounding is calculated, which
raises the error[4] due to multiple UoMs.

The commit ensures that when writing records, precision_rounding is
calculated separately for each Work Order's UoM.

[this commit]: https://github.com/odoo/odoo/pull/223715/commits/b857d192085a38b612335223d04f8bdff91b898c

[1]: https://github.com/odoo/odoo/blob/186a9eb4a6c55c9c4c2178d4b2492a9a23a267fe/addons/mrp/models/mrp_workorder.py#L698-L703

[2]; https://github.com/odoo/odoo/blob/186a9eb4a6c55c9c4c2178d4b2492a9a23a267fe/addons/mrp/models/mrp_workorder.py#L706

[3]: https://github.com/odoo/odoo/blob/186a9eb4a6c55c9c4c2178d4b2492a9a23a267fe/addons/mrp/models/mrp_workorder.py#L708

[4]: https://github.com/odoo/odoo/blob/186a9eb4a6c55c9c4c2178d4b2492a9a23a267fe/addons/mrp/models/mrp_workorder.py#L477

sentry-7050854871

X-original-commit: cdff2a9a2eb8999f271d1a0312aaf612baa94232