[FIX] account: prevent error when removing bank accounts
Currently an error occurs when we try to remove bank accounts from a partner.

Steps to reproduce:
- Install accountant with demo data.
- Go to customers and create a new one with random name.
- Under accounting tab add a new bank account with an acc number, bank and save.
- Now remove the bank account record.

Error:
`AttributeError: 'NoneType' object has no attribute 'origin'`

Cause:
- The error occurs because of the SQL query [1] returning None values in the
 `id2duplicates` dict, somewhat like `{1: [None]}`, this caused the browse [2]
  to assign `None` to the `duplicate_bank_partner_ids`.
- While recording snapshots for diff checking in onchange system the none value
  will be stored like`None: {display_name:{}}` and when the line [3] tries to
  access `id_.origin` where `id_` is None and causes the error.

Solution:
- Added a condition which makes sure null values are not accounted.
 (The Join is added to makes sure that the correct `partner_id` is fetched.)

[1]: https://github.com/odoo/odoo/blob/04ba4e4a51843701dd42a3f0243add50b3ac0c79/addons/account/models/res_partner_bank.py#L71-L85

[2]: https://github.com/odoo/odoo/blob/04ba4e4a51843701dd42a3f0243add50b3ac0c79/addons/account/models/res_partner_bank.py#L88

[3]: https://github.com/odoo/odoo/blob/04ba4e4a51843701dd42a3f0243add50b3ac0c79/addons/web/models/models.py#L1173

sentry-6748249363

closes odoo/odoo#219455

Signed-off-by: Antoine Dupuis (andu) <andu@odoo.com>