[ADD] pos, pos_product_expiry: handle lot expiration date in POS
Installing POS with Lots & Serial Numbers enabled raises an error when
selecting a product that uses lots.

Steps to Reproduce:
- Install POS (with demo data).
- Activate "Lots & Serial Numbers".
- Open Furniture Shop > Select "Drawer".

Error:
AttributeError - 'stock.lot' object has no attribute 'expiration_date'

Cause:
The commit (ref 1) adds functionality from the product_expiry module to POS.
However, the module is not included in the dependencies, leading to an error.

Fix:
This commit adds a bridge module between `point_of_sale` and `product_expiry`.
And update the result, only when the expiry feature is enabled.

ref 1: https://github.com/odoo/odoo/pull/236456/changes

sentry-7203789966