[FIX] website_slides: fix datetimeObj.getTime is not a function
HOW TO REPRODUCE
================

- Don't need to login
- From Odoo front-end, go to Courses > Trees, Wood and Gardens >
    Main Trees Categories
- You get the following client error:
    Uncaught Promise > datetimeObj.getTime is not a function

HOW TO SOLVE:
============

Unlike standard JS equivalent, luxon datetime objects don't have a
getTime() function. Replace it by valueOf() function.
Also, remove calls to `DateTime.fromJSDate().formatting_fn()` by
luxon equivalent functions.

see a25e49d44d36d6fd10af48fdc67b24d20ce2e321

task-3632077

closes odoo/odoo#147165

X-original-commit: 657d5493f8a0f42cdbc6a4c598361d6366aef812
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>