[FIX] website_sale: don't add a product in GMC if it's not available for sale
Currently an error is generated when the user tries to open the
XML file of the product feed to Google.

Steps to produce:
- Go to settings and enable `Google Merchant Center Data Source`
- In settings, enable `Prevent Sale of Zero-Priced Product`
- Create a product with a 0 price and publish the website
- Go to website settings and click the `Copy file link` button from
 `Google Merchant Center Data Source`
- Open copied link  >>>  error generated

Error: `XPathEvalError: Undefined namespace prefix`

This is because the method `_prepare_gmc_price_info` tries to add a `price`
key in the dict of the product in GMC XML, but to prevent sale when the product
has a zero price, it does not add a price to the GMC info at code line [1].

This commit will fix the above issue by not adding product into GMC info when
the price is available in the product.

[1]- https://github.com/odoo/odoo/blob/2efb56381c4030aee246074e1318aa1c35d40eec/addons/website_sale/models/product_product.py#L305-L306

sentry-6658754370

closes odoo/odoo#213435

X-original-commit: 8edf50cdc1677aecb550b17d2c1f4cc4574130fa
Signed-off-by: Lionel Piraux (lipi) <lipi@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>