[FIX] website_slides: prevent error if slide not found
When users try to access a 'slide ID' that is not included in
'channel_slides_ids', a traceback occurs.

Steps to reproduce:
- Install 'website_slides' module
- Go to the Website and click on the 'Courses' menu.
- Then go to '/slides/embed/<int:slide_id>' route.eg(http://localhost:8069/slides/embed/7)
- The error will occur.

Traceback:
ValueError: 7 is not in list

At [1], 'slide_content_ids' contains the IDs of 'channel content'. However,
we are trying to access a slide from the 'channel category' in URL.
As a result, at [2], when attempting to find the index of the slide in
'slide_content_ids', an error occurs because the slide ID actually belongs
to 'slide_category_ids' and is not present in 'slide_content_ids'.

Solution:
Added a special case for category slides — if the slide is a category,
redirect to the channel homepage.

[1]- https://github.com/odoo/odoo/blob/482bb19e103de9ddbe1b1942b94b33d3da38889b/addons/website_slides/controllers/main.py#L120
[2]- https://github.com/odoo/odoo/blob/482bb19e103de9ddbe1b1942b94b33d3da38889b/addons/website_slides/controllers/main.py#L121

sentry-6572999628

X-original-commit: 7957ec690284e061f801bf9ff2b5258f29c5b76f