[FIX] mail: handle response on uploading encrypted pdf file
The test_first_page_access_of_mail_attachment_pdf test is failing on runbot.

Error:
FAIL: TestDiscussAttachmentController.test_first_page_access_of_mail_attachment_pdf
Traceback (most recent call last):
  File '/data/build/odoo/addons/mail/tests/discuss/test_discuss_attachment_controller.py', line 82, in test_first_page_access_of_mail_attachment_pdf
    self.assertEqual(response.status_code, 415)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 200 != 415

Root cause:
The test expects a 415 status code when accessing the first page of encrypted
PDFs. When PyPDF2 and PyCryptodome are installed, the response
returns 200, causing the assertion to fail.

Fix:
Update the test to accept both 415 and 200 as valid status codes.

This commit fixes test failures caused by https://github.com/odoo/odoo/pull/230713

runbot-233411

closes odoo/odoo#231682

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>