[FIX] stock_account: prevent change of valuation logic of a done SML
For now, a user chan change the locations of a done SML, making it
valuable while it was not (or the opposite), which leads to a broken
stock valuation.

To reproduce the issue:
1. In the Settins, enable
   - Automatic Accounting
   - Storage Locations
2. Create a product category C
   - Method: FIFO
   - Valo: Auto
3. Create a product P
   - Inventory tracked
   - Category P
   - Cost $1
4. Update its quantity
   - 10 x P at WH/Stock
5. Inventory > Reporting > Moves History, open SML related to P
6. Update the SML:
   - From: WH/Stock
   - To: WH/Stock/Shelf 1
   - Quantity: 100
7. Inventory > Reporting > Locations, look for P
   - There are two lines
     - -100 at WH/Stock
     - 100 at WH/Stock/Shelf 1
   - And, therefore, the total on hand is 0, which makes sense
8. Inventory > Reporting > Valuation, look for P

Error: There are two lines, one that adds $10 to the valuation (from
step 4) and a second one that adds $90. This is incorrect, the SML
is now an internal move and should not add any value to the stock.
In fact, the first line should even be cancelled

Letting the user changes a done SML can be convenient, but he should
not be able to change the locations as he wants since the code does
not handle all cases.

OPW-4275417

closes odoo/odoo#190910

X-original-commit: ca11a1fc00ac45d640143bbc4a3ab86526e8efe7
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>