[FIX] base: Prevent browsing falsy res_id `ir.model.data`
linked to https://github.com/odoo/odoo/pull/245469, there is another
case in the uninstallation flow that can raises a traceback in case of
a `ir.model.data` where `res_id = 0`

This commit adds an additional filter to the domain used to browse `ir.model.data`
in `_module_data_uninstall` in order to avoid selecting any that would
contain a falsy `res_id` and thus cause the above-mentioned assertion to
fail.

One way to reproduce this in a new trial:
- Create a new trial with several modules: `account`, `crm`, `project`, `sales`
- Install `web_studio`
- Uninstall `base_automation`
- Traceback
```
  File “/home/odoo/src/odoo/saas-19.1/odoo/orm/models.py”, line 5200, in browse
    assert all(ids) or all(isinstance(x, NewId) or x for x in ids), “Invalid falsy real id”
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid falsy real id
```

This is due to an `ir.model.data` containing a falsy res_id in the internal code of `saas_trial` (`installed-17`)

This fix will avoid any additional traceback like this one.

opw-5865316

closes odoo/odoo#245955

X-original-commit: 26326f5230aced891c84f31e9e92a3ba191f82c9
Signed-off-by: Krzysztof Magusiak (krma) <krma@odoo.com>