[FIX] account: prevent error when removing accounting date from invoice bill
Currently, An error occurs when removing an `Accounting Date` from the invoice
bill form view.

Steps to produce:

- Install the 'account' module (with demo data).
- Go to Invoicing / Vendors / Bills.
- Create a bill, remove value from the Accounting Date, and click anywhere in
form view.

AttributeError: 'bool' object has no attribute 'year'

An error occurs when the system tries to get a year part from the accounting
date [1], but the value of accounting date is missing.

Link 1: https://github.com/odoo/odoo/blob/a0205ffa3d4a42321a41503b8056a9f1c89328bb/addons/account/models/account_move.py#L3522

If the accounting date is not available, then provide a default value as an
invoice date or today's date to resolve an issue.

Sentry-6188666136

closes odoo/odoo#202176

X-original-commit: bfe75f657282ed79ebd7b71bd4046f1b52ef053e
Signed-off-by: John Laterre (jol) <jol@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>