[FIX] l10n_sa_edi: prevent error while generate invoice for pos order
When a user tries to validate an invoice of the POS order a traceback will
occur.

Steps to produce:

- Install 'l10n_sa_edi', 'point_of_sale', and 'contacts' modules.
- Switch to a 'SA Company' company.
- Open 'Point of Sale' and create and open New Session.
- Select any products (with customer taxes )> payment > Select payment method
> Invoice > Select individual customer > Validate error will generated
in the backend.

AttributeError: 'bool' object has no attribute 'encode'

This is because 'signature' is 'False' at [1] while generating an invoice for
an order and a system tries to encode it.

link [1]: https://github.com/odoo/odoo/blob/149a2acea96cff14990b667ee611c3afbdc146f2/addons/l10n_sa_edi/models/account_move.py#L115

This commit solves the above issue by adding a condition if 'signature'
is 'False'  then encodes a blank string.

sentry-5482247880

closes odoo/odoo#169407

Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>