[FIX] stock: add locations id to stock_move context in shop floor
Steps to reproduce issue:

1. Create a Product with Lots/Serials tracking
2. Create a BoM with an operation and add Product as By-Product
3. Create a Manufacturing Order using the BoM, click on Confirm then Plan
4. Go to Shop Floor, click on "Register [the By-Product]"
    - Not the button with the units
5. Click on either "Import Lots" or "Generate Serials"
6. Enter a Lot/Serial number and click on "Generate"
7. Traceback error:

>         loc_dest = self.env['stock.location'].browse(default_vals['location_dest_id'])
>     KeyError: 'location_dest_id'

Explanation:

When going through the Shop Floor, the context is missing a lot of elements that are normally passed in the manufacturing order form.
https://github.com/odoo/odoo/blob/338173e231355d265ddc88bcef5e9b0a608e248e/addons/mrp/views/mrp_production_views.xml#L432-L437

Suggested fix:

`default_dest_location_id` is the missing element causing the traceback but `default_location_id` is also required to create a `stock_move_line`.
Fix in Community, test in Enterprise.

opw-3719439

closes odoo/odoo#157922

X-original-commit: 2915f6da6d832ad0f2f8402bb3abe1e8139604b5
Related: odoo/enterprise#58796
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Stroobant Paul (stpa) <stpa@odoo.com>