[REM] /web/report is not used and doesn't work
it raises error because dispatch_rpc method doesn't handle case when
service_name is equal to 'report'

Traceback (most recent call last):
  File "/mnt/odoo-source/addons/web/controllers/main.py", line 74, in wrap
    return f(*args, **kwargs)
  File "/mnt/odoo-source/addons/web/controllers/main.py", line 1511, in index
    action["report_name"], report_ids, report_data, context])
  File "/mnt/odoo-source/odoo/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
UnboundLocalError: local variable 'dispatch' referenced before assignment