[FIX] l10n_ch:  display qr bank options in ch localization
When a user having CH Company tries to Add a Bank Accout then they will face the
issue.

Steps to produce:
- Install `l10n_ch`.
- Change company to CH Company.
- Invoicing > Configuration > Banks > Add a Bank Account.

Applying this commit will solve the issuse by allowing the user having
CH Company to add a bank accout. The user was facing the issue because
of the code:
https://github.com/odoo/odoo/blob/2476a3ae2e3ed66875a2ea855be640d127b58cf2/addons/l10n_ch/wizard/setup_wizards.py#L21
In above code `self` is passed in as an arguement in the compute function
while calling the function which is invalid.

Error: `TypeError: ResPartnerBank._compute_l10n_ch_display_qr_bank_options()
takes 1 positional argument but 2 were given`

sentry-4389863088

closes odoo/odoo#132779

Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>