[FIX] account: tax tag invert for manual reconciliation entry
Setup a CH company
Create a new invoice with switzerland partner
Add a product and tax 7.7%
Confirm
Go to Accounting > Customers > Followup reports.
Remove the filters, open the invoice, then click reconcile.
In the reconciliation widget, select invoice and record the manual
operation:
- Account: 3805 Losses from bad debts
- Taxes: 7.7% Sales
- Journal: Miscellaneous operations
- Label: Loss
- Tax Included in Price: True
Click on reconcile
Open the jounrnal entry corresponding to the manual operation

Error: the tax grid on the tax account has been correctly inverted,
while the tax grid on account 3805 Losses from bad debts is not
inverted, so it account as an invoice

opw-2819575