[FIX] mrp, mrp_repair: check uniqueness of SN used in MO, repair and unscrapped
Suppose a tracked-by-usn and consumed product returns in the stock
thanks to a repair order. Using again this component in a new
manufacturing order will raise an error

Steps to reproduce:
1. Enable mutistep routes in the settings
2. Create two products P_finished, P_comp
    - Storable
    - P_comp tracked by USN
3. Update the quantity of P_comp:
    - WH/Stock: 1 x Lot01
4. Create a manufacturing order MO:
    - Product: P_finished
    - Components:
        - 1 x P_comp
5. Confirm, Check availability and Mark MO as Done
    - (Lot01 should be consumed)
6. Create a repair order RO:
    - Product: P_finished
    - Remove:
        - Product: P_comp
        - Lot: Lot01
        - Destination Location: Virtual Location/scrap
7. Confirm RO, Start RO, End RO
8. Unscrap 1 x Lot01 (via an internal transfer from scrap to stock)
9. Repeat 4-5

> Error: a user error is raised: "The serial number SN used for component
P_compo has already been consumed"

Cause of the issue:
As the Lot01 has already been used in a MO, it is detected here:
https://github.com/odoo/odoo/blob/683c02b099ac616cba747e5bba1cebb126e5f8ed/addons/mrp/models/mrp_production.py#L1958-L1963

To determine if an error should be raised, we therefore need to account
the various moves related to our lot.

1. Since we did not unbuild our MO nor put back our Lot in stock from a
   repair: duplicates_returned is correctly set to 0.

2. Since we didn't srcap our lot via an internal transfer:
   removed is correclty set to 0.

3. Since we did unscrap our lot manually via an internal transfer:
   unremoved is correclty set to 1.

However, the condition to raise the error using these value is not
correct here:
https://github.com/odoo/odoo/blob/0505bda68052a3665f0d8dae28fa64864a1e2951/addons/mrp/models/mrp_production.py#L2239

First of all, since both "duplicates_returned" and "removed" are False
the error will be raised dispite the fact that we did indeed scrap
our lot using a repair.

This part of the condition use to correclty account for scrapping moves
prior to commit cf1051f but had to be updated in order to compute
correctly the seocnd part of the condition.

Second of all, while the relative signs of remove and unremoved are
correclty set in the conditions, their relative contribution to the
second part of the condition should be minus the contribution it is
namely if a lot is scraped by hand it should remove a lot (so should be
added to duplicates) and if a lot is unscrapped by hand it should be
added to lots (so should be subtracted to duplicates).

opw-3834835