[FIX] website_sale_stock: prevent traceback when quantity snippet is removed
steps to reproduce:
-------------------
1. Install website_sale_stock
2. Go to Website > Shop > Product (with inventory tracking enabled)
3. Click on Edit and remove the "Quantity" snippet
4. Save the changes

issue:
------
TypeError: Cannot read properties of null (reading 'value')

cause:
------
The code:
https://github.com/odoo/odoo/blob/6989f0d6bdab2f152996b0098806ac10124d1cc8/addons/website_sale_stock/static/src/js/variant_mixin.js#L35-L36
unconditionally accessed `addQtyInput.value`
This raises an error when the "Quantity" snippet has been removed,
since addQtyInput is null.

solution:
---------
Check if `addQtyInput` exists before accessing its value.

Co-authoured by loti@odoo.com

opw-5095486

closes odoo/odoo#228086

Signed-off-by: Louis Tinel (loti) <loti@odoo.com>