[FIX] hr_attendance: prevent error when creating an attendance for employee
Currently, an error occurs when a user creates an attendance for an employee.

Steps to Reproduce:
 - Install the hr_attendance module.
 - Go to Overtime Rulesets and create a new overtime ruleset by adding an
   overtime rule.
   Set Based on to Timing.
   Set the Start time greater than the Stop time (ex, Start = 10 and Stop = 5).
 - Go to Employees, open any employee record, and assign this Overtime
   Ruleset to the employee.
 - Now go to Attendances and create an attendance for that employee.

TypeError: '>' not supported between instances of 'datetime.datetime' and 'int'

This error occurs when a user sets the overtime rule on an employee and
then creates an attendance. At that point, the system tries to calculate
the overtime intervals based on the timing rule. Because the rule’s start
time is greater than the stop time, it attempts to calculate the interval for
the remaining working period of the day. However, the start date and
end date are calculated in datetime format [1], while integer and float
values are passed as arguments [2] for day in interval calulation. Since
the interval expects values of the same data type, than it raise the error [3].

This commit ensures that the day start and day end values are passed in
datetime format.

[1]: https://github.com/odoo/odoo/blob/67191cf0915081df352331a698be47b7e3ecd505/addons/hr_attendance/models/hr_attendance_overtime_rule.py#L524

[2]: https://github.com/odoo/odoo/blob/67191cf0915081df352331a698be47b7e3ecd505/addons/hr_attendance/models/hr_attendance_overtime_rule.py#L530

[3]: https://github.com/odoo/odoo/blob/67191cf0915081df352331a698be47b7e3ecd505/odoo/tools/intervals.py#L138-L154

sentry-7166788786

closes odoo/odoo#242491

Signed-off-by: Mélanie Peyrat (mepe) <mepe@odoo.com>