[FIX] mail: mail.message create on no user
Since [this](https://github.com/odoo/odoo/commit/24aab53406ba1a7f46b75cd05a899bb25f596122) change, `mail.message.create()` and `.write()` break when
self.env.user is None. This can happen when a route with `auth="none"` is used
and a similar traceback to the following will be returned:

```
`2026-01-06 09:07:27,903 13 ERROR paas_master odoo.addons.paas_master.controllers.controllers: Failed sync: Expected singleton: res.users()
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 6269, in ensure_one
    _id, = self._ids
    ^^^^
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/paas/paas_master/controllers/controllers.py", line 2523, in build_sync
    request.env.cr.commit()
  File "/home/odoo/src/odoo/18.0/odoo/sql_db.py", line 482, in commit
    self.flush()
  File "/home/odoo/src/odoo/18.0/odoo/sql_db.py", line 160, in flush
    self.precommit.run()
  File "/home/odoo/src/odoo/18.0/odoo/tools/misc.py", line 1172, in run
    func()
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 548, in _track_finalize
    tracking = records.with_context(context)._message_track(fnames, initial_values)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 661, in _message_track
    record._message_log(
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 2813, in _message_log
    return self._message_log_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 2872, in _message_log_batch
    return self.sudo()._message_create(values_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 2973, in _message_create
    ).create(create_values_list)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-75>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 498, in _model_create_multi
    return create(self, arg)
           ^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/paas/paas_master/models/mail.py", line 17, in create
    return super().create(values_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-50>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 498, in _model_create_multi
    return create(self, arg)
           ^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_message.py", line 597, in create
    if not (self.env.user.has_group('base.group_user') or self.env.su):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/res_users.py", line 1200, in has_group
    self.ensure_one()
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 6272, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.users()
2026-01-06 09:07:27,920 13 INFO paas_master werkzeug: 192.168.56.106 - - [06/Jan/2026 09:07:27] "POST /paas/build/sync HTTP/1.0" 200 - 22 0.005 0.024

```

That can be easily tested by calling a custom `auth='none'` route like the following:

```
diff --git a/addons/web/controllers/home.py b/addons/web/controllers/home.py
index 6138caf9660d..fc20d9e30ca7 100644
--- a/addons/web/controllers/home.py
+++ b/addons/web/controllers/home.py
@@ -40,6 +40,11 @@ class Home(http.Controller):
     def _web_client_readonly(self):
         return False

+    @http.route("/auth_none_test", auth="none")
+    def auth_none_test(self):
+        import uuid
+        request.env.ref("base.partner_admin").sudo().name = str(uuid.uuid4())
+
     # ideally, this route should be `auth="user"` but that don't work in non-monodb mode.
     @http.route(['/web', '/odoo', '/odoo/<path:subpath>', '/scoped_app/<path:subpath>'], type='http', auth="none", readonly=_web_client_readonly)
     def web_client(self, s_action=None, **kw):
```

The fix is to reverse the order of the checks because the only use cases we
have for a route in `auth="none"` are done in sudo so the condition is escaped
before the group check is done on `self.env.user`.

task-none