[FIX] spreadsheet_dashboard_sale: remove none related field from domain
Currently an error occurs in the log when the user tries to open dashboard

Steps to Reproduce:
1. Install the spreadsheet_dashboard_sale module
2. Navigate to Dashboards > Sales Dashboard.
3. Open or click on Edit for the Sales Spreadsheet Dashboard.

Error:
ValueError: Invalid field product.template.recurring_invoice in condition
('recurring_invoice', '!=', True)

Cause:
The recently added commit [1] adds a domain using the
`product_tmpl_id.recurring_invoice` field. However, this field belongs to
the `sale_subscription` module, which is not a dependency of the current module.

Fix:
Remove the non-existing `product_tmpl_id.recurring_invoice` field filter from
the domain

[1]: https://github.com/odoo/odoo/commit/10fe64e63987b93e42e28cc6fb8319af326ab8be

sentry-7752145163

closes odoo/odoo#290507

Signed-off-by: Pierre Rousseau (pro) <pro@odoo.com>