[FIX] website: fail test inde when you edit an image
The goal of this commit is to fix the indeterminate tests related
to image editing in the website builder.

Problem:
=====
Some tests related to image editing on the website fail in an indeterminate
manner. This test failure is related to the sidebar's async. When selecting
an image, the Image options need to fetch certain data (the original image, etc.).
The “html_editor.assets_image_cropper” bundle is also loaded. This loading
time can exceed 200 ms, causing the test to fail unpredictably.

Solution:
======
1.Preload the “html_editor.assets_image_cropper” bundle and store it in the cache.
2. Use `waitSidebarUpdated` when selecting an image.
   `waitSidebarUpdated`` will wait until all the data is loaded and
   the sidebar is updated. This solution is not optimal, but it will make
   all the tests deterministic.

The best solution:
=========
We should mock or preload all the data needed for the tests.
This change requires adapting the current production code to make it easily
patchable to mock, for example, “.text()” on a response to an image fetch.

Error: https://runbot.odoo.com/odoo/error/232956
Part-of: odoo/odoo#234312
Signed-off-by: Benoit Socias (bso) <bso@odoo.com>