[FIX] product: fix "test_pricelists_res_partner_form"
Many single runbot builds fail due to the
test_pricelists_res_partner_form test introduced
by https://github.com/odoo/odoo/pull/163768:

FAIL: TestPricelist.test_pricelists_res_partner_form
Traceback (most recent call last):
  File "/data/build/odoo/addons/product/tests/test_pricelist.py", line 168, in test_pricelists_res_partner_form
    self.assertEqual(partner_form.property_product_pricelist, default_pricelist)
  File "/data/build/odoo/odoo/tests/form.py", line 307, in __getattr__
    return self[field_name]
  File "/data/build/odoo/odoo/tests/form.py", line 312, in __getitem__
    assert field_info is not None, f"{field_name!r} was not found in the view"
AssertionError: 'property_product_pricelist' was not found in the view

This happens because `group_product_pricelist` is
not activated during the test, and then the form
doesn't contain 'property_product_pricelist' field.

Activate the feature in the setUpClass to fix
this issue.