Cherry pick of afaf395abae6c6acbb7b8b78bade4f39e16d411e failed
stdout:

stderr:
error: could not apply afaf395abae... [MOV] website_event(_online): move registration / reminder templates in their own file
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'