[FIX] stock: give correct field name to prepare stock return picking
This traceback arises when the user click on return button.

To reproduce this issue:

1) Install 'stock'
2) Activate 'Multi-Step Routes' from 'Inventory/configuration/settings'
3) Create a new product with quantity 100
4) Create a new record in 'Operations/Deliveries'
5) Select the created product in 'operations' with 'Demand' as 10
6) Click on 'Validate' button and then 'Return' button
7) Again click on 'Return' button

Error: 'KeyError: 'reserved_qty''

See: https://github.com/odoo/odoo/blob/c2b160fe50c24e9f01d0d5b350f2422cfdbc72d4/addons/stock/wizard/stock_picking_return.py#L86

Because the 'reserved_qty' field is removed from this pr:- https://github.com/odoo/odoo/pull/137864

sentry-4621794958

X-original-commit: c05fe1e26d728167097e46b338152bd96153089a