[FIX] mail: prevent error when sending mass mail without mail.thread
An AttributeError occurs when sending a mass email on a model that does not
inherit `mail.thread`.

Steps to reproduce:
1. Install the website_slides module with demo data.
2. Open an eLearning course.
3. Click the Attendees smart button.
4. Select one or more attendees.
5. Click Action → Send Email.
6. Open the template menu and select an email template.
7. Fill in the Reply To field.
8. Click Send.

Error:
AttributeError: 'slide.channel.partner' object has no attribute
_notify_get_classified_recipients_iterator

Cause:
A recent commit added [1] the 'Send Email' action to the `slide.channel.partner`
list view. However, this model does not inherit `mail.thread`. Because of this,
it is missing the `_notify_get_classified_recipients_iterator` method required
by the mail composer, causing a crash.

Fix:
Use `isinstance` to safely and accurately check if the record inherits
`mail.thread`. If it does not, fall back to an empty `mail.thread` recordset.
This simply returns blank results to avoid the crash, and will not cause any
other errors.

[1]:https://github.com/odoo/odoo/blob/4567628d3fa917fa7735cd87dcfbaa91f7e07ce7/addons/website_slides/views/slide_channel_partner_views.xml#L143-L151

sentry-7760936082