[FIX] hr_holidays: open employee's time off
It's currently impossible to open the employee's time off

To reproduce the issue:
1. Open an employee form
2. Click on the smart button "Time Off"

Error: it leads to an "Odoo Server Error"

Clicking on the smart button leads to
https://github.com/odoo/odoo/blob/6bb302bc401f012836efb84c96d619d6d6f7dc3f/addons/hr_holidays/models/hr_employee.py#L33-L35
Where we eval this:
https://github.com/odoo/odoo/blob/4ad41c7fc98b3aa183d1da3d7a01831cd300f76d/addons/hr_holidays/views/hr_leave_views.xml#L751-L757
However, since `</field>` doesn't come right after the closing
bracket `}`, the end of the field value contains a new empty line.
As a result, when evaluating it, it gives an error:
```
{IndentationError}IndentationError('unexpected indent', [...]
```

Considering that
- The use case must be fixed asap (luckily the bug is not on prod
  yet, cf merge date of [1])
- Stable versions

We have decided to locally fix the issue. However, as discussed with
the ORM team, a better/generic fix should be brought on master.

[1] 4ad41c7fc98b3aa183d1da3d7a01831cd300f76d

closes odoo/odoo#212393

X-original-commit: df024844382afc2e43b2b23678173a97b97b55fc
Signed-off-by: Yannick Tivisse (yti) <yti@odoo.com>
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>