[FIX] repair: prevent error when clicking Unassign button
Clicking the Unassign button to unassign the repair order's move as the
destination of a picking's move results in an error.

Steps to reproduce the error:
- Install "repair" module
- Go to Settings > Unable Reception Report
- Create 2 products: Product A and Product B
- Create a Repair order
      - Product to Repair: Product A
      - In Parts, Add a line > Product: Product B > Demand: 1
- Confirm the repair order
- Go to Inventory > Operations > Receipts > Create a receipt
      - In Operations, Add a product > Product: Product B > Demand: 1
- Click on Mark as To Do
- Click on Allocation smart button > Assign All > Unassign

Traceback:
"AttributeError: 'repair.order' object has no attribute '_remove_reference'"

https://github.com/odoo/odoo/blob/86c6f46ed0df225cad55b5a81b0bd5d47397f5d0/addons/stock/report/report_stock_reception.py#L358-L362
When the User clicks on Unassign button, "out_source" is the "repair.order"
record. The code then calls "_remove_reference()" method on this record.
However, the "repair.order" model does not have "_remove_reference()" method.
So, It will lead to the above traceback.

Solution:
Added the missing "_add_reference" and "_remove_reference" methods for
"repair.order" model.

sentry-7639973636