[FIX] mail: cannot read 'getMailboxCounter' of undefined
Before this commit, sometimes when opening Discuss app during page
loading, it throws the following error:

```
TypeError: Cannot read property 'getMailboxCounter' of undefined
```

This happens due to each thread creation in mail manager being
notifying to Discuss widget, which triggers a re-render of Discuss
sidebar. Discuss sidebar template assumes mailboxes always exist,
but that's not necessarily the case, especially during page load.

X-original-commit: 9508de6665556b6a09b184475273bb2b279ae223