[FIX] web: avoid traceback when deleting all grouped list entries
After this commit [1], deleting all entries of a grouped list may
trigger the following traceback:

```
TypeError: value[currencyField].forEach is not a function
```

This happens because the `currency_id` of an empty group becomes `0`, so
`forEach` is called on a non-iterable value.

This fix ensures that `currency_id` is correctly handled to prevent
such error.

[1] odoo@98f7462