Cherry pick of a132c627987cad81720aed8c4fe3ad2130665c33 failed
stdout:

stderr:
error: could not apply a132c627987... [REV] pos_adyen: avoid concurrent updates
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'