[FIX] base: avoid evaluating true domains when validating domain
During validating, the domain validation may trigger a
search on the comodel to ensure the domain is valid.

After [1], the validation still performs the search with Domain
True [here] because it ``search_domain`` is override because of
[comodel_domain] is False with ``Domain.True`` to handle this
checking if already ``search_domain`` is False or not

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-19.3/odoo/service/server.py", line 1643, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'], reinit_modules=config['reinit'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/func.py", line 67, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/odoo/orm/registry.py", line 224, in new
    load_modules(
  File "/home/odoo/src/odoo/saas-19.3/odoo/modules/loading.py", line 467, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/saas-19.3/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-19.3/odoo/modules/loading.py", line 61, in load_data
    convert_file(env, package.name, filename, idref, mode, noupdate=kind == 'demo')
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/convert.py", line 716, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/convert.py", line 815, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/convert.py", line 686, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/convert.py", line 639, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/saas-19.3/ai/security/security.xml:4
Invalid domain ['|', ('attachment_id.public', '=', True), ('attachment_id.res_access_read', '=', True)]: Cannot search, too many attachments

View error context:
'-no context-'
```

[here]: https://github.com/odoo/odoo/blob/4561e703128963d566a16ab1356c7ef12e44256a/odoo/addons/base/models/ir_attachment.py#L643
[1]: https://github.com/odoo/odoo/pull/260753
[comodel_domain]: https://github.com/odoo/odoo/blame/afca863b750ec58f5414a5d47e2e2a64e3eba598/odoo/orm/domains.py#L1440-L1442

upg-4248693
opw-6182400

X-original-commit: e7d01510f29315dccc17f1d1cc52bf6baba6c3d5
Part-of: odoo/odoo#264795
Signed-off-by: Krzysztof Magusiak (krma) <krma@odoo.com>
Signed-off-by: Sanchit Gupta (sagu) <sagu@odoo.com>