[FIX] mrp: add `stock.group_production_lot` to user in test
Versions
--------
- 18.0+

Steps
-----
1. Run `test_reservation_method_for_outgoing` without demo data.

Issue
-----
> AssertionError: 'lot_id' was not found in the view

Cause
-----
The `lot_id` field is only rendered if the current user has the
`stock.group_production_lot` group. This is only default when demo data
is installed.

Solution
--------
Add the group to the current user in `setUpClass`.

runbot-243588

closes odoo/odoo#266366

X-original-commit: 2680a0cccc634b778e6b15d078b614772aa7ebca
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>