[FIX] certificate: prevent an error while add keys in certificate
Currently, an error occurs when while adding a private/public key in the
certificate and key has no 'content' (Key file).

Step to produce:

- Install the 'certificate' module.
- Go to Settings, Click on 'certificates' which is in the Certificates and Keys
section
- Create a new certificate, add a name and valid certificate file.
- Create a 'Private Key' or 'Public Key' from the certificate form view
and try to save the record.

TypeError: argument should be a bytes-like object or ASCII string, not 'bool'

An error occurs because a user can directly create a certificate's
private/public key from the certificate form view without adding any content
that is required true in 'certificate.key' model, so an error occurs when the
system tries to decode the content of private/public key at [1], but it is
not available.

Link [1]: https://github.com/odoo/odoo/blob/2be7f413493a6ad43980eb031b8383deb3a706c0/addons/certificate/models/key.py#L157-L160

To resolve this issue, remove the 'create' option for private/public keys from
certificate form view

Sentry-5993525387

closes odoo/odoo#183870

Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>