[FIX] stock: avoid error when apply putaway strategy on packages
Steps to reproduce the bug:
- Create a storable product “P1” and “P2”
- Create two route:
    - route 1:
        - rule 1: Pull from “WH/Stock” to “WH/Stock/Shelf 1” -> Trigger another action
        - rule 2: Pull from “WH/Stock/Shelf 1” to “customer -> Trigger another action

    - route 2:
        - rule 1: Pull from “WH/Stock” to “WH/Stock/Shelf 2” -> Trigger another action
        - rule 2: Pull from “WH/Stock/Shelf 2” to “customer -> Trigger another action

- P1 -> route 1 + buy (add azure interior as vendor)
- P2 -> route 2 + buy (add azure interior as vendor)

- Create a SO:
     - vendor: Azure interior
    - One unit of P1 and P2

- Confirm the SO
- Go to the created PO
- Confirm the PO and go to the reception
- put in pack the products together
- Try to validate the picking.

Probelm:
An User Error is triggered:
ValueError: Expected singleton: stock.location(3694, 3696)

Because we have two moves with different destination locations, and
we are trying to set them in all the move lines.

opw-4291067

X-original-commit: 888cd502247282e6eb198c3afc33c61ec4d08f6b