[FIX] mail: mark messages as read when fetching mails
The refactor PR https://github.com/odoo/odoo/pull/191911 introduced
a nice/needed refactor of the fetchmail methods.

But in doing so a small logic error sneaked in.
More specifically:
This try/except/else block
https://github.com/odoo/odoo/blob/1f672b95a145b32d1ef2da9e83d82cd950045b5d/addons/mail/models/fetchmail.py#L305-L313
fails to account for the fact that in certain conditions a exception is expected
while the `message_process` methods try to match the mail content with Odoo
records.

One example:
If you fetch an email in the inbox that is addressed to an email address
that is **not** an email alias in the database, it will raise a ValueError.
Example:
```
ValueError: No possible route found for incoming message from "John Doe"
<john@example.com> to "Josephine" <mon_amour@odoolove.com>
(Message-Id <shrekislove@odoo.com>:). Create an appropriate mail.alias
or force the destination model.
```

It follows that the `else` block is never triggered and `handled_message`
will not be called, which would have marked the email in question as "READ".

This means, that the next time the fetchmail CRON job runs, it will retry
to refetch the same (failing) emails, which A) means lost time and processing
time for a non relevant email B) if the backlog of failing emails is important
enough, it will clog the mail fetching and we will never reach new emails.

Proposed fix:
Remove the else block, meaning that the `handled_message` get's called
even after an exception.

A this level of the stack we presume that any exception is either expected
or the results of a misconfiguration (mail flows or Odoo configuration).
So the mail was handled and should be marked a read in the mailbox being
fetched.

OPW-5122869

X-original-commit: 5e3f33b7e0836322c6853d749492720d20196124