[FIX] purchase_stock: update the PO qty without traceback
Steps to reproduce the bug:
- Create a storable product X1:
    - Route: MTO + buy
    - Vendor: Azure Interior
    - BoM:
        - Type: subcontractor
        - Subcontractor: Azure interior
        - Component: any component

- Create a MO:
    - product: P1
    - Component: X1, qty: 3
- Confirm the MO
- Go to the created PO
- Confirm the PO

- Go to the picking
- receive 2 units of P1 and validate it
- create a backorder
- Cancel the backorder
- Try to update the purchased qty in the PO line to 2

Problem:
A traceback is triggered:
File "/home/odoo/src/odoo/addons/purchase_stock/models/purchase.py", line 542, in _prepare_stock_move_vals
'picking_id': picking.id,
AttributeError: 'bool' object has no attribute 'id'

Solution:
When updating the quantity in the purchase order, if no picking requires
an update, it is better to avoid creating a new picking and new moves.

opw-3681064

closes odoo/odoo#152527

X-original-commit: 0da5d6cc0c94320ad39fe9b930dde4b0ef6feff5
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>