Cherry pick of f600d5fb6795ea990ab3976917a068d0d7d9abd9 failed
stdout:

stderr:
15:02:26.022837 git.c:344               trace: built-in: git cherry-pick f600d5fb6795ea990ab3976917a068d0d7d9abd9
error: could not apply f600d5fb6795... [FIX] website: target title tag inside <head>
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: