[FIX] account: check if code is null before match
```
  File "/home/odoo/src/odoo/19.0/addons/account/models/chart_template.py", line 432, in _pre_reload_data
    if not account or not re.match(f'^{values["code"]}0*$', account.code):
  File "/usr/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

The field `code` was changed from required to computed at this point:
https://github.com/odoo/odoo/commit/854c3b27aa5476c208572f19e64f8f3364bfc381#diff-19ef5a530c506fdee93fe0d113e61946b87fae7dd2d360558da69c0014f766b2L48

we now get some cases where the code is null during the `_pre_reload_data`
https://upgrade.odoo.com/odoo/tbg/2396