[FIX] account: prevent concurrent updates during email processing
Since https://github.com/odoo/odoo/commit/3916e310cfff4cad2f8938226290b6eb28205201,
in certain cases, customers sending large batches of emails to an accounting
email alias would report a small number of emails being bounced (ca. 5%).

Context:

1. While processing an email (after matching mail.alias, with the thread going
through `message_process`), if an error is uncaught and raised, the mailgate
generates a bounce email, as we presume that the email could not be processed
correctly.
2. When sending an email with an attachment to an accounting journal alias,
depending on the DB configuration, IAP calls for automatic OCR are triggered
asynchronously. These calls trigger callbacks from the IAP server, which might
hit the DB in parallel while another thread is processing another email. Given
their nature, they trigger updates on the relevant account.move, thus
triggering downstream computes in the model.
3. When processing an attachment, the account module triggers
`_extend_with_attachments`, which tries decoding the attachment in a rollback
context (see:
https://github.com/odoo/odoo/blob/43fc49ebc61fa5c987abd419da833edcc811f210/addons/account/models/account_document_import_mixin.py#L343-L344).
If a SerializationError happens during that process (concurrent update), it
will NOT use the retry mechanism of the ORM because the error is caught in the
`except Exception` block. Instead, it will try to post a message to the record
to inform the user that the attachment could not be processed.
4. The commit mentioned above changes the way `_update_sequence_made_gap`
works. One side effect seems to be that every time `made_sequence_gap` is
re-assigned (even if the value does not change per se), the ORM tries to
update the `write_date` on the flagged invoice that generated a sequence gap.

Bug:
Given the above context, emails might bounce unnecessarily for a valid email
alias and a valid email with an attachment if:

1. The journal is not using a slash-based sequence pattern (e.g., using "1234"
for the naming instead of "INV/2026/1234"). In that case, `sequence_prefix`
== "".
2. The first invoice does not start at "1".
3. When sending a burst of simultaneous emails in a multi-worker setup, each
thread will trigger `message_process` and downstream accounting computes while
processing the invoice. It will also trigger IAP calls and callbacks
asynchronously when automatic digitization is activated.
4. Each draft invoice that is created is named "/", meaning `sequence_prefix`
== "", which in turn re-triggers the checks in `_update_sequence_made_gap`.
5. This increases the chances dramatically of a serialization error while all
the parallel processes indirectly trigger an update on the `made_sequence_gap`
field of invoice "1234".
6. Most of the time, the serialization error is not triggered in the thread
processing the email, which correctly retries it. But in the few unlucky cases
where it is raised in the thread processing the email, it will be triggered in the
transaction rollback in `_extend_with_attachments`.
While handling the exception, it triggers a second error
because it tries to post a message to the record that was just rolled back:
-> `ERROR: current transaction is aborted, commands ignored until end of transaction block`
is raised in the thread running `message_process`, which
in turn triggers a bounce email.

Example logs (simplified):

```
2026-06-12 14:12:15 [Worker-Thread-101] INFO mail_thread: Routing email (1)
2026-06-12 14:12:15 [Worker-Thread-102] INFO mail_thread: Routing email (2)

2026-06-12 14:12:16 [Worker-Thread-101] INFO iap_tools: dispatching /parse
2026-06-12 14:12:16 [Worker-Thread-102] INFO iap_tools: dispatching /parse

2026-06-12 14:12:18 [Worker-Thread-101] INFO iap_tools: Webhook received,
triggering /get_result
2026-06-12 14:12:18 [Worker-Thread-102] INFO iap_tools: Webhook received,
triggering /get_result

2026-06-12 14:12:19 [Worker-Thread-101] INFO odoo.sql_db:
UPDATE "account_move" SET "made_sequence_gap" = true WHERE "id" = 1234
-> STATUS: OK (Acquired Row Lock)

2026-06-12 14:12:19 [Worker-Thread-102] ERROR odoo.sql_db: bad query:
UPDATE "account_move" SET "made_sequence_gap" = true WHERE "id" = 1234
ERROR: could not serialize access due to concurrent update
psycopg2.errors.SerializationFailure: could not serialize access

2026-06-12 14:12:19 [Worker-Thread-102] ERROR odoo.sql_db: bad query:
SELECT "mail_message"."id" FROM "mail_message" WHERE ...
ERROR: current transaction is aborted, commands ignored until end of
transaction block
psycopg2.errors.InFailedSqlTransaction: transaction is aborted

2026-06-12 14:12:19 [Worker-Thread-102] INFO "POST /saas_worker/smtp" 200
-> triggers Bounce email

```

Proposed Fix:
A) We update the conditions in `check_around` to ignore draft invoices when
they are the "previous" entity being checked. Only posted invoices should be
considered when doing the gap checks.
B) We add some guard clauses to prevent unnecessary writes to invoices that
created sequence gaps. Instead of assigning values directly, we store the
result of the check and only assign `made_sequence_gap` explicitly if the
value is different from the currently stored value. This prevents
unnecessary writes to the record if the value did not change.

Note:
- We chose this approach instead of touching `_extend_with_attachments` and the rollback
context directly. Mostly to prevent any unforseen side-effects, given that this
methods are used in accounting for all attachments.
But it might be worth analysing if those methods might be improved
to handle scenarios as described above in multi-worker setups + email handling.
- fixing the rollbackable context might tricky
 because the serialization error happens at the
first `cr.commit()` inside the context manager
- raising explicitly with `except psycopg2.extensions.TransactionRollbackError:`
in `_extend_with_attachments`
retries the whole request to the `message_process`,
which might not be a good idea

OPW-6272396

closes odoo/odoo#270251

Signed-off-by: William André (wan) <wan@odoo.com>