[FIX] sale_stock: force invoice_policy on product in test
## Issue
The test `test_anglo_saxon_cogs_partial_down_payment_credit_note` from
the `sale_stock` module is failing when the Kenyan localization is installed.

This issue is similar to the one fixed by https://github.com/odoo/odoo/commit/b9e5807cd70d.

## Steps to reproduce
1. Install `sale_stock` and `l10n_ke_edi_oscu_stock`
2. Run the test `test_anglo_saxon_cogs_partial_down_payment_credit_note`
3. **The test fails with the following error:**

```
AssertionError: Lists differ: [{'debit': 0, 'credit': 40, 'account_id': 268}] != []

First list contains 2 additional elements.
First extra element 0:
{'debit': 0, 'credit': 40, 'account_id': 288}

+ []
- [{'account_id': 288, 'credit': 40, 'debit': 0},
-  {'account_id': 268, 'credit': 0, 'debit': 40}]
```

## Cause
When `l10n_ke_edi_oscu_stock` is installed, the `invoice_policy` of Kenyan
products (or products without a company set) is set to `"delivery"` by
the `_compute_invoice_policy` method from that module:

https://github.com/odoo/enterprise/blob/f4cd9a38c699e8d8f17990a283793985bfc89948/l10n_ke_edi_oscu_stock/models/product.py#L16-L21

This impacts the `SaleOrder.qty_to_invoice` field, as we now use the
`qty_delivered` (which is 0 here) instead of the `product_uom_qty`:

https://github.com/odoo/odoo/blob/d0ee4af1ddb969dfc9023c628f8b128f2b22e89d/addons/sale/models/sale_order_line.py#L1001-L1006

With a `qty_to_invoice` set to 0, the `SaleOrder._get_invoiceable_lines`
doesn't add the product as an invoiceable line:

https://github.com/odoo/odoo/blob/d0ee4af1ddb969dfc9023c628f8b128f2b22e89d/addons/sale/models/sale_order.py#L1492-L1498

And finally, with the `'cogs'` invoice lines missing, the comparison with
the expected values fail:

https://github.com/odoo/odoo/blob/d0ee4af1ddb969dfc9023c628f8b128f2b22e89d/addons/sale_stock/tests/test_anglo_saxon_valuation.py#L1879-L1887

## Fix
We manually set the `invoice_policy` of the test product to 'order' to
keep the test configuration consistent regardless of the other modules
installed.

runbot-242508