[FIX] sale: create invoice when SO lines are empty
This error occurs when creating an invoice for a sale order with no SO line.

Steps to reproduce:
- Install 'sale_management' module
- Create a New SO and 'Add a Section' > Confirm
- Remove SO line > Create Invoice > Down Payment > Create Draft

Traceback:
TypeError: 'int' object is not iterable

At [1], the error occurs because self.order_line.mapped('sequence') returns an
empty list. The fallback value 10 is used, but since it's an
integer (not a list), it causes a TypeError.

[1]- https://github.com/odoo/odoo/blob/f101a9b6d65e34cf3d3175a341b87e3f14c44a02/addons/sale/models/sale_order.py#L2052

sentry-6601545000

closes odoo/odoo#209603

Signed-off-by: Victor Feyens (vfe) <vfe@odoo.com>