[FIX] l10n_in{_edi}: move iap service data to l10n_in
Commit merged at https://github.com/odoo/odoo/commit/2952b900d74e645340db96df0d9834cfaa430475 added
iap dependency to `l10n_in` and removed the dependency from `l10n_in_edi` but iap_service_data
was not moved to l10n_in which leads to following tracaback:
```py
  File "/data/build/odoo/addons/iap/models/iap_account.py", line 167, in get
    raise UserError("No service exists with the provided technical name")
odoo.exceptions.UserError: No service exists with the provided technical name
```

After this commit:
we move the iap service data to l10n_in module from l10n_in_edi.
And the above traceback is resolved.

closes odoo/odoo#180741

Related: odoo/upgrade#6543
Signed-off-by: William André (wan) <wan@odoo.com>