[FIX] {test_}mass_mailing: prevent error when merging mailing lists
Currently, error occurs when user tries to merge a mailing list.

Steps to replicate:
- Install `mass_mailing`.
- Open Email Marketing > Mailing Lists > Mailing Lists and switch to list view.
- Select a single record and Click merge.

Error:
```
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 8:           AND src_sub.list_id IN ()
                                         ^

ValueError: SyntaxError('syntax error at or near ")"\nLINE 8: 'AND src_sub.list_id IN ()\n'
^\n') while evaluating 'action = records.action_mailing_lists_merge()'
```

Cause:
- Error occurs due to a recent [PR].

- When the user selects only a single record, `self - dest` [1] evaluates to an
  empty recordset. As a result, `action_merge()` receives an empty `src_lists`.

- Later, this is used [here] and converted into an empty tuple, producing an
  invalid SQL clause like `src_sub.list_id IN ()`, which leads to this error.

Solution:
- When `src_lists` is an empty recordset, we early return from `action_merge()`.

[PR]: https://github.com/odoo/odoo/pull/72156

[1]: https://github.com/odoo/odoo/blob/4193b3735d64518290613f5c8132f1fd07afa229/addons/mass_mailing/models/mailing_list.py#L218

[here]: https://github.com/odoo/odoo/blob/4193b3735d64518290613f5c8132f1fd07afa229/addons/mass_mailing/models/mailing_list.py#L266

sentry-7447326420

closes odoo/odoo#263911

X-original-commit: 24634eeb710faaf09576ace1ff5834ed73eb9d06
Signed-off-by: Renaud Thiry (reth) <reth@odoo.com>