[FIX] account: Traceback when downloading Original bills
Users currently cannot retrieve original bills attached to
newly created draft moves, because an error is blocking the action

Steps to reproduce:
- Go to Accounting > Vendor > Bills
- Upload a pdf
- Back in list view, select the created bill, Download > Original Bills

Issue: Traceback will raise
`AttributeError: 'bool' object has no attribute 'decode'`

This occurs because, after ce73ed61bcf293953bc0c821ceaef3ddb9a47e3c,
draft moves are not named '/' anymore, the name field will be just `False`.
However reportlab expects a string and it crashes

opw-4502791

X-original-commit: 08a4fe308bab9e3324bd6ece21b35f664a3fda56