[FIX] mail: mail_followers: add selected column in SQL query GROUP BY
ISSUE:
	when executing the SQL query
	"""
	SELECT fol.id, fol.res_id, fol.partner_id, fol.channel_id, array_agg(subtype.id)%s
	FROM mail_followers fol
	%s
	LEFT JOIN mail_followers_mail_message_subtype_rel fol_rel ON fol_rel.mail_followers_id = fol.id
	LEFT JOIN mail_message_subtype subtype ON subtype.id = fol_rel.mail_message_subtype_id
	WHERE %s
	GROUP BY fol.id%s""" ...

	in '_get_subscription_data' method of the 'mail.followers' model

	Found:
	psycopg2.ProgrammingError: column "fol.res_id" must appear in the GROUP BY clause or be used in an aggregate function

	Tested with: postgres (PostgreSQL) 11.14 on Ubuntu 18.04 LTS

CAUSE:
	If we look at the logic of the query, we can see why this error occurs:

	`SELECT fol.id, fol.res_id, fol.partner_id, fol.channel_id ...`
	This says that for each row, we want the `id, res_id, partner_id, channel_id` from `mail_followers` table

	but in
	'GROUP BY fol.id ...''
	This says we want one row for each unique `id` of `mail_followers`, no matter what else is different.

	So, if there is more than `res_id, partner_id or channel_id` for the same `id` from `mail_followers` table (which won't happen as each row id is unique) BUT database would have no way of knowing which of those values to give us. So Postgres tells us to change the query.

SOLUTION:
	In this case, we know that every `id` corresponds to a single value of `res_id, partner_id & channel_id`, so we can just add them all to the GROUP BY clause