[FIX] hr_attendance: provide correct arguments to ValidationError
Currently, an error occurs when user saves an overtime ruleset.

Steps to reproduce:
 - Install the hr_attendance module.
 - Go to Overtime Rulesets and create a rule.
 - Add an overtime rule in this ruleset with:
    - Rule is based on: Quantity
    - and clear the 'If the worked hours on' field.
 - Save the rule and ruleset.

TypeError: UserError.__init__() got an unexpected keyword argument 'name'

This error occurs when a user saves the ruleset without setting the rule's
quantity period, and due to two arguments being wrongly placed in the
ValidationError[1], the error is raised.

This commit ensures that the validation error works correctly by passing a
single argument.

[1]: https://github.com/odoo/odoo/blob/34409128de0bb84cdee309b031b307c46d8b07c7/addons/hr_attendance/models/hr_attendance_overtime_rule.py#L147

sentry-6932048427

closes odoo/odoo#231497

X-original-commit: 3050fe2cef33879dc867aed237a11e7e4c00edb0
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>