[FIX] web_editor: raise NotFound instead of of ValueError for unsupported file
Currently a ValueError occurs when users access URLs like
'/web_editor/shape/image/jpeg'.

Error: `ValueError: Unsupported file: image/static/shapes/jpeg`

This ValueError was raised from the odoo/tools/misc.py at line [1] because the
file extension was not a match with the normalise path of the file path.

This commit will handle the ValueError at the time of opening the file;
now it shows not found instead of an error.

[1] - https://github.com/odoo/odoo/blob/231952114ae730bb8d4671f4a61f738e8b6dd5b8/odoo/tools/misc.py#L178

sentry-6073086305