[FIX] l10n_fr_pdp: don't locate Peppol error alert by its text
Issue:
Opening customer invoices or vendor bills crashes for users with French language in the settings when `l10n_fr_pdp` is installed:

ValueError: Element '<xpath expr="//div[contains(text(),'There was an error while sending this invoice via Peppol.')]">'
cannot be located in parent view

Steps to reproduce:
- Install `l10n_fr_pdp`
- Activate the French language
- Open invoices
--> Stacktrace

Cause:
The `account_peppol` alert text is translated, so the targeted div can't be found.

Fix:
Locate the alert by its class and `invisible` condition instead of by its text.

TODO in master: add an id or name on the div and use it to fix the xpath.

Fixes 6625465

X-original-commit: 86d581cee5682b2912f69263adedbea679b66e5b