[FIX] base: Prevent browsing falsy res_id `ir.model.data`
Since https://github.com/odoo/odoo/pull/227477, using falsy ids ids
illegal

This commit adds an additional filter to the domain used to browse
`ir.model.data` to compute the following fields: `(menus|views|reports)_by_module`
in order to avoid selecting any that would contain a falsy `res_id` and
thus cause the above-mentioned assertion to fail.

One way to reproduce this in a new trial:
- Create a new trial with several modules: `account`, `crm`, `project`, `sales`
- Install `web_studio`
- Uninstall `base_automation`
- Traceback
```
  File “/home/odoo/src/odoo/saas-19.1/odoo/orm/models.py”, line 5200, in browse
    assert all(ids) or all(isinstance(x, NewId) or x for x in ids), “Invalid falsy real id”
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid falsy real id
```

This is due to an `ir.model.data` containing a falsy res_id in the
internal code of `saas_trial` (`installed-17`)

This fix will avoid any additional traceback like this one.

opw-5865316

closes odoo/odoo#245469

Signed-off-by: Krzysztof Magusiak (krma) <krma@odoo.com>