[FIX] mrp: convert qty of subcontracted move
To reproduce the issue:
1. In Settings, enable:
    - Units of Measure
    - Storage Locations
2. Create two consumable products P1, P2:
    - P1:
        - UoM: g
        - Purchase UoM: g
3. Create a BoM:
    - Product: P1
    - Qty: 1 kg
    - Type: Subcontracting
    - Subcontractor: a partner PA
    - Component:
        - 1 x P2
4. Create a planned receipt R:
    - From: PA
    - With:
        - 10000 g x P1
5. Mark R as todo
6. In the detailed operations, add a new line:
    - To: WH/Stock
    - Done: 10
    - UoM: kg
7. Validate R
8. Open the product moves of P1

Error: The move from Production to Subcontacting Location contains 10 g,
which is incorrect.

In the detailed operations, we used an UoM different than the one of the
move. However, there isn't any conversion of the quantity

OPW-2859754