[FIX] mrp: `action_open_product_lot` is in the view `product_product_form_view_bom_button`
The button `action_open_product_lot` is added by the view `product_product_form_view_bom_button`.
Both the current view and the view `product_product_form_view_bom_button` inherited
from the view `product.product_normal_form_view`,
without any priority specified.

In order to make sure the button `action_open_product_lot` is in the view
when the view `product_product_form_view_bom_button` is loaded,
you either need to directly inherits from the view holding that button
`product_form_view_procurement_button`
either you need to increase the priority of the current view
so `product_product_form_view_bom_button` is loaded in priority.

Same thing for the view `product_template_form_view_bom_button`

Upgrade Request 47960

```
ValueError: Element '<xpath expr="//button[@name='action_open_product_lot']">' cannot be located in parent view

Error context:
View `product.product.procurement`
[view_id: 783, xml_id: mrp.product_product_form_view_bom_button, model: product.product, parent_id: 319]
```

X-original-commit: 26fac2af85acb0ae9f9e479aec5eb16930d69e49