[FIX] stock: prevent error on missing sequence
Currently, an error occurs when a user tries to generate lots while providing a
lot number.

Steps to replicate:
- Install purchase (without demo).
- Create a product `test`.
- Install stock and turn on `Lots and Serial Numbers`
- Open the product `test` and turn on `Track Inventory` `by Lots`.
- Open Receipts > add the product `test`> give demand as 3 > and go to its
  form view using view button.
- Click `Generate Lots` > type `lot1` in `First lot Number` > Generate > Error-1
- Click `Generate Lots` > type 0 in Quantity received > Generate > Error-2.

Error-1:
```
  File '/home/odoo/odoo18/community/addons/stock/models/stock_move.py', line 1026, in action_generate_lot_line_vals
    if (first_lot and first_lot == product.lot_sequence_id.get_next_char(first_number)):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File '/home/odoo/odoo18/community/odoo/addons/base/models/ir_sequence.py', line 237, in get_next_char
    interpolated_prefix, interpolated_suffix = self._get_prefix_suffix()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File '/home/odoo/odoo18/community/odoo/addons/base/models/ir_sequence.py', line 227, in _get_prefix_suffix
    self.ensure_one()
  File '/home/odoo/odoo18/community/odoo/orm/models.py', line 5640, in ensure_one
    raise ValueError('Expected singleton: %s' % self)
ValueError: Expected singleton: ir.sequence()
```

Error-2:
```
  File '/home/odoo/odoo18/community/addons/stock/models/stock_move.py', line 1025, in action_generate_lot_line_vals
    first_number = product.lot_sequence_id.number_next_actual - product.lot_sequence_id.number_increment
                   ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
```

Cause:
- Both errors originated through a recent [PR].

Error-1 (Expected singleton: ir.sequence()):
- As the product was already created before Inventory was installed, the
  `lot_sequence_id` was empty.
(Note:`lot_sequence_id` field has a default value , but default value
       assignment triggers only during the record creation,  any records created
       before stock is installed will not be assigned any value for
      `lot_sequence_id`.)

- As no `lot_sequence_id` is assigned to `test` product the line [1] calls
  `get_next_char()` on an empty recordset which further calls
  `_get_prefix_suffix()` [2] and raises singletonerror from [here].

Error-2 (UnboundLocalError: cannot access local variable 'product'):
- As the `Received Quantity` was given 0, the `count` argument is received as 0
  and as a result the `lot_qties` [3] and `lot_names` [4] are received as empty
  lists.
- This causes their [zip] to be empty list too and the loop never runs, so
  assignment to [product] variable never happens and causes the error to occur
  from here [5].

Solution:

Error-1:
- Now we perform write on `product.lot_sequence_id` only if it exists, otherwise
  we skip it.

Error-2:
- Moved the static assignment of variable `product` and `location_dest_id`
  outside the loop, this will also prevent the browse being called multiple
  times for browsing the same record.

[PR]: https://github.com/odoo/odoo/pull/240368

[1]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/addons/stock/models/stock_move.py#L1026

[2]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/odoo/addons/base/models/ir_sequence.py#L237

[here]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/odoo/addons/base/models/ir_sequence.py#L227

[3]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/addons/stock/models/stock_move.py#L989

[4]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/addons/stock/models/stock_move.py#L994

[zip]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/addons/stock/models/stock_move.py#L1000

[product]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/addons/stock/models/stock_move.py#L1004

[5]: https://github.com/odoo/odoo/blob/7ab52c1675b9764d11454c7b5216064bec4628f8/addons/stock/models/stock_move.py#L1025

sentry-7254849206,7265844194

X-original-commit: 49a593973b5e453f9c26d797e1a3e2bf289a5fdd