[FIX] mrp: consume expected quantity on mo backorder without reservation
Steps to reproduce:

- In the settings enable: Multi-Steps Routes
-  Set your warehouse to manufacture in 2 steps (pick then manufacture).
- Create a final product (FP) with a BOM in flexible consumption:
  - 1 x COMP (lot tracked)
- Create and confirm an MO for 1 units of FP
- Set the quantity producing on the MO to 1
> The consumed qty was updated to 1 unit
- Set a lot on the pre-production pikcing and validate
> The lot is not transfered to the MO which you are not able to
  validate since the registered component is lot less

Cause of the issue:

The issue is caused by
https://github.com/odoo/odoo/commit/2c9b66c17776faaaddbfb0931d8eb14a1e97361a
as the `qty_waiting` is based on the reservation state of the move
origin of the move rather than its actual demand:
https://github.com/odoo/odoo/blob/064385c59aacf1d0f010bce6f9e214c3cf668d39/addons/mrp/models/mrp_production.py#L1419-L1426
In particular, since the backorder of the pre-production picking was not
reserved (since nothing was available in stock), it was not taken into
account as it should have been.

Issue 2:

Steps to reproduce:

- In the settings Enable Multi-Steps Routes
- Unarchive MTO
- Create 3 products:
  - Final Product: Tracked by SN with a BOM: 1 X Super Component
  - Super Component: Tracked by SN, MTO with a BOM: 1 X Component
  - Basic Component: Put 10 units in stock
- Create and confirm an MO for 3 units of Final Product
> This should create an MO for 3 units of Super Component
- Go to the Child MO > Cogs wheel > Split in 3 MO's
- Click "Generate serial" on each Child MO and validate the first one
- On the MO for Final Product > Cogs wheel > Split in 3 MO's
- On the first MO, click "Generate Serial"
> Error: Reserving a negative quantity is not allowed.

Cause of the issue:

The `action_generate_serial` calls in turn the `set_qty_producing`:
https://github.com/odoo/odoo/blob/4e8f635a888c92e80ed3ad06d570083ecdf7f0c8/addons/mrp/models/mrp_production.py#L1601
However, since the main MO was split the Super component demand is of 1
but each child MO provide an origin quantity of 1 so that the `new_qty`
will be set to a negative one here:
https://github.com/odoo/odoo/blob/4e8f635a888c92e80ed3ad06d570083ecdf7f0c8/addons/mrp/models/mrp_production.py#L1418-L1426
But, since the first child MO was validated, there is already a move
line associated to the Super component move and the `_set_quantity_done`
will therefore try to adapt the reservation to a negative quantity which
leads to the error:
https://github.com/odoo/odoo/blob/4e8f635a888c92e80ed3ad06d570083ecdf7f0c8/addons/stock/models/stock_move_line.py#L469-L470

opw-6128575

closes odoo/odoo#271123

Signed-off-by: William Henrotin (whe) <whe@odoo.com>