[FIX] sale_project: prevent singleton error when cancelling multiple quotations
When user tries to cancel the multiple quotations at once,
a traceback will appear.

Steps to reproduce the error:
- Install 'sale_project'
- Go to Sales > Orders > Quotations > Select multiple quotations
- Actions > Cancel quotations > Cancel quotations

Error: A traceback appears:
'ValueError: Expected singleton: sale.order(1, 2)'

https://github.com/odoo/odoo/blob/5a7e83a4340aeee3c0208cea72c200e998e26ecd/addons/sale_project/models/sale_order.py#L318
Here, 'self.id' is used instead of 'self.ids'.

sentry-5659311816

closes odoo/odoo#175283

Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>