[FIX] base: return action content for readable fields
With the recently added embedded actions with commit [1], added line [2] where
it returns non related fields to actions, which may generate an error.

In the `account_online_synchronization` module, a below exception was generated
when cron `Account: Journal online sync` run.

error: `TypeError: Object of type datetime is not JSON serializable`

This exception was generated because [3] tries to store a dictionary of
action with a datetime object in the json field `connection_state_details`,
but when data is converted to cache at [4], it throws an exception because
`json.dumps` does not support datetime objects.

This commit will resolve the issue by following:
1. Override the `_get_action_dict` in 'ir.actions.act_window'.
2. In overridden '_get_action_dict' it just adds readable embedded
   field data when `embedded_action_ids` is available.

[1]-https://github.com/odoo/odoo/commit/f983703dfa3c5102fa818523ae419a70cc4b5230
[2]-https://github.com/odoo/odoo/blob/ebf6da8d24c72a391113310e66285ded1f5fc9b5/odoo/addons/base/models/ir_actions.py#L232-L236
[3]- https://github.com/odoo/enterprise/blob/b491d3fa529115229fcce58500f742a992a7f2e5/account_online_synchronization/models/account_online.py#L423
[4]-https://github.com/odoo/odoo/blob/ebf6da8d24c72a391113310e66285ded1f5fc9b5/odoo/fields.py#L3346

sentry-5655598227