[FIX] tools: prevent warning override behaviour
current behaviour:
when buggy server action is introduced, we don't handle it well, eg:
```
name = record.name
if name != record.partner_id:
    raise UserError("Datatype")
```
here, comparing `name` and `record.partner_id` doesn't make sense,
therefore our ORM default behaviour is to return false and rise
`AttributeError`, but the problem occurs when pypdf2 attempts to format
the warning message, which rises an error which isn't being handled:
```
  File "/home/odoo/.local/lib/python3.10/site-packages/PyPDF2/pdf.py", line 1069, in _showwarning
    file.write(formatWarning(message, category, filename, lineno, line))
  File "/home/odoo/.local/lib/python3.10/site-packages/PyPDF2/utils.py", line 69, in formatWarning
    file = filename.replace("/", "\\").rsplit("\\", 1)[1] # find the file name
IndexError: list index out of range
```
it is problematic since it is server action.

expected behaviour:
Even when buggy code is introduced, comparision should return False and
error should be handled well.

steps to reproduce:
1) Create new database from scratch and create server action with the
buggy code above, set model to `sale.orde` and add it to
`contextual action`
2) Go to any `sale.order` record and trigger the action.
3) it outputs the error.
4) please note that, if you restart the server, error doesn't happen,
because places where override happens doesn't get invoked.

task-4365106

closes odoo/odoo#189942

X-original-commit: 0018e0cc2150687bbf34149f5eb00fdb9151ced1
Signed-off-by: Xavier Morel (xmo) <xmo@odoo.com>