[FIX] web_editor: Avoid errors when multiple consecutive spans in email templates
Summary
-----
Currently with odoo enterprise and in code view, if there is html which has to be sanitized with 3 consecutive spans, it results in an error:
	- TypeError: anchorNode.parentNode.closest is not a function (for versions 16.3 and 16.4)
	- TypeError: Cannot read properties of null (reading 'isContentEditable') (for versions 17 and 17.1)

Steps to reproduce
-----
1. Enable the developer mode;
2. Create an email template (Settings > Technical > Email Templates);
3. Fill the fields "Name" and "Applies to" with any valid value;
4. Open the code view: write anything in the "Content" tab, select what you wrote then a bar will appears and click on the logo </>;
5. Write in the "Content" tab: <span>1</span><span>2</span><span>3</span>;
6. Save the template;
7. Select another tab ("Email Configuration" or "Settings") and come back the the "Content" tab.

Cause
-----
The html code written has to be sanitized, and during this process, the spans should be merged. Before merging, the selection (anchor and focus) is stored in memory and "normalized".
When 3 spans are consecutive, the selection moves to the HTML tag, and its parent is the document itself.
Normally, the getDeepRange method should replace the selection on the body, but in Enterprise, the HTML tag contains the audio element in addition to the head and body. Since this element doesn't have the same properties as the body, it can't be edited, and the selection remains on the HTML tag.
When attempting to set the selection, you should use the closest('body') method on the parent of HTML, which is the document. However, this method is not applicable to the document and results in an error.

Fix
-----
Add the 'odoo-editor-editable' class to the body before calling the 'sanitize' function in the file 'OdooEditor.js'.
So the "normalized" selection will at most be the body and will have the HTML tag as its parent rather than the document. This method effectively addresses the issue for versions 16.3 to 17.1.

opw-3556985