[FIX] purchase_stock: prevent error on confirming sale order
This error occurs when attempting to confirm the SO.

Steps to reproduce:
- Install the 'purchase_stock' and 'sale_management' modules
- Enable 'Multi-Step Routes' in Configuration
- Go to routes and unarchive 'Replenish on Order (MTO)' > Open rule and change
  'Supply Method'('Take From Stock, if unavailable, Trigger Another Rule')
- Create new Product(eg: Test) and in Inventory set Routes
  (Replenish on Order (MTO) and Buy)
- Create new SO with product created(Test) and 'Confirm'

Traceback:
AttributeError: 'bool' object has no attribute 'propagate_cancel'

At [1], this error occurs because the value of 'move_dest_ids' in
'procurement.values' is set to 'False'. This happens because when calling
'_action_confirm', the method '_prepare_procurement_values' is triggered, and
within this method, at [2], 'move_dest_ids' is explicitly assigned as 'False'.

[1]- https://github.com/odoo/odoo/blob/571161f0b28e85521c519f57c28ce1c19a4b4a33/addons/purchase_stock/models/stock_rule.py#L81-L83

[2]- https://github.com/odoo/odoo/blob/571161f0b28e85521c519f57c28ce1c19a4b4a33/addons/stock/models/stock_move.py#L1567-L1569

This commit resolves the error by returning a default value if the key does not
exist. In this case, the default value is an empty recordset of the 'stock.move'
model.

sentry-6451186204

closes odoo/odoo#204030

X-original-commit: 6465e62d2a0253699adbad151eba71d11cdb2d70
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>