[FIX] stock: Allow users to remove graph from overview
Steps to reproduce:
- Go to Inventory > Overview
- Enable Studio, delete a kanban card that contains the
  "picking_type_dashboard_graph" widget (field kanban_dashboard_graph)
> UncaughtPromiseError > OwlError
> TypeError: Cannot read properties of undefined (reading 'includes')
    at StockKanbanRenderer.getGroupsOrRecords

Cause of the issue:

`StockKanbanRenderer.getGroupsOrRecords` assumes the field
`kanban_dashboard_graph` is always present on every record to detect
if all Inventory Overview graphs are sample data and, if so,
replace them with randomized values.

By removing the card with studio, we remove the field from the fields
fetched for the record, and so `r.data.kanban_dashboard_graph` is
`undefined`.

Fix by ignoring records for which the field isn't fetched instead of
assuming it's always there.

opw-6512743