[FIX] hr_expense: prevent error when generating post journal entries
Currently an error occurs when the user is generating Post Journal Entries of an
employee whose work email is not specified.

Steps to Reproduce:
- Install `hr_expense` module.
- Open Expenses > Expense Reports.
- Open a report of employee whose work email is not specified.
- Make sure the status of the selected recordset is `Approved`
- Now click on the `Post Journal Entries` button.
- The error is generated.

Error: ValueError: External ID not found in the
system: hr.open_view_employee_tree

This error arises at [1] when it attempts to access the xml id with
the view`hr.open_view_employee_tree`but due to recent changes in forward port of
master this view has been removed with [2] as it wasn't used anywhere; but in
[3] `hr.open_view_employee_tree` was used and due to this now the error is
generated.

This commit fixes the above issue by using view `hr.open_view_employee_list_my`
instead of the removed view  `hr.open_view_employee_tree`.

Link: [1]-https://github.com/odoo/odoo/blob/4126dcc08ef22f2b644559ba24bd4ce093684f1c/addons/hr_expense/models/hr_expense_sheet.py#L638

[2]-https://github.com/odoo/odoo/commit/abd909498e4fd519ff8431ea9d7d09da4fc7c59a

[3]-https://github.com/odoo/odoo/commit/2c0b01e79e81e6a28ca5f610ad14d4cb8fd5d756

sentry-4968357276

X-original-commit: 65adc3d92a1ce1d1c8bdab1a7631531c75e78e8a