[FIX] account: break recursion when removing a bank statement
Steps:
- Have a lot of bank statements
- Try to delete an old bank statement

Bug:
Traceback:
RecursionError: maximum recursion depth exceeded

Explanation:
Unlinking a statement triggers a recursion with this line:
https://github.com/odoo/odoo/blob/0d6332fdbbea996aaae2dd07fb3c20deeb3a53b2/addons/account/models/account_bank_statement.py#L330
This makes the ORM call `_compute_ending_balance()`. If there are too
many statements after the one we just deleted, the stack depth limit is
reached.
With this commit, `_compute_ending_balance()` now depends on
`balance_end` instead of `balance_end_real`. This prevents the recursion
from happening.
Also, a loop has been used to compensate for the lack of recursion.

opw:2427083