[FIX] iap: handle errors while calling JSON-RPC endpoint
Currently, an error occurs in the log when a ValidationError or
InFailedSqlTransaction error occurs when calling the JSON-RPC endpoint in IAP.

error: `ConnectionError: null'

This is because [1] added logger.exception that logs every error in the
log when it appears.

This commit will use the logger warning to print a warning in the
terminal instead of the exception when a ValidationError or
InFailedSqlTransaction error occurs.

[1] - https://github.com/odoo/odoo/commit/a1477d1d00adb928b149f8e019f65c00f75ef129

sentry-6059323528