[I18N] base: improve in Russian translations
Currently, in Russian, the variable 'field' is translated into Russian as
'поле' which causes an error.

Error: `KeyError: 'поле'`

This commit fixes this issue by updating the translated variable
into the original variable.

sentry-5141195219

closes odoo/odoo#160619

Signed-off-by: Adrien Widart (awt) <awt@odoo.com>