[FIX] web: use jinja FileSystemLoader instead of PackageLoader
PackageLoader fails in recent versions with this error:

  File "/usr/lib/python3.10/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: odoo.addons.web.__spec__ is None