[FIX] mass_mailing: mobile preview error
Current behaviour:
When trying to preview a mailing template
with the debug mode enabled, there is an error:
Invalid props for component

Steps to reproduce:
1. Enable debug mode with assets
2. Go to Email Marketing
3. Create a new Mailing
4. Select a template
5. In the Editor, click on the mobile icon
6. ... 'preview' is not a function

Cause of the issue:
Caused by https://github.com/odoo/odoo/commit/2e1b3705c5f60c4ceed85a4c8c22a36d18144d6a

opw-3702901

closes odoo/odoo#158286

X-original-commit: 49d4f20242c48964b4f367a0d9ce1cdc964b6460
Signed-off-by: Antoine Demany (ande) <ande@odoo.com>