[FIX] stock,mrp: scrap kit
When scrapping a kit, it leads to incorrect behaviours

**Case 01:**
1. Create a storable kit with one storable component
2. Validate a scrap order with that kit

Error: a user error is raised "You should update the components
quantity instead of directly updating the quantity of the kit product"

When validating a scrap order, we actually process a stock move with
an already-defined SML
https://github.com/odoo/odoo/blob/89bd102829e332045119bbec5086f3c24cdaa3c5/addons/stock/models/stock_scrap.py#L145-L147
https://github.com/odoo/odoo/blob/89bd102829e332045119bbec5086f3c24cdaa3c5/addons/stock/models/stock_scrap.py#L112-L139

But, when creating a SML, and in some conditions, we are directly
updating the reserved qty of the quant:
https://github.com/odoo/odoo/blob/83221377cf865a5a6284ab6cb9b5d0958385bf77/addons/stock/models/stock_move_line.py#L353-L355

And, you can't do such a reservation since the product is a kit
https://github.com/odoo/odoo/blob/c07778bbce4311c142bd8e2ce3013998d4f126ae/addons/mrp/models/stock_quant.py#L8-L11

In order to anticipate the constraint, we should bypass the
reservation in case of a kit.

opw-4090951

closes odoo/odoo#177568

X-original-commit: 224de17845068263a49c02c95aa47ac8e283ad4d
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>