[FIX] point_of_sale: order might be undefined on pending payment
Using a payment method which rely on websocket (viva wallet, adyen,
mercado pago, etc.) trigger a callback on all browser session of a
given PoS session. If a browser session happen to not have any
current session, a JS traceback will pop:
```js
TypeError: Cannot read properties of undefined (reading 'payment_ids')
```
due to the webscoket listener checking if there is on-going order
using the payment method

opw-4374450

closes odoo/odoo#193474

Signed-off-by: David Monnom (moda) <moda@odoo.com>