[FIX] purchase: fix broken catalog on non-empty POs
Steps to reproduce:
- Open purchase app.
- Create an RFQ and add any product(s) to it.
- Click on "Catalog" button in products tab to add products from the
  catalog.

=> Expected behavior: Catalog opens with a list of products to choose
   from.
=> Current behavior: An error is triggered: `TypeError:
   PurchaseOrderLine._get_product_catalog_lines_data() got an
   unexpected keyword argument 'parent_record'`

This is because `_get_product_catalog_lines_data` in
`purhcase.order.line` model is the only override of this function that
does not accept keyword arguments. So when
`_get_product_catalog_order_line_info` in `product.catalog.mixin` calls
this function with any keyword argument, this error is triggered.

closes odoo/odoo#159668

Signed-off-by: William Henrotin (whe) <whe@odoo.com>