[FIX] base: allow uninstalling models with many2one fields that have an inverse one2many.
Allow the modification/deletion of many2one fields that have an inverse one2many when uninstalling.

Code that fails:

```python
from odoo import api, fields, models, _

class Department(models.Model):
    _name = 'aa.department'

    name = fields.Char(string='Department Name')
    employee_ids = fields.One2many(comodel_name='aa.employee',
                                   inverse_name='department_id', string='Employees')

class Employee(models.Model):
    _name = 'aa.employee'

    name = fields.Char(string='Employee Name')
    department_id = fields.Many2one(comodel_name='aa.department', string='Department')
```

Errors before this fix:

```
2016-11-10 13:25:19,950 1786 INFO prova10 odoo.addons.base.ir.ir_model: Dropped FK CONSTRAINT aa_employee_department_id_fkey@aa.employee
2016-11-10 13:25:19,955 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.constraint records with IDs: [678]
2016-11-10 13:25:19,960 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 5008@ir.model.fields
2016-11-10 13:25:19,961 1786 INFO prova10 odoo.addons.base.ir.ir_model: Unable to delete 5008@ir.model.fields
Traceback (most recent call last):
  File "/home/eantones/Documents/NuoBiT/dev/odoo/test10/odoo/odoo/addons/base/ir/ir_model.py", line 1278, in unlink_if_refcount
    self.env[model].browse(res_id).unlink()
  File "/home/eantones/Documents/NuoBiT/dev/odoo/test10/odoo/odoo/addons/base/ir/ir_model.py", line 452, in unlink
    self._prepare_update()
  File "/home/eantones/Documents/NuoBiT/dev/odoo/test10/odoo/odoo/addons/base/ir/ir_model.py", line 439, in _prepare_update
    raise UserError(msg % (field, model._field_inverses[field][0]))
UserError: (u"The field 'aa.employee.department_id' cannot be removed because the field 'aa.department.employee_ids' depends on it.", None)
2016-11-10 13:25:19,966 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 5006@ir.model.fields
2016-11-10 13:25:19,983 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10615]
2016-11-10 13:25:19,985 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [5006]
2016-11-10 13:25:19,994 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 5003@ir.model.fields
2016-11-10 13:25:20,004 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10612]
2016-11-10 13:25:20,005 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [5003]
2016-11-10 13:25:20,008 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 5002@ir.model.fields
2016-11-10 13:25:20,020 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10611]
2016-11-10 13:25:20,021 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [5002]
2016-11-10 13:25:20,032 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 4998@ir.model.fields
2016-11-10 13:25:20,046 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10606]
2016-11-10 13:25:20,047 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [4998]
2016-11-10 13:25:20,054 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 4995@ir.model.fields
2016-11-10 13:25:20,066 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10603]
2016-11-10 13:25:20,066 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [4995]
2016-11-10 13:25:20,069 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 4994@ir.model.fields
2016-11-10 13:25:20,077 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10602]
2016-11-10 13:25:20,078 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [4994]
2016-11-10 13:25:20,080 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 4993@ir.model.fields
2016-11-10 13:25:20,088 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10601]
2016-11-10 13:25:20,089 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [4993]
2016-11-10 13:25:20,096 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 369@ir.model
2016-11-10 13:25:20,101 1786 INFO prova10 odoo.addons.base.ir.ir_model: Unable to delete 369@ir.model
Traceback (most recent call last):
  File "/home/eantones/Documents/NuoBiT/dev/odoo/test10/odoo/odoo/addons/base/ir/ir_model.py", line 1278, in unlink_if_refcount
    self.env[model].browse(res_id).unlink()
  File "/home/eantones/Documents/NuoBiT/dev/odoo/test10/odoo/odoo/addons/base/ir/ir_model.py", line 136, in unlink
    model.field_id._prepare_update()
  File "/home/eantones/Documents/NuoBiT/dev/odoo/test10/odoo/odoo/addons/base/ir/ir_model.py", line 439, in _prepare_update
    raise UserError(msg % (field, model._field_inverses[field][0]))
UserError: (u"The field 'aa.employee.department_id' cannot be removed because the field 'aa.department.employee_ids' depends on it.", None)
2016-11-10 13:25:20,101 1786 INFO prova10 odoo.addons.base.ir.ir_model: Deleting 368@ir.model
2016-11-10 13:25:20,117 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10598]
2016-11-10 13:25:20,118 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model records with IDs: [368]
2016-11-10 13:25:20,125 1786 INFO prova10 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [10598, 10600, 10599, 10606, 10602, 10607, 10603, 10601, 10605, 10604, 10610, 10609, 10615, 10616, 10612, 10611, 10614, 10613]
2016-11-10 13:25:20,154 1786 INFO prova10 odoo.modules.loading: Reloading registry once more after uninstalling modules
2016-11-10 13:25:20,165 1786 INFO prova10 odoo.modules.loading: loading 1 modules...
2016-11-10 13:25:20,181 1786 INFO prova10 odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2016-11-10 13:25:20,278 1786 INFO prova10 odoo.modules.loading: loading 35 modules...
2016-11-10 13:25:20,333 1786 INFO prova10 odoo.modules.loading: 35 modules loaded in 0.05s, 0 queries
2016-11-10 13:25:20,536 1786 INFO prova10 odoo.modules.loading: Modules loaded.
```