get_memory_info was depricated and now it was removed from psutil
If odoo starts with worker, you will get AttributeError: 'Process' object has no attribute 'get_memory_info'
Because the depricated function get_memory_info doesn't exists anymore in the new version of psutil