[FIX] account,purchase_stock: fix error when opening accrued expense entry
When a user tries to open accrued expense entry from purchase order,
A traceback will appear.

Steps to reproduce the error:
- Install "purchase" and "accountant" module with demo data
- Create a Purchase Order > Add product Office Chair Black > Add quantity >
  Confirm Order > Set received quantity > Save
- Actions > Accrued Expense Entry

Traceback:
"AttributeError: 'product.product' object has no attribute 'cost_method'"

https://github.com/odoo/odoo/blob/242afb9ca3a76e3628260ac81a9f5ddcd5d445dd/addons/account/wizard/accrued_orders.py#L219
Here, "cost_method" field is accessed.
However, the "cost_method" field is defined in the "stock_account" module.
If "stock_account" is not installed, the field does not exist,
which leads to the traceback when opening the accrued expense entry.

sentry-7303032922