[FIX] sale_mrp: allow bom type change in multi-company setup
Steps to reproduce:

- Have two companies: company1 and company2
- Create a producct P available in both company1 and company2
- with company1, create a kit bom for a product P
- with company2, create and confirm a sale order for 1 unit of P
- with company1, change the bom type of P from kit to manufature
> UserError: As long as there are some sale order lines that must be
  delivered/invoiced and are related to these bills of materials, you
  can not remove them.

Cause of the issue:

Changing the bom type from a kit (phantom type) to a non kit will launch
a call of the `_ensure_bom_is_free` in order to ensure data integrity
if the kit bom was used by a relevant sale order line:
https://github.com/odoo/odoo/blob/f4c76be062bec47b68ee42505d7d42fed31ac0f2/addons/sale_mrp/models/mrp_bom.py#L15-L18
https://github.com/odoo/odoo/blob/f4c76be062bec47b68ee42505d7d42fed31ac0f2/addons/sale_mrp/models/mrp_bom.py#L24-L42
However, this check does not take the company of the bom into account
and in the present flow, the company of the bom is different from the
company of the supposedly problematic sol.

opw-6290304

X-original-commit: 45ca30455e72021bd69d5d2707ede2d5a033c16d