[FIX] base: prevent to save view without model
When the user tries to restore the default view using web studio but the `model`
field is not defined in the respective `ir.ui.view` model then the user will
face the `KeyError`.

Steps to produce:
- Install Studio, Sales > Activate Studio > Open Sales module
- Click on 'View' > Click on 'MORE' (With debugger mode on)
- Click on 'EDIT' > Remove the current value of the model and make it empty
- Save it and go back to Studio
- Click on 'RESTORE DEFAULT VIEW' > Click on 'OK'

ERROR: Traceback will appear `KeyError: False`

Here, to restore the default view `model` is required for that particular view,
but if user keep `model` empty then the traceback appears.

Sentry-4341141709