Cherry pick of dc8dac3e0f004f2d2569fb2bcf780a4b0669d23f failed
stdout:

stderr:
15:07:24.803999 git.c:344               trace: built-in: git cherry-pick dc8dac3e0f004f2d2569fb2bcf780a4b0669d23f
error: could not apply dc8dac3e0f0... [FIX] website_sale_stock: use website warehouse on sale order
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: