[FIX] event_product: ensure error gets raised in test by using a form
Versions
--------
- 18.0+

Steps
-----
1. Have a minimal database with `event_product` installed;
2. run `:TestEventProduct.test_ensure_event_service_tracking`.

Issue
-----
> FAIL: TestEventProduct.test_ensure_event_service_tracking
> AssertionError: ValidationError not raised

Cause
-----
The test works as expected with `sale_project` installed due to a
`write` override of `product.product`, setting the `service_tracking` to
'no' if `type` is no longer 'service'.

This change still occurs without `sale_project` installed, but via the
`_compute_service_tracking` method defined in `product`.

As this value is set via a compute method instead of `write`, the
`_check_event_ticket_service_tracking` method isn't triggered, and no
error is raised.

Solution
--------
Simulate a front-end flow by changing the `type` to 'consu' on a product
form. This way, the constraint method does get triggered as expected.

runbot-234024

X-original-commit: 4721fb28026947c7a4351a48838ea2732f9e9d86