[FIX] im_livechat : fix chatbot messages access error
Steps to Reproduce

1. Install the **Live Chat** module in version 18.4 or above.
2. Go to:
   **Settings → Users**
   * Open your user and change the access rights from
     **Live Chat / Administrator** to **Live Chat / User**.
   * Alternatively, create a new user giving him rights of the
     **Live Chat / User** group.
3. Login using the Live Chat user.
4. Open the **Live Chat** application and navigate to:
   **Live Chat → Sessions**
5. Open any existing session. The session and its messages are accessible
   without any issue.
6. In the search bar, click:
   **Filters → Custom Filter**
7. Select the field `Chatbot Messages (chatbot_message_ids)`.
You will face the below traceback.

The issue happens because `discuss.channel` records are accessible to users
having the `im_livechat_group_user` group through the Sessions menu:
[here]: https://github.com/odoo/odoo/blob/459a775a066fe1465e53fc751045baed39f80118/addons/im_livechat/views/im_livechat_channel_views.xml#L310-L315

The field `chatbot_message_ids` is defined as:
[here]: https://github.com/odoo/odoo/blob/459a775a066fe1465e53fc751045baed39f80118/addons/im_livechat/models/discuss_channel.py#L165

This field points to the `chatbot.message` model, but access to that model is
restricted to `im_livechat_group_manager` only:
[here]: https://github.com/odoo/odoo/blob/459a775a066fe1465e53fc751045baed39f80118/addons/im_livechat/security/ir.model.access.csv#L15

As a result, when a Live Chat user tries to use `chatbot_message_ids` in a
custom filter, Odoo attempts to read `chatbot.message` records and raises an
`AccessError`.

This issue started happening after the access rights changes introduced in:
[here]: https://github.com/odoo/odoo/pull/201880

Specifically, the following ACL changes:
[here]: https://github.com/odoo/odoo/pull/201880/changes#diff-c1592d633a34db44a7cc2a527482cecc56127cbba72649e7318dcf63ccf477afR19-R20

To fix this issue, added the group
`im_livechat_group_manager` on the field `chatbot_message_ids`
so only those user can access the field who belong to the group.

Traceback:

```.py
odoo.exceptions.AccessError: You are not allowed to access
'Chatbot Message' (chatbot.message) records.

This operation is allowed for the following groups:
        - Live Chat/Administrator

Contact your administrator to request access if necessary.
```

opw - [6169395]
upg - [4274573]

closes odoo/odoo#267002

X-original-commit: cc031ffe263f3b961c3a7a38e3ee3f1a28da135b
Signed-off-by: Niyati Patel (niyp) <niyp@odoo.com>