[IMP] mail: human-readable error on bad record single-id insert
Before this commit, when using a single-id data insertion on
a Model that doesn't support it, it throws the following
error message:

```
TypeError: can't convert symbol to string
```

This happens because the model doesn't support single-id
data syntax, e.g. `message.author = 1` for setting persona
with id "1". A persona needs both id and type because a
partner and guest can have same id but differs only by the
type.

For information, the error message tries to convert symbol
to string because the id or non-single id Models is an array
that contains the field names and the special AND/OR symbols.

With this commit, the message error explicitly names the model
and field with problematic value being attempted to insert, and
also mentions this is a failed attempt to use single-id data
syntax that is unsupported on the target model.

closes odoo/odoo#212714

Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>