[FIX] tools: prevent error when uploading invalid pdf file
Currently, an error occurs when trying to preview the first page of a PDF
attachment in Discuss if the PDF has no raw data.

Steps to produce:
- Install the mail module.
- Open Discuss and attach the PDF file without raw data [1].

Error:
TypeError: a bytes-like object is required, not 'bool'

Root cause:
At [3], to_pdf_stream directly calls io.BytesIO(), when the attachment has no
raw data, Python raises an error.

Fix:
This commit prevents errors when a user attaches a PDF file that has no raw data.

[1]:
https://drive.google.com/file/d/1onJYlCL_k51UwqKhc0kFaYFJynKuk4fT/view?usp=sharing

[2]:
https://github.com/odoo/odoo/blob/d42102cac8fff3967cb605a897bbb0e8690464ed/odoo/tools/pdf/__init__.py#L222

sentry-6963775400

closes odoo/odoo#233863

X-original-commit: 7563392be6c457b799b2700d39b2d424ca32a02e
Signed-off-by: Chong Wang (cwg) <cwg@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>