[FIX] html_editor: traceback on adding vimeo link in knowledge
Steps to reproduce:
-------------------------
1. Install the Knowledge app
2. Open any document and use `/media` to open the media dialog
3. Go to the Videos tab in the dialog
4. In another browser tab, open the Vimeo website
5. Copy any Vimeo video link and paste it into the dialog

Observation:
-------------------------
When pasting a Vimeo link, a traceback occurs:
```
TypeError: Cannot read properties of undefined (reading 'match')
    at EmbeddedVideoSelector.parseTimeToSeconds
```

Issue:
-------------------------
In the following function,
https://github.com/odoo/odoo/blob/2e3bf79e20170223cf1a666faede4bb1a56c162a/addons/html_editor/static/src/main/media/media_dialog/video_selector.js#L350-L353
This happens because the code splits the Vimeo URL using `#t`. If the URL does
not contain `#t`, the result is undefined, which is then passed to the
`parseTimeToSeconds` function.

Solution:
-------------------------
Added optional chain operator in `parseTimeToSeconds` for safe validation of
`value` before calling `.match()`

opw-5221403

closes odoo/odoo#234122

Signed-off-by: David Monjoie (dmo) <dmo@odoo.com>