[FIX] base: fixed traceback during compute of parent ids
Step to reproduce:
1. Multiple company
2. one of the company is archived
3. tax account_tax_template_s_iva0_g_i was added in 17.0
Init hook will load the data from account.tax-es_common.csv (_l10n_es_edi_facturae_post_init_hook)
when upgrading from 16.0 and fail because account_tax_template_s_iva0_g_i does not exists yet
and it's get parent_ids empty record set for archived company
https://github.com/odoo/odoo/commit/3757daca84dc080a276c04f310262a3ddf340a0f

so we got traceback from this line:

https://github.com/odoo/odoo/blob/5f60dd1af3a10ea04b2ff4efe84b50328692613b/addons/account/models/chart_template.py#L1131

The context is lost so `parent_ids` is computed without active_test=False
so non active records are excluded.

issues generated during upgrade

```
 File "/home/odoo/src/odoo/18.0/addons/l10n_es_edi_facturae/models/account_chart_template.py", line 12, in _get_es_facturae_account_tax
    taxes = {
  File "/home/odoo/src/odoo/18.0/addons/l10n_es_edi_facturae/models/account_chart_template.py", line 15, in <dictcomp>
    if self.env['account.chart.template'].ref(key, raise_if_not_found=False)
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 1131, in ref
    or self.env.ref(f"account.{self.env.company.parent_ids[0].id}_{xmlid}", raise_if_not_found)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 7003, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range
```