Cherry pick of 5650d899b4bdf7986ee05dbaf3229c554c230719 failed
stdout:

stderr:
Performing inexact rename detection:   0% (65130/20294508)   Performing inexact rename detection:   1% (204074/20294508)   Performing inexact rename detection:   2% (408148/20294508)   Performing inexact rename detection:   3% (612222/20294508)   Performing inexact rename detection:   4% (811954/20294508)   Performing inexact rename detection:   5% (1016028/20294508)   Performing inexact rename detection:   6% (1220102/20294508)   Performing inexact rename detection:   7% (1424176/20294508)   Performing inexact rename detection:   8% (1623908/20294508)   Performing inexact rename detection:   8% (1762852/20294508)   Performing inexact rename detection:   9% (1827982/20294508)   Performing inexact rename detection:  10% (2032056/20294508)   Performing inexact rename detection:  11% (2236130/20294508)   Performing inexact rename detection:  12% (2435862/20294508)   Performing inexact rename detection:  13% (2639936/20294508)   Performing inexact rename detection:  14% (2844010/20294508)   Performing inexact rename detection:  15% (3048084/20294508)   Performing inexact rename detection:  16% (3247816/20294508)   Performing inexact rename detection:  17% (3451890/20294508)   Performing inexact rename detection:  18% (3655964/20294508)   Performing inexact rename detection:  19% (3860038/20294508)   Performing inexact rename detection:  19% (4046744/20294508)   Performing inexact rename detection:  20% (4059770/20294508)   Performing inexact rename detection:  21% (4263844/20294508)   Performing inexact rename detection:  22% (4467918/20294508)   Performing inexact rename detection:  23% (4671992/20294508)   Performing inexact rename detection:  24% (4871724/20294508)   Performing inexact rename detection:  25% (5075798/20294508)   Performing inexact rename detection:  26% (5279872/20294508)   Performing inexact rename detection:  27% (5479604/20294508)   Performing inexact rename detection:  28% (5683678/20294508)   Performing inexact rename detection:  29% (5887752/20294508)   Performing inexact rename detection:  30% (6091826/20294508)   Performing inexact rename detection:  31% (6291558/20294508)   Performing inexact rename detection:  32% (6495632/20294508)   Performing inexact rename detection:  33% (6699706/20294508)   Performing inexact rename detection:  33% (6769178/20294508)   Performing inexact rename detection:  34% (6903780/20294508)   Performing inexact rename detection:  35% (7103512/20294508)   Performing inexact rename detection:  36% (7307586/20294508)   Performing inexact rename detection:  37% (7511660/20294508)   Performing inexact rename detection:  38% (7715734/20294508)   Performing inexact rename detection:  39% (7915466/20294508)   Performing inexact rename detection:  40% (8119540/20294508)   Performing inexact rename detection:  41% (8323614/20294508)   Performing inexact rename detection:  42% (8527688/20294508)   Performing inexact rename detection:  43% (8727420/20294508)   Performing inexact rename detection:  44% (8931494/20294508)   Performing inexact rename detection:  45% (9135568/20294508)   Performing inexact rename detection:  46% (9339642/20294508)   Performing inexact rename detection:  47% (9539374/20294508)   Performing inexact rename detection:  47% (9574110/20294508)   Performing inexact rename detection:  48% (9743448/20294508)   Performing inexact rename detection:  49% (9947522/20294508)   Performing inexact rename detection:  50% (10147254/20294508)   Performing inexact rename detection:  51% (10351328/20294508)   Performing inexact rename detection:  52% (10555402/20294508)   Performing inexact rename detection:  53% (10759476/20294508)   Performing inexact rename detection:  54% (10959208/20294508)   Performing inexact rename detection:  55% (11163282/20294508)   Performing inexact rename detection:  56% (11367356/20294508)   Performing inexact rename detection:  57% (11571430/20294508)   Performing inexact rename detection:  58% (11771162/20294508)   Performing inexact rename detection:  58% (11910106/20294508)   Performing inexact rename detection:  59% (11975236/20294508)   Performing inexact rename detection:  60% (12179310/20294508)   Performing inexact rename detection:  61% (12383384/20294508)   Performing inexact rename detection:  62% (12583116/20294508)   Performing inexact rename detection:  63% (12787190/20294508)   Performing inexact rename detection:  64% (12991264/20294508)   Performing inexact rename detection:  65% (13195338/20294508)   Performing inexact rename detection:  66% (13395070/20294508)   Performing inexact rename detection:  67% (13599144/20294508)   Performing inexact rename detection:  68% (13846638/20294508)   Performing inexact rename detection:  69% (14007292/20294508)   Performing inexact rename detection:  70% (14207024/20294508)   Performing inexact rename detection:  71% (14411098/20294508)   Performing inexact rename detection:  72% (14615172/20294508)   Performing inexact rename detection:  72% (14758458/20294508)   Performing inexact rename detection:  73% (14819246/20294508)   Performing inexact rename detection:  74% (15018978/20294508)   Performing inexact rename detection:  75% (15223052/20294508)   Performing inexact rename detection:  76% (15427126/20294508)   Performing inexact rename detection:  77% (15626858/20294508)   Performing inexact rename detection:  78% (15830932/20294508)   Performing inexact rename detection:  79% (16035006/20294508)   Performing inexact rename detection:  80% (16239080/20294508)   Performing inexact rename detection:  81% (16438812/20294508)   Performing inexact rename detection:  82% (16642886/20294508)   Performing inexact rename detection:  83% (16846960/20294508)   Performing inexact rename detection:  84% (17051034/20294508)   Performing inexact rename detection:  85% (17250766/20294508)   Performing inexact rename detection:  86% (17459182/20294508)   Performing inexact rename detection:  86% (17463524/20294508)   Performing inexact rename detection:  87% (17658914/20294508)   Performing inexact rename detection:  88% (17862988/20294508)   Performing inexact rename detection:  89% (18062720/20294508)   Performing inexact rename detection:  90% (18266794/20294508)   Performing inexact rename detection:  91% (18470868/20294508)   Performing inexact rename detection:  92% (18674942/20294508)   Performing inexact rename detection:  93% (18874674/20294508)   Performing inexact rename detection:  94% (19078748/20294508)   Performing inexact rename detection:  95% (19282822/20294508)   Performing inexact rename detection:  96% (19486896/20294508)   Performing inexact rename detection:  97% (19686628/20294508)   Performing inexact rename detection:  98% (19890702/20294508)   Performing inexact rename detection:  99% (20094776/20294508)   Performing inexact rename detection: 100% (20294508/20294508)   Performing inexact rename detection: 100% (20294508/20294508), done.
error: could not apply 5650d899b4b... [FIX] pivot: in scroll and menu positionning
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/web/static/src/js/views/pivot/pivot_controller.js'