[FIX] account: prevent traceback with expense accounts without code
Steps to Reproduce:
1. Install the Accounting module.
2. Enable Analytic Accounting in Settings.
3. Create and switch to a new company.
4. Create an expense type of account without setting a code.
5. Go to Analytic Distribution Models and create a new record.

Error:
TypeError: 'bool' object is not subscriptable

Cause:
Since commit https://github.com/odoo/odoo/commit/c3313b336b9f1305c363097745926f2bdf61e277,
account codes are optional. When an expense type account exists without a code,
_compute_prefix_placeholder tries to extract the first two characters of the
account code at [1]. However, an unset code field is treated as False, and
slicing this boolean value will raise an error.

Fix:
Only use the expense account code to compute prefix suggestions when the
account has a code. Otherwise, keep using the default prefix values.

sentry-7553918989

closes odoo/odoo#271856

X-original-commit: 9c5ac892b03d6114d9c4c83f6107bce7a13662e0
Signed-off-by: John Laterre (jol) <jol@odoo.com>