[FIX] sale_edi_ubl: add a test for empty Norwegian VAT
Steps to reproduce:
- Install the `sale_management` module.
- Create a new customer and set the country to `Norway`.
- Go to Sales and create a new quotation for the newly created customer.
- Click the `Print` button.

Error:
AttributeError: 'bool' object has no attribute 'startswith'

Root Cause:
At [1], `startswith()` is called on the VAT number even when the
customer's TIN (VAT) is not set, causing an error.

Fix:
This commit adds a test covering the above fix applied in [2].

[1]:
https://github.com/odoo/odoo/blob/5c2d5daa13cf582c40bdb44e245e1359d7c410f0/addons/account_edi_ubl_cii/models/account_edi_ubl.py#L924-L928

[2]:
https://github.com/odoo/odoo/commit/50ddfa124453295940adc75161fc7591c71b4fb5