Cherry pick of 90f1e4bcc522267c01d1190709d27549b9af975c failed
stdout:
Auto-merging addons/web/static/src/views/form/form_controller.scss
Auto-merging addons/web/static/src/views/list/list_renderer.scss
Auto-merging addons/web/static/src/views/list/list_renderer.xml
CONFLICT (content): Merge conflict in addons/web/static/src/views/list/list_renderer.xml

stderr:
13:00:12.190244 git.c:463               trace: built-in: git cherry-pick 90f1e4bcc522267c01d1190709d27549b9af975c
error: could not apply 90f1e4bcc522... [FIX] web: clipped dropdown on firefox in list views
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: