[FIX] auth_oauth: raise the Badrequest if the dbname doesn't available in kw
Currently, an exception is generated when the user tries to sign in
with oauth and `kw` is empty.

Error: `KeyError: 'state'`

This commit will fix the above issue by adapting the case with an empty `kw`
by raising `BadRequest()` when `dbname` was not found due to an empty `kw`.

sentry-5831561955