[FIX] mail: notification access rights
Check if user has access to the record before displaying a notification
about it.

steps to reproduce:
- create two companies (company_A and company_B)
- using the company switcher, select only company_A
- create a partner and set the field company_id on company_A
- send a sms or a mail with an error on this partner (you should have
a notification about the error on the top bar)
- use the company switcher to select only company_B

before this commit:
An error is raised when messages are fetched
odoo.exceptions.AccessError: Due to security restrictions, you are not
allowed to access 'Contact' (res.partner) records.

after this commit:
only notifications about records that can be accessed by the user are
displayed

opw-3558373