[FIX] account: prevent an error when open a portal view of invoices
Currently, an error occurs when opening a portal view of invoices and any
invoice has no 'Due Date'

Step to produce:

- Install the 'account' module.
- Create a new invoice, add a customer name and an invoice line, then save the
record.
- After that, remove the 'Payment terms' and confirm the invoice.
- Then Remove a 'Due Date' and save a record.
- Go to portal view and try to open 'Your Invoices',

TypeError: '<' not supported between instances of 'bool' and 'datetime.date'

An error occurs when the system tries to compare an invoice's due date with
today's date at [1], but the due date is missing.

Link [1]: https://github.com/odoo/odoo/blob/1615bdb7e52e5ad501922568a1baaee4fd07a4b7/addons/account/views/account_portal_templates.xml#L72

To resolve this issue, add a condition to skip the comparison between the
invoice's due date and today's date, if the due date of invoice is unavailable.

Sentry-6016842018

X-original-commit: 1829a8d6985f13fb1eff64153843d4b5d92b64a5