[FIX] payment: update modules that depend on `account`
On some DB, it is not possible to update some modules that depend on
`account`

To reproduce the issue:
1. Checkout before [1] and install `account_accountant`
2. Checkout after [1]
3. Update `account_accountant`

Error: a server error is displayed

> Field 'code' used in domain of field 'payment_acquirer_id' ([
> ('code', '=', code)]) must be present in view but is missing."")

Commit [1] contains unstable changes: it adds a domain on the field
`payment_provider_id` of `account.payment.method.line` and, to make
it work, it also adds the needed field `code` on the view
`view_account_journal_form`. But, if the view is not updated on an
existing database, the domain can not work, hence the client error.

This explains why the above use case does not work:
The module `account_accountant` has a view that also inherits the
view of account `account.view_account_journal_form`. As a result,
when updating the module (and, therefore, the view of
`account_accountant`), we `:View._validate_view` the whole view, which
will lead to:
https://github.com/odoo/odoo/blob/cc569054b83b0ed92ab8af31026fff5f29f47bca/odoo/addons/base/models/ir_ui_view.py#L2942-L2948

[1] df3edeb363c57964862e35344883a65621939ad4

opw-3993709
opw-3993707
sentry-5416409171

closes odoo/odoo#170308

X-original-commit: f957a4f9a1523d2a564e78aafd9d6831a0dbb1b7
Signed-off-by: Laurent Smet (las) <las@odoo.com>
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>