[REV] mrp: consume expected quantity on mo backorder
This reverts commit 3223deb871ca4cb4ac0381e4321f2dbf79a60189.

Steps to reproduce:

- Create 3 products: Final Product, Super Component, and Basic Component.
    - Final Product: tracked by serial number (SN).
    - Super Component is MTO.
- Final Product has a BoM:
    - 1 × Super Component
- Super Component has a BoM:
    - 1 × Basic Component
- Create and confirm an MO for 3 units of Final Product.
> This should create an MO for 3 units of Super Component.
- Split the MO of Final Product into 3 MOs of 1 unit (with the cog wheel)
- Check taht the quantity is set to 3 on the COMP move on the child MO
- Click Generate Serial on the first MO
> Error: Reserving a negative quantity is not allowed.

opw-6317083