Fix bug in ir_http.py with multi_languages
The current version of ir_http.py has a bug in method get_nearest_lang() that breaks the website module in multi_language installations. 
The error is shown in the log as:
********************
  File "/usr/lib/python2.7/site-packages/openerp/addons/website/models/ir_http.py", line 64, in get_nearest_lang
    for code, name in request.website.get_languages():
ValueError: too many values to unpack
********************
The bug is in the code:
       for code, name in request.website.get_languages():
            if code.startswith(short):
because get_languages() returns a list of tuples with THREE elements, but the code assumes those tuples are pairs and this raises a  "too many values to unpack" error.
The proposed simple fix is to iterate over the tuples and only take the only needed first element.