[I18N] base: improve in Russian translations
Currently, in Russian, the variable 'field' is translated into Russian as
'поле' which causes an error.

Error: `KeyError: 'поле'`

This commit fixes this issue by updating the translated variable
into the original variable.

sentry-5141195219

closes odoo/odoo#160734

X-original-commit: 98c4e4ec9e7076d118d19971d6e7b6c842a90f7b
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>