[FIX] stock: fix inconsistency on onhand qty on product
after this pr:
odoo#164196
It will create inconsistency during upgrade
specially when we are upgrading from 14.0 to 17.0
because when it's try to compute
qty_available, it's call _compute_quantities_dict,
on that function, to find quant domain, using get_domain_location
and on that function will find those warehouses which has
company_id = self.env.companies.ids and then related
virtual location of that warehouses. but in 14.0
will find all the warehouses as that code does
not exist in 14.0 so it will find
all the warehouses's virtual location before upgrade
and that will raise exception.

```
Traceback (most recent call last):
  File /tmp/tmpok8tnqc4/migrations/testing.py, line 211, in test_check
    self.check(value)
  File /tmp/tmpok8tnqc4/migrations/stock/tests/test_on_hand_quantity.py, line 58, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[17430, '1'], [17505, '1'], [17510, '1'], [1[59512 chars]'1']] != [[17985, '1'], [17986, '21'], [18063, '9'], [[23100 chars]'1']]

First differing element 0:
[17430, '1']
[17985, '1']

First list contains 2566 additional elements.
First extra element 1629:
[23315, '25']

Diff is 107124 characters long. Set self.maxDiff to None to see it. : Invariant check fail
```