[FIX] purchase: fix depracted product_uom field refactoring
A big refactor of UOM in saas-18.1 (https://github.com/odoo/odoo/pull/184131)
accidentally left a reference to the `product_uom` field on `purchase.order.line`.

But that field was renamed to `product_uom_id` in https://github.com/odoo/odoo/pull/186250.

In rare edge-cases, if we it `supplierinfo['product_uom_id'] = line.product_uom.id`
while confirming a purchase order, it will block it because of a traceback:

```
supplierinfo['product_uom_id'] = line.product_uom.id
^^^^^^^^^^^^^^^^
AttributeError: 'purchase.order.line' object has no attribute 'product_uom'. Did you mean: 'product_id'?
```

This PR fixes the issues by accounting for the field rename.

OPW-6068125