[FIX] base: avoid conflict during populate
partial backport of c5f8cb4f90c8cc903d0261f2c6978c8e297d4282
to avoid same errors on branch 14.0 of runbot

before this commit during populate on runbot:
ERROR: duplicate key value violates unique constraint "res_company_name_uniq"
DETAIL:  Key (name)=(company_0_EUR) already exists

after this commit:
no more errors