[FIX] purchase_stock: prevent error when opening replenish wizard
Currently, an error occurs when the replenish wizard is unable to find the
default 'Buy' route, which the user may have deleted.

Steps to produce:
- Install the `purchase_stock` module.
- Activate `Multi-Step Routes` from Settings.
- Navigate to `Inventory > Configuration > Warehouse Management > Routes (list)`.
- Delete the `Buy` route record.
- Create a new product without adding vendors or defining routes.
- Click on the `Replenish` button.
- Observe the error.

`AttributeError: 'NoneType' object has no attribute 'id'`

The issue occurs when attempting to access the `id` of the Buy route
`purchase_stock.route_warehouse0_buy` - [1], without verifying if it exists.
If this route is missing, `self.env.ref(...)` returns `None` which
leads to an `AttributeError`.

This commit resolves the issue by checking whether the
`purchase_stock.route_warehouse0_buy` route exists before attempting to
access its `id`. This prevents errors when the route is missing.

[1] - https://github.com/odoo/odoo/blob/58f4b01dda6ba2e67c21663399aab1c189f4a312/addons/purchase_stock/wizard/product_replenish.py#L108

Sentry-6275025957

closes odoo/odoo#212419

X-original-commit: 5f6bd8a364ffd30bca3c4bdb11dbc7981469c7ce
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>
Signed-off-by: Aditi Patel (adip) <adip@odoo.com>