[FIX] website: keep all parameters on force redirect
Scenario from 17.0:

- set domain on website
- go to website /website/force/1?path=%2F%3Fa%3Db%26c%3Dd with another
  domain
=> you are redirected to {domain}/?a=b instead of {domain}/?a=b&c=d

Scenario from 18.0:

- set domain on website
- go to /appointment/1 on other domain, select person date and time
- you are on /appointment/1/info with several required URL parameters
- click on "Editor"
=> you get error:

> TypeError: AppointmentController.appointment_type_id_form() missing 1
> required positional argument: 'duration'

Cause: the /website/force/ domain redirection doesn't encode the
parameter when redirecting, so we lose parameters after the first one.

Fix: encode parameters when redirecting domain in /website/force/ route.

opw-5441957

X-original-commit: f86f6f6a3dc6bbeb8c68308aab2462b9c7bb935d