[FIX] web: avoid cleaning non-dict server action results
Currently, an error occurs when a server action returns a non-dict
value.

`AttributeError: 'bool' object has no attribute 'setdefault'`

When executing a server action, its return value
is passed to `clean_action()` to process the resulting action.
However, server actions can also return values such as True, False,
or None when no action needs to be performed.
For example, [here] when resetting a bank statement line to draft, the server
action resets the linked journal entry and returns True. This value
is then passed to clean_action() [1], which expects an action dictionary
and attempts to call setdefault() [2] on it, resulting in the error above.

This commit ensure that only dictionary results should be passed to
clean_action(). Other return values are treated as no action, preventing
the error while preserving the existing behavior for valid action
dictionaries.

[here]: https://github.com/odoo/enterprise/pull/127189

[1]: https://github.com/odoo/odoo/blob/a6f99706c6a62fc65666a0ff5e58fa465b41a6fb/addons/web/controllers/action.py#L53-L59

[2]: https://github.com/odoo/odoo/blob/b3444e4bd421a30229b0dc7c8d5eb6c78b8b51ed/addons/web/controllers/utils.py#L24

Sentry-7354160052

X-original-commit: 87bc404425373b9a4ffb96817ddf7001ca322455