[FIX] l10n_tr_nilvera_edispatch: fix binary attachment domain in PDF retrieval
Steps to Reproduce:
- Install `l10n_tr_nilvera_edispatch` module.
- Run "Nilvera: retrieve e-Dispatch purchase PDFs" Scheduled Action.

Error:
ValueError: Binary field stored in attachment, accepts only existence check;
skipping domain in condition ('l10n_tr_nilvera_edispatch_xml_file', 'in', OrderedSet([True]))

Cause:
After commit https://github.com/odoo/odoo/commit/3641f23a9b4cd401444ca3371873d8123922f7b1,
The condition operators `=` and `!=` are normalized to `in` and `not in` respectively.

As a result:
`('field', '=', True)` becomes `('field', 'in', OrderedSet([True]))` and
`('field', '=', False)` becomes `('field', 'in', OrderedSet([False]))`

After this normalization, the domain optimizer `_optimize_type_binary_attachment()`
is applied - [1]. For attachment-type binary fields, it only allows `in/not in`
operators, and a value should be `{False}`. Therefore, the condition (converted)
`('l10n_tr_nilvera_edispatch_xml_file', 'in', [True])` is rejected.

Binary fields with `attachment=True` are not stored as a boolean value.
When converting their domain to SQL, `condition_to_sql()` - [2] handles them
as an EXISTS check on `ir.attachment` to determine whether an attachment exists.

Fix:
This commit replaces the `= True` in the condition with `!= False`.

[1]: https://github.com/odoo/odoo/blob/762fd7c0b65e8f8e3eb59eb8a57b1394cb176339/odoo/orm/domains.py#L1782-L1784
[2]: https://github.com/odoo/odoo/blob/762fd7c0b65e8f8e3eb59eb8a57b1394cb176339/odoo/orm/fields_binary.py#L217-L218

sentry-7627832395