Cherry pick of 197375949bb3a24f676b0d855b0b9004cdd02add failed
stdout:

stderr:
error: could not apply 197375949bb... [FIX] web_editor: prevent switching to text tools immediately
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'