[FIX] analytic: include custom groupBys in onGroupBySelected search items
Steps to reproduce:
- Install 'Accounting' module
- Search 'Analytic Report' > Click on 'Total' > 'Custom Group'
- Select 'Journal Item' > Now again close and select 'Journal Item'

Traceback:
TypeError: Cannot destructure property 'fieldName' of 'searchItems.find(...)' as it is undefined.
    at AnalyticPivotRenderer.onGroupBySelected (http://localhost:8069/web/assets/3b7bf10/web.assets_backend_lazy_dark.min.js:434:7)
    at Object.onSelected (eval at compile (http://localhost:8069/web/assets/b0799bf/web.assets_web.min.js:1376:421), <anonymous>:78:62)
    at DropdownItem.onClick (http://localhost:8069/web/assets/b0799bf/web.assets_web.min.js:2373:24)

Cause:
Custom groupBys were not being added to the search items list in
`onGroupBySelected`, causing a lookup failure when selecting a
custom groupBy from the dropdown.

Solution:
Added custom groupBys to the search items list so they can be
found and applied correctly.

opw-6227164