[FIX] calendar: handle singleton exception for sync calendar event
This error occurs when recurrence_id has no records when the user tries to
delete the sync calendar which has recurrent events.

Error: 'Expected singleton: calendar.recurrence()'

See-
https://github.com/odoo/odoo/blob/15.0/addons/calendar/models/calendar_event.py#L715

sentry-4367276387

closes odoo/odoo#134424

X-original-commit: 6ba4a671c4b37120146f137f88363dd5b170562f
Signed-off-by: Arnaud Joset (arj) <arj@odoo.com>