Cherry pick of bee227ae5c4777b4961ac82f36b17ddd942c3794 failed
stdout:

stderr:
error: could not apply bee227ae5c4... [FIX] account: reconciliation progress no count fail
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'