[FIX]  {website_}event: fix event tour
Before this commit, the user got a traceback saying:
```txt
TypeError: Cannot read properties of undefined (reading 'apply')
    at EventAdditionalTourSteps._get_website_event_steps
```
the reason of that issue is because a [recent generic change reviews](#125716)
`patch` function and so `this._super` no longer exists and has to be
replace by `super` as we extend a method of a class extended.

This commit adapts the additional steps adding via `patch` function
to be able to add those steps and start the tour as expected.

closes odoo/odoo#142653

Signed-off-by: Warnon Aurélien (awa) <awa@odoo.com>