[FIX] stock: prevent errors on generating lots
Currently, an error occurs when user tries to generate lots on a picking receipt
for a product that is tracked by lots.

Steps to replicate:
- Install `stock` and create a product `test` tracked `by lots`.
- Open Inventory > Operation > Receipts , create a new one with product `test`
  and quantity 3.
- Open the form view of the stock.move for `test` using the `view` button.
- Click `Generate Serials/Lots` and type `a` in `Quantity received` and click
  generate. (Error-1 will occur.)
- Click `Generate Serials/Lots` and type `a` in `Quantity per lot` and click
  generate. (Error-2 will occur.)

Error-1 :
```
File '/home/odoo/odoo18/community/addons/stock/models/stock_move.py', line 1055, in generate_lot_qty
    line_count = int(quantity // qty_per_lot)
                     ~~~~~~~~~^^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

Error-2 :
```
File '/home/odoo/odoo18/community/addons/stock/models/stock_move.py', line 1053, in generate_lot_qty
    if qty_per_lot <= 0:
       ^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

Cause:
- As the user typed in alphabets the [parsefloat] returns `NaN` which will be
  translated to `None` python side.
- As quantity is received as None the [line1] raises Error-1.
- As qty_per_lot is recieved as None the [line2] raises Error-2.

Solution:
- Raised Usererror when quantity received or quantity per lot is either negative
  or not a number.

[parsefloat]: https://github.com/odoo/odoo/blob/2da791df55762ae4dc1c06d2a43fad25b09dc11b/addons/stock/static/src/widgets/generate_serial.js#L50-L51

[line1]: https://github.com/odoo/odoo/blob/2da791df55762ae4dc1c06d2a43fad25b09dc11b/addons/stock/models/stock_move.py#L1001

[line2]: https://github.com/odoo/odoo/blob/2da791df55762ae4dc1c06d2a43fad25b09dc11b/addons/stock/models/stock_move.py#L999

related-sentry-7254849206