[FIX] mail, account: fix traceback when send invoices in batch
This error occurs when a user attempts to send multiple invoices at once.

Steps to Reproduce:

 - Install the account module.
 - Open Invoices.
 - Select multiple invoices and click Send.

KeyError: <NewId origin=3>

This issue was introduced in commit [1], where the _compute_alerts method
tries to set an alert in the wizard, but since this is a compute method,
we get a newId in the wizard when trying to access self.id. As a result,
we get False and the current issue occurs.

This commit will fix the above issue by using _origin.id, ensuring that it
always returns the ID of a valid record.

[1]- https://github.com/odoo/odoo/commit/39d1907d77ca9c88431e7e9dc9e8c938c
79a2987#diff-08b58bfc71bad9cffdb2d600d2f630a5643336c51d7ff6ccb94d0af859add094L58
-R63

Sentry-6562659542

closes odoo/odoo#210230

X-original-commit: 058d324855a6e2fe3df51386aa153d46419766bf
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>