[FIX] l10n_in: prevent error when configure an indian intergration
This error occurs when a user selects `Fiscal Country` to `India` and attempts
to configure any `Indian Integration`.

Steps to reproduce :
1. Install module `l10n_in`.
2. Create a new company `without assigning a country` and switch on it.
3. In Accounting settings :
  - Set Fiscal Country to India and Save.
  - Enable Registered Under GST, enter the GST Number, and Save.

ValueError: External ID not found in the system: account.1_sgst_group.

This error occurs when the `Fiscal Country` is set to `India` and due to recent
merge in module  at [1] allows users to fill in sgst_group even when the
`Fiscal Localization Package is not set`. As a result, the system cannot find
the required sgst_groupID, which is created dynamically when the Fiscal
Localization Package is set to India.

This commit ensures that if the id does not exist, the function will return
None instead of raising an exception.

Link [1] : https://github.com/odoo/odoo/pull/190265

sentry: 6362946694