[FIX] project: prevent traceback when editing message as a portal user
## Issue
When logged as a portal user, clicking the *Edit* button on a message in
 the chatter does not do anything.

## Steps to reproduce
1. Install *Project* (`project`)
2. Create a Project P and a Task T
3. In the Setting of Project P, click *Share Project* and select a portal user
4. Logged as a portal user, open Task T, send a message in the chatter,
then try to edit it by clicking the *Edit* (pencil) button.
5. **Nothing happens, but a traceback appears in the console: _Caused by:
TypeError: Cannot read properties of null (reading 'id')_**

## Cause
The condition causing this error is the following:

https://github.com/odoo/odoo/blob/5cfdc9260653a2b22eb79b16702769928d450932/addons/project/static/src/project_sharing/chatter/composer_patch.js#L9-L13

where `this.thread` is not defined yet. Other conditions in this patch
check for `this.thread` before trying to read its `id`
[[1](https://github.com/odoo/odoo/blob/5cfdc9260653a2b22eb79b16702769928d450932/addons/project/static/src/project_sharing/chatter/composer_patch.js#L25),
[2](https://github.com/odoo/odoo/blob/5cfdc9260653a2b22eb79b16702769928d450932/addons/project/static/src/project_sharing/chatter/composer_patch.js#L32)],
which leads to believe that the check was simply forgotten in this condition.

opw-6072570

closes odoo/odoo#258721

X-original-commit: 65c4ade5a811fc3cc6ccbf5e2130cc766975c82d
Signed-off-by: Xavier Bol (xbo) <xbo@odoo.com>
Signed-off-by: Quentin Colla (qucol) <qucol@odoo.com>