[FIX] web: allow records grouped by property fields to export
Step to reproduce
- open a task
- add a property field , say test
- add values for this field in few records
- go to list view and group by test
- select a record from result and export it (from Action btn)

Observation:
- traceback
```
  File "/home/odoo/17.0/addons/web/controllers/export.py", line 486, in base
    groupby_type = [Model._fields[x.split(':')[0]].type for x in groupby]
                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'task_properties.b60ee9baefee14a8'
```

Cause:
- The issue is caused by splitting, which didn't considered property field
- it tried to look for `task_properties.b60ee9baefee14a8` in _fields which
causes KeyError

FIx:
- split the field name properly to bring out actual field name while considering
granularity as well as the property fields

opw-5159155