[FIX] website_event_track: handle overflow error for large duration value
This issue occurs when we enter the large value(1111111111) in the `duration`
field.

Steps to produce:
- Install `website_event_track` module.
- Go to Events > Tracks > Create new record.
- Select any `track date` and enter the large duration value(e.g.1111111111)
- Save the record > Error will be generated.

Error: OverflowError: date value out of range

This issue occurs because here
https://github.com/odoo/odoo/blob/39fa1f851e53eed633d04145752293fb93cc41f7/addons/website_event_track/models/event_track.py#L277
when calculating the `track end date` based on theprovided duration value,
an error is triggered.

sentry-4573940256