[FIX] mail: only allow image operations for images in AttachmentViewer
First bug
=========

Steps to reproduce
------------------

- Go to A project task
- Upload an pdf
- Preview the pdf
- Press on the "+" key

```
TypeError: Cannot read properties of null (reading 'offsetWidth')
    at AttachmentViewer.updateZoomerStyle
```

Cause of the issue
------------------

Some operations should only be called when the current attachment is an
image.

Second bug
==========

Steps to reproduce
------------------

- Go to documents
- Click on an image document
- Edit the "Tags" field and type +

The image is resized

Cause of the issue
------------------

In the documents app, the viewer is not fullscreen.
The keyboard actions should only be used when the attachment viewer is
focused. The onKeyDown was bound to the document.

Solution
--------

We can bind the `onKeyDown` to the AttachmentViewer.
Since we now need the viewer focused, we can use the autofocus hook.

opw-3456439

X-original-commit: 7fa95127e55e21bcaf28191c872cd0a1b8a0a6a6