[FIX] website_sale: Ensure checkout steps are published
Traceback:
---------
```
Error while render the template
KeyError: 'current_step'
Template: website.step_wizard
Path: /t/div/div[1]/div/div/a/span
```
Ensure `is_published` is set to True for '/shop/extra_info' if the `extra step`
feature is enabled during migration.

Cause of the issue:
-----------------------
The issue occurs because the is_published field is set to False,
resulting in an empty value for `current_step`. This happens because
the `allowed_steps_domain` fails to include the step when the condition
is_published=True is not satisfied.

During migration while creation of `website.checkout.step` records,
the standard logic `is_published = bool(step.step_href != '/shop/extra_info')`
sets `is_published=False` for the /shop/extra_info step, even if the extra step
feature was enabled in v18.2. This leads to a KeyError when accessing
`/shop/extra_info` after migration. This fix ensures `is_published` is correctly
 set based on whether the extra info feature is enabled.

Steps to reproduce:
------------------------
1) In Odoo v18.2, go to Website > Configuration > Settings,
   and enable Extra Step During Checkout
2) Migrate the database to v18.3.
3) Navigate to /shop/extra_info on the website.

upg-2992540
opw-4867915