[FIX] account_edi_ubl_cii: allow bill upload with empty descriptions
In the Accounting app, users can upload vendor bills from XML files.
The XML files describe the content of the bill, such as the name and
address of the customer, the delivey and payment information,
or the invoice lines.

Whenever the `<cac:OrderReference>`/`<cbc:ID>` is missing **and** all
the `<cac:Item>`/`<cbc:Description>` are empty, the upload of the bill
fails and an *Odoo Server Error* is shown to the user.
This happens because of the following loop:

https://github.com/odoo/odoo/blob/2217d5220640531828eb5b2ae7a9d41ba9c97e78/addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py#L1166-L1169

If the `<cbc:Description>` field is empty, the attribute `desc.text` is
`None`, and calling `str.join` on it raises the following TypeError:

```
TypeError: sequence item 0: expected str instance, NoneType found
```

This fix prevents the error and allows the bill to be created as expected.

Steps to reproduce:
1. Install the Accounting (`accountant`) app
2. Go to Accounting > Vendors > Bills
3. Click *Upload*
4. Upload an XML file with no `<cac:OrderReference>` and where all the
items have empty `<cbc:Description>` fields.
An example of such file can be found is
`addons/account_edi_ubl_cii/tests/test_files/bis3/test_vendor_bill_empty_description.xml`,
which is an edited version of the `test_vendor_bill.xml` from the same directory
5. An *Odoo Server Error* appears

opw-5269474

X-original-commit: 43d16070d79d6de50967bab54f9ac92da7abd573