[FIX] website_slides: Fix bug when clicking at 'Go to website' of a slide before saving the course.
Bug description:
Inside a course add a new content (slide) and 'save & close'.
Then without saving the course click at 'Go to website' of this content.
Then his error will be displayed:
```  File "/data/build/odoo/addons/website_slides/models/slide_slide.py", line 387, in create
    channel = self.env['slide.channel'].browse(values['channel_id'])
KeyError: 'channel_id'```

Bug Causes:
In view `view_slide_slide_form_wo_channel_id`:
- Field `channel_id` was removed instead of making it invisible.