[FIX] l10n_in_ewaybill_stock: fix traceback on generating ewaybill
Before this commit:
While generating an ewaybill we get the following traceback:
```log
  File "/home/odoo/odoo/community/addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py", line 418, in _generate_ewaybill_direct
    'ewaybill_expiry_date': self._indian_timezone_to_odoo_utc(
  File "/home/odoo/odoo/community/addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py", line 433, in _indian_timezone_to_odoo_utc
    local_time = datetime.strptime(str_date, time_format)
TypeError: strptime() argument 1 must be str, not None
```

After this commit:
We resolve the traceback it was caused due to
string to datetime conversion because we were
receving `None` value instead of datetime string.
Now `_indian_timezone_to_odoo_utc` will return
False, incase of missing string datetime from
the response

closes odoo/odoo#176287

X-original-commit: e22d29a7c74c670911a4c17205465ea0da669674
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>
Signed-off-by: Harsh Modi (hamo) <hamo@odoo.com>