[FIX] tools: Regression managind xml error.
**Rationale:**

In the earliest versions of odoo fix an xml error while you are programming a new view was really complex because the error was not explicitly shown in the log This force you to guess what happen, with a no deterministic value to go and debug.

**Before this change**

- The position of the error is shown inside the file.
- Traceback telling you that the convert.py file failed.

**Example:**
```
.....traceback.

....ParseError: While parsing /path/.../.../views/file_views.xml

<xml entry action="...." id="..." parent="xml"/>
```

**After this change:**

- The position of the error is shown inside the file.
- Traceback telling you that the convert.py file failed.
- The actual returned error in the Exception.

Example
```
.....traceback.

....ParseError: While parsing /path/.../.../views/file_views.xml

The error was:

ValueError('External ID not found in the system: xxx.xxxx')
```

On this example it is clear (for example) that you have a type in the xml_id referred.