[FIX] pos_restaurant: load only shop demo products when no restaurant
When the user using `point_of_sale` deletes pos restaurant and tries
to load demo products in pos shop then user will face error.

Note: Use db without demo data

steps to produce:
- Install `point_of_sale`.
- Point Of Sale > Configuration > Point Of Sales, delete pos restaurant.
- Point Of Sale > Shop > New Session, click on `our demo products`.

Error: `KeyError: 'name'`

After applying our commit, if the user clicks on `our demo products`
after deleting pos restaurant then the user would be atleast able to see
shop demo products and other demo products which are not part of
pos restaurant.

sentry-4399441443

closes odoo/odoo#135633

X-original-commit: feaf26db77fde9afae23c8b3c3ea2f0f441b4dae
Signed-off-by: Joseph Caburnay (jcb) <jcb@odoo.com>