[FIX] purchase: prevent error when user mail is empty
This error occurs when user click on 'i' (information) icon.

Steps to reproduce:
- Install 'Purchase' module (without demo)
- Open PO > Add 'vendor' (eg: Administrator)
- Enable 'Ask confirmation' and click on 'i' icon

Traceback:
TypeError: Cannot read properties of undefined (reading 'toast_message')

This error occurs because the user has an empty 'email', which results in a
'False' value at [1]. By adding a condition, we bypass the 'toast_message'
assignment, but at [2], the code still attempts to access 'toast_message'.

[1]: https://github.com/odoo/odoo/blob/b1a007e4db9f6f844c6d6cee6963d6bc3ba024b8/addons/purchase/models/purchase_order.py#L988-L996
[2]: https://github.com/odoo/odoo/blob/b1a007e4db9f6f844c6d6cee6963d6bc3ba024b8/addons/purchase/static/src/toaster_button/toaster_button_widget.js#L22

No task ID