[FIX] phone_validation: fallback if no region provided
Before this commit if you would call phone_parse() but not pass along a country code it would crash.
THis is reproducable by calling the phone_parse function and not setting a country on the contact.
In this case you would get the following traceback:
AttributeError: 'bool' object has no attribute 'upper'.

This happend because the phonenumbers library tries to upper() the region but if Odoo doesn't have a country set it passes along False.
By doing a fallback to 'None' the phonenumbers library will natively handle this and the user in the UI does not get a traceback.