Cherry pick of 01fe5da9cde07e5bbd7ceaa404c2718078fe992d failed
stdout:

stderr:
Performing inexact rename detection:  45% (1497184/3265696)   Performing inexact rename detection:  46% (1503040/3265696)   Performing inexact rename detection:  47% (1536224/3265696)   Performing inexact rename detection:  48% (1569408/3265696)   Performing inexact rename detection:  49% (1600640/3265696)   Performing inexact rename detection:  50% (1633824/3265696)   Performing inexact rename detection:  51% (1667008/3265696)   Performing inexact rename detection:  52% (1698240/3265696)   Performing inexact rename detection:  53% (1731424/3265696)   Performing inexact rename detection:  54% (1764608/3265696)   Performing inexact rename detection:  55% (1797792/3265696)   Performing inexact rename detection:  56% (1829024/3265696)   Performing inexact rename detection:  57% (1862208/3265696)   Performing inexact rename detection:  58% (1895392/3265696)   Performing inexact rename detection:  59% (1928576/3265696)   Performing inexact rename detection:  60% (1959808/3265696)   Performing inexact rename detection:  61% (1992992/3265696)   Performing inexact rename detection:  62% (2026176/3265696)   Performing inexact rename detection:  63% (2057408/3265696)   Performing inexact rename detection:  64% (2090592/3265696)   Performing inexact rename detection:  65% (2123776/3265696)   Performing inexact rename detection:  66% (2156960/3265696)   Performing inexact rename detection:  67% (2188192/3265696)   Performing inexact rename detection:  68% (2221376/3265696)   Performing inexact rename detection:  69% (2254560/3265696)   Performing inexact rename detection:  70% (2287744/3265696)   Performing inexact rename detection:  71% (2318976/3265696)   Performing inexact rename detection:  72% (2352160/3265696)   Performing inexact rename detection:  73% (2385344/3265696)   Performing inexact rename detection:  74% (2418528/3265696)   Performing inexact rename detection:  75% (2449760/3265696)   Performing inexact rename detection:  76% (2482944/3265696)   Performing inexact rename detection:  77% (2516128/3265696)   Performing inexact rename detection:  78% (2547360/3265696)   Performing inexact rename detection:  79% (2580544/3265696)   Performing inexact rename detection:  80% (2613728/3265696)   Performing inexact rename detection:  81% (2646912/3265696)   Performing inexact rename detection:  82% (2678144/3265696)   Performing inexact rename detection:  83% (2711328/3265696)   Performing inexact rename detection:  84% (2744512/3265696)   Performing inexact rename detection:  85% (2777696/3265696)   Performing inexact rename detection:  86% (2808928/3265696)   Performing inexact rename detection:  87% (2842112/3265696)   Performing inexact rename detection:  88% (2875296/3265696)   Performing inexact rename detection:  89% (2906528/3265696)   Performing inexact rename detection:  90% (2939712/3265696)   Performing inexact rename detection:  91% (2972896/3265696)   Performing inexact rename detection:  92% (3006080/3265696)   Performing inexact rename detection:  93% (3037312/3265696)   Performing inexact rename detection:  94% (3070496/3265696)   Performing inexact rename detection:  95% (3103680/3265696)   Performing inexact rename detection:  96% (3136864/3265696)   Performing inexact rename detection:  97% (3168096/3265696)   Performing inexact rename detection:  98% (3201280/3265696)   Performing inexact rename detection:  99% (3234464/3265696)   Performing inexact rename detection: 100% (3265696/3265696)   Performing inexact rename detection: 100% (3265696/3265696), done.
error: could not apply 01fe5da9cde... [FIX] stock: correctly works on non unique recordsets
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'addons/stock/models/stock_warehouse.py'
Recorded preimage for 'addons/stock/tests/test_warehouse.py'