[FIX] hr_expense: `total_amount_company` without company set
`_compute_total_amount_company` calls `currency_id._convert`,
for which it's required to pass a company in the args

However, the field `company_id` is not required on the model `hr.expense`,
which mean it's not impossible to have an `hr.expense` without a company set.

Though, `_compute_total_amount_company` will only call `_convert`
when the expense `company_currency_id` is set.
```python
if expense.company_currency_id:
```

`company_currency_id` is a related field to the expense sheet:
```python
related='sheet_id.currency_id'
```

On the sheet, the currency is filled by default with the user company currency:
```python
default=lambda self: self.env.user.company_id.currency_id
```
On the expense sheet, it's the same strategy to fill by default the company:
```python
default=lambda self: self.env.user.company_id
```

So, when `company_currency_id` is set on the `hr.expense`,
there are pretty good chances `company_id` is set on the expense sheet,
and we can therefore fallback to the sheet company when
the expense company is not set correctly.

Migration request 44751

```
File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/hr_expense/saas~11.1.2.0/post-compute-fields.py", line 12, in migrate
util.recompute_fields(cr, 'hr.expense', ['total_amount_company'], ids=ids)
File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util.py", line 3895, in recompute_fields
records.recompute()
File "/src/odoo/12.0/odoo/models.py", line 5301, in recompute
vals = {n: rec[n] for n in ns}
File "/src/odoo/12.0/odoo/models.py", line 5301, in <dictcomp>
vals = {n: rec[n] for n in ns}
File "/src/odoo/12.0/odoo/models.py", line 5148, in __getitem__
return self._fields[key].__get__(self, type(self))
File "/src/odoo/12.0/odoo/fields.py", line 1016, in __get__
self.determine_value(record)
File "/src/odoo/12.0/odoo/fields.py", line 1105, in determine_value
self.compute_value(recs)
File "/src/odoo/12.0/odoo/fields.py", line 1083, in compute_value
self._compute_value(records)
File "/src/odoo/12.0/odoo/fields.py", line 1074, in _compute_value
getattr(records, self.compute)()
File "/src/odoo/12.0/addons/hr_expense/models/hr_expense.py", line 115, in _compute_total_amount_company
expense.company_id, date_expense or fields.Date.today())
File "/src/odoo/12.0/odoo/addons/base/models/res_currency.py", line 200, in _convert
assert company, "convert amount from unknown company"
AssertionError: convert amount from unknown company
```