[FIX] stock: prevent error when creating custom serial/lots
Issue Before This Commit:
============================

When generating custom serial/lot numbers in a receipt, clicking the 'New'
button in the 'Generate Lot Numbers' wizard(dialog) throws the following
error: 'Cannot read properties of undefined (reading 'lot_sequence_id')'.

Steps to Reproduce:
============================

- Install the stock module.
- Create a receipt for a product with lot/serial tracking.
- Confirm the receipt & click the "Details" button.
- Click the "Generate Serials/Lots" button.
- Then click the "New" button.

With This Commit:
============================

This issue was introduced by this
PR [205486](https://github.com/odoo/odoo/pull/205486),
as that PR did not cover this case. This commit ensures that lot_sequence_id
is correctly initialized and available when the "New" button is clicked
during serial/lot number generation.

closes odoo/odoo#208359

Signed-off-by: Steve Van Essche <svs@odoo.com>