[FIX] hr_recruitment: prevent error when creating alias ID
Currently, an error occurs when a user creates an alias ID.

Steps to Reproduce:
 - Install the hr_recruitment module.
 - Go to your current company and set the Email Domain value.
 - Go to Recruitment > Applications > By Job Positions.
 - In list view, create or open an existing Job Position.
 - In the Trackers tab, create a record through “Add a line.”
 - Click the clipboard button next to the email field.

Error:
AttributeError: 'hr.recruitment.source' object has no attribute 'name'

After [this commit], the dependency of utm.source.mixin was removed,
along with the source_id field referencing a source. The name field
was provided by utm.source.mixin, and it is now being accessed in
recruitment source, which raises the error.

This commit ensures that the system uses the name of source_id,
as it has been replaced by _rec_name to "source_id".

[this commit]: https://github.com/odoo/odoo/commit/927682ce8f5e6faea0da7216ac1163411f5e83bd

[1]: https://github.com/odoo/odoo/blob/949d368eda3d6f2c9b5fb04ec3a41fa1b2cc90d4/addons/hr_recruitment/models/hr_recruitment_source.py#L42

sentry-7353030705

closes odoo/odoo#255267

Signed-off-by: Mélanie Peyrat (mepe) <mepe@odoo.com>