[FIX] purchase_stock: prevent error when removing the promised date on a pol
Currently, an error occurs when the user removes the promised date on a
purchase order line.

Steps to Reproduce:

 - Install the purchase_stock module.
 - Create a purchase order with an order line.
 - Confirm the purchase order.
 - Validate the receipt using the smart button on the purchase order.
 - In the order line, make the Promised Date (optional, hidden) field visible.
 - Remove the value of the Promised Date and save.

AttributeError: 'bool' object has no attribute 'date'

After [this commit], the partner on-time rate depends on the promised date.
When the user removes the Promised Date from the purchase order line,
it tries to compute partner on-time rate. When it filters the move records
based on the comparison between the PO line promised date and the move
date and accesses the date from promised date [1], it raises an error.

This commit ensures that the comparison between the move date and the
promised date is performed only when the promised date exists. If no
promised date is set, the on-time rate is computed as 0.

[this commit]: https://github.com/odoo/odoo/commit/2ce0107c914f5eab3b724119ef6c812c347cdc8d#diff-c3231f0c5829f511c10589fc2c2298fe1c03d59f59a04a1ba8a60c85383ffa42

[1]: https://github.com/odoo/odoo/blob/2936763b700fcf31e3fd126a7c412c274783f342/addons/purchase_stock/models/res_partner.py#L57

sentry-7384699891