[FIX] mail: prevent error when use an icon in email template
Currently, an error occurs when using an image icon in the email template.

Step to produce:
- Install the 'mail' module.
- Go to Settings / Technical / Email / Email Templates, and open any templates.
- Insert any image icon, and save the record.

ValueError: `unknown color specifier: '1x1'`

An error occurred when attempting to retrieve computed styles for the element
during inlining converting. Specifically, when the system tries to fetch the
color code and other CSS properties, it returns empty values because
`getComputedStyle` fails to properly access the full set of styles from the
cloned element. This is because `getComputedStyle` cannot retrieve styles from
an element when it is detached from DOM (a cloned element not in a DOM).

To resolve this issue, the cloned element is temporarily added to a hidden
iframe within the DOM, So `getComputedStyle` access the required style
properties.

Ref:- https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle

Sentry-5747299019