[FIX] event: prevent error when editing full page ticket
The error occurs when a user tries to edit the address field in a report, which
causes the template `event_report_template_formatted_event_address` to act as
the `main_node` in the following [line](https://github.com/odoo/enterprise/blob/d1b36478bef4bae37dbb9f2394f36a5ed365f58c/web_studio/controllers/keyed_xml_differ.py#L658).
According to the following [commit](https://github.com/odoo/enterprise/pull/62955/commits/0489fcf7d2c6666b53aaa2007e636c5132028cf6),
when modifying elements within a report, it is assumed that the modified
elements will always have a parent view where the modification occurs.

**Steps to replicate:**
* Install `event` and `web_studio`
* Events > Studio > Reports > Full Page Ticket Example
* Put your cursor to the left of `Rue de la paix 123` next to the small gps
  symbol
* Type anything > Save

`AttributeError: 'NoneType' object has no attribute 'replace'`

**Solution:**
* Add a wrapping <div> element so that it acts as the `main_node` instead of the
  template itself, which does not have a parent.
* This would allow user to make changes near address.

**Sentry-6727234781**