Cherry pick of 38c1814b3ba3b7bbf2f15d8c939485cbb915e776 failed
stdout:

stderr:
error: could not apply 38c1814b3ba... [FIX] l10n_ch: qr bill report: display "Reference" only when using a QR-IBAN (hence a QRR reference). When using another kind of account, only use "Additional information" instead.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'