[FIX] stock: put in pack from SML view
Putting in pack from the SML view leads to package incorrectly located

To reproduce the issue:
1. In Settings, enable "Package"
2. Confirm a delivery with 2 available products
3. Open the SML thanks to the smart button
4. Tick a line > Put in pack
5. On the second line, in "Destination Package", look for the package

Error: it is impossible to find it

When opening the SML thanks to the smart button, we also load a lot
of default values:
https://github.com/odoo/odoo/blob/1492abd8c6bcfdbc48f730f6767b177aeff54bf7/addons/stock/models/stock_picking.py#L1203-L1221
Those are (obviously) SML specific.

However, this context is used when putting in pack. This is a
problem since `location_id` is also the field name of a package. As
a result, the ORM defines the location of the new package with the
default value, i.e. the source location of the SML. This is incorrect.

One consequence of this bug is the step 5 of the above use case.
When looking for a package, a domain checks its location:
https://github.com/odoo/odoo/blob/35feed47622b279abf8e593d8190ea36b64d32fd/addons/stock/models/stock_move_line.py#L51-L55
It must be either `False` or equal to the dest loc, which is not the
case with the created package.

Now... About the solution. It's probably difficult to do something
more hacky. However, it's not too invasive in the code and all user
will take benefit from it once the commit is deployed. On master, we
will discuss with both frameworks to negotiate/find something more
elegant.

OPW-5215243

closes odoo/odoo#242328

Signed-off-by: William Henrotin (whe) <whe@odoo.com>