[FIX] web: prevent error when exporting file in xlsx format
When the user tries to export a file of attachment in xlsx format,
A traceback will appear.

Steps to reproduce the error:
- Open attachments > Upload a file that does not contain base64-encoded content
- Select that file > Actions > Export > Export Format: XLSX >
  Add File content(raw) field > Export

Traceback:
"AttributeError: 'ExportXlsxWriter' object has no attribute 'field_names'"

In this commit: https://github.com/odoo/odoo/commit/c3c1900ffc43d6052db58ee5b945fa3383f2b25a
"field_names" is renamed to "fields".

https://github.com/odoo/odoo/blob/0e98b684834cf9e1d646e55599e7bc00aa5997f0/addons/web/controllers/export.py#L231
Here, "field_names" is still used.
So, it will lead to the above traceback.

sentry-6096581800

closes odoo/odoo#212104

X-original-commit: 5870b508089fc7a1aaa8d321232d159d6d99e896
Signed-off-by: Aaron Bohy (aab) <aab@odoo.com>
Signed-off-by: Renilkumar Kajavadra (reka) <reka@odoo.com>