[FIX] hr_work_entry_holidays: fix dates computaiton in `write`
We need to filter out records without `request_date_from` and
`request_date_to` to avoid the error:
```
  File "/tmp/tmpiaelju95/odoo/17.0/addons/hr_work_entry_holidays/models/hr_leave.py", line 180, in write
    stop = datetime.combine(max(stop_dates) + relativedelta(days=1), time.max)
TypeError: '>' not supported between instances of 'datetime.date' and 'bool'
```

Issue observed in test upgrades of `l10n_hk_hr_payroll`

closes odoo/odoo#140286

Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>