[FIX] website_livechat: verify if image_small is set
image_small is not required and may fail if empty
TypeError: cannot concatenate 'str' and 'bool' objects

Closes #13726