[FIX] l10n_es_edi_facturae: restrict xml currency fields to 2 decimals
Steps to reproduce:
- Have facturae modules installed
- Generate invoice with any amount
- Send to Facturae

Issue:
Resulting XML has 8 digits after the decimal point on several fields,
such as unit price, gross amount, and total cost.

When trying to validate such an XML with e-Fact [1], this results in validation
error: "RCF06001: En facturas emitidas en euros, alguno de los importes de las
líneas tiene más de dos decimales (regla 6a del anexo II de la Orden
HAP/1650/2015)."

It occurs after 88b7ee6d9d2a7fe96512da0a7eaf8efcf9020ee1. Even
if the TotalCost and GrossAmount have more digits in the xml, the file
will be accepted by the fiscal entity only if the digits after the
second one are all 0's. If any of the high precision digits is used,
validation may fail.

This commit partially revert changes introduced before because only
UnitPriceWithoutTax can actually have more precision

[1] https://efact.aoc.cat/bustia/validation/validateFile.htm

opw-5927356

X-original-commit: bc5cadbeffdc22df9ab7282e8183eb41d5aafdc3