[FIX] mrp_subcontracting: clean context of compo recording
On a receipt from a subcontractor, if the user prints the labels, it
will also print the labels of the components.

To reproduce the issue:
1. Create two storable products P_finished, P_compo
2. Create a BoM:
    - Product: P_finished
    - Type: Subcontracting
    - Subcontractors: a new subcontractor SC
    - Components: 1 x P_compo
3. Create and confirm a purchase order:
    - Vendor: SC
    - Products: 1 x P_finished
4. Open the receipt
5. Open the detailed operations of P_finished
6. Set the producing quantity to 1 and record the production
7. Print the labels

Error: P_compo is in the labels, it should not

When opening the receipt (step 4), the tree view of all operations has a
context with a lot of default values:
https://github.com/odoo/odoo/blob/4248aac2d224363a6ac4a59881bdb7c321623e4b/addons/stock/views/stock_picking_views.xml#L355-L358
Among them, a default value for `picking_id`.
Step 5-6, the user opens the detailed operations and completes the
produced/consumed quantities. Here is the issue: when saving the
quantities, a SML is created for the consumption of P_compo and because
of the context, its `picking_id` field is defined with the receipt
(which is incorrect).
Finally, when opening the wizard to print the labels, we use the SML of
the picking to get the products that need to be printed:
https://github.com/odoo/odoo/blob/d6304b28b8de027ba6eaa44ebc9b4b28d2c166c0/addons/stock/models/stock_picking.py#L1505-L1507
So, we will print P_compo on the labels PDF.

OPW-2991592

closes odoo/odoo#103017

X-original-commit: 1be768256a992042d9f53d2bda58b4a77b0cbbeb
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Adrien Widart <awt@odoo.com>