[REV] l10n_din5008: print delivery slip
This reverts [1] since it breaks the delivery slip

To reproduce the issue:
(Need `stock`)
1. Configure the document layout as DIN 5008
2. Create and validate a delivery order
3. Print the delivery slip

Error: Some information have disappeared (order, shipping date, and so on)

Reverting [1] since it's a recent commit, its use case is neither important
nor urgent, and it impacts several customers.

[1] 8d588f8198d9057311304e596c009a0795ca6ec7

OPW-6250072
OPW-6260066
OPW-6249926
OPW-6264966

closes odoo/odoo#268475

Signed-off-by: Adrien Widart (awt) <awt@odoo.com>