Cherry pick of aa4f24c5d21233f4e9c00cc09270ef634d271400 failed
stdout:

stderr:
error: could not apply aa4f24c5d21... [IMP] sale: ignore null SO in reconciliation matching
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'