[FIX] account_edi_ubl_cii: Avoid problems in community edition
The fields `deferred_start_date` and `deferred_end_date` are created
by the enterprise addon `account_accountant`, so not having it
installed, this crashes with:

```
  File "/opt/odoo/auto/addons/account_edi_ubl_cii/models/account_edi_cii.py", line 684, in <listcomp>
    billing_start_dates += [move_line.deferred_start_date for move_line in invoice.invoice_line_ids if move_line.deferred_start_date]
AttributeError: 'account.move.line' object has no attribute 'deferred_start_date'
```

This PR protects the access to these fields checking first if they exist.

Bug introduced in the refactoring in #261572.

TT64359

X-original-commit: 3e318cf847997c657cb635ceb3a26de629b20c1a