[FIX] website_sale_stock: prevent error when opening the shop
Currently, an error occurs when the user opens the shop page.

Steps to Reproduce:

 - Install website_sale_stock.
 - Go to Settings and enable Product Variants.
 - Create a product template of type Goods.
 - Enable Track Inventory.
 - In the Sales tab, disable Sell when Out-of-Stock.
 - In the Attributes & Variants tab, add one attribute with two values and save.
 - Delete all variants using the Variants smart button or from
   Inventory > Products > Product Variants.
 - Go to Website > Shop.

ValueError: Expected singleton: product.product()

After [this commit], when opening the shop page, it calculates the quick
add availability [1] for every product. It checks whether the product is sold
out [2] to determine whether the quick add to cart button should be displayed
or not. Since the product has no variants, it raises the error here [3].
Before 19.0, the quick add availability was calculated if the product had
variants [4].

This commit ensures that if a product has no variants, it is treated as
sold out. As a result, the quick add to cart button is not shown, as in the
previous version.

[this commit]: https://github.com/odoo/odoo/commit/c612b53c95dadc8fb62ad18aa47becca07867d2b

[1]: https://github.com/odoo/odoo/blob/74b762075e38b98b8b03f7fed8ea9e48d76e54f3/addons/website_sale_stock/models/product_template.py#L35-L39

[2]: https://github.com/odoo/odoo/blob/74b762075e38b98b8b03f7fed8ea9e48d76e54f3/addons/website_sale_stock/models/product_template.py#L33

[3]: https://github.com/odoo/odoo/blob/74b762075e38b98b8b03f7fed8ea9e48d76e54f3/addons/website_sale_stock/models/product_product.py#L41

[4]: https://github.com/odoo/odoo/blob/18d9baa690d6b103fbf8dbe875b3e00b056dd873/addons/website_sale/views/templates.xml#L400-L403

sentry-7287364112

closes odoo/odoo#250373

Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>