[FIX] _monkeypatches: explicitly import lxml.html.clean
In lxml 5.x, lxml.html.clean is no longer auto-loaded when importing
lxml.html. So when Odoo 19.0 runs on lxml 5.x it crashes at startup:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/19.0/odoo-bin", line 3, in <module>
    import odoo.cli
  File "/home/odoo/src/odoo/19.0/odoo/cli/__init__.py", line 2, in <module>
    from .command import Command, main  # noqa: F401
  File "/home/odoo/src/odoo/19.0/odoo/cli/command.py", line 8, in <module>
    import odoo.init  # import first for core setup
  File "/home/odoo/src/odoo/19.0/odoo/init.py", line 28, in <module>
    from .tools.gc import gc_set_timing
  File "/home/odoo/src/odoo/19.0/odoo/tools/__init__.py", line 11, in <module>
    from .i18n import format_list, py_to_js_locale
  File "/home/odoo/src/odoo/19.0/odoo/tools/i18n.py", line 8, in <module>
    from odoo.tools.misc import babel_locale_parse, get_lang
  File "/home/odoo/src/odoo/19.0/odoo/tools/misc.py", line 40, in <module>
    from lxml import etree, objectify
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/odoo/src/odoo/19.0/odoo/_monkeypatches/__init__.py", line 45, in exec_module
    patch_module(module.__name__)
  File "/home/odoo/src/odoo/19.0/odoo/_monkeypatches/__init__.py", line 67, in patch_module
    module.patch_module()
  File "/home/odoo/src/odoo/19.0/odoo/_monkeypatches/lxml.py", line 14, in patch_module
    lxml.html.clean._find_image_dataurls = re.compile(r'data:image/(.+?);base64,').findall
AttributeError: module 'lxml.html' has no attribute 'clean'
```

The version guard (< 5.2.0) ensures lxml.html.clean is always
available when the patch is applied.

See recently fixed: https://github.com/odoo/odoo/pull/264277

opw-6235175
upg-4291030