[FIX] stock: get weight of destination package
To reproduce the issue:
(Need delivery)
1. In Settings, enable "Packages"
2. Create a product P:
    - Type: Consumable
    - Weight: 1kg
3. Create and confirm a SO with 1 x P
4. Open the related Delivery Order
5. Put in pack
5. Open the detailed operations of P
6. Edit the destination package

Error: on the package form, the computed weight is 0kg, it should be 1kg

We should provide the `picking_id` in the context so that the compute
method can do its job:
https://github.com/odoo/odoo/blob/5a8690b35a2fa9c5ed81d858ac0d170beaabaaf9/addons/delivery/models/stock_picking.py#L14-L18

OPW-2972868