[FIX] website: prevent deleting fields used in website forms
The system crashes when a user tries to edit a website form field and
that field has already been deleted from the model.

Steps to produce:
- Install the 'website' module.
- Create a new custom field on a model(for example, a field on the
  `mail.mail` model).
- Website > edit > add Form widget to a page, and configure it to use
  the 'mail.mail' model.
- Add the newly created custom field to the form and save the page.
- Now, delete the custom field which is created previously.
- Return to the website page > edit > mark the deleted field as
  required, and attempt to save the changes.

Error:
ValueError: Unable to whitelist field(s) [''] for model 'mail.mail'.

Root cause:
- At [1], we can see that in the current version, it only logs an error
  using the logger but in later versions it raises a ValueError instead.

Solution:
- This fix prevents a field from being deleted if it is actively used in
  any website form.
- It adds a validation check that blocks the deletion and raises
  an error, forcing the user to remove the field from the form first.

[1]: https://github.com/odoo/odoo/blob/d4f424d731fa93ccd232d0def0a7612997345ef7/addons/website/models/website_form.py#L123-L126

sentry-5689731444

X-original-commit: c0a827519844ec43537e4487f6abe358bb82ba9a