FIX report generation when called from an action
The adjusted line somehow caused confusion in the old/new api briding code
because the read() from ir.actions.report.xml was called old_api style, with
a recordset as 'ids' parameter.

This bug is triggered with aeroo_reports installed

Traceback (most recent call last):
  File "/opt/odoo/8.0/odoo/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/web/controllers/main.py", line 1593, in index
    file_name = reports.read(res_id[0], ['name'], context)['name']
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/addons-extra/report_aeroo/report_xml.py", line 458, in read
    res = super(report_xml, self).read(cr, user, ids, fields, context)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 3145, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 3180, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 3312, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/8.0/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'ir.actions.report.xml'