[FIX] mrp: allow access BoM Overview consumable product
Steps to reproduce the bug:
- Create a consumable product:
    - Create a BoM

- Attempt to access the BoM overview

Problem:
An error is triggered:
"Caused by: TypeError: value.toFixed is not a function"

This error occurs when attempting to format the float value of the
available quantity for a consumable product, where the function is
called with `value: False`:

https://github.com/odoo/odoo/blob/054ca0a19aaf297f420a1b478b93ae26f1b943b8/addons/web/static/src/core/utils/numbers.js#L192

opw-3622251

closes odoo/odoo#144988

Signed-off-by: William Henrotin (whe) <whe@odoo.com>