[FIX] web_editor: raise NotFound instead of of ValueError for unsupported file
Currently a ValueError occurs when users access URLs like
'/web_editor/shape/image/jpeg'.

Error: `ValueError: Unsupported file: image/static/shapes/jpeg`

This commit will show page `NotFound` instead of an error.

sentry-6073086305