[FIX] hr: traceback when confirming PO
Have stock,purchase,timesheet_grid,hr installed
Uninstall module hr_org_chart
Set user to have 'User: all documents' rights for Timesheets
With the user, confirm a PO triggering a delivery

Traceback will raise
AttributeError: 'hr.employee' object has no attribute 'subordinate_ids'

This occurs because the field subordinate_ids is only defined in
hr_org_chart which has no connection with timesheet_grid

opw-3837639