[FIX] sale_stock: use correct rounding value for comparing product qty
Versions
--------
- 16.0+

Steps (saas-17.4+)
-----
1. Configure UoM decimal accuracy to be 0 digits;
2. create, confirm a SO;
3. create a downpayment invoice;
4. go back to the SO;
5. modify the product line's price.

Issue
-----
> AssertionError: precision_rounding must be positive, got 0.

Cause
-----
In saas-17.4, an extra check was added to the float utils to prevent `0`
from being used as a `precision_rounding` value.

The result of `precision_get` returns a `precision_digits` value, and is
being passed to `float_compare` as a back-up `precision_rounding` value
in case a line doesn't have a `product_uom.rounding` value.

Solution
--------
Convert the `precision_digits` value to a `precision_rounding` value, so
the floats get compared with the intended precision.

The `get_precision` value returned by `decimal.precision` is an integer
like 2 or 0, denoting the number of decimals to round to. By using it
as a negative exponent to 10, we get the corresponding rounding value,
e.g. `10 ** -2 == 0.01` & `10 ** -0 == 1.0`.

opw-4566621