[FIX] website_links: prevent error while adding old code in link tracker
Currently, an error will occur when the user adds an old code in
the edit link tracker.

Steps to produce:
- Install Link Tracker (website_links) and open website
- Click on Promote > Link Tracker
- Fill Link Tracker form and click 'Get tracked link'
- Edit code of your link by clicking the pencil icon > click ok
- again edit it and put old value > Click Ok >>> Error occurs

Error: `AttributeError: 'int' object has no attribute 'read'`

This error will occur because code [1] is used as the new_code.read()
try to call read() int object because 'search_count' returns count
of record, not an record set.

This commit will fix the above issue by using search instead of search_count
and also improve the code by creating the `_search_link_tracker_code` method,
which returns a search result of 'link.tracker.code' as per the passed domain.

[1] - https://github.com/odoo/odoo/blob/903b2674305fedc25cf7e2a02a9dd9a6c307af35/addons/website_links/controller/main.py#L24

sentry-5708922107