[FIX] purchase: fix assertionerror when 'Order Deadline' is removed
AssertionError: convert amount from unknown date
The problem occurred when removing the default value of 'Order Deadline' and
selecting a product before saving the record.

After applying this commit will fix this issue.

sentry-4175826548

X-original-commit: 0314edf028acf7365804028f0f3ef6123b6ae321