[FIX] hr: prevent error on loading scenario data
The system crash with error when user tries to load sample data of employees.

Steps to produce:-
- Install the Attendances module without demo data.
- Navigate to Employees > Departments and delete the Administrative department.
- Navigate to Employees > Configuration > Employment Types > delete all records.
- Go to Attendances > Load Demo.
- Observe the error.

Error:-
```
ValueError: External ID not found in the system: hr.contract_type_permanent
ValueError: External ID not found in the system: hr.dep_administration
```
Cause:
- The error occurs because the user deleted the records, and then try to load
  data, this causes the corresponding external ID to be missing from the system.

Solution:
- This commit resolves the error by providing a False value for the field if the
  referenced xmlid is missing from the database.

sentry-6856979884