[FIX] mrp: fix singleton error while multiple moves in 'move_finished_ids'
ValueError: Expected singleton: stock.move(32, 33)

This error occurs when we get the multiple lines of the same products in
'finish_moves' and after that when we try to mark as done at that time this
error occurs.

applying these changes will resolve this issue.

sentry-4217897073

X-original-commit: 686300babdecfd98ca93327364da3a0228d6d665