[FIX] maintenance: avoid traceback when stock module is not installed
**Steps to reproduce the bug:**
- Create a new database and install only the Maintenance app.
- Go to Equipment and create a new one.
- Navigate to the product information.
- Set a "Serial Number"

Problem:
A traceback is triggered when we try to compute the field display_name
using `self.name + self.serial_no`, but `self.name`` is not yet set
and is therefore False:

```
record.display_name = record.name + '/' + record.serial_no
                      ~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
```

opw-4261222

closes odoo/odoo#184513

X-original-commit: 3d640534887d5e0954cc9eb2c8588eda58d98bf7
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>