[FIX] website_sale: prevent error when changing the delivery address
Currently, an error occurs when the user changing the delivery address in
the website.

Steps to reproduce:
- Install the website_sale module and enable the Demo payment provider.
- Go to Website > Shop > Add a product to Cart > View cart > Checkout.
- Ensure there are at least two different delivery addresses > Confirm > Pay now.
- Quickly press the browser’s back button twice.
- Select a different delivery address.

Error:
ValueError: Expected singleton: sale.order()

Root Cause:
At [1], the code calls order.ensure_one(). When the cart (sale.order) is empty,
leads to an error.

Fix:
This commit prevents errors by returning early with an empty dict when
order_sudo is not set at [2], and raises a UserError to improve error
message clarity.

[1]:
https://github.com/odoo/odoo/blob/88c9a45ee1ff8dde871865723c3387c059af8289/addons/delivery/models/delivery_carrier.py#L157

[2]:
https://github.com/odoo/odoo/blob/88c9a45ee1ff8dde871865723c3387c059af8289/addons/website_sale/controllers/delivery.py#L21

sentry-6869972801