[FIX] web: prevent error when user clicks the call icon while creating a record
Currently an exception was generated when the user tries to save
the new employee record after clicking on call icon.

Steps to reproduce:
1) Install HR module
2) Create a new employee record by giving employee name
3) Click on the call icon of work phone
4) Now tries to save the new employee record

Error: `KeyError:  name`

This issue occurs because, while clicking the call widget, it creates the record
but does not update it in the browser.

As a result, when the user tries to save manually, It again  creates the record
with an empty vals_list.

So it will leads to the above traceback from the below lines

https://github.com/odoo/odoo/blob/2d64d94487d24278dc3c6615343a793e1ec94daf/addons/hr/models/hr_employee.py#L386

This fix resolves the issue by ensuring that clicking the call icon before saving
retains the user input. Additionally, I have added a test to verify this behavior.

sentry-6234873849

X-original-commit: 8f057d2b837f2d20032d23826e3e2a9d409b2a8c