[FIX] stock: allow scrapping a lot without on-hand quantity
Steps to reproduce:

- Enable "Lots & Serial Numbers" in the Inventory settings
- Create a storable product tracked by lots
- Create a lot for that product and leave it without any quantity
- Open the lot form > cog menu > Scrap
> ValueError: Expected singleton: stock.location()

Cause of the issue:

A lot is only given a `location_id` when all its positive quants lay in
a single location, so a lot with no quant at all has none:
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/addons/stock/models/stock_lot.py#L169-L172
The `action_scrap` nevertheless always forwards that value to the scrap
move, so the form is opened with `default_location_id` set to `False`:
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/addons/stock/models/stock_lot.py#L415-L426

Now, the issue is that the `_onchange_lot_ids` of the new stock move
then evaluates the reservation of a move whose source location is still
empty which raises the traceback because of a `self.ensure_one` required
on the location to determine if the move `should_bypass_reservation`:
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/addons/stock/models/stock_move.py#L1515
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/addons/stock/models/stock_move.py#L1989-L1992
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/addons/stock/models/stock_location.py#L414-L416

Note that if the default key was not present, the traceback would not be
triggered and the scrap would be performed from the
`default_stock_location` of the company:
https://github.com/odoo/odoo/blob/4c4219a7d9d51f703b15e83ab755faf1f2c8a71d/addons/stock/models/res_company.py#L21-L22

Indeed the issue is that the `default_get` looks the context key up by
*membership*, so that a falsy `default_location_id` is still returned as
a default value for the field if provided:
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/odoo/orm/models.py#L1313-L1317
And therefore will not be computed in the first onchange:
https://github.com/odoo/odoo/blob/8b8852f1c3ae5b78a4a3e99c99eacab83f0be5c9/addons/web/models/models.py#L1974-L1988

Note:

The `stock.lot.action_scrap`, and this `default_location_id` line with
it, were introduced by 1c7d80a10b5d, which replaced the `stock.scrap`
 model by scrap `stock.move` records. That commit is only present from
saas-19.2 onwards, so earlier versions are not affected.

opw-6441937

closes odoo/odoo#282573

X-original-commit: 837a94ca9ec5cc767695fef348d85a0812a2fea3
Signed-off-by: Steve Van Essche <svs@odoo.com>
Signed-off-by: Lancelot Semal (lase) <lase@odoo.com>