Bad return third param when no partners
The test `test_aged_report` in the file test_reconciliation.py fail because he expect a dict and call `get` on the list

```
Traceback (most recent call last):
odoo.addons.account.tests.test_reconciliation: `   File "/odoo/addons/account/tests/test_reconciliation.py", line 805, in test_aged_report
odoo.addons.account.tests.test_reconciliation: `     self.assertFalse(amls.get(partner.id, False), 'The aged receivable should not have amls either')
odoo.addons.account.tests.test_reconciliation: ` AttributeError: 'list' object has no attribute 'get'
```