[FIX] account: statement in bank reconciliation in list view
When user tries to add statement in bank reconciliation in list view,
a traceback will appear.

Steps to reproduce the issue:
- Go to Accounting > Dashboard > Bank
- Switch to list view of bank reconciliation.
- Create statement in any record of bank reconciliation > 'Create and edit'.

Error: A traceback appears:
'TypeError: object of type NoneType has no len()'

https://github.com/odoo/odoo/blob/e83b2de36761a093799464e289e81d4787296ff9/addons/account/models/account_bank_statement.py#L283
Here, when 'active_ids' is None and it tries to calculate len(active_ids),
So it will lead to above traceback.

sentry-4305119691