[FIX] base, tools: prevent errors when creating an inherited view
Currently, an error occurs when a user creates an inherited view.

Steps to Reproduce:
  - Go to Settings > Technical > User Interface > Views.
 - Create a new view by entering a name and selecting any inherited view.
 - In the Architecture, enter the below code:
```
    <xpath position="replace">
        <field name="name"/>
    </xpath>
```
 - Now save the view.

TypeError: Argument must be bytes or unicode, got 'NoneType'

Cause:

As we can see, when the user enters an xpath without the expr attribute,
and when it goes to find the inherited node [1]. Since the expr is missing,
its value becomes None [2]. Passing this None as an argument [3] causes
the error.

This commit ensures that when user creates or edits view with an xpath
that has a missing expr attribute, a ValidationError is raised [4], similar to
the behavior for an invalid xpath.

[1]: https://github.com/odoo/odoo/blob/4876a54e8cfb3a115b5423db102fc2b7a40b196a/odoo/tools/template_inheritance.py#L145

[2]: https://github.com/odoo/odoo/blob/4876a54e8cfb3a115b5423db102fc2b7a40b196a/odoo/tools/template_inheritance.py#L76

[3]: https://github.com/odoo/odoo/blob/4876a54e8cfb3a115b5423db102fc2b7a40b196a/odoo/tools/template_inheritance.py#L78

[4]: https://github.com/odoo/odoo/blob/4876a54e8cfb3a115b5423db102fc2b7a40b196a/odoo/addons/base/models/ir_ui_view.py#L377-L384

sentry-7161414430

X-original-commit: 0936f8d065ff40faafa43b601b37bbc504e8ad24