[FIX] project: Allows users to view sub-tasks in kanban mobile view
Example of steps:
- Install `industry_fsm`
- Create a task with a subtask
- Enable mobile view with devtools
- Open a task
- Navigate to sub-tasks tab
- Traceback

```
TypeError: undefined is not an object (evaluating 'ctx['record'].parent_id.raw_value')
```

parent_id was missing from "view_task_kanban"

opw-5981990

closes odoo/odoo#253771

X-original-commit: 2e1296b0604d4b21616fe52e741e54655e83055b
Signed-off-by: Hubert Van De Walle <huvw@odoo.com>
Signed-off-by: Achraf Ben Azzouz (abz) <abz@odoo.com>