[FIX] stock: fix for TypeError: value.toFixed is not a function on BomOverviewTable caused by False value on quantity
closes odoo/odoo#145449

Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>