[FIX] AttributeError: 'NoneType' object has no attribute '_name'
This commit is to prevent "AttributeError: 'NoneType' object has no attribute '_name'"
If we access a content added to our webpage is missing from filestore (The content url be like /web/image/aa82/some-image.jpeg) this will happen.