Cherry pick of 69a6c4d65f2997e4298dd52f3e9b5811fdd7e30e failed
stdout:

stderr:
11:58:53.314282 git.c:344               trace: built-in: git cherry-pick 69a6c4d65f2997e4298dd52f3e9b5811fdd7e30e
error: could not apply 69a6c4d65f2... [ADD] l10n_gcc_invoice: arabic/english report for GCC countries
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: