[FIX] mail: preventing typeerror on clicking unfollow
Currently a `TypeError` is arising when user clicks 'Unfollow'.

Steps to reproduce this error:
- Install 'Payroll'
- Go to Payslips > All payslips
- Create a new (or duplicate) playslip.
- Compute Sheet
- Create Draft Entry
- Create Payment report
- Run the "Payroll:Generate pdfs"CRON (model._cron_generate_pdf() on hr.payslip)
- Click the 'Unfollow' at the bottom of the payslip.
- The error appears in the log.

Error: `TypeError: MailController.mail_action_unfollow() missing 4 required
positional arguments: 'model', 'res_id', 'pid', and 'token'`

This commit solves the above issue by changing the missing fields to 'False'.
sentry-4952598215