[FIX] base: upgrade lxml to 5.1.0 for MacOS
The current version of lxml (4.9.2) is breaking Odoo on MacOS.
This commit upgrades lxml to 5.1.0 which prevents the issue.

With the current version, the following error is raised whenever we try
to install any module that depends on Mail:
lxml.etree.XMLSyntaxError: Char 0x0 out of allowed range

This error is due to an emoji that got introduced here:
97ce0844ca0c3d531a7a2e2e47a867d89835b24e