[FIX] web: prevent crash when using invalid args in name_search
The system crashes with an error when attempting to scan a barcode. because
`name_search` expects `domain` and it gives `args`.

Error:-
`TypeError: ProductProduct.name_search() got an unexpected keyword argument
'args'`

Sentry - 6388425767

closes odoo/odoo#211759

X-original-commit: a1b79d66ce9b37b9752261d5eadce0d2c7d976e0
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Krishna Arvindkumar Patel (krip) <krip@odoo.com>