[FIX] mrp: prevent typeerror when an mo is overviewed
Currently a `TypeError` appears when the user opens 'Overview' of an
'Manufacturing Order'.

Error: TypeError: can't compare datetime.datetime to datetime.date

The error occurs because when 'Overview' is opened of an MO, a comparison
is made between `Datetime & Date`,i.e `mo_planned_start` and `receipt['date'],`
which raises the above error.

This commit resolves the issue by keeping date format same of both the fields.

sentry-6250719075