Cherry pick of 9ae2a3330d11f6301dfaceea53baed4fca7b3e69 failed
stdout:

stderr:
error: could not apply 9ae2a3330d1... [FIX] l10n_be_intrastat: fix forward port error
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'