[FIX] account_edi_ubl_cii: handle empty Norwegian VAT
Steps to reproduce:
- Install the `sale_management` module.
- Create a new customer and set the country to `Norway`.
- Go to Sales and create a new quotation for the newly created customer.
- Click the `Print` button.

Error:
AttributeError: 'bool' object has no attribute 'startswith'

Root Cause:
At [1], `startswith()` is called on VAT even when the customer's
TIN (VAT) is not set, causing an error.

Fix:
This commit prevents the error and allows users to print the
report successfully.

[1]:
https://github.com/odoo/odoo/blob/5c2d5daa13cf582c40bdb44e245e1359d7c410f0/addons/account_edi_ubl_cii/models/account_edi_ubl.py#L924-L928

opw-6469642

X-original-commit: 50ddfa124453295940adc75161fc7591c71b4fb5