[FIX] hr_recruitment: fix recruitment sample data
Currently an error occurs when user tries to load scenario data for recruitment.

Steps to replicate:
- Install `hr_recruitment`.
- Open Recruitment and Click `Load sample Data`.

Error:
```
ValueError: Invalid field 'user_id' in 'hr.applicant'

odoo.tools.convert.ParseError: while parsing /home/odoo/odoo19/community/addons/hr_recruitment/data/scenarios/hr_recruitment_scenario.xml:72, somewhere inside
<record id='scenario_applicant_macm_helen' model='hr.applicant'>
            <field name=email_from>helenlee@exampe.email.com</field>
            <field name=partner_name>Helen Lee</field>...

Cause:
- The field `user_id` was changed to `recruiter_id` from the [PR].
- But the scenario data still had the field `user_id`, this caused the error.

Solution:
- Replace user_id in the sample data with recruiter_id and use an employee as a
  value instead of a user. One additional detail is that since this is sample
  data that can potentially be applied on a db that already has some records.
  There is a case where creating an employee in the sample file and linking them
  to the admin user, but that can cause an exception if the admin user is
  already linked to an employee. To circumvent this, we first check if there is
  an employee linked to the admin user. If not we create a new one and make the
  sample data use whichever employee that is linked to the admin user.

Backport for the PR: https://github.com/odoo/odoo/pull/246362

[PR]: https://github.com/odoo/odoo/pull/229665

sentry-7324422905