[FIX] point_of_sale, pos_hr: handle cash moves without partner
With pos_hr enabled, the cash in/out popup uses the cashier's
`work_contact_id` as partner for the `account.bank.statement.line`.
When that partner is archived or not part of the limited partner
loading, the relation cannot be resolved in the frontend and the
statement line is created with `partner_id = False`.

Deleting such a cash move then crashes in `delete_cash_in_out`:

    File ".../point_of_sale/models/pos_session.py", line 1877, in delete_cash_in_out
        action = cashier_name + ': ' + str(amount)
    TypeError: unsupported operand type(s) for +: 'bool' and 'str'

Steps to reproduce:
- Enable "Multi Employees per Session" (pos_hr) on a PoS config
- Archive the work contact of an employee, or make sure it is not
  included in the limited partner loading
- Open a session, log in as that employee and register a cash in/out
- As a manager, delete the cash move from the cash move list
=> Traceback, the cash move cannot be deleted

opw-6389830

closes odoo/odoo#276598

Signed-off-by: Stéphane Vanmeerhaeghe (stva) <stva@odoo.com>