[FIX] sale_stock: prevent error on validating stock picking
The error occurs when a SO line is deleted, and a return is processed for the
associated delivery using a different product, after which the return is
validated.

Steps to reproduce:
- Install the 'sale_management' and 'stock' modules
- Create & confirm an SO for one product
- Now cancel that SO and remove that product
- In Stock > Deliveries > Open that delivery(Cancelled)
- Click on the Return button and add any product > Return > Validate

Traceback:
ValueError: max() iterable argument is empty

At [1], a ValueError is raised because there are no SO lines, resulting in an
empty sequence is being passed to the max() function.

[1]- https://github.com/odoo/odoo/blob/deab3cafc8b3cd79dcc52fddd9511a38a7e77afa/addons/sale_stock/models/stock.py#L68

sentry-6709665025