[FIX] pos_viva_wallet: prevent error when sending walled response bus notification
With commit [1], we removed the method '_get_bus_channel_name', but at
line [2], it's still referenced, which causes an error.

AttributeError:
'pos.session' object has no attribute '_get_bus_channel_name'

This commit will fix the issue by using '_notify' for calling the notification
bus.

[1]-https://github.com/odoo/odoo/commit/b56644e24e84164f4d3a77fdede8333c08167cde
[2]-https://github.com/odoo/odoo/blob/5633d590decc6e8989c0f454a355e965f072f967/addons/pos_viva_wallet/models/pos_payment_method.py#L133

sentry-5562979975

closes odoo/odoo#172437

X-original-commit: 7c78dd49fb16b70f9df52510cee9a6e21b9678f5
Signed-off-by: Quentin Lejeune (qle) <qle@odoo.com>