[FIX] l10n_vn_edi_viettel_pos: prevent error when opening the POS register
Currently, an error occurs when user opening the POS register.

Steps to Reproduce:
 - Install l10n_vn_edi_viettel_pos with demo data.
 - Switch to the VN company.
 - Open Point of Sale and create any POS configuration.
 - Go to Point of Sale > Orders > Customers.
 - Remove the "Customer Invoices" filter, search for "Walk-in Customer",
   and delete it.
 - Go back to the Point of Sale dashboard and click "Open Register" on the
   POS configuration.

AttributeError: 'NoneType' object has no attribute 'id'

This error occurs when the user opens the POS config register. It loads
the default partner in the POS session from [1] and prepares the POS
data domain [2] if the default customer exists. However, if the default
customer does not exist, it attempts to access the `id` of `None`,
which raises the error.

This commit ensure the Walk-in Customer partner cannot be deleted as it
is required by the Vietnam point of sale.

[1]: https://github.com/odoo/odoo/blob/dd75e71513e5fb19139de8cfd2712dd4e5af81d3/addons/l10n_vn_edi_viettel_pos/models/pos_session.py#L15-L16

[2]: https://github.com/odoo/odoo/blob/dd75e71513e5fb19139de8cfd2712dd4e5af81d3/addons/l10n_vn_edi_viettel_pos/models/res_partner.py#L14-L16