[FIX] mail sanitize: allow BUTTON with truthy sanitize_form
Scenario:

- in 18.0, insert a slideshow in sanitize_form=True (the default) html
  field, for example an appointment description
- reload the page

Result: the navigation button are removed, and this traceback error
happens when showing the page (which prevent editing and remove it):

TypeError: Cannot read properties of undefined (reading 'style')
  at Class.start
  (/website/static/src/snippets/s_image_gallery/000.js:125)

Why:

Since 3deb8050831c69ca1e32039622b322ffa38cc497 18.0, the slideshow uses
BUTTON tags instead of LI as does bootstrap 5.0 for such case so the
issue could also happen with bootstrap example codes.

The "sanitize_form" field options enable the lxml cleaner "forms" option
which removes FORM tags, and kill BUTTON, INPUT, SELECT, TEXTAREA tags.

So the buttons used for navigation are removed which causes an issue
with the code not expecting it.

Solution:

This commit allows BUTTON tag even if sanitize_form is true.

Comparing with DOMPurify behavior (that allows form but has a whitelist
of attributes and for example prevent autofocus by intent) this could
lead to a security issue if the field is both sanitize_form=True and
sanitize_attributes=False.

To prevent this, when we allow the BUTTON, we force the removal of
attributes not in the whitelist.

note: to completely fix the issue, also whitelist data-bs-* attributes
that are necessary for bootstrap slideshows.

opw-4844700