[FIX] website: unskip test_03_snippets_all_drag_and_drop
Since PR odoo/odoo#214984, the “test_03_snippets_all_drag_and_drop” test fails
because the video snippet opens the media dialog and the test does
not handle it.

Solution: as with image snippets, we will ignore them in this test.
Error: https://runbot.odoo.com/odoo/runbot.build.error/231594
X-original-commit: 0fc107a3cca85e107302d108ee7a85abdc376412