[FIX] base: allow automated actions to add m2m values
Versions
--------
- 16.0

Commit 3871ae2c6c45 fixed this for 17.0+

Steps
-----
1. Create an automated action on a Model with tags (e.g. Contact);
2. set trigger to On Creation;
3. in data to write, have evaluation type to Value;
4. fill in the value (e.g. Services);
5. create a record that would trigger the automation.

Issue
-----
> ValueError: Wrong value for res.partner.category_id: Services

Cause
-----
Automated actions weren't able to handle writing by reference for m2m
fields. Commit 09a6df204f2a disallowed creating an automation like this
by throwing an error.

Writing by reference is actually possible with a slight modification to
the `_set_resource_ref` method. Writing by value on the other hand
doesn't make sense.

Solution
--------
1. Allow writing by reference for m2m fields, and add logic to link the
   correct record id on evaluation.
2. Disallow writing by value for m2m fields.

opw-4054461