[FIX] pos_self_order: allow opening mobile menu when country was not set
This issue arises when a user removes the `country` from their company and then
attempts to open the `mobile menu` for the restaurant using the POS module.

Steps to produce :
- Install `pos_self_order` module.
- Navigate to Settings > User & Companies > Companies
- Open your company > Remove the country of your company.
- Now go to POS module open the `mobile menu` for the restaurant.
- Error will be generated.

Error: IndexError: list index out of range

This issue occurs because here
https://github.com/odoo/odoo/blob/78cbdc604ec6ef48ef291d354126d7b171eaec64/addons/pos_self_order/models/pos_config.py#L335
when try to access the `country_id` it will not get that because country
was not selected in the company and also the country was not a required field.

sentry-4769344261