[FIX] fleet: prevent adding character in vehicle  model year
Currently an error occurs when a user adds a character in the
`Model Year` of fleet vehicles.

error: `ValueError: invalid literal for int() with base 10: '2016/2017'`

With the recently code change with [1], a 'char' widget was added in the field
'model_year' so it allows entering a character instead of an of an integer.

This commit removes the 'char' widget from the mode l'model_year'
so the user will allow entering only numbers.

[1] - https://github.com/odoo/odoo/commit/67d8f55a279d8ea34b747e06b84537815a74368a

sentry-5667064353

closes odoo/odoo#178312

X-original-commit: fff7b0389412e04d16d1c550af4e7aaa7c0a0cd1
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>