[FIX] l10n_in_edi : Shows JSON content on button click
Description of the issue this PR addresses:
This issue was introduced after the refactoring of binary fields
(https://github.com/odoo/odoo/pull/244421), where Binary fields now
expect proper binary data and treat string values as base64.

The JSON data was passed as a string to a binary field.
After the BinaryValue change, this string was treated as base64,
which caused a decoding error.

Before this Commit:
Clicking the JSON button resulted in an error:
binascii.Error: Only base64 data is allowed
Due to this, the JSON data could not be viewed.

After this Commit:
JSON data is now converted into the correct binary format using
Odoo's binary handling (odoo.tools.Binary) and it displays correctly.

Related Commit: https://github.com/odoo/odoo/commit/41fe2ebdb9cc37341362d7af829c087a5f72f9f1#diff-d3b35dffff8313ee07a08bceb336f03d6130bf001e3b0daa32b098cefcf95c3b
Full Error Details: https://pastebin.com/v12sD2vf

closes odoo/odoo#272138

X-original-commit: 87e44f053cedbeffbf686015f4d46d161f4b8dd6
Signed-off-by: Josse Colpaert (jco) <jco@odoo.com>