[FIX] stock: prevent error when NewIds are passed
Currently an error occurs when user tries to open reception report through
web studio.

Steps to replicate:
- Install stock, web_studio with demo.
- Open receipts and turn on studio mode.
- Go to reports and try to open `Reception Report`.

Error:
```
psycopg2.ProgrammingError: can't adapt type 'NewId'
```

Cause:
- Error occurs after this [PR] that prevents passing of falsy ids to orm.
- As a result the [line] passes `api.NewId()` that is received as `docids` in
  the function `_get_docs()` performs search using the `NewId` [here] which
  causes this error to occur.
- In the previous version the id passed was passed a static list `[0]` and
  then changed to `api.NewId()` which works perfectly fine with `browse()` but
  with any other operation that fires direct queries like `search()` or
  `_read_group()` it will cause this error to occur.

Solution:
- Removed NewIds from docids before the search.

[PR]: https://github.com/odoo/enterprise/pull/95117/changes#diff-cf8f46a54f86279b4d773f0d39b23d22f046eb6d33a39c851f2a86dcd2b5b202R645

[line]: https://github.com/odoo/enterprise/blob/431d1b513f26188f693abd949f78a893514205f0/web_studio/controllers/report.py#L649

[here]: https://github.com/odoo/odoo/blob/3263a7f54948d57f13176cf0416b1419150e9d87/addons/stock/report/report_stock_reception.py#L190

sentry-7236339558