[FIX] purchase: Fixed valueError for uom
Some purchase lines are of type note or section.
For those lines, the UoM is null,
So when the system tries to compute the unit price
Using the product UoM, we get a ValueError
due to the missing UoM.
To prevent this, we need to add a condition
in the compute method so that it only processes
lines where display_type is False.

```
  File "/home/odoo/src/odoo/19.0/addons/purchase/models/purchase_order_line.py", line 160, in _compute_price_unit_product_uom
    line.price_unit_product_uom = line.product_uom_id._compute_price(line.price_unit, line.product_id.uom_id)
   File "/home/odoo/src/odoo/19.0/addons/uom/models/uom_uom.py", line 195, in _compute_price
    self.ensure_one()
   File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 5934, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
 ValueError: Expected singleton: uom.uom()

```

X-original-commit: 6a5e070c8de6bb95c6ce6830c48a35c0c9920446