[FIX] website: prevent adding invalid domains to the website
Currently an error is generated when the user tries to open the
website after adding the invalid domain like `https://.com`

Steps to produce an error:
- Go to website settings and set the domain as `https://.com`
- Open the website page >>> Error occurs

Error: `UnicodeError: label empty or too long`

This error occurs during IDNA encoding/decoding because the domain contains
an empty second-level label, as seen in the above-mentioned domain.

The error is triggered in the `_idna_url` method during IDNA encoding
when the extracted base domain includes an empty second-level domain
in the above-mentioned URL.

This commit fixes the above issue by handling the existing `ValueError`
(`since UnicodeError is a subclass of ValueError`) in the constraint,
where a `ValidationError is raised when an error occurs during execution
of the `_idna_url` method.

sentry-7265749008