[FIX] base: fix traceback when user removes all devices in preferences
Currently, a traceback occurs when the user tries to `log out from all devices`.

To reproduce this issue:

1) Open the `Preferences` from the profile
2) Click `Log out from all devices` from the Account Security page
3) Give the current password and click `Log out from all devices`

Error:- "AttributeError: 'bool' object has no attribute 'strip'"

When the user clicks on the `Log out from all devices`, the `revoke_all_devices`
method triggers in which the `_check_identity` method is triggered.

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L2000-L2002

But here in the `_check_identity()` current password is set to False.
This leads to a traceback from the `_change_password` method.

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L1982-L1988

https://github.com/odoo/odoo/blob/a7db2d8f1336035f6e45d04da7c2ebec5f3d9dba/odoo/addons/base/models/res_users.py#L977-L978

Note:-
I don't know the scope of setting the password as False,
So instead of removing that line, I passed the current password as a variable.

sentry-5867375557

X-original-commit: 36d63a7ec925879e43d45a864ca7f0ac2b314ce2