[FIX] hr_work_entry_holidays: fix test case error
Steps to reproduce:
1. Install Payroll and Time Off modules.

Issue -
A ValueError is raised:
`raise ValueError('Wrong value for %s: %r' % (self, value))
ValueError: Wrong value for hr.contract.work_entry_source: 'attendance'`

Cause-:

The field work_entry_source is a selection field. The value 'attendance' is
added by the hr_work_entry_contract_attendance module, but it is being used in
 hr_work_entry_holidays.
If hr_work_entry_holidays is install without `hr_work_entry_contract_attendance`
 the value 'attendance' is invalid, causing the error.

Solution:
The `test_leave_validation_with_multiple_work_entry_types` test case was
originally written for this issue,
PR- https://github.com/odoo/odoo/pull/224254
but it is not important to use this field.
So, remove the use of this value in the test case, since it is not mandatory to
reproduce the issue.