[FIX] account: fix inexistent attachment_ids when sending invoice
- Install Invoicing
- Create an invoice
- Post invoice and send it
An AttributeError is raised:
"AttributeError: 'account.move' object has no attribute 'attachment_ids'"

"attachment_ids" field is not available on "account.move" in Invoicing.
It is declared in Accounting.

opw-2413574
opw-2413310

closes odoo/odoo#62988

Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>