[FIX] tools: make pdf signature avid crash in 3.10
Before this commit, when signature.py is called in python 3.10, the
following error is observed. ModuleNotFoundError is catched but an
ImportError is raised. In that case, the signature feature is disabled.

File "/home/odoo/src/odoo/saas-18.2/odoo/tools/pdf/signature.py", line 11, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes
ImportError: cannot import name 'PrivateKeyTypes' from 'cryptography.hazmat.primitives.asymmetric.types' (/home/odoo/.local/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/types.py)
2025-02-19 13:38:20,377 288857 INFO test_18.1_18.2 odoo.service.server: Initiating shutdown

X-original-commit: 8150e48db7513ce898adc87459ee33339799b353