[FIX] hr_recruitment_survey: fix TypeError on empty allowed_survey_types
Steps-to-Reproduce
- Install hr_recruitment_survey
- Make a user with no Survey rights but Recruitment Admin.
- From that user go to Recruitment > Configurations > Interview.
- Trying to create record will reproduce this error
```
File "/home/odoo/src/odoo/saas-19.3/addons/hr_recruitment_survey/models/
survey_survey.py", line 19, in _compute_allowed_survey_types
    survey.allowed_survey_types = [*survey.allowed_survey_types, 'recruitment']
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: Value after * must be an iterable, not bool
```

Reason
- Because user may not have survey rights return `[]`
[here] : https://github.com/odoo/odoo/blame/a7f9b44aad071efe401d3caa70d069aaf7e19cc9/addons/survey/models/survey_survey.py#L400
  which gets converted to false by orm
[here] : https://github.com/odoo/odoo/blob/3a4b2a320c1496e97eeb1834862230439da6ea2f/odoo/orm/fields_misc.py#L55-L74

- upg : 4282172
- opw : 6231531