[FIX] website_mail_channel: prevent crash in python3 email lib
`AttributeError: 'tuple' object has no attribute 'startswith'`

When given headers that are tuples. They are expected to be string, as per [1].
The issue was introduced with [2], indeed the code was moved from inside a dict
where `,` was the usual dict separator to outside of a dict where `,` at the end
made them tuples.

To reproduce the issue, run the `test_mail` suite after having
`website_mail_channel` installed.

Issue highlighted as part of task-2178641

[1] https://docs.python.org/3/library/email.policy.html#email.policy.Policy.header_store_parse
[2] cae1c3977ff2777dcb77e4c2a51deb72ee57db22

closes odoo/odoo#43688

X-original-commit: 3bda53a791e25bc710915015e581fd3cdc2bc1ec
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>