[FIX] tools: prevent traceback when uploading corrupted image
When user uploads the corrupted image in product.
a traceback will appear.

Steps to reproduce the issue.
- Create a new product > Upload a corrupted file in the product image
  ex.(https://tinyurl.com/2mazelw3)
- Save

Error: A traceback appears:
'SyntaxError: not a TIFF file (header b'Exif\x00\x00MM' not valid)'

Try-catch is added to catch the syntaxerror when the user tries
to upload the corrupted image.

sentry-5528394249