[FIX] product: always add product name to name_get
In RfQ, when searching for a product, if the latter has several supplier
information (with same vendor and different vendor product names/codes),
only the vendor product name of the last supplier information will be
displayed.

To reproduce the error:
(need purchase)
1. Create a product PR
    - Name: SuperProduct
    - In purchase tab, add two supplier information SI01, SI02
        - SI01:
            - Vendor: Partner PA
            - Vendor Product Name: 'A'
            - Vendor Product Code: 'A'
            - Quantity: 1
            - Price: 10
        - SI02:
            - Vendor: The same (PA)
            - Vendor Product Name: 'B'
            - vendor Product Code: 'B'
            - Quantity: 2
            - Price: 15
2. Create a RfQ
    - Vendor: PA
3. Add a line, and in Product field, enter "super"

Error: in the suggestions list, there is only "[B] B". If the user
clicks on it, the Description field will be defined with the same value
while it actually uses the quantity and the price from SI01. Even worse,
suppose SI02 is expired (it is possible to set an end date), the
suggestions list will still contain "[B] B"

When getting the name:
https://github.com/odoo/odoo/blob/824a6515a528cd2b682c3d3504c0d27ed9427cdb/odoo/models.py#L6432
It calls `name_get()`, which returns the list of all possibilities:
`[(SuperProduct_id, "[A] A"), (SuperProduct_id, "[B] B")]` but it then
converts the list in a dictionary. However, since several tuples have
the same key (SuperProduct_id), it will only keep the last value ("[B]
B"). This fix always adds the product name at the end of `name_get()`
result.

OPW-2465075