Cherry pick of 476978a1530469d7d93678aa5c0131d9b1fa767c failed
stdout:

stderr:
11:07:46.127178 git.c:344               trace: built-in: git cherry-pick 476978a1530469d7d93678aa5c0131d9b1fa767c
error: could not apply 476978a1530... [FIX] website: don't try to convert static url in multilang
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'