[FIX] cloud_storage_azure: allow hyphens in container names
Versions
--------
- saas-17.4+

Steps
-----
1. Create a Azure storage container with a hyphen in its name;
2. connect it to your database;
3. go to a contact;
4. click "Send message";
5. upload an attachment.

Issue
-----
Server Error pop-up.

In the logger, you get:
> TypeError: UserError.__init__() takes 2 positional arguments but 3 were given

Cause
-----
1. The `ValidationError` string is badly formatted.
2. The regex to verify Azure Blob Storage URLs doesn't allow hyphens in
   the container name.

Solution
--------
1. As the `ValidationError` is only shown in the logger, format is as an
   f-string.
2. Update the regex to the constraints imposed by Azure[^1].

opw-4770160

[^1]: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage