[FIX] website_sale: prevent errors when inserting a dynamic product snippet
Currently, an error occurs when a user insert a dynamic product snippet
onto website.

Steps to Reproduce:

 - Install website_sale without demo data.
 - Go to Website > eCommerce > Products > Ribbons.
 - Open any ribbon and set Assign to When New.
 - Go to the website > Edit > drag and drop the Catalog block, and select a
   Dynamic Product block (Generic Product Template (customizable)).

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'bool'

After this [recent commit], when a user drops a dynamic product snippet, the
system attempts to set the ribbon value [1]. If no product records are
available, it falls back to using sample products [2]. These sample products
are virtual records created with model.new() [3] [4] and are not stored in
the database, so they do not have a publish date.
When auto-assigned ribbon with the When New option assign, the system compares
the ribbon's new period with the product's publish date. Since the sample
products do not have a publish date, this comparison raises an error [5].

This commit ensures that the comparison between new period and publish date
is only performed when the product has a valid publish_date.

[recent commit]: https://github.com/odoo/odoo/commit/f427f795c24ee37ee02302642b77bfc314a9ea43

[1]: https://github.com/odoo/odoo/blob/b70330df7dc2017ab592b075c8ad8e048f671d90/addons/website_sale/templates/snippets/product_snippet_template_data.xml#L52-L58

[2]: https://github.com/odoo/odoo/blob/b70330df7dc2017ab592b075c8ad8e048f671d90/addons/website/models/website_snippet_filter.py#L75-L78

[3]: https://github.com/odoo/odoo/blob/b70330df7dc2017ab592b075c8ad8e048f671d90/addons/website/models/website_snippet_filter.py#L214-L215

[4]: https://github.com/odoo/odoo/blob/b70330df7dc2017ab592b075c8ad8e048f671d90/addons/website_sale/models/website_snippet_filter.py#L62-L95

[5]: https://github.com/odoo/odoo/blob/b70330df7dc2017ab592b075c8ad8e048f671d90/addons/website_sale/models/product_ribbon.py#L121-L124

sentry-7528296918

closes odoo/odoo#272972

X-original-commit: 19142e7b396e5474fe075a885670421a352c32dc
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>