[FIX] mail: message related to deleted record doesn't break discuss
Before this commit, when a message notification from inbox or
history has its related record deleted, the user couldn't load
inbox or history.

Steps to reproduce:
- Have mitchell admin receive notification in Odoo
- Install `mail_group`
- Wait a few seconds to receive following user_notification
  from mail group:
```
on My Company News
Hello,
You have messages to moderate, please go for the proceedings.
```
- Go to related record then delete it
- Go back to inbox or history

=> One of them show `An error occurred while fetching messages.`

This happens because the related record is not a `mail.thread`,
but still creates some `mail.message` to send user notifications.

`mail.thread` cascade delete the messages in message list, but
threadless records do not. Because the related record is deleted,
these messages are attempted to be displayed in mailbox, but due
to related record having no `display_name` by non-existing, the
fetch data of inbox/history crashes with:
```
MissingError: Record does not exist or has been deleted
```

This commit fixes the issue by doing its best to show message
even when the related record has been deleted.

opw-4546920

closes odoo/odoo#219798

X-original-commit: 0147d98dcad54f9bb1f344d8dac4363b3143949b
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>