[FIX] bus: prevent contextlib error while serving WebSockets
Currently, when a `PoolError` from `psycopg2.pool` is raised (code ref [1])
during the execution of `retrying()` inside `acquire_cursor()`, Python's
contextlib generates the following server error:

```
RuntimeError: generator didn't stop after throw()
```

This occurs because the exception is suppressed within the generator-based
context manager, causing the generator to continue execution after throw().

This commit fixes the issue by limiting the `suppression/retry` logic to the
cursor acquisition step. It also uses `ExitStack()` to ensure proper management
of the exit callback stack across the `yield`, guaranteeing that resources are
cleaned up correctly even if an exception is raised after the cursor is yielded.

[1]: https://github.com/odoo/odoo/blob/1956c5e3e14086f699e4582a7332577bc2fbf557/odoo/sql_db.py#L648

Sentry-7567409750,7401155298

X-original-commit: c000fb7f4a472fad6cac6a103c6f7fe2a7580494