[FIX] sale_purchase: validate service to purchase
To reproduce the issue: create several products at once (`vals_list`)

Error: it will lead to a `ValueError` ("Expected Singleton")

Python constraints are called on recordset. Therefore, in
`validate_service_to_purchase`, reading `service_to_purchase` on self is
incorrect.