[FIX] mail: no crash on reply in portal chatter
Before this commit, clicking on "Comment" button
in portal chatter to reply to a message leads to
the following crash:

```
TypeError: Cannot read properties of null (reading 'effectiveSelf')
```

This happens because it opens the composer to reply to the
message. Replying to a message should normally use the
composer of thread and rely on `props.messageToReplyTo` from
the `useMessageToReplyTo` hook, but portal chatter instead makes
a composer linked to the message.

The problem is that a message linked to a composer is actually
meant to say the composer is for editing the message, and when
editing the message the composer shows no avatar as this is shown
by the `Message` component.

Portal chatter reply to comment should display avatar of self
user, but the problem is that the component `Composer` isn't
directly linked to `thread`, therefore the LOC `thread.effectiveSelf`
crashes in template.

This commit fixes the issue by using the `message` linked to
composer when no immediate thread is found in order to display
the `effectiveSelf` avatar. A composer is necessarily linked to
either a thread or composer, thus this ensures the `effectiveSelf`
is defined.