[FIX] base: Fix attachment generation for multi-page reports
When we try to print multiple invoice who have multiple pages and have
H2 title in the comments, the system treats the document as separate files,
resulting in error: `AttributeError: 'NoneType' object has no attribute 'getValue'`.

Steps to reproduce:
- Create an invoice without any attachment.
- Create another invoice, ensuring that its printout spans multiple pages,
  and add an H2 title in the comments (narration).
- In the list view, attempt to print both invoices.
  - Ensure that the report being printed contains a value in the
    "Save as attachment prefix" field.

The issue arises because the presence of multiple H2 headings causes the
system to treat the document as separate files. Consequently, the condition
`if has_same_number_of_outlines and has_top_level_heading:`` is not
satisfied, which results in a stream to be None.

opw-4247013

closes odoo/odoo#187425

X-original-commit: b1276434c8b96baf29163d597ab615abd5dc8645
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>
Signed-off-by: Louis Gobert (loug) <loug@odoo.com>