[FIX] pos_hr: use session.id instead of config.current_session_id.id
`pos.config.current_session_id` is a computed field from the backend.
In some cases, it's possible that we don't have this field causing the following error

```
  TypeError: undefined is not an object
    (evaluating 'this.config.current_session_id.id')
```

Task: https://www.odoo.com/odoo/project/1737/tasks/6253422
X-original-commit: 7eec4bc6c520bfa4bff4361fc5ff52a514d0e89f