[FIX] pos_self_order: translate custom link names for available languages
Steps to reproduce:
-------------------
1. Enable self ordering with default language set to French
2. Open the self-order interface

-> The "Order Now" button label is still in English.

Why the issue:
--------------
The "Order Now" link is created dynamically in Python, so its translations
are not automatically populated from the po files. Only the language active
at creation time (typically English) is stored.

The fix:
--------
In `_prepare_self_order_custom_btn`, create the button in 'en_US', then
translate it to the other languages: the self order available languages,
but also the default user language. In that case, whenever a new
language is added to the self order languages, it will get translated.

Notes:
------
1. The initial button name is now created in plain english, and later
translated to the env language. That would allow us to always find that
particular button by doing `link.with_context('en_US').name === "Order Now"`.

2. We only translate to foreign X language (i.e. a non en_US language),
if the translation for the button in that X language is not set (i.e.,
if `link.with_context(lang=X).name == "Order Now"). That avoids
overriding any user custom translations.

3. `get_translation` was directly used because we cannot use `env._`
function as follows: `env._(link.name)` as that will throw a linting
error: "Bad usage of _, _lt function. (E8502)".

See: https://www.odoo.com/documentation/master/developer/howtos/translations.html#variables

opw-6088248