[FIX] point_of_sale, pos_restaurant: prevent error when loading store data
Currently a 'ParseError' arises when we try to load the store data after
deleting the 'Food' Category in Invoicing.

Steps to reproduce:
- Install 'Invoicing' application (without demo data).
- Invoicing > Configuration > Categories > Delete 'Food'
- Now in POS try to load 'Restaurant' and 'Bar'

Traceback:
ValueError: External ID not found in the system: point_of_sale.product_category_food

ParseError: while parsing /home/odoo/src/odoo/saas-18.1/addons/pos_restaurant/data/scenarios/restaurant_data.xml:56, somewhere inside
<record model="product.product" id="pos_food_bacon">
            <field name="name">Bacon Burger</field>
            <field name="list_price">15.50</field>
            <field name="standard_price">13.95</field>
            <field name="description_sale">200G Irish Black Angus beef, caramelized onions with paprika, chopped iceberg salad, red onions, grilled bacon, tomato sauce, pickles, barbecue sauce</field>
            <field name="type">consu</field>
            <field name="weight">0.01</field>
            <field name="uom_id" ref="uom.product_uom_unit"/>
            <field name="image_1920" type="base64" file="pos_restaurant/static/img/th-burger.png"/>
            <field name="available_in_pos" eval="True"/>
            <field name="categ_id" ref="point_of_sale.product_category_food"/>
            <field name="pos_categ_ids" eval="[(6, 0, [ref('food')])]"/>
        </record>

The error occurs because the user deleted the category, and then tried to load
the store data, that references the missing product category.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6314696040