[FIX] mail: no "'id' is lacking" on uploading attachment (odoo.sh)
A recent fix [1] introduced an issue on odoo.sh DBs where uploading
any file resulted to the following error:

```
Error: Identifying field "id" is lacking a value on Attachment with 'and' identifying mode
```

This happens because the code changed the inner-logic of
`_onAttachmentUploaded` to return attachment data rather than
make attachments. The operation was kept as synchronous, but
there's actually some custom code specific to odoo.sh infrastructure
that makes `_onAttachmentUploaded` asynchronous. Due to this,
JS models were feed with `Promise<object>` instead of `object`.
`Promise<object>` is unsupported by JS models as data, which lead to
the generic error `"id" is lacking`.

This commit fixes the issue by artificially turning method async,
so that the code always `await _onAttachmentUploaded()` so that
JS models necessarily receive an object of data as it should.

opw-3885216
opw-3940011
opw-3940054
opw-3940987

[1]: https://github.com/odoo/odoo/pull/164197

X-original-commit: 1a4c3f7973866888e6139594c6311791e4fb8de1