[FIX] website: fail inde palette in theme tab
The goal of this commit is to fix an undetermined bug in the theme tab
palette tests. Sometimes, ‘reload assets’ occurred before the end of the test.
We will therefore wait to go through ‘reload assets’ before the end of
the test in order to make it deterministic.

Error: https://runbot.odoo.com/odoo/error/232650
X-original-commit: bbd76a37c9858af82975e2a7f3e7e61fa2fc18d5