[FIX] l10n_ro res.partner form inheritance
When opening res.partner form view with a user who has no accounting rights, this raises following error because of wrong inheritance of this view:

AttributeError: Element '<field name="property_account_position">' cannot be located in parent view

Error context:
View `res.partner.form.ro`
[view_id: 1237, xml_id: l10n_ro.res_partner_form_ro, model: res.partner, parent_id: 126]

field property_account_position is added in the account module, not in base.