[FIX] sale_stock: prevent error when validating a picking record
Currently, an error occurs when user validates a picking.

Steps to Reproduce:

 - Install the sale_management and sale_stock modules.
 - Create a sale order without any sale order lines and confirm it.
 - Go to Inventory > Operations > Deliveries and create a picking record
   by adding a move line with a quantity greater than zero.
 - In the Additional tab, select the sale order (the one without order lines).
 - Now validate this delivery.

ValueError: max() arg is an empty sequence

This error occurs because, during validation of the delivery record,
the system attempts to create a sale order line for the product. If the
sale order does not have any existing order lines, the system tries to
determine the sequence from existing sale order lines. Since no lines exist,
the sequence list is empty[1], raising the error.

This commit ensures that when a sale order has no existing order lines,
a default sequence value of zero is used.

[1]: https://github.com/odoo/odoo/blob/9e404b52e8c9375a6534a67cfb0fcc0df523402b/addons/sale_stock/models/stock.py#L164

sentry-7089149997

closes odoo/odoo#254578

X-original-commit: 0f113c4a1c51bd98420cd9c710af71cab631e94b
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>