Cherry pick of 56435677e6e40ade966ebc75654dbd4309613458 failed
stdout:

stderr:
14:05:26.373578 git.c:344               trace: built-in: git cherry-pick 56435677e6e40ade966ebc75654dbd4309613458
error: could not apply 56435677e6e... [REF] point_of_sale + pos_restaurant: adjusted code for German POS localization
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: