[FIX] calendar: allow multi-record duplication of appointments
This error occurs when users attempt to duplicate multiple bookings within an
appointment.

Steps to reproduce:
- Install 'appointment' module
- Select an appointment (ie. Dental Care)
- Click on New and make 2 new bookings
- Go to list view > Select both records > Duplicate

Traceback:
ValueError: Expected singleton: calendar.event(5, 8)

This occurred because we called 'default_get' with a non-empty recordset at the
beginning of the 'create' method.

closes odoo/odoo#224389

X-original-commit: 67480e40e43da607ff379f7eab51cfa135a89639
Signed-off-by: Jérémy Hennecart (jeh) <jeh@odoo.com>