[FIX] project: handle type error in project.tags object
When users search for projects by tag name, in that case, a traceback error
occurs.

Steps to produce:
- Install the "project" module.
- Go to the "Project" icon, and Kanban View will open.
- Search projects by tag name, e.g., "Internal"
After that, a traceback will be generated.
Error:  TypeError: '<' not supported between instances of 'int' and 'NoneType'

When users search for projects by tag name, in that case,
limit is none type and len(ids), i.e., project tag ids and its type int,
so a type error occurs.

Code reference:
https://github.com/odoo/odoo/blob/saas-16.4/addons/project/models/project_tags.py#L85

sentry:4489689778