[FIX] stock: fix inconsistency on onhand qty on product
after this pr:
https://github.com/odoo/odoo/pull/164196
It will create inconsistency during upgrade
specially when we are upgrade from 15.0 to 17.0
or 16.0 to 17.0 because when it's try to compute
`qty_available`, it's call `_compute_quantities_dict`,
on that function, to find quant domain, using `get_domain_location`
and on that function will find those warehouses which has
`company_id = self.env.companies.ids` and then related
virtual location of that warehouses. but in 15.0 and 16.0
wil find all the warehouses as that code does
not exist in 15.0 and 16.0 so it will find
all the warehouses's virtual location before upgrade
and that will raise exception.

```
Traceback (most recent call last):
  File "/tmp/tmpshmnsol1/migrations/testing.py", line 211, in test_check
    self.check(value)
  File "/tmp/tmpshmnsol1/migrations/stock/tests/test_on_hand_quantity.py", line 58, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[2, [59 chars]24, '5'], [25, '3'], [26, '4'], [33, '1'], [34[21202 chars]37']] != [[2, [59 chars]24, '4'], [25, '3'], [26, '4'], [33, '1'], [34[6923 chars]'3']]

First differing element 6:
[24, '5']
[24, '4']
```

X-original-commit: fa9c559ef9f2b52aee18431e941a6fc2f43338da