[FIX] website: fix invalid datetime format for Visitors graph view
Currently, the search filters of the graph view of the 'website.visitor'
model contain datetime objects that are no longer supported. As a result,
the system throws an exception when the user tries to open the graph view
of the 'website.visitor' model.

error: psycopg2.errors.InvalidDatetimeFormat

To fix the issue, we will convert the datetime objects of the search
filters to a string by using the 'strftime' function. The string will
then be correctly interpreted by the system and the user will be able
to open the graph view.

task-2647293