[FIX] mail: avoid auto-mark as read in discuss HOOT test
Before this commit, this test was failing non-deterministically on
on some machines:
```
show banner for new message after thread was read from another device
```

With the following error:

```
Error: Failed to find 1 of ".o-mail-Thread-banner:has(:text('1 new message'))" (Timeout of 3 seconds). Found 0 instead.
```

This happens because while the message list has 20 messages, each
message is 1-line long. That means on many monitors the bottom of
conversation is visible and thus it can mark as read automatically
the conversation. When this happens the banner is removed, thus the
last step would fail.

This commit fixes the issue by making each message body bigger, so
that this is very unlikely to see the bottom of message list,
therefore avoiding the auto-mark as read from reaching the bottom
of conversation.

closes odoo/odoo#280102

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>