fix res.config default get
when programmatically creating a sale.res.config with
{u'group_sale_delivery_address': 1}, I'd get an SQL Exception:

DataError: invalid input syntax for integer: "True"
      LINE 1: ...rue, false, NULL, '1', false, NULL, NULL, 'cost', 'True', NU...

This was caused by default_get returning the following values:

{'auto_done_setting': False,
 'default_invoice_policy': 'cost',
 'default_picking_policy': 0,
 'deposit_product_id_setting': False,
 'group_discount_per_so_line': True,
 'group_display_incoterm': False,
 'group_mrp_properties': False,
 'group_pricelist_item': False,
 'group_product_pricelist': True,
 'group_product_variant': False,
 'group_route_so_lines': False,
 'group_sale_delivery_address': 1,
 'group_sale_pricelist': True,
 'group_uom': False,
 'module_delivery': 0,
 'module_sale_contract': False,
 'module_sale_margin': 0,
 'module_website_portal': False,
 'module_website_quote': 0,
 'module_website_sale_digital': False,
 'sale_pricelist_setting': 'percentage'}

Notice the Booleans for the group_xxx fields which are fields.selection with integer values.

This commit fixes the issue by applying the same conversion as the one done for modules.