[FIX] repair: handle parse-error if reinstall repair module
When users try to reinstall the "repair", a traceback will be generated.

Error:  while parsing /home/odoo/src/odoo/saas-16.4/addons/repair/data/repair_data.xml:9,
somewhere inside <record id="picking_type_warehouse0_repair"
model="stock.picking.type" forcecreate="0"> <field name="name">Repairs</field>
<field name="code">repair_operation</field>
<field name="company_id" ref="base.main_company"/>
<field name="default_location_src_id" ref="stock.stock_location_stock"/>
<field name="default_location_dest_id" model="stock.location" search="[('usage'...

When users try to reinstall the "repair", a traceback will be generated.
Because duplicate sequence records exist, they raise the ParseError.

This commit solves the above issue by clean-up sequences the "repair" module
uninstallation time.

code reference:
https://github.com/odoo/odoo/blob/a7f2d4420541ec9e974b961dd7bc9e5477ba999c/addons/stock/models/stock_picking.py#L286

https://github.com/odoo/odoo/blob/a7f2d4420541ec9e974b961dd7bc9e5477ba999c/addons/repair/data/repair_data.xml#L9

sentry-4570653150