[FIX] l10n_account_withholding_tax: prevent error when no repartition_line_ids
Traceback when no `repartition_line_ids` found in tax data.

Steps to reproduce:-
- Install `l10n_in` module with demo data.
- Install `l10n_account_withholding_tax` module.

Error:-
File /data/build/odoo/addons/l10n_account_withholding_tax/__init__.py, line 27, in _make_demo_tax
    tax_repartition_lines = [line[2] for line in tax_data[purchase_taxes[0]]['repartition_line_ids'] if line[2]['repartition_type'] == 'tax']

KeyError: 'repartition_line_ids'

Root Cause: At [1], No `repartition_line_ids` found in
`tax_data[purchase_taxes[0]]`.

Solution: Select only purchase taxes having `repartition_line_ids`.

[1]: https://github.com/odoo/odoo/blob/9805d09dff64de835de0c764da8c6e213d6b88aa/addons/l10n_account_withholding_tax/__init__.py#L27

closes odoo/odoo#227742

X-original-commit: a37a21195704a30732a7cc32680ff91d15f53b7d
Signed-off-by: Maximilien La Barre (malb) <malb@odoo.com>
Signed-off-by: Pratham Nareshbhai Patel (ppat) <ppat@odoo.com>