Cherry pick of ec6a49beeb91e99e15ffbb3112859839c4089ca8 failed
stdout:

stderr:
error: could not apply ec6a49beeb9... [REF] l10n_cl: Add custom report
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'