[FIX] hr_recruitment: add `company_id` field in applicant view
Steps to reproduce:
1. make an applicant, leave recruiter field empty
2. Go to kanban view and try to assign a recruiter on the
applicant

Error:
```
UncaughtPromiseError > EvalError
Uncaught Promise > Can not evaluate python expression: ([('share', '=', False), ('company_ids', 'in', company_id)])
Error: Name 'company_id' is not defined
```

The issue happens because the `company_id` field is missing
from the view and as a result this field cannot be found.

This commit adds the field so that the domain can be calculated
correctly.

opw-4188706

closes odoo/odoo#180595

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>