[FIX] website: fix slug_matching RequestUID
Before this commit, try to access original route that has been configured
with a redirect 308 will crash with an exception:
   psycopg2.ProgrammingError: can't adapt type 'RequestUID'

sudo() from PR v10 has been converted to new with_user system without check.
When we replace during review sudo by with_user, we don't reproduce it
because we always try to access /mag/<product> instead of /shop/<product>

How to reproduce:
   Add a 308 from /shop/<product>  to /mag/<product>
   Try to access /shop/<product> will crash with:
      psycopg2.ProgrammingError: can't adapt type 'RequestUID'