[FIX] point_of_sale: fix traceback during POS payment validation
Steps to reproduce:

1. Install the POS module.
2. Open POS and add a product.
3. Proceed to the payment page.
4. Make a payment greater than (total cost of order * 1000).
5. Try to validate the payment → traceback occurs.

Issue:
- A traceback is raised when validating a payment in the POS screen.

`undefined
TypeError: Cannot read properties of undefined (reading 'utils')
    at OrderPaymentValidation.isOrderValid `

Cause:
-  ` this.env` is not directly accessible in `OrderPaymentValidation`.
-  Use `this.pos.env` instead of `this.env` to correctly access the environment
during payment validation,

 -Reference:
https://github.com/odoo/odoo/blob/33c789eeed3b307e40c0f7ab2c6bc07c33867498/
addons/pos_online_payment/static/src/app/utils/
order_payment_validation.js#L25-L28

Solution:.
- Add return `True` in `validateOrder`, because even when the order was valid,
it returned `False`, causing the `ConfirmationDialog` to reopen repeatedly
when clicking 'OK'. Returning `True` ensures the dialog closes properly after
successful validation.

- Reference:
https://github.com/odoo/odoo/blob/d309b52e5b19727b3e91ed91afd44e392a3b851a/
addons/web/static/src/core/confirmation_dialog/confirmation_dialog.js#L71-L91

- After fixing the traceback, the 'Large Payment Amount' confirmation dialog
appears correctly. However, when clicking 'OK', the dialog was not closing
because the callback function `validateOrder` returned `False` even for valid
orders. This caused the dialog to reopen in an infinite loop.

https://github.com/odoo/odoo/blob/4cd1ad3aa46ad4645fc7b5e530b79d53382de6d5/
addons/point_of_sale/static/src/app/utils/order_payment_validation.js#L108-L138

opw-5137557

closes odoo/odoo#230526

X-original-commit: 6b170bcd8b1fe5b002ab69e67583289f62ce2219
Related: odoo/enterprise#96614
Signed-off-by: David Monnom (moda) <moda@odoo.com>
Signed-off-by: Pawan Kumar Gupta (pkgu) <pkgu@odoo.com>