[FIX] account_edi_ubl_cii: handle missing ChargeIndicator tag in CII import
An error occurs when importing a Factur-X invoice with a missing
`ChargeIndicator` tag.

Steps to Reproduce:
1. Install the `account_edi_ubl_cii` module.
2. Navigate to Invoicing > Vendors > Bills.
3. Upload a Factur-X XML invoice with missing a `<ChargeIndicator>` tag.

Error:
AttributeError: 'NoneType' object has no attribute 'lower'

Cause:
With commit [1], if the <ChargeIndicator> tag is missing from the XML, the code
gets None and crashes when trying to convert it to lowercase.

Fix:
Default the charge indicator to `false` when the tag is missing in the XML.

[1]:https://github.com/odoo/odoo/commit/5baa55712be21e210c875faa6713598cca35d7b5

sentry-7745633352