[FIX] hr_holidays: fix traceback when creating a leave request
Currently, a traceback occurrs when creating a leave request for an employee

To reproduce this issue in 18.0:

1) Install hr_holidays
2) Navigate to Time Off > Management > Allocations.
3) Create an allocation for 2 employees with same leave type
4) Navigate to Time Off > Management > Time Off.
5) Create a new time off  for employye1, with above leave type
6) Now, change the employee to employee2

Error:-
"'hr.leave.allocation' object has no attribute 'virtual_remaining_leaves'"

Cause:-

The field `virtual_remaining_leaves` is  present in `hr.leave.type`,
it was introduced from saas~18.3 in `hr.leave.allocation`.

So indeed a traceback will occur when trying to access
`virtual_remaining_leaves` from allocation from the below line.
https://github.com/odoo/odoo/blob/97f9ad816cb4b35aa2d4713038cc2c623dfaf176/addons/hr_holidays/models/hr_leave_type.py#L168-L170

Solution:-

Since the value of `virtual_remaining_leaves` is retrieved from the same method
(_get_consumed_leaves) for both `hr.leave.type` and `hr.leave.allocation` in 18.3,
So we can use the value of `virtual_remaining_leaves` from `hr.leave.type`.

opw-4860637,4868969

closes odoo/odoo#216436

X-original-commit: cf8ebae5d8317b48e61efde398d5331cc1b5f8eb
Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>
Signed-off-by: Altaf Shaik (alsh) <alsh@odoo.com>