[FIX] l10n_pe_pos: various bugs preventing opening the POS session
1. Loading the POS with l10n_pe_pos installed will simply fail because
`_load_pos_data_fields` returns a list of fields, not a dict
("TypeError: list indices must be integers or slices, not str")

2. After fixing this first bug, we are met with another traceback in the
JS code: "TypeError: this.update is not a function". The update function
should be called on an order.

Bug 1 was introduced in 02f756d061f1e52a2265e051ac57b13b311fb115

Part-of: odoo/odoo#174922
Related: odoo/enterprise#67568
Signed-off-by: Olivier Colson (oco) <oco@odoo.com>
Signed-off-by: Julien Van Roy (juvr) <juvr@odoo.com>