[FIX] mrp: fix traceback when the user tries to cancel mrp order
Currently, a traceback occurs when the user  tries to cancel the Manufacturing
Order which is linked with a Purchase Order

Steps to reproduce:

1) Install purchase and MRP without Demo
2) Enable UOm and multi-step routes from settings
3) Unarchive the MTO route and enable the products that are created for BOM
4) Create 2 BOMs A, B in which the 2nd BOM contains the first one  in component
5) Make sure the first BOM's product must have a vendor
6) Create an MRP order with BOM B and click the forecast button from components
7) Click manufacturing Forecast and confirm it then cancel

Error:- " 'purchase.order.line' object has no attribute 'product_uom'"

In order_exceptions we do get objects like `sale.order.line`,
`purchase.order.line`, `stock.move`etc.... depending on the MRP order.

Which is used in the `mrp.exception_on_mo` template to display the
The UOM, product name, etc., can be found in the line below.
https://github.com/odoo/odoo/blob/51c6a0dd06a362d5f8327741287beb422f250b7d/addons/mrp/data/mail_templates.xml#L18

But when we get `purchase.order.line` in `order_exception`, we get
the above traceback because product_uom is changed to
`product_uom_id` from the below commit.

https://github.com/odoo/odoo/pull/186250/files#diff-5684edced9bdfc98021a85de4c6cdf691ea7add74e56ab50334a1d7db9ef4224L32-R33

We can resolve this issue by checking whether the product_uom
attribute available in the move_raw_id or not.

sentry-6240577568