[FIX] web: Set extend to optional for flat button style
Steps to reproduce:
-------------------

- Install `Sign` and `Website` (for test purpose)
- Go to the website and enable the web editor
- Click on Theme tab, and set Button -> Primary Style to `Flat`
- Go to Sign module and copy the Share link of a document
- Open it in an incognito window

Issue:
------

Error: `The target selector was not found`

Cause:
------

Trying to extend `.btn.flat` selector while it is not declared in the
dependencies of the `sign.assets_public_sign` assets.

Solution:
---------

Set the `extend` to `optional`.

opw-3989063

closes odoo/odoo#170819

X-original-commit: 416a02d6d5a09c472f81f0a7368d91728950c8d2
Signed-off-by: Romeo Fragomeli (rfr) <rfr@odoo.com>
Signed-off-by: Nasreddin Boulif (bon) <bon@odoo.com>