[FIX] account: fix account demo data import
Steps to reproduce:
- Re-install Odoo 17 with custom account demo data (e.g. account.account.csv)

Issue:
TypeError: 'ABCMeta' object does not support the context manager protocol

Cause:
In load(), commit 2ca15862a731a84560f761fc5e7b65e6d2885c54 introduced the line `manager = nullcontext`, which must be `manager = nullcontext()` (https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext).

closes odoo/odoo#150364

Signed-off-by: Brice Bartoletti (bib) <bib@odoo.com>