[FIX] make 'get_module_path' always return absolute path
Bug Description
===============

In some cases, it is possible that relative path `./odoo/addons` could
appear inside `odoo.addons.__path__` variables. Thus, creation of
database fails with error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/service/db.py", line 58, in _initialize_db
    odoo.modules.db.initialize(cr)
  File "/opt/odoo/odoo/odoo/modules/db.py", line 40, in initialize
    info = odoo.modules.load_information_from_description_file(i)
  File "/opt/odoo/odoo/odoo/modules/module.py", line 314, in load_information_from_description_file
    f = tools.file_open(manifest_file, mode='rb')
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 201, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/opt/odoo/odoo/odoo/tools/misc.py", line 259, in _fileopen
    raise IOError('File not found: %s' % basename)
OSError: File not found: ./odoo/addons/payment_payumoney/__manifest__.py
```

It seems that relative path `./odoo/addons` appended to
`odoo.addons.__path__` by `odoo/addons/__init__.py` file, which calls
`pkgutil.extend_path`. And when `get_module_path` searches for addon
path, it may find that addon inside *this relative path*, and return it
like `./odoo/addons/web_tour`. Next this module path goes to
`load_information_from_description_file` which tries to open manifest
(path=`./odoo/addons/web_tour/__manifest__.py`) via `tools.file_open`
which fails trying to read file `addons/./odoo/addons/web_tour/__manifest__.py`

This happens when following conditions met:

Current Working Directory: /opt/odoo-13
Odoo sources located in: /opt/odoo-13/odoo

Fix Details
===========

This commit attempts to fix this bechavior by changing
`get_module_path` to always return absolute path.