[FIX] hr_attendance: not filter attendance without check out
Currently, an error occurs when the user tries to open an employees
who checks in but does not check out.

Steps to produce:
1. Install 'hr_attendance'
2. Open Attendence > Attendences > create new
3. Set check In date previous month and no add Check out
4. Open employees > try to open current user

Error:  `'<=' not supported between instances of 'bool' and 'datetime.datetime'`

This is because https://github.com/odoo/odoo/pull/140629 added [1] in the
filter, but in certain cases, the `att.check_out` may not be present.

This commit fixes the above issue by filtering attendees who have
a check-out date.

[1]-https://github.com/odoo/odoo/blob/46f2a019bd141389233257f24f0ddae05b0fa008/addons/hr_attendance/models/hr_employee.py#L82

sentry-4616207347

closes odoo/odoo#141867

X-original-commit: 679c813ec79f2c2d4baab5851e27422a996f3772
Signed-off-by: Sofie Gvaladze (sgv) <sgv@odoo.com>
Signed-off-by: Thomas Lefebvre (thle) <thle@odoo.com>