[FIX] point_of_sale: raise not_found for invalid url
When the user tries to enter a URL like pos/ui?config_id=abc instead of
pos/ui?config_id=int, the traceback appears.

Steps to produce:
1. install  PoS module > open session.
2. change the URL with pos/ui?config_id=abc and the traceback will be generated
Error: ValueError: invalid literal for int() with base 10: 'string'

see:
https://github.com/odoo/odoo/blob/0a854e59867461d1c159a5ef16c57052765b730d/addons/point_of_sale/controllers/main.py#L36-L37
In the above use case when trying to convert a config_id into type int(), if the
value is not numeric it will lead to the above traceback.
So, this commit raises not_found() error instead of valueerror

sentry-4317550539