[FIX] account: move test case to enterprise
Community build was failing with:
```test_bill_state_change_on_payment_state
    self.assertEqual(payment.invoice_ids.payment_state, 'not_paid')
AssertionError: 'paid' != 'not_paid'
- paid
+ not_paid```

In community there is no any `in_payment` state for account move records. As on
changing payment state to draft It stayed in the `paid` only. `in_payment` state
introduced in the enterprise module. So the test case is failing for the
community version.

To fix this I've moved the test case to the enterprise to retain the expected
behaviour.

runbot error: 234453

closes odoo/odoo#238034

X-original-commit: b5bb073be795f367f6bcdc632d977466ed8171ba
Related: odoo/enterprise#100922
Signed-off-by: Paolo Gatti (pgi) <pgi@odoo.com>
Signed-off-by: Joyal Patel (pajo) <pajo@odoo.com>