[FIX] account: calculate early discount if invoice has it in batch payment
While registering payments in batches, if one invoice payment term has an early
discount and another does not have an early discount, it generates a traceback.

Steps to Reproduce:
   1. Install "Invoicing".
   2. Create two invoices with different customers.
   3. Open the first invoice, select the 'payment term' that does not
      have an early discount, and confirm it.
   4. Open the second invoice, select the 'payment term' that has an
      early discount, and confirm it.
   5. From the list view select those two invoices and click on
      the 'Register Payment' Button.
   6. Then click on the wizard 'Create Payment' button.

Error: UnboundLocalError: local variable 'aml' referenced before assignment

This commit solves the above issue by calculating an early discount
if the related invoice payment term has an early discount.

sentery-4315297841