[FIX] web: select colors per cycle in a calendar
To reproduce the error:
1. Have a DB with > 24 users
2. Create an event for each user (in same week)
3. Open Week view in Calendar

Error: the first 24 users have a different color, but all the others
will have the same color.

30 colors are available:
https://github.com/odoo/odoo/blob/94b3e339ba45f664e8b892067a4dd3df134ec325/addons/web/static/src/scss/secondary_variables.scss#L9-L20
Therefore, each one should be used. Moreover, if the 30 colors are
already used once, the colors selection should cycle again on the 30
ones.

OPW-2532748
closes #70940

closes odoo/odoo#71597

Signed-off-by: Adrien Widart <adwid@users.noreply.github.com>
Co-authored-by: Nicolas Lempereur (nle) <nle@odoo.com>