[FIX] point_of_sale: fix traceback during POS payment validation
Steps to reproduce:

1. Install the POS module.
2. Open POS and add a product.
3. Proceed to the payment page.
4. Make a payment greater than (total cost of order * 1000).
5. Try to validate the payment → traceback occurs.

Issue:
- A traceback is raised when validating a payment in the POS screen.

`undefined
TypeError: Cannot read properties of undefined (reading 'utils')
    at OrderPaymentValidation.isOrderValid `

Cause:
-  ` this.env` is not directly accessible in `OrderPaymentValidation`.
-  Use `this.pos.env` instead of `this.env` to correctly access the environment
during payment validation,

 -Reference:
https://github.com/odoo/odoo/blob/9787b67b910476e72f93bcf8d60338ce6b06d076/
addons/pos_online_payment/static/src/app/utils/
order_payment_validation.js#L25-L28

Solution:.
- Add return `True` in `validateOrder`, because even when the order was valid,
it returned `False`, causing the `ConfirmationDialog` to reopen repeatedly
when clicking 'OK'. Returning `True` ensures the dialog closes properly after
successful validation.

- Reference:
https://github.com/odoo/odoo/blob/2a8f9cff7c4673528e4e24995d9b77eaf7f7296e/
addons/web/static/src/core/confirmation_dialog/confirmation_dialog.js#L71-L91

- After fixing the traceback, the 'Large Payment Amount' confirmation dialog
appears correctly. However, when clicking 'OK', the dialog was not closing
because the callback function `validateOrder` returned `False` even for valid
orders. This caused the dialog to reopen in an infinite loop.

https://github.com/odoo/odoo/blob/bb45c34c990079368e84786e11d38fdc2f3224a2/
addons/point_of_sale/static/src/app/utils/order_payment_validation.js#L108-L138

opw-5137557

closes odoo/odoo#230069

Related: odoo/enterprise#96284
Signed-off-by: David Monnom (moda) <moda@odoo.com>