[FIX] website_sale: prevent error when updating suggested products
Currently, an error occurs when the user tries to update suggested products.

Steps to Reproduce:
 - Install the website_sale module.
 - Go to Settings and enable Automate suggested products under the
   eCommerce section.
 - Go to Website > eCommerce > Products > Products.
 - Create a product and, in the eCommerce tab, add a category.
 - Make sure the product is not published.
 - On the product, click the gear icon and select Update suggested products.

ValueError: TypeError('unsupported operand types in: product.template() | None') while evaluating
'records.action_update_suggested_products()'

When the user updates suggested products, the system updates the product's
suggested products - optional, accessory, and alternative products [1].
While updating the alternative products [2], the system tries to find products
based on the categories and attributes shared with the current product [3].
When retrieving products from the current product's category, it gets
None [4] because the products linked to that category are unpublished and
are therefore excluded by the domain [5]. Later, using this None value raise
the error.

This commit ensures that when accessing a missing key in the category
dictionary, then it falls back to an empty product recordset.

[1]: https://github.com/odoo/odoo/blob/21e3310a3eba2ce915b33cf10ee4c14bdda7aad4/addons/website_sale/models/product_template.py#L346

[2]: https://github.com/odoo/odoo/blob/21e3310a3eba2ce915b33cf10ee4c14bdda7aad4/addons/website_sale/models/product_template.py#L384-L386

[3]: https://github.com/odoo/odoo/blob/21e3310a3eba2ce915b33cf10ee4c14bdda7aad4/addons/website_sale/models/product_template.py#L471-L483

[4]: https://github.com/odoo/odoo/blob/21e3310a3eba2ce915b33cf10ee4c14bdda7aad4/addons/website_sale/models/product_template.py#L482

[5]: https://github.com/odoo/odoo/blob/21e3310a3eba2ce915b33cf10ee4c14bdda7aad4/addons/website_sale/models/product_template.py#L445-L456

sentry-7660509183

X-original-commit: eb6cb54fd92bd3b57d2c4a02b26173e0bff8a880