[FIX] stock: prevent traceback on print picking operation report
Issue Before This Commit:
============================

A traceback occurs when printing the picking operations report.

Steps to Reproduce:
=====================
1. Install the purchase_stock module.
2. Activate 'Units of Measure & Packagings'.
3. Create a new Purchase Order (PO) with multiple purchase order lines.
4. Confirm the PO and navigate to the receipt.
5. Print a 'Picking Operations' report. it will give errors like:
  - AttributeError: 'stock.move' object has no attribute 'product_packaging_id'.

With This Commit:
=====================

The issue occurred because `product_packaging_id` was removed from `stock.move`
in this [PR](https://github.com/odoo/upgrade/commit/1ab23e5418c820329a618fb4c8c9f48b7862b6ec).
This fix replaces it with `packaging_uom_id`, ensuring the correct field is used
and preventing errors when printing the report.

task - [4583172](https://www.odoo.com/odoo/my-tasks/4583172)

closes odoo/odoo#198230

X-original-commit: a5a18e6e21ac3f4a3cd975345e9808234e9d0f5d
Signed-off-by: William Henrotin (whe) <whe@odoo.com>
Signed-off-by: Dhaval Hadiya (dhha) <dhha@odoo.com>