[FIX] sale_loyalty: prevent error on buying multiple gift cards
Currently, an error will occur when user tries to buy multiple giftcards from
the  website.

Error:
```
TypeError: SaleOrder._get_real_points_for_coupon() got an unexpected keyword argument 'post_confirm'
```

This occurred because the function `_get_real_points_for_coupon()` accepts the
argument `_post_confirm`[1] (changed by this [PR]), whereas  here in this
template we pass `post_confirm`.

Changed the method signature to accept the argument `post_confirm`.

[1]: https://github.com/odoo/odoo/blob/32d02f22a0f397ddcc83fe1cee53f8f62d73338d/addons/sale_loyalty/models/sale_order.py#L850
[PR]: https://github.com/odoo/odoo/pull/237354/changes#diff-05c263ea6063dd0045f2cd5be1888d608448ef8ff11f23371616334273c133e5L781-R845

sentry-7482959769

X-original-commit: b61e88e107783d0c7fc7923745b2d49ad85cc6b9