[FIX] fields,models,mail: prevent error while uninstalling module
Currently, an error is generated when the user tries to uninstall
`helpdesk_fsm` (same for `wbesite_helpdesk_livechat` after enabling
'Live Chat' in the helpdesk team).

error: `KeyError: 'helpdesk.team.fsm_project_id'`

This issue was generated because at line [1] it tries to reset the `use_fsm`
field (set use_fsm as false), but since `use_fsm` depends on the compute field
of `fsm_project_id` it tries recompute value while uninstalling `helpdesk_fsm`
but field `fsm_project_id` not in registry.

This commit will fix the above issue by accessing fields to compute from
pool by `.get` instead of direct field access; it will not throw a key error
when a field is not available.

[1] - https://github.com/odoo/enterprise/blob/c3d867ec1f17b1024e36213942c099f2982efe26/helpdesk/models/ir_module.py#L13-L16

sentry-6015535085