[FIX] hr_holidays_attendance: prevent traceback when clicking on time off type
Steps to reproduce:
--------------------------
1. Install hr_holidays_attendance.
2. Go to Time Off > Dashboard
3. Try to click on "Extra Hours"

Issue:
--------
A traceback occurs:
```
InvalidDomainError: Invalid domain representation: holiday_status_id,=,5,company_id,=,,user_id,=,2
```

Cause:
---------
After 0aeaa2b (hr_holidays), clicking a time off type sends
`employee_company` in the domain. However, the hour-based time off type
created by `hr_holidays_attendance` does not define `employee_company`,
so the domain contains 'undefined', triggering InvalidDomainError.

Solution:
-----------
Add the missing employee_company value in hr_holidays_attendance
to resolve the issue.

opw-5358682

closes odoo/odoo#239185

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>