[FIX] mail: add activities in mail thread if model has activity_ids field
When user call form mailing list contact and clicks on end call button traceback
will appear this is because mailing list contact not have activity_ids field.

Steps to reproduce the error:
- Install 'SMS Marketing' and 'Voip'
- Go to 'SMS Marketing' > Mailing Lists > Mailing Lists Contacts
- Open any record, add mobile number > call
- End the call

Error: A traceback appears: "AttributeError: 'mailing.contact' object has no
attribute 'activity_ids'"

sentry-4306579710