[FIX] pos_restaurant: load only shop demo products when no restaurant
When the user using `point_of_sale` deletes pos restaurant and tries
to load demo products in pos shop then user will face error.

Note: Use db without demo data

steps to produce:
- Install `point_of_sale`.
- Point Of Sale > Configuration > Point Of Sales, delete pos restaurant.
- Point Of Sale > Shop > New Session, click on `our demo products`.

Error: `TypeError: unsupported operand types in: pos.config() | None`

After applying our commit, if the user clicks on `our demo products`
after deleting pos restaurant then the user would be atleast able to see
shop demo products and other demo products which are not part of
pos restaurant.

sentry-4399441443