FIX missing method set_message_read Without this , if you click on https://github.com/odoo/odoo/blob/9.0/addons/website_forum/views/website_forum.xml#L108 you get   File "/home/elbati/workspace/odoo/progetti/community.seedoo.it/git/parts/odoo-ocb/addons/website_forum/controllers/main.py", line 100, in notification_read     request.env['mail.message'].browse([int(kwargs.get('notification_id'))]).set_message_read(read=True) AttributeError: 'mail.message' object has no attribute 'set_message_read'