[FIX] l10n_tr_nilvera_einvoice: fix zero VAT warning field type
The `l10n_tr_zero_vat_warning` field is a boolean field but was
incorrectly defined as [binary], causing the compute method to fail
when assigning a boolean value.

```py
  File "/home/odoo/src/odoo/saas-19.3/addons/l10n_tr_nilvera_einvoice/models/account_move.py", line 156, in _compute_l10n_tr_l10n_tr_zero_vat_warning
    invoice.l10n_tr_zero_vat_warning = exempt_zero_tax and invoice.l10n_tr_gib_invoice_type == 'SATIS' and exempt_zero_tax in invoice.line_ids.tax_ids
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/odoo/orm/fields.py", line 1892, in __set__
    self.write(protected_records, value)
  File "/home/odoo/src/odoo/saas-19.3/odoo/orm/fields_binary.py", line 151, in write
    super().write(records, value)
  File "/home/odoo/src/odoo/saas-19.3/odoo/orm/fields.py", line 1583, in write
    cache_value = self.convert_to_cache(value, records)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/odoo/orm/fields_binary.py", line 83, in convert_to_cache
    raise TypeError(f'{self}: use BinaryValue instead of {value.__class__.__name__}')
TypeError: account.move.l10n_tr_zero_vat_warning: use BinaryValue instead of bool
```

upg-4608394

[binary]: https://github.com/odoo/odoo/pull/242043/changes#diff-d3cbb345d0a5855b7d7aa91e64a0ff480e3e5acfa3b2c71503a23ca7f3c0c511R132