[FIX] auth_oauth: raise badrequest on missing state
When the user tries to log in with `odoo.com` or any other third-party app this
traceback may appear.

ERROR: Traceback will appear KeyError: 'state'

This commit will solve the above issue by raising the `BadRequest` if the
`state` is not available in `kw`.

Sentry-4476285288