[FIX] auth_ldap: LDAP login fails if it creates a new user.
Steps:

 - Set up LDAP authentication with Create User enabled and a Template User set
 - Log in with an LDAP identity that doesn't have an account yet

Get

odoo.exceptions.MissingError: Record does not exist or has been deleted

See https://github.com/odoo/odoo/issues/41060

X-original-commit: 752c1f931fb0ebe495c74d5b457330a50da0abe7