[FIX] sale: update invoiced qty after credit note
When adding a credit note to cancel an invoice, in the corresponding SO,
the invoiced quantities of the products are not updated.

To reproduce the error:
1. Create a SO with a product P
	- Set P-product's quantity to X
2. Confirm the SO
3. Invoice the X P-products, Validate the invoice
4. Go back to SO
	- The "Invoiced Quantity" for P-product is X
5. Go back to the invoice: Add credit note
	- Method: Cancel
5. Go back to SO

Error: The "Invoiced Quantity" of the product is not reset: the value is
still X. It should be 0. This flow works correctly from version 13
onwards.

The issue comes from the refund invoice creation which does not add the
link between SO's lines and refund invoice's lines. As a result, when
computing the invoiced quantity:
https://github.com/odoo/odoo/blob/ad2d96db8ad3e1fd7af2edda218fc34c0c1d259a/addons/sale/models/sale.py#L1045-L1053
`line.invoice_lines` will not contain the refund invoice lines, so
`qty_invoiced` will not decreased.

OPW-2419786