[FIX] {account_,}payment: allow generating QR codes without HTTP request
Versions
--------
- saas-18.3+

Steps
-----
1. In Accounting/Invoicing settings, enable "Add QR-code link on PDF";
2. create an automation rule for the `account.move` model;
3. set "Trigger" to "Create & Edit";
4. set "Apply on" domain to `[("state", "=", "posted")]`;
5. set "When updating" to "Status";
6. add an action to execute the following code:
   ```python
   env['account.move.send']._generate_and_send_invoices(records)
   ```
7. call `action_post` on an invoice via RPC or Odoo Shell.

Issue
-----
> odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
> RuntimeError: object is not bound

Cause
-----
In order to add a payment link QR code to the invoice[^1], it needs to
generate an access token for the portal. This happens via the
`generate_access_token` function from `odoo.addons.payment.utils`. Issue
is that it relies on having access to a `odoo.http.request` object, so
that it can use its `env` to retrieve the `database.secret` config
parameter.

When this flow gets triggered via an API call (or Odoo Shell), the
`request` object is unbound, causing the error.

[^1]: feature added via commit bcb73cd159885

Solution
--------
Introduce an optional `env` kwarg to `generate_access_token`, falling
back on `request.env` if it's not provided.

opw-5487075

closes odoo/odoo#243528

Signed-off-by: Levi Siuzdak <sile@odoo.com>