[FIX] mail: no crash on making draft record with livechat open
Before this commit, when a livechat operator had livechats open,
making a draft record result to crash.

Steps to reproduce:
- Log in as Admin;
- Set a livechat user name in Preferences then Save;
- In incognito, open livechat from website then post a message;
- In admin tab, when livechat is open, make a new record e.g.
  make a new sale order

=> Crash with:
```
TypeError: can't access property "channel_type", this.message.thread is undefined
```

This happens because when making a draft record, the chatter contains
the message "Creating a new record...". This record was missing
`originThread`, which is assumed to be necessarily known for any
message. Thankfully this is not a problem most of the time, but with
livechat open and livechat operator having a custom livechat name,
this executes evaluation of `this.message.originThread.type`, which
crashes due to unset `originThread`.

This commit fixes the issue by properly setting the originThread of
the "Creating a new record..." message.

opw-3913228

closes odoo/odoo#165265

Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>