[FIX] mail: convert date with user TZ
In the preferences, when changing the timezone of the user, the dates
are not correctly converted.

To reproduce the error:
(Use demo data)
1. Open CRM
2. In Proposition column, look at "Modern Open Space"
    - Clock is orange
    - Let the cursor over it, it displays "Today"
3. In the top bar, click on the clock (to get the activities)
    - There is one activity today
4. Go to CRM > Sales > My Activities
5. The activity for "Mordern Open Space" is scheduled for Today
    - It will be the same, in the logs, if you open the "Modern Open
Space"
6. In user preferences, change the timezone so that the date change to
yesterday or tomorrow
    - e.g., "Pacific/Honolulu" (the most easterly), "Pacific/Auckland"
(the most westerly)
    - (Here, suppose we choose "Pacific/Honolulu": the date changes to
yesterday)
7. If you repeat setps 2-3, all is updated:
    - Clock became green
    - It displays "Planned"
    - There isn't any activity for today
8. Open "Modern Open Space"

Error: In the logs, the activity is also scheduled for today (incorrect)
and the color of the word 'today' is green (i.e., color for future
activities -> also incorrect).

The value is based on the local machine timezone. It should use the user
timezone (as defined in the preferences).

OPW-2392170