[FIX] pos_hr: use session.id instead of config.current_session_id.id
`pos.config.current_session_id` is a computed field from the backend.
In some cases, it's possible that we don't have this field causing the following error

```
  TypeError: undefined is not an object
    (evaluating 'this.config.current_session_id.id')
```

closes odoo/odoo#268544

Task: https://www.odoo.com/odoo/project/1737/tasks/6253422
X-original-commit: a320d5222efdf3f8467373f341da6ad331efa5d7
Signed-off-by: David Monnom (moda) <moda@odoo.com>
Signed-off-by: Manu Vaillant (manv) <manv@odoo.com>