[FIX] account: prevent error when reloading chart template
Currently, an error occurs when reloading a chart template.

Steps to Reproduce:
 - Install the Accounting module with demo data.
 - Go to Accounting > Configuration > Accounting > Chart of Accounts.
 - Open the Current Assets account and remove its account code.
 - Go to Settings and click the Reload button under Fiscal Localization.

TypeError: expected string or bytes-like object, got 'bool'

After this [recent commit], account codes became optional and can be
removed. As a result, when the code is removed from the Fixed Assets
account and the chart template is reloaded, the reload process tries to
match template accounts [1] with existing accounts [2]. It retrieves the
existing account using its id [3] and correctly finds the account record,
but its code field is False. Later, when the reload logic compares the
existing account code with the template account code, it attempts to
 use account code in a regular expression, which raises error [4].

This commit ensures that accounts without a code are treated as having
a non-matching code.

[recent commit]: https://github.com/odoo/odoo/commit/c3313b336b9f1305c363097745926f2bdf61e277

[1]: https://github.com/odoo/odoo/blob/b04678b130438d5ee1605fadb9ca567930691fdf/addons/account/models/chart_template.py#L1153-L1155

[2]: https://github.com/odoo/odoo/blob/b04678b130438d5ee1605fadb9ca567930691fdf/addons/account/models/chart_template.py#L332

[3]: https://github.com/odoo/odoo/blob/b04678b130438d5ee1605fadb9ca567930691fdf/addons/account/models/chart_template.py#L435

[4]: https://github.com/odoo/odoo/blob/b04678b130438d5ee1605fadb9ca567930691fdf/addons/account/models/chart_template.py#L439

sentry-7556472625

closes odoo/odoo#271277

X-original-commit: 5ed53fb54e6541843f26a1e861df99170b5757a0
Signed-off-by: Antoine Boonen (aboo) <aboo@odoo.com>