[FIX] website_sale: prevent error when selecting estimated delivery date
Currently, an error occurs when the user selects an estimated delivery
date on the checkout page.

Steps to Reproduce:
 - Create a database with the Arabic language.
 - Install website_sale.
 - Go to Website > Configuration > eCommerce > Deliveries.
 - Open the Standard delivery record and, in the eCommerce tab,
   enable Estimated Delivery. Set 'In working days' with 'Allow selection
   up to day' and 'Based on value'.
 - Go to Website > Shop, add a product to the cart, proceed to checkout,
    and select the estimated delivery date displayed to the right of
   Standard delivery.

ValueError: time data '٢٠٢٦-١٠-٢٦' does not match format '%Y-%m-%d'

This error occurs because, when the user enters a date using Arabic
numerals, the date is displayed from right to left [1]. The date is then
passed as a string to set the commitment_date [2] of the order. Since
commitment_date is a datetime field, the string is converted to a
datetime value. However, the conversion expects the date to use
Latin numerals. As the date contains Arabic numerals, the conversion
raises the error [3].

This commit ensures that the date is serialized using serializeDate [4],
which uses the Latin numbering system (latn) expected by the system.

[1]: https://github.com/odoo/odoo/blob/9b0996e2d1d2254bc3a090183ff2e5dec6252a02/addons/website_sale/static/src/interactions/delivery_date_picker.js#L37-L40

[2]: https://github.com/odoo/odoo/blob/9b0996e2d1d2254bc3a090183ff2e5dec6252a02/addons/website_sale/controllers/delivery.py#L290-L298

[3]: https://github.com/odoo/odoo/blob/9b0996e2d1d2254bc3a090183ff2e5dec6252a02/odoo/orm/fields_temporal.py#L270

[4]: https://github.com/odoo/odoo/blob/7ef98548726f36856d78c745679b14b0165803ba/addons/web/static/src/core/l10n/dates.js#L552-L560

sentry-7776946208