[FIX] repair: assign zero price to service line when under warranty
Currently, an error occurs when user tries to end repair that has a service line
and is linked to a sale order or invoice.

Steps to replicate:
- Install `repair` with demo.
- Create a new repair order with a customer and check `Under Warranty`.
- Click on the `Services` page and add a product.
- Click on `Quote` button.
- Return to the repair order through breadcrumbs.
- Click `Confirm Repair` > `Start Repair` > `End Repair`.

Error:
```
  File '/home/odoo/odoo19/community/addons/repair/models/repair_service_line.py', line 120, in _update_repair_sale_order_line
    self.price_unit = 0.0
    ^^^^^^^^^^^^^^^
AttributeError: 'repair.service.line' object has no attribute 'price_unit'
```

Cause:
- The error was introduced after a recent improvement [PR].
- The `repair.service.line` model does not contain a `price_unit` field, which
  causes the error.
- The `price_unit` field is present in the related Sale Order Line or
  Invoice Line.

Solution:
- The price of the linked Sale Order Line or Invoice Line is now set to zero
  when the product is under warranty.

[PR]: https://github.com/odoo/odoo/pull/260278/files#diff-1ff5f0c96411a07c366ef6410fc4580798593205b57d5740fbb4a56259341c98R102

sentry-7620551626

X-original-commit: 0c15142ec606b9e1474856a95a642d7531b0c335