[FIX] mail : fix activitycell date
When on helpdesk app (or any app with an activity view), if you go on the
activity view while having activities due on a previous year it will
cause a traceback "TypeError: date.toLocaleDateString is not a function"

This happens because the function tries to call toLocaleDateString on a
datetime variable, not a date one.

opw-3432005

closes odoo/odoo#130090

X-original-commit: 81ec723b3956f198d5de99a5a4214359f67b8327
Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>