[FIX] pos_hr: compute employees per company
Step to reproduce:
- install point_of_sale with demo
- have two company and 1 pos in each company
- install pos_hr
- install pos_sale

Observation:
- we get a traceback
```
File "/src/saas-19.2/odoo/orm/fields_misc.py", line 115, in __get__
    raise ValueError("Expected singleton: %s" % record) from None
ValueError: Expected singleton: res.company(7, 8)
 ```
- and pos_sale is not installed

Cause:
- when installing `pos_sale`  `_ensure_downpayment_product` is called.
- this sets downpayment product on every `pos.config` record.
- this triggers write call from pos_hr, which tries to identify users for pos
- this uses `with_company(self.company)`   <-----  actual issue
- here self has two config, each from different company, hence `with_company`
raises singleton error

why not in earlier verison:
- before commit [1] we only set downpayment product on only pos_config_main
- now we set it on every pos.config, so now self contain multiple records

[1] https://github.com/odoo/odoo/commit/a3f9114434c7cab8757b0283698662792e6b7946

Fix:
- compute users per config

opw-6217135

X-original-commit: 582ee26e2bc004247598b9ea1e007e3c33fa30f0