[FIX] purchase: allow vendor to confirm that delivery will be on time
Steps to reproduce the bug:
- Go to contact and select azure interior:
    - Sales & purchase tab:
        - Enable “Receipt Reminder” 1 day

- Create a purchase order:
    - Select azure interior as vendor
    - add any storable product
    - Delivery ate: Tomorrow

- Confirm the PO

- Go to the Scheduled Actions: Purchase reminder
- Run it Manually
- Come back to the Dashbord > Emails
- Select the email for Azure interior:
    - Try to click on “YES”

Problem:
A traceback is triggered:
`AttributeError: type object 'datetime.datetime' has no attribute 'from_string'`

When the “YES” button is clicked, we retrieve the “confirmed_date”
from the arguments as a string and then call the `confirm_reminder_mail`
function (https://github.com/odoo/odoo/blob/809ff6c87e586146ca9c4c0388572fd71a575f04/addons/purchase/controllers/portal.py#L117).

This date will be localized to the PO timezone using the
`get_localized_date_planned` function: (https://github.com/odoo/odoo/blob/a0be5ea52aeff3520f8f1a92206a5aad38fdaa82/addons/purchase/models/purchase.py#L823).

We then get the timezone and use the `astimezone` function to transform
this date, but since it is in string format, an error is triggered.

This problem was introduced following this change:

https://github.com/odoo/odoo/commit/a0be5ea52aeff3520f8f1a92206a5aad38fdaa82#diff-86168e4c37e9a7c1437998990c2aa4e1690d16605812f57a81172936377b9c50L823

Before this fix, the date could be either a Date or a string, which was
already incorrect!

opw-4028362

closes odoo/odoo#172371

X-original-commit: f021f8e3480163584427ffa8adc2bfa28e5df9c0
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Djamel Touati (otd) <otd@odoo.com>