[FIX] account: prevent an error when create an invoice
Currently, An error occurs when attempting to create an invoice, and the user
entered invalid date in the 'Fiscal Periods' of the accounting settings.

Step to produce:

- Install the 'accountant' module (without demo data).
- Go to Settings / Technical / Sequences & Identifiers / Sequences, and Delete all
records.
- Go to Accounting settings, Set the month to February and the day to 29 in the
'Fiscal Periods' section.
- Go to Invoicing / Customers / Invoices, Try to create a new invoice.

ValueError: day is out of range for month

The issue occurs because the system attempts to get a 29th February
at [1], But 29th February is not available in all years(e.g '2025').

Link [1]: https://github.com/odoo/odoo/blob/0f507a8982a29bf1c35aaf9f8f97fc3d5381226c/addons/account/models/account_move.py#L3487

To resolve this, raise a validation error if the user enters an invalid date in
'Fiscal Year' of the accounting settings.

Sentry-6190026432