[FIX] mail: prevent error when parsing the mail without Content-type
An incoming mail may not contain a "Content-Type" header.
Parsing such a mail raises the error.

Traceback:
"AttributeError: 'NoneType' object has no attribute 'partition'"

https://github.com/odoo/odoo/blob/dd4aa68ff62d4e2d3796e36c8cfd1d7c762a61b8/addons/mail/models/mail_thread.py#L1679
This [commit] introduced parsing of the raw "Content-Type" header to extract
the MIME type.
When the "Content-Type" is missing, "part.get('Content-Type')" returns None,
It will lead to the above traceback during partition(';').

Solution:
Handle the missing "Content-Type" separately before validating the MIME type.
If header is missing, assume "application/octet-stream" and continue parsing.
Otherwise, keep the existing handling for unexpected MIME types and
the pdf case.

commit: https://github.com/odoo/odoo/commit/65c01ab682fbcbe6454192c689ffb394d312e1df

sentry-7598769539