[FIX] hr_work_entry_holidays: prevent error on installing module
Currently a 'ParseError' arises when the user installs the
'hr_work_entry_holidays' module after deleting all 'Time Off Types' in the
'Time Off' Configuration.

Steps to reproduce:
- Install 'hr_holidays' module (without demo data)
- Time Off > Configuration > 'Time Off Types' > Delete all
- Now install 'hr_work_entry_holidays' module

Traceback:
Exception: Cannot update missing record 'hr_holidays.holiday_status_comp'

ParseError: while parsing /home/odoo/src/odoo/saas-18.1/addons/hr_work_entry_holidays/data/hr_payroll_holidays_data.xml:5, somewhere inside
<record id="hr_holidays.holiday_status_comp" model="hr.leave.type">
            <field name="work_entry_type_id" ref="hr_work_entry_contract.work_entry_type_compensatory"/>
        </record>

The error occurs because the user deleted all 'Time Off Types' and then
installed the 'hr_work_entry_holidays' module. which requires particular records.

This commit solves the above issue by using noupdate="1" and forcecreate="False"
to bypass record creation if it violates checks.

https://github.com/odoo/odoo/blob/b794f0f332f473deb2c04eba60baf4761db3b508/odoo/tools/convert.py#L364-L366

sentry-5731062091

X-original-commit: 1ae13759e1484a7741d5c78885e9ee55d52e30dc