[FIX] mail_client_extension: not set parent_id if is_company
When using the Odoo Extension on Outlook, if the mail sender is already
a partner in the database, and if this partner is a company, it will
lead to an error on Outlook side

To reproduce the error:
(Need crm)
1. In Settings, enable "Outlook CRM Extension"
2. Set up an IAP account for service 'reveal'
3. On Outlook, let's have an email from X
4. On Odoo, create a partner P:
    - Partner is a Company
    - Email: X
5. On Outlook, open the Odoo Plugging

Error: An error message appears: "Something bad happened. Please, try
again later." and contact details are empty. There is a warning in Odoo
logs: "You cannot create recursive Partner hierarchies."

On extension loading, the module finds the partner P. Since the partner
hasn't any `parent_id`, the module then searches for a company linked to
the domain of X and finds P. It eventually tries to set the P's company
with P, this is the reason why an error is triggered.

When a partner hasn't any `parent_id`, the module should search for a
company only if the partner is not already a company.

OPW-2485223

X-original-commit: 8f599603f038bd903712746214edaeb83cbcc0ab