[FIX] calendar: include recurrent event to read_group result
In list view, when using the "Group By" functionality, if some events
are recurrent, the numbers of grouped events are incorrect: the
repetitions of the recurrent events are not counted.

To reproduce the error:
(Let "Mitchell Admin" be the current user's name)
1. Create an event E
	- Must be recurrent with 3 repetitions
2. Go to list view
3. Group by Responsible

Error: The number of events associated to Mitchell Admin is incorrect.
If the user clicks on the line (so he can see all Mitchell Admin's
event), the incorrect number will change and count all recurrences of
the events. (In this case: "Mitchell Admin (X)" becomes "Mitchell Admin
(X+2)", the repetitions of E-event have been added). The user should not
have to click on the line in order to get the correct number of events.

Note: This fix should be applied up to version 13. Afterwards, the
structure of the module has changed and the problem no longer occurs.

OPW-2455705