[FIX] base: prevent traceback when sequence_date is not a datetime
## Issue
When trying to call `dt.replace` on a `datetime.time`, a TypeError is raised

```
File "/home/odoo/Documents/src/odoo/190/odoo/addons/base/models/ir_sequence.py", line 270, in _next
    return seq_date.with_context(ir_sequence_date_range=seq_date.date_from, ir_sequence_date=dt.replace(tzinfo=None))._next()
                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'tzinfo' is an invalid keyword argument for replace()
```

## Steps to reproduce
1. Install *Accounting* (`accountant`)
2. Update the `account.payment` sequence:
    - Toggle *Use subsequences per date_range* and create a range
3. In Accounting > Customers > Payments, create a payment:
    - Payment Type: Receive
    - Customer: Any
    - Amount: Any
4. **A traceback appears**

## Cause
This error was introduced by https://github.com/odoo/odoo/commit/d2bec686edff.

The `AccountPayment._compute_name` method calls `_next_by_code` and passes
a date as the `sequence_date`.

https://github.com/odoo/odoo/blob/22a63b49a260dbde86aaab201b21b6c1a5a3d389/addons/account/models/account_payment.py#L420-L422

In the `_next` method, the `dt` variable is set to that date (`datetime.date`),
and calling the `.replace` method on that variable raises an error, as there's
no tzinfo for `datetime.date`s.

opw-6303885

closes odoo/odoo#270283

Signed-off-by: Raphael Collet <rco@odoo.com>