[FIX] sale_mrp: override l10n_ke invoice policy
Steps to reproduce:
===================
- Install `sale_mrp` and `l10n_ke_edi_oscu_stock`
- Set company country to be 'Kenya'
- Run the `test_kit_cogs_entry_with_delivery_line_removal` test
> odoo.exceptions.UserError: Cannot create an invoice. No items are available to invoice.

Cause of Issue:
===============
The test validates COGS entries for a kit by creating a sale order, then generating an invoice.

When `l10n_ke_edi_oscu_stock` is installed, it overrides the `invoice_policy` of all storable
products for Kenyan companies to `'delivery'`.
https://github.com/odoo/enterprise/blob/82b736a283ed5ab3ad431a1cdbcedc1b8e3c2d7c/l10n_ke_edi_oscu_stock/models/product.py#L16-L21

Because the test removes a required component from the picking, the delivered quantity of the kit
is computed as 0. Since the kit's invoice policy is dynamically forced to `'delivery'` by the
localization, calling `_create_invoices()` raises a `UserError` as there are no delivered items
to invoice, failing the test on runbot.

Fix:
====
Ensure that kit product use an invoicing policy of 'Ordered Quantities' rather than the default
'Delivered Quantities'. This allows the test to proceed and correctly evaluate the core COGS
computation logic it was designed to check.

runbot-243342

closes odoo/odoo#280025

X-original-commit: 515f74868c9dcc95be63d37a5da463acd2d4ecdb
Signed-off-by: Adrien Widart (awt) <awt@odoo.com>
Signed-off-by: Farah Ahmed (ahmfa) <ahmfa@odoo.com>