[FIX] website_event: Avoid Falsy display name for website.visitor
A visitor link to a event registration but not link to a partner can end
up with a display name = False

```
ipdb> visitor.event_registration_ids
event.registration(4179110,)
ipdb> visitor.event_registration_ids.name
False
ipdb> visitor.event_registration_ids.partner_id
res.partner()
```

This has a nasty side effect to make the merge of leads links to those
visitor to crash and thus make the _cron_assign_leads crashing as well

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-19.3/odoo/addons/base/models/ir_qweb.py", line 787, in _render_iterall
    for item in frame.iterator:
  File "<16125>", line 2433, in template_crm_crm_lead_merge_summary_16125
  File "<16125>", line 1990, in template_crm_crm_lead_merge_summary_16125_content
  File "/home/odoo/src/odoo/saas-19.3/odoo/tools/safe_eval/runtime.py", line 659, in safe_call
    return callee(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, bool found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_render_mixin.py", line 555, in _render_template_qweb_view
    render_result = self.env['ir.qweb']._render(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/odoo/addons/base/models/ir_qweb.py", line 758, in _render
    return Markup(''.join(iterator))
                  ^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/odoo/addons/base/models/ir_qweb.py", line 885, in _render_iterall
    raise QWebError(qweb_error_info) from error
odoo.addons.base.models.ir_qweb.QWebError: Error while rendering the template:
    TypeError: sequence item 0: expected str instance, bool found
    Template: crm.crm_lead_merge_summary
    Reference: 16125
    Path: /t/div/t/blockquote/div[22]/div[5]/t
    Element: <t t-out="\', \'.join(lead.visitor_ids.mapped(\'display_name\'))"/>
    From: (16125, '/t/div/t/blockquote/div[22]/div[5]/t', '<t t-out="\\\', \\\'.join(lead.visitor_ids.mapped(\\\'display_name\\\'))"/>')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-19.3/addons/crm/models/crm_lead.py", line 1554, in _merge_opportunity
    opportunities_head._merge_log_summary(merged_followers, opportunities_tail)
  File "/home/odoo/src/odoo/saas-19.3/addons/crm/models/crm_lead.py", line 1738, in _merge_log_summary
    self.message_post_with_source(
  File "/home/odoo/src/odoo/saas-19.3/addons/mass_mailing/models/mail_thread.py", line 42, in message_post_with_source
    return super(MailThread, self.with_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_thread.py", line 2726, in message_post_with_source
    bodies = self.env['mail.render.mixin']._render_template_qweb_view(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-19.3/addons/mail/models/mail_render_mixin.py", line 565, in _render_template_qweb_view
    raise UserError(
odoo.exceptions.UserError: Failed to render template
```

This commit fallback to the parent class display name when the
event_registration name is empty
to avoid this traceback

Co-authored-by: Thibault Delavallée <tde-banana-odoo@users.noreply.github.com>