[FIX] point_of_sale, pos_[discount, sale]: prevent error on installing module
Currently a 'ParseError' arises when the user installs the
'pos_discount' and 'pos_sale' modules after deleting the 'Service' category in
'Invoicing'.

Steps to reproduce:
- Install 'Invoicing' application (without demo data)
- Invoicing > Configuration > Categories > Delete 'Services'
- Now install 'pos_discount' and 'pos_sale' modules

Traceback:
ValueError: External ID not found in the system: product.product_category_services

ParseError: while parsing /home/odoo/src/odoo/saas-18.1/addons/pos_discount/data/pos_discount_data.xml:4, somewhere inside
<record id="product_product_consumable" model="product.product">
            <field name="name">Discount</field>
            <field name="available_in_pos">False</field>
            <field name="standard_price">0.00</field>
            <field name="list_price">0.00</field>
            <field name="weight">0.00</field>
            <field name="type">consu</field>
            <field name="categ_id" ref="product.product_category_services"/>
            <field name="uom_id" ref="uom.product_uom_unit"/>
            <field name="default_code">DISC</field>
            <field name="purchase_ok">False</field>
        </record>

The error occurs because the user deleted the category and then installed
'pos_discount' and 'pos_sale' modules, which reference the missing product
category.

This commit resolves the error by providing a False value for the field if the
product category is missing.

sentry-6291223593

X-original-commit: 6a89c24c5bcc9d79cccda0633ef1af48495cba84