[FIX] account_edi_ubl_cii: prevent an error when generate an invoice
Currently, an error occurs when uploading an XML file to generate an invoice.

Step to produce:

- Install the 'account_edi_ubl_cii' module.
- Go to Invoicing / Customers / Invoices, And upload this XML file to generate
an invoice.

ZeroDivisionError: float division by zero

The issue arises because the '_find_value()' method returns a string value,
such as '0'. This value is converted to a float and assigned to the 'basis_qty'
variable then the system tries to divide a float number with 'basis_qty'(zero)
at [1],

Link [1]: https://github.com/odoo/odoo/blob/4f9e06a701224ef18819391ddd57e56830af52f9/addons/account_edi_ubl_cii/models/account_edi_common.py#L558

To resolve this, assign a default value of 1.0 to the 'basis_qty' variable when
'_find_value()' returns a '0' or any other invalid value.

Sentry-6180097960