[FIX] l10n_cl: do not post demo moves of non chilean partners
When several localization modules are installed at once (with demo data),
loading the chilean demo data fails and the chilean demo company ends up
without any accounting demo data.

Steps to reproduce:

- Install `l10n_cl` together with the other localizations and the
  enterprise addons, with demo data enabled

Issue:

Error while loading accounting demo data
ValidationError: Document types for foreign customers must be export type
(codes 110, 111 or 112) or you should define the customer as an end
consumer and use receipts (codes 39 or 41)

Analysis:

Demo methods will posts every move of the chilean company, not only
the ones prepared by the module.
In combination with other modules loading their own demo data it may
raise the said error.

runbot-945980

closes odoo/odoo#289541

X-original-commit: 27cc7ea15b6285c4548182db139aeeaae3163ac6
Signed-off-by: Andrea Grazioso (agr) <agr@odoo.com>