Cherry pick of d441eb3875ec7ad4e9566be559de1c37a99c0c3f failed
stdout:
Auto-merging addons/stock/models/stock_location.py
CONFLICT (content): Merge conflict in addons/stock/models/stock_location.py
Auto-merging addons/stock/models/stock_move_line.py

stderr:
15:28:28.543479 git.c:463               trace: built-in: git cherry-pick d441eb3875ec7ad4e9566be559de1c37a99c0c3f --strategy ort
error: could not apply d441eb3875ec... [FIX] stock: remove iteration on record set
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: