[FIX] event: prevent an error when open a event ticket with invalid url
Currently, an error occurs while opening an event ticket with an invalid URL.

Step To Produce:

Install the 'event' module.
And Open any booked event, click on 'Attendees', and open any record, Click on
'View Ticket' in chatter.
Copy the ticket URL and try to open this ticket URL without 'registration_ids'
which is included in it.

TypeError: EventController.event_my_tickets() missing 2 required positional
arguments: 'registration_ids' and 'tickets_hash'

An error occurs when the system tries to call a route
'/event/int:event_id/my_tickets'' without certain parameters at [1].

To handle this issue, provide a default value to the parameter of the route
method.

sentry-4952598215