[FIX] stock: prevent error when applying inventory date in stock
Currently, an error occurs when applying the inventory date in the Stock
reporting view.

Steps to Reproduce:
 - Install the stock module.
 - Go to Settings > Languages, add Arabic, and switch to it.
 - Go to Inventory > Reporting > Stock.
 - In the left-side panel, enter an Inventory at Date and click Apply.

ValueError: time data '٢٠٢٦-٠٩-٠٩ ٠٥:١٨:٠٠' does not match format '%Y-%m-%d %H:%M:%S'

After the [recent commit] that added a date picker to the Stock report
search panel, when a user enters a date using Arabic numerals, the text
is displayed from right to left [1]. This date is then added to the
context [2]. When computing the quantities, the date value from the
context [3] is passed to it, where it is converted to a datetime [4].
However, the conversion expects the date to use Latin numerals.
Since the date is in Arabic numerals, this raises the error.

This commit ensures that the date is serialized using serializeDateTime [5],
which also uses the UTC timezone and the Latin numbering system (latn)
as expected by the system.

[recent commit]: https://github.com/odoo/odoo/commit/52bfa5b9bebbcb4f8042daa183edc39865036605

[1]: https://github.com/odoo/odoo/blob/7ef98548726f36856d78c745679b14b0165803ba/addons/stock/static/src/views/search/stock_report_search_panel.js#L39-L40

[2]: https://github.com/odoo/odoo/blob/7ef98548726f36856d78c745679b14b0165803ba/addons/stock/static/src/views/search/stock_report_search_model.js#L52-L53

[3]: https://github.com/odoo/odoo/blob/7ef98548726f36856d78c745679b14b0165803ba/addons/stock/models/product.py#L146

[4]: https://github.com/odoo/odoo/blob/7ef98548726f36856d78c745679b14b0165803ba/addons/stock/models/product.py#L162

[5]: https://github.com/odoo/odoo/blob/7ef98548726f36856d78c745679b14b0165803ba/addons/web/static/src/core/l10n/dates.js#L552-L560

sentry-7629069474

closes odoo/odoo#287181

Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>