[FIX] website_sale: fix error when accessing shop page
Currently, an error occurs when user deletes all the variants of a product and
opens the website raises an error.

Steps to replicate:
- Install `website_sale`, open settings and turn on `Product Reference Price`
  and `Product Variants`.
- Create a new product `test` , give an attribute and 2 values.
- Click on the `Variants` smart button,  select all and delete.
- Publish this produce in website and open shop on website.

Error:
```
ValueError: Expected singleton: product.product()
```

Cause:
- Issue occurs after a recent addition of a feature that shows product's unit
  price on website (check [PR]).
- As the user deleted all the variants of the product `test`, when trying to get
  the unit price of the product's variants [1] causes this error to occur.

Solution:
- If the product doesnt have any variants we should get the unit price from the
  product template itself.

[PR]: https://github.com/odoo/odoo/pull/254309

[1]: https://github.com/odoo/odoo/blob/22ede9cd601f54ebf248a7ddace433746f066e68/addons/website_sale/models/product_template.py#L686

sentry-7635385579