[FIX] stock: prevent warehouse stock location to be scrap location
If a user using inventory sets an internal location which is Location Stock
of the Warehouse as Scrap Location and then activattes module
mrp would face ParseError.

Steps to produce:
- Install `stock`.
- Inventory > Configuration > Settings > Under Warehouse check Storage Locations.
- Inventory > Configuration > Warehouse Management > Locations > Choose WH/Stock
as location and check Is a Scrap Location.
(A user can check it as scrap location only when when there are 0 delivery
orders to process so unreserve all the products associated to that location).
- Install 'mrp'.

Error: `ParseError`

This commit won't allow users to  scrape Warehouse Location
Stock as a Scrap Location.`

Sentry-4247161969