[FIX] auth_signup: logged on change password no traceback
Scenario: log in > My Account > Connection & Security > change your
password

Result:

The page is reloaded and the password is changed, but before that, there
is a traceback with:

TypeError: Cannot read properties of null (reading 'disabled')
  at Signup.onSubmit (/auth_signup/static/src/interactions/signup.js:14)

Issue: the signup interaction is also being run on the logged-in
password change form (portal.portal_my_security) when it should only be
run on login (web.login) or logged-out password reset
(auth_signup.reset_password).

opw-4671226

closes odoo/odoo#203725

Signed-off-by: Florian Vranckx (flvr) <flvr@odoo.com>