[FIX] spreadsheet: fix getFiltersMatchingPivot for no records
Task Description :

When right-clicking on a cell in a pivot with no matching records
and a positional argument, we get the following exception :

TypeError: Cannot convert a Symbol value to a string

This is coming from the fact we try the get the nth records
associated to the positional argument, but in a case where
there is no associated records.

Reproducibility:

This issue can be reproduced with the following steps :
1. Open a pivot
2. Change some cell to add a positional argument
3. Set a filter so that no related records can be found
4. Right-click on the previously changed cell

Related Task:

task-3009982

closes odoo/odoo#102450

Signed-off-by: Pierre Rousseau (pro) <pro@odoo.com>