[FIX] board: empty dashboard fails to render on mobile
Steps to reproduce
==================

- Go on a 14.0 runbot
- Open dashboard

```
TypeError: Cannot read properties of undefined (reading 'split')
    at Class.changeLayout
```

Cause of the issue
==================

`.oe_dashboard` isn't rendered on an empty dashboard

opw-3469183

X-original-commit: bc51651a0012644a1a9149fa6be1fb40c3a63686