[FIX] account: Skip archived company
Description of the issue/feature this PR addresses:

**Description:**
- During migration, tax compensation journal entries may be recreated for archived companies.
- While posting these [entries](https://github.com/odoo/upgrade/blob/2dd0730d914bd2555d21c0158e31a7630a04b4c0/migrations/account/saas~18.5.1.4/post-remove-tax-tag-invert.py#L69), the company consistency validation compares the move companies with the account companies from [here](https://github.com/odoo/odoo/blob/e3b0ca11d99b2ef819cdad68b169112cd73668b6/addons/account/models/account_move.py#L5612). causing false company mismatch errors such as: The entry is using accounts (...) from a different company.

Traceback (most recent call last):
  File "/home/odoo/src/odoo/19.0/odoo/service/server.py", line 1544, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'], reinit_modules=config['reinit'])
  File "/home/odoo/src/odoo/19.0/odoo/tools/func.py", line 88, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/19.0/odoo/orm/registry.py", line 199, in new
    load_modules(
  File "/home/odoo/src/odoo/19.0/odoo/modules/loading.py", line 464, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/19.0/odoo/modules/loading.py", line 230, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/19.0/odoo/modules/migration.py", line 215, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, version)
  File "/home/odoo/src/odoo/19.0/odoo/modules/migration.py", line 253, in exec_script
    mod.migrate(cr, installed_version)
  File "/tmp/tmpym5q01_g/migrations/account/saas~18.5.1.4/post-remove-tax-tag-invert.py", line 69, in migrate
    ).action_post()
  File "/tmp/tmpym5q01_g/migrations/util/orm.py", line 464, in caller
    return [getattr(chnk, attr)(*args, **kwargs) for chnk in chain(it, self._end())]
  File "/tmp/tmpym5q01_g/migrations/util/orm.py", line 464, in <listcomp>
    return [getattr(chnk, attr)(*args, **kwargs) for chnk in chain(it, self._end())]
  File "/home/odoo/src/odoo/19.0/addons/account/models/account_move.py", line 6091, in action_post
    self._post(soft=False)
  File "/home/odoo/src/odoo/19.0/addons/account/models/account_move.py", line 5618, in _post
    raise UserError(msg)
odoo.exceptions.UserError: The entry is using accounts (ACHAT MARCHANDISES INTRA) from a different company.

Current behavior before PR:

- The company mismatch validation also compares archived companies. After filtering inactive companies, empty company sets may incorrectly raise false company mismatch errors.

Desired behavior after PR is merged:

- The validation now only compares active companies and ignores empty/archived company sets, preventing false mismatch errors during migration posting.

Here is the upgrade PR for more info: [10334](https://github.com/odoo/upgrade/pull/10334)
OPW : 6236672
UPG : 4293633
TBG : 2745