[FIX] l10n_in: fix template code traceback
Previously, the template code was directly checked with `startswith('in')`,
which caused a traceback when no template code was there.

In this commit, the template code is checked first, and `startswith('in')` is
only called when a template code is available.

error: https://runbot.odoo.com/odoo/runbot.build.error/947112