[FIX] base: prevent crash on uninstall when checking undeletable module data
PR https://github.com/odoo/odoo/pull/72802 introduced an additional `record.exists()` check to revalidate xmlids that were previously undeletable, in case they became deletable after a model or field was dropped. This prevents orphaned `ir.model.data`.

However, calling `.exists()` on a record whose underlying table has  already been dropped raises some Errors.

Steps to reproduce:
-------------------

1. Install a module such as `account`.
2. Uninstall the module.
3. During uninstallation, the sanity check queries `record.exists()` for `ir.model.data` entries pointing to models whose tables have already been dropped.
4. This causes a crash:
```
    2025-09-24 11:32:50,424 486370 ERROR v16e_account odoo.sql_db: bad query:
    SELECT "account_account_tag".id FROM "account_account_tag" WHERE "account_account_tag".id IN (1)
    ERROR: relation "account_account_tag" does not exist
    LINE 1: SELECT "account_account_tag".id FROM "account_account_tag" W...
```

Fix:
----
Before calling `record.exists()`, we now ensure that the underlying table still exists (via `tools.table_exists()`). If the table is missing, the record is considered deleted and its `ir.model.data` entry is cleaned up.