[FIX] tools: TypeError when looking up image mimetype
Currently on SaaS it is not possible to import field image_1920 from a
as the operation fails

Steps to reproduce:
- Have python-magic library installed
- Products > Import records
- Upload a file containing an URL as image_1920
- Test upload

Upload fill fail with error
`Could not retrieve URL: <img-url> [image_1920: L1]: argument 2:
TypeError: wrong type`

Investigation:
It occurs because the python-magic library does not work with bytearray

opw-5004768

closes odoo/odoo#222482

Signed-off-by: Julien Castiaux (juc) <juc@odoo.com>