[FIX] bus: prevent error while receiving lastNotificationId as undefined
Currently an error occurs when the user reconnects after a network
interruption during login process.

Steps to replicate:
- Open an incognito tab browser and open the login page.
- Input credentials, and during the login process go to offline.
- Again, go online, and after a few times, an error will occur.

Note:- If an error does not occur, close the window and open a new one, try
offline and online again.

Error:
`BusController.has_missed_notifications() missing 1 required positional
argument: 'last_notification_id'`

This error occur because at code line [1]  the `lastNotificationId` is still
undefined (due to the network  interruption). This results in the client calling
`/bus/has_missed_notifications` with an invalid or missing parameter, causing
the controller to raise a `TypeError` due to a missing required argument.

This commit will fix above issue by providing a default value for
`last_notification_id` as 0, so that the field is always  present before making
the RPC call to `/bus/has_missed_notifications`.

[1]-https://github.com/odoo/odoo/blob/18.0/addons/bus/static/src/outdated_page_watcher_service.js#L55

sentry-5741581459