[FIX] account: fix inexistent attachment_ids when sending invoice
- Install Invoicing
- Create an invoice
- Post invoice and send it
An AttributeError is raised:
"AttributeError: 'account.move' object has no attribute 'attachment_ids'"

"attachment_ids" field is not available on "account.move" in Invoicing.
It is declared in Accounting.

opw-2413574
opw-2413310

X-original-commit: 685fbbb621ee3d93c66d92398916a6366c47b824