[FIX] mrp: missed update for workorder creation
Issue
----

When an `mrp.production`'s work orders are re-computed by
`_compute_workorder_ids`, the function may delete some of the previous
work orders that became obsolete, and either create new ones or update
existing ones. However, it doesn't take into account the deleted work
orders when choosing whether to update or create a work order.
So it ends up issuing an update command after a delete command for the
same order. This happens during splitting and causes work orders to
disappear, resulting in division by zero errors.

Steps
-----

 - Open Manufacturing -> Create a storable product and a BoM for this
   product.
 - Create a product as part of the BoM.
 - For the latter product, create another BoM that is a kit.
 - Create an operation in the BoM of the kit.
 - Create a manufacturing order for the storable product (first created
   product).
 - Set a quantity larger than 1, say 10, and manually save the MO
   (without confirming it).
 - Split the MO into same quantity (e.g. 10), and after confirming the
   split the following traceback is triggered:

`remaining_qty = initial_workorder_remaining_qty[index % workorders_len]
> ZeroDivisionError: integer division or modulo by zero`

opw-3994583

X-original-commit: b48615cdb75572f613242cdeb6d88b34194e84e5