[IMP] tiktok social media icon as optional to avoid errors
When compiling with a custom theme the selector can't find the element, and since there is no field nor XML placeholder in the social media icons template for the social media TikTok it fails to recognize the empty element and displays the following error:

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: The target selector was not found.
       Use "@extend .text-tiktok !optional" to avoid this error.
        on line 24065 of stdin
>>         }