[FIX] sale_gelato: fix crash when receiving order cancelation webhook
After an order is canceled on Gelato, we receveive a webhook with an
`fulfillmentStatus` of `cancel` and while processing it, it crash with:

```
ValueError: External ID not found in the system: sale.mail_template_sale_cancellation
```

The mail template used to notify the status change has been removed in
odoo/odoo@2c858ed15e50, so instead we simplify log the information on
the sale order chatter.

opw-5110226

closes odoo/odoo#230121

Signed-off-by: Antoine Vandevenne (anv) <anv@odoo.com>