[FIX] base, test_orm: avoid non-stored fields in default Calendar view
Steps to reproduce:
- Install `hr` and `web_studio`
- Go to Employees → click Studio icon.
- Click on Views → try to activate Calendar view.

Observation:
- You will get a traceback
  ValueError: Cannot convert hr.version.date_end to SQL because it is not stored

Issue:
- Since saas-18.4, the `hr_version` model introduced `date_start` and `date_end`
  fields, which are non-stored computed fields.
- These field names overlap with the default date field names (`date_start` and
  `date_end`) used when generating Calendar views. So, the Calendar view tried
  to use a non-stored field, and it caused the error.

Solution:
- Add an extra check in `set_first_of` to ensure that only stored fields are
  considered when selecting the default date field for Calendar views.

opw-4967654

closes odoo/odoo#225847

X-original-commit: 12f4f918e21aa76908b2b26525da16fc3fe3a65d
Signed-off-by: Lucas Perais (lpe) <lpe@odoo.com>
Signed-off-by: Dhwani Patel (dwa) <dwa@odoo.com>