[FIX] website: prevent error when submitting customized contact form
Currently, an error occurs when a user submits the customized Contact Us form.

Steps to Reproduce:
 - Install the website module.
 - Replace the Contact Us form with a customized form that does
   not contain the email_to field.
 - Go to Website > Contact Us page and submit the form with required details.
 - Error is logged in terminal.

KeyError: 'website_form_signature'

After [this commit], which changed the signature verification behavior for
forms inside HTML fields to protect the email_to(hidden field) in
mail.mail website forms from being modified by users. Since users are
allowed to customize the Contact Us form, they can remove the hidden
email_to field. In that case, the creation of website_form_signature is
skipped [1]. When the model is mail.mail, website_form_signature is
required for security. As a result, the controller attempts to retrieve it
from kwargs [2], which raises an error when it is missing.

This commit ensures that when website_form_signature is missing
from kwargs, it is handled gracefully by raising AccessDenied, consistent
with the existing behavior for an invalid signature.

[this commit]: https://github.com/odoo/odoo/pull/143139/changes/43cdff6577ddc906e89592494667e2f59ddca864

[1]: https://github.com/odoo/odoo/blob/4d8f0c68bab3da76d186d00e74ba0f69f731808a/addons/website/tools.py#L140-L141

[2]: https://github.com/odoo/odoo/blob/4d8f0c68bab3da76d186d00e74ba0f69f731808a/addons/website/controllers/form.py#L75-L77

sentry-7336816357