[FIX] account: remove tax groups not belonging to selected companies in COA
Currently, an error is produced on creating/saving the record of the chart of
account if the company of any tax belongs to a company which company is
not in the allowed Companies.

**Steps to reproduce:**
- Install the `accountant` and `l10n_be` modules.
- Activate the **IN Company** and keep **YourCompany** as the default.
- Navigate to `Accounting > Configuration > Accounting > Chart of Accounts`.
- Open the new form view of the model by clicking the **view** button.
- In **Companies** field, select the **IN Company**.
- Select the **5% GST** tax in **Default Taxes** field.
- Now, remove the **IN Company** from the **Companies** field.
- Attempt to save the record.

**Error:**
`AttributeError: 'account.account' object has no attribute 'company_id'`

Here, the `_check_company` method at [1] verifies that all relational fields
(such as tax groups) belong to the selected companies. While building the user
error message, it assumes that all involved records (e.g., `account.account`)
have a `company_id` field. However, `account.account` does not define
`company_id`, which results in an attribute error.

[1] - https://github.com/odoo/odoo/blob/887f3fa98f6172dc5d35f9981d43d6ccb4cf86dc/odoo/models.py#L4396

This commit added constraint that raises a **UserError** if any tax in the
**Default Taxes** field belongs to a company not included in the selected
**Companies**. This prevents errors during the company check.

Sentry - 6636043482