Cherry pick of 1e21ed4cd6c6434ea28c04a4dfb4736d5fc9605e failed
stdout:
Auto-merging addons/account/models/partner.py
CONFLICT (content): Merge conflict in addons/account/models/partner.py

stderr:
17:43:24.049103 git.c:463               trace: built-in: git cherry-pick 1e21ed4cd6c6434ea28c04a4dfb4736d5fc9605e
error: could not apply 1e21ed4cd6c6... [IMP] account: make inheritable region base domain used to get fiscal position
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: