[FIX] hw_scale: added field 'disable' to namedtuple 'ScaleProtocol'
Introduced at bb015818eaf
Getting error
TypeError: __new__() got an unexpected keyword argument 'disable'

closes odoo/odoo#28202