[FIX] Point_of_sale: Prevent multiple refunds in a single transaction
After the fix, when selecting multiple refunds not belonging to
a same order, a user error will appear, preventing an odoo
error later in the flow..
_____________________________________________________
Selecting several refunds from the same customer in the same transaction, and making sure to print an invoice at every operation caused an error.

1. Go to the point of sales module, and create an order for a specific customer. Proceed to the payment and make sure that finalizing the payment will create an invoice, before confirming the payment.
2. Create a second order for the same customer, and proceed the same way as in step 1.
3. On the product screen, click on "refund".
4. Select one order that you've just completed. Then, setup the quantity at 1 and click on refund.
5. Do step 4 again but this time, select the second order that you've just completed.
6. Click on payment, then click on invoice then try to validate the payment.

The error occurs:
Expected singleton: account.move(720, 722)
Traceback (most recent call last):
  File "/data/build/odoo/odoo/models.py", line 5896, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

It is due to an ensure_one() in python. Indeed, in the file point_of_sale/models/pos_order.py,in the function _prepare_invoice_vals(self), an error occured on the line:

vals['ref'] = _('Reversal of: %s', self.refunded_order_ids.account_move.name)

self.refunded_order_ids.account_move.name is supposed to be a singleton, but in the case where a transaction has several refund order, this isn't the case anymore, causing the error.

 ## Explanation of the fix

After the fix, when you select a second refund after selecting one, the previous one will be replaced by the current one, preventing users to select 2 refunds in the same transaction. In the code, this is translated as:
in the point_of_sale/static/src/app/screens/ticket_screen.js file, in the onDoRefund() function, when a refund (= orderline) is created, we check that there are less than 2. If not, we remove the previous ones.
______________________________________________________________
opw-4791231