[FIX] account: prevent an error when archiving multiple journals
This Error occurs when a user tries to archive multiple journals.

Steps to reproduce:

- Install the 'account' module
- Go to Invoicing / Configuration / Accounting / Journals.
- Select two or more journals and try to archive them.

ValueError: Expected singleton: account.journal(15, 18)

An error occurs at [1] because the system attempts to retrieve the id from
'self', which contains multiple records.

link [1]:https://github.com/odoo/odoo/blob/1f7debc24bab4e0a7f2ef0d85e50d9381e1826cd/addons/account/models/account_journal.py#L801

To resolve this issue, Use an 'ids' instead of an id to get a multiple record.

Sentry-5917175119

X-original-commit: d2714fa73e7c70e4e68f94e5ef53acb16c9e9fa9