[FIX] base: fix dependency error on distros without ID_LIKE assignment
Steps to replicate:
- Try installing odoo without some external dependency on a linux distro
  that does not assign ID_LIKE os-release variable.

Error:
- AttributeError: 'NoneType' object has no attribute 'split'

Cause:
- Default value None does not work here as it does not have a split()
  method.

Solution:
- Default is now an empty string instead of None.