[FIX] stock: auto-reserve after last step of multi-step receipt
The auto-reserve feature does not work if the products are received in
several steps

To reproduce the issue:
1. In Settings, enable "Multi-Step Routes"
2. Edit the existing warehouse:
    - Incoming Shipments: 2 steps
3. Create a storable product P
4. Create and confirm a SO with 1 x P
    - The delivery D is created and is waiting for one available P
5. Create and validate a receipt for 1 x P
    - An internal transfer T is generated (Input -> Stock)
6. Validate T
7. Open D

Error: The delivery is still waiting for the product while this product
should be reserved. This is correctly working in 1-step receipt

In 1-step receipt, when the user marks the receipt as done, the
destination of the associated SM is WH/Stock and its operation type code
is "incoming". Therefore, the module checks if some other moves (from
WH/Stock) can reserve the newly-available quantity.
However, in [2/3]-steps receipt, the operation type code of the
in-WH/Stock move is "internal". So, the conditions are not respected and
the module doesn't check the needs of reservation.

OPW-2806423

closes odoo/odoo#90715

Signed-off-by: Tiffany Chang <tic@odoo.com>