[FIX] mail, account: prevent error when sending invoices in batch
Currently, an error occurs when sending invoices in bulk.

Steps to Reproduce:
 - Install the account module.
 - Go to Email Templates and open Invoice: Sending.
 - In the Email Configuration, uncheck Default Recipients and enter
   demo@gmail.com in the cc field.
 - Go to Invoices.
 - Select multiple invoices and click Send.

KeyError: <NewId origin=33>

This error occurs when sending invoices in bulk. As mentioned in commit
058d324,
the issue was introduced in commit
39d1907, where
the _compute_alerts method attemptsto set an alert in the wizard. However,
since this is a computed field, the wizard record has a NewId and calls the
method with a transient record [1]. When trying to access record.id,
it returns a NewId [2], and later, when this NewId is used as a res_id [3],
it raises a KeyError.

[1]-https://github.com/odoo/odoo/blob/aff5f006d5b1996ea3ecc67998067cd0e292cf2a/addons/account/wizard/account_move_send_batch_wizard.py#L63

[2]- https://github.com/odoo/odoo/blob/c70bca77d0447b005b3898e1861facc2828475fc/addons/mail/models/mail_thread.py#L2037

[3]- https://github.com/odoo/odoo/blob/c70bca77d0447b005b3898e1861facc2828475fc/addons/mail/models/mail_thread.py#L2084

This commit fixes the above issue by using move_ids._origin, ensuring that
the method is always called with real records, and removes the changes
from the previous commit https://github.com/odoo/odoo/commit/058d324855a6e2fe3df51386aa153d46419766bf.

sentry-6562659542

X-original-commit: fc5912f267d25465ac9958fb46c4387dc99c95c4