[FIX] website_sale: prevent error when paying for cart via express checkout
Currently, an error occurs when user makes payment through express
checkout on the website.

Steps to Reproduce:
 - Install the website_sale_loyalty module.
 - Install Demo payment provider.
 - Go to website > Shop > Add a product to the cart.
 - View cart > Pay with Demo > Pay.
 - Click the back button (Chrome navbar)
 - Now, click 'Pay with Demo' > Pay again.

ValueError: Expected singleton: sale.order()

The error occurs after this commit bf8d08c,
which overrides method [1] to include the delivery discount, if any.
If order_sudo is empty, it raises this error[2].

This commit ensures that if order_sudo is not present, a UserError
is raised with an appropriate message.

[1]: https://github.com/odoo/odoo/blob/74a8334558bf86c07c0d68090a9126911867ef42/addons/website_sale/controllers/delivery.py#L160

[2]: https://github.com/odoo/odoo/blob/74a8334558bf86c07c0d68090a9126911867ef42/addons/website_sale_loyalty/controllers/delivery.py#L18

sentry-6759936549