[FIX] product_margin: prevent error when applying Group by on product margins
When there is no product in the database and user applies Group By
on product margins, a traceback will appear.

Steps to reproduce the error:
- Create a database without demo data
- Install "Accounting" module
- Go to Accounting > Configuration > Settings > Enable Margin Analysis
- Go to Accounting > Reporting > Product Margins > Click on Open Margins
  > Group By > Select any Group

Error: A traceback appears:
"SyntaxError
syntax error at or near ")"
LINE 35:                 WHERE l.product_id IN ()"

https://github.com/odoo/odoo/blob/b548452b78c2e5231730f673b263ba92ce036d3b/addons/product_margin/models/product_product.py#L142-L152
Here, when there is no product in the database,
So, self.ids will be [].
So it will lead to the above traceback.

sentry-5860443914