[FIX] l10n_gcc_invoice: prevent AttributeError while printing invoice
When the user tries to print the invoice for the Saudi company,
a traceback will appear.

Steps to reproduce the error:
- Install "l10n_sa"
- Switch to "SA Company"
- Create a new invoice > Confirm > Print the invoice

Error: A traceback appears:
"AttributeError: 'res.lang' object has no attribute '_lang_get_direction'"

https://github.com/odoo/odoo/blob/382e79857535cc0a404a8f70fbef071b79afea86/addons/l10n_gcc_invoice/views/report_invoice.xml#L285
Here, "_lang_get_direction" method is still used,
this method is replaced by "_get_data" method in commit odoo@9f5470f.

sentry-5596797662