Cherry pick of 3b5216f102decd6a7bd710c406bcba34cd97e378 failed
stdout:

stderr:
error: could not apply 3b5216f102d... [FIX] hr_holidays: Create leave in batch
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'