[FIX] hr_expense: prevent error when split an expense
Currently, an error occurs when users press the data-hotkey 'ALT + Q' to split
expense and any expense is not available in the split expense line.

Step to produce:

- Install the 'hr_expense' module.
- Create an expense, add a category, and click on the 'Split Expense' button.
- Delete all expenses from the split expense line, and press the data-hotkey
'ALT + Q' to click on the 'Split Expense' button to split expenses.

IndexError: tuple index out of range

This occurs because the system attempts to access the first expense from the
split expense line [1], but expenses are not available.

Link [1]: https://github.com/odoo/odoo/blob/280b762e7cd1b3d9a578bbae60cbb9b137ee5ce5/addons/hr_expense/wizard/hr_expense_split_wizard.py#L36

To resolve this issue, Disable a 'Split Expense' button after simply adding a
`disabled` attribute on it.

Sentry-6015854429

Part-of: odoo/odoo#194564
Signed-off-by: Aaron Bohy (aab) <aab@odoo.com>
Signed-off-by: Meet Gandhi (mega) <mega@odoo.com>