[FIX] sale: prevent error on clicking Edit Configuration
Currently, when a user adds a configurable product to an order line,
and remove the name of product and click on `Edit Configuration` (pencil icon)
error is encountered.

Steps to Reproduce:
- Install Sales module
- Create a Quotation
- Add a product(e.g Acoustic Bloc Screen), then only remove the name from the
  orderline and click on edit button(pencil Icon).

Error:
`TypeError: SaleProductConfiguratorController.sale_product_configurator_get_values()`
 `missing 1 required positional argument: 'product_template_id'`

Root Cause:
When a user clicks on Edit configuration, the client-side JavaScript makes an RPC
call to the server, targeting the `sale_product_configurator_get_values`. which
expects product_template_id at [1] and since it is removed from order line
the error is encountered.

[1]- https://github.com/odoo/odoo/blob/1b657cf1e1ce43874a3ede307b2f8ad68216aa56/addons/sale/controllers/product_configurator.py#L11-L13

Solution:
This commit prevents the error by adding a check to verify a product is selected
before allowing its configuration to be edited.

Sentry-5741581459