[FIX] osv: logger error to warning for searching non stored fields
When user tries to search non-stored fields in searchbar, the logger error will
occur.
Logger error is changed to warning, so it will reduce the noise in sentry.

Error: "Non-stored field stock.move.lot_ids cannot be searched."

sentry-4239766984