[FIX] orm, test_import_export: prevent error when exporting Property fields
Currently, an error occurs when exporting the product record.

Steps to Reproduce:

Install the stock module.

 - Go to any product and click the Edit Properties in the Actions.
 - In the new property field, enter any value.
 - In the list view, select that product and click Export from the Actions.
 - In the Available Fields section, search for Properties, add them, and
   click Export.

TypeError: Unsupported type <class 'odoo.orm.fields_properties.Property'> in write()

This error occurs when a user exports a product record and includes Properties
in the wizard. The 'Properties' field is a dynamic field that maps to
fields.Property, which is not supported by the export mechanism.
As a result, a TypeError is raised.

This commit ensures that if the export value is an instance of Property,
then convert_to_export returns its exportable values.

sentry-6618087979

closes odoo/odoo#213660

X-original-commit: b28e6adae73a09a7534d918d856ed55d9d71f9da
Signed-off-by: Raphael Collet <rco@odoo.com>