[FIX] partnership: fix view inheritance
The `partner_pages_tree_view` was attempting to modify `activity_ids` field attributes, but this field is added by the mail module in a sibling inheritance branch ([mail.res_partner_view_tree_inherit_mail]), making it unreachable from the [`partnership.view_res_partner_grade_tree`] ancestry chain:
```py
  base.view_partner_tree → partnership.view_res_partner_grade_tree → partner_pages_tree_view
  base.view_partner_tree → mail.res_partner_view_tree_inherit_mail ← activity_ids lives here
```
This caused a ParseError during base module upgrade:
```py
  File "/home/odoo/odoo/odoo/odoo/tools/convert.py", line 639, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing /home/odoo/odoo/odoo/odoo/addons/base/views/res_partner_views.xml:13
Error while parsing or validating view:
Element '<field name="activity_ids">' cannot be located in parent view
View error context:
{'file': '/home/odoo/odoo/odoo/odoo/addons/base/views/res_partner_views.xml',
 'line': 1,
 'name': 'Partner Pages List',
 'view': ir.ui.view(2148,),
 'view.model': 'res.partner',
 'view.parent': ir.ui.view(2108,),
 'xmlid': 'website_crm_partner_assign.partner_pages_tree_view'}
```

**Steps to reproduce:**
- In a v19.1 db install `website_crm_partner_assign`
- Go to apps and search base module and click upgrade

**Fix:**
Make the partner view from partnership inherit from the one defined in mail instead of the one defined in base. 

opw-6186684

[mail.res_partner_view_tree_inherit_mail]: https://github.com/odoo/odoo/blob/saas-19.3/addons/mail/views/res_partner_views.xml#L58C21-L67
[`partnership.view_res_partner_grade_tree`]: https://github.com/odoo/odoo/blob/f3b317310b84edb073009f7d15d7fec002f3ccf0/addons/partnership/views/res_partner_views.xml#L48-L57

closes odoo/odoo#265289

Forward-port-of: odoo/odoo#264639
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>