Cherry pick of 5e8647cddac7653ff6efd262f4aefcd30ce0fafa failed
stdout:
Auto-merging odoo/addons/base/models/ir_actions_report.py
CONFLICT (content): Merge conflict in odoo/addons/base/models/ir_actions_report.py
Auto-merging odoo/tools/pdf.py

stderr:
16:36:31.468751 git.c:463               trace: built-in: git cherry-pick 5e8647cddac7653ff6efd262f4aefcd30ce0fafa
error: could not apply 5e8647cddac7... [IMP] base: adapt for PyPDF2 >= 2.0.0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: