[FIX] l10n_ch: rename conflicting identifier of account data
l10n_ch depends on l10n_multilang.

Presence of account template with identifier 'transfer_account_id'
contradicted with the template having same identifier in l10n_generic_coa
while processing COA translations if any of the spoken languages
loaded before the install of l10n_ch.

The mentioned identifier for Belgium, Canada, and Saudi Arabia localizations
does not exist (i.e. no duplicity) which was verified, as these localizations
also does depend on l10n_multilang.

The below mentioned traceback could be generated without this commit
with the following steps:
 1. Install 'Invoicing Management' app.
 2. Enable multi company and switch to the newly created company.
 3. Load German (CH) / Deutsch (CH) translation.
 4. Attempt to install module with technical name l10n_ch.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/comunity/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/comunity/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo/comunity/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo/comunity/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/comunity/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/comunity/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/comunity/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/comunity/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/comunity/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/comunity/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/comunity/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/comunity/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo/comunity/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/home/odoo/odoo/comunity/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/odoo/comunity/odoo/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/odoo/comunity/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/odoo/comunity/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/comunity/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/odoo/comunity/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/odoo/comunity/odoo/modules/loading.py", line 200, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "<string>", line 30, in post_init
  File "<string>", line 10, in load_translations
  File "/home/odoo/odoo/comunity/addons/l10n_multilang/models/l10n_multilang.py", line 65, in process_coa_translations
    chart_template_id._process_accounts_translations(company.id, langs, 'name')
  File "/home/odoo/odoo/comunity/addons/l10n_multilang/models/l10n_multilang.py", line 77, in _process_accounts_translations
    return self.process_translations(langs, field, in_ids, out_ids)
  File "/home/odoo/odoo/comunity/addons/l10n_multilang/models/l10n_multilang.py", line 39, in process_translations
    out_ids[counter].ids,
  File "/home/odoo/odoo/comunity/odoo/models.py", line 4824, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range