[FIX] purchase: prevent deletion of UoM when it is in use
When a user deletes the UoM used in a purchase order line and then tries to
confirm the purchase order.

Steps to reproduce:
- Install 'purchase' module(without demo)
- Enable 'Units & Packagings' and Create a New UoM
- Create a New PO > Add a product in Line (with UoM=Units)
- Now go to selected product > 'Purchase' page -> Select 'Vendor' and set UoM
  to newly created UoM
- Now in PO order line change UoM to newly created UoM
- Now remove 'Vendor' and delete newly created UoM
- Orders > Requests for Quotation > Open PO > 'Confirm Order'

Traceback:
ValueError: Expected singleton: uom.uom()
ZeroDivisionError: float division by zero

This error occurs because, after the UoM is deleted, the 'product_uom_id' field
becomes empty, which leads to an error.

Solution:
This commit resolves the error by restricting the deletion of a UoM when it is
still in use.

sentry-6746792383

X-original-commit: 69427695b23feb52fc8bd574031b27412a808a8a