[FIX] account: prevent error when paying an invoice
Currently, an error occurs when a user attempts to pay an invoice.

Steps to Reproduce:

 - Install the Accounting module.
 - Go to Payment Terms and create a new Payment Term with at least two
   Due Term lines.
 - Go to Invoices and create a new Invoice.
 - Add one invoice line and set the Payment Term to the newly created
   payment term.
 - In the Journal Items tab > Enable the Due Date column (optional hidden).
 - From the two Receivable journal items, remove the Due Date from one
   of the receivable lines.
 - Now Confirm the invoice and Click on Pay.

TypeError: '<' not supported between instances of 'datetime.date' and 'bool'

This error occurs when the user clicks Pay, than it going to calculate the
total amount to pay from here [1]. If the payment term has more than
one term line, it creates more than one receivable invoice line, and the
receivable invoice lines are sorted from here [2]. When two or more
invoice lines have the same move_id, they are sorted based on the due date.
However, if one of the receivable lines does not have a due date,
the error is raised.
Similarly, as shown in [3], when the system retrieves the installment data,
it sorts the lines based on the due date and raises the same error.

This commit ensures that when there is no due date on any receivable
invoice line and two lines belong to the same invoice, the comparison
uses the maximum date as like here [4] and places that line at the end
for that invoice, thereby maintaining the correct flow. The same fix is
applied while retrieving the installment data, as described above.

[1]: https://github.com/odoo/odoo/blob/92a9f6b19670685dfe9fb1714bf01449768e5f62/addons/account/wizard/account_payment_register.py#L703

[2]: https://github.com/odoo/odoo/blob/92a9f6b19670685dfe9fb1714bf01449768e5f62/addons/account/wizard/account_payment_register.py#L635

[3]: https://github.com/odoo/odoo/blob/92a9f6b19670685dfe9fb1714bf01449768e5f62/addons/account/models/account_move_line.py#L3305

[4]: https://github.com/odoo/odoo/blob/92a9f6b19670685dfe9fb1714bf01449768e5f62/addons/account/models/account_move_line.py#L522

sentry-713241246

X-original-commit: e07df7c6556b30635aa3f796df1bd870224fb1a0