[FIX] sms: fix traceback on insert field click in readonly state
Steps to reproduce
----------------------------------------
1. Install the SMS Marketing module (mass_mailing_sms).
2. Open any SMS Marketing record in the "Sent" or "Sending" stage.
3. Click on the "Insert Field" button.

Observation
----------------------------------------
Traceback Occurs:
```
TypeError: Cannot read properties of null (reading 'getRootNode')
```

Issue
----------------------------------------
The SMS widget displays the "Insert Field" button even when the SMS message
field is readonly. The button relies on the textarea reference to open the
dynamic fields popover, but the textarea is only rendered in editable mode.

The readonly behavior of the text field can be seen here:
https://github.com/odoo/odoo/blob/ccce9fcc79edcfb1f310b49a16de8235d987b74b/addons/web/static/src/views/fields/text/text_field.xml#L5-L7

However, the SMS widget still renders the "Insert Field" button without
checking whether the message field is readonly:
https://github.com/odoo/odoo/blob/ccce9fcc79edcfb1f310b49a16de8235d987b/addons/sms/static/src/components/sms_widget/fields_sms_widget.xml#L6

As a result, clicking the button in readonly mode tries to access an
unavailable textarea reference to open the dynamic fields popover, causing
a traceback.

Solution
----------------------------------------
Hide the "Insert Field" button when the SMS message field is readonly,
preventing the dynamic fields popover from being opened when the textarea
reference is unavailable.

X-original-commit: 9ac06f2efd2d930dfaf7145aa5c944889e4c218b