[FIX] l10n_sa_pos: prevent error when creating consolidated POS invoices
Currently, an error occurs when trying to create a consolidated invoice for
multiple POS orders associated with the same customer.

Steps to reproduce:

- Install the l10n_sa_pos module and switch to the SA company.
- Create two POS orders for the same customer without invoicing at checkout.
- Close the POS session and go to Point of Sale > Orders.
- Select both orders > click Create Invoice > confirm the action.
  (Make sure Consolidated Billing is enabled)

Error:
ValueError: Expected singleton: pos.order(8, 7)

Root cause:
At [1], the code accesses `self.date_order` and `self.l10n_sa_reason`, but when
consolidated billing is enabled, self contains multiple POS orders, which
causes an error.

Fix:
This commit prevents the error by ensuring that the current datetime is
assigned when creating a consolidated invoice, same as [2].
For the refund reason, a fix similar to [3] has been applied.

[1]:
https://github.com/odoo/odoo/blob/0c87b6b8836522913dbe77b57a018ac26012edca/addons/l10n_sa_pos/models/pos_order.py#L17-L18

[2]:
https://github.com/odoo/odoo/blob/583bacdc8ad2b87b99b11d1e12dacf6e42edf22b/addons/point_of_sale/models/pos_order.py#L828-L832

[3]:
https://github.com/odoo/odoo/blob/0c87b6b8836522913dbe77b57a018ac26012edca/addons/l10n_es_edi_tbai_pos/models/pos_order.py#L103-L107

opw-5266908

X-original-commit: e3f2d71aa07368209f8cd1e61dbc2f6c1bf72e80