[FIX] base: prevent error when creating a new view
When the user tries to create a new view, a traceback will appear.

Steps to reproduce the error:
- Go to Settings > Technical > User Interface > Views > New

Error: A traceback appears:
'SyntaxError: syntax error at or near ")"
LINE 5:                 WHERE id IN () AND'

When the user creates a new view, self will be NewId in "_compute_warning_info",
so eventually in "_get_inheriting_views" method, self will be NewId,
so eventually self.ids will be [ ] here,
https://github.com/odoo/odoo/blob/855612ce254a4d4d547fc65b553b37c2876fcce2/odoo/addons/base/models/ir_ui_view.py#L611

so it will lead to the above traceback.

sentry-5675367115

closes odoo/odoo#176762

X-original-commit: 3548489ad1e6ba0a6072b13d0ee6031752f6a056
Signed-off-by: Rémy Voet (ryv) <ryv@odoo.com>