Cherry pick of b36bcfe2c2cb552d9b1a34bd6ead9849f26eea6b failed
stdout:

stderr:
error: could not apply b36bcfe2c2c... [IMP] calendar: faster recurring events search
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'