[FIX] stock: fix for TypeError: value.toFixed is not a function on BomOverviewTable caused by False value on quantity
closes odoo/odoo#145512

X-original-commit: 0969c13237fbe3b077a2298dab6aaecb7d80ec58
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>