[FIX] account: prevent traceback when accessing asset from a different company
Steps to reproduce :

1)Install Accounting and enable Analytic Accounting from configuration.
2) Create an analytic plan under Accounting > Configuration > Analytic Plans.
3) Add a line with domain set to miscellaneous,
   applicability as mandatory, and a prefix.
4) Create an analytic account using the smart button on the plan.
5) In a multi-company setup, create an asset record in one company.
6) Switch to another company and try to access asset created in first company.

Issue:
A traceback occurs
"AttributeError: 'bool' object has no attribute 'startswith'"

Cause:

When switching companies, all the chart of accounts records code
for the previous company, will set as False.

When accessing an asset record expects a account code
to call .startswith(), but it fails when code is False.
This leads to the above traceback.
https://github.com/odoo/odoo/blob/5a321b2327e36f3250b33c669bdb8bb344ab4cbd/addons/account/models/account_analytic_plan.py#L64-L67

Solution:
Add a check to ensure that the account’s code exists before attempting
to call .startswith().
This makes the code more robust across multi-company environments.

opw-4745633

X-original-commit: 88de499939c845eaee4ee435896c1a7da3c930b0