[FIX] l10n_ro_edi_stock: install the module
The test was failing when the module was not installed because it was
trying to access the auto_batch field but AttributeError: 'stock.picking.type' object has no attribute 'auto_batch'
, because we need to install the module to have the field available which is stock_picking_batch module.

build_error-115361

closes odoo/odoo#201438

Signed-off-by: Ricardo Gomes Rodrigues (rigr) <rigr@odoo.com>