[FIX] account: handle a key error
When executing the scheduled action 'payment: post-process transactions',
There's an issue where the system attempts to retrieve the
'pdf_attachment_values' key from the 'invoice_data' dictionary. However, This
key might be missing in certain cases,

Error: `KeyError: 'pdf_attachment_values' `

To create this scenario we have to set the 'Generate Peppol format by default'
field of the current company to 'true', After that open any invoice and
'confirm' it then go to its customer form view, After that Provide any value to
the 'Format' field which is in the 'accounting' section of 'res.partner'
form view. Go back to this invoice and click on the 'Send & Print' button. After
an open a wizard click on the 'Send & Print' button on it. Analysis reveals
that, In this process, the 'error' key is appended with the invoice_data
dictionary,  and method '_prepare_invoice_pdf_report' isn't invoked as we see
in [1], Thus the 'pdf_attachment_values' key is not appended with the
'invoice_data' dictionary[2].

This scenario may occur because the argument 'errors' is passed into
the '_generate_invoice_fallback_documents method' without including the
'pdf_attachment_values' key.[3].

Line [1]: https://github.com/odoo/odoo/blob/b5c229598aaea647f1d5d3c03bca64455e036e97/addons/account/wizard/account_move_send.py#L520-L528
Line[2]:https://github.com/odoo/odoo/blob/b5c229598aaea647f1d5d3c03bca64455e036e97/addons/account/wizard/account_move_send.py#L302-L322
Line[3]: https://github.com/odoo/odoo/blob/b5c229598aaea647f1d5d3c03bca64455e036e97/addons/account/wizard/account_move_send.py#L598-L600

To handle this situation, we can implement an if-else condition within
the '_hook_invoice_document_after_pdf_report_render' method. This condition will
ensure that the 'proforma_pdf_attachment_values' are passed when the
'pdf_attachment_values' key is absent in the 'invoice_data' dictionary.
This modification will handle situations where  the
'_generate_invoice_fallback_documents' method is invoked without
necessary key.

sentry-4323742571