[FIX] website_forum: removed chatter from forum post
Currently, an error occurs when user opens a forum post's form view.

Steps to replicate:
- Install `website_forum` with demo.
- Open the website, navigate to the Forums page, open any forum, and then
  open any post within that forum.
- Click on the `Forum Post` button next to the `New` button to open form view.

Error:
```
AttributeError: 'forum.post' object has no attribute '_get_thread_with_access'
```

Cause:
- The model `forum.post` doesnt inherit `mail.thread` anymore, it removed by
  this [PR].

- This causes the error to occur as the method `_get_thread_with_access` is in
  the `mail.thread` model.

Solution:
- Removed the chatter, it can only be used if the model inherits `mail.thread`.

[PR]: https://github.com/odoo/odoo/pull/209433/files#diff-9dc9697a1f14ce32ada7ce5b7dbdeca91124a06a43676e4fdf01f1c1909e1ec4L21

sentry-7609858049