[FIX] base: load demo data with a company and accounting
Usecase to reproduce:
- Install stock and accounting without demo data
- Load demo data

Current behavior:
RuntimeError: Module operations inside tests are not transactional and
thus forbidden...

It happens due to commit [1]. However when loading the demo data the
current thread has the attribute 'testing' set to True and prevent the
installation of new modules.

The solution would be to prevent the instalation of l10n when loading
demo data as before the patch

[1] 0d4fac7fe0a356cbaf40f71587c78765ce50fc1e

X-original-commit: 7fcba19860a52a0ed7267bb1ec9bfe2e31c5de71