[FIX] base_vat: prevent crash on invalid taiwan vat number
Steps to reproduce:

- Install the base_vat module.
- Navigate to Invoicing > Customers.
- Create a new contact and set the country to `Taiwan`.
- Enter `1234567A` as the Tax ID and try to save.

Error:
ValueError: invalid literal for int() with base 10: 'A'

Root cause:
At [1], `check_vat_tw` is missing validation to ensure that the
VAT number (without the country code) contains only digits, which
causes an error when calling the int() method on the VAT number.

Fix:
This commit prevents errors and ensures users receive a clear warning message.

[1]:
https://github.com/odoo/odoo/blob/23398d24e108875b2838715d4b366df265d53234/addons/base_vat/models/res_partner.py#L929-L958

No task Id

closes odoo/odoo#259936

X-original-commit: 99f31d239642b378cc918c4066cd8821f8485f53
Signed-off-by: William André (wan) <wan@odoo.com>
Signed-off-by: Utsav Maru (utma) <utma@odoo.com>