[FIX] purchase: planned date in different TZ
Depending on the TZ and the current time, the planned date of a PO may
be incorrect

To reproduce the issue:
1. Setup the server:
    - TZ: Australia/Sydney (UTC+11)
    - Time: 08:00 am
2. Create a PO:
    - Add a product (ensure the product doesn't have any lead time)

Error: The receipt date becomes the date of yesterday

The computation of `date_planned` is based on `date_order`, which is
UTC. Suppose current date is "2021-12-03 08:00 (UTC+11)": `date_order`
is `2021-12-02 21:00`. Therefore, in `_convert_to_middle_of_day`, when
combining the date of `date_order` and the time (12:00), the date day is
not the correct one (02 instead of 03)

Before combining the date and the time, we should first apply the
initial offset to ensure that the date day is correct

OPW-2689883

X-original-commit: 4b6b4a27dbca9d003c7fc07b0d6cf3891cd77369