[FIX] web: prevent error when uploading an svg
Currently an error occurs when user tries to upload a svg image as a logo in
document layout.

Steps to replicate:
- Initialize a db and open settings.
- Under the Document Layout section, click on `Configure Document Layout`.
- In the logo field add any SVG image.

Error:
```
  File '/home/odoo/odoo19/community/addons/web/models/base_document_layout.py', line 106, in _compute_logo_colors
    wizard.logo_primary_color, wizard.logo_secondary_color = wizard.extract_image_primary_secondary_colors(wizard_for_image.logo)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File '/home/odoo/odoo19/community/addons/web/models/base_document_layout.py', line 215, in extract_image_primary_secondary_colors
    base_w, base_h = image.size
                     ^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'size'
```

Cause:
- As user added an svg to the logo field, `tools.ImageProcess(logo)` tried to
  load the SVG which returned `self.image` as False because we dont process
  SVG or WEBP images [1].

- Later when we try to access `image.size` where image is false, we get error.

Solution:
- In earlier versions the method `base64_to_image()` was used [2], which raised
  an UserError on attempting `Image.open()` on a SVG.

- This error was caught by the try except block and returned `False, False` [3].

- To match to this behavior we return from the function when there is no image.

[1]: https://github.com/odoo/odoo/blob/4b2aaf2b711c9cfd8fd9f4a5915d6310064af6a9/odoo/tools/image.py#L83-L85

[2]: https://github.com/odoo/odoo/blob/39974cea6c37d21e21e3ed46a914d58f5ac16aad/addons/web/models/base_document_layout.py#L207

[3]: https://github.com/odoo/odoo/blob/4b2aaf2b711c9cfd8fd9f4a5915d6310064af6a9/addons/web/models/base_document_layout.py#L207-L211

sentry-7323084659

X-original-commit: 755fd5ec33e95877cb220b0d82560b14706bd55e