[FIX] web_editor: get image source while modifying it
If the user is using the `note` or any other module to add and modify images,
and they try to crop the image and apply the changes, they may face an error if
they try to crop it again without clicking on `apply changes` and instead click
somewhere outside the image.

steps to produce:
- Install `note`.
- Create a note, add an image in it.
- Click on image to crop it, select the portion you want to crop and then
  click on `Apply` to apply changes.
- Select the image again, click on crop icon and then click anywhere outside the
  image boundaries.

Error: `TypeError: 'bool' object is not subscriptable`.

Applying this commit will solve the issue because, after applying it, whenever
`modify_image` is called, `datas` will receive the proper source.

sentry-4185609374

closes odoo/odoo#132813

X-original-commit: 64633946812f9e41d387bf36692527edbae49c2a
Signed-off-by: David Monjoie (dmo) <dmo@odoo.com>