[FIX] website_sale: ensure product exists on reorder check
Versions
--------
- saas-17.4+

Steps
-----
1. Create a SO for non-user client;
2. add a product that isn't published on the website;
3. confirm SO;
4. create downpayment;
5. copy share SO link;
6. open link in private window.

Issue
-----
> 500: Internal Server Error
> Error while render the template
> ValueError: Expected singleton: product.product()

Cause
-----
Commit 59821eeef724 removed the creation of a "Down payment" product.
Before it, order lines were either of type `display_section` or they
had a `product_id` value. After the commit, a third option is for
`is_downpayment` to be true.

This regressed the fix to this issue added by 8a6ea0504c33f, as instead
of ensuring lines have a `product_id` value before checking if reorder
is allowed, it decided to check whether they're not of `display_type`.

Solution
--------
Ensure there's a `product_id` in `sale.order.line` instead of only
relying on the caller to filter those out beforehand.

opw-4711297

closes odoo/odoo#207857

X-original-commit: dfd0f4605600aef02a77bf50e88e1583b651d05d
Signed-off-by: Valentin Chevalier <vcr@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>