Cherry pick of ca434b29b4232d99325ffec8fe0f85ec9933f437 failed
stdout:
Auto-merging addons/web_editor/static/src/xml/editor.xml
CONFLICT (content): Merge conflict in addons/web_editor/static/src/xml/editor.xml

stderr:
19:55:50.135038 git.c:455               trace: built-in: git cherry-pick ca434b29b4232d99325ffec8fe0f85ec9933f437
error: could not apply ca434b29b42... [FIX] web_editor: allow dropdown in toolbar to move up
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: