[FIX] base: prevent deletion of default states
Steps to Reproduce:
- Install the Contact Module.
- Contact > Configuration > Fed. States
- Delete the 'Ceuta' state.
- Try to install the Accounting module.

Error:
ParseError: while parsing /home/odoo/src/odoo/20.0/addons/account/data/res_country_group.xml:4, somewhere inside

Cause:
The default Ceuta state is referenced by another module, so deleting it causes
a ParseError during module installation.

Fix:
This commit prevents the deletion of default states while allowing users
to delete custom states.

sentry-7753450969