[FIX] stock_account: prevent error when click on Adjust Valuation button
Currently, an error occurs when a user clicks on the Adjust Valuation button.

Steps to Reproduce:

 - Install the stock_account module.
 - Go to Receipts and create a receipt by adding a product with zero demand.
 - Go to Moves Analysis > switch to Kanban view and remove the Done filter.
 - Click on the selected product move > click the gear icon >
   click Adjust Valuation.

ZeroDivisionError: float division by zero.

After this commit, when the user clicks on the Adjust Valuation button,
the compute method runs to compute the current value details. When
it tries to calculate the unit price based on the move quantity and value,
and the quantity is zero, it raises the error[1].

This commit ensures that the current value details computation is skipped
when the move quantity is zero.

[1]: https://github.com/odoo/odoo/blob/0581b7fb6abc8e856cedf13254ba1f9d362d6d34/addons/stock_account/models/product_value.py#L59

sentry-7059220177

closes odoo/odoo#240285

X-original-commit: 8f2f3e79c0ec000b3d8ad3e6808d42f7619f491b
Signed-off-by: Steve Van Essche <svs@odoo.com>
Signed-off-by: Ashutosh Sharma (assh) <assh@odoo.com>