[FIX] website_sale: prevent error unpublished product add for wishlist
Currently, the error arises due to adding an unpublished product to wishlist
for multiple times.

Steps to reproduce:

- Install a 'website_sale_wishlist' module (with demo data).
- Open a website and go to the shop.
-  Add an unpublished product to the wishlist, then refresh the webpage and
again try to add that unpublished product to the wishlist, An error is generated
in the backend.

TypeError:  'NoneType' object is not subscriptable.

An issue arises when clicking on the 'add to wishlist' icon for unpublished
products. After refreshing the webpage, the 'add to wishlist' icon remains
enabled, allowing users to add the same unpublished product to their wishlist
multiple times. Consequently, duplicate records are inserted into the
'product_wishlist' table, An issue arises due to this.

To resolve this issue, the 'Add wishlist' button is now disabled for unpublished
products as we already filtered out the products from the wishlist that are
unpublished at [1].

Link [1]: https://github.com/odoo/odoo/blob/9685ebf6c7bed902086aa72993cde9ca9ce424ed/addons/website_sale_wishlist/models/product_wishlist.py#L25-L40

Sentry-5065439065