[FIX] {stock_,}maintenance: hide smart button for serial number
To reproduce the issue:
(Need stock. Enable demo data)
1. In Settings, edit user "Marc Demo":
   - Inventory: Nothing
2. Log in as Marc Demo
3. Maintenance > Equipment, click on an equipment

Error: an Access Error is displayed because a forbidden read
operation on `stock.lot`

Because of a condition on a smart button of the form view
https://github.com/odoo/odoo/blob/f1e217c5cb4934de4cb52d46136d89500d84d904/addons/maintenance/views/maintenance_views.xml#L373-L378
We execute the compute method of `match_serial`, which leads to
https://github.com/odoo/odoo/blob/61e586556028aff2f989f5bb90a94afffbd1ac96/addons/maintenance/models/maintenance.py#L166-L170
But the user does not have any access to `stock.lot` (cf step 1).

Indirectly related to sentry-5964505411
(cf discussion on PR of f1e217c5cb4934de4cb52d46136d89500d84d904)

X-original-commit: b33f28b6b1f062be50af66231989bfa71444e812