[FIX] mail: no crash on test test_04_meeting_view_tour avatarUrl
Before this commit, test `test_04_meeting_view_tour` could crash
non-deterministically with the following error:

```
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
Caused by: TypeError: Cannot read properties of undefined (reading 'avatarUrl')
    at DiscussSidebarCallParticipants.template
```

This happens because the template was reading a deep field in a JS
relation without guard in `rtc_session.channel_member_id.avatarUrl`.

When a rtc_session is known in client code, the `channel_member_id`
is not necessarily known, therefore code should guard it unless
context is explicit that this is known.

This commit adds optional guarding in the template to take into
account possibility to know rtc session without the related channel
member id.

Fixes runbot-error-233597