[FIX] sale_stock: fix msg argument in assertion
third positional argument is places not msg (which expects a number not a str)
https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertAlmostEqual

fixes errors like these:
 if round(abs(second-first), places) == 0:
 TypeError: 'str' object cannot be interpreted as an integer

and gives the intended message when assertion is errornous