[FIX] hr_expense,web: prevent traceback when attaching receipt after submission
Versions
- 18.0

Steps to Reproduce
1. Log in as Admin.
2. Install the Expenses module.
3. Go to Users > Select or Create an internal user:
   - Create an Employee for the user (if not already done).
4. Log in with this user.
5. Go to Expenses > Create a new expense.
6. Add a name and total, click "Create Report", then "Submit to Manager".
7. Go back to the expense and attempt to attach a receipt.

Issue
- A traceback is raised when trying to attach receipt after submitting report.

Cause:
- The user lacks write access while uploading reciept to the submitted expense ,
  triggering  an AccessError.
- Also, when setting the attachment, the method _message_set_main_attachment_id
  attempts to filter on mimetype, assuming it's always a string. If the mimetype
  is False this results in:
  `AttributeError: 'bool' object has no attribute 'endswith'.`

Solution:
- Added checks to ensure the user has write access to both the expense and its
  sheet before attaching documents..

opw-4760255