Cherry pick of e4cc562aaac9523018f4d487896781ee13247738 failed
stdout:
Auto-merging odoo/addons/base/tests/common.py
Auto-merging odoo/addons/base/tests/test_base.py
Auto-merging odoo/addons/base/tests/test_ir_actions.py
Auto-merging odoo/addons/base/tests/test_ir_attachment.py
Auto-merging odoo/addons/base/tests/test_views.py
CONFLICT (content): Merge conflict in odoo/addons/base/tests/test_views.py
Auto-merging odoo/addons/base/tests/test_xmlrpc.py
Auto-merging odoo/addons/test_main_flows/tests/test_flow.py
Auto-merging odoo/addons/test_new_api/tests/test_new_fields.py
Auto-merging odoo/tests/common.py

stderr:
12:41:00.868260 git.c:463               trace: built-in: git cherry-pick e4cc562aaac9523018f4d487896781ee13247738
error: could not apply e4cc562aaac9... [FIX] base: Make tests demo data independent
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: