[FIX] stock_dropshipping,purchase_stock: prevent traceback when mixing date type
**Steps to reproduce:**
* Install *sale_management*, *sale_subscription*, and *stock* modules.
* Go to *Settings* and enable *Dropshipping*.
* Create two products:
  * One *normal dropship* product.
  * One *dropship + subscription* product.
* Create a *Quotation*.
  Add both products to the order.
* Confirm the quotation.

**Observed behavior:**
* A traceback occurs during confirmation:
   File '/home/odoo/workspace/odoo19/odoo/addons/purchase_stock/models/stock_rule.py', line 159, in _run_buy
    date_planned = po.date_planned or min(v['date_planned'] for v in po_line_values)
TypeError: can't compare datetime.datetime to datetime.date

**Cause:**
* In *_run_buy*, the system computes the earliest *date_planned* using:
https://github.com/odoo/odoo/blob/4056fa8036ddad11c898cd775b7fa21ba4f8a5de/addons/purchase_stock/models/stock_rule.py#L159
* Subscription products set *date_planned* as *datetime.date*,
https://github.com/odoo/enterprise/blob/a88c64a224805d95b60a20c502428897655dba53/sale_subscription_stock/models/sale_order_line.py#L153
`current_period_start = self.order_id.last_invoice_date or
self.order_id.start_date or fields.Date.today()`
*  while normal products set *date_planned* as *datetime.datetime*.
https://github.com/odoo/odoo/blob/4056fa8036ddad11c898cd775b7fa21ba4f8a5de/addons/sale_stock/models/sale_order_line.py#L286

before min() It call  `_prepare_purchase_order_line_from_procurement`,
the value is assigned directly from `values.get('date_planned')`, and conversion
with `fields.Datetime.to_datetime()` only happens conditionally:
https://github.com/odoo/odoo/blob/98e6e929bf8e0c34ec77fb9d07ef253e0abf681c/addons/purchase_stock/models/purchase_order_line.py#L347-L350
As a result, some values remain `date` while others are `datetime`,

* When both are present in *po_line_values*, Python cannot compare the
  two types, causing the crash.

**Fix:**

So by moving the `fields.Datetime.to_datetime()` cast to the initial
assignment of `res['date_planned']`, so it is always a `datetime`
regardless of the source, and removing the now-redundant cast inside
the `if` block.

opw-6034079

closes odoo/odoo#256991

X-original-commit: ea5224cc5c52cba42cfb64e7963a323b49849360
Signed-off-by: Quentin Wolfs (quwo) <quwo@odoo.com>
Signed-off-by: Pawan Kumar Gupta (pkgu) <pkgu@odoo.com>