[FIX] tests framework: split big headless browser logs into chunks
It prevents random output errors on printing big logs. For example, js tour system
prints entire HTML code when js tour cannot find some element specified in a
tour step.

Example of the error log
========================

2019-10-03 09:29:32,813 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: _check_for_tooltip
2019-10-03 09:29:32,815 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - modal_displayed: 0
2019-10-03 09:29:32,816 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - trigger '.button.paymentmethod:contains("Credits")': 6
2019-10-03 09:29:32,817 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - visible trigger '.button.paymentmethod:contains("Credits")': 0
2019-10-03 09:29:32,819 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - extra_trigger '.button.paymentmethod:contains("Credits")': 6
2019-10-03 09:29:32,820 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - visible extra_trigger '.button.paymentmethod:contains("Credits")': 0
2019-10-03 09:29:32,969 5798 [1;32m[1;49mINFO[0m openerp_test odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: <body class="">
<div class="o_main_content"><div class="o_control_panel o_hidden"></div><div class="o_content"><div class="pos">
<div class="pos-topheader">
<div class="pos-branding">

.... about 50 000 chars are skipped .....

<span class="filters">
<i class="fa fa-filter"></i>
Filters
<Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking

Credits
=======

* code for splitting log is based on this answer:
  https://stackoverflow.com/a/18854817/222675

* size 16000 is chosen, because of this workaround for similar problem in
another project: https://github.com/boto/boto3/issues/894#issuecomment-262626535