[FIX] hr_holidays: prevent error when create a resource time off
Currently, An error occurs when creating a resource time off.

Step to produce:

- Install the 'hr_holidays' module.
- Enable debug mode.
- Go to Time Off / Configuration / Time Off Types, And delete `Sick Time Off`.
- Go to Settings / Technical / Resource / Resource Time Off, and create a new
record.
- Add a Time Off Request with the following conditions:
The start date is before today's date, end date is after today's date, And state
is set to Draft.
- Try to save a Resource Time Off record.

ValueError: External ID not found in the system: hr_holidays.holiday_status_sl

An error occurs when the system tries to retrieve an external ID of the
'Sick Time Off' at [1], but it is not available.

Link [1]: https://github.com/odoo/odoo/blob/1303193386665d120ccb5d0045ee984337af0826/addons/hr_holidays/models/resource.py#L67

To handle this issue, add 'raise_if_not_found=False' in ref() argument if the
external ID of the 'Sick Time Off' is not available.

Sentry-6320807644