[FIX] mail: prevent error when creating a channel with guest members
Currently, an error occurs when creating a channel that includes guest members.

Steps to Reproduce:
 - Install the mail module.
 - Go to Channels > New.
 - Fill in the channel name and Under Members, add a member with a guest,
   and save.

KeyError: 'partner_id'

This error occurs when a user creates a channel and adds a guest in the
Members section. This error occurs after [this commit]( https://github.com/odoo/odoo/commit/ad612321bcafe6dfdaabf3aa37f26af364185a69),
where the partner_id and guest_id fields dynamically become readonly [1],
so that if only the guest is entered, the partner becomes readonly,
and when the record is created, the partner_id key does not exist, and
raises the error [2].

This commit ensures that the partner_id is accessed only if it is present
in the record.

[1]: https://github.com/odoo/odoo/blob/5bddf9bfb634d09d3264e4fe4734d75f1083775a/addons/mail/views/discuss_channel_views.xml#L87-L88

[2]: https://github.com/odoo/odoo/blob/5bddf9bfb634d09d3264e4fe4734d75f1083775a/addons/mail/models/discuss/discuss_channel.py#L235

sentry-6791956423

closes odoo/odoo#222211

Signed-off-by: Sébastien Theys (seb) <seb@odoo.com>