[FIX] account_check_printing: prevent error on non-numeric next check number
Currently, an error occurs when a user sets a non-numeric value as the
journal's next check number.

Steps to Reproduce:
 - Install the account_check_printing module with demo data.
 - Go to Invoicing > Configuration > Accounting > Journals.
 - Open the bank journal.
 - In the Outgoing Payments tab > Enable Manual Numbering.
 - Set the next check number to a non-numeric value (e.g. FA1234) and save.

ValueError: invalid literal for int() with base 10: 'FA1234'

After this commit, the next check number is converted to an integer without
first validating that it contains only numeric characters [1]. Since the value
can be non-numeric, converting it directly to an integer raises the error.

This commit ensures that the next check number is converted to an integer
only after verifying that it contains numeric characters only.

[1]: https://github.com/odoo/odoo/blob/00dd75f345d7f5ddb04cecf52eca07e5a22c7d3c/addons/account_check_printing/models/account_journal.py#L57-L61

sentry-7498755988

closes odoo/odoo#268095

X-original-commit: f894d56d46902d4f5ae8c1a86f8e73f94ec2a73c
Signed-off-by: Laurent Smet (las) <las@odoo.com>