[FIX] link_tracker:  prevent error while sending mail with a buttons without URL
Currently, an exception is generated when the user sends a template to a mailing
that contains icons like Facebook, LinkedIn, etc.

Steps to produce an exception:
1. Create a database without demo data > install 'Email Marketing'.
2. Go to Email Marketing > Create New > Select the `Welcome Message` template.
3. Click 'Send' >> An error will occur in the log, and there is nothing to send.

Error: `AttributeError: 'NoneType' object has no attribute 'startswith'`

This is because at [1], we don't have `href` in 'link_node', so we receive
`False` in 'original_url', and as a result, it generates an error while
accessing 'original_url.startswith'.

With the recently refactored code with commit [2], line [1] was added.
Before this change, Line [3] was filtering out elements from `html` that
did not have 'href'.

This commit will fix the above issue by not processing to find the absolute
URL if we do not have `original_url`.

[1]- https://github.com/odoo/odoo/blob/b6629bbdb53d9a4bacee2032190e30a848bb6d6d/addons/link_tracker/tools/html.py#L25
[2]- https://github.com/odoo/odoo/commit/6349051e5e4442cfabc899520c5708081dc0be31
[3]- https://github.com/odoo/odoo/blob/c9644a086b294e69b69e52e8ccfd5292bde815da/addons/link_tracker/models/mail_render_mixin.py#L39

sentry-5140192785

closes odoo/odoo#163532

X-original-commit: 9d3808c8c5acb585c4ad12f31c16738bb2570835
Signed-off-by: Thibault Delavallee (tde) <tde@openerp.com>