[FIX] website: prevent invalid domain paths containing '.' or '..'
This error occurs when the domain URL contains '.' or '..' segments.

Steps to reproduce:
- Install 'website' module
- Settings > Domain > Add URL with '/../' (eg: https://power.odoo.com/OA_HTML/help/../ieshostedsurvey.jsp)
- Open 'Website' module

Traceback:
ValueError: Dot segments are not allowed

This issue occurs because at [1], we intentionally raise a 'ValueError' to
prevent the use of '.' or '..' in the URL path. In Chrome, the sequence '/../'
is interpreted as a 'back path' AFAIK.
For example:
'http://localhost:8069/odoo/action-218/../2 → http://localhost:8069/odoo/2'

This commit fixes the issue by validating the domain URL path. If it contains
'.' or '..', a 'ValidationError' is raised to clearly inform the user that the
entered URL is invalid.

[1]: https://github.com/odoo/odoo/blob/dc6dd927faea1f4501d6c50c586d5ea46bd1fc95/odoo/tools/urls.py#L72-L73

sentry-6932797319

closes odoo/odoo#230917

Signed-off-by: Soukéina Bojabza (sobo) <sobo@odoo.com>