[FIX] l10n_eu_oss: prevent error when account code is missing
This error occurs when both companies are selected and 'Refresh tax mapping' is
clicked under Taxes.

Steps to reproduce:
- Install 'l10n_eu_oss' application
- Create a NEW Company with EU Localizations > Switch to it
- Now select both Companies
- Invoicing > Configuration > Settings > Taxes > `Refresh tax mapping`

Traceback:
TypeError: expected string or bytes-like object, got 'bool'

At [1], this error occurs because clicking 'Refresh tax mapping' attempts to
retrieve the 'Tax Payable' account code from both companies. In this case, the
code from the parent company is retrieved correctly, but the child company's
code is missing (i.e., False). As a result, an error is raised during the
process.

This commit fixes the above error by ensuring the code is fetched within the
appropriate company context.

[1]- https://github.com/odoo/odoo/blob/4cadc407c00dfe93af943c70d6d3b07c5ae01929/addons/l10n_eu_oss/models/res_company.py#L46-L49

sentry-6611611716