[FIX] website: unknown action id for builderaction
steps to reproduce:

1. Drop facebook snippet.
2. Click on it.
3. Traceback

The DataAttributeListAction and CheckFacebookLinkAction were not
registered correctly in the plugin, due to a mismatch in the action IDs.

Changes made:
"checkFacebookLinkAction" --->  "checkFacebookLink"

"dataAttributeListAction" ---> "dataAttributeList"

resolves issue:
Error: Unknown builder action id: dataAttributeListAction
    at BuilderActionsPlugin.getAction
    at usePrepareAction
    at useClickableBuilderComponent
    at BuilderCheckbox.setup
    at new ComponentNode