[FIX] base_import: prevent error when importing utf-16 CSV file
Currently, an error occurs when importing CSV files encoded in utf-16.

Steps to reproduce:
- Install the `account_bank_statement_import_csv` module.
- Open invoicing and upload file [1] in Bank transactions.
- Change the encoding to `utf-16` and click `test`.

Error:
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x0a in
position 376: truncated data

Root Cause:
At [2], the CSV data is decoded strictly with the specified encoding. When
decoding detects incomplete or unexpected byte sequences, python raises an error.

Fix:
This commit ensures raising a warning, improving the error message clarity.

[1]:
https://drive.google.com/file/d/14thHRN210aeY8fcUBAb01PniVrd7QHer/view?usp=sharing

[2]:
https://github.com/odoo/odoo/blob/67503c0ce7ede8373800caa0a12203d271b7f1ae/addons/base_import/models/base_import.py#L544

sentry-6864546266