[FIX] website_sale: handle invalid literal issue for category in product page
When a user search product on a website and click on it. After that modify the
URL  like '/shop/warranty-30?category=string', instead of the
'/shop/warranty-30?category=1'.  in that case, the trace back will be generated.

Steps to produce an issue:
- Install the website_sale module.
- Go to the Website > Shop, search for a product, and then click on it.
- Now change the URL  eg.  '//shop/warranty-30?category=any string.
After that, a traceback will be generated.

Error: invalid literal for int() with base 10: 'aze'

If applied, this commit will solve the issue of the invalid literal for
integer, when the user enters the URL like '/shop/warranty-30?category=string',
instead of the '/shop/warranty-30?category=1'.

Sentry-4084912758