[FIX] website: hide publish and unpublish actions
If user tries to publish or unpublish the forum post from forum posts list view,
a traceback will appear.

Steps to reproduce the issue:
- Install website_forum
- Configure website
- Go to Website -> site -> Forum Posts
- Select any post -> Action -> 'Publish' or 'Unpublish'

Error: A traceback appears:
"ValueError: Invalid field 'is_published' on model 'forum.post'"

https://github.com/odoo/odoo/blob/551685368971161975d64f480e9bec326db8931e/
addons/website/static/src/components/views/page_list.js#L69
Here we will receive 'forum.post' in this.props.resModel.
is_published field is not present in the 'forum.post' model,
So it will lead to above traceback.

sentry-4256037237

X-original-commit: d635d05d99b8492d738918a432fddcc9a189c8c0