[FIX] account: prevent a error when create an accrued expense entry
Currently, an error occurs when creating an accrued expense entry with 0.0
amount total.

Step to produce:

- Install the 'account_accountant' and 'purchase' module. (with demo data)
-  Create a purchase order, set a 'Vendor' and product whose price is 0.0.
- Open an 'Accrued Expense Entry' through the action button.
- Add an amount and try to 'CREATE ENTRY'.

ZeroDivisionError: float division by zero

An error occurs when the system tries to divide a float number by 0.0 due to the
total amount of purchase is 0.0 at [1]

Link [1]: https://github.com/odoo/odoo/blob/ace8768a36badd28c4be6b56acf526f8ea53c8f5/addons/account/wizard/accrued_orders.py#L218

To handle this issue, we have to give '1' if the amount total of purchase is 0.0.

sentry - 5560340833