[FIX] stock: prevent error when running the Routes server action
Currently, an error occurs when the user runs the Routes server action.

Steps to Reproduce:

 - Install the stock module.
 - In developer mode, go to Server Actions and open the Routes
   server action record.
 - Click Create Contextual Action.
 - Go to Products, select one or multiple in list view, and click
   Routes from the Action menu, or run it from the form view.

ValueError: TypeError("object of type 'bool' has no len()") while evaluating
'action = model.action_open_routes_diagram()'

This server action is originally called from the product form view
using the View Diagram button [1]. However, when it is created as a
contextual action, it can also be called from the list or form view,
where default_product_id and default_product_tmpl_id are not
included and products is False [1] , which raises the error here [2].

This commit makes the product variable fallback to an empty
product.product recordset, which prevents the traceback.

[1]: https://github.com/odoo/odoo/blob/ea56382f804e494a86a72dab02a26134ef358c50/addons/stock/views/product_views.xml#L136-L138

[2]: https://github.com/odoo/odoo/blob/ea56382f804e494a86a72dab02a26134ef358c50/addons/stock/models/product.py#L1041-L1056

[3]: https://github.com/odoo/odoo/blob/ea56382f804e494a86a72dab02a26134ef358c50/addons/stock/models/product.py#L1047

sentry-7466002694