[FIX] account: prevent error on invoice when removing currency
Currently, an error occurs on an invoice when user selects a payment term and
removes the currency.

Steps to replicate:
- Install account, turn on multiple currencies and open invoices.
- Create a new invoice > add a line > add a customer > save.
- Select payment term as `30% Now, Balance 60 Days` > Remove the currency.

Error:
```
ValueError: Expected singleton: res.currency()
```

Cause:
- This error only occurs when the selected payment term contains at least two
  due term lines [1].

- When the selected payment term has atleast two lines the check [1] assigns
  `on_balance_line` as  false and the `else` block is evaluated where currency
  being an empty recordset (as the user removed it) causes the error from [line]
  when trying to perform `round()` on an empty res.currency recordset.

Solution:
- As the currency is a required field, user will not be able to save the record
  until a currency is assigned.

- Used journal's currency or company's currency as a fallback when computing
  payment terms if the current currency is empty.

[1]: https://github.com/odoo/odoo/blob/177002c0aca95de2de6458bb65bedf5c74541ac0/addons/account/models/account_payment_term.py#L229

[line]: https://github.com/odoo/odoo/blob/177002c0aca95de2de6458bb65bedf5c74541ac0/addons/account/models/account_payment_term.py#L240

sentry-7569922293