[FIX] hr_holidays: prevent error when validity period is removed
An error occurs if the Validity Period is removed while creating a new
allocation.

Steps to reproduce:
- Install the 'hr_holidays' module
- Time Off > My Time > My Allocation
- Open New and remove the 'Validity Period'

Traceback:
AttributeError: 'bool' object has no attribute 'strftime'

This commit ensures that changing the date won't cause an error, but instead
will display a warning upon saving the form, as it is a required field.

sentry-6709097746

closes odoo/odoo#216015

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>