[FIX] website: s_floating_blocks new card grid resizable
Scenario:

- add a "Cards" snippet (s_floating_blocks)
- click on "Add New" cards
- resize vertically the grid containing "Card Title"

Result: traceback error is shown

  TypeError: Cannot read properties of undefined (reading 'substring')
   at iframeWindowMouseUp (snippets.options.js:4799:1)

Cause: the code assume that there is always a g-col-* class and it is
there on demo cards, as well as if the grid is resized horizontally, but
it's not there when adding a new card.

Fix: adding the class the the new card template.

opw-5027818