[FIX][modules] Choose the right addons path.
Right now, if you have in your configuration addon paths that start with the same words, it could happen that this method returns a wrong value.

For example, let's assume you have these paths:

- `/opt/odoo/web`
- `/opt/odoo/website`

And let's assume you install a module called `website_myaddon` found in `/opt/odoo/website`, and it contains a file `views/templates.xml` that define a view with XMLID `website_myaddon.index`.

The `website_myaddon.index` view record will have an `arch_fs` value of `site/website_myaddon/views/templates.xml`.

If you now try to execute Odoo with `odoo.py --dev` option enabled, it will try to find a file called `website_myaddon/views/templates.xml` inside the `site` module, which does not exist, so it will yield an error such as:

```
INFO demo openerp.modules.loading: loading 55 modules...
INFO demo openerp.modules.module: module website_portal_v10: creating or updating database tables
INFO demo openerp.modules.loading: loading website_portal_v10/views/templates.xml
INFO demo openerp.addons.base.ir.ir_translation: module website_portal_v10: loading translation file (es) for language es_ES
INFO demo openerp.tools.translate: loading /opt/odoo/extra-addons/website/website_portal_v10/i18n/es.po
WARNING demo openerp.modules.module: module site: module not found
ERROR demo openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 176, in load_module_graph
    registry['ir.ui.view']._validate_module_views(cr, SUPERUSER_ID, module_name)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 1191, in _validate_module_views
    if not self._check_xml(cr, uid, [vid]):
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 292, in _check_xml
    view_arch = etree.fromstring(encode(view.arch))
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 829, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 927, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3298, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3228, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3419, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/site-packages/openerp/osv/fields.py", line 1495, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 159, in _arch_get
    arch_fs = get_view_arch_from_file(fullpath, view.xml_id)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 96, in get_view_arch_from_file
    doc = etree.parse(filename)
  File "lxml.etree.pyx", line 3197, in lxml.etree.parse (src/lxml/lxml.etree.c:64816)
  File "parser.pxi", line 1596, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:92968)
TypeError: cannot parse from 'bool'
ERROR demo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/extra-addons/core/web/controllers/main.py", line 900, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/extra-addons/core/web/controllers/main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 176, in load_module_graph
    registry['ir.ui.view']._validate_module_views(cr, SUPERUSER_ID, module_name)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 1191, in _validate_module_views
    if not self._check_xml(cr, uid, [vid]):
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 292, in _check_xml
    view_arch = etree.fromstring(encode(view.arch))
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 829, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/openerp/fields.py", line 927, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3298, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3228, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 3419, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/site-packages/openerp/osv/fields.py", line 1495, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 159, in _arch_get
    arch_fs = get_view_arch_from_file(fullpath, view.xml_id)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_ui_view.py", line 96, in get_view_arch_from_file
    doc = etree.parse(filename)
  File "lxml.etree.pyx", line 3197, in lxml.etree.parse (src/lxml/lxml.etree.c:64816)
  File "parser.pxi", line 1596, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:92968)
TypeError: cannot parse from 'bool'
```

This patch makes it choose the right addons path always. Now run `odoo.py --dev` and it works.