[FIX] mail: Set 'email_from' False if user don't have an email address
Right now, when we create a new user and not set an email address and give some rights to him/her. Now login with that user and as per the rights when he/she is trying to create any record, a traceback occured regarding attributeError because inside the code, user must have an email address and system will try to do operation on that. If user don't have an email address and as per code 'formataddr((author.name, author.email))' will be called where author.email is False and because of these traceback will be ocuured like "AttributeError: 'bool' object has no attribute 'encode'". So, while set the value of key 'email_from' added a condition that if user don't have an email address then 'False' otherwise call 'formataddr' for user's name and email.

Related to task #1823990