[FIX] base,tools: t-call attribute no translate whitelist
Scenario: enable second language on website, go to /shop, edit
translation => error 500 is shown with error:

   SyntaxError: invalid syntax (<>, line 1)

Cause: since eb6e88a25050fff2bd09317739dd51ba451450df parameters are set
on the t-call tags, but this can conflict with attribute tag that are
translatable. In the case of /shop, there is:

  <t t-call="website_sale.search" placeholder="placeholder"/>

that is transformed to:

  <t t-call="website_sale.search"
     placeholder="<span data-oe-model=...>placeholder</span>"/>

but this is an invalid value, t-call attribute should only be translated
if they have the suffix .translate and should not be auto-translated.

opw-5121074

closes odoo/odoo#230881

X-original-commit: f1e17fa554afb0db7e1e5cf0090a17dee22b7a98
Signed-off-by: Nicolas Lempereur (nle) <nle@odoo.com>