[FIX] core: give fallback value of UTC if there is no tz in employee
Currently a traceback occurrs from multiple places when there is no
tz for employee and used in the `pytz.timezone` method.

https://github.com/odoo/enterprise/blob/517983ae9deec37795eb11522134a1f5ade31e9b/hr_payroll/wizard/hr_payroll_payslips_by_employees.py#L131

For instance, if there is no tz in resource_calendar_id, it leads to a
traceback.

Error: "'bool' object has no attribute 'upper'"

This error is occurring from the pytz.timezone library that if there is no name,
it leads to the above the error.

To resolve this issue we can give a default value of `UTC` is there is no name.
which makes the code more robust.

sentry-6134147853, 6119911834