Cherry pick of 49c982d9fc66074b507bb689850732084e483a41 failed
stdout:

stderr:
error: could not apply 49c982d9fc6... [FIX] payment_stripe_sca: better error handling
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'