[FIX] account: prevent error while printing tax return
This error occurs when `o.tax_totals` returns False, causing an AttributeError
when accessed in the `QWeb template`.

- Install module `accountant`.
- Go to `Reporting` and open `Tax Return`.
- Open `Closing Entry` and `Print`.

AttributeError: 'bool' object has no attribute 'get'

The error occurs because `o.tax_totals` returns `False` instead of a dictionary
causing an AttributeError when accessed in the `QWeb template`.

The error is resolved by adding a check to ensure o.tax_totals is not false
before accessing its attributes,

sentry-6115648026