[FIX] website: sitemap method ok with redirect 308
Scenario:

- create a redirect 308 from route with a sitemap method
(eg.  /website/version)
- go to /sitemap.xml (you might need to delete sitemap in attachment
before)

Result: you get a 500 error, with this traceback in server logs:

…
File "/Users/odoo/src/odoo/17.0/addons/website/models/website.py", line 1333, in _enumerate_pages
if rule.endpoint.func.__func__ in sitemap_endpoint_done:
AttributeError: 'functools.partial' object has no attribute '__func__'. Did you mean: '__doc__'?

Issue: since 239ae1b457683fdfaa2b2f4abb01a6dad9ecdb46 we use the
function that partial links to to duplicate a route, but there could be
two level of partial (partial of a partial) in case of a redirect.

Fix: take a second level of partial (from the redirection and not the
route) when handling duplicates routes.

opw-4594629
opw-4614216
opw-4628703