[FIX] mail: no crash when loading chathub on logging in as diff user
Before this commit, when logging in as Demo user with a direct chat,
logging out + logging in with Mitchell Admin would crash with the
following error:

```
TypeError: can't access property "imStatusUI", this.channel.correspondent is undefined
```

This happens because this attempts to restore the direct chat in chat
window. Normally this shouldn't happen thanks to being unable to
fetch inaccessible channels, however Mitchell Admin is the admin of
DB thus can fetch the channel data. The crash comes from computation
of `correspondent` that is `undefined` because it can't determine a
correspondent from the Point of view of Mitchell Admin, and the
template isn't defensive against missing a `correspondent` in a
direct chat.

One solution could have been to support opening of direct chat, but
this implies fixing a lot of complex issues, such as:

- Mitchell Admin can't use composer because this attempts to add a
member but there's a contraint for direct chat to have at most 2
members
- This direct chat looks like a group chat without a name, we can
guess this is a direct chat only because of broken avatar and the
start message in message list stating this is a direct chat
- Several other actions show weird behavior, like "Invite People"
ignoring people in the chat

This commit fixes the issue by ignoring the restore of chat in chat
hub for direct chats that current user is not a member.

closes odoo/odoo#277199

Signed-off-by: Alexandre Kühn (aku) <aku@odoo.com>