Fix uncaught exception if wkhtmltopdf is broken
The "report" addon assumes re.search() always succeeds, resulting in the
unhelpful "AttributeError: 'NoneType' object has no attribute 'group'".
This provides a clear log message so the user can find the problem.

For example, wkhtmltopdf is likely to be installed from outside normal
distribution repositories due to Odoo's need for the latest version with
Qt patches, so it may be prone to shared library loading errors.